# gen_phase12_14.py
from helper import format_lesson

def generate_phase12():
    out = []
    out.append("""## Phase 12: Autonomous AI Agents, Multi-Agent Systems & Tool Orchestration
**Target Duration**: 4 Weeks (Lessons 12.1 – 12.30)
**Core Focus**: Cognitive agent architectures (ReAct, Plan-and-Solve, Reflexion), state graph execution with LangGraph, durable checkpointing and time-travel, Human-in-the-Loop (HITL) workflows, schema-validated tool engineering, sandboxed execution environments (Docker/gVisor/Wasm), multi-agent supervisor hierarchies, and agent trajectory evaluations.

---
""")

    p12_data = [
        (1, "Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains",
         "Phase 10, Lesson 10.2",
         ["The spectrum of autonomy: deterministic scripts vs prompt chains vs autonomous agents with dynamic branching",
          "Core components of an agent: Brain (LLM), Memory (short-term working state & long-term episodic memory), Tools, and Planning",
          "The Sense-Plan-Act cycle: perceiving environment feedback, updating internal beliefs, formulating plans, and executing actions",
          "Bounded rationality in LLM agents: token horizon limits, stochastic decision making, and cascading failure propagation",
          "Deterministic guardrails on non-deterministic models: constraining agent state transitions with state machines",
          "Architecture overview: designing agent workflows that guarantee business logic invariants while leveraging model flexibility"],
         "Granting an un-constrained agent open loop execution without state boundaries, burning thousands of dollars in infinite tool loops.",
         "Draft an architectural state chart comparing linear prompt chaining vs dynamic cyclic agent state execution.",
         "CodeAgent: Agent architectural specification."),

        (2, "Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion",
         "Lesson 12.1",
         ["ReAct (Yao et al.): interleaving Reasoning ('Thought'), Action ('Tool Call'), and Observation ('Environment Feedback')",
          "Failure modes of pure ReAct: local greedy planning, losing track of high-level goals, and cycling between similar actions",
          "Plan-and-Solve (Wang et al.): generating an explicit multi-step plan upfront, then executing sub-tasks systematically",
          "Reflexion (Shinn et al.): verbal self-reflection, evaluating task outcomes, writing critique into episodic memory, and retrying",
          "Tree-of-Thoughts (ToT) (Yao et al.): exploring multiple reasoning paths concurrently with backtracking and lookahead evaluation",
          "Selecting the right architecture: matching task complexity to cognitive overhead and latency budgets"],
         "Using pure ReAct on complex 20-step software engineering tasks, causing the agent to get stuck in myopic 3-step loops.",
         "Implement a Reflexion agent harness that critiques its own failed Python code executions and succeeds on the second attempt.",
         "CodeAgent: Cognitive loop controller."),

        (3, "Tool Engineering I: Dynamic Schema Generation & Pydantic Validation",
         "Phase 1, Phase 10",
         ["Tools as typed RPC interfaces: exposing functions, APIs, and databases to LLMs via JSON Schema definitions",
          "Writing clear, unambiguous tool descriptions: specifying parameter types, required fields, constraints, and return schemas",
          "Pydantic schema generation: using `TypeAdapter` and Pydantic models to automatically generate clean OpenAPI/JSON schemas",
          "Input validation and sanitization: intercepting invalid LLM tool arguments before execution and returning structured errors",
          "Handling missing arguments: implementing conversational clarification loops when required tool parameters are omitted",
          "Security threat modeling for tools: preventing privilege escalation, SQL injection, and command injection via tool parameters"],
         "Providing vague tool descriptions ('executes stuff'), causing the LLM to hallucinate invalid parameter names and argument types.",
         "Build a tool registry library in Python that dynamically exports Pydantic-validated callable tools to OpenAI and Anthropic formats.",
         "CodeAgent: Core tool registry engine."),

        (4, "Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery",
         "Phase 4, Lesson 12.3",
         ["The unreliability of external environments: handling network timeouts, API rate limits, and non-deterministic tool failures",
          "Idempotent tool design: ensuring that duplicate tool executions do not produce unintended side effects (e.g. double charging)",
          "Structured error returns: why raising Python exceptions crashes agents; formatting errors as informative feedback strings",
          "Designing actionable error messages: providing the LLM with exact guidance on how to fix invalid inputs upon failure",
          "Execution timeouts: wrapping tool executions with strict `asyncio.timeout()` boundaries to prevent hung external processes",
          "Tool output truncation: summarizing massive tool return payloads (e.g. 50MB file reads) to prevent blowing the context window"],
         "Allowing an unhandled tool exception to bubble up and crash the entire agent runtime, losing all conversational session state.",
         "Implement a resilient tool execution wrapper supporting timeouts, exponential retries, and informative error formatting for LLMs.",
         "CodeAgent: Resilient tool execution pipeline."),

        (5, "Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory",
         "Phase 10, Lesson 12.1",
         ["Taxonomy of agent memory: Working Memory (active context), Episodic Memory (past task experiences), Semantic Memory (knowledge)",
          "Managing Working Memory: rolling window message history, summarization compression, and token budget management",
          "Episodic Memory with Vector Stores: embedding past execution trajectories, indexing task outcomes, and retrieving relevant past solutions",
          "Entity Memory: maintaining a structured JSON knowledge graph of extracted user preferences, project configurations, and facts",
          "Memory consolidation: background tasks that distill daily conversation logs into concise long-term user profiles",
          "Privacy and memory purging: implementing GDPR-compliant memory forgetfulness APIs to delete user history on demand"],
         "Unbounded message history growth causing context window overflow and astronomical API token costs on long-running tasks.",
         "Build a hybrid agent memory system combining in-memory message history with vector-indexed episodic retrieval of past task logs.",
         "CodeAgent: Multi-tiered agent memory architecture."),

        (6, "LangGraph Foundations: State Graphs, Nodes & Directed Edges",
         "Phase 3, Lesson 12.1",
         ["Why linear DAGs (LangChain) fail for autonomous agents: agents require loops, conditional cycles, and dynamic branching",
          "LangGraph core mental model: agents as stateful multi-actor graphs; computation as a sequence of state transitions",
          "The `StateGraph` object: defining global typed state schemas using `TypedDict` or Pydantic models",
          "Nodes as pure transformation functions: `Node(state) -> PartialStateUpdate`; taking state and returning incremental changes",
          "Edges: Normal edges (unconditional transitions $A \\to B$) vs Conditional edges (routing based on state values)",
          "The compile step: compiling `StateGraph` into an executable `Pregel` runnable with graph validation and cycle checks"],
         "Designing cyclic graphs without explicit termination conditions, resulting in infinite execution loops that drain API credits.",
         "Construct a basic LangGraph state machine with 3 nodes, conditional routing, and verified termination on reaching target state.",
         "CodeAgent: Foundational LangGraph workflow orchestration."),

        (7, "LangGraph State Management: Reducers, Channels & Immutability",
         "Lesson 12.6",
         ["State channel architecture: how LangGraph manages concurrent updates to individual fields within global state",
          "The overwrite default: why standard state fields overwrite previous values unless explicit reducers are configured",
          "Reducer functions: defining custom aggregation logic (e.g. `operator.add` for appending to lists, custom dictionary merging)",
          "The `add_messages` reducer: handling message lists with automatic deduplication based on unique message IDs",
          "State immutability: treating state as immutable snapshots to prevent side-effect bugs across parallel node executions",
          "Annotated type definitions: using `typing.Annotated[list[BaseMessage], add_messages]` for expressive schema declarations"],
         "Accidentally overwriting the entire conversation message history with the latest single message due to a missing reducer annotation.",
         "Build a custom LangGraph state schema featuring list-append reducers, numerical accumulation reducers, and dictionary mergers.",
         "CodeAgent: State schema and channel reducer suite."),

        (8, "LangGraph Execution Engine: Supersteps, Concurrency & Pregel Internals",
         "Lesson 12.6, Lesson 12.7",
         ["Pregel algorithm (Google): bulk synchronous parallel (BSP) graph processing model underlying LangGraph execution",
          "The Superstep concept: discrete execution rounds where all active nodes execute in parallel on current state snapshot",
          "Barrier synchronization: waiting for all active nodes in the current superstep to complete before applying state updates",
          "Deterministic state updates: resolving conflicting updates to the same channel using deterministic reducer ordering",
          "Streaming graph execution: streaming node updates (`stream_mode='updates'`) vs streaming full values vs streaming LLM tokens",
          "Recursion limits: configuring `recursion_limit` (default 25) to catch accidental infinite loops safely"],
         "Attempting to share mutable memory between two nodes executing concurrently in the same superstep, causing race conditions.",
         "Execute a multi-branch parallel LangGraph workflow; inspect superstep execution logs and verify barrier synchronization.",
         "CodeAgent: Concurrent workflow execution engine."),

        (9, "Durable Checkpointing & State Persistence with PostgreSQL",
         "Phase 4, Lesson 12.7",
         ["Why in-memory agents fail in production: server restarts, container scaling, and deployment crashes wipe out active tasks",
          "LangGraph Checkpointer abstraction: `BaseCheckpointSaver` interface, saving state snapshots after every superstep",
          "Checkpointer backends: `MemorySaver` (ephemeral testing) vs `PostgresSaver` / `AsyncPostgresSaver` for enterprise persistence",
          "Thread IDs: partitioning execution state by unique `thread_id` to isolate multi-tenant user sessions",
          "Database schema for checkpointing: checkpoints table, checkpoint writes table, and serialization of state blobs (Pickle / JSON)",
          "Resilience against crashes: resuming an interrupted agent task seamlessly from the exact last completed superstep"],
         "Using ephemeral in-memory checkpointing in production, losing customer task progress whenever a worker pod restarts.",
         "Configure `AsyncPostgresSaver` on PostgreSQL; execute a 10-step agent workflow, kill the process mid-run, and resume seamlessly.",
         "CodeAgent: Enterprise PostgreSQL state checkpointing engine."),

        (10, "Time-Travel Debugging: State Replay, Forking & History Inspection",
         "Lesson 12.9",
         ["The power of durable checkpointing: full chronological history of every state snapshot across all supersteps",
          "Inspecting thread history: `graph.get_state_history(config)` returning past states, node outputs, and timestamps",
          "Time-travel debugging: rewinding an agent to a past checkpoint before a hallucination or bad tool call occurred",
          "State forking: branching execution from an arbitrary historical checkpoint with modified state parameters to explore alternate paths",
          "Replaying trajectories: re-running past agent runs with zero code changes to verify determinism or debug edge cases",
          "Visualizing execution trees: rendering past execution states and branch points in administrative debugging interfaces"],
         "Attempting to fork state without creating a new checkpoint config, accidentally overwriting existing historical records.",
         "Build a time-travel CLI utility that inspects past agent supersteps, rewinds to step 3, modifies state, and resumes execution.",
         "CodeAgent: Time-travel state inspection and replay module."),

        (11, "Human-in-the-Loop (HITL) I: Interrupts, Pausing & State Modification",
         "Lesson 12.9, Lesson 12.10",
         ["Why autonomous agents require human oversight: high-risk actions (financial transfers, file deletion, production deployments)",
          "LangGraph Interrupt mechanism: `interrupt()` function pausing graph execution and persisting state to checkpointer",
          "Pre-execution breakpoints: configuring `interrupt_before=['deploy_node']` to halt execution automatically before sensitive operations",
          "Post-execution breakpoints: `interrupt_after=['generate_sql']` to allow human review of generated SQL before execution",
          "Resuming execution: sending human approval or updated state inputs via `Command(resume=...)` to continue the paused graph",
          "Modifying state during interrupt: allowing human operators to edit the agent's proposed plan or tool arguments before continuation"],
         "Resuming an interrupted graph without supplying required resume payloads, causing the agent to hang indefinitely in pause state.",
         "Implement a Human-in-the-Loop approval workflow that pauses before a mock destructive action, accepts human edits, and resumes.",
         "CodeAgent: Human-in-the-loop review and approval gate."),

        (12, "Human-in-the-Loop (HITL) II: Dynamic Review Queues & Webhook Resumption",
         "Phase 5, Lesson 12.11",
         ["Architecting enterprise review systems: routing paused agent tasks into shared administrative approval queues",
          "Webhook integration: notifying reviewers via Slack, email, or webhook when an agent requests human authorization",
          "Handling reviewer latency: managing tasks paused for hours or days without consuming server memory or worker threads",
          "Reviewer role-based access control (RBAC): verifying that the approver possesses appropriate authorization privileges",
          "Timeout policies on human reviews: defining automated fallback actions (cancel, escalate, or default to safe option) on review expiration",
          "Audit logging for human interactions: recording who approved what action, exact diffs applied, and timestamped rationale"],
         "Holding synchronous HTTP connections open while waiting for human review, exhausting server sockets and timing out.",
         "Build an asynchronous review queue API backed by PostgreSQL where reviewers approve or reject paused agent executions via REST.",
         "CodeAgent: Enterprise asynchronous review and authorization system."),

        (13, "Sandboxed Code Execution I: Security Risks & Threat Modeling",
         "Phase 0, Phase 5",
         ["The supreme danger of code-generating agents: running untrusted, model-generated Python/Bash code on host infrastructure",
          "Attack vectors: arbitrary remote code execution (RCE), filesystem exfiltration (`cat /etc/shadow`), fork bombs, reverse shells",
          "Why naive sandboxing fails: `eval()`, `exec()`, AST filtering, and monkey-patching `__import__` are trivially bypassed in Python",
          "Bypassing Python AST filters: using `object.__subclasses__()` traversal to reach `os.system` without explicit imports",
          "Network exfiltration threats: untrusted code making HTTP requests to external attacker servers with environment variables and secrets",
          "Security boundaries: process-level vs container-level vs virtual machine-level vs WebAssembly isolation"],
         "Relying on Python AST parsing to 'safely' execute agent-generated code, allowing a simple subclass exploit to wipe the host disk.",
         "Construct a security test suite demonstrating 5 classic Python sandbox escapes against naive `exec()` and AST filters.",
         "CodeAgent: Sandbox threat model and escape verification harness."),

        (14, "Sandboxed Code Execution II: Ephemeral Docker & Container Isolation",
         "Phase 4, Phase 7, Lesson 12.13",
         ["Container-based sandboxing: launching isolated, single-use Docker containers for each code execution request",
          "Hardening container environments: dropping all Linux capabilities (`--cap-drop=ALL`), non-root execution (`--user 1000:1000`)",
          "Filesystem protection: read-only root filesystem (`--read-only`), mounting small temporary in-memory tmpfs for `/tmp`",
          "Resource limits: setting strict cgroup limits for CPU (`--cpus=1.0`), memory (`--memory=256m`), and process count (`--pids-limit=64`)",
          "Network isolation: running with `--network=none` to completely block outbound internet access and data exfiltration",
          "Container lifecycle management: automated container destruction with strict timeouts (`--rm`, timeout daemon) to prevent zombie processes"],
         "Leaving container network enabled, allowing an agent-generated script to download malware or exfiltrate private credentials.",
         "Build a Python Docker execution wrapper that runs arbitrary code in an ephemeral hardened container with zero network and read-only rootfs.",
         "CodeAgent: Hardened Docker code execution sandbox."),

        (15, "Sandboxed Code Execution III: gVisor, Firecracker & MicroVMs",
         "Phase 0, Lesson 12.14",
         ["The shared kernel vulnerability of standard containers: kernel exploits escaping container namespaces into host OS",
          "gVisor (Google): application kernel (Sentry) running in user space, intercepting and virtualizing all Linux syscalls",
          "Configuring containerd with `runsc`: seamless integration of gVisor runtime into Docker and Kubernetes environments",
          "Firecracker (AWS): minimalist MicroVMs running on Linux KVM (Kernel-based Virtual Machine); boot times in $<5ms$",
          "Comparing isolation technologies: Docker (low isolation, fast) vs gVisor (strong syscall filtering) vs Firecracker (hardware virtualization)",
          "Production sandbox architecture: managing a pool of pre-warmed Firecracker microVMs for instant sub-second code execution"],
         "Running untrusted code in standard Docker containers on shared Kubernetes worker nodes, risking host kernel compromise.",
         "Configure a gVisor (`runsc`) container runtime; execute code attempting restricted syscalls and verify gVisor interception.",
         "CodeAgent: MicroVM and gVisor sandboxed runtime integration."),

        (16, "Sandboxed Code Execution IV: WebAssembly (Wasm) & WASI Runtimes",
         "Phase 0, Lesson 12.13",
         ["WebAssembly as a universal secure sandbox: memory-safe, deterministic, capability-based virtual execution environment",
          "WebAssembly System Interface (WASI): standardized capability-based system interface for non-browser Wasm execution",
          "Wasmtime / Wasmer runtimes in Python: executing compiled Wasm modules directly from Python via language bindings",
          "Zero-trust capabilities: granting explicit, fine-grained directory access and network permissions to Wasm modules",
          "Executing Python inside Wasm: compiling CPython to WebAssembly (Pyodide, Wasm-Python) for near-instant sandboxed Python execution",
          "Performance and cold starts: sub-millisecond instantiation times and microsecond execution teardown with Wasm"],
         "Attempting to run compiled C/Rust binaries with unrestricted host filesystem access, bypassing Wasm capability sandboxing.",
         "Deploy a Python-in-Wasm (Wasmtime) sandboxed execution engine in Python; benchmark 1ms cold start and strict capability boundaries.",
         "CodeAgent: High-speed WebAssembly sandboxed runner."),

        (17, "Building CodeAgent I: The Workspace & Virtual Filesystem Environment",
         "Phase 0, Phase 4",
         ["CodeAgent project requirements: an autonomous software engineer that writes, tests, debugs, and refactors real codebases",
          "Workspace abstraction: managing a dedicated directory per task with file tracking, git initialization, and clean isolation",
          "Virtual Filesystem operations: implementing robust tool primitives: `read_file`, `write_file`, `edit_file`, `list_directory`",
          "Precise file editing: why whole-file rewriting fails on large files; implementing chunk-based string replacement with diffs",
          "Diff validation: verifying that target replacement blocks are unique before modifying source files to prevent accidental corruption",
          "Git integration: automatic git commit after every agent action to provide an immutable operational audit trail"],
         "Whole-file rewrites truncating large 1,000-line files when output token limits are hit mid-generation.",
         "Build a robust file manipulation toolset in Python supporting line-targeted replacements, diff previews, and git snapshotting.",
         "CodeAgent: Workspace and filesystem management toolset."),

        (18, "Building CodeAgent II: Terminal Execution & Bash Tool Orchestration",
         "Phase 0, Phase 4, Lesson 12.14",
         ["Bash command execution tool: allowing the agent to run compilers, linters, tests, and package managers",
          "Process execution mechanics: `asyncio.create_subprocess_exec` vs `create_subprocess_shell` security trade-offs",
          "Handling long-running and hanging commands: automated timeouts, process group termination (`os.killpg`), and SIGKILL escalation",
          "Paging command mitigation: enforcing `PAGER=cat` to prevent commands like `git diff` or `less` from blocking on interactive stdin",
          "Capturing stdout and stderr: streaming command output, truncation limits (preventing multi-megabyte log flooding), and exit codes",
          "Command whitelisting and blacklisting: preventing interactive commands (`vim`, `nano`, `top`) from hanging the execution loop"],
         "Executing a command that prompts for interactive user confirmation (`y/n`), hanging the background agent process indefinitely.",
         "Build an asynchronous, non-interactive Bash command executor in Python with process group termination and output truncation.",
         "CodeAgent: Interactive terminal execution engine."),

        (19, "Building CodeAgent III: Code Navigation & AST Semantic Search",
         "Phase 1, Phase 10",
         ["Why simple grep is insufficient for large codebases: missing semantic context, hierarchy, and symbol relationships",
          "Abstract Syntax Tree (AST) parsing with Tree-sitter: universal multi-language parsing (Python, TypeScript, Go, Rust)",
          "Symbol extraction: parsing class definitions, function signatures, docstrings, and imports into a structured symbol index",
          "Code navigation tools: `find_symbol_definition`, `find_references`, `get_function_signature`, and `get_class_hierarchy`",
          "Combining lexical search with AST navigation: using ripgrep for fast regex scanning and Tree-sitter for precise syntax node extraction",
          "Token-efficient repository map: generating a compact 500-token structural map of the entire codebase for working context"],
         "Stuffing all source files into the prompt, overwhelming the model context window and degrading reasoning accuracy.",
         "Build a Tree-sitter powered code navigation engine extracting symbols and function signatures across a multi-file Python project.",
         "CodeAgent: Semantic code navigation and AST symbol engine."),

        (20, "Building CodeAgent IV: Test-Driven Development (TDD) Loop & Repair",
         "Phase 1, Lesson 12.2",
         ["Test-Driven Development (TDD) agent loop: Write Test $\\to$ Run Test (Verify Failure) $\\to$ Implement Code $\\to$ Run Test (Verify Pass)",
          "Parsing test suite outputs: structured regex extraction of test failures, assertion errors, and tracebacks from `pytest` / `vitest`",
          "Automated error triage: feeding stack traces, failing line numbers, and expected vs actual values back into the agent reasoning loop",
          "The Reflexion repair cycle: agent formulates a bug hypothesis, inspects relevant source lines, modifies code, and re-executes tests",
          "Preventing regression: running the full test suite after every modification to verify that bug fixes didn't break existing functionality",
          "Self-stopping criteria: terminating execution successfully upon 100% test pass or escalating to human after 5 failed repair attempts"],
         "Agent modifying the test assertions to pass rather than fixing the underlying broken application logic.",
         "Run CodeAgent on a broken repository; verify that it parses pytest error output, applies correct code edits, and passes all tests.",
         "CodeAgent: Automated TDD execution and repair engine."),

        (21, "Multi-Agent Architectures: When to Split into Specialized Agents",
         "Lesson 12.1",
         ["The monolithic agent breakdown: why single agents with 30 tools fail due to tool selection confusion and context bloat",
          "Principles of Multi-Agent Systems: division of labor, domain specialization, smaller focused prompt contexts, and modular testing",
          "Agent roles taxonomy: Planner / Architect, Researcher / Explorer, Software Engineer, Code Reviewer / QA, DevOps Engineer",
          "Communication topologies: Centralized Supervisor vs Decentralized Peer-to-Peer vs Hierarchical Teams vs Pipeline Chaining",
          "Cost and latency implications: multi-agent systems multiply token usage; matching architecture to task value",
          "Evaluating multi-agent trade-offs: when single-agent with structured workflows outperforms multi-agent debate"],
         "Deploying a multi-agent system of 6 debating agents for a trivial 1-file typo fix, burning $5 in tokens for a 2-second task.",
         "Draft an architectural comparison matrix evaluating Single-Agent vs Supervisor Multi-Agent on a complex software feature task.",
         "CodeAgent: Multi-agent architectural design document."),

        (22, "Multi-Agent Patterns I: The Supervisor-Worker Orchestration Pattern",
         "Lesson 12.6, Lesson 12.21",
         ["Supervisor-Worker topology: a centralized orchestrator agent delegating specialized sub-tasks to dedicated worker agents",
          "The Supervisor node in LangGraph: analyzing user request, maintaining high-level plan, and routing to specialized worker nodes",
          "Worker agent specialization: Research Worker (read-only tools), Coder Worker (filesystem tools), Test Worker (bash/pytest tools)",
          "Worker execution lifecycle: worker receives sub-task, executes internal cyclic loop to completion, and returns structured outcome to Supervisor",
          "Supervisor state synthesis: aggregating worker outputs, updating task progress, and deciding the next worker to invoke or terminating",
          "Dynamic replanning: supervisor modifying the remaining plan when a worker reports an impossible sub-task"],
         "Workers returning massive unstructured chat transcripts to the supervisor, overflowing the supervisor context window.",
         "Implement a LangGraph Supervisor-Worker system with a Research Worker and Coder Worker collaborating to solve a coding challenge.",
         "CodeAgent: Supervisor-Worker orchestration network."),

        (23, "Multi-Agent Patterns II: Hierarchical Teams & Subgraph Composition",
         "Lesson 12.6, Lesson 12.22",
         ["Scaling beyond flat supervisor topologies: nested hierarchical teams managing complex enterprise software projects",
          "Subgraph composition in LangGraph: compiling independent state graphs and embedding them as callable nodes inside parent graphs",
          "Top-level Engineering Director graph: delegating to Frontend Team subgraph, Backend Team subgraph, and QA Team subgraph",
          "State boundary isolation: subgraphs operating on local state schemas, passing only essential summaries back to parent graphs",
          "Cross-team communication protocols: standardized contract interfaces between frontend and backend agent teams",
          "Parallel team execution: executing independent subgraphs concurrently in the same superstep to minimize total wall-clock time"],
         "State pollution across teams: sharing global mutable variables across subgraphs causing unintended cross-team side effects.",
         "Build a nested LangGraph system where a parent Manager graph coordinates a Backend subgraph and a Frontend subgraph in parallel.",
         "CodeAgent: Hierarchical multi-team subgraph architecture."),

        (24, "Multi-Agent Patterns III: Collaborative Multi-Agent Debate & Consensus",
         "Lesson 12.21",
         ["The Multi-Agent Debate paradigm (Du et al.): multiple agents presenting solutions, critiquing each other, and reaching consensus",
          "Mitigating individual model hallucinations: how peer critique surfaces factual errors, edge-case oversights, and logic bugs",
          "Debate topologies: Round-Robin debate vs Adversarial debate (Proposer vs Red Team Critic) vs Jury Consensus voting",
          "Structuring critique prompts: forcing critics to focus on security vulnerabilities, edge cases, and algorithmic complexity",
          "Consensus termination algorithms: measuring solution convergence; terminating when critique identifies zero remaining issues",
          "Preventing groupthink: injecting contrarian personas or temperature diversity to avoid agents prematurely agreeing on wrong answers"],
         "Agents entering an infinite polite agreement loop ('I agree with your brilliant point') without performing rigorous critical verification.",
         "Implement an Adversarial Code Review debate where a Critic agent attacks a Coder agent's code until 0 security vulnerabilities remain.",
         "CodeAgent: Adversarial debate and code review engine."),

        (25, "Agent Communication Protocols & Structured Message Buses",
         "Phase 4, Phase 7, Lesson 12.22",
         ["Inter-agent communication standards: moving beyond raw natural language strings to structured protocol messages",
          "Agent Communication Language (ACL) principles: performatives (Request, Inform, Propose, Reject, Confirm, Query)",
          "Structured message envelop: `sender`, `recipient`, `performative`, `conversation_id`, `reply_with`, `payload` (Pydantic model)",
          "Asynchronous message routing: backing inter-agent communication with Redis Streams or Kafka for distributed multi-agent systems",
          "Agent service discovery: registry where agents query capabilities of available peer agents dynamically",
          "Dead-letter queues and message tracing: tracking inter-agent message exchanges with distributed OpenTelemetry spans"],
         "Natural language ambiguity causing Worker B to misinterpret Worker A's output format, resulting in parsing crashes.",
         "Implement a typed JSON message bus supporting standard FIPA-ACL performatives for structured inter-agent collaboration.",
         "CodeAgent: Distributed agent message bus protocol."),

        (26, "Agent Trajectory Evaluation: Benchmarking on SWE-bench & GAIA",
         "Phase 10, Lesson 12.20",
         ["Benchmarking autonomous agents: moving from simple Q&A benchmarks to real-world software engineering benchmarks",
          "SWE-bench (Princeton): evaluating agents on resolving real GitHub issues from popular open-source repositories",
          "SWE-bench task anatomy: issue description, base repo commit, environment setup, and gold evaluation patch (`pytest` verification)",
          "General AI Assistants (GAIA) benchmark: multi-modal, tool-use, multi-step real-world assistant evaluation tasks",
          "Evaluation metrics: Pass@1, execution trajectory length (number of tool calls), total token cost, and wall-clock time",
          "Analyzing failure trajectories: classifying agent failures (bad plan, file editing error, test failure, context overflow)"],
         "Evaluating agents on synthetic toy problems, failing to predict catastrophic failure rates on messy real-world codebases.",
         "Set up a local SWE-bench evaluation runner; evaluate CodeAgent on 5 real GitHub issues and compute exact Pass@1 accuracy.",
         "CodeAgent: SWE-bench evaluation and trajectory analysis harness."),

        (27, "Trajectory Mining & Synthetic Distillation for Agent Fine-Tuning",
         "Phase 9, Phase 10, Lesson 12.26",
         ["The cost bottleneck of frontier models: running agent loops on GPT-4 / Claude 3.5 Sonnet costs $0.50-$2.00 per task",
          "Trajectory Mining: collecting thousands of successful multi-step execution traces from frontier models",
          "Filtering high-quality trajectories: filtering for traces that solved tasks with minimal tool calls and zero syntax errors",
          "Formatting agent trajectories for supervised fine-tuning (SFT): tokenizing multi-turn messages, tool calls, and environment observations",
          "Fine-tuning open-source models (Llama-3-8B) on agent trajectories: teaching smaller models exact tool calling and reasoning habits",
          "Performance parity: achieving 90% of frontier model agent accuracy at 5% of the API cost using distilled local models"],
         "Fine-tuning on failed or meandering agent trajectories, training the distilled model to repeat infinite loops and syntax bugs.",
         "Mine 50 successful CodeAgent trajectories, clean into structured SFT format, and prepare a dataset for model distillation.",
         "CodeAgent: Trajectory mining and training dataset generator."),

        (28, "Production Agent Observability: Tracing Trajectories with Langfuse & Arize",
         "Phase 7, Phase 10, Lesson 12.8",
         ["The black-box agent problem: diagnosing why an agent took a wrong turn at step 14 of a 25-step execution trajectory",
          "Distributed tracing for agent graphs: instrumenting every node, tool call, LLM invocation, and state transition with OpenInference",
          "Visualizing agent execution trees: inspecting intermediate state updates, tool inputs/outputs, and token costs in Langfuse UI",
          "Latency profiling: pinpointing which specific tool executions or LLM calls dominated total execution duration",
          "Cost analytics: tracking dollar cost per task, token efficiency, and identifying prompt bloat across long trajectories",
          "Alerting on runaway agents: automated alerts for agents exceeding recursion thresholds or burning $> $5 on a single session"],
         "Lacking granular span tracing, forcing engineers to manually comb through 10,000 lines of terminal stdout logs to find bugs.",
         "Instrument CodeAgent with Langfuse; capture a complete 20-step execution trace and analyze token cost and tool latency bottlenecks.",
         "CodeAgent: Production observability and trajectory tracing suite."),

        (29, "Agentic Security & Guardrails: Sandboxing, Privilege Escalation & Blast Radius",
         "Phase 5, Lesson 12.13, Lesson 12.14",
         ["Security threat landscape for autonomous agents: OWASP Top 10 for LLM Applications and Agentic Systems",
          "Indirect Prompt Injection in agents: external data (scraped web pages, cloned git repos, user issues) hijacking agent tool execution",
          "Privilege Escalation vectors: agent using low-privilege tools to modify high-privilege configuration files or credentials",
          "Blast Radius Containment: least privilege tool permissions, scoped API keys, sandboxed filesystem roots, and resource quotas",
          "Automated safety guardrails: intercepting dangerous bash commands (`rm -rf`, `curl | bash`, `chmod 777`) via pre-execution hooks",
          "Auditing and compliance: immutable cryptographic logging of all agent actions, approvals, and environment mutations"],
         "Cloning a malicious repository containing a prompt injection in README.md that instructs CodeAgent to exfiltrate AWS credentials.",
         "Execute an indirect prompt injection attack against CodeAgent; verify that pre-execution security hooks block malicious tool execution.",
         "CodeAgent: Enterprise security guardrails and injection defense suite."),

        (30, "CodeAgent Production Deployment & Autonomous Engineering Defense",
         "Phase 6, Phase 7, Lesson 12.28",
         ["Assembling the complete autonomous software engineer: LangGraph state machine, PostgreSQL checkpointer, hardened Docker sandbox",
          "Full-stack agent integration: Next.js frontend streaming live agent thoughts, tool calls, diff previews, and HITL approval modals",
          "Deploying CodeAgent on Kubernetes: asynchronous Celery worker pods running sandboxed containers, isolated from host cluster",
          "Production readiness review: validating resilience against API outages, database restarts, and adversarial prompt attacks",
          "The Autonomous Engineering Benchmark: setting CodeAgent loose on an unfamiliar codebase to resolve an issue with zero human intervention",
          "Architectural defense: presenting system architecture, safety bounds, SWE-bench performance, and cost engineering to leadership"],
         "Deploying CodeAgent directly into production repositories with write permissions without branch protection or PR gates.",
         "Deploy CodeAgent to an isolated environment; assign it a real bug in a web app, and verify that it opens a verified PR with passing tests.",
         "CodeAgent: Final end-to-end production deployment and system defense.")
    ]

    for item in p12_data:
        out.append(format_lesson(12, item[0], item[1], item[2], item[3], item[4], item[5], item[6]))

    out.append("""
### Phase 12 Capstone Deliverables
- **CodeAgent**: An autonomous multi-agent software engineering system built with LangGraph, PostgreSQL durable checkpointing, time-travel debugging, Human-in-the-Loop review queues, gVisor/Docker sandboxed execution, Tree-sitter AST navigation, automated TDD repair loops, and SWE-bench trajectory evaluation.

### Phase 12 Exit Benchmark
- Deploy CodeAgent against 5 real GitHub repository issues; CodeAgent must autonomously navigate the codebase, reproduce the bug via test, modify code in sandbox, verify all tests pass, and generate clean PR diffs with $> 60\\%$ Pass@1 success rate.
""")
    return "\n".join(out)


def generate_phase13():
    out = []
    out.append("""## Phase 13: Specialized Production Tracks
**Target Duration**: 4 Weeks (Lessons 13.1 – 13.20)
**Core Focus**: Deep specialization across 4 high-impact production engineering tracks (5 advanced lessons per track): Track A (Advanced Product Engineering), Track B (High-Throughput MLOps & Distributed Training), Track C (Systems Security & Cloud Infrastructure Hardening), and Track D (Applied AI Research & Frontier Model Architectures).

---
""")

    p13_data = [
        # Track A: Advanced Product Engineering (13.1 - 13.5)
        (1, "Track A: Micro-Frontends & Module Federation at Enterprise Scale",
         "Phase 6, Lesson 6.16",
         ["Micro-frontend architectural patterns: independent deployments, autonomous team lifecycles, and shared app shells",
          "Webpack/Rspack Module Federation internals: host containers, remote containers, shared dependency singletons, and version negotiation",
          "Runtime integration vs build-time composition: dynamic script injection, sandboxed CSS styling, and global state isolation",
          "Cross-micro-frontend communication: event bus patterns, shared stores via custom browser events, and URL routing synchronization",
          "Shared dependency optimization: resolving React singleton conflicts (`shared: { react: { singleton: true } }`) and version mismatches",
          "Resilience and fault tolerance: graceful fallback rendering when remote micro-frontends experience deployment or network outages"],
         "Duplicate React instances loaded in runtime breaking hook contexts; remote micro-frontend crash taking down entire host shell.",
         "Build a host container dynamically loading two remote micro-frontends with shared React singletons and isolated CSS namespaces.",
         "Track A Capstone: Enterprise micro-frontend platform."),

        (2, "Track A: Local-First Software & Offline Real-Time Sync with CRDTs (Yjs)",
         "Phase 6, Phase 7, Lesson 7.5",
         ["The Local-First software manifesto: immediate local read/write operations, full offline availability, and background synchronization",
          "Conflict-Free Replicated Data Types (CRDTs) in the browser: Yjs architecture, binary state vectors, and update encoding",
          "Shared types: Y.Doc, Y.Map, Y.Array, and Y.Text supporting collaborative rich text editing with zero merge conflicts",
          "Persistence layer: synchronizing Yjs binary documents to client-side IndexedDB via `y-indexeddb` for offline persistence",
          "Network synchronization providers: WebSockets (`y-websocket`) and WebRTC (`y-webrtc`) for peer-to-peer real-time updates",
          "Reconciliation and awareness: tracking user presence (cursors, selections, active status) across multi-user collaborative sessions"],
         "State vector bloat causing client IndexedDB performance to degrade; unhandled connection dropouts losing offline document edits.",
         "Build a local-first collaborative document editor that functions 100% offline, persists to IndexedDB, and syncs seamlessly upon reconnect.",
         "Track A Capstone: Local-first collaborative editor."),

        (3, "Track A: High-Performance Canvas & WebGL Rendering",
         "Phase 0, Phase 6",
         ["Browser graphics rendering: DOM/SVG limits (performance drops past 2,000 elements) vs HTML5 Canvas and WebGL",
          "Canvas 2D rendering context: immediate mode rendering, coordinate systems, transformation matrices, and path drawing",
          "Optimizing Canvas 2D: OffscreenCanvas, double buffering, spatial indexing (QuadTree) for fast viewport culling",
          "WebGL fundamentals: GPU pipeline, vertex shaders, fragment shaders, GLSL syntax, and buffer attributes",
          "Rendering 100,000 interactive data points at 60fps: instanced rendering, memory-packed Float32Array buffers, and GPU draw calls",
          "Hit testing at scale: GPU color picking vs spatial CPU QuadTree traversal for mouse hover and click interactions"],
         "Executing expensive Canvas drawing calls on the main thread during scroll events, dropping frames to 15fps.",
         "Build a real-time financial chart rendering 100,000 data points at a stable 60fps using OffscreenCanvas and QuadTree culling.",
         "Track A Capstone: High-frequency charting engine."),

        (4, "Track A: WebAssembly (Wasm) Frontend Modules & Rust Compilation",
         "Phase 0, Phase 1, Phase 6",
         ["Why WebAssembly on the frontend: near-native execution speed for computationally intensive client-side tasks",
          "Compiling Rust to WebAssembly: `wasm-pack`, `wasm-bindgen`, and generating TypeScript declaration files",
          "Memory management between JS and Wasm: linear memory buffer, typed arrays, passing strings, and zero-copy pointer views",
          "Web Workers and Wasm concurrency: multi-threaded Wasm execution using `SharedArrayBuffer` and WebAssembly threads",
          "High-performance client-side audio/image processing: building client-side image filters, encryption, and video manipulation",
          "Benchmarking Wasm vs native JavaScript: measuring $5\\times - 10\\times$ speedup on heavy cryptographic hashing and image convolution"],
         "Excessive serializing and deserializing of large JSON strings across the JS-Wasm boundary, negating all compute speedup benefits.",
         "Write a high-performance image blurring kernel in Rust, compile to Wasm, and execute in browser at 10x the speed of pure JS.",
         "Track A Capstone: Client-side Wasm media processing engine."),

        (5, "Track A: Global Multi-Tenant Billing, Tax Compliance & Invoicing",
         "Phase 5, Phase 6, Lesson 6.40",
         ["Architecting global SaaS monetization: multi-currency support, localized pricing, and payment method diversity (Cards, SEPA, iDEAL)",
          "Global tax compliance: VAT (Europe), GST (Australia/India), state sales tax (US); integrating Stripe Tax / Avalara calculation APIs",
          "Complex billing models: tiered per-seat pricing, metered usage-based billing, minimum commitments, and overage calculations",
          "Invoice generation engine: PDF generation, immutable legal invoice numbering, tax breakdown compliance, and payment receipts",
          "Dunning management: automated retry schedules on failed charges, smart card updater, and customer grace period enforcement",
          "Revenue recognition (ASC 606): deferred revenue schedules, recognizing subscription revenue ratably over service delivery periods"],
         "Incorrect tax calculation on digital services triggering legal non-compliance penalties across European Union jurisdictions.",
         "Implement a complete multi-currency SaaS billing engine with automated tax calculation, invoice generation, and dunning retries.",
         "Track A Capstone: Enterprise global billing and tax engine."),

        # Track B: High-Throughput MLOps & Distributed Training (13.6 - 13.10)
        (6, "Track B: Distributed Deep Learning Foundations: Data Parallelism & AllReduce",
         "Phase 9, Phase 11",
         ["The scale limit of single-GPU training: models and batch sizes exceeding 80GB VRAM on modern NVIDIA H100 GPUs",
          "Distributed training paradigms: Data Parallelism (DP), Tensor Parallelism (TP), Pipeline Parallelism (PP), and Sequence Parallelism",
          "Distributed Data Parallel (DDP): replicating model across $N$ GPUs, scattering mini-batches, and synchronizing gradients",
          "Collective communication primitives (NCCL): Broadcast, Scatter, Gather, AllGather, Reduce, and Ring-AllReduce",
          "Ring-AllReduce mathematical efficiency: optimal bandwidth utilization independent of the number of participating GPUs ($2 \\frac{N-1}{N} S$)",
          "Gradient bucketing in PyTorch DDP: overlapping gradient communication with backward computation to hide network latency"],
         "Using PyTorch `DataParallel` instead of `DistributedDataParallel`, suffering from single-process GIL lock bottlenecks.",
         "Implement a Ring-AllReduce gradient synchronization simulation in Python using socket message passing across 4 virtual processes.",
         "Track B Capstone: Distributed training communication harness."),

        (7, "Track B: Fully Sharded Data Parallel (FSDP) & DeepSpeed ZeRO-3",
         "Phase 9, Lesson 13.6",
         ["The memory footprint of deep learning: Model Parameters ($1\\times$), Gradients ($1\\times$), Optimizer States ($4-8\\times$ for AdamW)",
          "ZeRO (Zero Redundancy Optimizer) memory stages: ZeRO-1 (Optimizer State Sharding), ZeRO-2 (Gradient Sharding), ZeRO-3 (Parameter Sharding)",
          "PyTorch Fully Sharded Data Parallel (FSDP): native ZeRO-3 implementation sharding parameters, gradients, and optimizer states across GPUs",
          "Forward and backward passes in FSDP: AllGathering parameters just-in-time for layer computation, discarding them immediately after",
          "CPU Offloading: swapping partitioned optimizer states and parameters to system host RAM during memory-constrained training",
          "Training a 70-Billion parameter LLM across an 8-GPU cluster: configuring FSDP wrapping policies and backward prefetching"],
         "Failing to configure fine-grained module wrapping in FSDP, causing FSDP to AllGather the entire model at once and trigger OOM.",
         "Configure and run PyTorch FSDP training of a multi-billion parameter transformer across multiple GPUs with parameter sharding.",
         "Track B Capstone: Large-scale FSDP distributed training pipeline."),

        (8, "Track B: High-Throughput LLM Inference Optimization: TensorRT-LLM & vLLM",
         "Phase 10, Phase 11, Lesson 11.23",
         ["Inference serving challenges at enterprise scale: optimizing TTFT, token generation throughput, and minimizing GPU idle time",
          "PagedAttention internals: eliminating KV-cache memory fragmentation by allocating non-contiguous virtual memory blocks",
          "Chunked Prefill: interleaving heavy prefill prompt processing with lightweight token decode passes to eliminate latency spikes",
          "Speculative Decoding: utilizing small draft models to propose multiple candidate tokens verified in parallel by target model",
          "NVIDIA TensorRT-LLM architecture: custom C++ runtime, fused multi-head attention kernels, and FP8 tensor core acceleration",
          "Benchmarking production serving: stress-testing vLLM and TensorRT-LLM across varying prompt lengths and batch sizes"],
         "Serving LLMs with un-paged KV caches, wasting 60% of GPU memory on internal fragmentation and dropping maximum concurrency.",
         "Deploy and benchmark a TensorRT-LLM and vLLM server; measure 4x throughput improvement over standard HuggingFace pipeline.",
         "Track B Capstone: High-throughput GPU inference cluster."),

        (9, "Track B: Distributed Orchestration with Ray: Clusters, Actors & Workflows",
         "Phase 7, Lesson 13.6",
         ["Ray architecture: universal framework for scaling AI and Python applications (Ray Core, Ray Train, Ray Serve, Ray Data)",
          "Ray Core primitives: Tasks (stateless distributed functions) and Actors (stateful distributed classes with managed lifecycle)",
          "Ray Cluster architecture: Head node (Global Control Store - GCS, scheduler), Worker nodes, and autoscaling cloud node pools",
          "Distributed data processing with Ray Data: streaming multi-terabyte datasets across GPU memory with zero-copy Plasma object store",
          "Distributed hyperparameter tuning with Ray Tune: population-based training, Bayesian optimization, and early stopping schedulers",
          "Fault tolerance in Ray: actor health checks, object lineage reconstruction, and automatic task retry on worker node preemption"],
         "Storing large data objects inside task arguments rather than putting them into the Ray Plasma object store, causing network flooding.",
         "Build a distributed data processing and model training pipeline using Ray Core and Ray Train across a multi-node cluster.",
         "Track B Capstone: Distributed Ray cluster workflow engine."),

        (10, "Track B: Feature Stores & Real-Time ML Pipelines: Feast & Hopsworks",
         "Phase 4, Phase 7, Phase 11",
         ["The training-serving skew crisis: model features computed differently during offline training than during online production inference",
          "Feature Store architecture: unifying feature definitions across batch training pipelines and low-latency real-time inference APIs",
          "Offline Store vs Online Store: BigQuery/Snowflake/Parquet for historical batch point-in-time joins vs Redis/DynamoDB for <5ms lookups",
          "Point-in-Time Correctness (Time Travel): generating training datasets without data leakage from future timestamps",
          "Feature definitions in Feast: Entity, FeatureView, Source, and automated feature materialization pipelines from offline to online stores",
          "Feature monitoring: tracking feature drift, missing value rates, and schema violations in production feature serving"],
         "Data leakage during training dataset generation by joining features from future dates, producing artificially inflated model accuracy.",
         "Deploy Feast feature store; register batch and streaming feature views, and execute point-in-time joins for model training.",
         "Track B Capstone: Production Feast feature store deployment."),

        # Track C: Systems Security & Cloud Infrastructure Hardening (13.11 - 13.15)
        (11, "Track C: eBPF-Powered Security Observability: Cilium & Tetragon",
         "Phase 0, Phase 7",
         ["Extended Berkeley Packet Filter (eBPF) architecture: executing verified bytecode sandboxed directly inside the Linux kernel",
          "Why eBPF supersedes traditional user-space monitoring: zero context switches, kernel-level visibility, tamper-proof security",
          "Tetragon runtime security: hook points in kernel syscalls (`sys_execve`, `sys_open`, `sys_connect`), kprobes, and tracepoints",
          "Real-time threat detection: detecting privilege escalation, shell spawning inside containers, and namespace escapes instantly",
          "Cilium eBPF network security: Layer 3/4/7 network policies enforced at socket layer without iptables overhead",
          "Automated security remediation: killing malicious processes (`sigkill`) directly from the kernel before unauthorized actions complete"],
         "Deploying user-space audit daemons that can be killed or disabled by attackers who gain root privileges in container namespaces.",
         "Deploy Cilium and Tetragon on a Kubernetes cluster; write an eBPF security policy that detects and kills unauthorized shell execution.",
         "Track C Capstone: Kernel-level eBPF security enforcement engine."),

        (12, "Track C: Zero-Trust Architecture: Mutual TLS & SPIFFE/SPIRE",
         "Phase 5, Phase 7",
         ["Zero-Trust principles: assume breach, never trust, verify explicitly, enforce least privilege access across all services",
          "Secure Production Identity Framework for Everyone (SPIFFE): standardized cryptographic identity specification for workloads",
          "SPIRE (SPIFFE Runtime Environment): SPIRE Server (CA, registration APIs) and SPIRE Agent (workload attestation, SVID issuance)",
          "Workload Attestation: verifying container image, UID, namespace, and binary hash before granting cryptographic identities",
          "SPIFFE Verifiable Identity Document (SVID): short-lived X.509 certificates rotated automatically every hour",
          "Enforcing end-to-end mutual TLS (mTLS): configuring Envoy sidecars with SPIRE SVIDs for automatic peer authentication"],
         "Relying on long-lived static API tokens or network IP whitelists for microservice authentication in dynamic cloud environments.",
         "Deploy SPIRE on Kubernetes; configure workload attestation and verify automated short-lived mTLS communication between microservices.",
         "Track C Capstone: SPIFFE/SPIRE Zero-Trust identity infrastructure."),

        (13, "Track C: Enterprise Key Management, Envelope Encryption & HSMs",
         "Phase 5, Phase 7",
         ["Cryptographic security at scale: protecting multi-tenant data at rest using Hardware Security Modules (HSMs) and KMS",
          "Envelope Encryption mechanics: encrypting plaintext with unique Data Encryption Key (DEK); encrypting DEK with Key Encryption Key (KEK)",
          "Why envelope encryption is mandatory: avoiding sending multi-gigabyte data payloads to central KMS over the network",
          "Cloud KMS integration: Google Cloud KMS / AWS KMS, Customer-Managed Encryption Keys (CMEK), and key rotation policies",
          "Cryptographic erasure (Crypto-Shredding): fulfilling GDPR right-to-be-forgotten by destroying tenant KEKs in HSMs instantly",
          "FIPS 140-2 Level 3 HSM compliance: hardware tamper-resistance, zero extraction of master private keys, and audit logging"],
         "Storing unencrypted Data Encryption Keys (DEKs) in database columns alongside encrypted data payloads.",
         "Implement an Envelope Encryption pipeline in Python using Cloud KMS with automated DEK generation and Crypto-Shredding verification.",
         "Track C Capstone: Enterprise envelope encryption and KMS pipeline."),

        (14, "Track C: DevSecOps CI/CD Automation: Static & Dynamic Security Scanning",
         "Phase 5, Phase 7",
         ["DevSecOps philosophy: shifting security left into developer workflows and automated CI/CD deployment pipelines",
          "Static Application Security Testing (SAST): AST-based vulnerability scanning with Semgrep, custom security rules, and CVE detection",
          "Software Bill of Materials (SBOM): generating standardized CycloneDX / SPDX component inventories in CI builds",
          "Dependency vulnerability management: automated vulnerability scanning with Snyk / Trivy, tracking CVSS scores and remediation paths",
          "Dynamic Application Security Testing (DAST): automated vulnerability probing of running staging environments with OWASP ZAP",
          "Policy as Code with Open Policy Agent (OPA) / Conftest: blocking Kubernetes deployments violating security benchmarks (e.g. root containers)"],
         "Failing to block CI builds on critical CVSS 10.0 vulnerabilities, allowing known remote code execution bugs into production.",
         "Build a GitHub Actions DevSecOps pipeline with Semgrep SAST, Trivy SBOM generation, and OPA Conftest deployment gate enforcement.",
         "Track C Capstone: Automated DevSecOps security pipeline."),

        (15, "Track C: Red-Teaming, Penetration Testing & Vulnerability Disclosure",
         "Phase 5, Phase 10",
         ["Red-Teaming methodology: simulating real-world sophisticated adversary attacks across systems, infrastructure, and personnel",
          "Penetration testing phases: Reconnaissance, Vulnerability Scanning, Exploitation, Privilege Escalation, Lateral Movement, Exfiltration",
          "Web application exploitation: chaining SSRF, deserialization bugs, and SQL injection into remote shell access on backend servers",
          "Cloud infrastructure attacks: exploiting misconfigured IAM roles, metadata server access (SSRF to `169.254.169.254`), and bucket permissions",
          "Vulnerability disclosure protocols: coordinated vulnerability disclosure (CVD), bug bounty program management, and CVE assignment",
          "Authoring executive security reports: translating technical vulnerabilities into business risk impacts and remediation roadmaps"],
         "Failing to protect the cloud metadata server (IMDSv2), allowing an SSRF vulnerability to dump cloud IAM credentials.",
         "Execute a comprehensive penetration test on a mock cloud architecture; document findings and author an executive remediation report.",
         "Track C Capstone: Red-team penetration audit and defense report."),

        # Track D: Applied AI Research & Frontier Model Architectures (13.16 - 13.20)
        (16, "Track D: Alignment Science: Direct Preference Optimization (DPO) & RLHF",
         "Phase 9, Phase 10",
         ["The alignment problem: steering raw pre-trained next-token predictors toward helpful, harmless, and honest behavior",
          "Reinforcement Learning from Human Feedback (RLHF) classical pipeline: SFT $\\to$ Reward Model Training $\\to$ PPO Policy Optimization",
          "Proximal Policy Optimization (PPO) complexity: coordinating 4 models concurrently (Policy, Value, Reference, Reward), training instability",
          "Direct Preference Optimization (DPO) breakthrough (Rafailov et al.): mathematically deriving closed-form policy loss without a reward model",
          "DPO loss formulation: $\\mathcal{L}_{DPO}(\\pi_\\theta; \\pi_{ref}) = -\\mathbb{E}\\left[\\log \\sigma\\left(\\beta \\log \\frac{\\pi_\\theta(y_w|x)}{\\pi_{ref}(y_w|x)} - \\beta \\log \\frac{\\pi_\\theta(y_l|x)}{\\pi_{ref}(y_l|x)}\\right)\\right]$",
          "KTO (Kahneman-Tversky Optimization) and ORPO (Odds Ratio Preference Optimization): preference optimization without paired datasets"],
         "Setting DPO temperature parameter $\\beta$ too high or low, causing model mode collapse or failing to learn user preferences.",
         "Implement the DPO loss function from scratch in PyTorch; fine-tune an aligned model on paired preference data.",
         "Track D Capstone: DPO model alignment and preference optimization pipeline."),

        (17, "Track D: Mixture of Experts (MoE) Architecture: Routing & Sparse Compute",
         "Phase 9, Lesson 13.7",
         ["Dense models vs Sparse Mixture of Experts (MoE): scaling parameter capacity exponentially while keeping inference compute constant",
          "MoE layer architecture: replacing standard FFN layers with $N$ parallel expert FFNs and a learnable gating router network",
          "Top-$k$ routing mechanics (Shazeer et al.): router projecting token embedding to logits, selecting top $k$ experts via softmax (typically $k=2$)",
          "Expert capacity and load balancing: auxiliary load balancing loss (Switch Transformer) preventing routing collapse to single popular expert",
          "Token dropping vs padding: managing fixed expert buffer capacities during batched execution across distributed GPU nodes",
          "DeepSeek-V2/V3 and Mixtral architecture: fine-grained experts, shared experts, and multi-token prediction heads"],
         "Router collapsing to 1 or 2 dominant experts due to missing load balancing loss, leaving remaining experts untrained.",
         "Build a Top-2 Mixture of Experts (MoE) transformer layer with auxiliary load balancing loss from scratch in PyTorch.",
         "Track D Capstone: Sparse Mixture of Experts (MoE) architecture."),

        (18, "Track D: State Space Models (SSMs) & Modern Mamba Architecture",
         "Phase 9, Phase 10",
         ["The quadratic bottleneck of Transformers: $O(T^2)$ computational complexity of self-attention limiting long-context scalability",
          "Classical State Space Models: continuous differential equations mapping 1D stimulus $x(t) \\to y(t)$ via latent state $h(t)$",
          "HiPPO framework (High-order Polynomial Projection Operators): memory initialization maintaining continuous signal history",
          "Structured State Space Models (S4): continuous to discrete discretization (Bilinear / Euler transform) and fast convolutional training",
          "Mamba architecture (Gu & Dao): Selective State Spaces (S6) making transition matrices input-dependent to filter irrelevant information",
          "Hardware-aware selective scan: fused GPU SRAM kernel eliminating slow HBM transfers, achieving linear $O(T)$ training and $O(1)$ inference"],
         "Attempting to train S4/Mamba with standard non-fused PyTorch scan operators, causing massive memory overhead and GPU stalling.",
         "Implement a discrete State Space Model forward pass in PyTorch; verify linear $O(T)$ memory scaling on 10,000 token sequences.",
         "Track D Capstone: Selective State Space (Mamba) sequence model."),

        (19, "Track D: Mechanistic Interpretability: Probing Features & Induction Heads",
         "Phase 9, Phase 10",
         ["The mechanistic interpretability goal: reverse-engineering the internal weights and circuits of neural networks into human-understandable algorithms",
          "Linear Artificial Neurons vs Polysemanticity: single neurons firing for completely unrelated concepts due to superposition",
          "Sparse Autoencoders (SAEs) (Anthropic): decomposing internal dense activations into sparse, monosemantic feature dictionaries",
          "Attention circuit analysis (Elhage et al.): QK-circuits (where tokens attend) vs OV-circuits (what information is moved)",
          "Induction Heads: two-layer attention circuits that implement in-context pattern completion ($[A][B] \\dots [A] \\to [B]$)",
          "Activation patching and causal scrubbing: isolating exact neural sub-circuits responsible for specific factual recall and reasoning"],
         "Assuming individual neurons map to single human concepts, ignoring superposition and cross-layer feature interference.",
         "Train a Sparse Autoencoder (SAE) on transformer hidden states; extract and visualize monosemantic features and verify induction heads.",
         "Track D Capstone: Mechanistic interpretability and SAE feature extraction harness."),

        (20, "Track D: Frontier Model Quantization & Custom Kernel Engineering (Triton)",
         "Phase 0, Phase 9, Phase 11",
         ["The memory wall in deep learning: compute speed exceeding GPU memory bandwidth; arithmetic intensity optimization",
          "OpenAI Triton language: Python-based programming model for writing high-performance GPU kernels without writing raw CUDA C++",
          "Triton programming mental model: block-level programming, automated shared memory management, and coalesced global memory loads",
          "Writing a custom fused Softmax kernel in Triton: loading blocks into SRAM, vectorized operations, and storing results with minimal HBM passes",
          "Writing a fused FlashAttention kernel in Triton: tiling Query, Key, Value blocks, online softmax scaling, and zero materialized $T \\times T$ matrix",
          "Benchmarking custom Triton kernels: achieving $> 80\\%$ of theoretical peak hardware TFLOPs on modern NVIDIA GPUs"],
         "Failing to handle non-power-of-two tensor boundaries in Triton block masking, producing silent memory corruption.",
         "Write and benchmark a custom fused FlashAttention kernel in OpenAI Triton; demonstrate $3\\times$ speedup over native PyTorch attention.",
         "Track D Capstone: Custom fused FlashAttention Triton kernel.")
    ]

    for item in p13_data:
        out.append(format_lesson(13, item[0], item[1], item[2], item[3], item[4], item[5], item[6]))

    out.append("""
### Phase 13 Capstone Deliverables
- **Track A Capstone**: Production Enterprise Web Platform with Module Federation micro-frontends, Yjs local-first sync, Wasm Rust compute, and Stripe global billing.
- **Track B Capstone**: Distributed Training & High-Throughput MLOps Platform with PyTorch FSDP, DeepSpeed ZeRO-3, TensorRT-LLM, Ray clusters, and Feast feature store.
- **Track C Capstone**: Hardened Zero-Trust Cloud Platform with Cilium/Tetragon eBPF kernel security, SPIFFE/SPIRE mTLS, KMS envelope encryption, and DevSecOps pipelines.
- **Track D Capstone**: Frontier AI Research & System Engine with DPO alignment, Top-2 MoE routing, Mamba selective state spaces, and custom OpenAI Triton kernels.

### Phase 13 Exit Benchmark
- Complete the dedicated specialization track capstone and pass a rigorous 60-minute technical defense with verifiable production artifacts.
""")
    return "\n".join(out)


def generate_phase14():
    out = []
    out.append("""## Phase 14: Comprehensive Capstone Project & Production Defense
**Target Duration**: 12 Weeks (Lessons 14.1 – 14.15)
**Core Focus**: Designing, building, deploying, hardening, observing, and defending a massive, enterprise-grade, multi-tenant, autonomous AI-native SaaS system from first principles, culminating in a live production defense before senior engineering leaders.

---
""")

    p14_data = [
        (1, "Enterprise Capstone I: System Architecture & Non-Functional Requirements",
         "Phase 8, Phase 12",
         ["Defining the enterprise project charter: building a multi-tenant, autonomous software intelligence and operations platform",
          "Scoping functional requirements: automated code review, security remediation, real-time telemetry analytics, autonomous bug repair",
          "Scoping non-functional requirements: $99.99\\%$ uptime SLA, sub-200ms API p99 latency, zero cross-tenant data leakage",
          "Architecture Decision Records (ADRs): documenting technology choices across database, frontend, messaging, and AI models",
          "Threat modeling: defining security boundaries, zero-trust network policies, and PII compliance controls",
          "Creating the multi-repository vs monorepo workspace structure with Turborepo and strict dependency boundaries"],
         "Vague architectural boundaries leading to monolithic spaghetti code and circular dependencies between services.",
         "Author the complete System Architecture Specification and ADR documentation; pass an initial architectural review.",
         "Enterprise Capstone: System architecture document and ADRs."),

        (2, "Enterprise Capstone II: Relational Data Modeling & Multi-Tenant Isolation",
         "Phase 5, Phase 10",
         ["Designing the core relational schema in PostgreSQL: organizations, users, workspaces, repositories, agent tasks, audits",
          "Multi-tenant isolation patterns: Row-Level Security (RLS) vs schema-per-tenant vs database-per-tenant trade-offs",
          "Implementing PostgreSQL Row-Level Security (RLS): policies enforcing `WHERE organization_id = current_setting('app.current_org_id')`",
          "Migration pipeline: automated, backward-compatible migrations with Flyway/Prisma/Alembic in continuous delivery pipelines",
          "High-performance indexing: composite B-trees, GIN indexes on JSONB metadata, and partial indexes for active tasks",
          "Seeding the database: generating deterministic, realistic enterprise fixture data with millions of mock records for stress testing"],
         "Leaking tenant data due to missing RLS policies or forgotten `organization_id` filters on complex join queries.",
         "Implement and verify PostgreSQL Row-Level Security across 15 relational tables with automated multi-tenant isolation unit tests.",
         "Enterprise Capstone: Relational database schema with RLS."),

        (3, "Enterprise Capstone III: High-Throughput Event Streaming & Task Queues",
         "Phase 4, Phase 5, Phase 7",
         ["Asynchronous event backbone: deploying Apache Kafka KRaft clusters for high-throughput event ingestion",
          "Defining event schemas with Protocol Buffers: strict backward and forward schema compatibility guarantees",
          "Kafka producer pipeline: idempotent producers with `acks=all`, batching, and snappy compression",
          "Kafka consumer architecture: consumer groups, partition assignments, and non-blocking retry topics with exponential backoff",
          "Celery and Redis task queue integration: orchestrating long-running asynchronous background jobs with progress reporting",
          "Dead Letter Queues (DLQ) and alert routing: capturing failed messages, poison pills, and automated administrative replay"],
         "Message loss during consumer restarts; poison pills stalling partition consumption indefinitely without DLQs.",
         "Deploy Kafka and Celery streaming infrastructure; achieve 20,000 events/sec ingestion with zero dropped messages.",
         "Enterprise Capstone: Distributed event streaming and task queue pipeline."),

        (4, "Enterprise Capstone IV: Hybrid RAG Pipeline & Vector Search Engine",
         "Phase 10",
         ["Enterprise knowledge indexing: ingesting multi-format documentation, source code repositories, and user support tickets",
          "Layout-aware document parsing: extracting markdown hierarchies, AST symbol graphs, and tabular data",
          "Dual-stream hybrid retrieval: pgvector HNSW dense semantic search + PostgreSQL BM25 full-text search",
          "Reciprocal Rank Fusion (RRF): combining search result ranks into a unified candidate pool ($k=60$)",
          "Cross-Encoder re-ranking: scoring top-50 candidates down to top-5 high-relevance chunks using BAAI `bge-reranker-large`",
          "Evaluation gate: verifying with EvalKit that retrieval achieves Context Relevance $>0.88$ and Groundedness $>0.96$"],
         "Vector search returning outdated documentation versions due to missing temporal and version metadata filtering.",
         "Implement and evaluate the end-to-end hybrid RAG retrieval pipeline on 100,000 enterprise documents with sub-150ms latency.",
         "Enterprise Capstone: Production hybrid RAG and vector search service."),

        (5, "Enterprise Capstone V: Autonomous Multi-Agent Engineering Workflows",
         "Phase 12",
         ["Orchestrating autonomous workflows with LangGraph: Planner, Researcher, Coder, and QA Reviewer agent nodes",
          "Durable state persistence: `AsyncPostgresSaver` checkpointing every superstep to enable seamless crash recovery",
          "Human-in-the-Loop review gates: programmatic `interrupt()` triggers before deploying code or modifying database schemas",
          "Sandboxed tool execution: executing agent-generated Bash and Python scripts inside ephemeral gVisor-hardened Docker containers",
          "AST code navigation: Tree-sitter powered symbol extraction and non-destructive line-targeted diff patching",
          "Automated TDD loop: agent writes test, verifies failure, modifies source code, and validates full test suite pass"],
         "Agent entering infinite execution loops or executing destructive commands outside the sandboxed workspace boundary.",
         "Deploy the autonomous multi-agent engineering workflow; verify that it autonomously fixes bugs in a test repository.",
         "Enterprise Capstone: Autonomous multi-agent orchestration engine."),

        (6, "Enterprise Capstone VI: Full-Stack SaaS Web Application & Real-Time UI",
         "Phase 6",
         ["Next.js App Router architecture: nested layouts, React Server Components (RSC), and Server Actions",
          "CompKit design system integration: accessible, theme-aware UI primitives adhering to WCAG 2.2 AAA guidelines",
          "Real-time streaming interfaces: Server-Sent Events (SSE) streaming live LLM tokens and agent thought trajectories",
          "Interactive multi-agent dashboard: visualizing active agent state graphs, tool invocations, and diff approval modals",
          "Stripe subscription integration: self-service checkout, multi-tier seat licensing, customer billing portal, and webhooks",
          "Client-side performance engineering: optimizing Core Web Vitals to achieve 98+ Lighthouse scores across all pages"],
         "Client-side re-rendering waterfalls freezing UI during high-frequency agent streaming event floods.",
         "Build and deploy the complete Next.js full-stack web application; verify real-time SSE streaming and Stripe billing checkout.",
         "Enterprise Capstone: Full-stack web dashboard and user portal."),

        (7, "Enterprise Capstone VII: Automated Testing, Vitest & Playwright E2E",
         "Phase 1, Phase 5, Phase 6",
         ["Comprehensive testing pyramid: Unit tests ($>80\\%$ coverage), Integration tests, and End-to-End (E2E) test suites",
          "Backend integration testing: testing FastAPI endpoints, database migrations, and Kafka producers using `pytest` and `testcontainers`",
          "Frontend unit testing: testing React components, custom hooks, and state reducers with Vitest and React Testing Library",
          "Mocking external dependencies: Mock Service Worker (MSW) intercepting Stripe and LLM API calls in CI environments",
          "Playwright E2E automation: multi-browser tests covering user signup, workspace creation, agent invocation, and billing upgrade",
          "Visual regression testing: automated pixel-diff comparisons catching unintentional CSS layout regressions"],
         "Flaky E2E tests relying on arbitrary timeouts, breaking CI/CD deployment pipelines on minor network jitter.",
         "Execute the complete test suite: 500+ unit tests, 100+ integration tests, and 20 Playwright E2E journeys passing with 0 flakes.",
         "Enterprise Capstone: Automated test harness and E2E validation suite."),

        (8, "Enterprise Capstone VIII: Cloud Infrastructure as Code with Terraform",
         "Phase 7",
         ["Declarative infrastructure provisioning on Google Cloud Platform (GCP) using modular Terraform",
          "Remote state architecture: GCS backend with state locking, customer-managed KMS encryption, and environment segregation",
          "VPC and networking: multi-zone custom VPC, private subnets, Cloud NAT, and Private Google Access",
          "Managed Kubernetes: private VPC-native GKE cluster provisioning with Workload Identity and Cilium CNI",
          "Managed database and cache provisioning: Cloud SQL PostgreSQL instance and Memorystore Redis clusters with private IPs",
          "Automated Terraform CI/CD: running `tflint`, `tfsec`, and automated `terraform plan` on all pull requests"],
         "Manual cloud resource creation leading to un-tracked infrastructure drift and un-reproducible environments.",
         "Provision the complete multi-region cloud infrastructure from scratch using Terraform with a single automated apply.",
         "Enterprise Capstone: Production Terraform infrastructure repository."),

        (9, "Enterprise Capstone IX: Kubernetes Deployment, GitOps & ArgoCD",
         "Phase 7",
         ["Packaging applications: multi-stage OCI container builds producing minimal distroless images with 0 CVEs",
          "Kubernetes workload manifests: Deployments, StatefulSets, Services, and Gateway API HTTPRoute definitions",
          "Secret management: External Secrets Operator (ESO) synchronizing secrets from GCP Secret Manager into Kubernetes",
          "GitOps continuous delivery with ArgoCD: App-of-Apps pattern, automated sync policies, and self-healing reconciliation",
          "Horizontal Pod Autoscaling (HPA): autoscaling workloads dynamically based on real-time Prometheus QPS and CPU metrics",
          "Zero-downtime rolling updates: calibrated `preStop` hooks, termination grace periods, and readiness probe thresholds"],
         "Deploying containers as root or exposing plaintext secrets in git manifests, violating enterprise security policies.",
         "Deploy the full microservice fleet to GKE using ArgoCD GitOps; execute a rolling update with zero dropped client connections.",
         "Enterprise Capstone: Kubernetes manifests and ArgoCD GitOps repository."),

        (10, "Enterprise Capstone X: Distributed Observability, Tracing & Alerting",
         "Phase 7, Phase 11",
         ["End-to-end distributed tracing: OpenTelemetry (OTel) instrumentation across Next.js, FastAPI, Celery, and LangGraph",
          "Collecting telemetry: OTel Collector routing spans to Jaeger/Tempo, metrics to Prometheus, and logs to Grafana Loki",
          "Grafana dashboards: designing unified operational dashboards correlating request latency, error rates, and resource utilization",
          "Service Level Objectives (SLOs): configuring 99.9% availability and $<200$ms p95 latency SLOs with error budget alerts",
          "Prometheus Alertmanager: multi-window multi-burn-rate alerts routing critical pages to PagerDuty and warnings to Slack",
          "GenAI observability: tracking prompt tokens, completion tokens, LLM latency, and retrieval quality scores in Langfuse"],
         "Alert fatigue caused by low-threshold CPU alerts; missing distributed trace headers across asynchronous Celery task boundaries.",
         "Deploy the complete observability stack; trace a user request from frontend click through Kafka, Celery, and LLM to database.",
         "Enterprise Capstone: Enterprise observability and Grafana monitoring stack."),

        (11, "Enterprise Capstone XI: Production Profiling & Performance Tuning",
         "Phase 11",
         ["Profiling under load: identifying CPU and memory bottlenecks using `py-spy` and `memray` under sustained traffic",
          "Database query tuning: analyzing `pg_stat_statements`, eliminating slow sequential scans via optimized composite indexes",
          "Connection pool optimization: tuning PgBouncer transaction pooling to handle 5,000 concurrent client connections smoothly",
          "Memory leak elimination: locating and resolving reference cycles and uncollected buffers in background worker processes",
          "Kernel network tuning: applying Linux `sysctl` socket buffer and connection queue optimizations on worker nodes",
          "Performance validation: proving that API p99 latency decreased by $\\ge 40\\%$ and memory consumption dropped by $\\ge 25\\%$"],
         "Premature optimization of non-critical code paths without empirical flame graph evidence of performance impact.",
         "Profile the production system under load; eliminate the top 2 bottlenecks and document verified before/after flame graphs.",
         "Enterprise Capstone: Performance audit report and optimization patches."),

        (12, "Enterprise Capstone XII: High-Concurrency Load Testing with k6",
         "Phase 11",
         ["Designing realistic load testing scenarios: modeling peak traffic spikes, diurnal user patterns, and concurrent agent runs",
          "Writing modular k6 test scripts: simulating 10,000 concurrent Virtual Users (VUs) executing mixed read/write/streaming flows",
          "Executing distributed stress testing: running distributed k6 load generators generating 25,000 requests/second",
          "SLA verification under load: asserting that error rate remains $<0.01\\%$ and p95 latency remains $<200$ms under peak load",
          "Identifying breaking points: pushing system load beyond capacity until throughput plateaus and graceful load shedding engages",
          "Authoring the Load Test Verification Report: documenting system capacity limits, bottleneck analysis, and scaling recommendations"],
         "Conducting load tests with static identical data payloads, triggering unrealistic 100% cache hit rates on all requests.",
         "Execute a 25,000 QPS distributed k6 load test; verify that system maintains all SLA latency thresholds without crashing.",
         "Enterprise Capstone: Comprehensive load testing report and k6 test suite."),

        (13, "Enterprise Capstone XIII: Chaos Engineering & Resilience Validation",
         "Phase 7, Phase 11",
         ["Validating system self-healing: testing whether the system survives component failures under active production load",
          "LitmusChaos experiment execution: terminating primary database pods, injecting 30% packet loss, killing Kubernetes worker nodes",
          "Verifying fault tolerance: testing automated database failover, Kafka consumer rebalancing, and circuit breaker trip mechanics",
          "Evaluating user impact during chaos: proving that customer API requests experience zero data loss and $<0.5\\%$ transient errors",
          "Disaster recovery drill: executing an automated cluster restoration drill from Velero backups into a secondary cloud region",
          "Resilience certification: compiling the Chaos Verification Report proving compliance with five-nines availability principles"],
         "Failing to automate chaos experiments, leaving critical failover procedures untested until an actual production outage strikes.",
         "Execute a multi-fault LitmusChaos experiment during active load testing; prove zero data corruption and automated recovery under 60s.",
         "Enterprise Capstone: Chaos engineering verification report."),

        (14, "Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance",
         "Phase 5, Phase 10, Phase 13",
         ["Executing a comprehensive pre-launch security audit: scanning all codebases with Semgrep SAST and containers with Trivy",
          "Penetration testing: conducting authenticated and unauthenticated penetration attacks against web APIs and agent sandboxes",
          "Prompt injection red-teaming: testing 20 direct and indirect prompt injection attacks against the autonomous agent pipelines",
          "PII and data privacy audit: verifying Microsoft Presidio PII redaction and testing GDPR data deletion workflows",
          "Zero-Trust verification: inspecting mTLS certificate rotation and Kubernetes network policy default-deny enforcement",
          "Compiling the Security & Compliance Dossier: documenting threat mitigations, SOC2 Type II controls, and vulnerability remediation"],
         "Launching an enterprise platform with open container egress or un-redacted user PII in distributed application logs.",
         "Pass the automated security and penetration audit with 0 critical or high vulnerabilities; verify 100% prompt injection containment.",
         "Enterprise Capstone: Security audit dossier and penetration test report."),

        (15, "Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense",
         "Phase 8, Phase 11",
         ["Authoring Production Runbooks: step-by-step diagnostic workflows for alert triage, database failbacks, and incident escalation",
          "Service Level Agreement (SLA) contract defense: presenting documented error budget policies and disaster recovery runbooks",
          "Disaster Recovery (DR) sign-off: proving Recovery Point Objective (RPO) $< 1\\text{ minute}$ and Recovery Time Objective (RTO) $< 15\\text{ minutes}$",
          "The Production Engineering Live Defense: delivering a 60-minute technical architectural presentation to senior engineering staff",
          "Defending architectural trade-offs: answering rigorous interrogation on consistency models, scaling bottlenecks, and cost trade-offs",
          "Final project certification: signing off on code quality, test coverage, deployment automation, and production readiness"],
         "Inability to explain why an architectural decision was chosen over alternatives when questioned by senior engineering leadership.",
         "Successfully defend the entire Enterprise Capstone architecture in a 60-minute live presentation, answering all technical challenges.",
         "Enterprise Capstone: Production Runbooks, DR Plan, and Capstone Sign-off.")
    ]

    for item in p14_data:
        out.append(format_lesson(14, item[0], item[1], item[2], item[3], item[4], item[5], item[6]))

    out.append("""
### Phase 14 Capstone Deliverables
- **Enterprise Unified Capstone**: The ultimate full-stack, multi-tenant, autonomous AI-native SaaS platform codifying every concept across all 14 preceding phases: PostgreSQL with Row-Level Security, Kafka event streaming, Celery task queues, hybrid RAG with pgvector and BM25, LangGraph multi-agent orchestration, Next.js 14 App Router, CompKit design system, Terraform cloud infrastructure on GKE, ArgoCD GitOps, OpenTelemetry observability, k6 load testing, LitmusChaos resilience, and automated DevSecOps pipelines.

### Phase 14 Exit Benchmark (The Ultimate Mastery Benchmark)
- Successfully present and defend the live, deployed Enterprise Capstone in a rigorous 60-minute technical architecture defense without notes or preparation slides.
- Undergo a blind, unannounced fault injection during the live defense (simulated database pod failure under active traffic); the system must self-heal with zero data corruption and restore steady-state SLAs within 60 seconds.
""")
    return "\n".join(out)

if __name__ == "__main__":
    p12 = generate_phase12()
    p13 = generate_phase13()
    p14 = generate_phase14()
    print(f"Phase 12: {p12.count('#### Lesson ')} lessons")
    print(f"Phase 13: {p13.count('#### Lesson ')} lessons")
    print(f"Phase 14: {p14.count('#### Lesson ')} lessons")
    print(f"Total: {p12.count('#### Lesson ') + p13.count('#### Lesson ') + p14.count('#### Lesson ')} lessons")
