# gen_phase8_9.py
from helper import format_lesson

def generate_phase8():
    out = []
    out.append("""## Phase 8: Systems Design, High-Availability Architectures & Interview Mastery
**Target Duration**: 3 Weeks (Lessons 8.1 – 8.30)
**Core Focus**: End-to-end system design methodology, back-of-the-envelope estimation math, data modeling at massive scale, deep dives into 10 canonical production systems, trade-off defense, failure mitigation, and Architecture Decision Records (ADRs).

---
""")

    p8_data = [
        (1, "The 4-Step System Design Interview Framework & Requirement Scoping",
         "Phase 4, Phase 7",
         ["Step 1: Scoping functional requirements (core user journeys) vs non-functional requirements (latency, availability, scale)",
          "Defining out-of-scope boundaries to prevent architectural derailment during interview discussions",
          "Step 2: Back-of-the-envelope capacity estimation: QPS, bandwidth, storage, memory, and cache projections",
          "Step 3: High-Level Architecture (HLA): client, CDN, load balancer, API gateway, stateless services, cache, and database",
          "Step 4: Deep Dive & Bottlenecks: identifying single points of failure, partition tolerance, and failover workflows",
          "Collaborative communication: driving the discussion, active listening, asking clarifying questions, and managing time"],
         "Jumping straight into database schemas or microservices without scoping functional and non-functional requirements.",
         "Write a structured 1-page system requirements specification (SRS) for a global link shortening platform under 15 minutes.",
         "System Design Portfolio: Requirement scoping templates."),

        (2, "Back-of-the-Envelope Estimation: Numbers Every Engineer Must Know",
         "Phase 0, Lesson 8.1",
         ["Latency numbers to memorize: L1 cache (1ns), RAM (100ns), SSD read (100µs), HDD seek (10ms), cross-datacenter RTT (150ms)",
          "Throughput calculations: converting Monthly Active Users (MAU) and Daily Active Users (DAU) to Read/Write QPS",
          "Peak multiplier heuristics: average QPS vs peak QPS (typically $2\\times$ to $5\\times$ average load)",
          "Storage volumetric estimation: bytes per record $\\times$ records per day $\\times$ retention years $\\times$ replication factor",
          "Bandwidth volumetric estimation: ingress bandwidth (write QPS $\\times$ payload size) vs egress bandwidth (read QPS $\\times$ payload size)",
          "Memory and cache sizing: 80/20 Pareto rule (20% of hot data generates 80% of read traffic) memory provisioning"],
         "Confusing bits (Gbps) with bytes (GB/s); failing to account for peak load spikes leading to 50% infrastructure under-provisioning.",
         "Calculate exact QPS, storage (5-year), RAM cache, and bandwidth requirements for Twitter (500M DAU) with zero calculator aids.",
         "System Design Portfolio: Automated capacity planning spreadsheet."),

        (3, "Data Storage Paradigms & Database Selection Matrix",
         "Phase 4, Phase 7",
         ["Relational (RDBMS) vs NoSQL: ACID guarantees vs horizontal scalability, schema flexibility, and query patterns",
          "Document stores (MongoDB): nested denormalized hierarchical documents, index structures, and write-heavy workloads",
          "Wide-column stores (Cassandra, ScyllaDB): log-structured merge trees (LSM), tunable consistency, high write throughput",
          "Key-Value stores (Redis, DynamoDB): lightning sub-millisecond lookups, TTL expirations, and partition keys",
          "Graph databases (Neo4j): vertex and edge traversal, index-free adjacency, and social graph fraud detection",
          "Time-series databases (InfluxDB, TimescaleDB): columnar compression, downsampling, and high-frequency sensor/metric ingestion"],
         "Choosing NoSQL for financial balances without transactional multi-record atomicity; choosing RDBMS for petabyte append-only logs.",
         "Draft a comprehensive technical decision matrix comparing PostgreSQL, Cassandra, DynamoDB, and Redis across 8 operational criteria.",
         "System Design Portfolio: Database architectural selection guide."),

        (4, "Caching Architectures: Invalidation, Thundering Herd & Topologies",
         "Phase 4, Lesson 8.2",
         ["Caching topologies: In-memory local cache vs Distributed cache clusters (Redis, Memcached) vs Multi-tier caching",
          "Cache access patterns: Cache-Aside (Lazy Loading), Read-Through, Write-Through, and Write-Behind (Write-Back)",
          "Cache eviction policies: Least Recently Used (LRU), Least Frequently Used (LFU), First In First Out (FIFO)",
          "Cache Invalidation problems: cache stampede / thundering herd mitigation using mutex locking, probabilistic early expiration (XFetch)",
          "Cache Penetration (queries for non-existent keys): mitigating via null caching and Bloom filters",
          "Cache Breakdown (hot key expiry) and Cache Avalanche (simultaneous massive key expirations) mitigation with TTL jitter"],
         "Cache avalanche crashing core databases when 100,000 keys expire at midnight simultaneously without randomized TTL jitter.",
         "Implement the XFetch probabilistic early cache expiration algorithm in Python; simulate high-concurrency read traffic under load.",
         "System Design Portfolio: High-throughput caching architectural patterns."),

        (5, "Load Balancing, Reverse Proxies & Anycast Routing",
         "Phase 4, Phase 7",
         ["Layer 4 (Transport, TCP/UDP) vs Layer 7 (Application, HTTP/gRPC) load balancing trade-offs and SSL termination",
          "Load balancing algorithms: Round Robin, Weighted Least Connections, IP Hash, and Consistent Hashing",
          "Anycast BGP routing: announcing the same IP address globally to route client traffic to the nearest topological datacenter",
          "Reverse proxy mechanics: NGINX and Envoy proxy internals, connection pooling, buffer management, and gzip/brotli compression",
          "Direct Server Return (DSR): high-throughput video streaming optimization bypassing load balancers for egress traffic",
          "High-availability load balancers: Active-Passive configurations using VRRP (Virtual Router Redundancy Protocol) and Keepalived"],
         "Layer 7 load balancer becoming CPU-bound due to un-offloaded TLS handshakes without dedicated cryptographic hardware.",
         "Configure an Envoy proxy topology demonstrating Layer 7 content-based routing, weighted canary traffic splitting, and circuit breaking.",
         "System Design Portfolio: Global edge routing and load balancing blueprints."),

        (6, "API Gateway Architectures, Rate Limiting & Aggregation",
         "Phase 4, Lesson 8.5",
         ["API Gateway responsibilities: request routing, protocol translation (gRPC to JSON), authentication, and telemetry",
          "Backend-For-Frontend (BFF) pattern: tailored API gateways for mobile, web, and public developer clients",
          "Distributed Rate Limiting algorithms: Token Bucket, Leaky Bucket, Sliding Window Counter with Redis and Lua scripts",
          "Distributed rate limiting synchronization: centralized Redis vs local memory with gossip protocol synchronization",
          "Request aggregation and batching: combining multiple microservice calls into single client responses to reduce latency",
          "Security controls at the gateway: IP whitelisting, geo-blocking, DDoS mitigation, and WAF rule evaluation"],
         "Centralized Redis rate limiter creating a single point of failure and adding 10ms latency overhead to every API request.",
         "Implement a sliding window counter rate limiter in Redis Lua script handling 50,000 concurrent requests with zero race conditions.",
         "System Design Portfolio: Enterprise API Gateway and rate limiting architecture."),

        (7, "Message Queues vs Event Streams: Decoupling Asynchronous Systems",
         "Phase 4, Phase 7",
         ["Queue-based messaging (RabbitMQ, SQS): push model, message acknowledgment, individual message consumption, worker pools",
          "Log-based event streaming (Kafka, Kinesis): pull model, partitioned commit logs, ordered replayability, consumer groups",
          "Choosing between Queues and Streams: complex routing/task distribution vs high-throughput real-time event analytics",
          "Message delivery guarantees: At-most-once, At-least-once, Exactly-once processing (idempotent consumers)",
          "Dead Letter Queues (DLQ) and retry backoff strategies: handling poisoned messages without blocking queue pipelines",
          "Event-driven architecture patterns: Event Sourcing, Command Query Responsibility Segregation (CQRS), and Saga choreography"],
         "Using a message queue as a permanent database without understanding broker storage limits and memory backpressure.",
         "Design an end-to-end asynchronous order processing architecture comparing RabbitMQ task queues with Kafka event streaming.",
         "System Design Portfolio: Asynchronous event messaging blueprints."),

        (8, "Database Sharding, Partitioning & Rebalancing Strategies",
         "Phase 4, Phase 7",
         ["Vertical partitioning (splitting columns) vs Horizontal partitioning / Sharding (splitting rows across machines)",
          "Sharding key selection: cardinality, query access patterns, avoiding hot spots (celebrity problem)",
          "Sharding strategies: Range-based sharding vs Hash-based sharding vs Directory-based (lookup table) sharding",
          "Consistent Hashing in database sharding: minimizing data movement during node additions and removals",
          "Cross-shard queries and joins: scatter-gather queries, two-phase commit over shards, and why cross-shard joins are anti-patterns",
          "Live sharding rebalancing: migrating partitions online without downtime using dual-writes and asynchronous reconciliation"],
         "Selecting a monotonically increasing auto-increment ID as sharding key, concentrating 100% of all write traffic on the latest single shard.",
         "Implement a consistent hashing sharding manager in Python mapping keys across 16 database shards with virtual node balancing.",
         "System Design Portfolio: Scalable database sharding architecture."),

        (9, "High Availability, Redundancy & Active-Active Failover",
         "Phase 7, Lesson 8.8",
         ["High Availability (HA) metrics: 99.9% (Three Nines, 8.76h downtime/yr) vs 99.999% (Five Nines, 5.26m downtime/yr)",
          "Redundancy models: Active-Passive (Warm/Cold standby) vs Active-Active multi-region deployment architectures",
          "Automated failover mechanics: health heartbeats, split-brain detection, fencing tokens, and DNS TTL considerations",
          "Active-Active data synchronization: conflict-free replication, asynchronous cross-region replication, and multi-master conflicts",
          "GeoDNS and Latency-based Anycast routing: steering global users dynamically to healthy regions during catastrophic disasters",
          "Designing for disaster recovery: mean time to detect (MTTD), mean time to recover (MTTR), and chaos game days"],
         "Split-brain condition causing two active masters in different datacenters to accept conflicting writes during network partition.",
         "Draft an Active-Active multi-region architecture diagram with failover runbooks and split-brain fencing token safety proofs.",
         "System Design Portfolio: Global multi-region high-availability blueprint."),

        (10, "Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers",
         "Phase 0, Phase 7",
         ["Unique ID requirements: 64-bit size, globally unique, roughly time-ordered, high generation throughput (>1M IDs/sec)",
          "UUIDv4 limitations: 128-bit size, completely random ordering causing catastrophic B-tree fragmentation and index bloat",
          "UUIDv7 modern standard: Unix timestamp prefix + random suffix combining time-ordering with standard 128-bit formats",
          "Flickr Ticket Server: centralized MySQL servers with auto-increment and `REPLACE INTO` statements (single point of failure risks)",
          "Twitter Snowflake architecture: 1-bit unused, 41-bit timestamp (epoch ms), 10-bit machine/worker ID, 12-bit sequence number",
          "Handling clock drift in Snowflake: NTP backwards time adjustments, refusing generation, or waiting for clock synchronization"],
         "Server clock moving backwards during NTP sync generating duplicate IDs in Twitter Snowflake algorithm without drift safeguards.",
         "Implement a fully functional Twitter Snowflake 64-bit ID generator in Python handling 4,096 IDs per millisecond with clock rollback checks.",
         "System Design Portfolio: Distributed ID generation system design."),

        (11, "System Deep Dive 1: Global URL Shortener (TinyURL / Bitly)",
         "Lesson 8.1, Lesson 8.10",
         ["Requirements: 100M URLs created/month, 100:1 read-to-write ratio, sub-10ms redirection latency, custom alias support",
          "Capacity estimation: 100M writes/month $\\approx 40$ write QPS, 4,000 read QPS; 5-year storage: $\\approx 15\\text{TB}$",
          "URL encoding algorithms: Base62 encoding (a-z, A-Z, 0-9) vs MD5/SHA256 hashing truncation with collision handling",
          "Pre-generated Key Generation Service (KGS): dedicated service generating unique Base62 tokens ahead of time into Redis/DB",
          "Data modeling: relational vs NoSQL schema, primary keys, indexing short URL tokens, and expiration timestamps",
          "High-performance redirection: HTTP 301 Permanent Redirect (client caching) vs HTTP 302 Temporary Redirect (telemetry tracking)"],
         "Using HTTP 301 preventing server-side click analytics tracking; MD5 hash collisions requiring expensive database retry loops.",
         "Produce a complete architectural blueprint for TinyURL featuring KGS token generation, Redis caching, and Cassandra storage.",
         "System Design Portfolio: Project 1 - Global URL Shortener."),

        (12, "System Deep Dive 2: High-Throughput Distributed Rate Limiter",
         "Lesson 8.6, Lesson 8.10",
         ["Requirements: protect APIs from DDoS and abuse, enforce multi-tier tenant quotas, sub-2ms latency overhead",
          "Capacity estimation: 1,000,000 requests/second global API ingress; tracking millions of unique client IP/API keys",
          "Algorithm trade-offs: Token Bucket vs Sliding Window Counter vs Leaky Bucket across high concurrency",
          "Distributed architecture: Edge API gateways with local caching + central Redis clusters using pipelined Lua scripts",
          "Race condition mitigation: eliminating check-then-set race conditions using atomic Redis Lua scripts",
          "Handling Redis cluster outages: failing open (allowing traffic) vs failing closed (blocking traffic) under security SLAs"],
         "Failing closed during rate limiter redis outage, taking down entire company API for all legitimate paying customers.",
         "Produce a complete architectural blueprint for an enterprise rate limiter handling 1M QPS with localized synchronization.",
         "System Design Portfolio: Project 2 - Distributed Rate Limiter."),

        (13, "System Deep Dive 3: Distributed Web Crawler & Indexer",
         "Lesson 8.3, Lesson 8.7",
         ["Requirements: crawl 1 billion web pages per month, respect robots.txt, avoid infinite crawl traps, extract links and text",
          "Capacity estimation: 1B pages/month $\\approx 400$ pages/sec; storing raw HTML (100TB/month), inverted index extraction",
          "Crawl frontier architecture: prioritized queues, politeness queues (per-host rate limiting), and DNS caching layer",
          "Duplicate URL detection: Fingerprinting web page content using SimHash and 64-bit Bloom filters for billions of URLs",
          "Distributed worker architecture: stateless crawler pods, distributed task scheduling via Kafka, and S3 object storage ingestion",
          "Parsing & extraction pipeline: headless browser rendering (for JS-rendered SPAs) vs lightweight HTTP parsing trade-offs"],
         "Getting caught in infinite calendar crawl traps (`/calendar?day=X+1`); overloading small web servers violating politeness rules.",
         "Produce a complete architectural blueprint for a distributed web crawler crawling 1B pages with SimHash deduplication.",
         "System Design Portfolio: Project 3 - Distributed Web Crawler."),

        (14, "System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X)",
         "Lesson 8.4, Lesson 8.7",
         ["Requirements: 500M DAU, post tweets, follow users, generate timeline news feeds, real-time fanout",
          "Capacity estimation: 500M DAU, 5,000 tweets/sec average, 25,000 peak; timeline reads 500,000 QPS",
          "Fanout-on-Write (Push model): writing tweet IDs directly into followers' Redis home timeline lists upon post",
          "Fanout-on-Read (Pull model): fetching and merging tweets dynamically when a user requests their timeline",
          "The Celebrity / Hotspot Problem: why Push models fail for users with 100M followers (Taylor Swift, Elon Musk)",
          "Hybrid Fanout Architecture: Push for standard users, Pull for high-follower celebrity accounts, merged at read time"],
         "Attempting Push fanout on a 100M follower user causing 10-minute fanout processing lag and overwhelming Redis cluster queues.",
         "Produce a complete architectural blueprint for Twitter's news feed using hybrid push/pull fanout and Redis caching.",
         "System Design Portfolio: Project 4 - Social Media News Feed."),

        (15, "System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack)",
         "Lesson 8.5, Lesson 8.7",
         ["Requirements: 1-on-1 chat, group chat (up to 1,000 users), read receipts, offline message storage, end-to-end encryption (E2EE)",
          "Capacity estimation: 2B users, 100B messages/day $\\approx 1.15\\text{M}$ messages/sec; peak 3M msgs/sec",
          "Connection management: maintaining persistent bidirectional WebSocket / TCP connections across millions of chat gateways",
          "Session Service and User-to-Gateway mapping: tracking which gateway holds the active socket for user $X$ via Redis",
          "Message delivery workflow: online routing through gateways vs offline message persistence in Cassandra / DynamoDB",
          "Group chat fanout: server-side fanout queues vs client-side individual sends, managing group state and message ordering"],
         "Chat servers crashing and disconnecting 500,000 active WebSockets simultaneously, triggering a catastrophic reconnection storm.",
         "Produce a complete architectural blueprint for a global chat platform supporting 2B users with WebSocket connection servers.",
         "System Design Portfolio: Project 5 - Real-Time Chat Platform."),

        (16, "System Deep Dive 6: Large-Scale Video Streaming Platform (YouTube / Netflix)",
         "Lesson 8.5, Lesson 8.8",
         ["Requirements: upload videos, automated multi-bitrate transcoding, adaptive streaming playback (HLS, DASH), search, comments",
          "Capacity estimation: 500 hours uploaded/minute; storage: petabytes/day; egress bandwidth: tens of Terabits/second",
          "Video ingestion pipeline: chunked multipart upload directly to object storage (S3/GCS) with presigned URLs",
          "Transcoding architecture: distributed DAG worker pools splitting videos into chunks, encoding (H.264, AV1) at multiple resolutions",
          "Adaptive Bitrate Streaming (ABR): HLS `.m3u8` master playlists, segment delivery (`.ts` / `.m4s`), client-driven bitrate adaptation",
          "Content Delivery Network (CDN) strategy: tiered caching (edge POPs, regional mid-tier caches, origin shields) and Open Connect appliances"],
         "Transcoding jobs stalling on massive 4K video files without chunked parallel processing; origin servers melted by CDN cache misses.",
         "Produce a complete architectural blueprint for video ingestion, parallel transcoding pipelines, and multi-CDN edge delivery.",
         "System Design Portfolio: Project 6 - Video Streaming Architecture."),

        (17, "System Deep Dive 7: Distributed Cloud Object Storage (Amazon S3 / Google Cloud Storage)",
         "Lesson 7.4, Lesson 8.8",
         ["Requirements: store billions of arbitrary binary objects (blobs), 99.999999999% (11 Nines) durability, multi-part uploads",
          "Decoupling Metadata from Blob Data: metadata storage in distributed LSM/key-value stores, raw binary chunks on raw disk servers",
          "Durability mechanics: Triple replication vs Erasure Coding (e.g. Reed-Solomon $8+4$ scheme) storage overhead reduction (1.5x vs 3x)",
          "Chunking and placement architecture: breaking files into 64MB chunks, consistent hashing placement, failure domain isolation",
          "Garbage collection and compaction: reclaiming deleted object chunks asynchronously without blocking write paths",
          "Data integrity verification: end-to-end CRC32 / MD5 checksumming, background scrubbing to detect silent bit-rot on disk"],
         "Silent bit rot on physical hard drives corrupting stored files without detection; metadata index becoming a bottleneck.",
         "Produce a complete architectural blueprint for a distributed blob storage system with Erasure Coding and background data scrubbing.",
         "System Design Portfolio: Project 7 - Distributed Object Storage."),

        (18, "System Deep Dive 8: Collaborative Document Editing System (Google Docs / Figma)",
         "Lesson 7.5, Lesson 8.15",
         ["Requirements: multi-user real-time concurrent editing, cursor presence, offline editing support, version history, low latency",
          "Concurrency models comparison: Pessimistic Locking vs Operational Transformation (OT) vs CRDTs (Conflict-Free Replicated Data Types)",
          "Operational Transformation (OT) deep dive: Central server sequencing, transforming operations against concurrent states",
          "CRDT text sequences (RGA, Yjs, Automerge): peer-to-peer capability, mathematical convergence, and memory overhead",
          "Session server architecture: routing all collaborators of document $D$ to the same stateful session server via consistent hashing",
          "Compaction and snapshots: periodically snapshotting document state to persistent storage and truncating operation logs"],
         "Operational transformation divergence bugs in peer-to-peer topologies; memory explosion from retaining millions of granular keystroke CRDT tombstones.",
         "Produce a complete architectural blueprint for Google Docs using centralized OT and WebSocket session affinity.",
         "System Design Portfolio: Project 8 - Collaborative Document Editing."),

        (19, "System Deep Dive 9: Real-Time Ride-Hailing Geospatial Service (Uber / Lyft)",
         "Lesson 8.3, Lesson 8.15",
         ["Requirements: match riders with nearby drivers, real-time location updates (every 4s per driver), surge pricing, ETA calculation",
          "Capacity estimation: 5M active drivers reporting GPS every 4 seconds $\\approx 1.25\\text{M}$ GPS writes/second",
          "Geospatial indexing algorithms: Geohashes vs Google S2 Geometry vs Uber H3 (hexagonal hierarchical spatial index)",
          "Why hexagons (Uber H3): uniform distance to all 6 neighboring cells, avoiding distortion in square or rectangular grids",
          "Location ingestion architecture: high-throughput Kafka streaming, ephemeral geospatial in-memory store (Redis GEO / custom memory grid)",
          "Driver matching service: spatial range query (within radius $R$), filtering eligible drivers, dispatch locking via Redis distributed locks"],
         "Driver location updates overwhelming disk-backed relational databases; race conditions where multiple riders match the same driver simultaneously.",
         "Produce a complete architectural blueprint for Uber driver ingestion and geospatial dispatch matching using Uber H3 and Redis.",
         "System Design Portfolio: Project 9 - Real-Time Ride-Hailing Service."),

        (20, "System Deep Dive 10: Financial Transaction Ledger & Payment Processing (Stripe)",
         "Phase 4, Lesson 7.6",
         ["Requirements: zero double-spend, strict ACID compliance, double-entry bookkeeping, audit trail, PCI-DSS compliance",
          "Double-entry bookkeeping principle: every transaction must balance (Debits = Credits); immutable append-only ledger entries",
          "Idempotency architecture: client-provided idempotency keys, atomic check-and-insert in database before payment processor calls",
          "Handling external payment gateways: asynchronous webhooks, reconciliation jobs, network timeouts, and state machines",
          "Distributed lock vs Database serializability: preventing concurrent withdrawal race conditions on account balances",
          "Financial reconciliation engine: matching bank settlement files against internal transaction ledgers to detect discrepancy"],
         "Network timeout during external payment charge treated as failure, causing duplicate customer charge on naive retry.",
         "Produce a complete architectural blueprint for an immutable double-entry financial ledger with end-to-end idempotency guarantees.",
         "System Design Portfolio: Project 10 - Financial Transaction Ledger."),

        (21, "Search Engine Architecture: Inverted Index & Distributed Search (Elasticsearch)",
         "Lesson 8.3, Lesson 8.8",
         ["Search fundamentals: documents, fields, text tokenization, stemming, stop-word removal, and inverted index data structures",
          "Inverted index mechanics: posting lists, term dictionary, term index (FST - Finite State Transducers), and SkipLists",
          "Distributed search architecture: Sharding indices, primary vs replica shards, coordinator nodes, scatter-gather query execution",
          "Relevance ranking algorithms: TF-IDF (Term Frequency - Inverse Document Frequency) and modern BM25 probabilistic scoring",
          "Index updates and near real-time (NRT) search: Lucene segments, in-memory buffer, commit log (translog), and background segment merging",
          "Handling search traffic spikes: caching filter queries, routing keys for targeted sharding, and deep pagination limits (`search_after`)"],
         "Performing deep pagination (`from: 100000`) causing out-of-memory crash across search coordinator nodes; expensive un-cached wildcard queries.",
         "Design an enterprise search infrastructure indexing 50M documents with BM25 ranking and scatter-gather coordinator nodes.",
         "System Design Portfolio: Enterprise Distributed Search Engine."),

        (22, "Notification Engine: Multi-Channel Delivery, Batching & Deduplication",
         "Lesson 8.7, Lesson 8.12",
         ["Requirements: multi-channel notifications (Push, SMS, Email, In-app), priority queues, template rendering, user preferences",
          "System architecture: Notification API, preference verification service, template engine, and channel worker pools",
          "Third-party provider integration: APNs (Apple), FCM (Google), Twilio (SMS), SendGrid (Email); handling third-party rate limits",
          "Notification batching and digesting: grouping high-frequency events (e.g. '5 people liked your photo') using Redis time windows",
          "Deduplication mechanisms: idempotency keys, Redis sliding window hash deduplication preventing spam notifications",
          "Delivery tracking and fallback routing: tracking delivery callbacks, falling back from Push to SMS upon delivery timeout"],
         "Notification storm caused by an un-throttled batch job sending millions of pushes, burning third-party API quotas and getting accounts banned.",
         "Design a resilient multi-channel notification engine with user preference filtering, message batching, and automated provider fallbacks.",
         "System Design Portfolio: Scalable Notification Engine."),

        (23, "Metrics & Telemetry Pipeline: High-Throughput Time-Series Ingestion",
         "Phase 7, Lesson 8.7",
         ["Requirements: ingest 10M metric data points/sec, downsampling, real-time alerting, long-term retention, sub-second query latency",
          "Metrics data model: metric name, timestamp, key-value tag dimensions, and floating-point numeric value",
          "Ingestion architecture: local daemon agents (StatsD/OTel), load-balanced Kafka stream buffers, and stream processing engines (Flink)",
          "Storage architecture: Time-Series Databases (VictoriaMetrics, ClickHouse, Prometheus), columnar compression, delta-of-delta timestamps",
          "Rollup and downsampling pipelines: aggregating 1-second raw metrics into 1-minute, 1-hour, and 1-day rollups over time",
          "Query engine optimization: inverted index over label tag combinations, caching query results, and partition pruning"],
         "Cardinality explosion when application code dynamically adds user IDs as metric labels, crashing time-series storage memory.",
         "Design a 10M events/sec telemetry ingestion pipeline featuring Kafka streaming, ClickHouse columnar storage, and downsampling.",
         "System Design Portfolio: High-Throughput Telemetry Pipeline."),

        (24, "E-Commerce Flash Sale System: High-Concurrency Inventory Reservation",
         "Phase 4, Lesson 8.8",
         ["Requirements: 10,000 items available, 1,000,000 users attempting to buy at 12:00:00, zero overselling, fair ordering",
          "The overselling problem: classic check-then-act database updates causing inventory to drop below zero under high concurrency",
          "Multi-layer traffic filtering: CDN static asset caching, API gateway rate limiting, and CAPTCHA challenge verification",
          "In-memory inventory reservation: atomic inventory decrement in Redis using Lua scripts (`if stock >= qty then decr end`)",
          "Asynchronous order creation: pushing successful reservations into Kafka for asynchronous database order generation",
          "Unpaid order release: transactional outbox pattern, scheduled TTL expiration returning un-purchased inventory back to Redis stock pool"],
         "Database row-locking contention crashing PostgreSQL when 50,000 transactions attempt to update the same inventory row simultaneously.",
         "Design a flash sale inventory reservation system using Redis Lua scripts, Kafka queuing, and automated 15-minute payment expiration.",
         "System Design Portfolio: Flash Sale Inventory Architecture."),

        (25, "Distributed Task Scheduler: Quartz, Temporal & Workflow Orchestration",
         "Phase 7, Lesson 8.7",
         ["Task scheduling paradigms: Cron-based recurring jobs vs Delayed tasks vs Complex multi-step directed acyclic graph (DAG) workflows",
          "Distributed cron architecture: leader-elected scheduler nodes, database task leases, and preventing duplicate executions",
          "Delayed task queue architecture: Redis Sorted Sets (`ZADD` with execute timestamp score, `ZRANGEBYSCORE` polling workers)",
          "Workflow Orchestration with Temporal / Airflow: durable execution, event history replay, state machine persistence, and compensation logic",
          "Handling task worker failures: heartbeats, automatic task reassignment, exponential backoff, and idempotent task execution",
          "Scalability: partitioning task queues by tenant, priority weighting, and worker auto-scaling based on queue depth"],
         "Workers crashing mid-task without durable state checkpoints, causing long-running financial batch processes to restart from scratch.",
         "Design a durable distributed workflow orchestrator capable of executing multi-day saga transactions with automated step retries.",
         "System Design Portfolio: Distributed Workflow Orchestrator."),

        (26, "Content Delivery Networks (CDN) & Edge Computing Architecture",
         "Lesson 8.5, Lesson 8.16",
         ["CDN architectural topology: Points of Presence (PoPs), edge caching servers, transit peering, and origin shields",
          "Content caching strategies: Cache-Control headers (s-maxage, public, stale-while-revalidate, immutable), surrogate keys (Cache-Tags)",
          "Cache Purging at scale: instant global cache invalidation using surrogate keys across thousands of edge servers in <150ms",
          "Dynamic content acceleration: TCP connection reuse, TLS session resumption, and route optimization over private backbones",
          "Edge compute (Cloudflare Workers, Fastly Compute@Edge): executing V8 isolates at edge PoPs for A/B testing, auth checks, and redirects",
          "DDoS mitigation at the edge: Anycast bandwidth absorption, SYN flood filtering, and Web Application Firewall (WAF) rule sets"],
         "Serving personalized user dashboard pages with public Cache-Control headers, leaking private user data to other edge visitors.",
         "Design a global CDN architecture featuring origin shielding, instant surrogate key invalidation, and edge auth token verification.",
         "System Design Portfolio: Global CDN & Edge Architecture."),

        (27, "Modern Data Warehouses & Lakehouses: ClickHouse, Snowflake & Iceberg",
         "Lesson 8.3, Lesson 8.23",
         ["OLTP (Online Transaction Processing) vs OLAP (Online Analytical Processing): row-oriented vs columnar storage mechanics",
          "Columnar storage internals: Parquet files, dictionary encoding, run-length encoding (RLE), and vectorized SIMD query execution",
          "Data Lakehouse architecture: decoupling compute from storage (S3/GCS) with Apache Iceberg open table metadata formats",
          "ClickHouse architecture: MergeTree storage engine, primary key sparse indexes, data compression, and sub-second analytical queries",
          "ETL vs ELT pipelines: raw data ingestion, transformation via dbt/Spark, and analytical dimensional modeling (Star vs Snowflake schema)",
          "Data freshness vs Query speed: batch loading vs real-time streaming ingestion into analytical columnar stores"],
         "Running heavy analytical aggregation queries (`GROUP BY` over 100M rows) on production OLTP PostgreSQL instances.",
         "Design a real-time data lakehouse pipeline ingesting transaction events from Kafka into Apache Iceberg tables with ClickHouse analytics.",
         "System Design Portfolio: Enterprise Analytical Lakehouse Architecture."),

        (28, "Resiliency Engineering: Load Shedding, Graceful Degradation & Chaos Testing",
         "Phase 7, Lesson 8.9",
         ["System degradation under extreme load: queue latency amplification, memory exhaustion, and catastrophic thrashing",
          "Load Shedding mechanics: rejecting excess requests early at the gateway when CPU or queue wait times cross critical thresholds",
          "Graceful Degradation: disabling non-essential features (e.g. recommendations, comments) to preserve core workflows (checkout, reading)",
          "Prioritized traffic handling: classifying requests (critical, high, low) and dropping low-priority requests during emergencies",
          "Chaos Engineering in architecture: proactively testing component failures (simulating network partition, region outage, disk failure)",
          "Blast radius containment: cell-based architecture, dividing large fleets into independent, isolated failure domains (cells)"],
         "Allowing overloaded servers to attempt processing all requests, causing 100% of requests to timeout rather than shedding 20% to save 80%.",
         "Design a cell-based architecture with automated load shedding and graceful degradation modes for a mission-critical banking service.",
         "System Design Portfolio: Resiliency & Cell-Based Architecture."),

        (29, "Security, Governance & Compliance in Large-Scale Systems",
         "Phase 5, Phase 7",
         ["Zero-Trust Architecture: never trust, always verify; mutual TLS (mTLS) between all internal microservices with SPIFFE/SPIRE",
          "Data at rest and in transit encryption: customer-managed encryption keys (CMEK), envelope encryption with KMS, TLS 1.3 enforcement",
          "Identity and Access Management (IAM) at scale: role-based access control (RBAC), attribute-based access control (ABAC), policy enforcement",
          "Compliance standards: GDPR right-to-be-forgotten implementation in distributed append-only storage, SOC2 Type II controls, PCI-DSS",
          "Auditing and data lineage: immutable audit logs, tamper-evident log hashing, and tracking data provenance across pipelines",
          "Secret management: automated secret rotation, dynamic database credentials, and eliminating hardcoded secrets in source control"],
         "Failing to handle GDPR deletion requests across distributed Kafka backups and un-compacted analytical cold storage.",
         "Design a zero-trust financial microservice architecture with end-to-end mTLS, KMS envelope encryption, and GDPR compliance pipelines.",
         "System Design Portfolio: Enterprise Security & Compliance Architecture."),

        (30, "Architecture Decision Records (ADRs) & Defending Systems in Technical Reviews",
         "Lesson 8.1 through Lesson 8.29",
         ["Architecture Decision Records (ADR) format: Context, Decision, Status, Consequences (positive, negative, neutral)",
          "Structuring technical proposals: Request For Comments (RFC) process, gathering engineering feedback, driving alignment",
          "Defending design trade-offs: latency vs cost, consistency vs availability, operational simplicity vs maximum performance",
          "Live system design interview simulations: whiteboard navigation, managing ambiguous constraints, and handling pushback",
          "Production readiness reviews (PRR): operational checklists, monitoring coverage, runbooks, and rollback procedures",
          "Continuous architectural evolution: avoiding premature optimization while preventing architectural dead-ends"],
         "Presenting a system design as 'perfect' without acknowledging trade-offs, negative consequences, and failure modes.",
         "Write and defend a production-grade Architecture Decision Record (ADR) justifying the migration from PostgreSQL to Cassandra.",
         "System Design Portfolio: Production ADR and System Review Defense.")
    ]

    for item in p8_data:
        out.append(format_lesson(8, item[0], item[1], item[2], item[3], item[4], item[5], item[6]))

    out.append("""
### Phase 8 Capstone Deliverables
- **10 Production System Design Portfolios**: Fully documented architectural specifications, complete with back-of-the-envelope calculations, data schemas, high-level diagrams, deep-dive sequence diagrams, failure mode analyses, and ADRs for all 10 canonical production systems.

### Phase 8 Exit Benchmark
- Complete a 60-minute mock System Design interview defense with zero notes, successfully designing an active-active, multi-region architecture handling 1M+ QPS with fully verified capacity math and trade-off justification.
""")
    return "\n".join(out)


def generate_phase9():
    out = []
    out.append("""## Phase 9: Mathematics of Deep Learning, Autograd & Core Neural Architectures
**Target Duration**: 4 Weeks (Lessons 9.1 – 9.40)
**Core Focus**: Multidimensional tensor algebra, Strides, Einsum, analytical backpropagation, loss functions, optimization algorithms (AdamW), building an Autograd engine from scratch (GradFlow), PyTorch core execution mechanics, and implementing a Decoder-Only Transformer from scratch (TransformerLab).

---
""")

    p9_data = [
        (1, "Multidimensional Tensor Algebra: Vector Spaces & Inner Products",
         "Phase 2, Phase 3",
         ["Vector spaces over real numbers $\\mathbb{R}^n$: axioms, linear combinations, spanning sets, and linear independence",
          "Basis and dimension: standard basis, change of basis, and coordinate representations",
          "Inner product spaces: Euclidean dot product, geometric interpretation (angle, projection), and Cauchy-Schwarz inequality",
          "Vector norms: $L_1$ (Manhattan), $L_2$ (Euclidean), $L_p$, and $L_\\infty$ norms; sparsity-inducing properties of $L_1$",
          "Orthogonality and orthonormal bases: Gram-Schmidt orthogonalization process and orthogonal projection matrices",
          "Hyperplanes, half-spaces, and linear separability in machine learning feature spaces"],
         "Violating vector space dimensional compatibility during projection computations; dividing by zero when normalizing zero-vectors.",
         "Implement a vectorized linear projection engine in NumPy computing projections of high-dimensional vectors onto arbitrary subspaces.",
         "GradFlow: Fundamental vector math primitives."),

        (2, "Matrix Transformations, Ranks & Invertibility",
         "Lesson 9.1",
         ["Matrices as linear mappings $T: \\mathbb{R}^n \\to \\mathbb{R}^m$; domain, codomain, range, and kernel (null space)",
          "Matrix multiplication as composition of linear transformations; non-commutativity ($AB \\neq BA$)",
          "Fundamental Subspaces of a Matrix: Column space, Null space, Row space, and Left Null space (Rank-Nullity Theorem)",
          "Matrix rank: full row rank, full column rank, rank deficiency, and low-rank approximations in neural networks (LoRA)",
          "Determinants: geometric interpretation as volume scaling factor, properties, and singularity criteria",
          "Matrix inversion: inverse properties, conditions for invertibility, and numerical instability of direct matrix inversion"],
         "Computing explicit matrix inverses ($A^{-1}b$) instead of solving linear systems ($Ax=b$) via decomposition, causing massive precision loss.",
         "Write a matrix rank and null-space solver using Gaussian elimination with partial pivoting in pure Python/NumPy.",
         "GradFlow: Matrix transformation validation utilities."),

        (3, "Matrix Decompositions: LU, QR & Cholesky",
         "Lesson 9.2",
         ["LU Decomposition: factoring $A = PLU$ with partial pivoting; solving linear systems in $O(n^2)$ after $O(n^3)$ factorization",
          "QR Decomposition: factoring $A = QR$ with orthogonal $Q$ and upper triangular $R$ using Householder reflections and Givens rotations",
          "Solving least squares problems via QR decomposition: avoiding condition number squaring from normal equations ($A^TA x = A^Tb$)",
          "Cholesky Decomposition: factoring symmetric positive-definite matrices $A = LL^T$; efficiency and numerical stability",
          "Condition number of a matrix: $\\kappa(A) = \\|A\\| \\|A^{-1}\\|$; ill-conditioned systems and error amplification bounds",
          "Applications of matrix decompositions in deep learning: Whitening transformations, covariance modeling, and stable weight initializations"],
         "Attempting Cholesky factorization on non-positive-definite matrices; numerical overflow during un-pivoted LU elimination.",
         "Implement LU decomposition with partial pivoting and QR decomposition via Householder reflections from scratch in pure Python.",
         "GradFlow: Numerical linear algebra decomposition suite."),

        (4, "Spectral Theory: Eigenvalues, Eigenvectors & Diagonalization",
         "Lesson 9.3",
         ["Characteristic equation: $\\det(A - \\lambda I) = 0$, eigenvalues $\\lambda$, and eigenvectors $v$",
          "Geometric vs Algebraic multiplicity of eigenvalues, defective matrices, and conditions for matrix diagonalizability ($A = PDP^{-1}$)",
          "Spectral Theorem for Symmetric Matrices: real eigenvalues, orthogonal eigenvectors, and $A = Q \\Lambda Q^T$",
          "Quadratic forms: $x^T A x$, positive definite, positive semi-definite, and indefinite matrices; Hessian matrix connection",
          "Power Iteration algorithm: computing dominant eigenvalue and eigenvector of large sparse matrices",
          "Rayleigh quotient and its stationary points: connecting eigenvectors to extremal values of quadratic forms"],
         "Assuming all matrices are diagonalizable; power iteration failing to converge when dominant eigenvalues are equal in magnitude.",
         "Implement the Power Iteration and Rayleigh Quotient algorithms to compute the top $k$ eigenvalues of symmetric matrices.",
         "TransformerLab: Positional embedding and attention spectrum analysis."),

        (5, "Singular Value Decomposition (SVD) & Principal Component Analysis (PCA)",
         "Lesson 9.4",
         ["The SVD Theorem: any matrix $A \\in \\mathbb{R}^{m \\times n}$ factors as $A = U \\Sigma V^T$ with orthogonal $U, V$ and non-negative diagonal $\\Sigma$",
          "Singular values vs eigenvalues: singular values as lengths of principal semi-axes of transformed unit spheres",
          "Eckart-Young-Mirsky Theorem: low-rank matrix approximation by truncating SVD; optimal approximation in Frobenius and spectral norms",
          "Moore-Penrose Pseudoinverse ($A^+$): minimum-norm least-squares solution for overdetermined and underdetermined systems",
          "Principal Component Analysis (PCA): maximizing variance of projections, covariance matrix eigendecomposition, and dimensionality reduction",
          "Modern applications: Low-Rank Adaptation (LoRA) of LLMs, weight matrix compression, and latent semantic analysis"],
         "Failing to center data before computing PCA, leading to false principal directions aligned with dataset mean.",
         "Build a full PCA and truncated SVD dimensionality reduction engine from scratch in NumPy; compress an image dataset by 80% with minimal loss.",
         "TransformerLab: Low-rank projection analysis."),

        (6, "Tensor Strides, Memory Layouts & Einstein Summation (Einsum)",
         "Phase 0, Lesson 9.1",
         ["Tensor storage internals: 1D contiguous memory buffer, shape tuple, and stride tuple",
          "Row-major (C-order) vs Column-major (Fortran-order) layouts: stride calculation formula ($s_i = \\prod_{j=i+1}^{d-1} n_j$)",
          "Non-contiguous tensors: slicing, transposing, and broadcasting creating zero-copy views by modifying strides",
          "Broadcasting rules: matching dimensions from right to left, dimension compatibility ($d_1 == d_2$ or $d_1 == 1$ or $d_2 == 1$)",
          "The `.contiguous()` operation: when deep learning frameworks must reallocate memory to re-establish sequential strides",
          "Einstein Summation notation (`einsum`): index notation, implicit vs explicit modes, expressing matmul, batch matmul, transpose, and attention"],
         "Invoking `.view()` on a non-contiguous tensor in PyTorch triggering runtime errors; stride bugs causing silent memory corruptions.",
         "Implement a custom `Tensor` data structure in Python managing arbitrary shapes, strides, broadcasting, and slicing views over a 1D list.",
         "GradFlow: Core multi-dimensional Tensor and stride engine."),

        (7, "Multivariate Differential Calculus: Gradients, Jacobians & Directional Derivatives",
         "Phase 2, Lesson 9.1",
         ["Functions $f: \\mathbb{R}^n \\to \\mathbb{R}$: partial derivatives, gradient vector $\\nabla f(x)$, and steepness interpretation",
          "Directional derivatives: $D_v f(x) = \\nabla f(x)^T v$; gradient as the direction of steepest ascent",
          "Vector-valued functions $f: \\mathbb{R}^n \\to \\mathbb{R}^m$: the Jacobian matrix $J \\in \\mathbb{R}^{m \\times n}$ of all first-order partials",
          "Matrix calculus conventions: numerator layout (Jacobian formulation) vs denominator layout (gradient formulation)",
          "Vector-Jacobian Products (VJP): why reverse-mode automatic differentiation computes $v^T J$ rather than full $J$",
          "Jacobian-Vector Products (JVP): forward-mode automatic differentiation and directional derivative evaluation"],
         "Mixing numerator and denominator layout conventions mid-derivation, yielding transposed matrix gradient dimensions.",
         "Derive by hand and verify numerically via finite differences the analytical gradient and Jacobian of vector mapping $f(x) = Ax / \\|x\\|_2$.",
         "GradFlow: Analytical gradient calculation foundations."),

        (8, "The Multivariable Chain Rule & Computational Graphs",
         "Lesson 9.7",
         ["Univariate chain rule review: $(f \\circ g)'(x) = f'(g(x)) g'(x)$",
          "Multivariable chain rule: composing vector functions $z = f(y)$ where $y = g(x)$; Jacobian product $J_{z,x} = J_{z,y} J_{y,x}$",
          "Computational Directed Acyclic Graphs (DAG): nodes as variables/operations, directed edges as data dependencies",
          "Forward accumulation (Forward-Mode AD): propagating tangent vectors along DAG from inputs to outputs ($O(n)$ passes for $n$ inputs)",
          "Reverse accumulation (Reverse-Mode AD / Backpropagation): propagating adjoint vectors backward from output scalar to inputs ($O(1)$ pass)",
          "Why deep learning uses reverse-mode: neural loss functions map millions of parameters ($\mathbb{R}^n$) to a single scalar loss ($\mathbb{R}$)"],
         "Forward-mode AD computing gradients parameter-by-parameter, resulting in millions of forward passes instead of one reverse pass.",
         "Construct a DAG computation graph on paper and evaluate forward values and reverse adjoints step-by-step for a non-trivial function.",
         "GradFlow: Computational graph DAG architecture."),

        (9, "Second-Order Calculus: The Hessian Matrix, Curvature & Taylor Approximations",
         "Lesson 9.7",
         ["Second-order partial derivatives and Clairaut's Schwarz Theorem: symmetry of mixed partials ($\\frac{\\partial^2 f}{\\partial x_i \\partial x_j} = \\frac{\\partial^2 f}{\\partial x_j \\partial x_i}$)",
          "The Hessian matrix $H \\in \\mathbb{R}^{n \\times n}$: definition, symmetry, and representing local quadratic curvature",
          "Multivariable Taylor series expansions: 1st-order (linear tangent plane) and 2nd-order (quadratic approximation)",
          "Classifying stationary points ($\\nabla f(x) = 0$): positive definite $H$ (local minimum), negative definite (maximum), indefinite (saddle point)",
          "Curvature along unit direction $v$: directional second derivative $v^T H v$; condition number of Hessian and ill-conditioned ravines",
          "Hessian-Free optimization and Hessian-Vector Products (HVP): computing $H v$ without storing the $O(n^2)$ full Hessian matrix"],
         "Assuming local zero-gradient points are local minima in high dimensions, ignoring the prevalence of high-dimensional saddle points.",
         "Compute the Hessian matrix of the Rosenbrock function; analyze its condition number and demonstrate gradient descent oscillations.",
         "GradFlow: Curvature analysis and numerical verification."),

        (10, "Probability Theory for Machine Learning: Random Variables, Densities & Independence",
         "Phase 2, Phase 3",
         ["Probability spaces, axioms of probability, conditional probability, and Bayes' Theorem ($P(A|B) = \\frac{P(B|A)P(A)}{P(B)}$)",
          "Discrete random variables: PMF, CDF, Bernoulli, Binomial, and Categorical distributions",
          "Continuous random variables: PDF, CDF, Uniform, and Gaussian (Normal) distributions",
          "Expectation, variance, covariance, and correlation matrix: linearity of expectation ($\\mathbb{E}[aX + bY] = a\\mathbb{E}[X] + b\\mathbb{E}[Y]$)",
          "Multivariate Gaussian distribution: mean vector $\\mu$, covariance matrix $\\Sigma$, and geometric ellipse contours",
          "Independence vs Uncorrelatedness: why zero covariance does not imply statistical independence for non-Gaussian variables"],
         "Confusing probability density with probability mass (PDF values can exceed 1.0); dividing by singular covariance matrices.",
         "Implement a Multivariate Gaussian probability density evaluator from scratch in NumPy with Cholesky-stabilized determinant computation.",
         "GradFlow: Probabilistic foundations for machine learning."),

        (11, "Information Theory: Entropy, Cross-Entropy & Kullback-Leibler (KL) Divergence",
         "Lesson 9.10",
         ["Self-information (surprisal): $I(x) = -\\log_2 P(x)$; Shannon Entropy $H(P) = -\\sum_x P(x) \\log P(x)$ as expected information content",
          "Joint entropy, conditional entropy, and mutual information: $I(X; Y) = H(X) - H(X|Y)$ measuring shared information",
          "Kullback-Leibler (KL) Divergence: $D_{KL}(P \\parallel Q) = \\sum_x P(x) \\log \\frac{P(x)}{Q(x)}$ measuring relative entropy between distributions",
          "Properties of KL Divergence: non-negativity (Gibbs' inequality: $D_{KL} \\ge 0$), asymmetry ($D_{KL}(P \\parallel Q) \\neq D_{KL}(Q \\parallel P)$)",
          "Cross-Entropy: $H(P, Q) = H(P) + D_{KL}(P \\parallel Q) = -\\sum_x P(x) \\log Q(x)$; relationship to maximum likelihood estimation",
          "Forward KL (mode-covering) vs Reverse KL (mode-seeking) behavior in variational inference and generative modeling"],
         "Treating KL divergence as a distance metric despite its asymmetry ($D_{KL}(P \\parallel Q) \\neq D_{KL}(Q \\parallel P)$).",
         "Implement Shannon Entropy, Cross-Entropy, and KL Divergence functions in Python; demonstrate forward vs reverse KL mode fitting.",
         "TransformerLab: Cross-entropy loss formulation and attention entropy analysis."),

        (12, "Statistical Estimators: Maximum Likelihood (MLE) & Maximum A Posteriori (MAP)",
         "Lesson 9.10, Lesson 9.11",
         ["Parametric estimation: estimating underlying population parameters $\\theta$ from observed data samples $\\mathcal{D}$",
          "Likelihood function $L(\\theta; \\mathcal{D})$ and Log-Likelihood $\\ell(\\theta) = \\sum_{i=1}^N \\log p(x_i | \\theta)$ under i.i.d. assumptions",
          "Maximum Likelihood Estimation (MLE): maximizing log-likelihood; connecting Gaussian MLE to Ordinary Least Squares (OLS)",
          "Connecting Categorical MLE to Cross-Entropy loss in classification models",
          "Maximum A Posteriori (MAP) estimation: incorporating prior distributions $p(\\theta)$ via Bayes' rule ($\\theta_{MAP} = \\arg\\max [\\log p(\\mathcal{D}|\\theta) + \\log p(\\theta)]$)",
          "Regularization equivalence: Gaussian prior ($L_2$ / Ridge) vs Laplace prior ($L_1$ / Lasso) on weights"],
         "Maximizing raw likelihood instead of log-likelihood, resulting in floating-point underflow when multiplying small probabilities.",
         "Derive analytically and implement in Python the MLE and MAP estimators for linear regression with Gaussian and Laplace priors.",
         "GradFlow: Loss function probabilistic derivation suite."),

        (13, "Neural Network Foundations: The Perceptron, Multilayer Perceptrons (MLP) & Universal Approximation",
         "Lesson 9.1, Lesson 9.7",
         ["The McCulloch-Pitts neuron and Rosenblatt Perceptron: weights, bias, step activation, and linear classification boundaries",
          "The XOR problem: Minsky & Papert's proof of perceptron linear limitations and the necessity of hidden layers",
          "Multilayer Perceptron (MLP) architecture: input layer, hidden layers, output layer, and fully connected affine transformations ($z = Wx + b$)",
          "The Universal Approximation Theorem (Cybenko, Hornik): single hidden layer with non-linear activation approximating continuous functions",
          "Depth vs Width: why deep neural networks achieve exponential representational efficiency over shallow wide networks",
          "Matrix formulation of batch forward passes: $Z = X W^T + b$ where $X \\in \\mathbb{R}^{B \\times d_{in}}$ and $W \\in \\mathbb{R}^{d_{out} \\times d_{in}}$"],
         "Omitting the bias vector $b$, constraining linear decision boundaries to pass strictly through the coordinate origin.",
         "Build a 2-layer MLP from scratch in pure Python (no external libraries) that successfully learns the non-linear XOR truth table.",
         "GradFlow: Fundamental Multi-Layer Perceptron implementation."),

        (14, "Activation Functions: Sigmoid, Tanh, ReLU, GELU & SwiGLU",
         "Lesson 9.13",
         ["Role of non-linear activations: breaking linearity to enable multi-layer feature representation learning",
          "Sigmoid $\\sigma(z) = \\frac{1}{1 + e^{-z}}$: saturation at tails, vanishing gradients (max derivative 0.25), and non-zero-centered outputs",
          "Hyperbolic Tangent $\\tanh(z)$: zero-centered outputs, saturation at tails, and relation to sigmoid ($\\tanh(z) = 2\\sigma(2z) - 1$)",
          "Rectified Linear Unit (ReLU) $f(z) = \\max(0, z)$: constant gradient for positive inputs, computational efficiency, and 'Dying ReLU' problem",
          "Leaky ReLU and Parametric ReLU (PReLU): introducing non-zero slope for negative inputs to prevent dead neurons",
          "Modern Transformer activations: Gaussian Error Linear Unit (GELU) and Swish/SiLU; SwiGLU gated linear units in LLaMA"],
         "Using sigmoid activations throughout deep 10-layer networks, causing complete vanishing of gradients during backpropagation.",
         "Implement Sigmoid, Tanh, ReLU, GELU, and SwiGLU activations along with their exact analytical derivatives in NumPy.",
         "TransformerLab: Activation function layer suite."),

        (15, "Loss Functions: MSE, Binary Cross-Entropy, Categorical Cross-Entropy & Softmax",
         "Lesson 9.11, Lesson 9.14",
         ["Mean Squared Error (MSE) loss: formulation, derivation from Gaussian MLE, sensitivity to outliers, and regression tasks",
          "Binary Cross-Entropy (BCE) loss: formulation, derivation from Bernoulli likelihood, and pairing with sigmoid output layer",
          "Softmax function: mapping arbitrary logits $z \\in \\mathbb{R}^K$ to a valid probability distribution over $K$ classes ($\\sum p_i = 1$)",
          "Numerical stability of Softmax: subtracting maximum logit value ($z_i - \\max(z)$) to prevent floating-point exponential overflow",
          "Categorical Cross-Entropy loss: $-\\sum_{k=1}^K y_k \\log p_k$; derivation from categorical distribution likelihood",
          "The combined Softmax + Cross-Entropy gradient: elegant derivation showing $\\frac{\\partial L}{\\partial z_i} = p_i - y_i$"],
         "Evaluating raw `np.exp(z)` in Softmax causing NaN/overflow crashes on large logit values ($z > 709$).",
         "Implement a numerically stable fused Softmax-Cross-Entropy loss function and verify that its gradient simplifies to $\\hat{y} - y$.",
         "GradFlow: Core loss functions and numerical stability layer."),

        (16, "Analytical Backpropagation I: Gradients for Linear Layers & Affine Transforms",
         "Lesson 9.7, Lesson 9.15",
         ["The scalar-by-matrix derivative: conventions, dimensions matching, and chain rule application",
          "Forward pass of linear layer: $Y = X W + b$ with shapes $X \\in \\mathbb{R}^{B \\times D}$, $W \\in \\mathbb{R}^{D \\times M}$, $b \\in \\mathbb{R}^{1 \\times M}$",
          "Derivation of weight gradient: $\\frac{\\partial L}{\\partial W} = X^T \\frac{\\partial L}{\\partial Y}$ (dimensions $(D \\times B) \\times (B \\times M) = (D \\times M)$)",
          "Derivation of input gradient: $\\frac{\\partial L}{\\partial X} = \\frac{\\partial L}{\\partial Y} W^T$ (dimensions $(B \\times M) \\times (M \\times D) = (B \\times D)$)",
          "Derivation of bias gradient: $\\frac{\\partial L}{\\partial b} = \\sum_{i=1}^B \\frac{\\partial L}{\\partial Y_{i,:}}$ (summing over batch dimension)",
          "Memory management: caching input activations $X$ and weights $W$ during forward pass for backward computation"],
         "Transposing matrices incorrectly in backpropagation formulas, producing dimension mismatches or computing invalid gradients.",
         "Derive and hand-code the forward and backward passes for a dense linear layer in NumPy; verify gradients via finite differences.",
         "GradFlow: Dense Linear layer with exact analytical backprop."),

        (17, "Analytical Backpropagation II: End-to-End 3-Layer Network by Hand",
         "Lesson 9.16",
         ["End-to-end forward architecture: $Z_1 = X W_1 + b_1$, $A_1 = \\text{ReLU}(Z_1)$, $Z_2 = A_1 W_2 + b_2$, $\\hat{Y} = \\text{Softmax}(Z_2)$",
          "Loss calculation: $L = \\text{CrossEntropy}(\\hat{Y}, Y)$",
          "Step 1 backward: output logit gradient $\\delta_2 = \\frac{\\partial L}{\\partial Z_2} = \\hat{Y} - Y$",
          "Step 2 backward: parameter gradients $\\frac{\\partial L}{\\partial W_2} = A_1^T \\delta_2$, $\\frac{\\partial L}{\\partial b_2} = \\text{sum}(\\delta_2, \\text{axis}=0)$",
          "Step 3 backward: hidden activation gradient $\\frac{\\partial L}{\\partial A_1} = \\delta_2 W_2^T$",
          "Step 4 backward: ReLU gate gradient $\\delta_1 = \\frac{\\partial L}{\\partial Z_1} = \\frac{\\partial L}{\\partial A_1} \\odot \\mathbb{I}(Z_1 > 0)$, followed by $W_1, b_1$ gradients"],
         "Computing ReLU backward gradient using post-activation values $A_1$ rather than pre-activation $Z_1$ when Leaky ReLU is introduced.",
         "Implement a 3-layer neural network from scratch in NumPy with 100% manual backpropagation; train it to 98% accuracy on MNIST.",
         "GradFlow: Fully verified manual MLP reference implementation."),

        (18, "Numerical Gradient Checking (GradCheck) & Finite Differences",
         "Lesson 9.7, Lesson 9.17",
         ["Why gradient checking is essential: silent bugs in analytical backprop allowing networks to learn partially while degrading performance",
          "Finite difference approximations: Forward difference ($\\frac{f(\\theta + \\epsilon) - f(\\theta)}{\\epsilon}$, error $O(\\epsilon)$)",
          "Centered difference approximation: $\\frac{f(\\theta + \\epsilon) - f(\\theta - \\epsilon)}{2\\epsilon}$, error $O(\\epsilon^2)$",
          "Choosing the perturbation size: why $\\epsilon \\approx 10^{-7}$ balances truncation error and floating-point cancellation error",
          "Relative error metric: $\\frac{\\|\\nabla_{analytical} - \\nabla_{numerical}\\|_2}{\\|\\nabla_{analytical}\\|_2 + \\|\\nabla_{numerical}\\|_2 + 10^{-15}}$",
          "Failure triage: interpreting relative errors ($<10^{-7}$ perfect, $>10^{-2}$ major bug in analytical backprop)"],
         "Using forward difference instead of centered difference, leading to false-positive gradient bug warnings.",
         "Build a universal `grad_check` utility function verifying arbitrary tensor layers against centered finite differences.",
         "GradFlow: Universal gradient checking verification suite."),

        (19, "Weight Initialization Dynamics: Vanishing/Exploding Gradients & He/Xavier",
         "Lesson 9.10, Lesson 9.16",
         ["The initialization problem: zero initialization symmetry breaking failure, too small (vanishing), too large (exploding)",
          "Variance propagation through layers: deriving $\\text{Var}(y) = n \\cdot \\text{Var}(w) \\cdot \\text{Var}(x)$ under zero-mean inputs",
          "Xavier (Glorot) Initialization: preserving variance across forward and backward passes for tanh/sigmoid: $W \\sim \\mathcal{N}\\left(0, \\frac{2}{n_{in} + n_{out}}\\right)$",
          "He (Kaiming) Initialization: accounting for half-rectification in ReLU activations: $W \\sim \\mathcal{N}\\left(0, \\frac{2}{n_{in}}\\right)$",
          "LeCun Initialization: optimal scaling for SELU self-normalizing networks",
          "Modern LLM initialization: scaling residual projection weights by $\\frac{1}{\\sqrt{2 \\times N_{layers}}}$ to stabilize deep Transformer training"],
         "Initializing weights with standard normal distribution $\\mathcal{N}(0, 1)$, causing activations to explode to infinity within 6 layers.",
         "Simulate activation and gradient variance through 50 layers with different initializations; prove He initialization prevents collapse.",
         "GradFlow: Initializer module (He, Xavier, Normal, Uniform)."),

        (20, "Batch Normalization & Layer Normalization Internals",
         "Lesson 9.10, Lesson 9.19",
         ["Internal Covariate Shift hypothesis vs smoothing the optimization landscape: how normalization stabilizes loss surfaces",
          "Batch Normalization (BatchNorm): batch mean, batch variance, normalize, affine scale and shift ($\\gamma \\hat{x} + \\beta$)",
          "Running statistics in BatchNorm: tracking running_mean and running_var via momentum for evaluation mode inference",
          "Failure modes of BatchNorm: small batch sizes, sequence modeling disparity, and training/eval mode mismatch bugs",
          "Layer Normalization (LayerNorm): normalizing across feature dimensions per sample independently of batch size",
          "Analytical backpropagation through LayerNorm: deriving gradients with respect to inputs, gamma, and beta"],
         "Forgetting to switch BatchNorm from training mode to evaluation mode, producing catastrophic random predictions during production inference.",
         "Implement LayerNorm and BatchNorm from scratch in NumPy, including both forward pass and complete analytical backward gradient passes.",
         "TransformerLab: Pre-LayerNorm and RMSNorm layers."),

        (21, "Optimization Fundamentals: Gradient Descent & Stochastic Gradient Descent (SGD)",
         "Lesson 9.7, Lesson 9.16",
         ["Optimization landscape: convex functions vs non-convex neural network loss surfaces, local minima, and saddle points",
          "Batch Gradient Descent (BGD): updating parameters over full dataset; stability vs extreme computational cost on large data",
          "Stochastic Gradient Descent (SGD): single-sample parameter updates; high variance, noisy gradient estimates, escaping saddle points",
          "Mini-Batch SGD: sweet spot balancing computational parallelism on GPUs with gradient estimation stability ($B=32, 64, 256$)",
          "Learning rate (step size $\\eta$): divergence from overly high $\\eta$, creeping stagnation from overly low $\\eta$",
          "Ill-conditioned ravines: why standard SGD oscillates violently perpendicular to steep valley walls while making slow progress along the valley floor"],
         "Using an excessively high learning rate causing loss to diverge to infinity/NaN within the first few parameter update steps.",
         "Implement a modular Mini-Batch SGD optimizer in pure NumPy with batch generation, epoch looping, and loss tracking.",
         "GradFlow: Base optimizer class and SGD implementation."),

        (22, "Advanced Optimizers: Momentum, Nesterov, RMSprop & AdamW",
         "Lesson 9.21",
         ["Momentum: exponential moving average of past gradients ($v_t = \\beta v_{t-1} + g_t$); dampening oscillations in ravines",
          "Nesterov Accelerated Gradient (NAG): computing gradient after looking ahead along current momentum vector",
          "RMSprop: adaptive learning rates dividing gradient by root-mean-square of running squared gradients ($s_t = \\beta s_{t-1} + (1-\\beta)g_t^2$)",
          "Adam (Adaptive Moment Estimation): combining 1st moment (momentum) and 2nd moment (RMSprop) with bias correction for initial steps",
          "Adam bias correction derivation: why dividing by $(1 - \\beta_1^t)$ and $(1 - \\beta_2^t)$ is mathematically necessary near $t=1$",
          "AdamW (Decoupled Weight Decay): Loshchilov & Hutter's proof that $L_2$ regularization $\\neq$ weight decay in adaptive optimizers; AdamW formulation"],
         "Using standard Adam with $L_2$ penalty instead of AdamW, causing heavily updated weights to decay slower than rarely updated weights.",
         "Implement SGD with Momentum, RMSprop, and AdamW from scratch in pure NumPy; compare convergence trajectories on a Rosenbrock function.",
         "GradFlow & TransformerLab: Production AdamW optimizer engine."),

        (23, "Learning Rate Schedulers & Regularization Techniques",
         "Lesson 9.22",
         ["Learning rate scheduling: Step decay, Exponential decay, and Cosine Annealing schedules",
          "Linear Warmup: starting with small learning rate to prevent early unstable gradients from destroying pre-trained or initialized weights",
          "Cosine Annealing with Warmup: modern standard schedule in LLM pre-training ($T_{warmup}$, $T_{max}$, $\\eta_{min}$)",
          "$L_2$ Regularization (Ridge / Weight Decay): shrinking weights toward zero, geometric interpretation as constraining parameter norm ball",
          "$L_1$ Regularization (Lasso): sparsity induction, geometric interpretation at coordinate corners",
          "Dropout: randomly zeroing activations with probability $p$ during training; inverted dropout scaling ($\\frac{1}{1-p}$) to preserve inference expectation"],
         "Failing to scale inverted dropout by $\\frac{1}{1-p}$ during training, causing activation magnitudes to diverge between train and eval modes.",
         "Implement Cosine Annealing with Warmup scheduler and Inverted Dropout from scratch; verify learning rate schedule curves.",
         "TransformerLab: Training loop scheduler and regularization."),

        (24, "Building an Autograd Engine I: The Value Node & Computational Graph",
         "Lesson 9.8, Lesson 9.17",
         ["Architecture of an automatic differentiation engine: tracing operations during forward execution to build a dynamic computation graph",
          "The `Value` / `Node` scalar data structure: holding `data`, `grad`, `_prev` children set, `_op` label, and `_backward` closure",
          "Operator overloading in Python: implementing `__add__`, `__mul__`, `__sub__`, `__pow__`, `__neg__`, `__truediv__`",
          "Defining scalar backward closures: writing the local derivative chain rule directly inside overloaded operator methods",
          "The accumulation invariant: why gradients must accumulate (`grad += ...`) rather than assign (`grad = ...`) to support node reuse",
          "Graph visualization: rendering the computational DAG with Graphviz/dot to trace forward values and backward adjoints"],
         "Overwriting gradients (`self.grad = out.grad * ...`) instead of accumulating (`self.grad += ...`), causing incorrect gradients on branching graphs.",
         "Implement a micro-autograd scalar engine supporting addition, multiplication, powers, and ReLU with automatic backward execution.",
         "GradFlow: Scalar autograd proof-of-concept."),

        (25, "Building an Autograd Engine II: Topological Sort & Backward Engine",
         "Lesson 9.24",
         ["The dependency problem in reverse-mode AD: a node cannot execute its backward pass until all its parent nodes have propagated their gradients",
          "Directed Acyclic Graph (DAG) properties: topological ordering definition and guarantees",
          "Topological sort algorithms: Depth-First Search (DFS) post-order traversal with a visited set to build reversed evaluation order",
          "The `.backward()` function: setting root node adjoint to 1.0 (`self.grad = 1.0`), sorting graph topologically, and invoking `_backward()` in reverse",
          "Handling cycles: validating graph acyclicity; raising explicit exceptions on cyclic dependencies",
          "Edge cases: handling scalar constants, shared variables ($z = x + x$, $z = x \\cdot x$), and multi-path branch reconvergence"],
         "Invoking backward passes in arbitrary graph order rather than strict reverse topological sort, producing incomplete partial gradients.",
         "Implement DFS topological sorting in the autograd engine; verify exact gradient calculation on diamond-shaped computational graphs ($x \\to y, z \\to w$).",
         "GradFlow: Graph topological sorting and backward coordinator."),

        (26, "Building an Autograd Engine III: Tensor-Level Autograd & Vector-Jacobian Products",
         "Lesson 9.6, Lesson 9.25",
         ["Moving from scalar autograd to multi-dimensional Tensor autograd: memory efficiency, vectorized operations, and BLAS acceleration",
          "The `Tensor` class: wrapping a NumPy ndarray, maintaining `data`, `grad`, `creator` context, and `requires_grad` boolean flags",
          "Vector-Jacobian Products (VJPs) in Tensor ops: computing output-adjoint product without explicitly instantiating giant Jacobian matrices",
          "Tensor addition with broadcasting backward: un-broadcasting gradients via summation along broadcasted axes to match input shape",
          "Tensor matrix multiplication (`matmul`) backward: deriving exact matrix product backward formulas using input caches",
          "Transposition and reshape backward: reversing permutations and reshaping incoming gradients to original operand layouts"],
         "Failing to un-broadcast gradients during backward passes of broadcasted operations, resulting in shape mismatch runtime crashes.",
         "Implement Tensor-level automatic differentiation for `matmul`, `add` (with arbitrary broadcasting), and `sum` in pure Python/NumPy.",
         "GradFlow: Core multi-dimensional Tensor autograd engine."),

        (27, "Building an Autograd Engine IV: Neural Network Module Abstractions",
         "Lesson 9.13, Lesson 9.26",
         ["The `Module` base class: managing parameters, registering sub-modules, recursive parameter collection, and zeroing gradients",
          "The `Parameter` wrapper: tensor with `requires_grad=True` tracked automatically inside module hierarchies",
          "Implementing `Linear` layer module: initializing weight and bias parameters, forward matmul and addition",
          "Implementing non-linear activation modules: `ReLU`, `Sigmoid`, `Tanh`, and `GELU` with tensor autograd support",
          "Implementing composite modules: `Sequential` container chaining arbitrary layers in ordered execution passes",
          "Training loop interface: `model.zero_grad()`, `loss = criterion(model(x), y)`, `loss.backward()`, `optimizer.step()`"],
         "Forgetting to zero gradients before calling `.backward()`, causing gradients to accumulate indefinitely across training steps.",
         "Build a modular neural network library (`Module`, `Parameter`, `Linear`, `Sequential`) on top of the custom Tensor autograd engine.",
         "GradFlow: High-level neural network abstractions module."),

        (28, "Building an Autograd Engine V: Loss Modules, Optimizers & GradFlow Validation",
         "Lesson 9.22, Lesson 9.27",
         ["Implementing loss function modules: `MSELoss` and `CrossEntropyLoss` with fused stable log-softmax",
          "Implementing optimizer classes: `SGD` (with momentum and weight decay) and `AdamW` updating `Module.parameters()` directly",
          "Training loop validation: training a multi-layer neural network built entirely with GradFlow on real data (synthetic non-linear classification)",
          "Overfitting a single batch test: verifying that the network can drive loss on a small batch of 10 samples to $< 0.0001$",
          "Benchmark comparison: benchmarking GradFlow training speed and gradient accuracy against PyTorch on identical architectures",
          "Packaging GradFlow: creating a clean, documented, installable Python library with 100% test coverage"],
         "AdamW optimizer updating parameter data without detaching from computation graph, causing graph explosion and massive memory leaks.",
         "Train an MLP built exclusively in GradFlow to 95%+ accuracy on the spirals non-linear classification dataset; pass all numerical grad checks.",
         "GradFlow: Final integration, test suite, and packaging."),

        (29, "PyTorch Deep Dive I: Tensors, Storage, Strides & Memory Layouts",
         "Lesson 9.6, Phase 0",
         ["PyTorch internal architecture: Python frontend, C++ ATen library, CUDA kernels, and PyTorch autograd engine",
          "The `torch.Tensor` object: Tensor metadata (shape, stride, dtype, device) vs underlying `torch.Storage` contiguous 1D array",
          "Memory sharing and non-copying operations: `view()`, `transpose()`, `permute()`, `narrow()`, and `squeeze()` sharing storage",
          "In-place operations (`add_()`, `mul_()`): storage mutation, cache invalidation, and autograd graph version checking (`_version`)",
          "Hardware devices: allocating and transferring tensors between CPU and CUDA devices (`.to(device)`, `.cuda()`)",
          "Memory pinning (`pin_memory=True`): page-locked host memory enabling asynchronous DMA transfers to GPU memory"],
         "Using in-place operations on variables needed for backward passes, triggering PyTorch's internal version counter modification runtime error.",
         "Inspect PyTorch tensor storage pointers and strides using `.storage().data_ptr()` and `.stride()`; trace zero-copy views vs `.clone()`.",
         "PyTorch Engineering: Storage and stride mastery."),

        (30, "PyTorch Deep Dive II: Autograd Mechanics, Hooks & Computation Graphs",
         "Lesson 9.26, Lesson 9.29",
         ["PyTorch dynamic graph execution: constructing the DAG on-the-fly during the forward pass; `grad_fn` pointers on output tensors",
          "Controlling autograd tracking: `torch.no_grad()` (disabling graph construction during eval) vs `torch.inference_mode()` (ultimate optimization)",
          "Tensor gradient attributes: `.grad`, `.requires_grad_()`, `.retain_grad()` (retaining non-leaf node gradients for inspection)",
          "Autograd hooks: `register_hook` on tensors and `register_forward_hook` / `register_full_backward_hook` on `nn.Module`",
          "Inspecting intermediate activations and gradients using hooks without modifying model source code",
          "Custom autograd functions: subclassing `torch.autograd.Function` with static `forward(ctx, ...)` and `backward(ctx, ...)` methods"],
         "Accumulating computation graphs in logging variables by writing `total_loss += loss` instead of `total_loss += loss.item()`, causing OOM.",
         "Write a custom PyTorch `torch.autograd.Function` implementing a numerically stabilized custom activation function with registered hooks.",
         "PyTorch Engineering: Custom autograd extension and inspection hooks."),

        (31, "PyTorch Deep Dive III: nn.Module Architecture, Parameters & Buffers",
         "Lesson 9.27, Lesson 9.30",
         ["`nn.Module` internal state: `_parameters`, `_buffers`, `_modules`, `_forward_hooks`, and `_backward_hooks` ordered dictionaries",
          "Parameters vs Buffers: trainable weights (`nn.Parameter`) vs non-trainable state (e.g. running stats, positional embeddings) via `register_buffer`",
          "Weight initialization patterns: applying `init` functions across all submodules using `model.apply(init_weights)`",
          "State dictionaries: `model.state_dict()`, serialization via `torch.save()`, and strict vs non-strict weight loading (`load_state_dict`)",
          "Model modes: `model.train()` vs `model.eval()`, side effects on Dropout, BatchNorm, and customized behavior",
          "Building complex modular architectures: nested `nn.ModuleList`, `nn.ModuleDict`, and residual skip-connection modules"],
         "Storing non-trainable state in standard Python lists or attributes instead of registering as buffers, causing state to be omitted from `state_dict`.",
         "Build a modular ResNet-style skip-connection block in PyTorch with custom parameter initialization and persistent registered buffers.",
         "PyTorch Engineering: Advanced neural network module design."),

        (32, "PyTorch Deep Dive IV: High-Performance DataLoaders & Multiprocessing",
         "Phase 0, Phase 4, Lesson 9.29",
         ["The data pipeline bottleneck: keeping GPU compute saturating by streaming data asynchronously ahead of execution",
          "`torch.utils.data.Dataset` abstraction: Map-style datasets (`__len__`, `__getitem__`) vs Iterable-style datasets for massive streams",
          "`DataLoader` internals: `batch_size`, `shuffle`, `sampler`, `batch_sampler`, and custom `collate_fn` for dynamic sequence padding",
          "Multiprocessing worker architecture: `num_workers > 0`, process forking vs spawning, and worker initialization functions (`worker_init_fn`)",
          "Avoiding memory leaks in PyTorch DataLoaders: reference cycles, copy-on-write degradation with large Python objects in workers",
          "Prefetching and pinned memory: `pin_memory=True`, `prefetch_factor`, and asynchronous GPU transfers during worker execution"],
         "Worker processes copying large Python lists on fork, exhausting system RAM and triggering Linux OOM killer crashes.",
         "Construct a high-performance custom `DataLoader` with dynamic sequence batching, pinned memory, and zero memory leaks under stress.",
         "TransformerLab: High-throughput tokenized dataset pipeline."),

        (33, "PyTorch Deep Dive V: Mixed Precision Training (FP16/BF16) & AMP",
         "Phase 0, Lesson 9.29",
         ["Floating-point numerical representations: FP32 (single precision), FP16 (half precision), and BF16 (Bfloat16: 8-bit exponent, 7-bit mantissa)",
          "Why BF16 is superior for deep learning: preserving the dynamic dynamic range of FP32, eliminating underflow/overflow scaling issues",
          "Automatic Mixed Precision (AMP): `torch.autocast`: executing matmuls in FP16/BF16 while accumulating and updating in FP32",
          "Gradient scaling with `torch.cuda.amp.GradScaler`: preventing small gradients from underflowing to zero in FP16 backward passes",
          "Dynamic loss scaling mechanics: scaling loss up before backward, un-scaling gradients before optimizer step, skipping steps with inf/nan",
          "Memory and throughput profiling: measuring $2\\times$ memory reduction and $3\\times$ throughput speedup on modern tensor core GPUs"],
         "Calling `optimizer.step()` before `scaler.step()` in FP16 training, applying corrupted inf/nan gradients directly to parameters.",
         "Instrument a standard PyTorch training loop with `torch.autocast` and `GradScaler`; verify zero gradient underflow and 2.5x speedup.",
         "TransformerLab: Mixed precision training pipeline."),

        (34, "PyTorch Deep Dive VI: Training Loop Engineering, Checkpointing & Reproducibility",
         "Lesson 9.28, Lesson 9.33",
         ["Production training loop anatomy: train epoch, validation epoch, metric aggregation, and early stopping criteria",
          "Durable checkpointing: saving model state, optimizer state, scheduler state, epoch count, and scaler state to disk",
          "Resuming interrupted training: exact state restoration, verifying loss trajectory continuity across restarts",
          "Gradient clipping: `torch.nn.utils.clip_grad_norm_`: clipping global $L_2$ norm of concatenated gradients to prevent exploding gradients",
          "Complete determinism and reproducibility: setting seeds across Python `random`, NumPy, PyTorch CPU, PyTorch CUDA, and cuDNN flags",
          "Gradient accumulation: simulating large effective batch sizes ($B_{effective} = B_{physical} \\times \\text{accum\\_steps}$) under constrained VRAM"],
         "Saving only model weights in checkpoints, failing to restore optimizer momentum and learning rate schedule upon resume.",
         "Build a production training harness with gradient accumulation, norm clipping, durable checkpointing, and exact resumption verification.",
         "TransformerLab: Resilient model training framework."),

        (35, "Sequence Modeling: From Recurrent Neural Networks (RNNs) to Attention",
         "Phase 3, Lesson 9.13",
         ["Sequence-to-sequence learning problem: modeling variable-length temporal sequences ($x_1, x_2, \\dots, x_T$)",
          "Vanilla Recurrent Neural Networks (RNNs): hidden state recurrence ($h_t = \\tanh(W_{hh} h_{t-1} + W_{xh} x_t + b)$)",
          "Backpropagation Through Time (BPTT): unrolling recurrence through time; mathematical proof of vanishing and exploding gradients in deep unrolls",
          "Gated architectures: Long Short-Term Memory (LSTM) cells (forget, input, output gates, cell state) and Gated Recurrent Units (GRU)",
          "The fundamental bottleneck of recurrent architectures: sequential $O(T)$ execution preventing hardware parallelism on GPUs",
          "The Attention breakthrough (Bahdanau, Vaswani): routing information directly between any two sequence positions in $O(1)$ path length"],
         "Attempting to train standard vanilla RNNs on sequences longer than 50 tokens, causing vanishing gradients to stall training completely.",
         "Implement an unrolled Vanilla RNN and LSTM forward pass in NumPy; demonstrate gradient vanishing over 30 time steps.",
         "TransformerLab: Historical perspective and architectural comparison."),

        (36, "Self-Attention Mechanics: Queries, Keys, Values & Scaled Dot-Product",
         "Lesson 9.6, Lesson 9.35",
         ["Conceptual intuition: information retrieval metaphor (matching query against database keys to extract weighted values)",
          "Input projection: transforming input embeddings $X \\in \\mathbb{R}^{T \\times d}$ into Queries $Q = X W_Q$, Keys $K = X W_K$, Values $V = X W_V$",
          "Attention score computation: raw similarity matrix $S = Q K^T \\in \\mathbb{R}^{T \\times T}$ measuring pairwise token affinities",
          "Scaling factor $\\frac{1}{\\sqrt{d_k}}$: mathematical proof why unscaled dot products grow large in high dimensions, pushing softmax into near-zero gradient saturation",
          "Attention weights: $A = \\text{Softmax}\\left(\\frac{Q K^T}{\\sqrt{d_k}}\\right) \\in \\mathbb{R}^{T \\times T}$; valid probability distribution across sequence",
          "Context output: $O = A V \\in \\mathbb{R}^{T \\times d_v}$; weighted combination of value vectors representing contextualized representations"],
         "Omitting the $\\sqrt{d_k}$ scaling factor, causing softmax gradients to vanish instantly and halting attention weight training.",
         "Implement Scaled Dot-Product Attention from scratch in pure NumPy; verify that attention probabilities sum to 1.0 across all rows.",
         "TransformerLab: Core Scaled Dot-Product Attention module."),

        (37, "Multi-Head Attention (MHA) & Causal Masking Internals",
         "Lesson 9.6, Lesson 9.36",
         ["Why Multi-Head Attention: allowing the model to jointly attend to information from different representation subspaces at different positions",
          "MHA projection geometry: splitting $d_{model}$ into $h$ heads of dimension $d_k = d_{model} / h$",
          "Tensor reshape gymnastics: reshaping $(B, T, d_{model}) \\to (B, T, h, d_k) \\to (B, h, T, d_k)$ for parallel batch matmul",
          "Causal (Autoregressive) Masking: why decoder-only models must prevent position $i$ from attending to future positions $j > i$",
          "Upper-triangular masking: filling future attention scores with $-\\infty$ before applying softmax ($e^{-\\infty} = 0$)",
          "Output projection: concatenating head outputs and projecting through $W_O \\in \\mathbb{R}^{d_{model} \\times d_{model}}$"],
         "Applying causal mask after softmax instead of before, resulting in uniform non-zero weights on masked future tokens.",
         "Implement Multi-Head Causal Self-Attention with efficient 4D tensor reshaping in PyTorch; verify causal zero-leakage to future tokens.",
         "TransformerLab: Causal Multi-Head Attention block."),

        (38, "Positional Encodings: Absolute, Learned & Rotary Position Embeddings (RoPE)",
         "Lesson 9.4, Lesson 9.37",
         ["Permutation invariance of attention: why Transformers cannot distinguish token order without explicit positional information",
          "Sinusoidal Absolute Positional Encodings (Vaswani et al.): fixed sine and cosine functions of varying frequencies ($PE_{(pos, 2i)}$)",
          "Learned Absolute Positional Embeddings (GPT-2): trainable lookup table per position and sequence length limitation constraints",
          "Relative Positional Encodings: encoding relative distance between tokens $i$ and $j$ rather than absolute coordinates",
          "Rotary Position Embedding (RoPE) deep dive (Su et al.): rotating Query and Key vectors in 2D coordinate pairs by angle $m \\theta$",
          "Mathematical beauty of RoPE: $\\langle R_m q, R_n k \\rangle = g(q, k, m - n)$; incorporating relative position via complex multiplication"],
         "Using standard learned positional embeddings and attempting to run inference on sequences longer than the training context window.",
         "Implement Rotary Position Embeddings (RoPE) from scratch; prove mathematically and verify in code that inner product depends only on $(m-n)$.",
         "TransformerLab: RoPE embedding implementation."),

        (39, "The Complete Decoder-Only Transformer Architecture",
         "Lesson 9.20, Lesson 9.37, Lesson 9.38",
         ["Decoder-Only architecture overview (GPT, LLaMA): token embedding, positional encoding, stacked transformer blocks, and unembedding head",
          "Transformer Block anatomy: Pre-LayerNorm (RMSNorm), Causal Multi-Head Attention, residual skip connection, Feed-Forward Network (FFN)",
          "Feed-Forward Network (FFN): two-layer MLP with hidden expansion factor $4\\times$ ($d_{model} \\to 4d_{model} \\to d_{model}$)",
          "Pre-LN vs Post-LN: mathematical proof why Pre-LN enables stable gradient flow in deep architectures without warmups",
          "Weight tying (Embedding-Unembedding): sharing weights between token embedding and final linear projection layer to save parameters",
          "Parameter count arithmetic: exact closed-form formula calculating total parameters from $d_{model}$, $N_{layers}$, $N_{heads}$, and $V_{vocab}$"],
         "Placing LayerNorm after the residual connection (Post-LN) in deep models without warmup, leading to un-trainable diverging weights.",
         "Assemble the complete Decoder-Only Transformer architecture from scratch in PyTorch; verify parameter counts match theoretical formulas.",
         "TransformerLab: Complete autoregressive Transformer model."),

        (40, "TransformerLab: Pre-Training a Custom GPT from Scratch & Generation",
         "Lesson 9.34, Lesson 9.39",
         ["Dataset preparation: building a custom character/BPE tokenizer, tokenizing raw text corpus (TinyShakespeare/WikiText)",
          "Autoregressive data formatting: input sequences $x = [t_1, \\dots, t_{T}]$ and target shifted sequences $y = [t_2, \\dots, t_{T+1}]$",
          "Pre-training loop: optimizing cross-entropy loss across all sequence tokens using AdamW and Cosine Annealing scheduler",
          "Autoregressive generation loop: greedy decoding vs Top-$k$ sampling vs Top-$p$ (nucleus) sampling vs Temperature scaling",
          "Key-Value (KV) Caching intuition: caching past keys and values during generation to reduce per-token complexity from $O(T^2)$ to $O(T)$",
          "Attention weight visualization: extracting attention matrices, generating heatmaps, and analyzing learned syntactic patterns"],
         "Re-computing past token keys and values during generation without KV caching, causing generation to slow down quadratically.",
         "Pre-train your custom GPT model on TinyShakespeare from scratch; generate coherent text with configurable temperature and top-p sampling.",
         "TransformerLab: Pre-training, evaluation, text generation, and attention visualization.")
    ]

    for item in p9_data:
        out.append(format_lesson(9, item[0], item[1], item[2], item[3], item[4], item[5], item[6]))

    out.append("""
### Phase 9 Capstone Deliverables
- **GradFlow**: A complete, lightweight, dependency-free autograd engine and neural network library built in pure Python/NumPy supporting dynamic computational DAGs, topological sorting, tensor broadcasting, reverse-mode VJPs, modules, loss functions, and optimizers (SGD, AdamW).
- **TransformerLab**: An end-to-end Decoder-Only autoregressive Transformer language model (GPT-style) built from scratch in PyTorch, featuring Rotary Position Embeddings (RoPE), RMSNorm, Causal Multi-Head Attention, mixed-precision training, durable checkpointing, and KV-cached generation with attention visualization heatmaps.

### Phase 9 Exit Benchmark
- Train the GradFlow custom engine on a non-linear dataset; all parameters must match analytical finite differences to a relative error $< 10^{-7}$.
- Train TransformerLab from scratch on a raw text corpus, driving cross-entropy loss down from $\\ln(V)$ to $< 1.8$, generating syntactically valid text with verified attention heatmaps.
""")
    return "\n".join(out)

if __name__ == "__main__":
    p8 = generate_phase8()
    p9 = generate_phase9()
    print(f"Phase 8: {p8.count('#### Lesson ')} lessons")
    print(f"Phase 9: {p9.count('#### Lesson ')} lessons")
    print(f"Total: {p8.count('#### Lesson ') + p9.count('#### Lesson ')} lessons")
