INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-13-16', 'phase-13-lesson-16-track-d-alignment-science-direct-preferen', 'module-14', 16, 'Lesson 14.16: Track D: Alignment Science: Direct Preference Optimization (DPO) & RLHF', 'Prerequisites: Phase 9, Phase 10', 'Prerequisites: Phase 9, Phase 10 | Subtopics: 6 items', 'Systems project application', 360, 14, 3310.0, 800.0, '# Lesson 13.16: Track D: Alignment Science: Direct Preference Optimization (DPO) & RLHF

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 10
- **Subtopics**:
  - `13.16.1` The alignment problem: steering raw pre-trained next-token predictors toward helpful, harmless, and honest behavior
  - `13.16.2` Reinforcement Learning from Human Feedback (RLHF) classical pipeline: SFT $\to$ Reward Model Training $\to$ PPO Policy Optimization
  - `13.16.3` Proximal Policy Optimization (PPO) complexity: coordinating 4 models concurrently (Policy, Value, Reference, Reward), training instability
  - `13.16.4` Direct Preference Optimization (DPO) breakthrough (Rafailov et al.): mathematically deriving closed-form policy loss without a reward model
  - `13.16.5` DPO loss formulation: $\mathcal{L}_{DPO}(\pi_\theta; \pi_{ref}) = -\mathbb{E}\left[\log \sigma\left(\beta \log \frac{\pi_\theta(y_w|x)}{\pi_{ref}(y_w|x)} - \beta \log \frac{\pi_\theta(y_l|x)}{\pi_{ref}(y_l|x)}\right)\right]$
  - `13.16.6` KTO (Kahneman-Tversky Optimization) and ORPO (Odds Ratio Preference Optimization): preference optimization without paired datasets
- **Key Failure Modes & Edge Cases**: Setting DPO temperature parameter $\beta$ too high or low, causing model mode collapse or failing to learn user preferences.
- **Verification & Mastery Check**: Implement the DPO loss function from scratch in PyTorch; fine-tune an aligned model on paired preference data.
- **Project Application**: Track D Capstone: DPO model alignment and preference optimization pipeline.', '{"solution.py": "# Phase 13 // Lesson 13.16: Track D: Alignment Science: Direct Preference Optimization (DPO) & RLHF\n\ndef solve():\n    \"\"\"\n    Verification: Implement the DPO loss function from scratch in PyTorch; fine-tune an aligned model on paired prefer\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.16", "subtopics_count": 6, "verification_criteria": "Implement the DPO loss function from scratch in PyTorch; fine-tune an aligned model on paired preference data.", "subtopics": ["13.16.1 The alignment problem: steering raw pre-trained next-token predictors toward helpful, harmless, and honest behavior", "13.16.2 Reinforcement Learning from Human Feedback (RLHF) classical pipeline: SFT $\\to$ Reward Model Training $\\to$ PPO Policy Optimization", "13.16.3 Proximal Policy Optimization (PPO) complexity: coordinating 4 models concurrently (Policy, Value, Reference, Reward), training instability", "13.16.4 Direct Preference Optimization (DPO) breakthrough (Rafailov et al.): mathematically deriving closed-form policy loss without a reward model", "13.16.5 DPO loss formulation: $\\mathcal{L}_{DPO}(\\pi_\\theta; \\pi_{ref}) = -\\mathbb{E}\\left[\\log \\sigma\\left(\\beta \\log \\frac{\\pi_\\theta(y_w|x)}{\\pi_{ref}(y_w|x)} - \\beta \\log \\frac{\\pi_\\theta(y_l|x)}{\\pi_{ref}(y_l|x)}\\right)\\right]$", "13.16.6 KTO (Kahneman-Tversky Optimization) and ORPO (Odds Ratio Preference Optimization): preference optimization without paired datasets"]}'::jsonb, '["Explain how this implementation prevents: Setting DPO temperature parameter $\\beta$ too high or low, causing model mode collapse or failing to learn user preferen", "How does Track D: Alignment Science: Direct Preference Optimization (DPO) & RLHF scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-17', 'phase-13-lesson-17-track-d-mixture-of-experts-moe-architectu', 'module-14', 17, 'Lesson 14.17: Track D: Mixture of Experts (MoE) Architecture: Routing & Sparse Compute', 'Prerequisites: Phase 9, Lesson 13.7', 'Prerequisites: Phase 9, Lesson 13.7 | Subtopics: 6 items', 'Systems project application', 360, 14, 3370.0, 850.0, '# Lesson 13.17: Track D: Mixture of Experts (MoE) Architecture: Routing & Sparse Compute

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Lesson 13.7
- **Subtopics**:
  - `13.17.1` Dense models vs Sparse Mixture of Experts (MoE): scaling parameter capacity exponentially while keeping inference compute constant
  - `13.17.2` MoE layer architecture: replacing standard FFN layers with $N$ parallel expert FFNs and a learnable gating router network
  - `13.17.3` Top-$k$ routing mechanics (Shazeer et al.): router projecting token embedding to logits, selecting top $k$ experts via softmax (typically $k=2$)
  - `13.17.4` Expert capacity and load balancing: auxiliary load balancing loss (Switch Transformer) preventing routing collapse to single popular expert
  - `13.17.5` Token dropping vs padding: managing fixed expert buffer capacities during batched execution across distributed GPU nodes
  - `13.17.6` DeepSeek-V2/V3 and Mixtral architecture: fine-grained experts, shared experts, and multi-token prediction heads
- **Key Failure Modes & Edge Cases**: Router collapsing to 1 or 2 dominant experts due to missing load balancing loss, leaving remaining experts untrained.
- **Verification & Mastery Check**: Build a Top-2 Mixture of Experts (MoE) transformer layer with auxiliary load balancing loss from scratch in PyTorch.
- **Project Application**: Track D Capstone: Sparse Mixture of Experts (MoE) architecture.', '{"solution.py": "# Phase 13 // Lesson 13.17: Track D: Mixture of Experts (MoE) Architecture: Routing & Sparse Compute\n\ndef solve():\n    \"\"\"\n    Verification: Build a Top-2 Mixture of Experts (MoE) transformer layer with auxiliary load balancing loss from scr\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.17", "subtopics_count": 6, "verification_criteria": "Build a Top-2 Mixture of Experts (MoE) transformer layer with auxiliary load balancing loss from scratch in PyTorch.", "subtopics": ["13.17.1 Dense models vs Sparse Mixture of Experts (MoE): scaling parameter capacity exponentially while keeping inference compute constant", "13.17.2 MoE layer architecture: replacing standard FFN layers with $N$ parallel expert FFNs and a learnable gating router network", "13.17.3 Top-$k$ routing mechanics (Shazeer et al.): router projecting token embedding to logits, selecting top $k$ experts via softmax (typically $k=2$)", "13.17.4 Expert capacity and load balancing: auxiliary load balancing loss (Switch Transformer) preventing routing collapse to single popular expert", "13.17.5 Token dropping vs padding: managing fixed expert buffer capacities during batched execution across distributed GPU nodes", "13.17.6 DeepSeek-V2/V3 and Mixtral architecture: fine-grained experts, shared experts, and multi-token prediction heads"]}'::jsonb, '["Explain how this implementation prevents: Router collapsing to 1 or 2 dominant experts due to missing load balancing loss, leaving remaining experts untrained.", "How does Track D: Mixture of Experts (MoE) Architecture: Routing & Sparse Compute scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-18', 'phase-13-lesson-18-track-d-state-space-models-ssms-modern-ma', 'module-14', 18, 'Lesson 14.18: Track D: State Space Models (SSMs) & Modern Mamba Architecture', 'Prerequisites: Phase 9, Phase 10', 'Prerequisites: Phase 9, Phase 10 | Subtopics: 6 items', 'Systems project application', 360, 14, 3250.0, 900.0, '# Lesson 13.18: Track D: State Space Models (SSMs) & Modern Mamba Architecture

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 10
- **Subtopics**:
  - `13.18.1` The quadratic bottleneck of Transformers: $O(T^2)$ computational complexity of self-attention limiting long-context scalability
  - `13.18.2` Classical State Space Models: continuous differential equations mapping 1D stimulus $x(t) \to y(t)$ via latent state $h(t)$
  - `13.18.3` HiPPO framework (High-order Polynomial Projection Operators): memory initialization maintaining continuous signal history
  - `13.18.4` Structured State Space Models (S4): continuous to discrete discretization (Bilinear / Euler transform) and fast convolutional training
  - `13.18.5` Mamba architecture (Gu & Dao): Selective State Spaces (S6) making transition matrices input-dependent to filter irrelevant information
  - `13.18.6` Hardware-aware selective scan: fused GPU SRAM kernel eliminating slow HBM transfers, achieving linear $O(T)$ training and $O(1)$ inference
- **Key Failure Modes & Edge Cases**: Attempting to train S4/Mamba with standard non-fused PyTorch scan operators, causing massive memory overhead and GPU stalling.
- **Verification & Mastery Check**: Implement a discrete State Space Model forward pass in PyTorch; verify linear $O(T)$ memory scaling on 10,000 token sequences.
- **Project Application**: Track D Capstone: Selective State Space (Mamba) sequence model.', '{"solution.py": "# Phase 13 // Lesson 13.18: Track D: State Space Models (SSMs) & Modern Mamba Architecture\n\ndef solve():\n    \"\"\"\n    Verification: Implement a discrete State Space Model forward pass in PyTorch; verify linear $O(T)$ memory scaling \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.18", "subtopics_count": 6, "verification_criteria": "Implement a discrete State Space Model forward pass in PyTorch; verify linear $O(T)$ memory scaling on 10,000 token sequences.", "subtopics": ["13.18.1 The quadratic bottleneck of Transformers: $O(T^2)$ computational complexity of self-attention limiting long-context scalability", "13.18.2 Classical State Space Models: continuous differential equations mapping 1D stimulus $x(t) \\to y(t)$ via latent state $h(t)$", "13.18.3 HiPPO framework (High-order Polynomial Projection Operators): memory initialization maintaining continuous signal history", "13.18.4 Structured State Space Models (S4): continuous to discrete discretization (Bilinear / Euler transform) and fast convolutional training", "13.18.5 Mamba architecture (Gu & Dao): Selective State Spaces (S6) making transition matrices input-dependent to filter irrelevant information", "13.18.6 Hardware-aware selective scan: fused GPU SRAM kernel eliminating slow HBM transfers, achieving linear $O(T)$ training and $O(1)$ inference"]}'::jsonb, '["Explain how this implementation prevents: Attempting to train S4/Mamba with standard non-fused PyTorch scan operators, causing massive memory overhead and GPU sta", "How does Track D: State Space Models (SSMs) & Modern Mamba Architecture scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-19', 'phase-13-lesson-19-track-d-mechanistic-interpretability-prob', 'module-14', 19, 'Lesson 14.19: Track D: Mechanistic Interpretability: Probing Features & Induction Heads', 'Prerequisites: Phase 9, Phase 10', 'Prerequisites: Phase 9, Phase 10 | Subtopics: 6 items', 'Systems project application', 360, 14, 3310.0, 950.0, '# Lesson 13.19: Track D: Mechanistic Interpretability: Probing Features & Induction Heads

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 10
- **Subtopics**:
  - `13.19.1` The mechanistic interpretability goal: reverse-engineering the internal weights and circuits of neural networks into human-understandable algorithms
  - `13.19.2` Linear Artificial Neurons vs Polysemanticity: single neurons firing for completely unrelated concepts due to superposition
  - `13.19.3` Sparse Autoencoders (SAEs) (Anthropic): decomposing internal dense activations into sparse, monosemantic feature dictionaries
  - `13.19.4` Attention circuit analysis (Elhage et al.): QK-circuits (where tokens attend) vs OV-circuits (what information is moved)
  - `13.19.5` Induction Heads: two-layer attention circuits that implement in-context pattern completion ($[A][B] \dots [A] \to [B]$)
  - `13.19.6` Activation patching and causal scrubbing: isolating exact neural sub-circuits responsible for specific factual recall and reasoning
- **Key Failure Modes & Edge Cases**: Assuming individual neurons map to single human concepts, ignoring superposition and cross-layer feature interference.
- **Verification & Mastery Check**: Train a Sparse Autoencoder (SAE) on transformer hidden states; extract and visualize monosemantic features and verify induction heads.
- **Project Application**: Track D Capstone: Mechanistic interpretability and SAE feature extraction harness.', '{"solution.py": "# Phase 13 // Lesson 13.19: Track D: Mechanistic Interpretability: Probing Features & Induction Heads\n\ndef solve():\n    \"\"\"\n    Verification: Train a Sparse Autoencoder (SAE) on transformer hidden states; extract and visualize monosemantic fe\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.19", "subtopics_count": 6, "verification_criteria": "Train a Sparse Autoencoder (SAE) on transformer hidden states; extract and visualize monosemantic features and verify induction heads.", "subtopics": ["13.19.1 The mechanistic interpretability goal: reverse-engineering the internal weights and circuits of neural networks into human-understandable algorithms", "13.19.2 Linear Artificial Neurons vs Polysemanticity: single neurons firing for completely unrelated concepts due to superposition", "13.19.3 Sparse Autoencoders (SAEs) (Anthropic): decomposing internal dense activations into sparse, monosemantic feature dictionaries", "13.19.4 Attention circuit analysis (Elhage et al.): QK-circuits (where tokens attend) vs OV-circuits (what information is moved)", "13.19.5 Induction Heads: two-layer attention circuits that implement in-context pattern completion ($[A][B] \\dots [A] \\to [B]$)", "13.19.6 Activation patching and causal scrubbing: isolating exact neural sub-circuits responsible for specific factual recall and reasoning"]}'::jsonb, '["Explain how this implementation prevents: Assuming individual neurons map to single human concepts, ignoring superposition and cross-layer feature interference.", "How does Track D: Mechanistic Interpretability: Probing Features & Induction Heads scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-20', 'phase-13-lesson-20-track-d-frontier-model-quantization-custo', 'module-14', 20, 'Lesson 14.20: Track D: Frontier Model Quantization & Custom Kernel Engineering (Triton)', 'Prerequisites: Phase 0, Phase 9, Phase 11', 'Prerequisites: Phase 0, Phase 9, Phase 11 | Subtopics: 6 items', 'Systems project application', 360, 14, 3370.0, 1000.0, '# Lesson 13.20: Track D: Frontier Model Quantization & Custom Kernel Engineering (Triton)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 9, Phase 11
- **Subtopics**:
  - `13.20.1` The memory wall in deep learning: compute speed exceeding GPU memory bandwidth; arithmetic intensity optimization
  - `13.20.2` OpenAI Triton language: Python-based programming model for writing high-performance GPU kernels without writing raw CUDA C++
  - `13.20.3` Triton programming mental model: block-level programming, automated shared memory management, and coalesced global memory loads
  - `13.20.4` Writing a custom fused Softmax kernel in Triton: loading blocks into SRAM, vectorized operations, and storing results with minimal HBM passes
  - `13.20.5` Writing a fused FlashAttention kernel in Triton: tiling Query, Key, Value blocks, online softmax scaling, and zero materialized $T \times T$ matrix
  - `13.20.6` Benchmarking custom Triton kernels: achieving $> 80\%$ of theoretical peak hardware TFLOPs on modern NVIDIA GPUs
- **Key Failure Modes & Edge Cases**: Failing to handle non-power-of-two tensor boundaries in Triton block masking, producing silent memory corruption.
- **Verification & Mastery Check**: Write and benchmark a custom fused FlashAttention kernel in OpenAI Triton; demonstrate $3\times$ speedup over native PyTorch attention.
- **Project Application**: Track D Capstone: Custom fused FlashAttention Triton kernel.', '{"solution.py": "# Phase 13 // Lesson 13.20: Track D: Frontier Model Quantization & Custom Kernel Engineering (Triton)\n\ndef solve():\n    \"\"\"\n    Verification: Write and benchmark a custom fused FlashAttention kernel in OpenAI Triton; demonstrate $3\\times$ spe\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.20", "subtopics_count": 6, "verification_criteria": "Write and benchmark a custom fused FlashAttention kernel in OpenAI Triton; demonstrate $3\\times$ speedup over native PyTorch attention.", "subtopics": ["13.20.1 The memory wall in deep learning: compute speed exceeding GPU memory bandwidth; arithmetic intensity optimization", "13.20.2 OpenAI Triton language: Python-based programming model for writing high-performance GPU kernels without writing raw CUDA C++", "13.20.3 Triton programming mental model: block-level programming, automated shared memory management, and coalesced global memory loads", "13.20.4 Writing a custom fused Softmax kernel in Triton: loading blocks into SRAM, vectorized operations, and storing results with minimal HBM passes", "13.20.5 Writing a fused FlashAttention kernel in Triton: tiling Query, Key, Value blocks, online softmax scaling, and zero materialized $T \\times T$ matrix", "13.20.6 Benchmarking custom Triton kernels: achieving $> 80\\%$ of theoretical peak hardware TFLOPs on modern NVIDIA GPUs"]}'::jsonb, '["Explain how this implementation prevents: Failing to handle non-power-of-two tensor boundaries in Triton block masking, producing silent memory corruption.", "How does Track D: Frontier Model Quantization & Custom Kernel Engineering (Triton) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-1', 'phase-14-lesson-01-enterprise-capstone-i-system-architecture', 'module-14', 21, 'Lesson 14.21: Enterprise Capstone I: System Architecture & Non-Functional Requirements', 'Prerequisites: Phase 8, Phase 12', 'Prerequisites: Phase 8, Phase 12 | Subtopics: 6 items', 'Systems project application', 380, 15, 3560.0, 50.0, '# Lesson 14.1: Enterprise Capstone I: System Architecture & Non-Functional Requirements

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 8, Phase 12
- **Subtopics**:
  - `14.1.1` Defining the enterprise project charter: building a multi-tenant, autonomous software intelligence and operations platform
  - `14.1.2` Scoping functional requirements: automated code review, security remediation, real-time telemetry analytics, autonomous bug repair
  - `14.1.3` Scoping non-functional requirements: $99.99\%$ uptime SLA, sub-200ms API p99 latency, zero cross-tenant data leakage
  - `14.1.4` Architecture Decision Records (ADRs): documenting technology choices across database, frontend, messaging, and AI models
  - `14.1.5` Threat modeling: defining security boundaries, zero-trust network policies, and PII compliance controls
  - `14.1.6` Creating the multi-repository vs monorepo workspace structure with Turborepo and strict dependency boundaries
- **Key Failure Modes & Edge Cases**: Vague architectural boundaries leading to monolithic spaghetti code and circular dependencies between services.
- **Verification & Mastery Check**: Author the complete System Architecture Specification and ADR documentation; pass an initial architectural review.
- **Project Application**: Enterprise Capstone: System architecture document and ADRs.', '{"solution.py": "# Phase 14 // Lesson 14.1: Enterprise Capstone I: System Architecture & Non-Functional Requirements\n\ndef solve():\n    \"\"\"\n    Verification: Author the complete System Architecture Specification and ADR documentation; pass an initial archite\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.1", "subtopics_count": 6, "verification_criteria": "Author the complete System Architecture Specification and ADR documentation; pass an initial architectural review.", "subtopics": ["14.1.1 Defining the enterprise project charter: building a multi-tenant, autonomous software intelligence and operations platform", "14.1.2 Scoping functional requirements: automated code review, security remediation, real-time telemetry analytics, autonomous bug repair", "14.1.3 Scoping non-functional requirements: $99.99\\%$ uptime SLA, sub-200ms API p99 latency, zero cross-tenant data leakage", "14.1.4 Architecture Decision Records (ADRs): documenting technology choices across database, frontend, messaging, and AI models", "14.1.5 Threat modeling: defining security boundaries, zero-trust network policies, and PII compliance controls", "14.1.6 Creating the multi-repository vs monorepo workspace structure with Turborepo and strict dependency boundaries"]}'::jsonb, '["Explain how this implementation prevents: Vague architectural boundaries leading to monolithic spaghetti code and circular dependencies between services.", "How does Enterprise Capstone I: System Architecture & Non-Functional Requirements scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-2', 'phase-14-lesson-02-enterprise-capstone-ii-relational-data-mo', 'module-14', 22, 'Lesson 14.22: Enterprise Capstone II: Relational Data Modeling & Multi-Tenant Isolation', 'Prerequisites: Phase 5, Phase 10', 'Prerequisites: Phase 5, Phase 10 | Subtopics: 6 items', 'Systems project application', 380, 15, 3620.0, 100.0, '# Lesson 14.2: Enterprise Capstone II: Relational Data Modeling & Multi-Tenant Isolation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Phase 10
- **Subtopics**:
  - `14.2.1` Designing the core relational schema in PostgreSQL: organizations, users, workspaces, repositories, agent tasks, audits
  - `14.2.2` Multi-tenant isolation patterns: Row-Level Security (RLS) vs schema-per-tenant vs database-per-tenant trade-offs
  - `14.2.3` Implementing PostgreSQL Row-Level Security (RLS): policies enforcing `WHERE organization_id = current_setting(''app.current_org_id'')`
  - `14.2.4` Migration pipeline: automated, backward-compatible migrations with Flyway/Prisma/Alembic in continuous delivery pipelines
  - `14.2.5` High-performance indexing: composite B-trees, GIN indexes on JSONB metadata, and partial indexes for active tasks
  - `14.2.6` Seeding the database: generating deterministic, realistic enterprise fixture data with millions of mock records for stress testing
- **Key Failure Modes & Edge Cases**: Leaking tenant data due to missing RLS policies or forgotten `organization_id` filters on complex join queries.
- **Verification & Mastery Check**: Implement and verify PostgreSQL Row-Level Security across 15 relational tables with automated multi-tenant isolation unit tests.
- **Project Application**: Enterprise Capstone: Relational database schema with RLS.', '{"solution.py": "# Phase 14 // Lesson 14.2: Enterprise Capstone II: Relational Data Modeling & Multi-Tenant Isolation\n\ndef solve():\n    \"\"\"\n    Verification: Implement and verify PostgreSQL Row-Level Security across 15 relational tables with automated multi-\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.2", "subtopics_count": 6, "verification_criteria": "Implement and verify PostgreSQL Row-Level Security across 15 relational tables with automated multi-tenant isolation unit tests.", "subtopics": ["14.2.1 Designing the core relational schema in PostgreSQL: organizations, users, workspaces, repositories, agent tasks, audits", "14.2.2 Multi-tenant isolation patterns: Row-Level Security (RLS) vs schema-per-tenant vs database-per-tenant trade-offs", "14.2.3 Implementing PostgreSQL Row-Level Security (RLS): policies enforcing `WHERE organization_id = current_setting(''app.current_org_id'')`", "14.2.4 Migration pipeline: automated, backward-compatible migrations with Flyway/Prisma/Alembic in continuous delivery pipelines", "14.2.5 High-performance indexing: composite B-trees, GIN indexes on JSONB metadata, and partial indexes for active tasks", "14.2.6 Seeding the database: generating deterministic, realistic enterprise fixture data with millions of mock records for stress testing"]}'::jsonb, '["Explain how this implementation prevents: Leaking tenant data due to missing RLS policies or forgotten `organization_id` filters on complex join queries.", "How does Enterprise Capstone II: Relational Data Modeling & Multi-Tenant Isolation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-3', 'phase-14-lesson-03-enterprise-capstone-iii-high-throughput-e', 'module-14', 23, 'Lesson 14.23: Enterprise Capstone III: High-Throughput Event Streaming & Task Queues', 'Prerequisites: Phase 4, Phase 5, Phase 7', 'Prerequisites: Phase 4, Phase 5, Phase 7 | Subtopics: 6 items', 'Systems project application', 380, 15, 3500.0, 150.0, '# Lesson 14.3: Enterprise Capstone III: High-Throughput Event Streaming & Task Queues

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 5, Phase 7
- **Subtopics**:
  - `14.3.1` Asynchronous event backbone: deploying Apache Kafka KRaft clusters for high-throughput event ingestion
  - `14.3.2` Defining event schemas with Protocol Buffers: strict backward and forward schema compatibility guarantees
  - `14.3.3` Kafka producer pipeline: idempotent producers with `acks=all`, batching, and snappy compression
  - `14.3.4` Kafka consumer architecture: consumer groups, partition assignments, and non-blocking retry topics with exponential backoff
  - `14.3.5` Celery and Redis task queue integration: orchestrating long-running asynchronous background jobs with progress reporting
  - `14.3.6` Dead Letter Queues (DLQ) and alert routing: capturing failed messages, poison pills, and automated administrative replay
- **Key Failure Modes & Edge Cases**: Message loss during consumer restarts; poison pills stalling partition consumption indefinitely without DLQs.
- **Verification & Mastery Check**: Deploy Kafka and Celery streaming infrastructure; achieve 20,000 events/sec ingestion with zero dropped messages.
- **Project Application**: Enterprise Capstone: Distributed event streaming and task queue pipeline.', '{"solution.py": "# Phase 14 // Lesson 14.3: Enterprise Capstone III: High-Throughput Event Streaming & Task Queues\n\ndef solve():\n    \"\"\"\n    Verification: Deploy Kafka and Celery streaming infrastructure; achieve 20,000 events/sec ingestion with zero drop\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.3", "subtopics_count": 6, "verification_criteria": "Deploy Kafka and Celery streaming infrastructure; achieve 20,000 events/sec ingestion with zero dropped messages.", "subtopics": ["14.3.1 Asynchronous event backbone: deploying Apache Kafka KRaft clusters for high-throughput event ingestion", "14.3.2 Defining event schemas with Protocol Buffers: strict backward and forward schema compatibility guarantees", "14.3.3 Kafka producer pipeline: idempotent producers with `acks=all`, batching, and snappy compression", "14.3.4 Kafka consumer architecture: consumer groups, partition assignments, and non-blocking retry topics with exponential backoff", "14.3.5 Celery and Redis task queue integration: orchestrating long-running asynchronous background jobs with progress reporting", "14.3.6 Dead Letter Queues (DLQ) and alert routing: capturing failed messages, poison pills, and automated administrative replay"]}'::jsonb, '["Explain how this implementation prevents: Message loss during consumer restarts; poison pills stalling partition consumption indefinitely without DLQs.", "How does Enterprise Capstone III: High-Throughput Event Streaming & Task Queues scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-4', 'phase-14-lesson-04-enterprise-capstone-iv-hybrid-rag-pipelin', 'module-14', 24, 'Lesson 14.24: Enterprise Capstone IV: Hybrid RAG Pipeline & Vector Search Engine', 'Prerequisites: Phase 10', 'Prerequisites: Phase 10 | Subtopics: 6 items', 'Systems project application', 380, 15, 3560.0, 200.0, '# Lesson 14.4: Enterprise Capstone IV: Hybrid RAG Pipeline & Vector Search Engine

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 10
- **Subtopics**:
  - `14.4.1` Enterprise knowledge indexing: ingesting multi-format documentation, source code repositories, and user support tickets
  - `14.4.2` Layout-aware document parsing: extracting markdown hierarchies, AST symbol graphs, and tabular data
  - `14.4.3` Dual-stream hybrid retrieval: pgvector HNSW dense semantic search + PostgreSQL BM25 full-text search
  - `14.4.4` Reciprocal Rank Fusion (RRF): combining search result ranks into a unified candidate pool ($k=60$)
  - `14.4.5` Cross-Encoder re-ranking: scoring top-50 candidates down to top-5 high-relevance chunks using BAAI `bge-reranker-large`
  - `14.4.6` Evaluation gate: verifying with EvalKit that retrieval achieves Context Relevance $>0.88$ and Groundedness $>0.96$
- **Key Failure Modes & Edge Cases**: Vector search returning outdated documentation versions due to missing temporal and version metadata filtering.
- **Verification & Mastery Check**: Implement and evaluate the end-to-end hybrid RAG retrieval pipeline on 100,000 enterprise documents with sub-150ms latency.
- **Project Application**: Enterprise Capstone: Production hybrid RAG and vector search service.', '{"solution.py": "# Phase 14 // Lesson 14.4: Enterprise Capstone IV: Hybrid RAG Pipeline & Vector Search Engine\n\ndef solve():\n    \"\"\"\n    Verification: Implement and evaluate the end-to-end hybrid RAG retrieval pipeline on 100,000 enterprise documents \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.4", "subtopics_count": 6, "verification_criteria": "Implement and evaluate the end-to-end hybrid RAG retrieval pipeline on 100,000 enterprise documents with sub-150ms latency.", "subtopics": ["14.4.1 Enterprise knowledge indexing: ingesting multi-format documentation, source code repositories, and user support tickets", "14.4.2 Layout-aware document parsing: extracting markdown hierarchies, AST symbol graphs, and tabular data", "14.4.3 Dual-stream hybrid retrieval: pgvector HNSW dense semantic search + PostgreSQL BM25 full-text search", "14.4.4 Reciprocal Rank Fusion (RRF): combining search result ranks into a unified candidate pool ($k=60$)", "14.4.5 Cross-Encoder re-ranking: scoring top-50 candidates down to top-5 high-relevance chunks using BAAI `bge-reranker-large`", "14.4.6 Evaluation gate: verifying with EvalKit that retrieval achieves Context Relevance $>0.88$ and Groundedness $>0.96$"]}'::jsonb, '["Explain how this implementation prevents: Vector search returning outdated documentation versions due to missing temporal and version metadata filtering.", "How does Enterprise Capstone IV: Hybrid RAG Pipeline & Vector Search Engine scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-5', 'phase-14-lesson-05-enterprise-capstone-v-autonomous-multi-ag', 'module-14', 25, 'Lesson 14.25: Enterprise Capstone V: Autonomous Multi-Agent Engineering Workflows', 'Prerequisites: Phase 12', 'Prerequisites: Phase 12 | Subtopics: 6 items', 'Systems project application', 380, 15, 3620.0, 250.0, '# Lesson 14.5: Enterprise Capstone V: Autonomous Multi-Agent Engineering Workflows

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 12
- **Subtopics**:
  - `14.5.1` Orchestrating autonomous workflows with LangGraph: Planner, Researcher, Coder, and QA Reviewer agent nodes
  - `14.5.2` Durable state persistence: `AsyncPostgresSaver` checkpointing every superstep to enable seamless crash recovery
  - `14.5.3` Human-in-the-Loop review gates: programmatic `interrupt()` triggers before deploying code or modifying database schemas
  - `14.5.4` Sandboxed tool execution: executing agent-generated Bash and Python scripts inside ephemeral gVisor-hardened Docker containers
  - `14.5.5` AST code navigation: Tree-sitter powered symbol extraction and non-destructive line-targeted diff patching
  - `14.5.6` Automated TDD loop: agent writes test, verifies failure, modifies source code, and validates full test suite pass
- **Key Failure Modes & Edge Cases**: Agent entering infinite execution loops or executing destructive commands outside the sandboxed workspace boundary.
- **Verification & Mastery Check**: Deploy the autonomous multi-agent engineering workflow; verify that it autonomously fixes bugs in a test repository.
- **Project Application**: Enterprise Capstone: Autonomous multi-agent orchestration engine.', '{"solution.py": "# Phase 14 // Lesson 14.5: Enterprise Capstone V: Autonomous Multi-Agent Engineering Workflows\n\ndef solve():\n    \"\"\"\n    Verification: Deploy the autonomous multi-agent engineering workflow; verify that it autonomously fixes bugs in a \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.5", "subtopics_count": 6, "verification_criteria": "Deploy the autonomous multi-agent engineering workflow; verify that it autonomously fixes bugs in a test repository.", "subtopics": ["14.5.1 Orchestrating autonomous workflows with LangGraph: Planner, Researcher, Coder, and QA Reviewer agent nodes", "14.5.2 Durable state persistence: `AsyncPostgresSaver` checkpointing every superstep to enable seamless crash recovery", "14.5.3 Human-in-the-Loop review gates: programmatic `interrupt()` triggers before deploying code or modifying database schemas", "14.5.4 Sandboxed tool execution: executing agent-generated Bash and Python scripts inside ephemeral gVisor-hardened Docker containers", "14.5.5 AST code navigation: Tree-sitter powered symbol extraction and non-destructive line-targeted diff patching", "14.5.6 Automated TDD loop: agent writes test, verifies failure, modifies source code, and validates full test suite pass"]}'::jsonb, '["Explain how this implementation prevents: Agent entering infinite execution loops or executing destructive commands outside the sandboxed workspace boundary.", "How does Enterprise Capstone V: Autonomous Multi-Agent Engineering Workflows scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-6', 'phase-14-lesson-06-enterprise-capstone-vi-full-stack-saas-we', 'module-14', 26, 'Lesson 14.26: Enterprise Capstone VI: Full-Stack SaaS Web Application & Real-Time UI', 'Prerequisites: Phase 6', 'Prerequisites: Phase 6 | Subtopics: 6 items', 'Systems project application', 380, 15, 3500.0, 300.0, '# Lesson 14.6: Enterprise Capstone VI: Full-Stack SaaS Web Application & Real-Time UI

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 6
- **Subtopics**:
  - `14.6.1` Next.js App Router architecture: nested layouts, React Server Components (RSC), and Server Actions
  - `14.6.2` CompKit design system integration: accessible, theme-aware UI primitives adhering to WCAG 2.2 AAA guidelines
  - `14.6.3` Real-time streaming interfaces: Server-Sent Events (SSE) streaming live LLM tokens and agent thought trajectories
  - `14.6.4` Interactive multi-agent dashboard: visualizing active agent state graphs, tool invocations, and diff approval modals
  - `14.6.5` Stripe subscription integration: self-service checkout, multi-tier seat licensing, customer billing portal, and webhooks
  - `14.6.6` Client-side performance engineering: optimizing Core Web Vitals to achieve 98+ Lighthouse scores across all pages
- **Key Failure Modes & Edge Cases**: Client-side re-rendering waterfalls freezing UI during high-frequency agent streaming event floods.
- **Verification & Mastery Check**: Build and deploy the complete Next.js full-stack web application; verify real-time SSE streaming and Stripe billing checkout.
- **Project Application**: Enterprise Capstone: Full-stack web dashboard and user portal.', '{"solution.py": "# Phase 14 // Lesson 14.6: Enterprise Capstone VI: Full-Stack SaaS Web Application & Real-Time UI\n\ndef solve():\n    \"\"\"\n    Verification: Build and deploy the complete Next.js full-stack web application; verify real-time SSE streaming and\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.6", "subtopics_count": 6, "verification_criteria": "Build and deploy the complete Next.js full-stack web application; verify real-time SSE streaming and Stripe billing checkout.", "subtopics": ["14.6.1 Next.js App Router architecture: nested layouts, React Server Components (RSC), and Server Actions", "14.6.2 CompKit design system integration: accessible, theme-aware UI primitives adhering to WCAG 2.2 AAA guidelines", "14.6.3 Real-time streaming interfaces: Server-Sent Events (SSE) streaming live LLM tokens and agent thought trajectories", "14.6.4 Interactive multi-agent dashboard: visualizing active agent state graphs, tool invocations, and diff approval modals", "14.6.5 Stripe subscription integration: self-service checkout, multi-tier seat licensing, customer billing portal, and webhooks", "14.6.6 Client-side performance engineering: optimizing Core Web Vitals to achieve 98+ Lighthouse scores across all pages"]}'::jsonb, '["Explain how this implementation prevents: Client-side re-rendering waterfalls freezing UI during high-frequency agent streaming event floods.", "How does Enterprise Capstone VI: Full-Stack SaaS Web Application & Real-Time UI scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-7', 'phase-14-lesson-07-enterprise-capstone-vii-automated-testing', 'module-14', 27, 'Lesson 14.27: Enterprise Capstone VII: Automated Testing, Vitest & Playwright E2E', 'Prerequisites: Phase 1, Phase 5, Phase 6', 'Prerequisites: Phase 1, Phase 5, Phase 6 | Subtopics: 6 items', 'Systems project application', 380, 15, 3560.0, 350.0, '# Lesson 14.7: Enterprise Capstone VII: Automated Testing, Vitest & Playwright E2E

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Phase 5, Phase 6
- **Subtopics**:
  - `14.7.1` Comprehensive testing pyramid: Unit tests ($>80\%$ coverage), Integration tests, and End-to-End (E2E) test suites
  - `14.7.2` Backend integration testing: testing FastAPI endpoints, database migrations, and Kafka producers using `pytest` and `testcontainers`
  - `14.7.3` Frontend unit testing: testing React components, custom hooks, and state reducers with Vitest and React Testing Library
  - `14.7.4` Mocking external dependencies: Mock Service Worker (MSW) intercepting Stripe and LLM API calls in CI environments
  - `14.7.5` Playwright E2E automation: multi-browser tests covering user signup, workspace creation, agent invocation, and billing upgrade
  - `14.7.6` Visual regression testing: automated pixel-diff comparisons catching unintentional CSS layout regressions
- **Key Failure Modes & Edge Cases**: Flaky E2E tests relying on arbitrary timeouts, breaking CI/CD deployment pipelines on minor network jitter.
- **Verification & Mastery Check**: Execute the complete test suite: 500+ unit tests, 100+ integration tests, and 20 Playwright E2E journeys passing with 0 flakes.
- **Project Application**: Enterprise Capstone: Automated test harness and E2E validation suite.', '{"solution.py": "# Phase 14 // Lesson 14.7: Enterprise Capstone VII: Automated Testing, Vitest & Playwright E2E\n\ndef solve():\n    \"\"\"\n    Verification: Execute the complete test suite: 500+ unit tests, 100+ integration tests, and 20 Playwright E2E jour\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.7", "subtopics_count": 6, "verification_criteria": "Execute the complete test suite: 500+ unit tests, 100+ integration tests, and 20 Playwright E2E journeys passing with 0 flakes.", "subtopics": ["14.7.1 Comprehensive testing pyramid: Unit tests ($>80\\%$ coverage), Integration tests, and End-to-End (E2E) test suites", "14.7.2 Backend integration testing: testing FastAPI endpoints, database migrations, and Kafka producers using `pytest` and `testcontainers`", "14.7.3 Frontend unit testing: testing React components, custom hooks, and state reducers with Vitest and React Testing Library", "14.7.4 Mocking external dependencies: Mock Service Worker (MSW) intercepting Stripe and LLM API calls in CI environments", "14.7.5 Playwright E2E automation: multi-browser tests covering user signup, workspace creation, agent invocation, and billing upgrade", "14.7.6 Visual regression testing: automated pixel-diff comparisons catching unintentional CSS layout regressions"]}'::jsonb, '["Explain how this implementation prevents: Flaky E2E tests relying on arbitrary timeouts, breaking CI/CD deployment pipelines on minor network jitter.", "How does Enterprise Capstone VII: Automated Testing, Vitest & Playwright E2E scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-8', 'phase-14-lesson-08-enterprise-capstone-viii-cloud-infrastruc', 'module-14', 28, 'Lesson 14.28: Enterprise Capstone VIII: Cloud Infrastructure as Code with Terraform', 'Prerequisites: Phase 7', 'Prerequisites: Phase 7 | Subtopics: 6 items', 'Systems project application', 380, 15, 3620.0, 400.0, '# Lesson 14.8: Enterprise Capstone VIII: Cloud Infrastructure as Code with Terraform

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7
- **Subtopics**:
  - `14.8.1` Declarative infrastructure provisioning on Google Cloud Platform (GCP) using modular Terraform
  - `14.8.2` Remote state architecture: GCS backend with state locking, customer-managed KMS encryption, and environment segregation
  - `14.8.3` VPC and networking: multi-zone custom VPC, private subnets, Cloud NAT, and Private Google Access
  - `14.8.4` Managed Kubernetes: private VPC-native GKE cluster provisioning with Workload Identity and Cilium CNI
  - `14.8.5` Managed database and cache provisioning: Cloud SQL PostgreSQL instance and Memorystore Redis clusters with private IPs
  - `14.8.6` Automated Terraform CI/CD: running `tflint`, `tfsec`, and automated `terraform plan` on all pull requests
- **Key Failure Modes & Edge Cases**: Manual cloud resource creation leading to un-tracked infrastructure drift and un-reproducible environments.
- **Verification & Mastery Check**: Provision the complete multi-region cloud infrastructure from scratch using Terraform with a single automated apply.
- **Project Application**: Enterprise Capstone: Production Terraform infrastructure repository.', '{"solution.py": "# Phase 14 // Lesson 14.8: Enterprise Capstone VIII: Cloud Infrastructure as Code with Terraform\n\ndef solve():\n    \"\"\"\n    Verification: Provision the complete multi-region cloud infrastructure from scratch using Terraform with a single \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.8", "subtopics_count": 6, "verification_criteria": "Provision the complete multi-region cloud infrastructure from scratch using Terraform with a single automated apply.", "subtopics": ["14.8.1 Declarative infrastructure provisioning on Google Cloud Platform (GCP) using modular Terraform", "14.8.2 Remote state architecture: GCS backend with state locking, customer-managed KMS encryption, and environment segregation", "14.8.3 VPC and networking: multi-zone custom VPC, private subnets, Cloud NAT, and Private Google Access", "14.8.4 Managed Kubernetes: private VPC-native GKE cluster provisioning with Workload Identity and Cilium CNI", "14.8.5 Managed database and cache provisioning: Cloud SQL PostgreSQL instance and Memorystore Redis clusters with private IPs", "14.8.6 Automated Terraform CI/CD: running `tflint`, `tfsec`, and automated `terraform plan` on all pull requests"]}'::jsonb, '["Explain how this implementation prevents: Manual cloud resource creation leading to un-tracked infrastructure drift and un-reproducible environments.", "How does Enterprise Capstone VIII: Cloud Infrastructure as Code with Terraform scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-9', 'phase-14-lesson-09-enterprise-capstone-ix-kubernetes-deploym', 'module-14', 29, 'Lesson 14.29: Enterprise Capstone IX: Kubernetes Deployment, GitOps & ArgoCD', 'Prerequisites: Phase 7', 'Prerequisites: Phase 7 | Subtopics: 6 items', 'Systems project application', 380, 15, 3500.0, 450.0, '# Lesson 14.9: Enterprise Capstone IX: Kubernetes Deployment, GitOps & ArgoCD

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7
- **Subtopics**:
  - `14.9.1` Packaging applications: multi-stage OCI container builds producing minimal distroless images with 0 CVEs
  - `14.9.2` Kubernetes workload manifests: Deployments, StatefulSets, Services, and Gateway API HTTPRoute definitions
  - `14.9.3` Secret management: External Secrets Operator (ESO) synchronizing secrets from GCP Secret Manager into Kubernetes
  - `14.9.4` GitOps continuous delivery with ArgoCD: App-of-Apps pattern, automated sync policies, and self-healing reconciliation
  - `14.9.5` Horizontal Pod Autoscaling (HPA): autoscaling workloads dynamically based on real-time Prometheus QPS and CPU metrics
  - `14.9.6` Zero-downtime rolling updates: calibrated `preStop` hooks, termination grace periods, and readiness probe thresholds
- **Key Failure Modes & Edge Cases**: Deploying containers as root or exposing plaintext secrets in git manifests, violating enterprise security policies.
- **Verification & Mastery Check**: Deploy the full microservice fleet to GKE using ArgoCD GitOps; execute a rolling update with zero dropped client connections.
- **Project Application**: Enterprise Capstone: Kubernetes manifests and ArgoCD GitOps repository.', '{"solution.py": "# Phase 14 // Lesson 14.9: Enterprise Capstone IX: Kubernetes Deployment, GitOps & ArgoCD\n\ndef solve():\n    \"\"\"\n    Verification: Deploy the full microservice fleet to GKE using ArgoCD GitOps; execute a rolling update with zero dr\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.9", "subtopics_count": 6, "verification_criteria": "Deploy the full microservice fleet to GKE using ArgoCD GitOps; execute a rolling update with zero dropped client connections.", "subtopics": ["14.9.1 Packaging applications: multi-stage OCI container builds producing minimal distroless images with 0 CVEs", "14.9.2 Kubernetes workload manifests: Deployments, StatefulSets, Services, and Gateway API HTTPRoute definitions", "14.9.3 Secret management: External Secrets Operator (ESO) synchronizing secrets from GCP Secret Manager into Kubernetes", "14.9.4 GitOps continuous delivery with ArgoCD: App-of-Apps pattern, automated sync policies, and self-healing reconciliation", "14.9.5 Horizontal Pod Autoscaling (HPA): autoscaling workloads dynamically based on real-time Prometheus QPS and CPU metrics", "14.9.6 Zero-downtime rolling updates: calibrated `preStop` hooks, termination grace periods, and readiness probe thresholds"]}'::jsonb, '["Explain how this implementation prevents: Deploying containers as root or exposing plaintext secrets in git manifests, violating enterprise security policies.", "How does Enterprise Capstone IX: Kubernetes Deployment, GitOps & ArgoCD scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-10', 'phase-14-lesson-10-enterprise-capstone-x-distributed-observa', 'module-14', 30, 'Lesson 14.30: Enterprise Capstone X: Distributed Observability, Tracing & Alerting', 'Prerequisites: Phase 7, Phase 11', 'Prerequisites: Phase 7, Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3560.0, 500.0, '# Lesson 14.10: Enterprise Capstone X: Distributed Observability, Tracing & Alerting

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Phase 11
- **Subtopics**:
  - `14.10.1` End-to-end distributed tracing: OpenTelemetry (OTel) instrumentation across Next.js, FastAPI, Celery, and LangGraph
  - `14.10.2` Collecting telemetry: OTel Collector routing spans to Jaeger/Tempo, metrics to Prometheus, and logs to Grafana Loki
  - `14.10.3` Grafana dashboards: designing unified operational dashboards correlating request latency, error rates, and resource utilization
  - `14.10.4` Service Level Objectives (SLOs): configuring 99.9% availability and $<200$ms p95 latency SLOs with error budget alerts
  - `14.10.5` Prometheus Alertmanager: multi-window multi-burn-rate alerts routing critical pages to PagerDuty and warnings to Slack
  - `14.10.6` GenAI observability: tracking prompt tokens, completion tokens, LLM latency, and retrieval quality scores in Langfuse
- **Key Failure Modes & Edge Cases**: Alert fatigue caused by low-threshold CPU alerts; missing distributed trace headers across asynchronous Celery task boundaries.
- **Verification & Mastery Check**: Deploy the complete observability stack; trace a user request from frontend click through Kafka, Celery, and LLM to database.
- **Project Application**: Enterprise Capstone: Enterprise observability and Grafana monitoring stack.', '{"solution.py": "# Phase 14 // Lesson 14.10: Enterprise Capstone X: Distributed Observability, Tracing & Alerting\n\ndef solve():\n    \"\"\"\n    Verification: Deploy the complete observability stack; trace a user request from frontend click through Kafka, Cel\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.10", "subtopics_count": 6, "verification_criteria": "Deploy the complete observability stack; trace a user request from frontend click through Kafka, Celery, and LLM to database.", "subtopics": ["14.10.1 End-to-end distributed tracing: OpenTelemetry (OTel) instrumentation across Next.js, FastAPI, Celery, and LangGraph", "14.10.2 Collecting telemetry: OTel Collector routing spans to Jaeger/Tempo, metrics to Prometheus, and logs to Grafana Loki", "14.10.3 Grafana dashboards: designing unified operational dashboards correlating request latency, error rates, and resource utilization", "14.10.4 Service Level Objectives (SLOs): configuring 99.9% availability and $<200$ms p95 latency SLOs with error budget alerts", "14.10.5 Prometheus Alertmanager: multi-window multi-burn-rate alerts routing critical pages to PagerDuty and warnings to Slack", "14.10.6 GenAI observability: tracking prompt tokens, completion tokens, LLM latency, and retrieval quality scores in Langfuse"]}'::jsonb, '["Explain how this implementation prevents: Alert fatigue caused by low-threshold CPU alerts; missing distributed trace headers across asynchronous Celery task boun", "How does Enterprise Capstone X: Distributed Observability, Tracing & Alerting scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-11', 'phase-14-lesson-11-enterprise-capstone-xi-production-profili', 'module-14', 31, 'Lesson 14.31: Enterprise Capstone XI: Production Profiling & Performance Tuning', 'Prerequisites: Phase 11', 'Prerequisites: Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3620.0, 550.0, '# Lesson 14.11: Enterprise Capstone XI: Production Profiling & Performance Tuning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 11
- **Subtopics**:
  - `14.11.1` Profiling under load: identifying CPU and memory bottlenecks using `py-spy` and `memray` under sustained traffic
  - `14.11.2` Database query tuning: analyzing `pg_stat_statements`, eliminating slow sequential scans via optimized composite indexes
  - `14.11.3` Connection pool optimization: tuning PgBouncer transaction pooling to handle 5,000 concurrent client connections smoothly
  - `14.11.4` Memory leak elimination: locating and resolving reference cycles and uncollected buffers in background worker processes
  - `14.11.5` Kernel network tuning: applying Linux `sysctl` socket buffer and connection queue optimizations on worker nodes
  - `14.11.6` Performance validation: proving that API p99 latency decreased by $\ge 40\%$ and memory consumption dropped by $\ge 25\%$
- **Key Failure Modes & Edge Cases**: Premature optimization of non-critical code paths without empirical flame graph evidence of performance impact.
- **Verification & Mastery Check**: Profile the production system under load; eliminate the top 2 bottlenecks and document verified before/after flame graphs.
- **Project Application**: Enterprise Capstone: Performance audit report and optimization patches.', '{"solution.py": "# Phase 14 // Lesson 14.11: Enterprise Capstone XI: Production Profiling & Performance Tuning\n\ndef solve():\n    \"\"\"\n    Verification: Profile the production system under load; eliminate the top 2 bottlenecks and document verified befo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.11", "subtopics_count": 6, "verification_criteria": "Profile the production system under load; eliminate the top 2 bottlenecks and document verified before/after flame graphs.", "subtopics": ["14.11.1 Profiling under load: identifying CPU and memory bottlenecks using `py-spy` and `memray` under sustained traffic", "14.11.2 Database query tuning: analyzing `pg_stat_statements`, eliminating slow sequential scans via optimized composite indexes", "14.11.3 Connection pool optimization: tuning PgBouncer transaction pooling to handle 5,000 concurrent client connections smoothly", "14.11.4 Memory leak elimination: locating and resolving reference cycles and uncollected buffers in background worker processes", "14.11.5 Kernel network tuning: applying Linux `sysctl` socket buffer and connection queue optimizations on worker nodes", "14.11.6 Performance validation: proving that API p99 latency decreased by $\\ge 40\\%$ and memory consumption dropped by $\\ge 25\\%$"]}'::jsonb, '["Explain how this implementation prevents: Premature optimization of non-critical code paths without empirical flame graph evidence of performance impact.", "How does Enterprise Capstone XI: Production Profiling & Performance Tuning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-12', 'phase-14-lesson-12-enterprise-capstone-xii-high-concurrency-', 'module-14', 32, 'Lesson 14.32: Enterprise Capstone XII: High-Concurrency Load Testing with k6', 'Prerequisites: Phase 11', 'Prerequisites: Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3500.0, 600.0, '# Lesson 14.12: Enterprise Capstone XII: High-Concurrency Load Testing with k6

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 11
- **Subtopics**:
  - `14.12.1` Designing realistic load testing scenarios: modeling peak traffic spikes, diurnal user patterns, and concurrent agent runs
  - `14.12.2` Writing modular k6 test scripts: simulating 10,000 concurrent Virtual Users (VUs) executing mixed read/write/streaming flows
  - `14.12.3` Executing distributed stress testing: running distributed k6 load generators generating 25,000 requests/second
  - `14.12.4` SLA verification under load: asserting that error rate remains $<0.01\%$ and p95 latency remains $<200$ms under peak load
  - `14.12.5` Identifying breaking points: pushing system load beyond capacity until throughput plateaus and graceful load shedding engages
  - `14.12.6` Authoring the Load Test Verification Report: documenting system capacity limits, bottleneck analysis, and scaling recommendations
- **Key Failure Modes & Edge Cases**: Conducting load tests with static identical data payloads, triggering unrealistic 100% cache hit rates on all requests.
- **Verification & Mastery Check**: Execute a 25,000 QPS distributed k6 load test; verify that system maintains all SLA latency thresholds without crashing.
- **Project Application**: Enterprise Capstone: Comprehensive load testing report and k6 test suite.', '{"solution.py": "# Phase 14 // Lesson 14.12: Enterprise Capstone XII: High-Concurrency Load Testing with k6\n\ndef solve():\n    \"\"\"\n    Verification: Execute a 25,000 QPS distributed k6 load test; verify that system maintains all SLA latency threshol\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.12", "subtopics_count": 6, "verification_criteria": "Execute a 25,000 QPS distributed k6 load test; verify that system maintains all SLA latency thresholds without crashing.", "subtopics": ["14.12.1 Designing realistic load testing scenarios: modeling peak traffic spikes, diurnal user patterns, and concurrent agent runs", "14.12.2 Writing modular k6 test scripts: simulating 10,000 concurrent Virtual Users (VUs) executing mixed read/write/streaming flows", "14.12.3 Executing distributed stress testing: running distributed k6 load generators generating 25,000 requests/second", "14.12.4 SLA verification under load: asserting that error rate remains $<0.01\\%$ and p95 latency remains $<200$ms under peak load", "14.12.5 Identifying breaking points: pushing system load beyond capacity until throughput plateaus and graceful load shedding engages", "14.12.6 Authoring the Load Test Verification Report: documenting system capacity limits, bottleneck analysis, and scaling recommendations"]}'::jsonb, '["Explain how this implementation prevents: Conducting load tests with static identical data payloads, triggering unrealistic 100% cache hit rates on all requests.", "How does Enterprise Capstone XII: High-Concurrency Load Testing with k6 scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-13', 'phase-14-lesson-13-enterprise-capstone-xiii-chaos-engineerin', 'module-14', 33, 'Lesson 14.33: Enterprise Capstone XIII: Chaos Engineering & Resilience Validation', 'Prerequisites: Phase 7, Phase 11', 'Prerequisites: Phase 7, Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3560.0, 650.0, '# Lesson 14.13: Enterprise Capstone XIII: Chaos Engineering & Resilience Validation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Phase 11
- **Subtopics**:
  - `14.13.1` Validating system self-healing: testing whether the system survives component failures under active production load
  - `14.13.2` LitmusChaos experiment execution: terminating primary database pods, injecting 30% packet loss, killing Kubernetes worker nodes
  - `14.13.3` Verifying fault tolerance: testing automated database failover, Kafka consumer rebalancing, and circuit breaker trip mechanics
  - `14.13.4` Evaluating user impact during chaos: proving that customer API requests experience zero data loss and $<0.5\%$ transient errors
  - `14.13.5` Disaster recovery drill: executing an automated cluster restoration drill from Velero backups into a secondary cloud region
  - `14.13.6` Resilience certification: compiling the Chaos Verification Report proving compliance with five-nines availability principles
- **Key Failure Modes & Edge Cases**: Failing to automate chaos experiments, leaving critical failover procedures untested until an actual production outage strikes.
- **Verification & Mastery Check**: Execute a multi-fault LitmusChaos experiment during active load testing; prove zero data corruption and automated recovery under 60s.
- **Project Application**: Enterprise Capstone: Chaos engineering verification report.', '{"solution.py": "# Phase 14 // Lesson 14.13: Enterprise Capstone XIII: Chaos Engineering & Resilience Validation\n\ndef solve():\n    \"\"\"\n    Verification: Execute a multi-fault LitmusChaos experiment during active load testing; prove zero data corruption \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.13", "subtopics_count": 6, "verification_criteria": "Execute a multi-fault LitmusChaos experiment during active load testing; prove zero data corruption and automated recovery under 60s.", "subtopics": ["14.13.1 Validating system self-healing: testing whether the system survives component failures under active production load", "14.13.2 LitmusChaos experiment execution: terminating primary database pods, injecting 30% packet loss, killing Kubernetes worker nodes", "14.13.3 Verifying fault tolerance: testing automated database failover, Kafka consumer rebalancing, and circuit breaker trip mechanics", "14.13.4 Evaluating user impact during chaos: proving that customer API requests experience zero data loss and $<0.5\\%$ transient errors", "14.13.5 Disaster recovery drill: executing an automated cluster restoration drill from Velero backups into a secondary cloud region", "14.13.6 Resilience certification: compiling the Chaos Verification Report proving compliance with five-nines availability principles"]}'::jsonb, '["Explain how this implementation prevents: Failing to automate chaos experiments, leaving critical failover procedures untested until an actual production outage s", "How does Enterprise Capstone XIII: Chaos Engineering & Resilience Validation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-14', 'phase-14-lesson-14-enterprise-capstone-xiv-security-audit-pe', 'module-14', 34, 'Lesson 14.34: Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance', 'Prerequisites: Phase 5, Phase 10, Phase 13', 'Prerequisites: Phase 5, Phase 10, Phase 13 | Subtopics: 6 items', 'Systems project application', 380, 15, 3620.0, 700.0, '# Lesson 14.14: Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Phase 10, Phase 13
- **Subtopics**:
  - `14.14.1` Executing a comprehensive pre-launch security audit: scanning all codebases with Semgrep SAST and containers with Trivy
  - `14.14.2` Penetration testing: conducting authenticated and unauthenticated penetration attacks against web APIs and agent sandboxes
  - `14.14.3` Prompt injection red-teaming: testing 20 direct and indirect prompt injection attacks against the autonomous agent pipelines
  - `14.14.4` PII and data privacy audit: verifying Microsoft Presidio PII redaction and testing GDPR data deletion workflows
  - `14.14.5` Zero-Trust verification: inspecting mTLS certificate rotation and Kubernetes network policy default-deny enforcement
  - `14.14.6` Compiling the Security & Compliance Dossier: documenting threat mitigations, SOC2 Type II controls, and vulnerability remediation
- **Key Failure Modes & Edge Cases**: Launching an enterprise platform with open container egress or un-redacted user PII in distributed application logs.
- **Verification & Mastery Check**: Pass the automated security and penetration audit with 0 critical or high vulnerabilities; verify 100% prompt injection containment.
- **Project Application**: Enterprise Capstone: Security audit dossier and penetration test report.', '{"solution.py": "# Phase 14 // Lesson 14.14: Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance\n\ndef solve():\n    \"\"\"\n    Verification: Pass the automated security and penetration audit with 0 critical or high vulnerabilities; verify 10\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.14", "subtopics_count": 6, "verification_criteria": "Pass the automated security and penetration audit with 0 critical or high vulnerabilities; verify 100% prompt injection containment.", "subtopics": ["14.14.1 Executing a comprehensive pre-launch security audit: scanning all codebases with Semgrep SAST and containers with Trivy", "14.14.2 Penetration testing: conducting authenticated and unauthenticated penetration attacks against web APIs and agent sandboxes", "14.14.3 Prompt injection red-teaming: testing 20 direct and indirect prompt injection attacks against the autonomous agent pipelines", "14.14.4 PII and data privacy audit: verifying Microsoft Presidio PII redaction and testing GDPR data deletion workflows", "14.14.5 Zero-Trust verification: inspecting mTLS certificate rotation and Kubernetes network policy default-deny enforcement", "14.14.6 Compiling the Security & Compliance Dossier: documenting threat mitigations, SOC2 Type II controls, and vulnerability remediation"]}'::jsonb, '["Explain how this implementation prevents: Launching an enterprise platform with open container egress or un-redacted user PII in distributed application logs.", "How does Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-15', 'phase-14-lesson-15-enterprise-capstone-xv-production-runbook', 'module-14', 35, 'Lesson 14.35: Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense', 'Prerequisites: Phase 8, Phase 11', 'Prerequisites: Phase 8, Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3500.0, 750.0, '# Lesson 14.15: Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 8, Phase 11
- **Subtopics**:
  - `14.15.1` Authoring Production Runbooks: step-by-step diagnostic workflows for alert triage, database failbacks, and incident escalation
  - `14.15.2` Service Level Agreement (SLA) contract defense: presenting documented error budget policies and disaster recovery runbooks
  - `14.15.3` Disaster Recovery (DR) sign-off: proving Recovery Point Objective (RPO) $< 1\text{ minute}$ and Recovery Time Objective (RTO) $< 15\text{ minutes}$
  - `14.15.4` The Production Engineering Live Defense: delivering a 60-minute technical architectural presentation to senior engineering staff
  - `14.15.5` Defending architectural trade-offs: answering rigorous interrogation on consistency models, scaling bottlenecks, and cost trade-offs
  - `14.15.6` Final project certification: signing off on code quality, test coverage, deployment automation, and production readiness
- **Key Failure Modes & Edge Cases**: Inability to explain why an architectural decision was chosen over alternatives when questioned by senior engineering leadership.
- **Verification & Mastery Check**: Successfully defend the entire Enterprise Capstone architecture in a 60-minute live presentation, answering all technical challenges.
- **Project Application**: Enterprise Capstone: Production Runbooks, DR Plan, and Capstone Sign-off.', '{"solution.py": "# Phase 14 // Lesson 14.15: Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense\n\ndef solve():\n    \"\"\"\n    Verification: Successfully defend the entire Enterprise Capstone architecture in a 60-minute live presentation, an\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.15", "subtopics_count": 6, "verification_criteria": "Successfully defend the entire Enterprise Capstone architecture in a 60-minute live presentation, answering all technical challenges.", "subtopics": ["14.15.1 Authoring Production Runbooks: step-by-step diagnostic workflows for alert triage, database failbacks, and incident escalation", "14.15.2 Service Level Agreement (SLA) contract defense: presenting documented error budget policies and disaster recovery runbooks", "14.15.3 Disaster Recovery (DR) sign-off: proving Recovery Point Objective (RPO) $< 1\\text{ minute}$ and Recovery Time Objective (RTO) $< 15\\text{ minutes}$", "14.15.4 The Production Engineering Live Defense: delivering a 60-minute technical architectural presentation to senior engineering staff", "14.15.5 Defending architectural trade-offs: answering rigorous interrogation on consistency models, scaling bottlenecks, and cost trade-offs", "14.15.6 Final project certification: signing off on code quality, test coverage, deployment automation, and production readiness"]}'::jsonb, '["Explain how this implementation prevents: Inability to explain why an architectural decision was chosen over alternatives when questioned by senior engineering le", "How does Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
