INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-2-21', 'phase-02-lesson-21-mean-median-mode-central-tendency', 'module-3', 21, 'Lesson 3.21: Mean, Median & Mode: Central Tendency', 'Prerequisites: Lesson 2.19', 'Prerequisites: Lesson 2.19 | Subtopics: 5 items', 'Systems project application', 140, 3, 500.0, 1050.0, '# Lesson 2.21: Mean, Median & Mode: Central Tendency

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.19
- **Subtopics**:
  - `2.21.1` Summarizing datasets: finding the center of a group of numbers.
  - `2.21.2` The Mean (average): summing all values and dividing by total count.
  - `2.21.3` The Median: the physical middle value when numbers are sorted in order.
  - `2.21.4` The Mode: the most frequently occurring value in the dataset.
  - `2.21.5` Handling outliers: why median is far more reliable than mean when measuring response latency.
- **Key Failure Modes & Edge Cases**: Relying solely on the average latency of an API, hiding the fact that 5% of users experience 10-second lag.
- **Verification & Mastery Check**: Write a function that calculates mean, median, and 95th percentile latency from a list of request times.
- **Project Application**: VectorCore: Latency summary statistics.', '{"solution.py": "# Phase 2 // Lesson 2.21: Mean, Median & Mode: Central Tendency\n\ndef solve():\n    \"\"\"\n    Verification: Write a function that calculates mean, median, and 95th percentile latency from a list of request ti\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.21", "subtopics_count": 5, "verification_criteria": "Write a function that calculates mean, median, and 95th percentile latency from a list of request times.", "subtopics": ["2.21.1 Summarizing datasets: finding the center of a group of numbers.", "2.21.2 The Mean (average): summing all values and dividing by total count.", "2.21.3 The Median: the physical middle value when numbers are sorted in order.", "2.21.4 The Mode: the most frequently occurring value in the dataset.", "2.21.5 Handling outliers: why median is far more reliable than mean when measuring response latency."]}'::jsonb, '["Explain how this implementation prevents: Relying solely on the average latency of an API, hiding the fact that 5% of users experience 10-second lag.", "How does Mean, Median & Mode: Central Tendency scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-22', 'phase-02-lesson-22-variance-standard-deviation-spread-of-dat', 'module-3', 22, 'Lesson 3.22: Variance & Standard Deviation: Spread of Data', 'Prerequisites: Lesson 2.21', 'Prerequisites: Lesson 2.21 | Subtopics: 4 items', 'Systems project application', 140, 3, 560.0, 1100.0, '# Lesson 2.22: Variance & Standard Deviation: Spread of Data

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.21
- **Subtopics**:
  - `2.22.1` Measuring spread: how dispersed numbers are around their average.
  - `2.22.2` Variance: the average squared difference from the mean.
  - `2.22.3` Standard deviation: the square root of variance, returning the spread back to original units.
  - `2.22.4` Consistent systems: why low standard deviation is the hallmark of reliable software systems.
- **Key Failure Modes & Edge Cases**: Forgetting to take the square root of variance, confusing squared units with actual data units.
- **Verification & Mastery Check**: Implement variance and standard deviation from scratch in pure Python without using math libraries.
- **Project Application**: VectorCore: Distribution dispersion metrics.', '{"solution.py": "# Phase 2 // Lesson 2.22: Variance & Standard Deviation: Spread of Data\n\ndef solve():\n    \"\"\"\n    Verification: Implement variance and standard deviation from scratch in pure Python without using math libraries.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.22", "subtopics_count": 4, "verification_criteria": "Implement variance and standard deviation from scratch in pure Python without using math libraries.", "subtopics": ["2.22.1 Measuring spread: how dispersed numbers are around their average.", "2.22.2 Variance: the average squared difference from the mean.", "2.22.3 Standard deviation: the square root of variance, returning the spread back to original units.", "2.22.4 Consistent systems: why low standard deviation is the hallmark of reliable software systems."]}'::jsonb, '["Explain how this implementation prevents: Forgetting to take the square root of variance, confusing squared units with actual data units.", "How does Variance & Standard Deviation: Spread of Data scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-23', 'phase-02-lesson-23-normal-gaussian-distribution-the-bell-cur', 'module-3', 23, 'Lesson 3.23: Normal Gaussian Distribution: The Bell Curve', 'Prerequisites: Lesson 2.22', 'Prerequisites: Lesson 2.22 | Subtopics: 4 items', 'Systems project application', 140, 3, 620.0, 1150.0, '# Lesson 2.23: Normal Gaussian Distribution: The Bell Curve

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.22
- **Subtopics**:
  - `2.23.1` The classic bell curve: why natural processes and measurement errors cluster around the center.
  - `2.23.2` Mean (center) and Standard Deviation (width) as the two parameters defining the entire curve.
  - `2.23.3` The 68-95-99.7 empirical rule: what percentage of data falls within 1, 2, and 3 standard deviations.
  - `2.23.4` Standardizing scores (Z-scores): converting arbitrary numbers into distance from the mean.
- **Key Failure Modes & Edge Cases**: Assuming all software metrics follow normal curves, when server traffic and response times are heavily skewed.
- **Verification & Mastery Check**: Generate 1,000 normal random samples in Python and verify that ~68% fall within 1 standard deviation.
- **Project Application**: VectorCore: Statistical distributions.', '{"solution.py": "# Phase 2 // Lesson 2.23: Normal Gaussian Distribution: The Bell Curve\n\ndef solve():\n    \"\"\"\n    Verification: Generate 1,000 normal random samples in Python and verify that ~68% fall within 1 standard deviation\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.23", "subtopics_count": 4, "verification_criteria": "Generate 1,000 normal random samples in Python and verify that ~68% fall within 1 standard deviation.", "subtopics": ["2.23.1 The classic bell curve: why natural processes and measurement errors cluster around the center.", "2.23.2 Mean (center) and Standard Deviation (width) as the two parameters defining the entire curve.", "2.23.3 The 68-95-99.7 empirical rule: what percentage of data falls within 1, 2, and 3 standard deviations.", "2.23.4 Standardizing scores (Z-scores): converting arbitrary numbers into distance from the mean."]}'::jsonb, '["Explain how this implementation prevents: Assuming all software metrics follow normal curves, when server traffic and response times are heavily skewed.", "How does Normal Gaussian Distribution: The Bell Curve scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-24', 'phase-02-lesson-24-softmax-function-numbers-to-probabilities', 'module-3', 24, 'Lesson 3.24: Softmax Function: Numbers to Probabilities', 'Prerequisites: Lesson 2.3, Lesson 2.20', 'Prerequisites: Lesson 2.3, Lesson 2.20 | Subtopics: 4 items', 'Systems project application', 140, 3, 500.0, 1200.0, '# Lesson 2.24: Softmax Function: Numbers to Probabilities

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.3, Lesson 2.20
- **Subtopics**:
  - `2.24.1` The challenge of raw model outputs (logits): unconstrained positive and negative real numbers.
  - `2.24.2` The Softmax formula: exponentiating numbers to make them strictly positive, then dividing by their sum.
  - `2.24.3` Two magical properties: all outputs are between 0 and 1, and the entire output array sums to exactly 1.0.
  - `2.24.4` The temperature parameter: controlling whether probabilities are sharp (confident) or smooth (creative).
- **Key Failure Modes & Edge Cases**: Numerical overflow: exponentiating large numbers like e^1000 causing float overflow to infinity.
- **Verification & Mastery Check**: Implement a numerically stable softmax function that subtracts the maximum logit before exponentiating.
- **Project Application**: VectorCore: Logit-to-probability converter.', '{"solution.py": "# Phase 2 // Lesson 2.24: Softmax Function: Numbers to Probabilities\n\ndef solve():\n    \"\"\"\n    Verification: Implement a numerically stable softmax function that subtracts the maximum logit before exponentiati\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.24", "subtopics_count": 4, "verification_criteria": "Implement a numerically stable softmax function that subtracts the maximum logit before exponentiating.", "subtopics": ["2.24.1 The challenge of raw model outputs (logits): unconstrained positive and negative real numbers.", "2.24.2 The Softmax formula: exponentiating numbers to make them strictly positive, then dividing by their sum.", "2.24.3 Two magical properties: all outputs are between 0 and 1, and the entire output array sums to exactly 1.0.", "2.24.4 The temperature parameter: controlling whether probabilities are sharp (confident) or smooth (creative)."]}'::jsonb, '["Explain how this implementation prevents: Numerical overflow: exponentiating large numbers like e^1000 causing float overflow to infinity.", "How does Softmax Function: Numbers to Probabilities scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-25', 'phase-02-lesson-25-cross-entropy-loss-measuring-prediction-e', 'module-3', 25, 'Lesson 3.25: Cross-Entropy Loss: Measuring Prediction Error', 'Prerequisites: Lesson 2.24', 'Prerequisites: Lesson 2.24 | Subtopics: 4 items', 'Systems project application', 140, 3, 560.0, 1250.0, '# Lesson 2.25: Cross-Entropy Loss: Measuring Prediction Error

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.24
- **Subtopics**:
  - `2.25.1` Loss functions: mathematical scorecards that tell an AI model how wrong its predictions were.
  - `2.25.2` Cross-entropy loss: comparing the predicted probability distribution against the true target label.
  - `2.25.3` The negative log penalty: heavily penalizing models that are confidently wrong.
  - `2.25.4` Why cross-entropy guides neural networks to learn faster and more accurately than squared error.
- **Key Failure Modes & Edge Cases**: Computing log(0.0) when a predicted probability is 0, which crashes with a math domain error.
- **Verification & Mastery Check**: Calculate cross-entropy loss for two scenarios: a confident correct guess vs a confident incorrect guess.
- **Project Application**: VectorCore: Classification loss calculation.', '{"solution.py": "# Phase 2 // Lesson 2.25: Cross-Entropy Loss: Measuring Prediction Error\n\ndef solve():\n    \"\"\"\n    Verification: Calculate cross-entropy loss for two scenarios: a confident correct guess vs a confident incorrect g\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.25", "subtopics_count": 4, "verification_criteria": "Calculate cross-entropy loss for two scenarios: a confident correct guess vs a confident incorrect guess.", "subtopics": ["2.25.1 Loss functions: mathematical scorecards that tell an AI model how wrong its predictions were.", "2.25.2 Cross-entropy loss: comparing the predicted probability distribution against the true target label.", "2.25.3 The negative log penalty: heavily penalizing models that are confidently wrong.", "2.25.4 Why cross-entropy guides neural networks to learn faster and more accurately than squared error."]}'::jsonb, '["Explain how this implementation prevents: Computing log(0.0) when a predicted probability is 0, which crashes with a math domain error.", "How does Cross-Entropy Loss: Measuring Prediction Error scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-26', 'phase-02-lesson-26-propositional-logic-truth-tables-logical-', 'module-3', 26, 'Lesson 3.26: Propositional Logic, Truth Tables, & Logical Equivalences', 'Prerequisites: Phase 1', 'Prerequisites: Phase 1 | Subtopics: 4 items', 'Systems project application', 140, 3, 620.0, 1300.0, '# Lesson 2.26: Propositional Logic, Truth Tables, & Logical Equivalences

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1
- **Subtopics**:
  - `2.26.1` Atomic propositions, logical connectives: AND, OR, NOT, Implication ($P \implies Q$), Biconditional ($P \iff Q$).
  - `2.26.2` Truth tables and semantic verification of tautologies, contradictions, and contingencies.
  - `2.26.3` De Morgan''s Laws for logic: $
eg(P \land Q) \iff 
eg P \lor 
eg Q$; equivalence to set complements.
  - `2.26.4` Boolean algebra in systems: simplifying nested conditional code branches algebraically.
- **Key Failure Modes & Edge Cases**: Writing nested if-else branches that evaluate to tautologies or unreachable dead-code blocks.
- **Verification & Mastery Check**: Simplify an ugly 5-level nested conditional statement using boolean algebra and verify equivalence via truth table.
- **Project Application**: DevAudit: AST conditional simplification rule.', '{"solution.py": "# Phase 2 // Lesson 2.26: Propositional Logic, Truth Tables, & Logical Equivalences\n\ndef solve():\n    \"\"\"\n    Verification: Simplify an ugly 5-level nested conditional statement using boolean algebra and verify equivalence v\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.26", "subtopics_count": 4, "verification_criteria": "Simplify an ugly 5-level nested conditional statement using boolean algebra and verify equivalence via truth table.", "subtopics": ["2.26.1 Atomic propositions, logical connectives: AND, OR, NOT, Implication ($P \\implies Q$), Biconditional ($P \\iff Q$).", "2.26.2 Truth tables and semantic verification of tautologies, contradictions, and contingencies.", "2.26.3 De Morgan''s Laws for logic: $", "2.26.4 Boolean algebra in systems: simplifying nested conditional code branches algebraically."]}'::jsonb, '["Explain how this implementation prevents: Writing nested if-else branches that evaluate to tautologies or unreachable dead-code blocks.", "How does Propositional Logic, Truth Tables, & Logical Equivalences scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-27', 'phase-02-lesson-27-predicate-logic-quantifiers-logical-negat', 'module-3', 27, 'Lesson 3.27: Predicate Logic, Quantifiers, & Logical Negation', 'Prerequisites: Lesson 2.26', 'Prerequisites: Lesson 2.26 | Subtopics: 4 items', 'Systems project application', 140, 3, 500.0, 1350.0, '# Lesson 2.27: Predicate Logic, Quantifiers, & Logical Negation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.26
- **Subtopics**:
  - `2.27.1` Predicates as parameterized truth functions: $P(x)$ mapping domain elements to booleans.
  - `2.27.2` Universal ($orall$) and Existential ($\exists$) quantifiers: semantics over finite and infinite domains.
  - `2.27.3` Negating quantified statements: $
eg(orall x, P(x)) \iff \exists x, 
eg P(x)$; domain edge cases.
  - `2.27.4` Nested quantifiers: order of quantification ($orall x \exists y$ vs $\exists y orall x$) and mathematical meaning.
- **Key Failure Modes & Edge Cases**: Failing to recognize that negating ''all users are active'' is ''at least one user is inactive'' (not ''all users are inactive'').
- **Verification & Mastery Check**: Translate a natural language business specification with nested quantifiers into formal predicate logic.
- **Project Application**: DevAudit: Static invariant validation.', '{"solution.py": "# Phase 2 // Lesson 2.27: Predicate Logic, Quantifiers, & Logical Negation\n\ndef solve():\n    \"\"\"\n    Verification: Translate a natural language business specification with nested quantifiers into formal predicate lo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.27", "subtopics_count": 4, "verification_criteria": "Translate a natural language business specification with nested quantifiers into formal predicate logic.", "subtopics": ["2.27.1 Predicates as parameterized truth functions: $P(x)$ mapping domain elements to booleans.", "2.27.2 Universal ($\forall$) and Existential ($\\exists$) quantifiers: semantics over finite and infinite domains.", "2.27.3 Negating quantified statements: $", "2.27.4 Nested quantifiers: order of quantification ($\forall x \\exists y$ vs $\\exists y \forall x$) and mathematical meaning."]}'::jsonb, '["Explain how this implementation prevents: Failing to recognize that negating ''all users are active'' is ''at least one user is inactive'' (not ''all users are inactiv", "How does Predicate Logic, Quantifiers, & Logical Negation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-28', 'phase-02-lesson-28-direct-proofs-contrapositive-proof-by-con', 'module-3', 28, 'Lesson 3.28: Direct Proofs, Contrapositive, & Proof by Contradiction', 'Prerequisites: Lesson 2.26', 'Prerequisites: Lesson 2.26 | Subtopics: 4 items', 'Systems project application', 140, 3, 560.0, 1400.0, '# Lesson 2.28: Direct Proofs, Contrapositive, & Proof by Contradiction

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.26
- **Subtopics**:
  - `2.28.1` The architecture of formal mathematical proofs: axioms, definitions, hypotheses, and conclusions.
  - `2.28.2` Direct proof methodology: assuming hypothesis $P$ and deriving conclusion $Q$ through logical deduction.
  - `2.28.3` Proof by Contraposition: proving $P \implies Q$ by proving $
eg Q \implies 
eg P$.
  - `2.28.4` Proof by Contradiction (Reductio ad Absurdum): assuming $
eg P$ and deriving an impossible contradiction ($R \land 
eg R$).
- **Key Failure Modes & Edge Cases**: Assuming that a property holding true for 100 test cases constitutes a mathematical proof.
- **Verification & Mastery Check**: Prove formally that if $3n+2$ is odd, then $n$ is odd, using proof by contraposition.
- **Project Application**: MathKit: Algorithm verification proofs.', '{"solution.py": "# Phase 2 // Lesson 2.28: Direct Proofs, Contrapositive, & Proof by Contradiction\n\ndef solve():\n    \"\"\"\n    Verification: Prove formally that if $3n+2$ is odd, then $n$ is odd, using proof by contraposition.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.28", "subtopics_count": 4, "verification_criteria": "Prove formally that if $3n+2$ is odd, then $n$ is odd, using proof by contraposition.", "subtopics": ["2.28.1 The architecture of formal mathematical proofs: axioms, definitions, hypotheses, and conclusions.", "2.28.2 Direct proof methodology: assuming hypothesis $P$ and deriving conclusion $Q$ through logical deduction.", "2.28.3 Proof by Contraposition: proving $P \\implies Q$ by proving $", "2.28.4 Proof by Contradiction (Reductio ad Absurdum): assuming $"]}'::jsonb, '["Explain how this implementation prevents: Assuming that a property holding true for 100 test cases constitutes a mathematical proof.", "How does Direct Proofs, Contrapositive, & Proof by Contradiction scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-29', 'phase-02-lesson-29-mathematical-induction-loop-invariants', 'module-3', 29, 'Lesson 3.29: Mathematical Induction & Loop Invariants', 'Prerequisites: Lesson 2.28', 'Prerequisites: Lesson 2.28 | Subtopics: 4 items', 'Systems project application', 140, 3, 620.0, 1450.0, '# Lesson 2.29: Mathematical Induction & Loop Invariants

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.28
- **Subtopics**:
  - `2.29.1` Principle of Mathematical Induction: Base Case $P(0)$ and Inductive Step $P(k) \implies P(k+1)$.
  - `2.29.2` Strong Induction: assuming all preceding cases $P(0), \dots, P(k)$ hold to prove $P(k+1)$.
  - `2.29.3` Loop Invariants in software engineering: Initialization, Maintenance, and Termination guarantees.
  - `2.29.4` Proving algorithm correctness: proving binary search and sorting termination via invariants.
- **Key Failure Modes & Edge Cases**: Writing recursive functions with subtle termination bugs where the base case fails to cover all branches.
- **Verification & Mastery Check**: Prove formally using loop invariants that binary search terminates with the correct index in $O(\log n)$ steps.
- **Project Application**: Foundation for Phase 3 algorithm correctness.', '{"solution.py": "# Phase 2 // Lesson 2.29: Mathematical Induction & Loop Invariants\n\ndef solve():\n    \"\"\"\n    Verification: Prove formally using loop invariants that binary search terminates with the correct index in $O(\\log\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.29", "subtopics_count": 4, "verification_criteria": "Prove formally using loop invariants that binary search terminates with the correct index in $O(\\log n)$ steps.", "subtopics": ["2.29.1 Principle of Mathematical Induction: Base Case $P(0)$ and Inductive Step $P(k) \\implies P(k+1)$.", "2.29.2 Strong Induction: assuming all preceding cases $P(0), \\dots, P(k)$ hold to prove $P(k+1)$.", "2.29.3 Loop Invariants in software engineering: Initialization, Maintenance, and Termination guarantees.", "2.29.4 Proving algorithm correctness: proving binary search and sorting termination via invariants."]}'::jsonb, '["Explain how this implementation prevents: Writing recursive functions with subtle termination bugs where the base case fails to cover all branches.", "How does Mathematical Induction & Loop Invariants scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-30', 'phase-02-lesson-30-set-theory-relations-equivalence-classes', 'module-3', 30, 'Lesson 3.30: Set Theory, Relations, & Equivalence Classes', 'Prerequisites: Lesson 2.26', 'Prerequisites: Lesson 2.26 | Subtopics: 4 items', 'Systems project application', 140, 3, 500.0, 1500.0, '# Lesson 2.30: Set Theory, Relations, & Equivalence Classes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.26
- **Subtopics**:
  - `2.30.1` Sets, subsets, power sets, set operations (union, intersection, difference, Cartesian product).
  - `2.30.2` Binary relations: reflexive, symmetric, anti-symmetric, and transitive properties.
  - `2.30.3` Equivalence relations and partitioning sets into disjoint equivalence classes.
  - `2.30.4` Partial orders, total orders, and Hasse diagrams: prerequisite structures.
- **Key Failure Modes & Edge Cases**: Assuming a comparison function defines a total order when it violates transitivity, causing sorting algorithms to loop infinitely.
- **Verification & Mastery Check**: Prove whether a given custom object comparator satisfies total ordering axioms.
- **Project Application**: DataSift: Entity resolution and clustering.', '{"solution.py": "# Phase 2 // Lesson 2.30: Set Theory, Relations, & Equivalence Classes\n\ndef solve():\n    \"\"\"\n    Verification: Prove whether a given custom object comparator satisfies total ordering axioms.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.30", "subtopics_count": 4, "verification_criteria": "Prove whether a given custom object comparator satisfies total ordering axioms.", "subtopics": ["2.30.1 Sets, subsets, power sets, set operations (union, intersection, difference, Cartesian product).", "2.30.2 Binary relations: reflexive, symmetric, anti-symmetric, and transitive properties.", "2.30.3 Equivalence relations and partitioning sets into disjoint equivalence classes.", "2.30.4 Partial orders, total orders, and Hasse diagrams: prerequisite structures."]}'::jsonb, '["Explain how this implementation prevents: Assuming a comparison function defines a total order when it violates transitivity, causing sorting algorithms to loop i", "How does Set Theory, Relations, & Equivalence Classes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-31', 'phase-02-lesson-31-functions-injections-surjections-bijectio', 'module-3', 31, 'Lesson 3.31: Functions: Injections, Surjections, & Bijections', 'Prerequisites: Lesson 2.30', 'Prerequisites: Lesson 2.30 | Subtopics: 4 items', 'Systems project application', 140, 3, 560.0, 1550.0, '# Lesson 2.31: Functions: Injections, Surjections, & Bijections

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.30
- **Subtopics**:
  - `2.31.1` Domain, codomain, and range (image) of mathematical mappings.
  - `2.31.2` Injective (one-to-one) functions: uniqueness of outputs ($f(a) = f(b) \implies a = b$).
  - `2.31.3` Surjective (onto) functions: every element of codomain is mapped.
  - `2.31.4` Bijective functions: one-to-one correspondences, invertibility, and applications in cryptography and data encoding.
- **Key Failure Modes & Edge Cases**: Assuming a hash function is invertible or collision-free without verifying bijective properties.
- **Verification & Mastery Check**: Prove that Base62 encoding is a bijection between non-negative integers and alphanumeric strings.
- **Project Application**: Phase 8: URL shortener encoding.', '{"solution.py": "# Phase 2 // Lesson 2.31: Functions: Injections, Surjections, & Bijections\n\ndef solve():\n    \"\"\"\n    Verification: Prove that Base62 encoding is a bijection between non-negative integers and alphanumeric strings.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.31", "subtopics_count": 4, "verification_criteria": "Prove that Base62 encoding is a bijection between non-negative integers and alphanumeric strings.", "subtopics": ["2.31.1 Domain, codomain, and range (image) of mathematical mappings.", "2.31.2 Injective (one-to-one) functions: uniqueness of outputs ($f(a) = f(b) \\implies a = b$).", "2.31.3 Surjective (onto) functions: every element of codomain is mapped.", "2.31.4 Bijective functions: one-to-one correspondences, invertibility, and applications in cryptography and data encoding."]}'::jsonb, '["Explain how this implementation prevents: Assuming a hash function is invertible or collision-free without verifying bijective properties.", "How does Functions: Injections, Surjections, & Bijections scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-32', 'phase-02-lesson-32-combinatorics-permutations-combinations-p', 'module-3', 32, 'Lesson 3.32: Combinatorics: Permutations, Combinations, & Pigeonhole', 'Prerequisites: Lesson 2.30', 'Prerequisites: Lesson 2.30 | Subtopics: 4 items', 'Systems project application', 140, 3, 620.0, 1600.0, '# Lesson 2.32: Combinatorics: Permutations, Combinations, & Pigeonhole

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.30
- **Subtopics**:
  - `2.32.1` The Multiplication Principle and Addition Principle of counting.
  - `2.32.2` Permutations: ordered selections with and without repetition ($n! / (n-k)!$).
  - `2.32.3` Combinations: unordered selections ($nCr = rac{n!}{k!(n-k)!}$); Pascal''s triangle identity.
  - `2.32.4` The Pigeonhole Principle: if $n+1$ items occupy $n$ containers, at least one container holds $\ge 2$ items; hash collision inevitability.
- **Key Failure Modes & Edge Cases**: Combinatorial explosion: underestimating search spaces in brute-force algorithms ($O(n!)$ vs $O(2^n)$).
- **Verification & Mastery Check**: Calculate the exact collision probability threshold for a 32-bit hash function using the Pigeonhole Principle.
- **Project Application**: Phase 3: Backtracking search spaces.', '{"solution.py": "# Phase 2 // Lesson 2.32: Combinatorics: Permutations, Combinations, & Pigeonhole\n\ndef solve():\n    \"\"\"\n    Verification: Calculate the exact collision probability threshold for a 32-bit hash function using the Pigeonhole \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.32", "subtopics_count": 4, "verification_criteria": "Calculate the exact collision probability threshold for a 32-bit hash function using the Pigeonhole Principle.", "subtopics": ["2.32.1 The Multiplication Principle and Addition Principle of counting.", "2.32.2 Permutations: ordered selections with and without repetition ($n! / (n-k)!$).", "2.32.3 Combinations: unordered selections ($nCr = \frac{n!}{k!(n-k)!}$); Pascal''s triangle identity.", "2.32.4 The Pigeonhole Principle: if $n+1$ items occupy $n$ containers, at least one container holds $\\ge 2$ items; hash collision inevitability."]}'::jsonb, '["Explain how this implementation prevents: Combinatorial explosion: underestimating search spaces in brute-force algorithms ($O(n!)$ vs $O(2^n)$).", "How does Combinatorics: Permutations, Combinations, & Pigeonhole scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-33', 'phase-02-lesson-33-graph-theory-definitions-topologies-isomo', 'module-3', 33, 'Lesson 3.33: Graph Theory: Definitions, Topologies, & Isomorphisms', 'Prerequisites: Lesson 2.30', 'Prerequisites: Lesson 2.30 | Subtopics: 4 items', 'Systems project application', 140, 3, 500.0, 1650.0, '# Lesson 2.33: Graph Theory: Definitions, Topologies, & Isomorphisms

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.30
- **Subtopics**:
  - `2.33.1` Graph components: vertices ($V$), edges ($E$), directed vs undirected, weighted vs unweighted.
  - `2.33.2` Vertex degrees, in-degree, out-degree, and the Handshaking Lemma ($\sum \deg(v) = 2|E|$).
  - `2.33.3` Paths, cycles, connectivity, bipartite graphs, and tree definitions (connected acyclic graph with $|V|-1$ edges).
  - `2.33.4` Graph Isomorphism: determining structural equivalence between graph representations.
- **Key Failure Modes & Edge Cases**: Failing to check for cycles in directed graphs, causing infinite loops in dependency resolution engines.
- **Verification & Mastery Check**: Prove that an undirected graph with $V$ vertices and $V-1$ edges is a tree if and only if it is acyclic.
- **Project Application**: MathKit: `mathkit.graph` module.', '{"solution.py": "# Phase 2 // Lesson 2.33: Graph Theory: Definitions, Topologies, & Isomorphisms\n\ndef solve():\n    \"\"\"\n    Verification: Prove that an undirected graph with $V$ vertices and $V-1$ edges is a tree if and only if it is acyc\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.33", "subtopics_count": 4, "verification_criteria": "Prove that an undirected graph with $V$ vertices and $V-1$ edges is a tree if and only if it is acyclic.", "subtopics": ["2.33.1 Graph components: vertices ($V$), edges ($E$), directed vs undirected, weighted vs unweighted.", "2.33.2 Vertex degrees, in-degree, out-degree, and the Handshaking Lemma ($\\sum \\deg(v) = 2|E|$).", "2.33.3 Paths, cycles, connectivity, bipartite graphs, and tree definitions (connected acyclic graph with $|V|-1$ edges).", "2.33.4 Graph Isomorphism: determining structural equivalence between graph representations."]}'::jsonb, '["Explain how this implementation prevents: Failing to check for cycles in directed graphs, causing infinite loops in dependency resolution engines.", "How does Graph Theory: Definitions, Topologies, & Isomorphisms scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-34', 'phase-02-lesson-34-directed-acyclic-graphs-dags-topological-', 'module-3', 34, 'Lesson 3.34: Directed Acyclic Graphs (DAGs) & Topological Properties', 'Prerequisites: Lesson 2.33', 'Prerequisites: Lesson 2.33 | Subtopics: 4 items', 'Systems project application', 140, 3, 560.0, 1700.0, '# Lesson 2.34: Directed Acyclic Graphs (DAGs) & Topological Properties

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.33
- **Subtopics**:
  - `2.34.1` DAG properties: directed edges with zero directed cycles.
  - `2.34.2` Sources and Sinks in DAGs; reachability analysis and transitive reduction.
  - `2.34.3` Topological Ordering: linear ordering of vertices where every directed edge $(u, v)$ has $u$ before $v$.
  - `2.34.4` Why DAGs underpin computational workflows: task scheduling, build systems, neural network backpropagation.
- **Key Failure Modes & Edge Cases**: Circular dependency deadlocks in software build systems and package managers.
- **Verification & Mastery Check**: Implement a mathematical cycle detector that outputs the exact cycle path if a graph fails to be a DAG.
- **Project Application**: GradFlow: Computational graph evaluation in Phase 9.', '{"solution.py": "# Phase 2 // Lesson 2.34: Directed Acyclic Graphs (DAGs) & Topological Properties\n\ndef solve():\n    \"\"\"\n    Verification: Implement a mathematical cycle detector that outputs the exact cycle path if a graph fails to be a D\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.34", "subtopics_count": 4, "verification_criteria": "Implement a mathematical cycle detector that outputs the exact cycle path if a graph fails to be a DAG.", "subtopics": ["2.34.1 DAG properties: directed edges with zero directed cycles.", "2.34.2 Sources and Sinks in DAGs; reachability analysis and transitive reduction.", "2.34.3 Topological Ordering: linear ordering of vertices where every directed edge $(u, v)$ has $u$ before $v$.", "2.34.4 Why DAGs underpin computational workflows: task scheduling, build systems, neural network backpropagation."]}'::jsonb, '["Explain how this implementation prevents: Circular dependency deadlocks in software build systems and package managers.", "How does Directed Acyclic Graphs (DAGs) & Topological Properties scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-35', 'phase-02-lesson-35-asymptotic-complexity-formal-big-o-big-om', 'module-3', 35, 'Lesson 3.35: Asymptotic Complexity: Formal Big-O, Big-Omega, Big-Theta', 'Prerequisites: Lesson 2.26', 'Prerequisites: Lesson 2.26 | Subtopics: 4 items', 'Systems project application', 140, 3, 620.0, 1750.0, '# Lesson 2.35: Asymptotic Complexity: Formal Big-O, Big-Omega, Big-Theta

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.26
- **Subtopics**:
  - `2.35.1` Formal definition of Big-$O$: $f(n) \in O(g(n)) \iff \exists c > 0, n_0 > 0 	ext{ s.t. } f(n) \le c \cdot g(n) \quad orall n \ge n_0$.
  - `2.35.2` Formal definition of Big-$\Omega$ (lower bound) and Big-$\Theta$ (tight asymptotic bound).
  - `2.35.3` Little-$o$ and Little-$\omega$ definitions: strict asymptotic dominance.
  - `2.35.4` Limit test for complexity: $\lim_{n 	o \infty} rac{f(n)}{g(n)}$ to classify relative growth rates.
- **Key Failure Modes & Edge Cases**: Claiming an algorithm is $O(1)$ based on a small benchmark without analyzing asymptotic behavior at scale.
- **Verification & Mastery Check**: Formally prove using limit definitions that $3n^2 + 5n\log n \in \Theta(n^2)$.
- **Project Application**: Phase 3: Algorithmic complexity proofs.', '{"solution.py": "# Phase 2 // Lesson 2.35: Asymptotic Complexity: Formal Big-O, Big-Omega, Big-Theta\n\ndef solve():\n    \"\"\"\n    Verification: Formally prove using limit definitions that $3n^2 + 5n\\log n \\in \\Theta(n^2)$.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.35", "subtopics_count": 4, "verification_criteria": "Formally prove using limit definitions that $3n^2 + 5n\\log n \\in \\Theta(n^2)$.", "subtopics": ["2.35.1 Formal definition of Big-$O$: $f(n) \\in O(g(n)) \\iff \\exists c > 0, n_0 > 0 \text{ s.t. } f(n) \\le c \\cdot g(n) \\quad \forall n \\ge n_0$.", "2.35.2 Formal definition of Big-$\\Omega$ (lower bound) and Big-$\\Theta$ (tight asymptotic bound).", "2.35.3 Little-$o$ and Little-$\\omega$ definitions: strict asymptotic dominance.", "2.35.4 Limit test for complexity: $\\lim_{n \to \\infty} \frac{f(n)}{g(n)}$ to classify relative growth rates."]}'::jsonb, '["Explain how this implementation prevents: Claiming an algorithm is $O(1)$ based on a small benchmark without analyzing asymptotic behavior at scale.", "How does Asymptotic Complexity: Formal Big-O, Big-Omega, Big-Theta scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-9-1', 'phase-09-lesson-01-multidimensional-tensor-algebra-vector-sp', 'module-4', 1, 'Lesson 4.1: Multidimensional Tensor Algebra: Vector Spaces & Inner Products', 'Prerequisites: Phase 2, Phase 3', 'Prerequisites: Phase 2, Phase 3 | Subtopics: 6 items', 'Systems project application', 280, 10, 2310.0, 50.0, '# Lesson 9.1: Multidimensional Tensor Algebra: Vector Spaces & Inner Products

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2, Phase 3
- **Subtopics**:
  - `9.1.1` Vector spaces over real numbers $\mathbb{R}^n$: axioms, linear combinations, spanning sets, and linear independence
  - `9.1.2` Basis and dimension: standard basis, change of basis, and coordinate representations
  - `9.1.3` Inner product spaces: Euclidean dot product, geometric interpretation (angle, projection), and Cauchy-Schwarz inequality
  - `9.1.4` Vector norms: $L_1$ (Manhattan), $L_2$ (Euclidean), $L_p$, and $L_\infty$ norms; sparsity-inducing properties of $L_1$
  - `9.1.5` Orthogonality and orthonormal bases: Gram-Schmidt orthogonalization process and orthogonal projection matrices
  - `9.1.6` Hyperplanes, half-spaces, and linear separability in machine learning feature spaces
- **Key Failure Modes & Edge Cases**: Violating vector space dimensional compatibility during projection computations; dividing by zero when normalizing zero-vectors.
- **Verification & Mastery Check**: Implement a vectorized linear projection engine in NumPy computing projections of high-dimensional vectors onto arbitrary subspaces.
- **Project Application**: GradFlow: Fundamental vector math primitives.', '{"solution.py": "# Phase 9 // Lesson 9.1: Multidimensional Tensor Algebra: Vector Spaces & Inner Products\n\ndef solve():\n    \"\"\"\n    Verification: Implement a vectorized linear projection engine in NumPy computing projections of high-dimensional v\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "9.1", "subtopics_count": 6, "verification_criteria": "Implement a vectorized linear projection engine in NumPy computing projections of high-dimensional vectors onto arbitrary subspaces.", "subtopics": ["9.1.1 Vector spaces over real numbers $\\mathbb{R}^n$: axioms, linear combinations, spanning sets, and linear independence", "9.1.2 Basis and dimension: standard basis, change of basis, and coordinate representations", "9.1.3 Inner product spaces: Euclidean dot product, geometric interpretation (angle, projection), and Cauchy-Schwarz inequality", "9.1.4 Vector norms: $L_1$ (Manhattan), $L_2$ (Euclidean), $L_p$, and $L_\\infty$ norms; sparsity-inducing properties of $L_1$", "9.1.5 Orthogonality and orthonormal bases: Gram-Schmidt orthogonalization process and orthogonal projection matrices", "9.1.6 Hyperplanes, half-spaces, and linear separability in machine learning feature spaces"]}'::jsonb, '["Explain how this implementation prevents: Violating vector space dimensional compatibility during projection computations; dividing by zero when normalizing zero-", "How does Multidimensional Tensor Algebra: Vector Spaces & Inner Products scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-9-2', 'phase-09-lesson-02-matrix-transformations-ranks-invertibilit', 'module-4', 2, 'Lesson 4.2: Matrix Transformations, Ranks & Invertibility', 'Prerequisites: Lesson 9.1', 'Prerequisites: Lesson 9.1 | Subtopics: 6 items', 'Systems project application', 280, 10, 2370.0, 100.0, '# Lesson 9.2: Matrix Transformations, Ranks & Invertibility

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 9.1
- **Subtopics**:
  - `9.2.1` Matrices as linear mappings $T: \mathbb{R}^n \to \mathbb{R}^m$; domain, codomain, range, and kernel (null space)
  - `9.2.2` Matrix multiplication as composition of linear transformations; non-commutativity ($AB \neq BA$)
  - `9.2.3` Fundamental Subspaces of a Matrix: Column space, Null space, Row space, and Left Null space (Rank-Nullity Theorem)
  - `9.2.4` Matrix rank: full row rank, full column rank, rank deficiency, and low-rank approximations in neural networks (LoRA)
  - `9.2.5` Determinants: geometric interpretation as volume scaling factor, properties, and singularity criteria
  - `9.2.6` Matrix inversion: inverse properties, conditions for invertibility, and numerical instability of direct matrix inversion
- **Key Failure Modes & Edge Cases**: Computing explicit matrix inverses ($A^{-1}b$) instead of solving linear systems ($Ax=b$) via decomposition, causing massive precision loss.
- **Verification & Mastery Check**: Write a matrix rank and null-space solver using Gaussian elimination with partial pivoting in pure Python/NumPy.
- **Project Application**: GradFlow: Matrix transformation validation utilities.', '{"solution.py": "# Phase 9 // Lesson 9.2: Matrix Transformations, Ranks & Invertibility\n\ndef solve():\n    \"\"\"\n    Verification: Write a matrix rank and null-space solver using Gaussian elimination with partial pivoting in pure P\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "9.2", "subtopics_count": 6, "verification_criteria": "Write a matrix rank and null-space solver using Gaussian elimination with partial pivoting in pure Python/NumPy.", "subtopics": ["9.2.1 Matrices as linear mappings $T: \\mathbb{R}^n \\to \\mathbb{R}^m$; domain, codomain, range, and kernel (null space)", "9.2.2 Matrix multiplication as composition of linear transformations; non-commutativity ($AB \\neq BA$)", "9.2.3 Fundamental Subspaces of a Matrix: Column space, Null space, Row space, and Left Null space (Rank-Nullity Theorem)", "9.2.4 Matrix rank: full row rank, full column rank, rank deficiency, and low-rank approximations in neural networks (LoRA)", "9.2.5 Determinants: geometric interpretation as volume scaling factor, properties, and singularity criteria", "9.2.6 Matrix inversion: inverse properties, conditions for invertibility, and numerical instability of direct matrix inversion"]}'::jsonb, '["Explain how this implementation prevents: Computing explicit matrix inverses ($A^{-1}b$) instead of solving linear systems ($Ax=b$) via decomposition, causing mas", "How does Matrix Transformations, Ranks & Invertibility scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-9-3', 'phase-09-lesson-03-matrix-decompositions-lu-qr-cholesky', 'module-4', 3, 'Lesson 4.3: Matrix Decompositions: LU, QR & Cholesky', 'Prerequisites: Lesson 9.2', 'Prerequisites: Lesson 9.2 | Subtopics: 6 items', 'Systems project application', 280, 10, 2250.0, 150.0, '# Lesson 9.3: Matrix Decompositions: LU, QR & Cholesky

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 9.2
- **Subtopics**:
  - `9.3.1` LU Decomposition: factoring $A = PLU$ with partial pivoting; solving linear systems in $O(n^2)$ after $O(n^3)$ factorization
  - `9.3.2` QR Decomposition: factoring $A = QR$ with orthogonal $Q$ and upper triangular $R$ using Householder reflections and Givens rotations
  - `9.3.3` Solving least squares problems via QR decomposition: avoiding condition number squaring from normal equations ($A^TA x = A^Tb$)
  - `9.3.4` Cholesky Decomposition: factoring symmetric positive-definite matrices $A = LL^T$; efficiency and numerical stability
  - `9.3.5` Condition number of a matrix: $\kappa(A) = \|A\| \|A^{-1}\|$; ill-conditioned systems and error amplification bounds
  - `9.3.6` Applications of matrix decompositions in deep learning: Whitening transformations, covariance modeling, and stable weight initializations
- **Key Failure Modes & Edge Cases**: Attempting Cholesky factorization on non-positive-definite matrices; numerical overflow during un-pivoted LU elimination.
- **Verification & Mastery Check**: Implement LU decomposition with partial pivoting and QR decomposition via Householder reflections from scratch in pure Python.
- **Project Application**: GradFlow: Numerical linear algebra decomposition suite.', '{"solution.py": "# Phase 9 // Lesson 9.3: Matrix Decompositions: LU, QR & Cholesky\n\ndef solve():\n    \"\"\"\n    Verification: Implement LU decomposition with partial pivoting and QR decomposition via Householder reflections fr\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "9.3", "subtopics_count": 6, "verification_criteria": "Implement LU decomposition with partial pivoting and QR decomposition via Householder reflections from scratch in pure Python.", "subtopics": ["9.3.1 LU Decomposition: factoring $A = PLU$ with partial pivoting; solving linear systems in $O(n^2)$ after $O(n^3)$ factorization", "9.3.2 QR Decomposition: factoring $A = QR$ with orthogonal $Q$ and upper triangular $R$ using Householder reflections and Givens rotations", "9.3.3 Solving least squares problems via QR decomposition: avoiding condition number squaring from normal equations ($A^TA x = A^Tb$)", "9.3.4 Cholesky Decomposition: factoring symmetric positive-definite matrices $A = LL^T$; efficiency and numerical stability", "9.3.5 Condition number of a matrix: $\\kappa(A) = \\|A\\| \\|A^{-1}\\|$; ill-conditioned systems and error amplification bounds", "9.3.6 Applications of matrix decompositions in deep learning: Whitening transformations, covariance modeling, and stable weight initializations"]}'::jsonb, '["Explain how this implementation prevents: Attempting Cholesky factorization on non-positive-definite matrices; numerical overflow during un-pivoted LU elimination", "How does Matrix Decompositions: LU, QR & Cholesky scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-9-4', 'phase-09-lesson-04-spectral-theory-eigenvalues-eigenvectors-', 'module-4', 4, 'Lesson 4.4: Spectral Theory: Eigenvalues, Eigenvectors & Diagonalization', 'Prerequisites: Lesson 9.3', 'Prerequisites: Lesson 9.3 | Subtopics: 6 items', 'Systems project application', 280, 10, 2310.0, 200.0, '# Lesson 9.4: Spectral Theory: Eigenvalues, Eigenvectors & Diagonalization

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 9.3
- **Subtopics**:
  - `9.4.1` Characteristic equation: $\det(A - \lambda I) = 0$, eigenvalues $\lambda$, and eigenvectors $v$
  - `9.4.2` Geometric vs Algebraic multiplicity of eigenvalues, defective matrices, and conditions for matrix diagonalizability ($A = PDP^{-1}$)
  - `9.4.3` Spectral Theorem for Symmetric Matrices: real eigenvalues, orthogonal eigenvectors, and $A = Q \Lambda Q^T$
  - `9.4.4` Quadratic forms: $x^T A x$, positive definite, positive semi-definite, and indefinite matrices; Hessian matrix connection
  - `9.4.5` Power Iteration algorithm: computing dominant eigenvalue and eigenvector of large sparse matrices
  - `9.4.6` Rayleigh quotient and its stationary points: connecting eigenvectors to extremal values of quadratic forms
- **Key Failure Modes & Edge Cases**: Assuming all matrices are diagonalizable; power iteration failing to converge when dominant eigenvalues are equal in magnitude.
- **Verification & Mastery Check**: Implement the Power Iteration and Rayleigh Quotient algorithms to compute the top $k$ eigenvalues of symmetric matrices.
- **Project Application**: TransformerLab: Positional embedding and attention spectrum analysis.', '{"solution.py": "# Phase 9 // Lesson 9.4: Spectral Theory: Eigenvalues, Eigenvectors & Diagonalization\n\ndef solve():\n    \"\"\"\n    Verification: Implement the Power Iteration and Rayleigh Quotient algorithms to compute the top $k$ eigenvalues of\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "9.4", "subtopics_count": 6, "verification_criteria": "Implement the Power Iteration and Rayleigh Quotient algorithms to compute the top $k$ eigenvalues of symmetric matrices.", "subtopics": ["9.4.1 Characteristic equation: $\\det(A - \\lambda I) = 0$, eigenvalues $\\lambda$, and eigenvectors $v$", "9.4.2 Geometric vs Algebraic multiplicity of eigenvalues, defective matrices, and conditions for matrix diagonalizability ($A = PDP^{-1}$)", "9.4.3 Spectral Theorem for Symmetric Matrices: real eigenvalues, orthogonal eigenvectors, and $A = Q \\Lambda Q^T$", "9.4.4 Quadratic forms: $x^T A x$, positive definite, positive semi-definite, and indefinite matrices; Hessian matrix connection", "9.4.5 Power Iteration algorithm: computing dominant eigenvalue and eigenvector of large sparse matrices", "9.4.6 Rayleigh quotient and its stationary points: connecting eigenvectors to extremal values of quadratic forms"]}'::jsonb, '["Explain how this implementation prevents: Assuming all matrices are diagonalizable; power iteration failing to converge when dominant eigenvalues are equal in mag", "How does Spectral Theory: Eigenvalues, Eigenvectors & Diagonalization scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-9-5', 'phase-09-lesson-05-singular-value-decomposition-svd-principa', 'module-4', 5, 'Lesson 4.5: Singular Value Decomposition (SVD) & Principal Component Analysis (PCA)', 'Prerequisites: Lesson 9.4', 'Prerequisites: Lesson 9.4 | Subtopics: 6 items', 'Systems project application', 280, 10, 2370.0, 250.0, '# Lesson 9.5: Singular Value Decomposition (SVD) & Principal Component Analysis (PCA)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 9.4
- **Subtopics**:
  - `9.5.1` The SVD Theorem: any matrix $A \in \mathbb{R}^{m \times n}$ factors as $A = U \Sigma V^T$ with orthogonal $U, V$ and non-negative diagonal $\Sigma$
  - `9.5.2` Singular values vs eigenvalues: singular values as lengths of principal semi-axes of transformed unit spheres
  - `9.5.3` Eckart-Young-Mirsky Theorem: low-rank matrix approximation by truncating SVD; optimal approximation in Frobenius and spectral norms
  - `9.5.4` Moore-Penrose Pseudoinverse ($A^+$): minimum-norm least-squares solution for overdetermined and underdetermined systems
  - `9.5.5` Principal Component Analysis (PCA): maximizing variance of projections, covariance matrix eigendecomposition, and dimensionality reduction
  - `9.5.6` Modern applications: Low-Rank Adaptation (LoRA) of LLMs, weight matrix compression, and latent semantic analysis
- **Key Failure Modes & Edge Cases**: Failing to center data before computing PCA, leading to false principal directions aligned with dataset mean.
- **Verification & Mastery Check**: Build a full PCA and truncated SVD dimensionality reduction engine from scratch in NumPy; compress an image dataset by 80% with minimal loss.
- **Project Application**: TransformerLab: Low-rank projection analysis.', '{"solution.py": "# Phase 9 // Lesson 9.5: Singular Value Decomposition (SVD) & Principal Component Analysis (PCA)\n\ndef solve():\n    \"\"\"\n    Verification: Build a full PCA and truncated SVD dimensionality reduction engine from scratch in NumPy; compress a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "9.5", "subtopics_count": 6, "verification_criteria": "Build a full PCA and truncated SVD dimensionality reduction engine from scratch in NumPy; compress an image dataset by 80% with minimal loss.", "subtopics": ["9.5.1 The SVD Theorem: any matrix $A \\in \\mathbb{R}^{m \\times n}$ factors as $A = U \\Sigma V^T$ with orthogonal $U, V$ and non-negative diagonal $\\Sigma$", "9.5.2 Singular values vs eigenvalues: singular values as lengths of principal semi-axes of transformed unit spheres", "9.5.3 Eckart-Young-Mirsky Theorem: low-rank matrix approximation by truncating SVD; optimal approximation in Frobenius and spectral norms", "9.5.4 Moore-Penrose Pseudoinverse ($A^+$): minimum-norm least-squares solution for overdetermined and underdetermined systems", "9.5.5 Principal Component Analysis (PCA): maximizing variance of projections, covariance matrix eigendecomposition, and dimensionality reduction", "9.5.6 Modern applications: Low-Rank Adaptation (LoRA) of LLMs, weight matrix compression, and latent semantic analysis"]}'::jsonb, '["Explain how this implementation prevents: Failing to center data before computing PCA, leading to false principal directions aligned with dataset mean.", "How does Singular Value Decomposition (SVD) & Principal Component Analysis (PCA) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
