INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-10-6', 'phase-10-lesson-06-vector-embeddings-semantic-space-cosine-s', 'module-11', 6, 'Lesson 11.6: Vector Embeddings: Semantic Space, Cosine Similarity & Distance Metrics', 'Prerequisites: Phase 2, Phase 9', 'Prerequisites: Phase 2, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 300.0, '# Lesson 10.6: Vector Embeddings: Semantic Space, Cosine Similarity & Distance Metrics

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2, Phase 9
- **Subtopics**:
  - `10.6.1` Embedding concept: mapping unstructured text into continuous high-dimensional vector spaces ($\mathbb{R}^D$, typically $D=768, 1536, 3072$)
  - `10.6.2` Geometric semantic representation: spatial proximity encoding semantic similarity; analogies ($v_{king} - v_{man} + v_{woman} \approx v_{queen}$)
  - `10.6.3` Cosine Similarity: $\cos(\theta) = \frac{u \cdot v}{\|u\|_2 \|v\|_2}$; scale-invariant angle measurement in range $[-1, 1]$
  - `10.6.4` Dot Product: $u \cdot v = \|u\|_2 \|v\|_2 \cos(\theta)$; equivalent to cosine similarity when vectors are $L_2$-normalized
  - `10.6.5` Euclidean Distance ($L_2$ distance): $\|u - v\|_2 = \sqrt{\sum (u_i - v_i)^2}$; monotonic relationship with cosine similarity on normalized vectors
  - `10.6.6` Manhattan Distance ($L_1$ distance) and inner product space trade-offs across different vector dimensions
- **Key Failure Modes & Edge Cases**: Computing dot products on un-normalized embeddings expecting cosine similarity scores, producing invalid ranking orders.
- **Verification & Mastery Check**: Write a vectorized similarity engine in NumPy computing pairwise Cosine, Dot Product, and Euclidean distances across 10,000 vectors.
- **Project Application**: DocuMind: Vector mathematical operations foundation.', '{"solution.py": "# Phase 10 // Lesson 10.6: Vector Embeddings: Semantic Space, Cosine Similarity & Distance Metrics\n\ndef solve():\n    \"\"\"\n    Verification: Write a vectorized similarity engine in NumPy computing pairwise Cosine, Dot Product, and Euclidean \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.6", "subtopics_count": 6, "verification_criteria": "Write a vectorized similarity engine in NumPy computing pairwise Cosine, Dot Product, and Euclidean distances across 10,000 vectors.", "subtopics": ["10.6.1 Embedding concept: mapping unstructured text into continuous high-dimensional vector spaces ($\\mathbb{R}^D$, typically $D=768, 1536, 3072$)", "10.6.2 Geometric semantic representation: spatial proximity encoding semantic similarity; analogies ($v_{king} - v_{man} + v_{woman} \\approx v_{queen}$)", "10.6.3 Cosine Similarity: $\\cos(\\theta) = \\frac{u \\cdot v}{\\|u\\|_2 \\|v\\|_2}$; scale-invariant angle measurement in range $[-1, 1]$", "10.6.4 Dot Product: $u \\cdot v = \\|u\\|_2 \\|v\\|_2 \\cos(\\theta)$; equivalent to cosine similarity when vectors are $L_2$-normalized", "10.6.5 Euclidean Distance ($L_2$ distance): $\\|u - v\\|_2 = \\sqrt{\\sum (u_i - v_i)^2}$; monotonic relationship with cosine similarity on normalized vectors", "10.6.6 Manhattan Distance ($L_1$ distance) and inner product space trade-offs across different vector dimensions"]}'::jsonb, '["Explain how this implementation prevents: Computing dot products on un-normalized embeddings expecting cosine similarity scores, producing invalid ranking orders.", "How does Vector Embeddings: Semantic Space, Cosine Similarity & Distance Metrics scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-7', 'phase-10-lesson-07-vector-indexing-i-flat-vs-inverted-file-i', 'module-11', 7, 'Lesson 11.7: Vector Indexing I: Flat vs Inverted File Index (IVF) Clustering', 'Prerequisites: Phase 3, Lesson 10.6', 'Prerequisites: Phase 3, Lesson 10.6 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 350.0, '# Lesson 10.7: Vector Indexing I: Flat vs Inverted File Index (IVF) Clustering

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Lesson 10.6
- **Subtopics**:
  - `10.7.1` Exact Nearest Neighbor search (Flat index): brute-force pairwise distance calculation, $O(N \cdot D)$ complexity, 100% recall
  - `10.7.2` The scale boundary: why Flat index becomes unusable for latency-sensitive applications when $N > 100,000$
  - `10.7.3` Approximate Nearest Neighbor (ANN) search: trading small recall degradation for orders-of-magnitude faster query latency
  - `10.7.4` Inverted File Index (IVF) architecture: partitioning vector space into $K$ Voronoi cells using $k$-means clustering
  - `10.7.5` IVF search mechanics: indexing centroid vectors; at query time, finding the $n_{probe}$ closest centroids and searching only those lists
  - `10.7.6` Tuning IVF trade-offs: $nlist$ (number of clusters) vs $nprobe$ (number of visited clusters); recall vs QPS trade-off curve
- **Key Failure Modes & Edge Cases**: Setting `nprobe=1` on an IVF index with high clustering variance, causing recall@10 to plummet to below 50%.
- **Verification & Mastery Check**: Implement an IVF vector index from scratch in Python with $k$-means centroid training, inverted posting lists, and tunable `nprobe`.
- **Project Application**: DocuMind: Core IVF index implementation.', '{"solution.py": "# Phase 10 // Lesson 10.7: Vector Indexing I: Flat vs Inverted File Index (IVF) Clustering\n\ndef solve():\n    \"\"\"\n    Verification: Implement an IVF vector index from scratch in Python with $k$-means centroid training, inverted post\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.7", "subtopics_count": 6, "verification_criteria": "Implement an IVF vector index from scratch in Python with $k$-means centroid training, inverted posting lists, and tunable `nprobe`.", "subtopics": ["10.7.1 Exact Nearest Neighbor search (Flat index): brute-force pairwise distance calculation, $O(N \\cdot D)$ complexity, 100% recall", "10.7.2 The scale boundary: why Flat index becomes unusable for latency-sensitive applications when $N > 100,000$", "10.7.3 Approximate Nearest Neighbor (ANN) search: trading small recall degradation for orders-of-magnitude faster query latency", "10.7.4 Inverted File Index (IVF) architecture: partitioning vector space into $K$ Voronoi cells using $k$-means clustering", "10.7.5 IVF search mechanics: indexing centroid vectors; at query time, finding the $n_{probe}$ closest centroids and searching only those lists", "10.7.6 Tuning IVF trade-offs: $nlist$ (number of clusters) vs $nprobe$ (number of visited clusters); recall vs QPS trade-off curve"]}'::jsonb, '["Explain how this implementation prevents: Setting `nprobe=1` on an IVF index with high clustering variance, causing recall@10 to plummet to below 50%.", "How does Vector Indexing I: Flat vs Inverted File Index (IVF) Clustering scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-8', 'phase-10-lesson-08-vector-indexing-ii-hierarchical-navigable', 'module-11', 8, 'Lesson 11.8: Vector Indexing II: Hierarchical Navigable Small World (HNSW) Graphs', 'Prerequisites: Phase 3, Lesson 10.7', 'Prerequisites: Phase 3, Lesson 10.7 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 400.0, '# Lesson 10.8: Vector Indexing II: Hierarchical Navigable Small World (HNSW) Graphs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Lesson 10.7
- **Subtopics**:
  - `10.8.1` Small World networks: high clustering coefficient and short average path lengths (six degrees of separation)
  - `10.8.2` SkipList 1D intuition: multi-layer linked lists with probabilistic exponential layer promotion for $O(\log N)$ search
  - `10.8.3` HNSW graph architecture: multi-layer proximity graphs where layer 0 contains all vectors, and higher layers contain sparser subsets
  - `10.8.4` Greedy graph routing algorithm: greedy search at top layer, descending layers at local minima until reaching layer 0
  - `10.8.5` Graph construction parameters: $M$ (max connections per node), $M_0$ (max connections in layer 0), $efConstruction$ (search depth during build)
  - `10.8.6` Query parameter $efSearch$: controlling dynamic candidate list size during search; direct dial for tuning Recall vs QPS
- **Key Failure Modes & Edge Cases**: Setting $efConstruction$ too low during graph building, creating disconnected graph clusters that cause permanent blind spots in search.
- **Verification & Mastery Check**: Build a working Hierarchical Navigable Small World (HNSW) graph search engine in Python; evaluate routing hops across layers.
- **Project Application**: DocuMind: HNSW graph indexing engine.', '{"solution.py": "# Phase 10 // Lesson 10.8: Vector Indexing II: Hierarchical Navigable Small World (HNSW) Graphs\n\ndef solve():\n    \"\"\"\n    Verification: Build a working Hierarchical Navigable Small World (HNSW) graph search engine in Python; evaluate ro\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.8", "subtopics_count": 6, "verification_criteria": "Build a working Hierarchical Navigable Small World (HNSW) graph search engine in Python; evaluate routing hops across layers.", "subtopics": ["10.8.1 Small World networks: high clustering coefficient and short average path lengths (six degrees of separation)", "10.8.2 SkipList 1D intuition: multi-layer linked lists with probabilistic exponential layer promotion for $O(\\log N)$ search", "10.8.3 HNSW graph architecture: multi-layer proximity graphs where layer 0 contains all vectors, and higher layers contain sparser subsets", "10.8.4 Greedy graph routing algorithm: greedy search at top layer, descending layers at local minima until reaching layer 0", "10.8.5 Graph construction parameters: $M$ (max connections per node), $M_0$ (max connections in layer 0), $efConstruction$ (search depth during build)", "10.8.6 Query parameter $efSearch$: controlling dynamic candidate list size during search; direct dial for tuning Recall vs QPS"]}'::jsonb, '["Explain how this implementation prevents: Setting $efConstruction$ too low during graph building, creating disconnected graph clusters that cause permanent blind ", "How does Vector Indexing II: Hierarchical Navigable Small World (HNSW) Graphs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-9', 'phase-10-lesson-09-vector-indexing-iii-product-quantization-', 'module-11', 9, 'Lesson 11.9: Vector Indexing III: Product Quantization (PQ) & Scalar Quantization', 'Prerequisites: Phase 0, Lesson 10.7', 'Prerequisites: Phase 0, Lesson 10.7 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 450.0, '# Lesson 10.9: Vector Indexing III: Product Quantization (PQ) & Scalar Quantization

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 10.7
- **Subtopics**:
  - `10.9.1` Memory consumption of high-dimensional vectors: storing 1M 1536-dim FP32 vectors requires $10^6 \times 1536 \times 4 \approx 6.14\text{GB}$ RAM
  - `10.9.2` Scalar Quantization (SQ8): converting 32-bit floating point numbers to 8-bit integers; $4\times$ memory reduction with minimal recall loss
  - `10.9.3` Product Quantization (PQ) architecture: splitting $D$-dimensional vector into $M$ sub-vectors, clustering each subspace into $K$ centroids
  - `10.9.4` Quantized representation: replacing sub-vectors with 8-bit centroid IDs; compressing 1536-dim FP32 to 96 bytes ($16\times$ compression)
  - `10.9.5` Asymmetric Distance Computation (ADC): querying unquantized query vector against quantized database vectors using lookup tables
  - `10.9.6` Combining IVF and PQ (IVF-PQ): clustering coarse centroids with IVF, then compressing residual vectors with PQ for massive scale
- **Key Failure Modes & Edge Cases**: Excessive PQ sub-vector decomposition destroying subtle semantic vector nuances; attempting PQ on low-dimensional spaces.
- **Verification & Mastery Check**: Implement Product Quantization (PQ) from scratch in NumPy; compress 50,000 vectors by $8\times$ and benchmark recall vs uncompressed Flat search.
- **Project Application**: DocuMind: Vector compression and quantization pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.9: Vector Indexing III: Product Quantization (PQ) & Scalar Quantization\n\ndef solve():\n    \"\"\"\n    Verification: Implement Product Quantization (PQ) from scratch in NumPy; compress 50,000 vectors by $8\\times$ and \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.9", "subtopics_count": 6, "verification_criteria": "Implement Product Quantization (PQ) from scratch in NumPy; compress 50,000 vectors by $8\\times$ and benchmark recall vs uncompressed Flat search.", "subtopics": ["10.9.1 Memory consumption of high-dimensional vectors: storing 1M 1536-dim FP32 vectors requires $10^6 \\times 1536 \\times 4 \\approx 6.14\\text{GB}$ RAM", "10.9.2 Scalar Quantization (SQ8): converting 32-bit floating point numbers to 8-bit integers; $4\\times$ memory reduction with minimal recall loss", "10.9.3 Product Quantization (PQ) architecture: splitting $D$-dimensional vector into $M$ sub-vectors, clustering each subspace into $K$ centroids", "10.9.4 Quantized representation: replacing sub-vectors with 8-bit centroid IDs; compressing 1536-dim FP32 to 96 bytes ($16\\times$ compression)", "10.9.5 Asymmetric Distance Computation (ADC): querying unquantized query vector against quantized database vectors using lookup tables", "10.9.6 Combining IVF and PQ (IVF-PQ): clustering coarse centroids with IVF, then compressing residual vectors with PQ for massive scale"]}'::jsonb, '["Explain how this implementation prevents: Excessive PQ sub-vector decomposition destroying subtle semantic vector nuances; attempting PQ on low-dimensional spaces", "How does Vector Indexing III: Product Quantization (PQ) & Scalar Quantization scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-10', 'phase-10-lesson-10-postgresql-vector-extensions-pgvector-arc', 'module-11', 10, 'Lesson 11.10: PostgreSQL Vector Extensions: pgvector Architecture & HNSW Tuning', 'Prerequisites: Phase 4, Lesson 10.8', 'Prerequisites: Phase 4, Lesson 10.8 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 500.0, '# Lesson 10.10: PostgreSQL Vector Extensions: pgvector Architecture & HNSW Tuning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 10.8
- **Subtopics**:
  - `10.10.1` Why vector search inside relational databases: eliminating dual-database synchronization lag and enabling unified SQL filtering
  - `10.10.2` `pgvector` extension internals: custom `vector` data type, operators (`<->` L2, `<#>` inner product, `<=>` cosine distance)
  - `10.10.3` Index types in `pgvector`: IVFFlat vs HNSW (pgvector 0.5.0+)
  - `10.10.4` Creating and tuning HNSW indexes: `CREATE INDEX ... USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)`
  - `10.10.5` Runtime query tuning: setting `SET hnsw.ef_search = 100` per session to balance query latency vs recall
  - `10.10.6` Hybrid queries in SQL: combining vector similarity with relational constraints (`WHERE organization_id = X AND created_at > Y`)
- **Key Failure Modes & Edge Cases**: Creating an IVFFlat index on an empty table before inserting data, resulting in empty or completely skewed cluster centroids.
- **Verification & Mastery Check**: Set up a PostgreSQL instance with `pgvector`; populate 100,000 1536-dim embeddings, build an HNSW index, and optimize query latency to <5ms.
- **Project Application**: DocuMind: Database storage and pgvector retrieval engine.', '{"solution.py": "# Phase 10 // Lesson 10.10: PostgreSQL Vector Extensions: pgvector Architecture & HNSW Tuning\n\ndef solve():\n    \"\"\"\n    Verification: Set up a PostgreSQL instance with `pgvector`; populate 100,000 1536-dim embeddings, build an HNSW in\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.10", "subtopics_count": 6, "verification_criteria": "Set up a PostgreSQL instance with `pgvector`; populate 100,000 1536-dim embeddings, build an HNSW index, and optimize query latency to <5ms.", "subtopics": ["10.10.1 Why vector search inside relational databases: eliminating dual-database synchronization lag and enabling unified SQL filtering", "10.10.2 `pgvector` extension internals: custom `vector` data type, operators (`<->` L2, `<#>` inner product, `<=>` cosine distance)", "10.10.3 Index types in `pgvector`: IVFFlat vs HNSW (pgvector 0.5.0+)", "10.10.4 Creating and tuning HNSW indexes: `CREATE INDEX ... USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)`", "10.10.5 Runtime query tuning: setting `SET hnsw.ef_search = 100` per session to balance query latency vs recall", "10.10.6 Hybrid queries in SQL: combining vector similarity with relational constraints (`WHERE organization_id = X AND created_at > Y`)"]}'::jsonb, '["Explain how this implementation prevents: Creating an IVFFlat index on an empty table before inserting data, resulting in empty or completely skewed cluster centr", "How does PostgreSQL Vector Extensions: pgvector Architecture & HNSW Tuning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-11', 'phase-10-lesson-11-vector-database-landscape-dedicated-vs-ge', 'module-11', 11, 'Lesson 11.11: Vector Database Landscape: Dedicated vs General-Purpose Stores', 'Prerequisites: Lesson 10.10', 'Prerequisites: Lesson 10.10 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 550.0, '# Lesson 10.11: Vector Database Landscape: Dedicated vs General-Purpose Stores

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.10
- **Subtopics**:
  - `10.11.1` Dedicated vector databases: Pinecone (managed SaaS), Qdrant (Rust, payload filtering), Milvus (distributed Go/C++), Weaviate (modular GraphQL)
  - `10.11.2` General-purpose extensions: pgvector (PostgreSQL), Redis Search (in-memory HNSW), Elasticsearch / OpenSearch dense_vector
  - `10.11.3` Architectural comparison matrix: scale (millions vs billions of vectors), indexing speed, filtering ergonomics, and operational cost
  - `10.11.4` Payload filtering mechanics: Pre-filtering (filter metadata first, then search vector subset) vs Post-filtering vs Single-stage filtered HNSW
  - `10.11.5` The filter-vector dilemma: why naive post-filtering fails when metadata filters exclude 99% of top vector matches
  - `10.11.6` Single-stage iterative graph traversal: Qdrant''s payload-aware HNSW traversing only graph nodes that satisfy metadata predicates
- **Key Failure Modes & Edge Cases**: Using post-filtering on restrictive metadata predicates, returning 0 search results because top vector neighbors were stripped post-hoc.
- **Verification & Mastery Check**: Benchmark Qdrant vs pgvector on 500,000 vectors with restrictive metadata filters; measure QPS and recall under high concurrency.
- **Project Application**: DocuMind: Vector storage engine selection benchmark.', '{"solution.py": "# Phase 10 // Lesson 10.11: Vector Database Landscape: Dedicated vs General-Purpose Stores\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark Qdrant vs pgvector on 500,000 vectors with restrictive metadata filters; measure QPS and r\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.11", "subtopics_count": 6, "verification_criteria": "Benchmark Qdrant vs pgvector on 500,000 vectors with restrictive metadata filters; measure QPS and recall under high concurrency.", "subtopics": ["10.11.1 Dedicated vector databases: Pinecone (managed SaaS), Qdrant (Rust, payload filtering), Milvus (distributed Go/C++), Weaviate (modular GraphQL)", "10.11.2 General-purpose extensions: pgvector (PostgreSQL), Redis Search (in-memory HNSW), Elasticsearch / OpenSearch dense_vector", "10.11.3 Architectural comparison matrix: scale (millions vs billions of vectors), indexing speed, filtering ergonomics, and operational cost", "10.11.4 Payload filtering mechanics: Pre-filtering (filter metadata first, then search vector subset) vs Post-filtering vs Single-stage filtered HNSW", "10.11.5 The filter-vector dilemma: why naive post-filtering fails when metadata filters exclude 99% of top vector matches", "10.11.6 Single-stage iterative graph traversal: Qdrant''s payload-aware HNSW traversing only graph nodes that satisfy metadata predicates"]}'::jsonb, '["Explain how this implementation prevents: Using post-filtering on restrictive metadata predicates, returning 0 search results because top vector neighbors were st", "How does Vector Database Landscape: Dedicated vs General-Purpose Stores scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-12', 'phase-10-lesson-12-approximate-nearest-neighbors-ann-benchma', 'module-11', 12, 'Lesson 11.12: Approximate Nearest Neighbors (ANN) Benchmarking: Recall@K vs QPS', 'Prerequisites: Lesson 10.7, Lesson 10.8', 'Prerequisites: Lesson 10.7, Lesson 10.8 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 600.0, '# Lesson 10.12: Approximate Nearest Neighbors (ANN) Benchmarking: Recall@K vs QPS

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.7, Lesson 10.8
- **Subtopics**:
  - `10.12.1` ANN benchmarking methodology: ground truth generation using exact brute-force Flat index search
  - `10.12.2` Recall@K definition: $\frac{|\text{Top } K \text{ approximate results} \cap \text{Top } K \text{ true results}|}{K}$
  - `10.12.3` Query throughput: Queries Per Second (QPS) under varying concurrency levels (single-threaded vs multi-threaded)
  - `10.12.4` Latency percentiles: p50, p95, p99 search latency distributions under sustained query load
  - `10.12.5` Generating Pareto frontiers: plotting Recall@K on the x-axis vs QPS on the y-axis across varying $efSearch$ / $nprobe$ configurations
  - `10.12.6` ann-benchmarks standard: understanding standardized datasets (GloVe, SIFT, Deep1B) and reproducing standardized evaluation runs
- **Key Failure Modes & Edge Cases**: Reporting 99% Recall@1 without measuring Recall@10 or p99 tail latency; evaluating on synthetic random vectors rather than clustered text embeddings.
- **Verification & Mastery Check**: Build an automated ANN benchmark harness evaluating recall@10 vs QPS curves across 5 index parameter configurations on a real dataset.
- **Project Application**: EvalKit: ANN benchmark and Pareto frontier generator.', '{"solution.py": "# Phase 10 // Lesson 10.12: Approximate Nearest Neighbors (ANN) Benchmarking: Recall@K vs QPS\n\ndef solve():\n    \"\"\"\n    Verification: Build an automated ANN benchmark harness evaluating recall@10 vs QPS curves across 5 index parameter\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.12", "subtopics_count": 6, "verification_criteria": "Build an automated ANN benchmark harness evaluating recall@10 vs QPS curves across 5 index parameter configurations on a real dataset.", "subtopics": ["10.12.1 ANN benchmarking methodology: ground truth generation using exact brute-force Flat index search", "10.12.2 Recall@K definition: $\\frac{|\\text{Top } K \\text{ approximate results} \\cap \\text{Top } K \\text{ true results}|}{K}$", "10.12.3 Query throughput: Queries Per Second (QPS) under varying concurrency levels (single-threaded vs multi-threaded)", "10.12.4 Latency percentiles: p50, p95, p99 search latency distributions under sustained query load", "10.12.5 Generating Pareto frontiers: plotting Recall@K on the x-axis vs QPS on the y-axis across varying $efSearch$ / $nprobe$ configurations", "10.12.6 ann-benchmarks standard: understanding standardized datasets (GloVe, SIFT, Deep1B) and reproducing standardized evaluation runs"]}'::jsonb, '["Explain how this implementation prevents: Reporting 99% Recall@1 without measuring Recall@10 or p99 tail latency; evaluating on synthetic random vectors rather th", "How does Approximate Nearest Neighbors (ANN) Benchmarking: Recall@K vs QPS scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-13', 'phase-10-lesson-13-document-ingestion-pipelines-parsing-pdfs', 'module-11', 13, 'Lesson 11.13: Document Ingestion Pipelines: Parsing PDFs, Markdown, HTML & OCR', 'Prerequisites: Phase 4, Lesson 10.5', 'Prerequisites: Phase 4, Lesson 10.5 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 650.0, '# Lesson 10.13: Document Ingestion Pipelines: Parsing PDFs, Markdown, HTML & OCR

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 10.5
- **Subtopics**:
  - `10.13.1` The messy reality of enterprise data: semi-structured PDFs, Word documents, scanned invoices, HTML wikis, and markdown
  - `10.13.2` PDF parsing internals: content streams, text positioning matrices ($Tm$), font glyph encodings, and reading order extraction
  - `10.13.3` Why naive PDF parsers fail: multi-column layouts read horizontally across columns, scrambled headers, and stripped formatting
  - `10.13.4` Advanced layout-aware parsers: PyMuPDF, pdfplumber, and layout-detection neural networks (LayoutLM, Marker)
  - `10.13.5` HTML and Markdown extraction: DOM element traversal, stripping script/nav tags, preserving markdown header hierarchy with BeautifulSoup
  - `10.13.6` Optical Character Recognition (OCR): Tesseract, easyOCR, and vision-language models for scanned document transcription
- **Key Failure Modes & Edge Cases**: Naive PDF parser reading two-column legal contracts horizontally across columns, interweaving unrelated sentences into nonsense.
- **Verification & Mastery Check**: Build a robust layout-aware PDF ingestion pipeline that correctly extracts two-column articles with preserved paragraph boundaries.
- **Project Application**: DocuMind: Enterprise multi-format document parser.', '{"solution.py": "# Phase 10 // Lesson 10.13: Document Ingestion Pipelines: Parsing PDFs, Markdown, HTML & OCR\n\ndef solve():\n    \"\"\"\n    Verification: Build a robust layout-aware PDF ingestion pipeline that correctly extracts two-column articles with \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.13", "subtopics_count": 6, "verification_criteria": "Build a robust layout-aware PDF ingestion pipeline that correctly extracts two-column articles with preserved paragraph boundaries.", "subtopics": ["10.13.1 The messy reality of enterprise data: semi-structured PDFs, Word documents, scanned invoices, HTML wikis, and markdown", "10.13.2 PDF parsing internals: content streams, text positioning matrices ($Tm$), font glyph encodings, and reading order extraction", "10.13.3 Why naive PDF parsers fail: multi-column layouts read horizontally across columns, scrambled headers, and stripped formatting", "10.13.4 Advanced layout-aware parsers: PyMuPDF, pdfplumber, and layout-detection neural networks (LayoutLM, Marker)", "10.13.5 HTML and Markdown extraction: DOM element traversal, stripping script/nav tags, preserving markdown header hierarchy with BeautifulSoup", "10.13.6 Optical Character Recognition (OCR): Tesseract, easyOCR, and vision-language models for scanned document transcription"]}'::jsonb, '["Explain how this implementation prevents: Naive PDF parser reading two-column legal contracts horizontally across columns, interweaving unrelated sentences into n", "How does Document Ingestion Pipelines: Parsing PDFs, Markdown, HTML & OCR scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-14', 'phase-10-lesson-14-chunking-strategies-fixed-size-sentence-r', 'module-11', 14, 'Lesson 11.14: Chunking Strategies: Fixed-Size, Sentence, Recursive & Semantic', 'Prerequisites: Lesson 10.13', 'Prerequisites: Lesson 10.13 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 700.0, '# Lesson 10.14: Chunking Strategies: Fixed-Size, Sentence, Recursive & Semantic

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.13
- **Subtopics**:
  - `10.14.1` Why chunking is mandatory: embedding model context length limits (typically 512 or 8192 tokens) and retrieval specificity
  - `10.14.2` Fixed-size chunking with overlap: character/token count thresholds (e.g. 500 tokens with 50 token overlap); simplicity vs boundary slicing
  - `10.14.3` Sentence-aware chunking: splitting strictly on sentence boundaries (using NLTK or SpaCy) to preserve linguistic semantics
  - `10.14.4` Recursive character chunking (LangChain-style): hierarchical separators (`[''\n\n'', ''\n'', '' '', '''']`) keeping structural paragraphs intact
  - `10.14.5` Semantic chunking: embedding consecutive sentences, computing cosine distance between adjacent sentences, and splitting on semantic drops
  - `10.14.6` The chunk size trade-off: small chunks (high precision retrieval, lost context) vs large chunks (rich context, diluted retrieval precision)
- **Key Failure Modes & Edge Cases**: Splitting chunks across hyphenated words or code blocks, destroying syntax and semantics; 0 chunk overlap causing lost context at seams.
- **Verification & Mastery Check**: Implement fixed, recursive, and semantic chunking algorithms from scratch in Python; evaluate semantic cohesion across chunk boundaries.
- **Project Application**: DocuMind: Modular chunking engine.', '{"solution.py": "# Phase 10 // Lesson 10.14: Chunking Strategies: Fixed-Size, Sentence, Recursive & Semantic\n\ndef solve():\n    \"\"\"\n    Verification: Implement fixed, recursive, and semantic chunking algorithms from scratch in Python; evaluate semant\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.14", "subtopics_count": 6, "verification_criteria": "Implement fixed, recursive, and semantic chunking algorithms from scratch in Python; evaluate semantic cohesion across chunk boundaries.", "subtopics": ["10.14.1 Why chunking is mandatory: embedding model context length limits (typically 512 or 8192 tokens) and retrieval specificity", "10.14.2 Fixed-size chunking with overlap: character/token count thresholds (e.g. 500 tokens with 50 token overlap); simplicity vs boundary slicing", "10.14.3 Sentence-aware chunking: splitting strictly on sentence boundaries (using NLTK or SpaCy) to preserve linguistic semantics", "10.14.4 Recursive character chunking (LangChain-style): hierarchical separators (`[''\\n\\n'', ''\\n'', '' '', '''']`) keeping structural paragraphs intact", "10.14.5 Semantic chunking: embedding consecutive sentences, computing cosine distance between adjacent sentences, and splitting on semantic drops", "10.14.6 The chunk size trade-off: small chunks (high precision retrieval, lost context) vs large chunks (rich context, diluted retrieval precision)"]}'::jsonb, '["Explain how this implementation prevents: Splitting chunks across hyphenated words or code blocks, destroying syntax and semantics; 0 chunk overlap causing lost c", "How does Chunking Strategies: Fixed-Size, Sentence, Recursive & Semantic scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-15', 'phase-10-lesson-15-multi-modal-document-parsing-tables-chart', 'module-11', 15, 'Lesson 11.15: Multi-Modal Document Parsing: Tables, Charts & Visual Layouts', 'Prerequisites: Lesson 10.13, Lesson 10.14', 'Prerequisites: Lesson 10.13, Lesson 10.14 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 750.0, '# Lesson 10.15: Multi-Modal Document Parsing: Tables, Charts & Visual Layouts

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.13, Lesson 10.14
- **Subtopics**:
  - `10.15.1` The tabular data crisis in RAG: flat text embeddings destroying 2D row/column relational alignment
  - `10.15.2` Table extraction techniques: structural HTML table representations vs Markdown tables vs CSV serialization
  - `10.15.3` Vision-Language Model (VLM) parsing: passing document page images to Gemini 1.5 Pro / GPT-4o for markdown table transcription
  - `10.15.4` Chart and infographic extraction: generating natural language descriptive summaries of visual charts for vector indexing
  - `10.15.5` Bounding box metadata: tracking $(x_0, y_0, x_1, y_1)$ page coordinates per chunk to enable visual citation highlighting in UIs
  - `10.15.6` Hierarchical section mapping: associating chunks with parent document title, chapter header, and subsection breadcrumbs
- **Key Failure Modes & Edge Cases**: Flattening financial balance sheets into unstructured paragraphs, causing LLM to swap columns and hallucinate revenue numbers.
- **Verification & Mastery Check**: Build a multi-modal document pipeline extracting complex nested financial tables into clean Markdown tables with coordinates.
- **Project Application**: DocuMind: Visual document and table extraction pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.15: Multi-Modal Document Parsing: Tables, Charts & Visual Layouts\n\ndef solve():\n    \"\"\"\n    Verification: Build a multi-modal document pipeline extracting complex nested financial tables into clean Markdown\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.15", "subtopics_count": 6, "verification_criteria": "Build a multi-modal document pipeline extracting complex nested financial tables into clean Markdown tables with coordinates.", "subtopics": ["10.15.1 The tabular data crisis in RAG: flat text embeddings destroying 2D row/column relational alignment", "10.15.2 Table extraction techniques: structural HTML table representations vs Markdown tables vs CSV serialization", "10.15.3 Vision-Language Model (VLM) parsing: passing document page images to Gemini 1.5 Pro / GPT-4o for markdown table transcription", "10.15.4 Chart and infographic extraction: generating natural language descriptive summaries of visual charts for vector indexing", "10.15.5 Bounding box metadata: tracking $(x_0, y_0, x_1, y_1)$ page coordinates per chunk to enable visual citation highlighting in UIs", "10.15.6 Hierarchical section mapping: associating chunks with parent document title, chapter header, and subsection breadcrumbs"]}'::jsonb, '["Explain how this implementation prevents: Flattening financial balance sheets into unstructured paragraphs, causing LLM to swap columns and hallucinate revenue nu", "How does Multi-Modal Document Parsing: Tables, Charts & Visual Layouts scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-16', 'phase-10-lesson-16-metadata-enrichment-temporal-tags-entity-', 'module-11', 16, 'Lesson 11.16: Metadata Enrichment: Temporal Tags, Entity Extraction & Hierarchy', 'Prerequisites: Lesson 10.3, Lesson 10.14', 'Prerequisites: Lesson 10.3, Lesson 10.14 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 800.0, '# Lesson 10.16: Metadata Enrichment: Temporal Tags, Entity Extraction & Hierarchy

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.3, Lesson 10.14
- **Subtopics**:
  - `10.16.1` Why pure vector similarity is insufficient: handling queries like ''What was our Q3 2024 revenue for customer X?''
  - `10.16.2` Automatic metadata extraction via small LLMs: extracting document dates, author, organization, product category, and document type
  - `10.16.3` Named Entity Recognition (NER): extracting people, organizations, locations, and unique identifier codes (e.g. ticket IDs)
  - `10.16.4` Document hierarchy tagging: injecting breadcrumb trails (e.g. `Document > Section 2 > Subsection A`) directly into chunk text
  - `10.16.5` Hypothetical question generation: using an LLM to generate 3 prospective user questions that each chunk answers, embedded alongside chunk
  - `10.16.6` Storing enriched metadata: JSONB payloads in pgvector or structured metadata payloads in dedicated vector stores
- **Key Failure Modes & Edge Cases**: Omitting temporal metadata, causing RAG to retrieve outdated 2021 corporate policies instead of updated 2024 policies for current questions.
- **Verification & Mastery Check**: Implement an automated metadata enrichment pipeline extracting dates, entities, and hypothetical questions for every ingested chunk.
- **Project Application**: DocuMind: Automated chunk metadata enrichment pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.16: Metadata Enrichment: Temporal Tags, Entity Extraction & Hierarchy\n\ndef solve():\n    \"\"\"\n    Verification: Implement an automated metadata enrichment pipeline extracting dates, entities, and hypothetical que\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.16", "subtopics_count": 6, "verification_criteria": "Implement an automated metadata enrichment pipeline extracting dates, entities, and hypothetical questions for every ingested chunk.", "subtopics": ["10.16.1 Why pure vector similarity is insufficient: handling queries like ''What was our Q3 2024 revenue for customer X?''", "10.16.2 Automatic metadata extraction via small LLMs: extracting document dates, author, organization, product category, and document type", "10.16.3 Named Entity Recognition (NER): extracting people, organizations, locations, and unique identifier codes (e.g. ticket IDs)", "10.16.4 Document hierarchy tagging: injecting breadcrumb trails (e.g. `Document > Section 2 > Subsection A`) directly into chunk text", "10.16.5 Hypothetical question generation: using an LLM to generate 3 prospective user questions that each chunk answers, embedded alongside chunk", "10.16.6 Storing enriched metadata: JSONB payloads in pgvector or structured metadata payloads in dedicated vector stores"]}'::jsonb, '["Explain how this implementation prevents: Omitting temporal metadata, causing RAG to retrieve outdated 2021 corporate policies instead of updated 2024 policies fo", "How does Metadata Enrichment: Temporal Tags, Entity Extraction & Hierarchy scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-17', 'phase-10-lesson-17-embedding-model-selection-mteb-leaderboar', 'module-11', 17, 'Lesson 11.17: Embedding Model Selection: MTEB Leaderboard, Bi-Encoders & Domain Tuning', 'Prerequisites: Lesson 10.6, Phase 9', 'Prerequisites: Lesson 10.6, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 850.0, '# Lesson 10.17: Embedding Model Selection: MTEB Leaderboard, Bi-Encoders & Domain Tuning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.6, Phase 9
- **Subtopics**:
  - `10.17.1` Massive Text Embedding Benchmark (MTEB): evaluating models across Retrieval, Reranking, Clustering, Classification, and STS tasks
  - `10.17.2` Bi-Encoder architecture: Siamese networks encoding query and document independently into fixed-size vectors ($u = f(q), v = f(d)$)
  - `10.17.3` Commercial vs Open-Source embedding models: OpenAI `text-embedding-3-large`, Cohere `embed-v3`, BAAI `bge-large-en-v1.5`, Voyage AI
  - `10.17.4` Asymmetric retrieval tasks: why some models require instruction prefixes (e.g. `query: ` vs `passage: `) for optimal scoring
  - `10.17.5` Domain-specific embeddings: why general-purpose embeddings degrade on medical, legal, or proprietary codebases
  - `10.17.6` Matryoshka Representation Learning (MRL): models trained to produce embeddings that can be truncated to 256 or 512 dimensions without loss
- **Key Failure Modes & Edge Cases**: Forgetting the required query prefix (`Represent this sentence for searching relevant passages:`) on models like E5, dropping retrieval accuracy by 25%.
- **Verification & Mastery Check**: Evaluate 3 open-source embedding models from MTEB on a domain-specific dataset; benchmark recall@5 and compute latency.
- **Project Application**: DocuMind: Multi-model embedding evaluation harness.', '{"solution.py": "# Phase 10 // Lesson 10.17: Embedding Model Selection: MTEB Leaderboard, Bi-Encoders & Domain Tuning\n\ndef solve():\n    \"\"\"\n    Verification: Evaluate 3 open-source embedding models from MTEB on a domain-specific dataset; benchmark recall@5 a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.17", "subtopics_count": 6, "verification_criteria": "Evaluate 3 open-source embedding models from MTEB on a domain-specific dataset; benchmark recall@5 and compute latency.", "subtopics": ["10.17.1 Massive Text Embedding Benchmark (MTEB): evaluating models across Retrieval, Reranking, Clustering, Classification, and STS tasks", "10.17.2 Bi-Encoder architecture: Siamese networks encoding query and document independently into fixed-size vectors ($u = f(q), v = f(d)$)", "10.17.3 Commercial vs Open-Source embedding models: OpenAI `text-embedding-3-large`, Cohere `embed-v3`, BAAI `bge-large-en-v1.5`, Voyage AI", "10.17.4 Asymmetric retrieval tasks: why some models require instruction prefixes (e.g. `query: ` vs `passage: `) for optimal scoring", "10.17.5 Domain-specific embeddings: why general-purpose embeddings degrade on medical, legal, or proprietary codebases", "10.17.6 Matryoshka Representation Learning (MRL): models trained to produce embeddings that can be truncated to 256 or 512 dimensions without loss"]}'::jsonb, '["Explain how this implementation prevents: Forgetting the required query prefix (`Represent this sentence for searching relevant passages:`) on models like E5, dro", "How does Embedding Model Selection: MTEB Leaderboard, Bi-Encoders & Domain Tuning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-18', 'phase-10-lesson-18-ingestion-pipeline-orchestration-idempote', 'module-11', 18, 'Lesson 11.18: Ingestion Pipeline Orchestration: Idempotency, Change Data Capture & Deduplication', 'Prerequisites: Phase 4, Phase 7, Lesson 10.14', 'Prerequisites: Phase 4, Phase 7, Lesson 10.14 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 900.0, '# Lesson 10.18: Ingestion Pipeline Orchestration: Idempotency, Change Data Capture & Deduplication

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7, Lesson 10.14
- **Subtopics**:
  - `10.18.1` Building production-grade ingestion pipelines: handling millions of documents continuously without data corruption
  - `10.18.2` Idempotency in vector ingestion: content-based hashing (SHA-256 of raw chunk) as deterministic vector primary keys
  - `10.18.3` Change Data Capture (CDC): detecting document modifications, deletions, and additions via database triggers or Kafka streams
  - `10.18.4` Incremental re-indexing: updating only modified chunks while pruning deleted document vectors to prevent stale ghost retrievals
  - `10.18.5` Near-duplicate document detection: MinHash and Locality-Sensitive Hashing (LSH) detecting duplicate documents before ingestion
  - `10.18.6` Pipeline failure resilience: dead-letter queues for unparseable documents, retry policies, and progress checkpoints in Redis
- **Key Failure Modes & Edge Cases**: Re-running an ingestion job re-inserting all documents with random UUIDs, duplicating millions of vectors and doubling cloud costs.
- **Verification & Mastery Check**: Build an idempotent document ingestion pipeline backed by SHA-256 chunk hashing that gracefully skips unchanged documents upon re-run.
- **Project Application**: DocuMind: Enterprise idempotent ingestion worker fleet.', '{"solution.py": "# Phase 10 // Lesson 10.18: Ingestion Pipeline Orchestration: Idempotency, Change Data Capture & Deduplication\n\ndef solve():\n    \"\"\"\n    Verification: Build an idempotent document ingestion pipeline backed by SHA-256 chunk hashing that gracefully skip\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.18", "subtopics_count": 6, "verification_criteria": "Build an idempotent document ingestion pipeline backed by SHA-256 chunk hashing that gracefully skips unchanged documents upon re-run.", "subtopics": ["10.18.1 Building production-grade ingestion pipelines: handling millions of documents continuously without data corruption", "10.18.2 Idempotency in vector ingestion: content-based hashing (SHA-256 of raw chunk) as deterministic vector primary keys", "10.18.3 Change Data Capture (CDC): detecting document modifications, deletions, and additions via database triggers or Kafka streams", "10.18.4 Incremental re-indexing: updating only modified chunks while pruning deleted document vectors to prevent stale ghost retrievals", "10.18.5 Near-duplicate document detection: MinHash and Locality-Sensitive Hashing (LSH) detecting duplicate documents before ingestion", "10.18.6 Pipeline failure resilience: dead-letter queues for unparseable documents, retry policies, and progress checkpoints in Redis"]}'::jsonb, '["Explain how this implementation prevents: Re-running an ingestion job re-inserting all documents with random UUIDs, duplicating millions of vectors and doubling c", "How does Ingestion Pipeline Orchestration: Idempotency, Change Data Capture & Deduplication scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-19', 'phase-10-lesson-19-hybrid-retrieval-architectures-dense-vect', 'module-11', 19, 'Lesson 11.19: Hybrid Retrieval Architectures: Dense Vector Search + Sparse Lexical Search', 'Prerequisites: Lesson 10.6, Lesson 10.10', 'Prerequisites: Lesson 10.6, Lesson 10.10 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 950.0, '# Lesson 10.19: Hybrid Retrieval Architectures: Dense Vector Search + Sparse Lexical Search

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.6, Lesson 10.10
- **Subtopics**:
  - `10.19.1` The fundamental limitations of dense vector search: struggle with exact keyword matches, SKU numbers, product codes, and acronyms
  - `10.19.2` The fundamental limitations of lexical search: vocabulary mismatch problem, inability to understand synonyms, paraphrases, and context
  - `10.19.3` Hybrid search paradigm: executing dense semantic vector search and sparse lexical keyword search in parallel
  - `10.19.4` Sparse representation models: BM25 traditional lexical scoring vs learned sparse representations (SPLADE, BM42)
  - `10.19.5` Combining dense and sparse results: score normalization, linear weighted score interpolation, and rank-based fusion
  - `10.19.6` Architecture of hybrid query engines: orchestrating parallel queries against pgvector and PostgreSQL full-text search (`tsvector`)
- **Key Failure Modes & Edge Cases**: Relying solely on vector search for product ID queries (`XJ-9000`), returning semantically similar models instead of the exact match.
- **Verification & Mastery Check**: Implement a dual-stream hybrid search engine executing dense vector search and sparse lexical search against PostgreSQL in parallel.
- **Project Application**: DocuMind: Hybrid retrieval orchestration layer.', '{"solution.py": "# Phase 10 // Lesson 10.19: Hybrid Retrieval Architectures: Dense Vector Search + Sparse Lexical Search\n\ndef solve():\n    \"\"\"\n    Verification: Implement a dual-stream hybrid search engine executing dense vector search and sparse lexical search\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.19", "subtopics_count": 6, "verification_criteria": "Implement a dual-stream hybrid search engine executing dense vector search and sparse lexical search against PostgreSQL in parallel.", "subtopics": ["10.19.1 The fundamental limitations of dense vector search: struggle with exact keyword matches, SKU numbers, product codes, and acronyms", "10.19.2 The fundamental limitations of lexical search: vocabulary mismatch problem, inability to understand synonyms, paraphrases, and context", "10.19.3 Hybrid search paradigm: executing dense semantic vector search and sparse lexical keyword search in parallel", "10.19.4 Sparse representation models: BM25 traditional lexical scoring vs learned sparse representations (SPLADE, BM42)", "10.19.5 Combining dense and sparse results: score normalization, linear weighted score interpolation, and rank-based fusion", "10.19.6 Architecture of hybrid query engines: orchestrating parallel queries against pgvector and PostgreSQL full-text search (`tsvector`)"]}'::jsonb, '["Explain how this implementation prevents: Relying solely on vector search for product ID queries (`XJ-9000`), returning semantically similar models instead of the", "How does Hybrid Retrieval Architectures: Dense Vector Search + Sparse Lexical Search scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-20', 'phase-10-lesson-20-bm25-lexical-retrieval-mechanics-inverted', 'module-11', 20, 'Lesson 11.20: BM25 Lexical Retrieval Mechanics & Inverted Indexes', 'Prerequisites: Phase 3, Lesson 8.21, Lesson 10.19', 'Prerequisites: Phase 3, Lesson 8.21, Lesson 10.19 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1000.0, '# Lesson 10.20: BM25 Lexical Retrieval Mechanics & Inverted Indexes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Lesson 8.21, Lesson 10.19
- **Subtopics**:
  - `10.20.1` The BM25 (Best Matching 25) probabilistic relevance framework derived from the Okapi information retrieval system
  - `10.20.2` Term Frequency (TF) saturation: why BM25 limits the impact of repeatedly repeating a keyword via parameter $k_1$ (typically 1.2-2.0)
  - `10.20.3` Inverse Document Frequency (IDF): $\text{IDF}(q_i) = \ln\left(\frac{N - n(q_i) + 0.5}{n(q_i) + 0.5} + 1\right)$; penalizing ubiquitous common words
  - `10.20.4` Document length normalization: parameter $b$ (typically 0.75) penalizing excessively long documents to prevent unfair length advantages
  - `10.20.5` BM25 formula derivation: $\sum_{i=1}^m \text{IDF}(q_i) \cdot \frac{f(q_i, D) \cdot (k_1 + 1)}{f(q_i, D) + k_1 \cdot (1 - b + b \cdot \frac{|D|}{\text{avgdl}})}$
  - `10.20.6` Implementing BM25 from scratch: tokenization, stop-words, term-document posting lists, and document length tracking
- **Key Failure Modes & Edge Cases**: Failing to normalize document length ($b=0$), causing 50-page documents to dominate search results over concise 1-paragraph answers.
- **Verification & Mastery Check**: Build a standalone BM25 retrieval engine from scratch in pure Python; verify scoring correctness against rank-bm25 library.
- **Project Application**: DocuMind: Core BM25 lexical retrieval engine.', '{"solution.py": "# Phase 10 // Lesson 10.20: BM25 Lexical Retrieval Mechanics & Inverted Indexes\n\ndef solve():\n    \"\"\"\n    Verification: Build a standalone BM25 retrieval engine from scratch in pure Python; verify scoring correctness aga\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.20", "subtopics_count": 6, "verification_criteria": "Build a standalone BM25 retrieval engine from scratch in pure Python; verify scoring correctness against rank-bm25 library.", "subtopics": ["10.20.1 The BM25 (Best Matching 25) probabilistic relevance framework derived from the Okapi information retrieval system", "10.20.2 Term Frequency (TF) saturation: why BM25 limits the impact of repeatedly repeating a keyword via parameter $k_1$ (typically 1.2-2.0)", "10.20.3 Inverse Document Frequency (IDF): $\\text{IDF}(q_i) = \\ln\\left(\\frac{N - n(q_i) + 0.5}{n(q_i) + 0.5} + 1\\right)$; penalizing ubiquitous common words", "10.20.4 Document length normalization: parameter $b$ (typically 0.75) penalizing excessively long documents to prevent unfair length advantages", "10.20.5 BM25 formula derivation: $\\sum_{i=1}^m \\text{IDF}(q_i) \\cdot \\frac{f(q_i, D) \\cdot (k_1 + 1)}{f(q_i, D) + k_1 \\cdot (1 - b + b \\cdot \\frac{|D|}{\\text{avgdl}})}$", "10.20.6 Implementing BM25 from scratch: tokenization, stop-words, term-document posting lists, and document length tracking"]}'::jsonb, '["Explain how this implementation prevents: Failing to normalize document length ($b=0$), causing 50-page documents to dominate search results over concise 1-paragr", "How does BM25 Lexical Retrieval Mechanics & Inverted Indexes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-21', 'phase-10-lesson-21-reciprocal-rank-fusion-rrf-weighted-score', 'module-11', 21, 'Lesson 11.21: Reciprocal Rank Fusion (RRF) & Weighted Score Combination', 'Prerequisites: Lesson 10.19, Lesson 10.20', 'Prerequisites: Lesson 10.19, Lesson 10.20 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 1050.0, '# Lesson 10.21: Reciprocal Rank Fusion (RRF) & Weighted Score Combination

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.19, Lesson 10.20
- **Subtopics**:
  - `10.21.1` The score normalization challenge: dense cosine similarity ($[0, 1]$) and BM25 scores ($[0, \infty)$) live on non-comparable mathematical scales
  - `10.21.2` Min-Max score normalization pitfalls: extreme outliers skewing normalized distribution, making linear combinations unreliable
  - `10.21.3` Reciprocal Rank Fusion (RRF) algorithm (Cormack et al.): rank-based fusion agnostic to raw score distributions
  - `10.21.4` RRF mathematical formulation: $\text{RRF\_Score}(d) = \sum_{m \in M} \frac{1}{k + r_m(d)}$ where $r_m(d)$ is document rank in system $m$
  - `10.21.5` The smoothing constant $k$ (typically $k=60$): dampening the advantage of top-ranked items and stabilizing multi-list aggregation
  - `10.21.6` Weighted RRF: applying domain-specific weight coefficients ($w_{dense} \cdot \text{RRF}_{dense} + w_{sparse} \cdot \text{RRF}_{sparse}$)
- **Key Failure Modes & Edge Cases**: Directly adding raw BM25 score (42.5) to raw cosine similarity (0.82), completely erasing the influence of the vector score.
- **Verification & Mastery Check**: Implement Reciprocal Rank Fusion (RRF) combining top-50 dense and top-50 sparse search result lists into a unified ranked list.
- **Project Application**: DocuMind: RRF result fusion module.', '{"solution.py": "# Phase 10 // Lesson 10.21: Reciprocal Rank Fusion (RRF) & Weighted Score Combination\n\ndef solve():\n    \"\"\"\n    Verification: Implement Reciprocal Rank Fusion (RRF) combining top-50 dense and top-50 sparse search result lists \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.21", "subtopics_count": 6, "verification_criteria": "Implement Reciprocal Rank Fusion (RRF) combining top-50 dense and top-50 sparse search result lists into a unified ranked list.", "subtopics": ["10.21.1 The score normalization challenge: dense cosine similarity ($[0, 1]$) and BM25 scores ($[0, \\infty)$) live on non-comparable mathematical scales", "10.21.2 Min-Max score normalization pitfalls: extreme outliers skewing normalized distribution, making linear combinations unreliable", "10.21.3 Reciprocal Rank Fusion (RRF) algorithm (Cormack et al.): rank-based fusion agnostic to raw score distributions", "10.21.4 RRF mathematical formulation: $\\text{RRF\\_Score}(d) = \\sum_{m \\in M} \\frac{1}{k + r_m(d)}$ where $r_m(d)$ is document rank in system $m$", "10.21.5 The smoothing constant $k$ (typically $k=60$): dampening the advantage of top-ranked items and stabilizing multi-list aggregation", "10.21.6 Weighted RRF: applying domain-specific weight coefficients ($w_{dense} \\cdot \\text{RRF}_{dense} + w_{sparse} \\cdot \\text{RRF}_{sparse}$)"]}'::jsonb, '["Explain how this implementation prevents: Directly adding raw BM25 score (42.5) to raw cosine similarity (0.82), completely erasing the influence of the vector sc", "How does Reciprocal Rank Fusion (RRF) & Weighted Score Combination scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-22', 'phase-10-lesson-22-query-transformation-multi-query-sub-ques', 'module-11', 22, 'Lesson 11.22: Query Transformation: Multi-Query, Sub-Question Decomposition & HyDE', 'Prerequisites: Lesson 10.2, Lesson 10.19', 'Prerequisites: Lesson 10.2, Lesson 10.19 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 1100.0, '# Lesson 10.22: Query Transformation: Multi-Query, Sub-Question Decomposition & HyDE

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.2, Lesson 10.19
- **Subtopics**:
  - `10.22.1` Why raw user queries fail: ambiguous phrasing, colloquial language, multiple questions in one, or lack of domain keywords
  - `10.22.2` Query Rewriting: using an LLM to rewrite ambiguous conversational prompts into clear, self-contained standalone search queries
  - `10.22.3` Multi-Query Generation: generating 3-5 diverse semantic variations of the user prompt to execute parallel multi-vector retrieval
  - `10.22.4` Sub-Question Decomposition: breaking complex compound questions into individual atomic questions retrieved independently
  - `10.22.5` Hypothetical Document Embeddings (HyDE) (Gao et al.): prompting an LLM to generate a hypothetical ideal answer, then embedding the answer
  - `10.22.6` Why HyDE works: mapping from query space into document passage space, bridging the semantic gap between questions and answers
- **Key Failure Modes & Edge Cases**: Using HyDE for factual numerical lookups where the LLM''s hallucinated hypothetical numbers distort vector search away from real facts.
- **Verification & Mastery Check**: Implement an automated query transformation pipeline featuring Multi-Query generation, Sub-Question decomposition, and HyDE.
- **Project Application**: DocuMind: Query rewriting and transformation engine.', '{"solution.py": "# Phase 10 // Lesson 10.22: Query Transformation: Multi-Query, Sub-Question Decomposition & HyDE\n\ndef solve():\n    \"\"\"\n    Verification: Implement an automated query transformation pipeline featuring Multi-Query generation, Sub-Question \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.22", "subtopics_count": 6, "verification_criteria": "Implement an automated query transformation pipeline featuring Multi-Query generation, Sub-Question decomposition, and HyDE.", "subtopics": ["10.22.1 Why raw user queries fail: ambiguous phrasing, colloquial language, multiple questions in one, or lack of domain keywords", "10.22.2 Query Rewriting: using an LLM to rewrite ambiguous conversational prompts into clear, self-contained standalone search queries", "10.22.3 Multi-Query Generation: generating 3-5 diverse semantic variations of the user prompt to execute parallel multi-vector retrieval", "10.22.4 Sub-Question Decomposition: breaking complex compound questions into individual atomic questions retrieved independently", "10.22.5 Hypothetical Document Embeddings (HyDE) (Gao et al.): prompting an LLM to generate a hypothetical ideal answer, then embedding the answer", "10.22.6 Why HyDE works: mapping from query space into document passage space, bridging the semantic gap between questions and answers"]}'::jsonb, '["Explain how this implementation prevents: Using HyDE for factual numerical lookups where the LLM''s hallucinated hypothetical numbers distort vector search away fr", "How does Query Transformation: Multi-Query, Sub-Question Decomposition & HyDE scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-23', 'phase-10-lesson-23-query-routing-semantic-classification-int', 'module-11', 23, 'Lesson 11.23: Query Routing: Semantic Classification, Intent Detection & Tool Dispatch', 'Prerequisites: Lesson 10.3, Lesson 10.22', 'Prerequisites: Lesson 10.3, Lesson 10.22 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1150.0, '# Lesson 10.23: Query Routing: Semantic Classification, Intent Detection & Tool Dispatch

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.3, Lesson 10.22
- **Subtopics**:
  - `10.23.1` The multi-index enterprise reality: code repositories, customer tickets, financial tables, and general wikis needing different retrieval paths
  - `10.23.2` Query Routing architectures: determining which retrieval strategy, index, or external database is best suited for a user request
  - `10.23.3` LLM-based routing: passing prompt to a fast small model (e.g. Claude 3 Haiku / GPT-4o-mini) with structured classification outputs
  - `10.23.4` Semantic Router (embedding classification): computing cosine similarity between query embedding and pre-defined intent centroid clusters (<5ms)
  - `10.23.5` Direct answering bypass: routing greeting, small-talk, or pure reasoning queries directly to the LLM without triggering expensive RAG searches
  - `10.23.6` Multi-hop routing: dynamically chaining SQL queries, vector search, and web search for complex hybrid research questions
- **Key Failure Modes & Edge Cases**: Executing expensive hybrid RAG retrievals on simple conversational greetings like ''Hello, how are you today?''.
- **Verification & Mastery Check**: Build an ultra-fast semantic query router in Python classifying incoming prompts into vector search, SQL search, or direct LLM bypass.
- **Project Application**: DocuMind: Dynamic semantic query router.', '{"solution.py": "# Phase 10 // Lesson 10.23: Query Routing: Semantic Classification, Intent Detection & Tool Dispatch\n\ndef solve():\n    \"\"\"\n    Verification: Build an ultra-fast semantic query router in Python classifying incoming prompts into vector search,\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.23", "subtopics_count": 6, "verification_criteria": "Build an ultra-fast semantic query router in Python classifying incoming prompts into vector search, SQL search, or direct LLM bypass.", "subtopics": ["10.23.1 The multi-index enterprise reality: code repositories, customer tickets, financial tables, and general wikis needing different retrieval paths", "10.23.2 Query Routing architectures: determining which retrieval strategy, index, or external database is best suited for a user request", "10.23.3 LLM-based routing: passing prompt to a fast small model (e.g. Claude 3 Haiku / GPT-4o-mini) with structured classification outputs", "10.23.4 Semantic Router (embedding classification): computing cosine similarity between query embedding and pre-defined intent centroid clusters (<5ms)", "10.23.5 Direct answering bypass: routing greeting, small-talk, or pure reasoning queries directly to the LLM without triggering expensive RAG searches", "10.23.6 Multi-hop routing: dynamically chaining SQL queries, vector search, and web search for complex hybrid research questions"]}'::jsonb, '["Explain how this implementation prevents: Executing expensive hybrid RAG retrievals on simple conversational greetings like ''Hello, how are you today?''.", "How does Query Routing: Semantic Classification, Intent Detection & Tool Dispatch scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-24', 'phase-10-lesson-24-cross-encoder-re-ranking-architecture-pre', 'module-11', 24, 'Lesson 11.24: Cross-Encoder Re-Ranking: Architecture, Precision Gains & Latency', 'Prerequisites: Lesson 10.17, Lesson 10.21', 'Prerequisites: Lesson 10.17, Lesson 10.21 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 1200.0, '# Lesson 10.24: Cross-Encoder Re-Ranking: Architecture, Precision Gains & Latency

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.17, Lesson 10.21
- **Subtopics**:
  - `10.24.1` Bi-Encoders vs Cross-Encoders: independent sentence encoding ($f(q), f(d)$) vs joint token-level cross-attention ($f(q, d)$)
  - `10.24.2` Why Cross-Encoders achieve superior ranking precision: all tokens of the query directly attend to all tokens of the candidate passage
  - `10.24.3` The computational cost of Cross-Encoders: $O(N)$ full forward passes at query time; why Cross-Encoders cannot be pre-indexed into vector stores
  - `10.24.4` The Two-Stage Retrieval Architecture: Stage 1 (retrieve top-100 via fast hybrid Bi-Encoder/BM25) $\to$ Stage 2 (re-rank top-100 to top-5 via Cross-Encoder)
  - `10.24.5` Production Cross-Encoder models: Cohere Rerank v3, BAAI `bge-reranker-large`, and mixed-precision execution
  - `10.24.6` Latency budget management: batching re-ranking candidates and enforcing timeouts to keep total retrieval latency under 200ms
- **Key Failure Modes & Edge Cases**: Attempting to re-rank 2,000 candidate documents with a heavy Cross-Encoder, blowing the API response latency budget past 5 seconds.
- **Verification & Mastery Check**: Implement a Two-Stage retrieval pipeline: retrieve 50 candidates via hybrid search, re-rank to top-5 via Cross-Encoder, measure MRR improvements.
- **Project Application**: DocuMind: Two-stage retrieval and cross-encoder re-ranking pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.24: Cross-Encoder Re-Ranking: Architecture, Precision Gains & Latency\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Two-Stage retrieval pipeline: retrieve 50 candidates via hybrid search, re-rank to top-5\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.24", "subtopics_count": 6, "verification_criteria": "Implement a Two-Stage retrieval pipeline: retrieve 50 candidates via hybrid search, re-rank to top-5 via Cross-Encoder, measure MRR improvements.", "subtopics": ["10.24.1 Bi-Encoders vs Cross-Encoders: independent sentence encoding ($f(q), f(d)$) vs joint token-level cross-attention ($f(q, d)$)", "10.24.2 Why Cross-Encoders achieve superior ranking precision: all tokens of the query directly attend to all tokens of the candidate passage", "10.24.3 The computational cost of Cross-Encoders: $O(N)$ full forward passes at query time; why Cross-Encoders cannot be pre-indexed into vector stores", "10.24.4 The Two-Stage Retrieval Architecture: Stage 1 (retrieve top-100 via fast hybrid Bi-Encoder/BM25) $\\to$ Stage 2 (re-rank top-100 to top-5 via Cross-Encoder)", "10.24.5 Production Cross-Encoder models: Cohere Rerank v3, BAAI `bge-reranker-large`, and mixed-precision execution", "10.24.6 Latency budget management: batching re-ranking candidates and enforcing timeouts to keep total retrieval latency under 200ms"]}'::jsonb, '["Explain how this implementation prevents: Attempting to re-rank 2,000 candidate documents with a heavy Cross-Encoder, blowing the API response latency budget past", "How does Cross-Encoder Re-Ranking: Architecture, Precision Gains & Latency scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-25', 'phase-10-lesson-25-context-compression-prompt-filtering-extr', 'module-11', 25, 'Lesson 11.25: Context Compression & Prompt Filtering: Extractive Summarization & LLMLingua', 'Prerequisites: Lesson 10.4, Lesson 10.24', 'Prerequisites: Lesson 10.4, Lesson 10.24 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 1250.0, '# Lesson 10.25: Context Compression & Prompt Filtering: Extractive Summarization & LLMLingua

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.4, Lesson 10.24
- **Subtopics**:
  - `10.25.1` The bloated context problem: re-ranked chunks still containing irrelevant sentences that inflate token costs and degrade LLM reasoning
  - `10.25.2` Extractive sentence compression: scoring individual sentences within retrieved chunks and pruning sentences below relevance thresholds
  - `10.25.3` LLMLingua (Microsoft Research): using small language models (e.g. LLaMA-2-7B) to compute token perplexity and compress prompts by up to 5x
  - `10.25.4` Token pruning mechanics: removing redundant structural tokens, whitespace, and low-information words while preserving semantic integrity
  - `10.25.5` Information density optimization: formatting retrieved context with clean XML tags (`<doc id=''1''>...</doc>`) for optimal model parsing
  - `10.25.6` Context deduplication: identifying and collapsing overlapping paragraphs from different retrieved documents
- **Key Failure Modes & Edge Cases**: Aggressive context compression stripping critical negation words (''not'', ''never''), reversing the factual meaning of retrieved policies.
- **Verification & Mastery Check**: Integrate LLMLingua prompt compression into a RAG pipeline; compress retrieved context by 40% while maintaining 100% answer accuracy.
- **Project Application**: DocuMind: Context compression and token pruning module.', '{"solution.py": "# Phase 10 // Lesson 10.25: Context Compression & Prompt Filtering: Extractive Summarization & LLMLingua\n\ndef solve():\n    \"\"\"\n    Verification: Integrate LLMLingua prompt compression into a RAG pipeline; compress retrieved context by 40% while \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.25", "subtopics_count": 6, "verification_criteria": "Integrate LLMLingua prompt compression into a RAG pipeline; compress retrieved context by 40% while maintaining 100% answer accuracy.", "subtopics": ["10.25.1 The bloated context problem: re-ranked chunks still containing irrelevant sentences that inflate token costs and degrade LLM reasoning", "10.25.2 Extractive sentence compression: scoring individual sentences within retrieved chunks and pruning sentences below relevance thresholds", "10.25.3 LLMLingua (Microsoft Research): using small language models (e.g. LLaMA-2-7B) to compute token perplexity and compress prompts by up to 5x", "10.25.4 Token pruning mechanics: removing redundant structural tokens, whitespace, and low-information words while preserving semantic integrity", "10.25.5 Information density optimization: formatting retrieved context with clean XML tags (`<doc id=''1''>...</doc>`) for optimal model parsing", "10.25.6 Context deduplication: identifying and collapsing overlapping paragraphs from different retrieved documents"]}'::jsonb, '["Explain how this implementation prevents: Aggressive context compression stripping critical negation words (''not'', ''never''), reversing the factual meaning of retr", "How does Context Compression & Prompt Filtering: Extractive Summarization & LLMLingua scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
