INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-8-6', 'phase-08-lesson-06-api-gateway-architectures-rate-limiting-a', 'module-9', 6, 'Lesson 9.6: API Gateway Architectures, Rate Limiting & Aggregation', 'Prerequisites: Phase 4, Lesson 8.5', 'Prerequisites: Phase 4, Lesson 8.5 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 300.0, '# Lesson 8.6: API Gateway Architectures, Rate Limiting & Aggregation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 8.5
- **Subtopics**:
  - `8.6.1` API Gateway responsibilities: request routing, protocol translation (gRPC to JSON), authentication, and telemetry
  - `8.6.2` Backend-For-Frontend (BFF) pattern: tailored API gateways for mobile, web, and public developer clients
  - `8.6.3` Distributed Rate Limiting algorithms: Token Bucket, Leaky Bucket, Sliding Window Counter with Redis and Lua scripts
  - `8.6.4` Distributed rate limiting synchronization: centralized Redis vs local memory with gossip protocol synchronization
  - `8.6.5` Request aggregation and batching: combining multiple microservice calls into single client responses to reduce latency
  - `8.6.6` Security controls at the gateway: IP whitelisting, geo-blocking, DDoS mitigation, and WAF rule evaluation
- **Key Failure Modes & Edge Cases**: Centralized Redis rate limiter creating a single point of failure and adding 10ms latency overhead to every API request.
- **Verification & Mastery Check**: Implement a sliding window counter rate limiter in Redis Lua script handling 50,000 concurrent requests with zero race conditions.
- **Project Application**: System Design Portfolio: Enterprise API Gateway and rate limiting architecture.', '{"solution.py": "# Phase 8 // Lesson 8.6: API Gateway Architectures, Rate Limiting & Aggregation\n\ndef solve():\n    \"\"\"\n    Verification: Implement a sliding window counter rate limiter in Redis Lua script handling 50,000 concurrent reque\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.6", "subtopics_count": 6, "verification_criteria": "Implement a sliding window counter rate limiter in Redis Lua script handling 50,000 concurrent requests with zero race conditions.", "subtopics": ["8.6.1 API Gateway responsibilities: request routing, protocol translation (gRPC to JSON), authentication, and telemetry", "8.6.2 Backend-For-Frontend (BFF) pattern: tailored API gateways for mobile, web, and public developer clients", "8.6.3 Distributed Rate Limiting algorithms: Token Bucket, Leaky Bucket, Sliding Window Counter with Redis and Lua scripts", "8.6.4 Distributed rate limiting synchronization: centralized Redis vs local memory with gossip protocol synchronization", "8.6.5 Request aggregation and batching: combining multiple microservice calls into single client responses to reduce latency", "8.6.6 Security controls at the gateway: IP whitelisting, geo-blocking, DDoS mitigation, and WAF rule evaluation"]}'::jsonb, '["Explain how this implementation prevents: Centralized Redis rate limiter creating a single point of failure and adding 10ms latency overhead to every API request.", "How does API Gateway Architectures, Rate Limiting & Aggregation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-7', 'phase-08-lesson-07-message-queues-vs-event-streams-decouplin', 'module-9', 7, 'Lesson 9.7: Message Queues vs Event Streams: Decoupling Asynchronous Systems', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 350.0, '# Lesson 8.7: Message Queues vs Event Streams: Decoupling Asynchronous Systems

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `8.7.1` Queue-based messaging (RabbitMQ, SQS): push model, message acknowledgment, individual message consumption, worker pools
  - `8.7.2` Log-based event streaming (Kafka, Kinesis): pull model, partitioned commit logs, ordered replayability, consumer groups
  - `8.7.3` Choosing between Queues and Streams: complex routing/task distribution vs high-throughput real-time event analytics
  - `8.7.4` Message delivery guarantees: At-most-once, At-least-once, Exactly-once processing (idempotent consumers)
  - `8.7.5` Dead Letter Queues (DLQ) and retry backoff strategies: handling poisoned messages without blocking queue pipelines
  - `8.7.6` Event-driven architecture patterns: Event Sourcing, Command Query Responsibility Segregation (CQRS), and Saga choreography
- **Key Failure Modes & Edge Cases**: Using a message queue as a permanent database without understanding broker storage limits and memory backpressure.
- **Verification & Mastery Check**: Design an end-to-end asynchronous order processing architecture comparing RabbitMQ task queues with Kafka event streaming.
- **Project Application**: System Design Portfolio: Asynchronous event messaging blueprints.', '{"solution.py": "# Phase 8 // Lesson 8.7: Message Queues vs Event Streams: Decoupling Asynchronous Systems\n\ndef solve():\n    \"\"\"\n    Verification: Design an end-to-end asynchronous order processing architecture comparing RabbitMQ task queues with \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.7", "subtopics_count": 6, "verification_criteria": "Design an end-to-end asynchronous order processing architecture comparing RabbitMQ task queues with Kafka event streaming.", "subtopics": ["8.7.1 Queue-based messaging (RabbitMQ, SQS): push model, message acknowledgment, individual message consumption, worker pools", "8.7.2 Log-based event streaming (Kafka, Kinesis): pull model, partitioned commit logs, ordered replayability, consumer groups", "8.7.3 Choosing between Queues and Streams: complex routing/task distribution vs high-throughput real-time event analytics", "8.7.4 Message delivery guarantees: At-most-once, At-least-once, Exactly-once processing (idempotent consumers)", "8.7.5 Dead Letter Queues (DLQ) and retry backoff strategies: handling poisoned messages without blocking queue pipelines", "8.7.6 Event-driven architecture patterns: Event Sourcing, Command Query Responsibility Segregation (CQRS), and Saga choreography"]}'::jsonb, '["Explain how this implementation prevents: Using a message queue as a permanent database without understanding broker storage limits and memory backpressure.", "How does Message Queues vs Event Streams: Decoupling Asynchronous Systems scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-8', 'phase-08-lesson-08-database-sharding-partitioning-rebalancin', 'module-9', 8, 'Lesson 9.8: Database Sharding, Partitioning & Rebalancing Strategies', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 400.0, '# Lesson 8.8: Database Sharding, Partitioning & Rebalancing Strategies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `8.8.1` Vertical partitioning (splitting columns) vs Horizontal partitioning / Sharding (splitting rows across machines)
  - `8.8.2` Sharding key selection: cardinality, query access patterns, avoiding hot spots (celebrity problem)
  - `8.8.3` Sharding strategies: Range-based sharding vs Hash-based sharding vs Directory-based (lookup table) sharding
  - `8.8.4` Consistent Hashing in database sharding: minimizing data movement during node additions and removals
  - `8.8.5` Cross-shard queries and joins: scatter-gather queries, two-phase commit over shards, and why cross-shard joins are anti-patterns
  - `8.8.6` Live sharding rebalancing: migrating partitions online without downtime using dual-writes and asynchronous reconciliation
- **Key Failure Modes & Edge Cases**: Selecting a monotonically increasing auto-increment ID as sharding key, concentrating 100% of all write traffic on the latest single shard.
- **Verification & Mastery Check**: Implement a consistent hashing sharding manager in Python mapping keys across 16 database shards with virtual node balancing.
- **Project Application**: System Design Portfolio: Scalable database sharding architecture.', '{"solution.py": "# Phase 8 // Lesson 8.8: Database Sharding, Partitioning & Rebalancing Strategies\n\ndef solve():\n    \"\"\"\n    Verification: Implement a consistent hashing sharding manager in Python mapping keys across 16 database shards wit\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.8", "subtopics_count": 6, "verification_criteria": "Implement a consistent hashing sharding manager in Python mapping keys across 16 database shards with virtual node balancing.", "subtopics": ["8.8.1 Vertical partitioning (splitting columns) vs Horizontal partitioning / Sharding (splitting rows across machines)", "8.8.2 Sharding key selection: cardinality, query access patterns, avoiding hot spots (celebrity problem)", "8.8.3 Sharding strategies: Range-based sharding vs Hash-based sharding vs Directory-based (lookup table) sharding", "8.8.4 Consistent Hashing in database sharding: minimizing data movement during node additions and removals", "8.8.5 Cross-shard queries and joins: scatter-gather queries, two-phase commit over shards, and why cross-shard joins are anti-patterns", "8.8.6 Live sharding rebalancing: migrating partitions online without downtime using dual-writes and asynchronous reconciliation"]}'::jsonb, '["Explain how this implementation prevents: Selecting a monotonically increasing auto-increment ID as sharding key, concentrating 100% of all write traffic on the l", "How does Database Sharding, Partitioning & Rebalancing Strategies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-9', 'phase-08-lesson-09-high-availability-redundancy-active-activ', 'module-9', 9, 'Lesson 9.9: High Availability, Redundancy & Active-Active Failover', 'Prerequisites: Phase 7, Lesson 8.8', 'Prerequisites: Phase 7, Lesson 8.8 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 450.0, '# Lesson 8.9: High Availability, Redundancy & Active-Active Failover

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 8.8
- **Subtopics**:
  - `8.9.1` High Availability (HA) metrics: 99.9% (Three Nines, 8.76h downtime/yr) vs 99.999% (Five Nines, 5.26m downtime/yr)
  - `8.9.2` Redundancy models: Active-Passive (Warm/Cold standby) vs Active-Active multi-region deployment architectures
  - `8.9.3` Automated failover mechanics: health heartbeats, split-brain detection, fencing tokens, and DNS TTL considerations
  - `8.9.4` Active-Active data synchronization: conflict-free replication, asynchronous cross-region replication, and multi-master conflicts
  - `8.9.5` GeoDNS and Latency-based Anycast routing: steering global users dynamically to healthy regions during catastrophic disasters
  - `8.9.6` Designing for disaster recovery: mean time to detect (MTTD), mean time to recover (MTTR), and chaos game days
- **Key Failure Modes & Edge Cases**: Split-brain condition causing two active masters in different datacenters to accept conflicting writes during network partition.
- **Verification & Mastery Check**: Draft an Active-Active multi-region architecture diagram with failover runbooks and split-brain fencing token safety proofs.
- **Project Application**: System Design Portfolio: Global multi-region high-availability blueprint.', '{"solution.py": "# Phase 8 // Lesson 8.9: High Availability, Redundancy & Active-Active Failover\n\ndef solve():\n    \"\"\"\n    Verification: Draft an Active-Active multi-region architecture diagram with failover runbooks and split-brain fenc\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.9", "subtopics_count": 6, "verification_criteria": "Draft an Active-Active multi-region architecture diagram with failover runbooks and split-brain fencing token safety proofs.", "subtopics": ["8.9.1 High Availability (HA) metrics: 99.9% (Three Nines, 8.76h downtime/yr) vs 99.999% (Five Nines, 5.26m downtime/yr)", "8.9.2 Redundancy models: Active-Passive (Warm/Cold standby) vs Active-Active multi-region deployment architectures", "8.9.3 Automated failover mechanics: health heartbeats, split-brain detection, fencing tokens, and DNS TTL considerations", "8.9.4 Active-Active data synchronization: conflict-free replication, asynchronous cross-region replication, and multi-master conflicts", "8.9.5 GeoDNS and Latency-based Anycast routing: steering global users dynamically to healthy regions during catastrophic disasters", "8.9.6 Designing for disaster recovery: mean time to detect (MTTD), mean time to recover (MTTR), and chaos game days"]}'::jsonb, '["Explain how this implementation prevents: Split-brain condition causing two active masters in different datacenters to accept conflicting writes during network pa", "How does High Availability, Redundancy & Active-Active Failover scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-10', 'phase-08-lesson-10-unique-id-generation-at-scale-snowflake-u', 'module-9', 10, 'Lesson 9.10: Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers', 'Prerequisites: Phase 0, Phase 7', 'Prerequisites: Phase 0, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 500.0, '# Lesson 8.10: Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 7
- **Subtopics**:
  - `8.10.1` Unique ID requirements: 64-bit size, globally unique, roughly time-ordered, high generation throughput (>1M IDs/sec)
  - `8.10.2` UUIDv4 limitations: 128-bit size, completely random ordering causing catastrophic B-tree fragmentation and index bloat
  - `8.10.3` UUIDv7 modern standard: Unix timestamp prefix + random suffix combining time-ordering with standard 128-bit formats
  - `8.10.4` Flickr Ticket Server: centralized MySQL servers with auto-increment and `REPLACE INTO` statements (single point of failure risks)
  - `8.10.5` Twitter Snowflake architecture: 1-bit unused, 41-bit timestamp (epoch ms), 10-bit machine/worker ID, 12-bit sequence number
  - `8.10.6` Handling clock drift in Snowflake: NTP backwards time adjustments, refusing generation, or waiting for clock synchronization
- **Key Failure Modes & Edge Cases**: Server clock moving backwards during NTP sync generating duplicate IDs in Twitter Snowflake algorithm without drift safeguards.
- **Verification & Mastery Check**: Implement a fully functional Twitter Snowflake 64-bit ID generator in Python handling 4,096 IDs per millisecond with clock rollback checks.
- **Project Application**: System Design Portfolio: Distributed ID generation system design.', '{"solution.py": "# Phase 8 // Lesson 8.10: Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers\n\ndef solve():\n    \"\"\"\n    Verification: Implement a fully functional Twitter Snowflake 64-bit ID generator in Python handling 4,096 IDs per \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.10", "subtopics_count": 6, "verification_criteria": "Implement a fully functional Twitter Snowflake 64-bit ID generator in Python handling 4,096 IDs per millisecond with clock rollback checks.", "subtopics": ["8.10.1 Unique ID requirements: 64-bit size, globally unique, roughly time-ordered, high generation throughput (>1M IDs/sec)", "8.10.2 UUIDv4 limitations: 128-bit size, completely random ordering causing catastrophic B-tree fragmentation and index bloat", "8.10.3 UUIDv7 modern standard: Unix timestamp prefix + random suffix combining time-ordering with standard 128-bit formats", "8.10.4 Flickr Ticket Server: centralized MySQL servers with auto-increment and `REPLACE INTO` statements (single point of failure risks)", "8.10.5 Twitter Snowflake architecture: 1-bit unused, 41-bit timestamp (epoch ms), 10-bit machine/worker ID, 12-bit sequence number", "8.10.6 Handling clock drift in Snowflake: NTP backwards time adjustments, refusing generation, or waiting for clock synchronization"]}'::jsonb, '["Explain how this implementation prevents: Server clock moving backwards during NTP sync generating duplicate IDs in Twitter Snowflake algorithm without drift safe", "How does Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-11', 'phase-08-lesson-11-system-deep-dive-1-global-url-shortener-t', 'module-9', 11, 'Lesson 9.11: System Deep Dive 1: Global URL Shortener (TinyURL / Bitly)', 'Prerequisites: Lesson 8.1, Lesson 8.10', 'Prerequisites: Lesson 8.1, Lesson 8.10 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 550.0, '# Lesson 8.11: System Deep Dive 1: Global URL Shortener (TinyURL / Bitly)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.1, Lesson 8.10
- **Subtopics**:
  - `8.11.1` Requirements: 100M URLs created/month, 100:1 read-to-write ratio, sub-10ms redirection latency, custom alias support
  - `8.11.2` Capacity estimation: 100M writes/month $\approx 40$ write QPS, 4,000 read QPS; 5-year storage: $\approx 15\text{TB}$
  - `8.11.3` URL encoding algorithms: Base62 encoding (a-z, A-Z, 0-9) vs MD5/SHA256 hashing truncation with collision handling
  - `8.11.4` Pre-generated Key Generation Service (KGS): dedicated service generating unique Base62 tokens ahead of time into Redis/DB
  - `8.11.5` Data modeling: relational vs NoSQL schema, primary keys, indexing short URL tokens, and expiration timestamps
  - `8.11.6` High-performance redirection: HTTP 301 Permanent Redirect (client caching) vs HTTP 302 Temporary Redirect (telemetry tracking)
- **Key Failure Modes & Edge Cases**: Using HTTP 301 preventing server-side click analytics tracking; MD5 hash collisions requiring expensive database retry loops.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for TinyURL featuring KGS token generation, Redis caching, and Cassandra storage.
- **Project Application**: System Design Portfolio: Project 1 - Global URL Shortener.', '{"solution.py": "# Phase 8 // Lesson 8.11: System Deep Dive 1: Global URL Shortener (TinyURL / Bitly)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for TinyURL featuring KGS token generation, Redis caching\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.11", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for TinyURL featuring KGS token generation, Redis caching, and Cassandra storage.", "subtopics": ["8.11.1 Requirements: 100M URLs created/month, 100:1 read-to-write ratio, sub-10ms redirection latency, custom alias support", "8.11.2 Capacity estimation: 100M writes/month $\\approx 40$ write QPS, 4,000 read QPS; 5-year storage: $\\approx 15\\text{TB}$", "8.11.3 URL encoding algorithms: Base62 encoding (a-z, A-Z, 0-9) vs MD5/SHA256 hashing truncation with collision handling", "8.11.4 Pre-generated Key Generation Service (KGS): dedicated service generating unique Base62 tokens ahead of time into Redis/DB", "8.11.5 Data modeling: relational vs NoSQL schema, primary keys, indexing short URL tokens, and expiration timestamps", "8.11.6 High-performance redirection: HTTP 301 Permanent Redirect (client caching) vs HTTP 302 Temporary Redirect (telemetry tracking)"]}'::jsonb, '["Explain how this implementation prevents: Using HTTP 301 preventing server-side click analytics tracking; MD5 hash collisions requiring expensive database retry l", "How does System Deep Dive 1: Global URL Shortener (TinyURL / Bitly) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-12', 'phase-08-lesson-12-system-deep-dive-2-high-throughput-distri', 'module-9', 12, 'Lesson 9.12: System Deep Dive 2: High-Throughput Distributed Rate Limiter', 'Prerequisites: Lesson 8.6, Lesson 8.10', 'Prerequisites: Lesson 8.6, Lesson 8.10 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 600.0, '# Lesson 8.12: System Deep Dive 2: High-Throughput Distributed Rate Limiter

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.6, Lesson 8.10
- **Subtopics**:
  - `8.12.1` Requirements: protect APIs from DDoS and abuse, enforce multi-tier tenant quotas, sub-2ms latency overhead
  - `8.12.2` Capacity estimation: 1,000,000 requests/second global API ingress; tracking millions of unique client IP/API keys
  - `8.12.3` Algorithm trade-offs: Token Bucket vs Sliding Window Counter vs Leaky Bucket across high concurrency
  - `8.12.4` Distributed architecture: Edge API gateways with local caching + central Redis clusters using pipelined Lua scripts
  - `8.12.5` Race condition mitigation: eliminating check-then-set race conditions using atomic Redis Lua scripts
  - `8.12.6` Handling Redis cluster outages: failing open (allowing traffic) vs failing closed (blocking traffic) under security SLAs
- **Key Failure Modes & Edge Cases**: Failing closed during rate limiter redis outage, taking down entire company API for all legitimate paying customers.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for an enterprise rate limiter handling 1M QPS with localized synchronization.
- **Project Application**: System Design Portfolio: Project 2 - Distributed Rate Limiter.', '{"solution.py": "# Phase 8 // Lesson 8.12: System Deep Dive 2: High-Throughput Distributed Rate Limiter\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for an enterprise rate limiter handling 1M QPS with local\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.12", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for an enterprise rate limiter handling 1M QPS with localized synchronization.", "subtopics": ["8.12.1 Requirements: protect APIs from DDoS and abuse, enforce multi-tier tenant quotas, sub-2ms latency overhead", "8.12.2 Capacity estimation: 1,000,000 requests/second global API ingress; tracking millions of unique client IP/API keys", "8.12.3 Algorithm trade-offs: Token Bucket vs Sliding Window Counter vs Leaky Bucket across high concurrency", "8.12.4 Distributed architecture: Edge API gateways with local caching + central Redis clusters using pipelined Lua scripts", "8.12.5 Race condition mitigation: eliminating check-then-set race conditions using atomic Redis Lua scripts", "8.12.6 Handling Redis cluster outages: failing open (allowing traffic) vs failing closed (blocking traffic) under security SLAs"]}'::jsonb, '["Explain how this implementation prevents: Failing closed during rate limiter redis outage, taking down entire company API for all legitimate paying customers.", "How does System Deep Dive 2: High-Throughput Distributed Rate Limiter scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-13', 'phase-08-lesson-13-system-deep-dive-3-distributed-web-crawle', 'module-9', 13, 'Lesson 9.13: System Deep Dive 3: Distributed Web Crawler & Indexer', 'Prerequisites: Lesson 8.3, Lesson 8.7', 'Prerequisites: Lesson 8.3, Lesson 8.7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 650.0, '# Lesson 8.13: System Deep Dive 3: Distributed Web Crawler & Indexer

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.3, Lesson 8.7
- **Subtopics**:
  - `8.13.1` Requirements: crawl 1 billion web pages per month, respect robots.txt, avoid infinite crawl traps, extract links and text
  - `8.13.2` Capacity estimation: 1B pages/month $\approx 400$ pages/sec; storing raw HTML (100TB/month), inverted index extraction
  - `8.13.3` Crawl frontier architecture: prioritized queues, politeness queues (per-host rate limiting), and DNS caching layer
  - `8.13.4` Duplicate URL detection: Fingerprinting web page content using SimHash and 64-bit Bloom filters for billions of URLs
  - `8.13.5` Distributed worker architecture: stateless crawler pods, distributed task scheduling via Kafka, and S3 object storage ingestion
  - `8.13.6` Parsing & extraction pipeline: headless browser rendering (for JS-rendered SPAs) vs lightweight HTTP parsing trade-offs
- **Key Failure Modes & Edge Cases**: Getting caught in infinite calendar crawl traps (`/calendar?day=X+1`); overloading small web servers violating politeness rules.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for a distributed web crawler crawling 1B pages with SimHash deduplication.
- **Project Application**: System Design Portfolio: Project 3 - Distributed Web Crawler.', '{"solution.py": "# Phase 8 // Lesson 8.13: System Deep Dive 3: Distributed Web Crawler & Indexer\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for a distributed web crawler crawling 1B pages with SimH\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.13", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for a distributed web crawler crawling 1B pages with SimHash deduplication.", "subtopics": ["8.13.1 Requirements: crawl 1 billion web pages per month, respect robots.txt, avoid infinite crawl traps, extract links and text", "8.13.2 Capacity estimation: 1B pages/month $\\approx 400$ pages/sec; storing raw HTML (100TB/month), inverted index extraction", "8.13.3 Crawl frontier architecture: prioritized queues, politeness queues (per-host rate limiting), and DNS caching layer", "8.13.4 Duplicate URL detection: Fingerprinting web page content using SimHash and 64-bit Bloom filters for billions of URLs", "8.13.5 Distributed worker architecture: stateless crawler pods, distributed task scheduling via Kafka, and S3 object storage ingestion", "8.13.6 Parsing & extraction pipeline: headless browser rendering (for JS-rendered SPAs) vs lightweight HTTP parsing trade-offs"]}'::jsonb, '["Explain how this implementation prevents: Getting caught in infinite calendar crawl traps (`/calendar?day=X+1`); overloading small web servers violating politenes", "How does System Deep Dive 3: Distributed Web Crawler & Indexer scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-14', 'phase-08-lesson-14-system-deep-dive-4-real-time-social-media', 'module-9', 14, 'Lesson 9.14: System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X)', 'Prerequisites: Lesson 8.4, Lesson 8.7', 'Prerequisites: Lesson 8.4, Lesson 8.7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 700.0, '# Lesson 8.14: System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.4, Lesson 8.7
- **Subtopics**:
  - `8.14.1` Requirements: 500M DAU, post tweets, follow users, generate timeline news feeds, real-time fanout
  - `8.14.2` Capacity estimation: 500M DAU, 5,000 tweets/sec average, 25,000 peak; timeline reads 500,000 QPS
  - `8.14.3` Fanout-on-Write (Push model): writing tweet IDs directly into followers'' Redis home timeline lists upon post
  - `8.14.4` Fanout-on-Read (Pull model): fetching and merging tweets dynamically when a user requests their timeline
  - `8.14.5` The Celebrity / Hotspot Problem: why Push models fail for users with 100M followers (Taylor Swift, Elon Musk)
  - `8.14.6` Hybrid Fanout Architecture: Push for standard users, Pull for high-follower celebrity accounts, merged at read time
- **Key Failure Modes & Edge Cases**: Attempting Push fanout on a 100M follower user causing 10-minute fanout processing lag and overwhelming Redis cluster queues.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for Twitter''s news feed using hybrid push/pull fanout and Redis caching.
- **Project Application**: System Design Portfolio: Project 4 - Social Media News Feed.', '{"solution.py": "# Phase 8 // Lesson 8.14: System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for Twitter''s news feed using hybrid push/pull fanout and\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.14", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for Twitter''s news feed using hybrid push/pull fanout and Redis caching.", "subtopics": ["8.14.1 Requirements: 500M DAU, post tweets, follow users, generate timeline news feeds, real-time fanout", "8.14.2 Capacity estimation: 500M DAU, 5,000 tweets/sec average, 25,000 peak; timeline reads 500,000 QPS", "8.14.3 Fanout-on-Write (Push model): writing tweet IDs directly into followers'' Redis home timeline lists upon post", "8.14.4 Fanout-on-Read (Pull model): fetching and merging tweets dynamically when a user requests their timeline", "8.14.5 The Celebrity / Hotspot Problem: why Push models fail for users with 100M followers (Taylor Swift, Elon Musk)", "8.14.6 Hybrid Fanout Architecture: Push for standard users, Pull for high-follower celebrity accounts, merged at read time"]}'::jsonb, '["Explain how this implementation prevents: Attempting Push fanout on a 100M follower user causing 10-minute fanout processing lag and overwhelming Redis cluster qu", "How does System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-15', 'phase-08-lesson-15-system-deep-dive-5-global-real-time-chat-', 'module-9', 15, 'Lesson 9.15: System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack)', 'Prerequisites: Lesson 8.5, Lesson 8.7', 'Prerequisites: Lesson 8.5, Lesson 8.7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 750.0, '# Lesson 8.15: System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.5, Lesson 8.7
- **Subtopics**:
  - `8.15.1` Requirements: 1-on-1 chat, group chat (up to 1,000 users), read receipts, offline message storage, end-to-end encryption (E2EE)
  - `8.15.2` Capacity estimation: 2B users, 100B messages/day $\approx 1.15\text{M}$ messages/sec; peak 3M msgs/sec
  - `8.15.3` Connection management: maintaining persistent bidirectional WebSocket / TCP connections across millions of chat gateways
  - `8.15.4` Session Service and User-to-Gateway mapping: tracking which gateway holds the active socket for user $X$ via Redis
  - `8.15.5` Message delivery workflow: online routing through gateways vs offline message persistence in Cassandra / DynamoDB
  - `8.15.6` Group chat fanout: server-side fanout queues vs client-side individual sends, managing group state and message ordering
- **Key Failure Modes & Edge Cases**: Chat servers crashing and disconnecting 500,000 active WebSockets simultaneously, triggering a catastrophic reconnection storm.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for a global chat platform supporting 2B users with WebSocket connection servers.
- **Project Application**: System Design Portfolio: Project 5 - Real-Time Chat Platform.', '{"solution.py": "# Phase 8 // Lesson 8.15: System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for a global chat platform supporting 2B users with WebSo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.15", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for a global chat platform supporting 2B users with WebSocket connection servers.", "subtopics": ["8.15.1 Requirements: 1-on-1 chat, group chat (up to 1,000 users), read receipts, offline message storage, end-to-end encryption (E2EE)", "8.15.2 Capacity estimation: 2B users, 100B messages/day $\\approx 1.15\\text{M}$ messages/sec; peak 3M msgs/sec", "8.15.3 Connection management: maintaining persistent bidirectional WebSocket / TCP connections across millions of chat gateways", "8.15.4 Session Service and User-to-Gateway mapping: tracking which gateway holds the active socket for user $X$ via Redis", "8.15.5 Message delivery workflow: online routing through gateways vs offline message persistence in Cassandra / DynamoDB", "8.15.6 Group chat fanout: server-side fanout queues vs client-side individual sends, managing group state and message ordering"]}'::jsonb, '["Explain how this implementation prevents: Chat servers crashing and disconnecting 500,000 active WebSockets simultaneously, triggering a catastrophic reconnection", "How does System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-16', 'phase-08-lesson-16-system-deep-dive-6-large-scale-video-stre', 'module-9', 16, 'Lesson 9.16: System Deep Dive 6: Large-Scale Video Streaming Platform (YouTube / Netflix)', 'Prerequisites: Lesson 8.5, Lesson 8.8', 'Prerequisites: Lesson 8.5, Lesson 8.8 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 800.0, '# Lesson 8.16: System Deep Dive 6: Large-Scale Video Streaming Platform (YouTube / Netflix)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.5, Lesson 8.8
- **Subtopics**:
  - `8.16.1` Requirements: upload videos, automated multi-bitrate transcoding, adaptive streaming playback (HLS, DASH), search, comments
  - `8.16.2` Capacity estimation: 500 hours uploaded/minute; storage: petabytes/day; egress bandwidth: tens of Terabits/second
  - `8.16.3` Video ingestion pipeline: chunked multipart upload directly to object storage (S3/GCS) with presigned URLs
  - `8.16.4` Transcoding architecture: distributed DAG worker pools splitting videos into chunks, encoding (H.264, AV1) at multiple resolutions
  - `8.16.5` Adaptive Bitrate Streaming (ABR): HLS `.m3u8` master playlists, segment delivery (`.ts` / `.m4s`), client-driven bitrate adaptation
  - `8.16.6` Content Delivery Network (CDN) strategy: tiered caching (edge POPs, regional mid-tier caches, origin shields) and Open Connect appliances
- **Key Failure Modes & Edge Cases**: Transcoding jobs stalling on massive 4K video files without chunked parallel processing; origin servers melted by CDN cache misses.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for video ingestion, parallel transcoding pipelines, and multi-CDN edge delivery.
- **Project Application**: System Design Portfolio: Project 6 - Video Streaming Architecture.', '{"solution.py": "# Phase 8 // Lesson 8.16: System Deep Dive 6: Large-Scale Video Streaming Platform (YouTube / Netflix)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for video ingestion, parallel transcoding pipelines, and \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.16", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for video ingestion, parallel transcoding pipelines, and multi-CDN edge delivery.", "subtopics": ["8.16.1 Requirements: upload videos, automated multi-bitrate transcoding, adaptive streaming playback (HLS, DASH), search, comments", "8.16.2 Capacity estimation: 500 hours uploaded/minute; storage: petabytes/day; egress bandwidth: tens of Terabits/second", "8.16.3 Video ingestion pipeline: chunked multipart upload directly to object storage (S3/GCS) with presigned URLs", "8.16.4 Transcoding architecture: distributed DAG worker pools splitting videos into chunks, encoding (H.264, AV1) at multiple resolutions", "8.16.5 Adaptive Bitrate Streaming (ABR): HLS `.m3u8` master playlists, segment delivery (`.ts` / `.m4s`), client-driven bitrate adaptation", "8.16.6 Content Delivery Network (CDN) strategy: tiered caching (edge POPs, regional mid-tier caches, origin shields) and Open Connect appliances"]}'::jsonb, '["Explain how this implementation prevents: Transcoding jobs stalling on massive 4K video files without chunked parallel processing; origin servers melted by CDN ca", "How does System Deep Dive 6: Large-Scale Video Streaming Platform (YouTube / Netflix) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-17', 'phase-08-lesson-17-system-deep-dive-7-distributed-cloud-obje', 'module-9', 17, 'Lesson 9.17: System Deep Dive 7: Distributed Cloud Object Storage (Amazon S3 / Google Cloud Storage)', 'Prerequisites: Lesson 7.4, Lesson 8.8', 'Prerequisites: Lesson 7.4, Lesson 8.8 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 850.0, '# Lesson 8.17: System Deep Dive 7: Distributed Cloud Object Storage (Amazon S3 / Google Cloud Storage)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.4, Lesson 8.8
- **Subtopics**:
  - `8.17.1` Requirements: store billions of arbitrary binary objects (blobs), 99.999999999% (11 Nines) durability, multi-part uploads
  - `8.17.2` Decoupling Metadata from Blob Data: metadata storage in distributed LSM/key-value stores, raw binary chunks on raw disk servers
  - `8.17.3` Durability mechanics: Triple replication vs Erasure Coding (e.g. Reed-Solomon $8+4$ scheme) storage overhead reduction (1.5x vs 3x)
  - `8.17.4` Chunking and placement architecture: breaking files into 64MB chunks, consistent hashing placement, failure domain isolation
  - `8.17.5` Garbage collection and compaction: reclaiming deleted object chunks asynchronously without blocking write paths
  - `8.17.6` Data integrity verification: end-to-end CRC32 / MD5 checksumming, background scrubbing to detect silent bit-rot on disk
- **Key Failure Modes & Edge Cases**: Silent bit rot on physical hard drives corrupting stored files without detection; metadata index becoming a bottleneck.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for a distributed blob storage system with Erasure Coding and background data scrubbing.
- **Project Application**: System Design Portfolio: Project 7 - Distributed Object Storage.', '{"solution.py": "# Phase 8 // Lesson 8.17: System Deep Dive 7: Distributed Cloud Object Storage (Amazon S3 / Google Cloud Storage)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for a distributed blob storage system with Erasure Coding\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.17", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for a distributed blob storage system with Erasure Coding and background data scrubbing.", "subtopics": ["8.17.1 Requirements: store billions of arbitrary binary objects (blobs), 99.999999999% (11 Nines) durability, multi-part uploads", "8.17.2 Decoupling Metadata from Blob Data: metadata storage in distributed LSM/key-value stores, raw binary chunks on raw disk servers", "8.17.3 Durability mechanics: Triple replication vs Erasure Coding (e.g. Reed-Solomon $8+4$ scheme) storage overhead reduction (1.5x vs 3x)", "8.17.4 Chunking and placement architecture: breaking files into 64MB chunks, consistent hashing placement, failure domain isolation", "8.17.5 Garbage collection and compaction: reclaiming deleted object chunks asynchronously without blocking write paths", "8.17.6 Data integrity verification: end-to-end CRC32 / MD5 checksumming, background scrubbing to detect silent bit-rot on disk"]}'::jsonb, '["Explain how this implementation prevents: Silent bit rot on physical hard drives corrupting stored files without detection; metadata index becoming a bottleneck.", "How does System Deep Dive 7: Distributed Cloud Object Storage (Amazon S3 / Google Cloud Storage) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-18', 'phase-08-lesson-18-system-deep-dive-8-collaborative-document', 'module-9', 18, 'Lesson 9.18: System Deep Dive 8: Collaborative Document Editing System (Google Docs / Figma)', 'Prerequisites: Lesson 7.5, Lesson 8.15', 'Prerequisites: Lesson 7.5, Lesson 8.15 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 900.0, '# Lesson 8.18: System Deep Dive 8: Collaborative Document Editing System (Google Docs / Figma)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.5, Lesson 8.15
- **Subtopics**:
  - `8.18.1` Requirements: multi-user real-time concurrent editing, cursor presence, offline editing support, version history, low latency
  - `8.18.2` Concurrency models comparison: Pessimistic Locking vs Operational Transformation (OT) vs CRDTs (Conflict-Free Replicated Data Types)
  - `8.18.3` Operational Transformation (OT) deep dive: Central server sequencing, transforming operations against concurrent states
  - `8.18.4` CRDT text sequences (RGA, Yjs, Automerge): peer-to-peer capability, mathematical convergence, and memory overhead
  - `8.18.5` Session server architecture: routing all collaborators of document $D$ to the same stateful session server via consistent hashing
  - `8.18.6` Compaction and snapshots: periodically snapshotting document state to persistent storage and truncating operation logs
- **Key Failure Modes & Edge Cases**: Operational transformation divergence bugs in peer-to-peer topologies; memory explosion from retaining millions of granular keystroke CRDT tombstones.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for Google Docs using centralized OT and WebSocket session affinity.
- **Project Application**: System Design Portfolio: Project 8 - Collaborative Document Editing.', '{"solution.py": "# Phase 8 // Lesson 8.18: System Deep Dive 8: Collaborative Document Editing System (Google Docs / Figma)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for Google Docs using centralized OT and WebSocket sessio\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.18", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for Google Docs using centralized OT and WebSocket session affinity.", "subtopics": ["8.18.1 Requirements: multi-user real-time concurrent editing, cursor presence, offline editing support, version history, low latency", "8.18.2 Concurrency models comparison: Pessimistic Locking vs Operational Transformation (OT) vs CRDTs (Conflict-Free Replicated Data Types)", "8.18.3 Operational Transformation (OT) deep dive: Central server sequencing, transforming operations against concurrent states", "8.18.4 CRDT text sequences (RGA, Yjs, Automerge): peer-to-peer capability, mathematical convergence, and memory overhead", "8.18.5 Session server architecture: routing all collaborators of document $D$ to the same stateful session server via consistent hashing", "8.18.6 Compaction and snapshots: periodically snapshotting document state to persistent storage and truncating operation logs"]}'::jsonb, '["Explain how this implementation prevents: Operational transformation divergence bugs in peer-to-peer topologies; memory explosion from retaining millions of granu", "How does System Deep Dive 8: Collaborative Document Editing System (Google Docs / Figma) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-19', 'phase-08-lesson-19-system-deep-dive-9-real-time-ride-hailing', 'module-9', 19, 'Lesson 9.19: System Deep Dive 9: Real-Time Ride-Hailing Geospatial Service (Uber / Lyft)', 'Prerequisites: Lesson 8.3, Lesson 8.15', 'Prerequisites: Lesson 8.3, Lesson 8.15 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 950.0, '# Lesson 8.19: System Deep Dive 9: Real-Time Ride-Hailing Geospatial Service (Uber / Lyft)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.3, Lesson 8.15
- **Subtopics**:
  - `8.19.1` Requirements: match riders with nearby drivers, real-time location updates (every 4s per driver), surge pricing, ETA calculation
  - `8.19.2` Capacity estimation: 5M active drivers reporting GPS every 4 seconds $\approx 1.25\text{M}$ GPS writes/second
  - `8.19.3` Geospatial indexing algorithms: Geohashes vs Google S2 Geometry vs Uber H3 (hexagonal hierarchical spatial index)
  - `8.19.4` Why hexagons (Uber H3): uniform distance to all 6 neighboring cells, avoiding distortion in square or rectangular grids
  - `8.19.5` Location ingestion architecture: high-throughput Kafka streaming, ephemeral geospatial in-memory store (Redis GEO / custom memory grid)
  - `8.19.6` Driver matching service: spatial range query (within radius $R$), filtering eligible drivers, dispatch locking via Redis distributed locks
- **Key Failure Modes & Edge Cases**: Driver location updates overwhelming disk-backed relational databases; race conditions where multiple riders match the same driver simultaneously.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for Uber driver ingestion and geospatial dispatch matching using Uber H3 and Redis.
- **Project Application**: System Design Portfolio: Project 9 - Real-Time Ride-Hailing Service.', '{"solution.py": "# Phase 8 // Lesson 8.19: System Deep Dive 9: Real-Time Ride-Hailing Geospatial Service (Uber / Lyft)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for Uber driver ingestion and geospatial dispatch matchin\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.19", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for Uber driver ingestion and geospatial dispatch matching using Uber H3 and Redis.", "subtopics": ["8.19.1 Requirements: match riders with nearby drivers, real-time location updates (every 4s per driver), surge pricing, ETA calculation", "8.19.2 Capacity estimation: 5M active drivers reporting GPS every 4 seconds $\\approx 1.25\\text{M}$ GPS writes/second", "8.19.3 Geospatial indexing algorithms: Geohashes vs Google S2 Geometry vs Uber H3 (hexagonal hierarchical spatial index)", "8.19.4 Why hexagons (Uber H3): uniform distance to all 6 neighboring cells, avoiding distortion in square or rectangular grids", "8.19.5 Location ingestion architecture: high-throughput Kafka streaming, ephemeral geospatial in-memory store (Redis GEO / custom memory grid)", "8.19.6 Driver matching service: spatial range query (within radius $R$), filtering eligible drivers, dispatch locking via Redis distributed locks"]}'::jsonb, '["Explain how this implementation prevents: Driver location updates overwhelming disk-backed relational databases; race conditions where multiple riders match the s", "How does System Deep Dive 9: Real-Time Ride-Hailing Geospatial Service (Uber / Lyft) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-20', 'phase-08-lesson-20-system-deep-dive-10-financial-transaction', 'module-9', 20, 'Lesson 9.20: System Deep Dive 10: Financial Transaction Ledger & Payment Processing (Stripe)', 'Prerequisites: Phase 4, Lesson 7.6', 'Prerequisites: Phase 4, Lesson 7.6 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 1000.0, '# Lesson 8.20: System Deep Dive 10: Financial Transaction Ledger & Payment Processing (Stripe)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 7.6
- **Subtopics**:
  - `8.20.1` Requirements: zero double-spend, strict ACID compliance, double-entry bookkeeping, audit trail, PCI-DSS compliance
  - `8.20.2` Double-entry bookkeeping principle: every transaction must balance (Debits = Credits); immutable append-only ledger entries
  - `8.20.3` Idempotency architecture: client-provided idempotency keys, atomic check-and-insert in database before payment processor calls
  - `8.20.4` Handling external payment gateways: asynchronous webhooks, reconciliation jobs, network timeouts, and state machines
  - `8.20.5` Distributed lock vs Database serializability: preventing concurrent withdrawal race conditions on account balances
  - `8.20.6` Financial reconciliation engine: matching bank settlement files against internal transaction ledgers to detect discrepancy
- **Key Failure Modes & Edge Cases**: Network timeout during external payment charge treated as failure, causing duplicate customer charge on naive retry.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for an immutable double-entry financial ledger with end-to-end idempotency guarantees.
- **Project Application**: System Design Portfolio: Project 10 - Financial Transaction Ledger.', '{"solution.py": "# Phase 8 // Lesson 8.20: System Deep Dive 10: Financial Transaction Ledger & Payment Processing (Stripe)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for an immutable double-entry financial ledger with end-t\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.20", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for an immutable double-entry financial ledger with end-to-end idempotency guarantees.", "subtopics": ["8.20.1 Requirements: zero double-spend, strict ACID compliance, double-entry bookkeeping, audit trail, PCI-DSS compliance", "8.20.2 Double-entry bookkeeping principle: every transaction must balance (Debits = Credits); immutable append-only ledger entries", "8.20.3 Idempotency architecture: client-provided idempotency keys, atomic check-and-insert in database before payment processor calls", "8.20.4 Handling external payment gateways: asynchronous webhooks, reconciliation jobs, network timeouts, and state machines", "8.20.5 Distributed lock vs Database serializability: preventing concurrent withdrawal race conditions on account balances", "8.20.6 Financial reconciliation engine: matching bank settlement files against internal transaction ledgers to detect discrepancy"]}'::jsonb, '["Explain how this implementation prevents: Network timeout during external payment charge treated as failure, causing duplicate customer charge on naive retry.", "How does System Deep Dive 10: Financial Transaction Ledger & Payment Processing (Stripe) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-21', 'phase-08-lesson-21-search-engine-architecture-inverted-index', 'module-9', 21, 'Lesson 9.21: Search Engine Architecture: Inverted Index & Distributed Search (Elasticsearch)', 'Prerequisites: Lesson 8.3, Lesson 8.8', 'Prerequisites: Lesson 8.3, Lesson 8.8 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 1050.0, '# Lesson 8.21: Search Engine Architecture: Inverted Index & Distributed Search (Elasticsearch)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.3, Lesson 8.8
- **Subtopics**:
  - `8.21.1` Search fundamentals: documents, fields, text tokenization, stemming, stop-word removal, and inverted index data structures
  - `8.21.2` Inverted index mechanics: posting lists, term dictionary, term index (FST - Finite State Transducers), and SkipLists
  - `8.21.3` Distributed search architecture: Sharding indices, primary vs replica shards, coordinator nodes, scatter-gather query execution
  - `8.21.4` Relevance ranking algorithms: TF-IDF (Term Frequency - Inverse Document Frequency) and modern BM25 probabilistic scoring
  - `8.21.5` Index updates and near real-time (NRT) search: Lucene segments, in-memory buffer, commit log (translog), and background segment merging
  - `8.21.6` Handling search traffic spikes: caching filter queries, routing keys for targeted sharding, and deep pagination limits (`search_after`)
- **Key Failure Modes & Edge Cases**: Performing deep pagination (`from: 100000`) causing out-of-memory crash across search coordinator nodes; expensive un-cached wildcard queries.
- **Verification & Mastery Check**: Design an enterprise search infrastructure indexing 50M documents with BM25 ranking and scatter-gather coordinator nodes.
- **Project Application**: System Design Portfolio: Enterprise Distributed Search Engine.', '{"solution.py": "# Phase 8 // Lesson 8.21: Search Engine Architecture: Inverted Index & Distributed Search (Elasticsearch)\n\ndef solve():\n    \"\"\"\n    Verification: Design an enterprise search infrastructure indexing 50M documents with BM25 ranking and scatter-gath\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.21", "subtopics_count": 6, "verification_criteria": "Design an enterprise search infrastructure indexing 50M documents with BM25 ranking and scatter-gather coordinator nodes.", "subtopics": ["8.21.1 Search fundamentals: documents, fields, text tokenization, stemming, stop-word removal, and inverted index data structures", "8.21.2 Inverted index mechanics: posting lists, term dictionary, term index (FST - Finite State Transducers), and SkipLists", "8.21.3 Distributed search architecture: Sharding indices, primary vs replica shards, coordinator nodes, scatter-gather query execution", "8.21.4 Relevance ranking algorithms: TF-IDF (Term Frequency - Inverse Document Frequency) and modern BM25 probabilistic scoring", "8.21.5 Index updates and near real-time (NRT) search: Lucene segments, in-memory buffer, commit log (translog), and background segment merging", "8.21.6 Handling search traffic spikes: caching filter queries, routing keys for targeted sharding, and deep pagination limits (`search_after`)"]}'::jsonb, '["Explain how this implementation prevents: Performing deep pagination (`from: 100000`) causing out-of-memory crash across search coordinator nodes; expensive un-ca", "How does Search Engine Architecture: Inverted Index & Distributed Search (Elasticsearch) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-22', 'phase-08-lesson-22-notification-engine-multi-channel-deliver', 'module-9', 22, 'Lesson 9.22: Notification Engine: Multi-Channel Delivery, Batching & Deduplication', 'Prerequisites: Lesson 8.7, Lesson 8.12', 'Prerequisites: Lesson 8.7, Lesson 8.12 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 1100.0, '# Lesson 8.22: Notification Engine: Multi-Channel Delivery, Batching & Deduplication

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.7, Lesson 8.12
- **Subtopics**:
  - `8.22.1` Requirements: multi-channel notifications (Push, SMS, Email, In-app), priority queues, template rendering, user preferences
  - `8.22.2` System architecture: Notification API, preference verification service, template engine, and channel worker pools
  - `8.22.3` Third-party provider integration: APNs (Apple), FCM (Google), Twilio (SMS), SendGrid (Email); handling third-party rate limits
  - `8.22.4` Notification batching and digesting: grouping high-frequency events (e.g. ''5 people liked your photo'') using Redis time windows
  - `8.22.5` Deduplication mechanisms: idempotency keys, Redis sliding window hash deduplication preventing spam notifications
  - `8.22.6` Delivery tracking and fallback routing: tracking delivery callbacks, falling back from Push to SMS upon delivery timeout
- **Key Failure Modes & Edge Cases**: Notification storm caused by an un-throttled batch job sending millions of pushes, burning third-party API quotas and getting accounts banned.
- **Verification & Mastery Check**: Design a resilient multi-channel notification engine with user preference filtering, message batching, and automated provider fallbacks.
- **Project Application**: System Design Portfolio: Scalable Notification Engine.', '{"solution.py": "# Phase 8 // Lesson 8.22: Notification Engine: Multi-Channel Delivery, Batching & Deduplication\n\ndef solve():\n    \"\"\"\n    Verification: Design a resilient multi-channel notification engine with user preference filtering, message batchin\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.22", "subtopics_count": 6, "verification_criteria": "Design a resilient multi-channel notification engine with user preference filtering, message batching, and automated provider fallbacks.", "subtopics": ["8.22.1 Requirements: multi-channel notifications (Push, SMS, Email, In-app), priority queues, template rendering, user preferences", "8.22.2 System architecture: Notification API, preference verification service, template engine, and channel worker pools", "8.22.3 Third-party provider integration: APNs (Apple), FCM (Google), Twilio (SMS), SendGrid (Email); handling third-party rate limits", "8.22.4 Notification batching and digesting: grouping high-frequency events (e.g. ''5 people liked your photo'') using Redis time windows", "8.22.5 Deduplication mechanisms: idempotency keys, Redis sliding window hash deduplication preventing spam notifications", "8.22.6 Delivery tracking and fallback routing: tracking delivery callbacks, falling back from Push to SMS upon delivery timeout"]}'::jsonb, '["Explain how this implementation prevents: Notification storm caused by an un-throttled batch job sending millions of pushes, burning third-party API quotas and ge", "How does Notification Engine: Multi-Channel Delivery, Batching & Deduplication scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-23', 'phase-08-lesson-23-metrics-telemetry-pipeline-high-throughpu', 'module-9', 23, 'Lesson 9.23: Metrics & Telemetry Pipeline: High-Throughput Time-Series Ingestion', 'Prerequisites: Phase 7, Lesson 8.7', 'Prerequisites: Phase 7, Lesson 8.7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 1150.0, '# Lesson 8.23: Metrics & Telemetry Pipeline: High-Throughput Time-Series Ingestion

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 8.7
- **Subtopics**:
  - `8.23.1` Requirements: ingest 10M metric data points/sec, downsampling, real-time alerting, long-term retention, sub-second query latency
  - `8.23.2` Metrics data model: metric name, timestamp, key-value tag dimensions, and floating-point numeric value
  - `8.23.3` Ingestion architecture: local daemon agents (StatsD/OTel), load-balanced Kafka stream buffers, and stream processing engines (Flink)
  - `8.23.4` Storage architecture: Time-Series Databases (VictoriaMetrics, ClickHouse, Prometheus), columnar compression, delta-of-delta timestamps
  - `8.23.5` Rollup and downsampling pipelines: aggregating 1-second raw metrics into 1-minute, 1-hour, and 1-day rollups over time
  - `8.23.6` Query engine optimization: inverted index over label tag combinations, caching query results, and partition pruning
- **Key Failure Modes & Edge Cases**: Cardinality explosion when application code dynamically adds user IDs as metric labels, crashing time-series storage memory.
- **Verification & Mastery Check**: Design a 10M events/sec telemetry ingestion pipeline featuring Kafka streaming, ClickHouse columnar storage, and downsampling.
- **Project Application**: System Design Portfolio: High-Throughput Telemetry Pipeline.', '{"solution.py": "# Phase 8 // Lesson 8.23: Metrics & Telemetry Pipeline: High-Throughput Time-Series Ingestion\n\ndef solve():\n    \"\"\"\n    Verification: Design a 10M events/sec telemetry ingestion pipeline featuring Kafka streaming, ClickHouse columnar \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.23", "subtopics_count": 6, "verification_criteria": "Design a 10M events/sec telemetry ingestion pipeline featuring Kafka streaming, ClickHouse columnar storage, and downsampling.", "subtopics": ["8.23.1 Requirements: ingest 10M metric data points/sec, downsampling, real-time alerting, long-term retention, sub-second query latency", "8.23.2 Metrics data model: metric name, timestamp, key-value tag dimensions, and floating-point numeric value", "8.23.3 Ingestion architecture: local daemon agents (StatsD/OTel), load-balanced Kafka stream buffers, and stream processing engines (Flink)", "8.23.4 Storage architecture: Time-Series Databases (VictoriaMetrics, ClickHouse, Prometheus), columnar compression, delta-of-delta timestamps", "8.23.5 Rollup and downsampling pipelines: aggregating 1-second raw metrics into 1-minute, 1-hour, and 1-day rollups over time", "8.23.6 Query engine optimization: inverted index over label tag combinations, caching query results, and partition pruning"]}'::jsonb, '["Explain how this implementation prevents: Cardinality explosion when application code dynamically adds user IDs as metric labels, crashing time-series storage mem", "How does Metrics & Telemetry Pipeline: High-Throughput Time-Series Ingestion scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-24', 'phase-08-lesson-24-e-commerce-flash-sale-system-high-concurr', 'module-9', 24, 'Lesson 9.24: E-Commerce Flash Sale System: High-Concurrency Inventory Reservation', 'Prerequisites: Phase 4, Lesson 8.8', 'Prerequisites: Phase 4, Lesson 8.8 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 1200.0, '# Lesson 8.24: E-Commerce Flash Sale System: High-Concurrency Inventory Reservation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 8.8
- **Subtopics**:
  - `8.24.1` Requirements: 10,000 items available, 1,000,000 users attempting to buy at 12:00:00, zero overselling, fair ordering
  - `8.24.2` The overselling problem: classic check-then-act database updates causing inventory to drop below zero under high concurrency
  - `8.24.3` Multi-layer traffic filtering: CDN static asset caching, API gateway rate limiting, and CAPTCHA challenge verification
  - `8.24.4` In-memory inventory reservation: atomic inventory decrement in Redis using Lua scripts (`if stock >= qty then decr end`)
  - `8.24.5` Asynchronous order creation: pushing successful reservations into Kafka for asynchronous database order generation
  - `8.24.6` Unpaid order release: transactional outbox pattern, scheduled TTL expiration returning un-purchased inventory back to Redis stock pool
- **Key Failure Modes & Edge Cases**: Database row-locking contention crashing PostgreSQL when 50,000 transactions attempt to update the same inventory row simultaneously.
- **Verification & Mastery Check**: Design a flash sale inventory reservation system using Redis Lua scripts, Kafka queuing, and automated 15-minute payment expiration.
- **Project Application**: System Design Portfolio: Flash Sale Inventory Architecture.', '{"solution.py": "# Phase 8 // Lesson 8.24: E-Commerce Flash Sale System: High-Concurrency Inventory Reservation\n\ndef solve():\n    \"\"\"\n    Verification: Design a flash sale inventory reservation system using Redis Lua scripts, Kafka queuing, and automat\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.24", "subtopics_count": 6, "verification_criteria": "Design a flash sale inventory reservation system using Redis Lua scripts, Kafka queuing, and automated 15-minute payment expiration.", "subtopics": ["8.24.1 Requirements: 10,000 items available, 1,000,000 users attempting to buy at 12:00:00, zero overselling, fair ordering", "8.24.2 The overselling problem: classic check-then-act database updates causing inventory to drop below zero under high concurrency", "8.24.3 Multi-layer traffic filtering: CDN static asset caching, API gateway rate limiting, and CAPTCHA challenge verification", "8.24.4 In-memory inventory reservation: atomic inventory decrement in Redis using Lua scripts (`if stock >= qty then decr end`)", "8.24.5 Asynchronous order creation: pushing successful reservations into Kafka for asynchronous database order generation", "8.24.6 Unpaid order release: transactional outbox pattern, scheduled TTL expiration returning un-purchased inventory back to Redis stock pool"]}'::jsonb, '["Explain how this implementation prevents: Database row-locking contention crashing PostgreSQL when 50,000 transactions attempt to update the same inventory row si", "How does E-Commerce Flash Sale System: High-Concurrency Inventory Reservation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-25', 'phase-08-lesson-25-distributed-task-scheduler-quartz-tempora', 'module-9', 25, 'Lesson 9.25: Distributed Task Scheduler: Quartz, Temporal & Workflow Orchestration', 'Prerequisites: Phase 7, Lesson 8.7', 'Prerequisites: Phase 7, Lesson 8.7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 1250.0, '# Lesson 8.25: Distributed Task Scheduler: Quartz, Temporal & Workflow Orchestration

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 8.7
- **Subtopics**:
  - `8.25.1` Task scheduling paradigms: Cron-based recurring jobs vs Delayed tasks vs Complex multi-step directed acyclic graph (DAG) workflows
  - `8.25.2` Distributed cron architecture: leader-elected scheduler nodes, database task leases, and preventing duplicate executions
  - `8.25.3` Delayed task queue architecture: Redis Sorted Sets (`ZADD` with execute timestamp score, `ZRANGEBYSCORE` polling workers)
  - `8.25.4` Workflow Orchestration with Temporal / Airflow: durable execution, event history replay, state machine persistence, and compensation logic
  - `8.25.5` Handling task worker failures: heartbeats, automatic task reassignment, exponential backoff, and idempotent task execution
  - `8.25.6` Scalability: partitioning task queues by tenant, priority weighting, and worker auto-scaling based on queue depth
- **Key Failure Modes & Edge Cases**: Workers crashing mid-task without durable state checkpoints, causing long-running financial batch processes to restart from scratch.
- **Verification & Mastery Check**: Design a durable distributed workflow orchestrator capable of executing multi-day saga transactions with automated step retries.
- **Project Application**: System Design Portfolio: Distributed Workflow Orchestrator.', '{"solution.py": "# Phase 8 // Lesson 8.25: Distributed Task Scheduler: Quartz, Temporal & Workflow Orchestration\n\ndef solve():\n    \"\"\"\n    Verification: Design a durable distributed workflow orchestrator capable of executing multi-day saga transactions \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.25", "subtopics_count": 6, "verification_criteria": "Design a durable distributed workflow orchestrator capable of executing multi-day saga transactions with automated step retries.", "subtopics": ["8.25.1 Task scheduling paradigms: Cron-based recurring jobs vs Delayed tasks vs Complex multi-step directed acyclic graph (DAG) workflows", "8.25.2 Distributed cron architecture: leader-elected scheduler nodes, database task leases, and preventing duplicate executions", "8.25.3 Delayed task queue architecture: Redis Sorted Sets (`ZADD` with execute timestamp score, `ZRANGEBYSCORE` polling workers)", "8.25.4 Workflow Orchestration with Temporal / Airflow: durable execution, event history replay, state machine persistence, and compensation logic", "8.25.5 Handling task worker failures: heartbeats, automatic task reassignment, exponential backoff, and idempotent task execution", "8.25.6 Scalability: partitioning task queues by tenant, priority weighting, and worker auto-scaling based on queue depth"]}'::jsonb, '["Explain how this implementation prevents: Workers crashing mid-task without durable state checkpoints, causing long-running financial batch processes to restart f", "How does Distributed Task Scheduler: Quartz, Temporal & Workflow Orchestration scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
