INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-4-6', 'phase-04-lesson-06-process-forking-copy-on-write-cow-execve', 'module-6', 6, 'Lesson 6.6: Process Forking, Copy-On-Write (COW), & `execve`', 'Prerequisites: Phase 0 (Lesson 0.21)', 'Prerequisites: Phase 0 (Lesson 0.21) | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 300.0, '# Lesson 4.6: Process Forking, Copy-On-Write (COW), & `execve`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.21)
- **Subtopics**:
  - `4.6.1` The `fork()` system call: duplicating process address space, file descriptors, and signal masks.
  - `4.6.2` Copy-On-Write (COW) mechanics: sharing identical physical pages marked read-only until a process writes to a page.
  - `4.6.3` The `execve()` system call: clearing virtual address space, loading new ELF binary, initializing new stack and heap.
  - `4.6.4` The `posix_spawn()` optimized interface: avoiding memory table duplication overhead on modern Linux.
- **Key Failure Modes & Edge Cases**: Redis background save (`BGSAVE`) memory spikes: COW dirty page copies exhausting RAM when writes are heavy during saves.
- **Verification & Mastery Check**: Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW in action.
- **Project Application**: NanoHTTP and systems tooling.', '{"solution.py": "# Phase 4 // Lesson 4.6: Process Forking, Copy-On-Write (COW), & `execve`\n\ndef solve():\n    \"\"\"\n    Verification: Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.6", "subtopics_count": 4, "verification_criteria": "Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW in action.", "subtopics": ["4.6.1 The `fork()` system call: duplicating process address space, file descriptors, and signal masks.", "4.6.2 Copy-On-Write (COW) mechanics: sharing identical physical pages marked read-only until a process writes to a page.", "4.6.3 The `execve()` system call: clearing virtual address space, loading new ELF binary, initializing new stack and heap.", "4.6.4 The `posix_spawn()` optimized interface: avoiding memory table duplication overhead on modern Linux."]}'::jsonb, '["Explain how this implementation prevents: Redis background save (`BGSAVE`) memory spikes: COW dirty page copies exhausting RAM when writes are heavy during saves.", "How does Process Forking, Copy-On-Write (COW), & `execve` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-7', 'phase-04-lesson-07-inter-process-communication-pipes-named-f', 'module-6', 7, 'Lesson 6.7: Inter-Process Communication: Pipes & Named FIFOs', 'Prerequisites: Phase 0 (Lesson 0.24)', 'Prerequisites: Phase 0 (Lesson 0.24) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 350.0, '# Lesson 4.7: Inter-Process Communication: Pipes & Named FIFOs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.24)
- **Subtopics**:
  - `4.7.1` Anonymous pipes (`pipe()`): unidirectional kernel ring buffer (64KB default capacity).
  - `4.7.2` Blocking behavior: `write()` blocks when pipe buffer is full; `read()` blocks when pipe buffer is empty.
  - `4.7.3` Broken pipe signal: `SIGPIPE` generated when writing to a pipe with zero active read file descriptors.
  - `4.7.4` Named pipes (`mkfifo()`): filesystem entries enabling IPC between unrelated processes without parent-child ancestry.
- **Key Failure Modes & Edge Cases**: Crashing on unhandled `SIGPIPE` when downstream readers close connections abruptly while writer continues writing.
- **Verification & Mastery Check**: Implement a bidirectional IPC communication channel between two processes using a pair of named FIFOs.
- **Project Application**: SysTrace and systems IPC.', '{"solution.py": "# Phase 4 // Lesson 4.7: Inter-Process Communication: Pipes & Named FIFOs\n\ndef solve():\n    \"\"\"\n    Verification: Implement a bidirectional IPC communication channel between two processes using a pair of named FIFO\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.7", "subtopics_count": 4, "verification_criteria": "Implement a bidirectional IPC communication channel between two processes using a pair of named FIFOs.", "subtopics": ["4.7.1 Anonymous pipes (`pipe()`): unidirectional kernel ring buffer (64KB default capacity).", "4.7.2 Blocking behavior: `write()` blocks when pipe buffer is full; `read()` blocks when pipe buffer is empty.", "4.7.3 Broken pipe signal: `SIGPIPE` generated when writing to a pipe with zero active read file descriptors.", "4.7.4 Named pipes (`mkfifo()`): filesystem entries enabling IPC between unrelated processes without parent-child ancestry."]}'::jsonb, '["Explain how this implementation prevents: Crashing on unhandled `SIGPIPE` when downstream readers close connections abruptly while writer continues writing.", "How does Inter-Process Communication: Pipes & Named FIFOs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-8', 'phase-04-lesson-08-unix-domain-sockets-passing-file-descript', 'module-6', 8, 'Lesson 6.8: Unix Domain Sockets & Passing File Descriptors', 'Prerequisites: Lesson 4.7', 'Prerequisites: Lesson 4.7 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 400.0, '# Lesson 4.8: Unix Domain Sockets & Passing File Descriptors

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.7
- **Subtopics**:
  - `4.8.1` Unix Domain Sockets (`AF_UNIX`): bidirectional local IPC bypassing network stack, checksums, and TCP headers.
  - `4.8.2` Stream (`SOCK_STREAM`) vs Datagram (`SOCK_DGRAM`) Unix sockets; filesystem socket nodes.
  - `4.8.3` Passing Open File Descriptors: utilizing `sendmsg()` and `recvmsg()` with `SCM_RIGHTS` ancillary control messages.
  - `4.8.4` Why UDS outperforms loopback TCP (`127.0.0.1`): 2x throughput, lower latency, filesystem permission security.
- **Key Failure Modes & Edge Cases**: Dangling socket files on filesystem after unclean process termination preventing service restarts.
- **Verification & Mastery Check**: Build a parent process that opens a TCP socket and passes the active file descriptor to a child worker via UDS.
- **Project Application**: PgBouncer local connections in Phase 5.', '{"solution.py": "# Phase 4 // Lesson 4.8: Unix Domain Sockets & Passing File Descriptors\n\ndef solve():\n    \"\"\"\n    Verification: Build a parent process that opens a TCP socket and passes the active file descriptor to a child work\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.8", "subtopics_count": 4, "verification_criteria": "Build a parent process that opens a TCP socket and passes the active file descriptor to a child worker via UDS.", "subtopics": ["4.8.1 Unix Domain Sockets (`AF_UNIX`): bidirectional local IPC bypassing network stack, checksums, and TCP headers.", "4.8.2 Stream (`SOCK_STREAM`) vs Datagram (`SOCK_DGRAM`) Unix sockets; filesystem socket nodes.", "4.8.3 Passing Open File Descriptors: utilizing `sendmsg()` and `recvmsg()` with `SCM_RIGHTS` ancillary control messages.", "4.8.4 Why UDS outperforms loopback TCP (`127.0.0.1`): 2x throughput, lower latency, filesystem permission security."]}'::jsonb, '["Explain how this implementation prevents: Dangling socket files on filesystem after unclean process termination preventing service restarts.", "How does Unix Domain Sockets & Passing File Descriptors scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-9', 'phase-04-lesson-09-posix-signals-asynchronous-interruption-r', 'module-6', 9, 'Lesson 6.9: POSIX Signals: Asynchronous Interruption & Re-entrancy', 'Prerequisites: Phase 0 (Lesson 0.25)', 'Prerequisites: Phase 0 (Lesson 0.25) | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 450.0, '# Lesson 4.9: POSIX Signals: Asynchronous Interruption & Re-entrancy

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.25)
- **Subtopics**:
  - `4.9.1` Signal delivery mechanics: kernel interrupting user-space instruction stream and executing registered signal handler.
  - `4.9.2` Signal masks: blocking and unblocking signals via `sigprocmask()` during critical sections.
  - `4.9.3` Signal Re-entrancy: why calling non-reentrant functions (`printf`, `malloc`, `free`) inside signal handlers causes deadlocks.
  - `4.9.4` Async-signal-safe functions list: POSIX standard guarantees; setting `sig_atomic_t` or `volatile` flags.
- **Key Failure Modes & Edge Cases**: Deadlocks in production signal handlers caused by attempting to acquire a mutex or allocate memory inside the handler.
- **Verification & Mastery Check**: Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self-pipe trick.
- **Project Application**: NanoHTTP: Graceful shutdown signal engine.', '{"solution.py": "# Phase 4 // Lesson 4.9: POSIX Signals: Asynchronous Interruption & Re-entrancy\n\ndef solve():\n    \"\"\"\n    Verification: Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.9", "subtopics_count": 4, "verification_criteria": "Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self-pipe trick.", "subtopics": ["4.9.1 Signal delivery mechanics: kernel interrupting user-space instruction stream and executing registered signal handler.", "4.9.2 Signal masks: blocking and unblocking signals via `sigprocmask()` during critical sections.", "4.9.3 Signal Re-entrancy: why calling non-reentrant functions (`printf`, `malloc`, `free`) inside signal handlers causes deadlocks.", "4.9.4 Async-signal-safe functions list: POSIX standard guarantees; setting `sig_atomic_t` or `volatile` flags."]}'::jsonb, '["Explain how this implementation prevents: Deadlocks in production signal handlers caused by attempting to acquire a mutex or allocate memory inside the handler.", "How does POSIX Signals: Asynchronous Interruption & Re-entrancy scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-10', 'phase-04-lesson-10-zombie-processes-orphan-reaping-waitpid', 'module-6', 10, 'Lesson 6.10: Zombie Processes, Orphan Reaping, & `waitpid`', 'Prerequisites: Lesson 4.6', 'Prerequisites: Lesson 4.6 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 500.0, '# Lesson 4.10: Zombie Processes, Orphan Reaping, & `waitpid`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.6
- **Subtopics**:
  - `4.10.1` Process termination lifecycle: child process exits, becomes Zombie (`Z` state), retains exit status in PCB.
  - `4.10.2` Reaping zombies: parent calling `wait()` or `waitpid()` to read child exit status and release kernel PCB memory.
  - `4.10.3` Orphan processes: parent terminating before child; child adopted by init process (PID 1 / systemd).
  - `4.10.4` Subreaper processes: using `prctl(PR_SET_CHILD_SUBREAPER)` in process managers to reap orphaned descendant trees.
- **Key Failure Modes & Edge Cases**: Zombie accumulation exhausting kernel PID limits in container environments where PID 1 fails to reap children.
- **Verification & Mastery Check**: Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated workers immediately.
- **Project Application**: Container process management in Phase 4 and Phase 7.', '{"solution.py": "# Phase 4 // Lesson 4.10: Zombie Processes, Orphan Reaping, & `waitpid`\n\ndef solve():\n    \"\"\"\n    Verification: Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated wor\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.10", "subtopics_count": 4, "verification_criteria": "Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated workers immediately.", "subtopics": ["4.10.1 Process termination lifecycle: child process exits, becomes Zombie (`Z` state), retains exit status in PCB.", "4.10.2 Reaping zombies: parent calling `wait()` or `waitpid()` to read child exit status and release kernel PCB memory.", "4.10.3 Orphan processes: parent terminating before child; child adopted by init process (PID 1 / systemd).", "4.10.4 Subreaper processes: using `prctl(PR_SET_CHILD_SUBREAPER)` in process managers to reap orphaned descendant trees."]}'::jsonb, '["Explain how this implementation prevents: Zombie accumulation exhausting kernel PID limits in container environments where PID 1 fails to reap children.", "How does Zombie Processes, Orphan Reaping, & `waitpid` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-11', 'phase-04-lesson-11-kernel-threads-vs-user-space-green-thread', 'module-6', 11, 'Lesson 6.11: Kernel Threads vs User-Space Green Threads', 'Prerequisites: Phase 1 (Lesson 1.31)', 'Prerequisites: Phase 1 (Lesson 1.31) | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 550.0, '# Lesson 4.11: Kernel Threads vs User-Space Green Threads

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.31)
- **Subtopics**:
  - `4.11.1` 1:1 Threading Model: each application thread maps directly to a Linux kernel thread (NPTL - Native POSIX Thread Library).
  - `4.11.2` M:N Threading Model: $M$ user-space green threads multiplexed over $N$ OS threads (Go goroutines, Erlang actors).
  - `4.11.3` Context-switch cost: saving CPU registers, flushing pipeline, kernel transition overhead (~1–2 microseconds).
  - `4.11.4` Thread stack allocation: 8MB default stack vs customizable thread stack sizes (`pthread_attr_setstacksize`).
- **Key Failure Modes & Edge Cases**: Spawning 10,000 OS threads simultaneously, exhausting virtual memory and collapsing system under context switching.
- **Verification & Mastery Check**: Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 coroutines.
- **Project Application**: NanoHTTP: Version 1 (Multi-Threaded Server).', '{"solution.py": "# Phase 4 // Lesson 4.11: Kernel Threads vs User-Space Green Threads\n\ndef solve():\n    \"\"\"\n    Verification: Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 corout\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.11", "subtopics_count": 4, "verification_criteria": "Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 coroutines.", "subtopics": ["4.11.1 1:1 Threading Model: each application thread maps directly to a Linux kernel thread (NPTL - Native POSIX Thread Library).", "4.11.2 M:N Threading Model: $M$ user-space green threads multiplexed over $N$ OS threads (Go goroutines, Erlang actors).", "4.11.3 Context-switch cost: saving CPU registers, flushing pipeline, kernel transition overhead (~1\u20132 microseconds).", "4.11.4 Thread stack allocation: 8MB default stack vs customizable thread stack sizes (`pthread_attr_setstacksize`)."]}'::jsonb, '["Explain how this implementation prevents: Spawning 10,000 OS threads simultaneously, exhausting virtual memory and collapsing system under context switching.", "How does Kernel Threads vs User-Space Green Threads scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-12', 'phase-04-lesson-12-race-conditions-critical-sections-mutual-', 'module-6', 12, 'Lesson 6.12: Race Conditions, Critical Sections, & Mutual Exclusion', 'Prerequisites: Lesson 4.11', 'Prerequisites: Lesson 4.11 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 600.0, '# Lesson 4.12: Race Conditions, Critical Sections, & Mutual Exclusion

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.11
- **Subtopics**:
  - `4.12.1` Race conditions defined: output non-deterministically dependent on relative execution timing of concurrent threads.
  - `4.12.2` Critical Section: code block accessing shared mutable state that must execute atomically.
  - `4.12.3` Mutual Exclusion (Mutex): binary lock ensuring at most one thread executes inside the critical section.
  - `4.12.4` Mutex performance: futex (Fast Userspace Mutex) in Linux — avoiding syscalls on uncontended lock acquisitions.
- **Key Failure Modes & Edge Cases**: Data corruption in concurrent bank account balances caused by unprotected read-modify-write operations.
- **Verification & Mastery Check**: Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it using a Mutex.
- **Project Application**: NanoHTTP: Shared connection metrics.', '{"solution.py": "# Phase 4 // Lesson 4.12: Race Conditions, Critical Sections, & Mutual Exclusion\n\ndef solve():\n    \"\"\"\n    Verification: Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.12", "subtopics_count": 4, "verification_criteria": "Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it using a Mutex.", "subtopics": ["4.12.1 Race conditions defined: output non-deterministically dependent on relative execution timing of concurrent threads.", "4.12.2 Critical Section: code block accessing shared mutable state that must execute atomically.", "4.12.3 Mutual Exclusion (Mutex): binary lock ensuring at most one thread executes inside the critical section.", "4.12.4 Mutex performance: futex (Fast Userspace Mutex) in Linux \u2014 avoiding syscalls on uncontended lock acquisitions."]}'::jsonb, '["Explain how this implementation prevents: Data corruption in concurrent bank account balances caused by unprotected read-modify-write operations.", "How does Race Conditions, Critical Sections, & Mutual Exclusion scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-13', 'phase-04-lesson-13-deadlocks-coffman-conditions-lock-orderin', 'module-6', 13, 'Lesson 6.13: Deadlocks, Coffman Conditions, & Lock Ordering', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 650.0, '# Lesson 4.13: Deadlocks, Coffman Conditions, & Lock Ordering

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.13.1` Deadlock definition: two or more threads permanently blocked, each waiting for a lock held by the other.
  - `4.13.2` The Four Coffman Conditions: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait.
  - `4.13.3` Deadlock prevention via strict Lock Ordering: establishing a global lock hierarchy (always acquire Lock A before Lock B).
  - `4.13.4` Deadlock detection: resource allocation graphs and cycle detection; lock acquisition timeouts (`try_lock`).
- **Key Failure Modes & Edge Cases**: Intermittent production deadlocks occurring when two background jobs acquire database table locks in reverse order.
- **Verification & Mastery Check**: Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using strict lock hierarchies.
- **Project Application**: Database transaction concurrency in Phase 5.', '{"solution.py": "# Phase 4 // Lesson 4.13: Deadlocks, Coffman Conditions, & Lock Ordering\n\ndef solve():\n    \"\"\"\n    Verification: Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using st\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.13", "subtopics_count": 4, "verification_criteria": "Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using strict lock hierarchies.", "subtopics": ["4.13.1 Deadlock definition: two or more threads permanently blocked, each waiting for a lock held by the other.", "4.13.2 The Four Coffman Conditions: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait.", "4.13.3 Deadlock prevention via strict Lock Ordering: establishing a global lock hierarchy (always acquire Lock A before Lock B).", "4.13.4 Deadlock detection: resource allocation graphs and cycle detection; lock acquisition timeouts (`try_lock`)."]}'::jsonb, '["Explain how this implementation prevents: Intermittent production deadlocks occurring when two background jobs acquire database table locks in reverse order.", "How does Deadlocks, Coffman Conditions, & Lock Ordering scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-14', 'phase-04-lesson-14-condition-variables-thread-signaling', 'module-6', 14, 'Lesson 6.14: Condition Variables & Thread Signaling', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 700.0, '# Lesson 4.14: Condition Variables & Thread Signaling

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.14.1` The need for Condition Variables: waiting for a state condition to become true without busy-waiting (spinning).
  - `4.14.2` Condition Variable primitives: `wait(mutex)` (atomically releases mutex and sleeps), `signal()` / `notify()`, `broadcast()`.
  - `4.14.3` Spurious Wakeups: why condition variables must ALWAYS be checked inside a `while (!condition)` loop.
  - `4.14.4` Lost Wakeups: signaling a condition variable before a waiting thread has entered the wait state.
- **Key Failure Modes & Edge Cases**: Using an `if` statement instead of `while` with condition variables, causing data corruption on spurious wakeups.
- **Verification & Mastery Check**: Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`, `not_empty`).
- **Project Application**: NanoHTTP: Thread pool task queue.', '{"solution.py": "# Phase 4 // Lesson 4.14: Condition Variables & Thread Signaling\n\ndef solve():\n    \"\"\"\n    Verification: Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.14", "subtopics_count": 4, "verification_criteria": "Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`, `not_empty`).", "subtopics": ["4.14.1 The need for Condition Variables: waiting for a state condition to become true without busy-waiting (spinning).", "4.14.2 Condition Variable primitives: `wait(mutex)` (atomically releases mutex and sleeps), `signal()` / `notify()`, `broadcast()`.", "4.14.3 Spurious Wakeups: why condition variables must ALWAYS be checked inside a `while (!condition)` loop.", "4.14.4 Lost Wakeups: signaling a condition variable before a waiting thread has entered the wait state."]}'::jsonb, '["Explain how this implementation prevents: Using an `if` statement instead of `while` with condition variables, causing data corruption on spurious wakeups.", "How does Condition Variables & Thread Signaling scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-15', 'phase-04-lesson-15-read-write-locks-reader-writer-priority-d', 'module-6', 15, 'Lesson 6.15: Read-Write Locks & Reader-Writer Priority Dilemmas', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 750.0, '# Lesson 4.15: Read-Write Locks & Reader-Writer Priority Dilemmas

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.15.1` Shared-Exclusive Locking (Read-Write Lock / `rwlock`): multiple concurrent readers OR single exclusive writer.
  - `4.15.2` Reader-Preference locks: allows continuous readers; risks Writer Starvation under heavy read traffic.
  - `4.15.3` Writer-Preference locks: incoming readers wait once a writer requests the lock; prevents writer starvation.
  - `4.15.4` Fair Read-Write locks: FIFO ordering of readers and writers.
- **Key Failure Modes & Edge Cases**: Writer starvation in read-heavy caches where writers are permanently blocked from updating expired cache keys.
- **Verification & Mastery Check**: Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read throughput vs standard mutex.
- **Project Application**: CacheKit: Multi-threaded cache design.', '{"solution.py": "# Phase 4 // Lesson 4.15: Read-Write Locks & Reader-Writer Priority Dilemmas\n\ndef solve():\n    \"\"\"\n    Verification: Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read thro\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.15", "subtopics_count": 4, "verification_criteria": "Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read throughput vs standard mutex.", "subtopics": ["4.15.1 Shared-Exclusive Locking (Read-Write Lock / `rwlock`): multiple concurrent readers OR single exclusive writer.", "4.15.2 Reader-Preference locks: allows continuous readers; risks Writer Starvation under heavy read traffic.", "4.15.3 Writer-Preference locks: incoming readers wait once a writer requests the lock; prevents writer starvation.", "4.15.4 Fair Read-Write locks: FIFO ordering of readers and writers."]}'::jsonb, '["Explain how this implementation prevents: Writer starvation in read-heavy caches where writers are permanently blocked from updating expired cache keys.", "How does Read-Write Locks & Reader-Writer Priority Dilemmas scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-16', 'phase-04-lesson-16-spinlocks-atomic-operations-compare-and-s', 'module-6', 16, 'Lesson 6.16: Spinlocks, Atomic Operations, & Compare-And-Swap (CAS)', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 800.0, '# Lesson 4.16: Spinlocks, Atomic Operations, & Compare-And-Swap (CAS)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.16.1` Spinlocks: busy-waiting in a tight loop checking a lock flag; optimal when lock hold time is less than context-switch cost.
  - `4.16.2` Atomic CPU Instructions: `LOCK CMPXCHG` (Compare-And-Swap), `LOCK XADD` (Fetch-And-Add).
  - `4.16.3` Lock-Free Programming concepts: building concurrent data structures without mutexes using CAS loops.
  - `4.16.4` The ABA Problem in lock-free structures: memory reuse masking intermediate state modifications.
- **Key Failure Modes & Edge Cases**: Using spinlocks on single-core systems or holding spinlocks while performing blocking I/O, freezing the CPU core.
- **Verification & Mastery Check**: Implement a lock-free concurrent counter using atomic Compare-And-Swap operations.
- **Project Application**: High-performance concurrency foundation.', '{"solution.py": "# Phase 4 // Lesson 4.16: Spinlocks, Atomic Operations, & Compare-And-Swap (CAS)\n\ndef solve():\n    \"\"\"\n    Verification: Implement a lock-free concurrent counter using atomic Compare-And-Swap operations.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.16", "subtopics_count": 4, "verification_criteria": "Implement a lock-free concurrent counter using atomic Compare-And-Swap operations.", "subtopics": ["4.16.1 Spinlocks: busy-waiting in a tight loop checking a lock flag; optimal when lock hold time is less than context-switch cost.", "4.16.2 Atomic CPU Instructions: `LOCK CMPXCHG` (Compare-And-Swap), `LOCK XADD` (Fetch-And-Add).", "4.16.3 Lock-Free Programming concepts: building concurrent data structures without mutexes using CAS loops.", "4.16.4 The ABA Problem in lock-free structures: memory reuse masking intermediate state modifications."]}'::jsonb, '["Explain how this implementation prevents: Using spinlocks on single-core systems or holding spinlocks while performing blocking I/O, freezing the CPU core.", "How does Spinlocks, Atomic Operations, & Compare-And-Swap (CAS) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-17', 'phase-04-lesson-17-the-producer-consumer-pattern-thread-pool', 'module-6', 17, 'Lesson 6.17: The Producer-Consumer Pattern & Thread Pools', 'Prerequisites: Lesson 4.14', 'Prerequisites: Lesson 4.14 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 850.0, '# Lesson 4.17: The Producer-Consumer Pattern & Thread Pools

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.14
- **Subtopics**:
  - `4.17.1` Architecture of the Producer-Consumer pattern: decoupling task generation from task processing via bounded buffer.
  - `4.17.2` Backpressure handling: blocking producers when the task buffer reaches high-water mark capacity.
  - `4.17.3` Thread Pool architecture: pre-allocated worker threads listening on a shared task queue.
  - `4.17.4` Graceful thread pool shutdown: poison pill / sentinel task patterns to terminate idle worker threads.
- **Key Failure Modes & Edge Cases**: Unbounded task queues growing infinitely during traffic spikes until the process crashes via Out-Of-Memory.
- **Verification & Mastery Check**: Build a complete multi-threaded Thread Pool from scratch in C or Python supporting task submission and graceful shutdown.
- **Project Application**: NanoHTTP: Multi-threaded request worker pool.', '{"solution.py": "# Phase 4 // Lesson 4.17: The Producer-Consumer Pattern & Thread Pools\n\ndef solve():\n    \"\"\"\n    Verification: Build a complete multi-threaded Thread Pool from scratch in C or Python supporting task submission a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.17", "subtopics_count": 4, "verification_criteria": "Build a complete multi-threaded Thread Pool from scratch in C or Python supporting task submission and graceful shutdown.", "subtopics": ["4.17.1 Architecture of the Producer-Consumer pattern: decoupling task generation from task processing via bounded buffer.", "4.17.2 Backpressure handling: blocking producers when the task buffer reaches high-water mark capacity.", "4.17.3 Thread Pool architecture: pre-allocated worker threads listening on a shared task queue.", "4.17.4 Graceful thread pool shutdown: poison pill / sentinel task patterns to terminate idle worker threads."]}'::jsonb, '["Explain how this implementation prevents: Unbounded task queues growing infinitely during traffic spikes until the process crashes via Out-Of-Memory.", "How does The Producer-Consumer Pattern & Thread Pools scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-18', 'phase-04-lesson-18-livelock-priority-inversion-starvation', 'module-6', 18, 'Lesson 6.18: Livelock, Priority Inversion, & Starvation', 'Prerequisites: Lesson 4.13', 'Prerequisites: Lesson 4.13 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 900.0, '# Lesson 4.18: Livelock, Priority Inversion, & Starvation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.13
- **Subtopics**:
  - `4.18.1` Livelock: threads actively changing state in response to each other without making forward progress (e.g., hallway passing problem).
  - `4.18.2` Starvation: thread repeatedly denied access to shared resources due to scheduling imbalances or greedy competitors.
  - `4.18.3` Priority Inversion: low-priority thread holding a lock required by high-priority thread; preempted by medium-priority thread.
  - `4.18.4` Priority Inheritance Protocol: temporarily boosting low-priority thread''s priority to match waiting high-priority thread.
- **Key Failure Modes & Edge Cases**: The Mars Pathfinder spacecraft reset incident: classic priority inversion between audio task and bus task.
- **Verification & Mastery Check**: Construct a simulation demonstrating priority inversion and implement a priority inheritance wrapper to resolve it.
- **Project Application**: Systems concurrency mastery.', '{"solution.py": "# Phase 4 // Lesson 4.18: Livelock, Priority Inversion, & Starvation\n\ndef solve():\n    \"\"\"\n    Verification: Construct a simulation demonstrating priority inversion and implement a priority inheritance wrapper\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.18", "subtopics_count": 4, "verification_criteria": "Construct a simulation demonstrating priority inversion and implement a priority inheritance wrapper to resolve it.", "subtopics": ["4.18.1 Livelock: threads actively changing state in response to each other without making forward progress (e.g., hallway passing problem).", "4.18.2 Starvation: thread repeatedly denied access to shared resources due to scheduling imbalances or greedy competitors.", "4.18.3 Priority Inversion: low-priority thread holding a lock required by high-priority thread; preempted by medium-priority thread.", "4.18.4 Priority Inheritance Protocol: temporarily boosting low-priority thread''s priority to match waiting high-priority thread."]}'::jsonb, '["Explain how this implementation prevents: The Mars Pathfinder spacecraft reset incident: classic priority inversion between audio task and bus task.", "How does Livelock, Priority Inversion, & Starvation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-19', 'phase-04-lesson-19-socket-abstractions-non-blocking-file-des', 'module-6', 19, 'Lesson 6.19: Socket Abstractions & Non-Blocking File Descriptors', 'Prerequisites: Phase 0 (Lesson 0.20)', 'Prerequisites: Phase 0 (Lesson 0.20) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 950.0, '# Lesson 4.19: Socket Abstractions & Non-Blocking File Descriptors

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.20)
- **Subtopics**:
  - `4.19.1` BSD Socket API: `socket()`, `bind()`, `listen()`, `accept()`, `connect()`, `send()`, `recv()`.
  - `4.19.2` Blocking Sockets: calls block thread execution until data arrives or OS buffer drains.
  - `4.19.3` Non-Blocking Sockets: setting `O_NONBLOCK` via `fcntl()`; returning `EWOULDBLOCK` or `EAGAIN` immediately.
  - `4.19.4` The C10K Problem: why thread-per-connection architectures collapse when scaling past 10,000 concurrent sockets.
- **Key Failure Modes & Edge Cases**: Calling `recv()` in a tight while loop on non-blocking sockets without I/O multiplexing, pinning CPU at 100%.
- **Verification & Mastery Check**: Create a non-blocking TCP socket server and handle `EWOULDBLOCK` exceptions cleanly.
- **Project Application**: NanoHTTP: Socket configuration.', '{"solution.py": "# Phase 4 // Lesson 4.19: Socket Abstractions & Non-Blocking File Descriptors\n\ndef solve():\n    \"\"\"\n    Verification: Create a non-blocking TCP socket server and handle `EWOULDBLOCK` exceptions cleanly.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.19", "subtopics_count": 4, "verification_criteria": "Create a non-blocking TCP socket server and handle `EWOULDBLOCK` exceptions cleanly.", "subtopics": ["4.19.1 BSD Socket API: `socket()`, `bind()`, `listen()`, `accept()`, `connect()`, `send()`, `recv()`.", "4.19.2 Blocking Sockets: calls block thread execution until data arrives or OS buffer drains.", "4.19.3 Non-Blocking Sockets: setting `O_NONBLOCK` via `fcntl()`; returning `EWOULDBLOCK` or `EAGAIN` immediately.", "4.19.4 The C10K Problem: why thread-per-connection architectures collapse when scaling past 10,000 concurrent sockets."]}'::jsonb, '["Explain how this implementation prevents: Calling `recv()` in a tight while loop on non-blocking sockets without I/O multiplexing, pinning CPU at 100%.", "How does Socket Abstractions & Non-Blocking File Descriptors scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-20', 'phase-04-lesson-20-evolution-of-multiplexing-select-and-poll', 'module-6', 20, 'Lesson 6.20: Evolution of Multiplexing: `select()` and `poll()`', 'Prerequisites: Lesson 4.19', 'Prerequisites: Lesson 4.19 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 1000.0, '# Lesson 4.20: Evolution of Multiplexing: `select()` and `poll()`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.19
- **Subtopics**:
  - `4.20.1` I/O Multiplexing concept: asking the OS kernel to monitor multiple file descriptors and notify when any are ready.
  - `4.20.2` `select()` mechanics: bitmap arrays of file descriptors (`fd_set`); 1024 FD limit (`FD_SETSIZE`); $O(n)$ scanning.
  - `4.20.3` `poll()` mechanics: array of `pollfd` structs; removing 1024 limit; still suffers from $O(n)$ kernel-user scanning.
  - `4.20.4` Why `select` and `poll` scale poorly: copying file descriptor arrays back and forth between user and kernel space on every call.
- **Key Failure Modes & Edge Cases**: Attempting to monitor 10,000 connections with `select()`, triggering buffer overflow or severe $O(n)$ latency penalties.
- **Verification & Mastery Check**: Write a server using `select()` that multiplexes 50 client connections and measure performance degradation as connection count increases.
- **Project Application**: Systems evolution understanding.', '{"solution.py": "# Phase 4 // Lesson 4.20: Evolution of Multiplexing: `select()` and `poll()`\n\ndef solve():\n    \"\"\"\n    Verification: Write a server using `select()` that multiplexes 50 client connections and measure performance degra\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.20", "subtopics_count": 4, "verification_criteria": "Write a server using `select()` that multiplexes 50 client connections and measure performance degradation as connection count increases.", "subtopics": ["4.20.1 I/O Multiplexing concept: asking the OS kernel to monitor multiple file descriptors and notify when any are ready.", "4.20.2 `select()` mechanics: bitmap arrays of file descriptors (`fd_set`); 1024 FD limit (`FD_SETSIZE`); $O(n)$ scanning.", "4.20.3 `poll()` mechanics: array of `pollfd` structs; removing 1024 limit; still suffers from $O(n)$ kernel-user scanning.", "4.20.4 Why `select` and `poll` scale poorly: copying file descriptor arrays back and forth between user and kernel space on every call."]}'::jsonb, '["Explain how this implementation prevents: Attempting to monitor 10,000 connections with `select()`, triggering buffer overflow or severe $O(n)$ latency penalties.", "How does Evolution of Multiplexing: `select()` and `poll()` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-21', 'phase-04-lesson-21-linux-epoll-architecture-red-black-trees-', 'module-6', 21, 'Lesson 6.21: Linux `epoll` Architecture: Red-Black Trees & Ready Lists', 'Prerequisites: Lesson 4.20', 'Prerequisites: Lesson 4.20 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 1050.0, '# Lesson 4.21: Linux `epoll` Architecture: Red-Black Trees & Ready Lists

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.20
- **Subtopics**:
  - `4.21.1` Why `epoll` is $O(1)$: kernel-maintained data structures persisting across system calls.
  - `4.21.2` The Interest List: Red-Black tree storing monitored file descriptors; efficient insertion, deletion, modification in $O(\log n)$.
  - `4.21.3` The Ready List: doubly linked list of file descriptors with ready I/O events; populated asynchronously by kernel driver callbacks.
  - `4.21.4` `epoll` system calls: `epoll_create1(EPOLL_CLOEXEC)`, `epoll_ctl()` (EPOLL_CTL_ADD, MOD, DEL), `epoll_wait()`.
- **Key Failure Modes & Edge Cases**: Failing to remove closed file descriptors from epoll sets, leading to spurious wakeups or memory leaks in older kernels.
- **Verification & Mastery Check**: Write a raw C or Python script invoking `epoll_create1`, registering sockets, and handling events via `epoll_wait`.
- **Project Application**: NanoHTTP: Version 2 (Async/Event-driven server).', '{"solution.py": "# Phase 4 // Lesson 4.21: Linux `epoll` Architecture: Red-Black Trees & Ready Lists\n\ndef solve():\n    \"\"\"\n    Verification: Write a raw C or Python script invoking `epoll_create1`, registering sockets, and handling events vi\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.21", "subtopics_count": 4, "verification_criteria": "Write a raw C or Python script invoking `epoll_create1`, registering sockets, and handling events via `epoll_wait`.", "subtopics": ["4.21.1 Why `epoll` is $O(1)$: kernel-maintained data structures persisting across system calls.", "4.21.2 The Interest List: Red-Black tree storing monitored file descriptors; efficient insertion, deletion, modification in $O(\\log n)$.", "4.21.3 The Ready List: doubly linked list of file descriptors with ready I/O events; populated asynchronously by kernel driver callbacks.", "4.21.4 `epoll` system calls: `epoll_create1(EPOLL_CLOEXEC)`, `epoll_ctl()` (EPOLL_CTL_ADD, MOD, DEL), `epoll_wait()`."]}'::jsonb, '["Explain how this implementation prevents: Failing to remove closed file descriptors from epoll sets, leading to spurious wakeups or memory leaks in older kernels.", "How does Linux `epoll` Architecture: Red-Black Trees & Ready Lists scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-22', 'phase-04-lesson-22-level-triggered-lt-vs-edge-triggered-et-e', 'module-6', 22, 'Lesson 6.22: Level-Triggered (LT) vs Edge-Triggered (ET) epoll', 'Prerequisites: Lesson 4.21', 'Prerequisites: Lesson 4.21 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 1100.0, '# Lesson 4.22: Level-Triggered (LT) vs Edge-Triggered (ET) epoll

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.21
- **Subtopics**:
  - `4.22.1` Level-Triggered (LT) mode: `epoll_wait()` returns as long as buffer has unread data (safe, forgiving default).
  - `4.22.2` Edge-Triggered (ET) mode (`EPOLLET`): `epoll_wait()` notifies ONLY on state change (data arrival transition).
  - `4.22.3` The Edge-Triggered contract: must read socket in a loop until it returns `EAGAIN` / `EWOULDBLOCK`.
  - `4.22.4` Starvation in ET: long-running loops reading a single chatty socket while other sockets wait in ready list.
- **Key Failure Modes & Edge Cases**: Using Edge-Triggered epoll but reading only once, causing the connection to hang indefinitely waiting for the next packet.
- **Verification & Mastery Check**: Implement an Edge-Triggered epoll event loop that correctly reads until `EAGAIN` and handles concurrent connections.
- **Project Application**: NanoHTTP: High-concurrency socket engine.', '{"solution.py": "# Phase 4 // Lesson 4.22: Level-Triggered (LT) vs Edge-Triggered (ET) epoll\n\ndef solve():\n    \"\"\"\n    Verification: Implement an Edge-Triggered epoll event loop that correctly reads until `EAGAIN` and handles concurr\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.22", "subtopics_count": 4, "verification_criteria": "Implement an Edge-Triggered epoll event loop that correctly reads until `EAGAIN` and handles concurrent connections.", "subtopics": ["4.22.1 Level-Triggered (LT) mode: `epoll_wait()` returns as long as buffer has unread data (safe, forgiving default).", "4.22.2 Edge-Triggered (ET) mode (`EPOLLET`): `epoll_wait()` notifies ONLY on state change (data arrival transition).", "4.22.3 The Edge-Triggered contract: must read socket in a loop until it returns `EAGAIN` / `EWOULDBLOCK`.", "4.22.4 Starvation in ET: long-running loops reading a single chatty socket while other sockets wait in ready list."]}'::jsonb, '["Explain how this implementation prevents: Using Edge-Triggered epoll but reading only once, causing the connection to hang indefinitely waiting for the next packe", "How does Level-Triggered (LT) vs Edge-Triggered (ET) epoll scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-23', 'phase-04-lesson-23-event-loop-architectures-reactor-vs-proac', 'module-6', 23, 'Lesson 6.23: Event Loop Architectures: Reactor vs Proactor Patterns', 'Prerequisites: Lesson 4.21', 'Prerequisites: Lesson 4.21 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 1150.0, '# Lesson 4.23: Event Loop Architectures: Reactor vs Proactor Patterns

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.21
- **Subtopics**:
  - `4.23.1` The Reactor Pattern: synchronous event demultiplexer notifying application event handlers when resources are ready (Node.js, Redis, Nginx, Python asyncio).
  - `4.23.2` The Proactor Pattern: asynchronous I/O completion framework; OS initiates I/O and notifies handlers upon completion (Windows IOCP, Linux io_uring).
  - `4.23.3` Linux `io_uring`: modern submission and completion ring buffers sharing memory between kernel and user space; zero syscalls.
  - `4.23.4` Thread-safe event loops: wake-up pipes / eventfd primitives for signaling event loops from other threads.
- **Key Failure Modes & Edge Cases**: Blocking the single-threaded Reactor event loop with synchronous CPU work, freezing all concurrent network connections.
- **Verification & Mastery Check**: Design and implement a single-threaded Reactor event loop from scratch handling timer events and network events.
- **Project Application**: Foundation for Phase 1 Python asyncio and Node.js in Phase 6.', '{"solution.py": "# Phase 4 // Lesson 4.23: Event Loop Architectures: Reactor vs Proactor Patterns\n\ndef solve():\n    \"\"\"\n    Verification: Design and implement a single-threaded Reactor event loop from scratch handling timer events and net\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.23", "subtopics_count": 4, "verification_criteria": "Design and implement a single-threaded Reactor event loop from scratch handling timer events and network events.", "subtopics": ["4.23.1 The Reactor Pattern: synchronous event demultiplexer notifying application event handlers when resources are ready (Node.js, Redis, Nginx, Python asyncio).", "4.23.2 The Proactor Pattern: asynchronous I/O completion framework; OS initiates I/O and notifies handlers upon completion (Windows IOCP, Linux io_uring).", "4.23.3 Linux `io_uring`: modern submission and completion ring buffers sharing memory between kernel and user space; zero syscalls.", "4.23.4 Thread-safe event loops: wake-up pipes / eventfd primitives for signaling event loops from other threads."]}'::jsonb, '["Explain how this implementation prevents: Blocking the single-threaded Reactor event loop with synchronous CPU work, freezing all concurrent network connections.", "How does Event Loop Architectures: Reactor vs Proactor Patterns scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-24', 'phase-04-lesson-24-socket-options-tuning-so-reuseaddr-so-reu', 'module-6', 24, 'Lesson 6.24: Socket Options & Tuning: `SO_REUSEADDR`, `SO_REUSEPORT`, `TCP_NODELAY`', 'Prerequisites: Phase 0 (Lesson 0.20), Lesson 4.19', 'Prerequisites: Phase 0 (Lesson 0.20), Lesson 4.19 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 1200.0, '# Lesson 4.24: Socket Options & Tuning: `SO_REUSEADDR`, `SO_REUSEPORT`, `TCP_NODELAY`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.20), Lesson 4.19
- **Subtopics**:
  - `4.24.1` `SO_REUSEADDR`: allowing immediate binding to a local address in `TIME_WAIT` state upon server restarts.
  - `4.24.2` `SO_REUSEPORT`: allowing multiple independent server sockets to bind to the exact same port; kernel-level load balancing across processes.
  - `4.24.3` `TCP_NODELAY`: disabling Nagle''s algorithm to eliminate artificial packet batching latency in real-time RPC protocols.
  - `4.24.4` Socket buffer sizing: `SO_RCVBUF` and `SO_SNDBUF`; TCP auto-tuning and bandwidth-delay product.
- **Key Failure Modes & Edge Cases**: `OSError: [Errno 98] Address already in use` upon server restarts caused by omitting `SO_REUSEADDR`.
- **Verification & Mastery Check**: Demonstrate server restart failure without `SO_REUSEADDR`, fix it, and benchmark latency reduction of `TCP_NODELAY`.
- **Project Application**: NanoHTTP: Mandatory socket configuration.', '{"solution.py": "# Phase 4 // Lesson 4.24: Socket Options & Tuning: `SO_REUSEADDR`, `SO_REUSEPORT`, `TCP_NODELAY`\n\ndef solve():\n    \"\"\"\n    Verification: Demonstrate server restart failure without `SO_REUSEADDR`, fix it, and benchmark latency reduction o\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.24", "subtopics_count": 4, "verification_criteria": "Demonstrate server restart failure without `SO_REUSEADDR`, fix it, and benchmark latency reduction of `TCP_NODELAY`.", "subtopics": ["4.24.1 `SO_REUSEADDR`: allowing immediate binding to a local address in `TIME_WAIT` state upon server restarts.", "4.24.2 `SO_REUSEPORT`: allowing multiple independent server sockets to bind to the exact same port; kernel-level load balancing across processes.", "4.24.3 `TCP_NODELAY`: disabling Nagle''s algorithm to eliminate artificial packet batching latency in real-time RPC protocols.", "4.24.4 Socket buffer sizing: `SO_RCVBUF` and `SO_SNDBUF`; TCP auto-tuning and bandwidth-delay product."]}'::jsonb, '["Explain how this implementation prevents: `OSError: [Errno 98] Address already in use` upon server restarts caused by omitting `SO_REUSEADDR`.", "How does Socket Options & Tuning: `SO_REUSEADDR`, `SO_REUSEPORT`, `TCP_NODELAY` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-25', 'phase-04-lesson-25-the-tcp-three-way-handshake-connection-st', 'module-6', 25, 'Lesson 6.25: The TCP Three-Way Handshake & Connection State Machine', 'Prerequisites: Phase 0 (Lesson 0.6)', 'Prerequisites: Phase 0 (Lesson 0.6) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 1250.0, '# Lesson 4.25: The TCP Three-Way Handshake & Connection State Machine

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.6)
- **Subtopics**:
  - `4.25.1` TCP Three-Way Handshake: SYN (Seq=x) $	o$ SYN-ACK (Seq=y, Ack=x+1) $	o$ ACK (Seq=x+1, Ack=y+1).
  - `4.25.2` TCP State Machine: LISTEN, SYN_SENT, SYN_RECEIVED, ESTABLISHED, FIN_WAIT_1, FIN_WAIT_2, CLOSE_WAIT, CLOSING, LAST_ACK, TIME_WAIT, CLOSED.
  - `4.25.3` SYN Flood attacks: half-open connections exhausting backlog queues; defense via SYN Cookies (`tcp_syncookies`).
  - `4.25.4` Connection teardown: four-way FIN handshake and `TIME_WAIT` duration (2MSL - Maximum Segment Lifetime, typically 60s).
- **Key Failure Modes & Edge Cases**: SYN backlog exhaustion crashing production servers during sudden traffic spikes.
- **Verification & Mastery Check**: Capture a complete TCP three-way handshake using `tcpdump` and inspect sequence numbers in Wireshark.
- **Project Application**: NanoHTTP: Connection lifecycle.', '{"solution.py": "# Phase 4 // Lesson 4.25: The TCP Three-Way Handshake & Connection State Machine\n\ndef solve():\n    \"\"\"\n    Verification: Capture a complete TCP three-way handshake using `tcpdump` and inspect sequence numbers in Wireshark\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.25", "subtopics_count": 4, "verification_criteria": "Capture a complete TCP three-way handshake using `tcpdump` and inspect sequence numbers in Wireshark.", "subtopics": ["4.25.1 TCP Three-Way Handshake: SYN (Seq=x) $\to$ SYN-ACK (Seq=y, Ack=x+1) $\to$ ACK (Seq=x+1, Ack=y+1).", "4.25.2 TCP State Machine: LISTEN, SYN_SENT, SYN_RECEIVED, ESTABLISHED, FIN_WAIT_1, FIN_WAIT_2, CLOSE_WAIT, CLOSING, LAST_ACK, TIME_WAIT, CLOSED.", "4.25.3 SYN Flood attacks: half-open connections exhausting backlog queues; defense via SYN Cookies (`tcp_syncookies`).", "4.25.4 Connection teardown: four-way FIN handshake and `TIME_WAIT` duration (2MSL - Maximum Segment Lifetime, typically 60s)."]}'::jsonb, '["Explain how this implementation prevents: SYN backlog exhaustion crashing production servers during sudden traffic spikes.", "How does The TCP Three-Way Handshake & Connection State Machine scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
