INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-0-21', 'phase-00-lesson-21-text-manipulation-string-methods-cleaning', 'module-1', 21, 'Lesson 1.21: Text Manipulation, String Methods & Cleaning', 'Prerequisites: Lesson 0.3', 'Prerequisites: Lesson 0.3 | Subtopics: 4 items', 'Systems project application', 100, 1, 0.0, 1050.0, '# Lesson 0.21: Text Manipulation, String Methods & Cleaning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.3
- **Subtopics**:
  - `0.21.1` Real-world text cleaning: stripping unwanted whitespace, tabs, and newlines (`strip`, `lstrip`, `rstrip`).
  - `0.21.2` Case transformations and normalization: `lower()`, `upper()`, and case-insensitive matching.
  - `0.21.3` Finding, counting, and replacing text patterns: `.find()`, `.count()`, and `.replace()`.
  - `0.21.4` Splitting and joining text: converting paragraphs to word lists with `.split()` and reconstructing with `.join()`.
- **Key Failure Modes & Edge Cases**: Modifying strings expecting them to change in-place; strings are immutable in Python, so the result must be reassigned.
- **Verification & Mastery Check**: Write a text sanitizer function that removes leading numbers, strips extraneous whitespace, and lowercases user prompts.
- **Project Application**: PromptCLI: Raw prompt preprocessing and token sanitization.', '{"solution.py": "# Phase 0 // Lesson 0.21: Text Manipulation, String Methods & Cleaning\n\ndef solve():\n    \"\"\"\n    Verification: Write a text sanitizer function that removes leading numbers, strips extraneous whitespace, and lowe\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.21", "subtopics_count": 4, "verification_criteria": "Write a text sanitizer function that removes leading numbers, strips extraneous whitespace, and lowercases user prompts.", "subtopics": ["0.21.1 Real-world text cleaning: stripping unwanted whitespace, tabs, and newlines (`strip`, `lstrip`, `rstrip`).", "0.21.2 Case transformations and normalization: `lower()`, `upper()`, and case-insensitive matching.", "0.21.3 Finding, counting, and replacing text patterns: `.find()`, `.count()`, and `.replace()`.", "0.21.4 Splitting and joining text: converting paragraphs to word lists with `.split()` and reconstructing with `.join()`."]}'::jsonb, '["Explain how this implementation prevents: Modifying strings expecting them to change in-place; strings are immutable in Python, so the result must be reassigned.", "How does Text Manipulation, String Methods & Cleaning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-22', 'phase-00-lesson-22-working-with-python-lists-collections', 'module-1', 22, 'Lesson 1.22: Working with Python Lists & Collections', 'Prerequisites: Lesson 0.6', 'Prerequisites: Lesson 0.6 | Subtopics: 4 items', 'Systems project application', 100, 1, 60.0, 1100.0, '# Lesson 0.22: Working with Python Lists & Collections

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.6
- **Subtopics**:
  - `0.22.1` The Python List: storing ordered collections of items in numbered positions.
  - `0.22.2` Modifying lists: `.append()`, `.extend()`, `.insert()`, `.pop()`, and `.remove()`.
  - `0.22.3` Slicing lists: extracting sub-lists with `[start:stop:step]` syntax.
  - `0.22.4` Checking membership: using `in` and `not in` to test if an item exists in a collection.
- **Key Failure Modes & Edge Cases**: Calling `.pop()` or accessing an index on an empty list, triggering an `IndexError`.
- **Verification & Mastery Check**: Build a conversation history list where new messages are appended, and only the 5 most recent turns are retained.
- **Project Application**: PromptCLI: Multi-turn chat message history buffer.', '{"solution.py": "# Phase 0 // Lesson 0.22: Working with Python Lists & Collections\n\ndef solve():\n    \"\"\"\n    Verification: Build a conversation history list where new messages are appended, and only the 5 most recent turns \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.22", "subtopics_count": 4, "verification_criteria": "Build a conversation history list where new messages are appended, and only the 5 most recent turns are retained.", "subtopics": ["0.22.1 The Python List: storing ordered collections of items in numbered positions.", "0.22.2 Modifying lists: `.append()`, `.extend()`, `.insert()`, `.pop()`, and `.remove()`.", "0.22.3 Slicing lists: extracting sub-lists with `[start:stop:step]` syntax.", "0.22.4 Checking membership: using `in` and `not in` to test if an item exists in a collection."]}'::jsonb, '["Explain how this implementation prevents: Calling `.pop()` or accessing an index on an empty list, triggering an `IndexError`.", "How does Working with Python Lists & Collections scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-23', 'phase-00-lesson-23-list-comprehensions-data-transformations', 'module-1', 23, 'Lesson 1.23: List Comprehensions & Data Transformations', 'Prerequisites: Lesson 0.22', 'Prerequisites: Lesson 0.22 | Subtopics: 4 items', 'Systems project application', 100, 1, 120.0, 1150.0, '# Lesson 0.23: List Comprehensions & Data Transformations

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.22
- **Subtopics**:
  - `0.23.1` The List Comprehension syntax: transforming lists in a single readable line.
  - `0.23.2` Filtering with conditionals: `[item for item in items if condition]`.
  - `0.23.3` Transforming text data: stripping and normalizing an entire batch of inputs at once.
  - `0.23.4` When to use comprehensions vs regular loops for clean, maintainable code.
- **Key Failure Modes & Edge Cases**: Nesting three or more list comprehensions, creating unreadable "clever" code that teammates cannot debug.
- **Verification & Mastery Check**: Take a list of raw user inputs and produce a cleaned list of non-empty prompts in a single comprehension.
- **Project Application**: PromptCLI: Batch prompt cleanup and extraction.', '{"solution.py": "# Phase 0 // Lesson 0.23: List Comprehensions & Data Transformations\n\ndef solve():\n    \"\"\"\n    Verification: Take a list of raw user inputs and produce a cleaned list of non-empty prompts in a single comprehen\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.23", "subtopics_count": 4, "verification_criteria": "Take a list of raw user inputs and produce a cleaned list of non-empty prompts in a single comprehension.", "subtopics": ["0.23.1 The List Comprehension syntax: transforming lists in a single readable line.", "0.23.2 Filtering with conditionals: `[item for item in items if condition]`.", "0.23.3 Transforming text data: stripping and normalizing an entire batch of inputs at once.", "0.23.4 When to use comprehensions vs regular loops for clean, maintainable code."]}'::jsonb, '["Explain how this implementation prevents: Nesting three or more list comprehensions, creating unreadable \"clever\" code that teammates cannot debug.", "How does List Comprehensions & Data Transformations scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-24', 'phase-00-lesson-24-dictionaries-keys-values-fast-lookups', 'module-1', 24, 'Lesson 1.24: Dictionaries: Keys, Values & Fast Lookups', 'Prerequisites: Lesson 0.22', 'Prerequisites: Lesson 0.22 | Subtopics: 4 items', 'Systems project application', 100, 1, 0.0, 1200.0, '# Lesson 0.24: Dictionaries: Keys, Values & Fast Lookups

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.22
- **Subtopics**:
  - `0.24.1` The Dictionary mental model: pairing unique keys with stored values (like a phone contact list).
  - `0.24.2` Adding, updating, and removing dictionary entries.
  - `0.24.3` Safe lookups: using `.get(key, default)` to prevent unhandled `KeyError` crashes.
  - `0.24.4` Iterating over dictionaries: accessing `.keys()`, `.values()`, and `.items()`.
- **Key Failure Modes & Edge Cases**: Accessing a missing dictionary key with brackets (`dict[key]`) rather than `.get()`, crashing the application.
- **Verification & Mastery Check**: Build a model pricing dictionary and look up the per-token cost for an arbitrary model name safely.
- **Project Application**: PromptCLI: Dynamic AI model parameter and pricing lookup.', '{"solution.py": "# Phase 0 // Lesson 0.24: Dictionaries: Keys, Values & Fast Lookups\n\ndef solve():\n    \"\"\"\n    Verification: Build a model pricing dictionary and look up the per-token cost for an arbitrary model name safely.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.24", "subtopics_count": 4, "verification_criteria": "Build a model pricing dictionary and look up the per-token cost for an arbitrary model name safely.", "subtopics": ["0.24.1 The Dictionary mental model: pairing unique keys with stored values (like a phone contact list).", "0.24.2 Adding, updating, and removing dictionary entries.", "0.24.3 Safe lookups: using `.get(key, default)` to prevent unhandled `KeyError` crashes.", "0.24.4 Iterating over dictionaries: accessing `.keys()`, `.values()`, and `.items()`."]}'::jsonb, '["Explain how this implementation prevents: Accessing a missing dictionary key with brackets (`dict[key]`) rather than `.get()`, crashing the application.", "How does Dictionaries: Keys, Values & Fast Lookups scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-25', 'phase-00-lesson-25-sets-unique-item-filtering', 'module-1', 25, 'Lesson 1.25: Sets & Unique Item Filtering', 'Prerequisites: Lesson 0.24', 'Prerequisites: Lesson 0.24 | Subtopics: 4 items', 'Systems project application', 100, 1, 60.0, 1250.0, '# Lesson 0.25: Sets & Unique Item Filtering

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.24
- **Subtopics**:
  - `0.25.1` What is a Set: an unordered collection that automatically enforces uniqueness.
  - `0.25.2` Instant deduplication: turning lists into sets with `set(my_list)`.
  - `0.25.3` Fast membership testing: why checking `item in my_set` is lightning-fast compared to lists.
  - `0.25.4` Set operations: union, intersection, and difference between collections.
- **Key Failure Modes & Edge Cases**: Trying to index into a set with `my_set[0]`; sets are unordered and do not support indexing.
- **Verification & Mastery Check**: Given a list of 1,000 prompt tags with duplicates, extract the unique tags and find overlapping tags with a whitelist.
- **Project Application**: PromptCLI: User prompt tag deduplication and stopword filtering.', '{"solution.py": "# Phase 0 // Lesson 0.25: Sets & Unique Item Filtering\n\ndef solve():\n    \"\"\"\n    Verification: Given a list of 1,000 prompt tags with duplicates, extract the unique tags and find overlapping tags\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.25", "subtopics_count": 4, "verification_criteria": "Given a list of 1,000 prompt tags with duplicates, extract the unique tags and find overlapping tags with a whitelist.", "subtopics": ["0.25.1 What is a Set: an unordered collection that automatically enforces uniqueness.", "0.25.2 Instant deduplication: turning lists into sets with `set(my_list)`.", "0.25.3 Fast membership testing: why checking `item in my_set` is lightning-fast compared to lists.", "0.25.4 Set operations: union, intersection, and difference between collections."]}'::jsonb, '["Explain how this implementation prevents: Trying to index into a set with `my_set[0]`; sets are unordered and do not support indexing.", "How does Sets & Unique Item Filtering scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-26', 'phase-00-lesson-26-reading-and-writing-files-in-python', 'module-1', 26, 'Lesson 1.26: Reading and Writing Files in Python', 'Prerequisites: Lesson 0.8', 'Prerequisites: Lesson 0.8 | Subtopics: 4 items', 'Systems project application', 100, 1, 120.0, 1300.0, '# Lesson 0.26: Reading and Writing Files in Python

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.8
- **Subtopics**:
  - `0.26.1` The file system mental model: folders, files, relative paths vs absolute paths.
  - `0.26.2` Opening files safely: the `with open(...) as f:` context manager that closes files automatically.
  - `0.26.3` Reading files: `.read()`, `.readline()`, and iterating over lines efficiently.
  - `0.26.4` Writing files: write mode (`"w"`) vs append mode (`"a"`).
- **Key Failure Modes & Edge Cases**: Using write mode (`"w"`) instead of append mode (`"a"`), accidentally erasing existing file contents.
- **Verification & Mastery Check**: Write a script that reads a prompt template from a `.txt` file, substitutes the user''s name, and appends the result to a log file.
- **Project Application**: PromptCLI: Local prompt template loading and output logging.', '{"solution.py": "# Phase 0 // Lesson 0.26: Reading and Writing Files in Python\n\ndef solve():\n    \"\"\"\n    Verification: Write a script that reads a prompt template from a `.txt` file, substitutes the user''s name, and app\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.26", "subtopics_count": 4, "verification_criteria": "Write a script that reads a prompt template from a `.txt` file, substitutes the user''s name, and appends the result to a log file.", "subtopics": ["0.26.1 The file system mental model: folders, files, relative paths vs absolute paths.", "0.26.2 Opening files safely: the `with open(...) as f:` context manager that closes files automatically.", "0.26.3 Reading files: `.read()`, `.readline()`, and iterating over lines efficiently.", "0.26.4 Writing files: write mode (`\"w\"`) vs append mode (`\"a\"`)."]}'::jsonb, '["Explain how this implementation prevents: Using write mode (`\"w\"`) instead of append mode (`\"a\"`), accidentally erasing existing file contents.", "How does Reading and Writing Files in Python scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-27', 'phase-00-lesson-27-json-data-serialization-and-parsing', 'module-1', 27, 'Lesson 1.27: JSON Data: Serialization and Parsing', 'Prerequisites: Lesson 0.24, Lesson 0.26', 'Prerequisites: Lesson 0.24, Lesson 0.26 | Subtopics: 4 items', 'Systems project application', 100, 1, 0.0, 1350.0, '# Lesson 0.27: JSON Data: Serialization and Parsing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.24, Lesson 0.26
- **Subtopics**:
  - `0.27.1` What is JSON: the universal data format used by modern web apps and AI APIs.
  - `0.27.2` Parsing JSON text into Python dictionaries using `json.loads()`.
  - `0.27.3` Serializing Python dictionaries into JSON text using `json.dumps()`.
  - `0.27.4` Reading and writing `.json` files directly with `json.load()` and `json.dump()`.
- **Key Failure Modes & Edge Cases**: Passing invalid JSON strings (like single quotes or trailing commas) to `json.loads()`, causing `JSONDecodeError`.
- **Verification & Mastery Check**: Parse a simulated LLM JSON response string, extract the message content, and save the structured record to `session.json`.
- **Project Application**: PromptCLI: Configuration management and structured response logging.', '{"solution.py": "# Phase 0 // Lesson 0.27: JSON Data: Serialization and Parsing\n\ndef solve():\n    \"\"\"\n    Verification: Parse a simulated LLM JSON response string, extract the message content, and save the structured rec\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.27", "subtopics_count": 4, "verification_criteria": "Parse a simulated LLM JSON response string, extract the message content, and save the structured record to `session.json`.", "subtopics": ["0.27.1 What is JSON: the universal data format used by modern web apps and AI APIs.", "0.27.2 Parsing JSON text into Python dictionaries using `json.loads()`.", "0.27.3 Serializing Python dictionaries into JSON text using `json.dumps()`.", "0.27.4 Reading and writing `.json` files directly with `json.load()` and `json.dump()`."]}'::jsonb, '["Explain how this implementation prevents: Passing invalid JSON strings (like single quotes or trailing commas) to `json.loads()`, causing `JSONDecodeError`.", "How does JSON Data: Serialization and Parsing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-28', 'phase-00-lesson-28-error-handling-try-except-graceful-recove', 'module-1', 28, 'Lesson 1.28: Error Handling: try, except & Graceful Recovery', 'Prerequisites: Lesson 0.8', 'Prerequisites: Lesson 0.8 | Subtopics: 4 items', 'Systems project application', 100, 1, 60.0, 1400.0, '# Lesson 0.28: Error Handling: try, except & Graceful Recovery

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.8
- **Subtopics**:
  - `0.28.1` Why programs fail: syntax errors vs runtime exceptions.
  - `0.28.2` Catching errors with `try` and `except`: keeping your application running when inputs are invalid.
  - `0.28.3` Specific exception types: `ValueError`, `KeyError`, `FileNotFoundError`, `TypeError`.
  - `0.28.4` The `finally` and `else` blocks: running cleanup routines reliably.
- **Key Failure Modes & Edge Cases**: Using a bare `except:` clause without specifying the error type, silently masking fatal bugs.
- **Verification & Mastery Check**: Write a robust file-reading function that catches `FileNotFoundError` and returns a friendly default prompt without crashing.
- **Project Application**: PromptCLI: Resilient input parser and configuration loader.', '{"solution.py": "# Phase 0 // Lesson 0.28: Error Handling: try, except & Graceful Recovery\n\ndef solve():\n    \"\"\"\n    Verification: Write a robust file-reading function that catches `FileNotFoundError` and returns a friendly default\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.28", "subtopics_count": 4, "verification_criteria": "Write a robust file-reading function that catches `FileNotFoundError` and returns a friendly default prompt without crashing.", "subtopics": ["0.28.1 Why programs fail: syntax errors vs runtime exceptions.", "0.28.2 Catching errors with `try` and `except`: keeping your application running when inputs are invalid.", "0.28.3 Specific exception types: `ValueError`, `KeyError`, `FileNotFoundError`, `TypeError`.", "0.28.4 The `finally` and `else` blocks: running cleanup routines reliably."]}'::jsonb, '["Explain how this implementation prevents: Using a bare `except:` clause without specifying the error type, silently masking fatal bugs.", "How does Error Handling: try, except & Graceful Recovery scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-29', 'phase-00-lesson-29-environment-variables-secrets-management', 'module-1', 29, 'Lesson 1.29: Environment Variables & Secrets Management', 'Prerequisites: Lesson 0.26', 'Prerequisites: Lesson 0.26 | Subtopics: 4 items', 'Systems project application', 100, 1, 120.0, 1450.0, '# Lesson 0.29: Environment Variables & Secrets Management

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.26
- **Subtopics**:
  - `0.29.1` Why hardcoding secrets is dangerous: keeping API keys out of Git repositories.
  - `0.29.2` Reading environment variables with Python''s built-in `os.environ` and `os.getenv()`.
  - `0.29.3` Using `.env` files locally with `python-dotenv`.
  - `0.29.4` The `.gitignore` file: preventing secrets and local caches from ever being committed to GitHub.
- **Key Failure Modes & Edge Cases**: Committing an un-ignored `.env` file to a public repository, exposing production AI API keys.
- **Verification & Mastery Check**: Configure a script that loads an `OPENAI_API_KEY` from a local `.env` file, printing an error if the key is missing.
- **Project Application**: PromptCLI: Secure API key configuration manager.', '{"solution.py": "# Phase 0 // Lesson 0.29: Environment Variables & Secrets Management\n\ndef solve():\n    \"\"\"\n    Verification: Configure a script that loads an `OPENAI_API_KEY` from a local `.env` file, printing an error if the\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.29", "subtopics_count": 4, "verification_criteria": "Configure a script that loads an `OPENAI_API_KEY` from a local `.env` file, printing an error if the key is missing.", "subtopics": ["0.29.1 Why hardcoding secrets is dangerous: keeping API keys out of Git repositories.", "0.29.2 Reading environment variables with Python''s built-in `os.environ` and `os.getenv()`.", "0.29.3 Using `.env` files locally with `python-dotenv`.", "0.29.4 The `.gitignore` file: preventing secrets and local caches from ever being committed to GitHub."]}'::jsonb, '["Explain how this implementation prevents: Committing an un-ignored `.env` file to a public repository, exposing production AI API keys.", "How does Environment Variables & Secrets Management scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-30', 'phase-00-lesson-30-making-http-get-and-post-requests-with-ht', 'module-1', 30, 'Lesson 1.30: Making HTTP GET and POST Requests with HTTPX', 'Prerequisites: Lesson 0.27, Lesson 0.29', 'Prerequisites: Lesson 0.27, Lesson 0.29 | Subtopics: 4 items', 'Systems project application', 100, 1, 0.0, 1500.0, '# Lesson 0.30: Making HTTP GET and POST Requests with HTTPX

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.27, Lesson 0.29
- **Subtopics**:
  - `0.30.1` The Client-Server model: how your computer talks to remote API servers across the internet.
  - `0.30.2` HTTP verbs: GET (fetching data) vs POST (submitting prompts and payloads).
  - `0.30.3` Sending headers: authentication tokens (`Bearer ...`) and Content-Type (`application/json`).
  - `0.30.4` Checking status codes: 200 (OK), 400 (Bad Request), 401 (Unauthorized), 429 (Rate Limited), 500 (Server Error).
- **Key Failure Modes & Edge Cases**: Forgetting to check `.status_code` or call `.raise_for_status()`, leading to subtle bugs on failed requests.
- **Verification & Mastery Check**: Send an HTTP POST request to a mock JSON endpoint using `httpx` and verify the status code is 200.
- **Project Application**: PromptCLI: Remote AI inference gateway client.', '{"solution.py": "# Phase 0 // Lesson 0.30: Making HTTP GET and POST Requests with HTTPX\n\ndef solve():\n    \"\"\"\n    Verification: Send an HTTP POST request to a mock JSON endpoint using `httpx` and verify the status code is 200.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.30", "subtopics_count": 4, "verification_criteria": "Send an HTTP POST request to a mock JSON endpoint using `httpx` and verify the status code is 200.", "subtopics": ["0.30.1 The Client-Server model: how your computer talks to remote API servers across the internet.", "0.30.2 HTTP verbs: GET (fetching data) vs POST (submitting prompts and payloads).", "0.30.3 Sending headers: authentication tokens (`Bearer ...`) and Content-Type (`application/json`).", "0.30.4 Checking status codes: 200 (OK), 400 (Bad Request), 401 (Unauthorized), 429 (Rate Limited), 500 (Server Error)."]}'::jsonb, '["Explain how this implementation prevents: Forgetting to check `.status_code` or call `.raise_for_status()`, leading to subtle bugs on failed requests.", "How does Making HTTP GET and POST Requests with HTTPX scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-31', 'phase-00-lesson-31-handling-network-timeouts-exponential-bac', 'module-1', 31, 'Lesson 1.31: Handling Network Timeouts & Exponential Backoff', 'Prerequisites: Lesson 0.30', 'Prerequisites: Lesson 0.30 | Subtopics: 4 items', 'Systems project application', 100, 1, 60.0, 1550.0, '# Lesson 0.31: Handling Network Timeouts & Exponential Backoff

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.30
- **Subtopics**:
  - `0.31.1` Transient network failures: why remote API calls will inevitably fail in production.
  - `0.31.2` Setting request timeouts: preventing programs from hanging forever when servers lag.
  - `0.31.3` The Exponential Backoff algorithm: waiting 1s, 2s, 4s before retrying to prevent overwhelming servers.
  - `0.31.4` Adding random jitter: avoiding retry storms across distributed clients.
- **Key Failure Modes & Edge Cases**: Retrying immediately in a tight `while` loop without backoff, getting your IP permanently rate-limited.
- **Verification & Mastery Check**: Implement a retry loop that retries a failing simulated HTTP request up to 3 times with exponential backoff.
- **Project Application**: PromptCLI: Automated network retry resilience engine.', '{"solution.py": "# Phase 0 // Lesson 0.31: Handling Network Timeouts & Exponential Backoff\n\ndef solve():\n    \"\"\"\n    Verification: Implement a retry loop that retries a failing simulated HTTP request up to 3 times with exponential \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.31", "subtopics_count": 4, "verification_criteria": "Implement a retry loop that retries a failing simulated HTTP request up to 3 times with exponential backoff.", "subtopics": ["0.31.1 Transient network failures: why remote API calls will inevitably fail in production.", "0.31.2 Setting request timeouts: preventing programs from hanging forever when servers lag.", "0.31.3 The Exponential Backoff algorithm: waiting 1s, 2s, 4s before retrying to prevent overwhelming servers.", "0.31.4 Adding random jitter: avoiding retry storms across distributed clients."]}'::jsonb, '["Explain how this implementation prevents: Retrying immediately in a tight `while` loop without backoff, getting your IP permanently rate-limited.", "How does Handling Network Timeouts & Exponential Backoff scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-32', 'phase-00-lesson-32-parsing-xml-markdown-unstructured-ai-text', 'module-1', 32, 'Lesson 1.32: Parsing XML, Markdown & Unstructured AI Text', 'Prerequisites: Lesson 0.21', 'Prerequisites: Lesson 0.21 | Subtopics: 4 items', 'Systems project application', 100, 1, 120.0, 1600.0, '# Lesson 0.32: Parsing XML, Markdown & Unstructured AI Text

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.21
- **Subtopics**:
  - `0.32.1` The reality of AI outputs: why models often return markdown code blocks, XML tags, or conversational text.
  - `0.32.2` Extracting text between XML tags (e.g., `<thought>...</thought>` or `<answer>...</answer>`).
  - `0.32.3` Stripping markdown code fences: extracting clean JSON from ` ```json ... ``` ` blocks.
  - `0.32.4` Regular expressions for text extraction: using `re.search()` to isolate structured patterns.
- **Key Failure Modes & Edge Cases**: Assuming an LLM will return pure JSON without markdown backticks, causing `json.loads()` to crash.
- **Verification & Mastery Check**: Write a robust extractor that extracts valid JSON from a response string wrapped in conversational filler and markdown fences.
- **Project Application**: PromptCLI: Response parser and code block extractor.', '{"solution.py": "# Phase 0 // Lesson 0.32: Parsing XML, Markdown & Unstructured AI Text\n\ndef solve():\n    \"\"\"\n    Verification: Write a robust extractor that extracts valid JSON from a response string wrapped in conversational f\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.32", "subtopics_count": 4, "verification_criteria": "Write a robust extractor that extracts valid JSON from a response string wrapped in conversational filler and markdown fences.", "subtopics": ["0.32.1 The reality of AI outputs: why models often return markdown code blocks, XML tags, or conversational text.", "0.32.2 Extracting text between XML tags (e.g., `<thought>...</thought>` or `<answer>...</answer>`).", "0.32.3 Stripping markdown code fences: extracting clean JSON from ` ```json ... ``` ` blocks.", "0.32.4 Regular expressions for text extraction: using `re.search()` to isolate structured patterns."]}'::jsonb, '["Explain how this implementation prevents: Assuming an LLM will return pure JSON without markdown backticks, causing `json.loads()` to crash.", "How does Parsing XML, Markdown & Unstructured AI Text scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-33', 'phase-00-lesson-33-command-line-arguments-with-argparse', 'module-1', 33, 'Lesson 1.33: Command-Line Arguments with Argparse', 'Prerequisites: Lesson 0.8', 'Prerequisites: Lesson 0.8 | Subtopics: 4 items', 'Systems project application', 100, 1, 0.0, 1650.0, '# Lesson 0.33: Command-Line Arguments with Argparse

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.8
- **Subtopics**:
  - `0.33.1` Why CLI tools matter: running scripts with flags and options directly from the terminal.
  - `0.33.2` Python''s `argparse` module: defining positional arguments and optional flags (`--model`, `--temp`).
  - `0.33.3` Type casting and default values: automatically converting string inputs to integers or floats.
  - `0.33.4` Generating automated help menus: `--help` documentation generated directly from argument descriptions.
- **Key Failure Modes & Edge Cases**: Failing to provide help descriptions, making command-line tools impossible for teammates to use.
- **Verification & Mastery Check**: Build a CLI script `prompt_tool.py` that takes `--prompt`, `--temperature`, and `--verbose` flags and prints the settings.
- **Project Application**: PromptCLI: Terminal CLI argument parsing interface.', '{"solution.py": "# Phase 0 // Lesson 0.33: Command-Line Arguments with Argparse\n\ndef solve():\n    \"\"\"\n    Verification: Build a CLI script `prompt_tool.py` that takes `--prompt`, `--temperature`, and `--verbose` flags an\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.33", "subtopics_count": 4, "verification_criteria": "Build a CLI script `prompt_tool.py` that takes `--prompt`, `--temperature`, and `--verbose` flags and prints the settings.", "subtopics": ["0.33.1 Why CLI tools matter: running scripts with flags and options directly from the terminal.", "0.33.2 Python''s `argparse` module: defining positional arguments and optional flags (`--model`, `--temp`).", "0.33.3 Type casting and default values: automatically converting string inputs to integers or floats.", "0.33.4 Generating automated help menus: `--help` documentation generated directly from argument descriptions."]}'::jsonb, '["Explain how this implementation prevents: Failing to provide help descriptions, making command-line tools impossible for teammates to use.", "How does Command-Line Arguments with Argparse scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-34', 'phase-00-lesson-34-packaging-reusable-modules-python-imports', 'module-1', 34, 'Lesson 1.34: Packaging Reusable Modules & Python Imports', 'Prerequisites: Lesson 0.8', 'Prerequisites: Lesson 0.8 | Subtopics: 4 items', 'Systems project application', 100, 1, 60.0, 1700.0, '# Lesson 0.34: Packaging Reusable Modules & Python Imports

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.8
- **Subtopics**:
  - `0.34.1` Breaking scripts into modules: separating logic into multiple `.py` files.
  - `0.34.2` Import statements: `import utils`, `from config import MODEL_NAME`.
  - `0.34.3` The `if __name__ == "__main__":` idiom: making files both importable modules and executable scripts.
  - `0.34.4` Creating packages: using folders and `__init__.py` to organize multi-file projects.
- **Key Failure Modes & Edge Cases**: Circular imports where module A imports module B and module B imports module A, causing import crashes.
- **Verification & Mastery Check**: Organize a 3-file project (`main.py`, `prompt_templates.py`, `api_client.py`) and successfully run the application.
- **Project Application**: PromptCLI: Modular codebase architecture.', '{"solution.py": "# Phase 0 // Lesson 0.34: Packaging Reusable Modules & Python Imports\n\ndef solve():\n    \"\"\"\n    Verification: Organize a 3-file project (`main.py`, `prompt_templates.py`, `api_client.py`) and successfully run t\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.34", "subtopics_count": 4, "verification_criteria": "Organize a 3-file project (`main.py`, `prompt_templates.py`, `api_client.py`) and successfully run the application.", "subtopics": ["0.34.1 Breaking scripts into modules: separating logic into multiple `.py` files.", "0.34.2 Import statements: `import utils`, `from config import MODEL_NAME`.", "0.34.3 The `if __name__ == \"__main__\":` idiom: making files both importable modules and executable scripts.", "0.34.4 Creating packages: using folders and `__init__.py` to organize multi-file projects."]}'::jsonb, '["Explain how this implementation prevents: Circular imports where module A imports module B and module B imports module A, causing import crashes.", "How does Packaging Reusable Modules & Python Imports scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-35', 'phase-00-lesson-35-virtual-environments-modern-package-manag', 'module-1', 35, 'Lesson 1.35: Virtual Environments & Modern Package Management (uv / pip)', 'Prerequisites: Lesson 0.34', 'Prerequisites: Lesson 0.34 | Subtopics: 4 items', 'Systems project application', 100, 1, 120.0, 1750.0, '# Lesson 0.35: Virtual Environments & Modern Package Management (uv / pip)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.34
- **Subtopics**:
  - `0.35.1` Why virtual environments exist: preventing dependency version conflicts across projects.
  - `0.35.2` Creating and activating environments with `python -m venv .venv`.
  - `0.35.3` Installing dependencies with `pip install` and generating `requirements.txt`.
  - `0.35.4` Ultra-fast modern package management with `uv`: lightning-fast dependency resolution.
- **Key Failure Modes & Edge Cases**: Installing packages into the global system Python instead of an active virtual environment.
- **Verification & Mastery Check**: Create an isolated `.venv`, install `httpx` and `pydantic`, and export a pinned `requirements.txt`.
- **Project Application**: PromptCLI: Isolated dependency blueprint.', '{"solution.py": "# Phase 0 // Lesson 0.35: Virtual Environments & Modern Package Management (uv / pip)\n\ndef solve():\n    \"\"\"\n    Verification: Create an isolated `.venv`, install `httpx` and `pydantic`, and export a pinned `requirements.txt`.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.35", "subtopics_count": 4, "verification_criteria": "Create an isolated `.venv`, install `httpx` and `pydantic`, and export a pinned `requirements.txt`.", "subtopics": ["0.35.1 Why virtual environments exist: preventing dependency version conflicts across projects.", "0.35.2 Creating and activating environments with `python -m venv .venv`.", "0.35.3 Installing dependencies with `pip install` and generating `requirements.txt`.", "0.35.4 Ultra-fast modern package management with `uv`: lightning-fast dependency resolution."]}'::jsonb, '["Explain how this implementation prevents: Installing packages into the global system Python instead of an active virtual environment.", "How does Virtual Environments & Modern Package Management (uv / pip) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-36', 'phase-00-lesson-36-modern-python-type-hints-static-typing', 'module-1', 36, 'Lesson 1.36: Modern Python Type Hints & Static Typing', 'Prerequisites: Lesson 0.8', 'Prerequisites: Lesson 0.8 | Subtopics: 4 items', 'Systems project application', 100, 1, 0.0, 1800.0, '# Lesson 0.36: Modern Python Type Hints & Static Typing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.8
- **Subtopics**:
  - `0.36.1` Why type hints matter: catching bugs before running code and unlocking superior IDE autocomplete.
  - `0.36.2` Basic type annotations: `name: str`, `age: int`, `score: float`, `is_active: bool`.
  - `0.36.3` Container types: `list[str]`, `dict[str, int]`, `tuple[int, int]`.
  - `0.36.4` Optional and Union types: `str | None` for values that might be missing.
- **Key Failure Modes & Edge Cases**: Assuming Python enforces types at runtime; type hints are for static analysis and tools like Mypy/IDE, not runtime checks.
- **Verification & Mastery Check**: Annotate a prompt-formatting function with full parameter and return types, verifying it with `mypy`.
- **Project Application**: PromptCLI: Type-safe prompt orchestration pipeline.', '{"solution.py": "# Phase 0 // Lesson 0.36: Modern Python Type Hints & Static Typing\n\ndef solve():\n    \"\"\"\n    Verification: Annotate a prompt-formatting function with full parameter and return types, verifying it with `mypy`\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.36", "subtopics_count": 4, "verification_criteria": "Annotate a prompt-formatting function with full parameter and return types, verifying it with `mypy`.", "subtopics": ["0.36.1 Why type hints matter: catching bugs before running code and unlocking superior IDE autocomplete.", "0.36.2 Basic type annotations: `name: str`, `age: int`, `score: float`, `is_active: bool`.", "0.36.3 Container types: `list[str]`, `dict[str, int]`, `tuple[int, int]`.", "0.36.4 Optional and Union types: `str | None` for values that might be missing."]}'::jsonb, '["Explain how this implementation prevents: Assuming Python enforces types at runtime; type hints are for static analysis and tools like Mypy/IDE, not runtime check", "How does Modern Python Type Hints & Static Typing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-37', 'phase-00-lesson-37-introduction-to-pydantic-data-validation-', 'module-1', 37, 'Lesson 1.37: Introduction to Pydantic: Data Validation from Scratch', 'Prerequisites: Lesson 0.36', 'Prerequisites: Lesson 0.36 | Subtopics: 4 items', 'Systems project application', 100, 1, 60.0, 1850.0, '# Lesson 0.37: Introduction to Pydantic: Data Validation from Scratch

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.36
- **Subtopics**:
  - `0.37.1` The Pydantic mental model: turning loose dictionaries into guaranteed, validated data models.
  - `0.37.2` Creating a `BaseModel`: defining fields, default values, and required attributes.
  - `0.37.3` Automatic type coercion: how Pydantic cleanly converts strings like `"123"` into integers `123`.
  - `0.37.4` Catching validation errors: inspecting `ValidationError` when data fails to meet schema rules.
- **Key Failure Modes & Edge Cases**: Passing invalid data into Pydantic models without a `try/except ValidationError` block.
- **Verification & Mastery Check**: Define an `AIResponse` Pydantic model with fields `content: str`, `tokens: int`, and validate a dirty dictionary against it.
- **Project Application**: PromptCLI: Structured output validation foundation.', '{"solution.py": "# Phase 0 // Lesson 0.37: Introduction to Pydantic: Data Validation from Scratch\n\ndef solve():\n    \"\"\"\n    Verification: Define an `AIResponse` Pydantic model with fields `content: str`, `tokens: int`, and validate a dirt\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.37", "subtopics_count": 4, "verification_criteria": "Define an `AIResponse` Pydantic model with fields `content: str`, `tokens: int`, and validate a dirty dictionary against it.", "subtopics": ["0.37.1 The Pydantic mental model: turning loose dictionaries into guaranteed, validated data models.", "0.37.2 Creating a `BaseModel`: defining fields, default values, and required attributes.", "0.37.3 Automatic type coercion: how Pydantic cleanly converts strings like `\"123\"` into integers `123`.", "0.37.4 Catching validation errors: inspecting `ValidationError` when data fails to meet schema rules."]}'::jsonb, '["Explain how this implementation prevents: Passing invalid data into Pydantic models without a `try/except ValidationError` block.", "How does Introduction to Pydantic: Data Validation from Scratch scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-38', 'phase-00-lesson-38-git-fundamentals-commits-history-diffs', 'module-1', 38, 'Lesson 1.38: Git Fundamentals: Commits, History & Diffs', 'Prerequisites: Lesson 0.26', 'Prerequisites: Lesson 0.26 | Subtopics: 4 items', 'Systems project application', 100, 1, 120.0, 1900.0, '# Lesson 0.38: Git Fundamentals: Commits, History & Diffs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.26
- **Subtopics**:
  - `0.38.1` Why version control is mandatory: time-traveling through project history and safe experimentation.
  - `0.38.2` The 3 Git states: Working Directory, Staging Area (`git add`), and Repository (`git commit`).
  - `0.38.3` Writing meaningful commit messages: describing the "why" rather than just the "what".
  - `0.38.4` Inspecting changes: using `git status`, `git diff`, and `git log --oneline`.
- **Key Failure Modes & Edge Cases**: Running `git add .` without checking `git status`, accidentally staging sensitive `.env` files.
- **Verification & Mastery Check**: Initialize a Git repository, stage files, make 3 distinct commits, and view the commit history log.
- **Project Application**: PromptCLI: Version control initialization.', '{"solution.py": "# Phase 0 // Lesson 0.38: Git Fundamentals: Commits, History & Diffs\n\ndef solve():\n    \"\"\"\n    Verification: Initialize a Git repository, stage files, make 3 distinct commits, and view the commit history log.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.38", "subtopics_count": 4, "verification_criteria": "Initialize a Git repository, stage files, make 3 distinct commits, and view the commit history log.", "subtopics": ["0.38.1 Why version control is mandatory: time-traveling through project history and safe experimentation.", "0.38.2 The 3 Git states: Working Directory, Staging Area (`git add`), and Repository (`git commit`).", "0.38.3 Writing meaningful commit messages: describing the \"why\" rather than just the \"what\".", "0.38.4 Inspecting changes: using `git status`, `git diff`, and `git log --oneline`."]}'::jsonb, '["Explain how this implementation prevents: Running `git add .` without checking `git status`, accidentally staging sensitive `.env` files.", "How does Git Fundamentals: Commits, History & Diffs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-39', 'phase-00-lesson-39-git-branching-merging-workflows', 'module-1', 39, 'Lesson 1.39: Git Branching & Merging Workflows', 'Prerequisites: Lesson 0.38', 'Prerequisites: Lesson 0.38 | Subtopics: 4 items', 'Systems project application', 100, 1, 0.0, 1950.0, '# Lesson 0.39: Git Branching & Merging Workflows

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.38
- **Subtopics**:
  - `0.39.1` Why branch: developing new features or prompt experiments in isolation without breaking the main codebase.
  - `0.39.2` Creating and switching branches: `git branch` and `git switch -c feature-prompt-v2`.
  - `0.39.3` Merging branches: bringing feature changes cleanly into the `main` branch.
  - `0.39.4` Resolving merge conflicts calmly: understanding conflict markers (`<<<<<<<`, `=======`, `>>>>>>>`).
- **Key Failure Modes & Edge Cases**: Panic-deleting code during merge conflicts; conflict markers are simply Git asking you to choose which version to keep.
- **Verification & Mastery Check**: Create a feature branch, make a change, merge it into main, and cleanly delete the feature branch.
- **Project Application**: PromptCLI: Feature branch workflow for prompt enhancements.', '{"solution.py": "# Phase 0 // Lesson 0.39: Git Branching & Merging Workflows\n\ndef solve():\n    \"\"\"\n    Verification: Create a feature branch, make a change, merge it into main, and cleanly delete the feature branch.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.39", "subtopics_count": 4, "verification_criteria": "Create a feature branch, make a change, merge it into main, and cleanly delete the feature branch.", "subtopics": ["0.39.1 Why branch: developing new features or prompt experiments in isolation without breaking the main codebase.", "0.39.2 Creating and switching branches: `git branch` and `git switch -c feature-prompt-v2`.", "0.39.3 Merging branches: bringing feature changes cleanly into the `main` branch.", "0.39.4 Resolving merge conflicts calmly: understanding conflict markers (`<<<<<<<`, `=======`, `>>>>>>>`)."]}'::jsonb, '["Explain how this implementation prevents: Panic-deleting code during merge conflicts; conflict markers are simply Git asking you to choose which version to keep.", "How does Git Branching & Merging Workflows scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-0-40', 'phase-00-lesson-40-remote-repositories-github-collaboration', 'module-1', 40, 'Lesson 1.40: Remote Repositories & GitHub Collaboration', 'Prerequisites: Lesson 0.39', 'Prerequisites: Lesson 0.39 | Subtopics: 4 items', 'Systems project application', 100, 1, 60.0, 2000.0, '# Lesson 0.40: Remote Repositories & GitHub Collaboration

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 0.39
- **Subtopics**:
  - `0.40.1` Local vs Remote: connecting local Git repositories to GitHub with `git remote add origin`.
  - `0.40.2` Pushing and pulling: `git push -u origin main` and `git pull`.
  - `0.40.3` Pull Requests (PRs): proposing changes, code review etiquette, and automated CI checks.
  - `0.40.4` Writing a professional README.md: explaining how to install, configure, and run your project.
- **Key Failure Modes & Edge Cases**: Pushing directly to `main` without testing, breaking the production deployment for other engineers.
- **Verification & Mastery Check**: Write a clean, comprehensive `README.md` for a project including installation, configuration, and example usage.
- **Project Application**: PromptCLI: Open-source project portfolio presentation.', '{"solution.py": "# Phase 0 // Lesson 0.40: Remote Repositories & GitHub Collaboration\n\ndef solve():\n    \"\"\"\n    Verification: Write a clean, comprehensive `README.md` for a project including installation, configuration, and ex\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "0.40", "subtopics_count": 4, "verification_criteria": "Write a clean, comprehensive `README.md` for a project including installation, configuration, and example usage.", "subtopics": ["0.40.1 Local vs Remote: connecting local Git repositories to GitHub with `git remote add origin`.", "0.40.2 Pushing and pulling: `git push -u origin main` and `git pull`.", "0.40.3 Pull Requests (PRs): proposing changes, code review etiquette, and automated CI checks.", "0.40.4 Writing a professional README.md: explaining how to install, configure, and run your project."]}'::jsonb, '["Explain how this implementation prevents: Pushing directly to `main` without testing, breaking the production deployment for other engineers.", "How does Remote Repositories & GitHub Collaboration scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
