INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-11-11', 'phase-11-lesson-11-memory-leak-debugging-in-native-code-valg', 'module-12', 11, 'Lesson 12.11: Memory Leak Debugging in Native Code: Valgrind, ASan & LeakSanitizer', 'Prerequisites: Phase 0, Lesson 11.9', 'Prerequisites: Phase 0, Lesson 11.9 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 550.0, '# Lesson 11.11: Memory Leak Debugging in Native Code: Valgrind, ASan & LeakSanitizer

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 11.9
- **Subtopics**:
  - `11.11.1` Valgrind Memcheck architecture: dynamic binary instrumentation tracking every memory read, write, and allocation in virtual CPU
  - `11.11.2` Valgrind detection capabilities: definitely lost, indirectly lost, possibly lost, still reachable memory, and invalid reads/writes
  - `11.11.3` AddressSanitizer (ASan): compile-time instrumentation (`-fsanitize=address`); shadow memory architecture, $2\times$ overhead vs Valgrind''s $20\times$
  - `11.11.4` LeakSanitizer (LSan): stand-alone or ASan-integrated memory leak detector with near-zero runtime overhead
  - `11.11.5` Detecting use-after-free, buffer overflows (stack and heap), and double-free bugs in C/C++ and Rust `unsafe` code
  - `11.11.6` Debugging memory bugs in Python C-extensions: running Python interpreter under ASan with custom suppression files
- **Key Failure Modes & Edge Cases**: Running Valgrind on high-throughput network tests, causing artificial 30x slowdown that trips network timeouts.
- **Verification & Mastery Check**: Compile a C/Rust module with AddressSanitizer; execute a test suite that triggers a use-after-free and interpret the ASan crash trace.
- **Project Application**: ModelPulse: Native memory debugging and sanitizer harness.', '{"solution.py": "# Phase 11 // Lesson 11.11: Memory Leak Debugging in Native Code: Valgrind, ASan & LeakSanitizer\n\ndef solve():\n    \"\"\"\n    Verification: Compile a C/Rust module with AddressSanitizer; execute a test suite that triggers a use-after-free a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.11", "subtopics_count": 6, "verification_criteria": "Compile a C/Rust module with AddressSanitizer; execute a test suite that triggers a use-after-free and interpret the ASan crash trace.", "subtopics": ["11.11.1 Valgrind Memcheck architecture: dynamic binary instrumentation tracking every memory read, write, and allocation in virtual CPU", "11.11.2 Valgrind detection capabilities: definitely lost, indirectly lost, possibly lost, still reachable memory, and invalid reads/writes", "11.11.3 AddressSanitizer (ASan): compile-time instrumentation (`-fsanitize=address`); shadow memory architecture, $2\\times$ overhead vs Valgrind''s $20\\times$", "11.11.4 LeakSanitizer (LSan): stand-alone or ASan-integrated memory leak detector with near-zero runtime overhead", "11.11.5 Detecting use-after-free, buffer overflows (stack and heap), and double-free bugs in C/C++ and Rust `unsafe` code", "11.11.6 Debugging memory bugs in Python C-extensions: running Python interpreter under ASan with custom suppression files"]}'::jsonb, '["Explain how this implementation prevents: Running Valgrind on high-throughput network tests, causing artificial 30x slowdown that trips network timeouts.", "How does Memory Leak Debugging in Native Code: Valgrind, ASan & LeakSanitizer scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-12', 'phase-11-lesson-12-database-profiling-i-pg-stat-statements-w', 'module-12', 12, 'Lesson 12.12: Database Profiling I: pg_stat_statements & Workload Analysis', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 600.0, '# Lesson 11.12: Database Profiling I: pg_stat_statements & Workload Analysis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `11.12.1` `pg_stat_statements` extension internals: tracking execution statistics across all SQL statements executed on PostgreSQL
  - `11.12.2` Key performance metrics: `calls`, `total_exec_time`, `mean_exec_time`, `stddev_exec_time`, `rows`, `shared_blks_hit`, `shared_blks_read`
  - `11.12.3` Identifying query bottlenecks: Top-N queries by total time (system impact) vs Top-N queries by mean time (user latency)
  - `11.12.4` Cache hit ratio calculations: evaluating PostgreSQL buffer cache efficiency: $\frac{\text{shared\_blks\_hit}}{\text{shared\_blks\_hit} + \text{shared\_blks\_read}}$
  - `11.12.5` Query normalization: how pg_stat_statements strips constants to group identical query structures together
  - `11.12.6` Automated query regression detection: scheduling periodic snapshots of pg_stat_statements into analytical tables
- **Key Failure Modes & Edge Cases**: Optimizing rare 10-second queries that execute once a month while ignoring 50ms queries that execute 5,000 times per second.
- **Verification & Mastery Check**: Configure `pg_stat_statements` on PostgreSQL; write diagnostic queries that pinpoint the top 5 most resource-consuming production queries.
- **Project Application**: ModelPulse: PostgreSQL query telemetry collector.', '{"solution.py": "# Phase 11 // Lesson 11.12: Database Profiling I: pg_stat_statements & Workload Analysis\n\ndef solve():\n    \"\"\"\n    Verification: Configure `pg_stat_statements` on PostgreSQL; write diagnostic queries that pinpoint the top 5 most \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.12", "subtopics_count": 6, "verification_criteria": "Configure `pg_stat_statements` on PostgreSQL; write diagnostic queries that pinpoint the top 5 most resource-consuming production queries.", "subtopics": ["11.12.1 `pg_stat_statements` extension internals: tracking execution statistics across all SQL statements executed on PostgreSQL", "11.12.2 Key performance metrics: `calls`, `total_exec_time`, `mean_exec_time`, `stddev_exec_time`, `rows`, `shared_blks_hit`, `shared_blks_read`", "11.12.3 Identifying query bottlenecks: Top-N queries by total time (system impact) vs Top-N queries by mean time (user latency)", "11.12.4 Cache hit ratio calculations: evaluating PostgreSQL buffer cache efficiency: $\\frac{\\text{shared\\_blks\\_hit}}{\\text{shared\\_blks\\_hit} + \\text{shared\\_blks\\_read}}$", "11.12.5 Query normalization: how pg_stat_statements strips constants to group identical query structures together", "11.12.6 Automated query regression detection: scheduling periodic snapshots of pg_stat_statements into analytical tables"]}'::jsonb, '["Explain how this implementation prevents: Optimizing rare 10-second queries that execute once a month while ignoring 50ms queries that execute 5,000 times per sec", "How does Database Profiling I: pg_stat_statements & Workload Analysis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-13', 'phase-11-lesson-13-database-profiling-ii-explain-analyze-que', 'module-12', 13, 'Lesson 12.13: Database Profiling II: EXPLAIN ANALYZE & Query Execution Plans', 'Prerequisites: Lesson 11.12', 'Prerequisites: Lesson 11.12 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 650.0, '# Lesson 11.13: Database Profiling II: EXPLAIN ANALYZE & Query Execution Plans

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.12
- **Subtopics**:
  - `11.13.1` How PostgreSQL executes queries: Parser $\to$ Rewriter $\to$ Planner/Optimizer $\to$ Executor
  - `11.13.2` `EXPLAIN` vs `EXPLAIN (ANALYZE, BUFFERS, TIMING)`: estimated plan costs vs actual execution times and buffer hits
  - `11.13.3` Cost estimation units: arbitrary units relative to 1.0 (sequential page fetch `seq_page_cost`); `random_page_cost` default 4.0
  - `11.13.4` Plan node types: Seq Scan, Index Scan, Index Only Scan, Bitmap Index Scan, Bitmap Heap Scan
  - `11.13.5` Join algorithms: Nested Loop (small sets), Hash Join (large unsorted sets), Merge Join (pre-sorted inputs)
  - `11.13.6` Spotting optimizer estimation errors: large discrepancies between estimated `rows=X` and actual `rows=Y` indicating stale statistics
- **Key Failure Modes & Edge Cases**: Running `EXPLAIN ANALYZE` on a destructive `DELETE` or `UPDATE` query in production, accidentally executing the deletion.
- **Verification & Mastery Check**: Analyze an `EXPLAIN (ANALYZE, BUFFERS)` execution plan; eliminate a slow Sequential Scan by adding an optimized composite index.
- **Project Application**: ModelPulse: Execution plan analyzer and index recommender.', '{"solution.py": "# Phase 11 // Lesson 11.13: Database Profiling II: EXPLAIN ANALYZE & Query Execution Plans\n\ndef solve():\n    \"\"\"\n    Verification: Analyze an `EXPLAIN (ANALYZE, BUFFERS)` execution plan; eliminate a slow Sequential Scan by adding a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.13", "subtopics_count": 6, "verification_criteria": "Analyze an `EXPLAIN (ANALYZE, BUFFERS)` execution plan; eliminate a slow Sequential Scan by adding an optimized composite index.", "subtopics": ["11.13.1 How PostgreSQL executes queries: Parser $\\to$ Rewriter $\\to$ Planner/Optimizer $\\to$ Executor", "11.13.2 `EXPLAIN` vs `EXPLAIN (ANALYZE, BUFFERS, TIMING)`: estimated plan costs vs actual execution times and buffer hits", "11.13.3 Cost estimation units: arbitrary units relative to 1.0 (sequential page fetch `seq_page_cost`); `random_page_cost` default 4.0", "11.13.4 Plan node types: Seq Scan, Index Scan, Index Only Scan, Bitmap Index Scan, Bitmap Heap Scan", "11.13.5 Join algorithms: Nested Loop (small sets), Hash Join (large unsorted sets), Merge Join (pre-sorted inputs)", "11.13.6 Spotting optimizer estimation errors: large discrepancies between estimated `rows=X` and actual `rows=Y` indicating stale statistics"]}'::jsonb, '["Explain how this implementation prevents: Running `EXPLAIN ANALYZE` on a destructive `DELETE` or `UPDATE` query in production, accidentally executing the deletion", "How does Database Profiling II: EXPLAIN ANALYZE & Query Execution Plans scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-14', 'phase-11-lesson-14-database-profiling-iii-lock-contention-de', 'module-12', 14, 'Lesson 12.14: Database Profiling III: Lock Contention, Deadlocks & Vacuum', 'Prerequisites: Lesson 11.12, Lesson 11.13', 'Prerequisites: Lesson 11.12, Lesson 11.13 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 700.0, '# Lesson 11.14: Database Profiling III: Lock Contention, Deadlocks & Vacuum

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.12, Lesson 11.13
- **Subtopics**:
  - `11.14.1` PostgreSQL locking hierarchy: Table locks (AccessShare to AccessExclusive) vs Row locks (ForShare, ForUpdate)
  - `11.14.2` Lock contention analysis: inspecting `pg_locks` and `pg_stat_activity` to find blocking PIDs and blocked queries
  - `11.14.3` Deadlock detection: PostgreSQL deadlock_timeout (default 1s), wait-for graph cycle resolution, and transactional retry patterns
  - `11.14.4` Multi-Version Concurrency Control (MVCC) bloat: table and index bloat caused by dead tuples left behind by updates and deletes
  - `11.14.5` Autovacuum internals: vacuum workers, scale factors (`autovacuum_vacuum_scale_factor`), cost limits, and freeze maps
  - `11.14.6` Aggressive vacuum tuning: tuning autovacuum for high-write tables to prevent table bloat and transaction ID wraparound (TXID)
- **Key Failure Modes & Edge Cases**: Running `ALTER TABLE ADD COLUMN ... DEFAULT <non-null>` on legacy Postgres versions, taking an AccessExclusive lock that freezes traffic.
- **Verification & Mastery Check**: Simulate concurrent locking conflicts; write an automated monitoring query that alerts on transactions blocked for $>5$ seconds.
- **Project Application**: ModelPulse: Database lock contention and vacuum monitor.', '{"solution.py": "# Phase 11 // Lesson 11.14: Database Profiling III: Lock Contention, Deadlocks & Vacuum\n\ndef solve():\n    \"\"\"\n    Verification: Simulate concurrent locking conflicts; write an automated monitoring query that alerts on transactio\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.14", "subtopics_count": 6, "verification_criteria": "Simulate concurrent locking conflicts; write an automated monitoring query that alerts on transactions blocked for $>5$ seconds.", "subtopics": ["11.14.1 PostgreSQL locking hierarchy: Table locks (AccessShare to AccessExclusive) vs Row locks (ForShare, ForUpdate)", "11.14.2 Lock contention analysis: inspecting `pg_locks` and `pg_stat_activity` to find blocking PIDs and blocked queries", "11.14.3 Deadlock detection: PostgreSQL deadlock_timeout (default 1s), wait-for graph cycle resolution, and transactional retry patterns", "11.14.4 Multi-Version Concurrency Control (MVCC) bloat: table and index bloat caused by dead tuples left behind by updates and deletes", "11.14.5 Autovacuum internals: vacuum workers, scale factors (`autovacuum_vacuum_scale_factor`), cost limits, and freeze maps", "11.14.6 Aggressive vacuum tuning: tuning autovacuum for high-write tables to prevent table bloat and transaction ID wraparound (TXID)"]}'::jsonb, '["Explain how this implementation prevents: Running `ALTER TABLE ADD COLUMN ... DEFAULT <non-null>` on legacy Postgres versions, taking an AccessExclusive lock that", "How does Database Profiling III: Lock Contention, Deadlocks & Vacuum scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-15', 'phase-11-lesson-15-database-profiling-iv-connection-pooling-', 'module-12', 15, 'Lesson 12.15: Database Profiling IV: Connection Pooling & PgBouncer Internals', 'Prerequisites: Lesson 11.12, Phase 4', 'Prerequisites: Lesson 11.12, Phase 4 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 750.0, '# Lesson 11.15: Database Profiling IV: Connection Pooling & PgBouncer Internals

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.12, Phase 4
- **Subtopics**:
  - `11.15.1` The cost of PostgreSQL connections: process-per-connection architecture, 5-10MB RAM per backend, and fork overhead
  - `11.15.2` Why thousands of open connections degrade database performance: context switching, cache contention, and lock table overhead
  - `11.15.3` PgBouncer architecture: lightweight, single-process, event-driven connection pooler sitting in front of PostgreSQL
  - `11.15.4` Pooling modes: Session pooling (connection held until client disconnects) vs Transaction pooling (held during transaction only)
  - `11.15.5` Statement pooling: extreme multiplexing for autocommit queries; incompatibility with prepared statements
  - `11.15.6` Configuring PgBouncer: `pool_mode = transaction`, `max_client_conn = 5000`, `default_pool_size = 50`, `reserve_pool_size`
- **Key Failure Modes & Edge Cases**: Using Transaction pooling mode with application code relying on session-level `SET` variables or un-named prepared statements.
- **Verification & Mastery Check**: Deploy PgBouncer in front of PostgreSQL; benchmark 2,000 concurrent client connections with and without pooling using `pgbench`.
- **Project Application**: ModelPulse: Enterprise database connection pooling blueprint.', '{"solution.py": "# Phase 11 // Lesson 11.15: Database Profiling IV: Connection Pooling & PgBouncer Internals\n\ndef solve():\n    \"\"\"\n    Verification: Deploy PgBouncer in front of PostgreSQL; benchmark 2,000 concurrent client connections with and with\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.15", "subtopics_count": 6, "verification_criteria": "Deploy PgBouncer in front of PostgreSQL; benchmark 2,000 concurrent client connections with and without pooling using `pgbench`.", "subtopics": ["11.15.1 The cost of PostgreSQL connections: process-per-connection architecture, 5-10MB RAM per backend, and fork overhead", "11.15.2 Why thousands of open connections degrade database performance: context switching, cache contention, and lock table overhead", "11.15.3 PgBouncer architecture: lightweight, single-process, event-driven connection pooler sitting in front of PostgreSQL", "11.15.4 Pooling modes: Session pooling (connection held until client disconnects) vs Transaction pooling (held during transaction only)", "11.15.5 Statement pooling: extreme multiplexing for autocommit queries; incompatibility with prepared statements", "11.15.6 Configuring PgBouncer: `pool_mode = transaction`, `max_client_conn = 5000`, `default_pool_size = 50`, `reserve_pool_size`"]}'::jsonb, '["Explain how this implementation prevents: Using Transaction pooling mode with application code relying on session-level `SET` variables or un-named prepared state", "How does Database Profiling IV: Connection Pooling & PgBouncer Internals scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-16', 'phase-11-lesson-16-load-testing-foundations-closed-vs-open-s', 'module-12', 16, 'Lesson 12.16: Load Testing Foundations: Closed vs Open Systems & Little''s Law', 'Prerequisites: Phase 8, Lesson 11.1', 'Prerequisites: Phase 8, Lesson 11.1 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 800.0, '# Lesson 11.16: Load Testing Foundations: Closed vs Open Systems & Little''s Law

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 8, Lesson 11.1
- **Subtopics**:
  - `11.16.1` Load testing paradigms: Closed System (fixed number of users looping; requests delayed if system slows) vs Open System
  - `11.16.2` Open System model: users arrive independently according to a Poisson process; arrival rate does not slow down when system degrades
  - `11.16.3` Why closed model load testers hide catastrophic production outages: masking queue explosions through coordinated omission
  - `11.16.4` Little''s Law: $L = \lambda W$ (Average items in system = Arrival rate $\times$ Average time in system)
  - `11.16.5` Load testing types: Smoke test (minimal load), Stress test (breaking point), Soak/Endurance test (memory leaks over 24h), Spike test
  - `11.16.6` Defining load testing targets: p95 latency $<150$ms at 5,000 QPS with $<0.01\%$ HTTP error rate
- **Key Failure Modes & Edge Cases**: Conducting load testing using a closed-loop tester that throttles itself when the server degrades, reporting misleadingly low latencies.
- **Verification & Mastery Check**: Calculate expected queue lengths and concurrency requirements for a 10,000 QPS service using Little''s Law.
- **Project Application**: ModelPulse: Load test capacity planning spreadsheet.', '{"solution.py": "# Phase 11 // Lesson 11.16: Load Testing Foundations: Closed vs Open Systems & Little''s Law\n\ndef solve():\n    \"\"\"\n    Verification: Calculate expected queue lengths and concurrency requirements for a 10,000 QPS service using Little''\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.16", "subtopics_count": 6, "verification_criteria": "Calculate expected queue lengths and concurrency requirements for a 10,000 QPS service using Little''s Law.", "subtopics": ["11.16.1 Load testing paradigms: Closed System (fixed number of users looping; requests delayed if system slows) vs Open System", "11.16.2 Open System model: users arrive independently according to a Poisson process; arrival rate does not slow down when system degrades", "11.16.3 Why closed model load testers hide catastrophic production outages: masking queue explosions through coordinated omission", "11.16.4 Little''s Law: $L = \\lambda W$ (Average items in system = Arrival rate $\\times$ Average time in system)", "11.16.5 Load testing types: Smoke test (minimal load), Stress test (breaking point), Soak/Endurance test (memory leaks over 24h), Spike test", "11.16.6 Defining load testing targets: p95 latency $<150$ms at 5,000 QPS with $<0.01\\%$ HTTP error rate"]}'::jsonb, '["Explain how this implementation prevents: Conducting load testing using a closed-loop tester that throttles itself when the server degrades, reporting misleadingl", "How does Load Testing Foundations: Closed vs Open Systems & Little''s Law scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-17', 'phase-11-lesson-17-modern-load-testing-with-k6-javascript-sc', 'module-12', 17, 'Lesson 12.17: Modern Load Testing with k6: JavaScript Scripting & Virtual Users', 'Prerequisites: Lesson 11.16', 'Prerequisites: Lesson 11.16 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 850.0, '# Lesson 11.17: Modern Load Testing with k6: JavaScript Scripting & Virtual Users

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.16
- **Subtopics**:
  - `11.17.1` k6 engine architecture: Go-based multi-threaded execution engine with embedded JavaScript (Goja) runtime for test scripts
  - `11.17.2` Writing k6 scripts: Virtual Users (VUs), `setup()`, default function, `teardown()`, and lifecycle stages
  - `11.17.3` Execution scenarios: configuring ramping VUs, constant VUs, ramping arrival rate (open model), and constant arrival rate
  - `11.17.4` Custom metrics: Counters, Gauges, Rates, and Trends; defining thresholds (`thresholds: { ''http_req_duration'': [''p(95)<200''] }`)
  - `11.17.5` Checks vs Thresholds: verifying functional response correctness without halting tests vs failing CI builds on SLA violations
  - `11.17.6` Data-driven testing: parameterizing tests with real CSV/JSON user credentials, unique search queries, and realistic payloads
- **Key Failure Modes & Edge Cases**: Writing k6 scripts that execute heavy synchronous computational loops inside the VU iteration, choking the load generator''s own CPU.
- **Verification & Mastery Check**: Write a modular k6 load testing suite simulating an e-commerce checkout flow with ramping arrival rate and strict p95 latency thresholds.
- **Project Application**: ModelPulse: Automated k6 load testing suite.', '{"solution.py": "# Phase 11 // Lesson 11.17: Modern Load Testing with k6: JavaScript Scripting & Virtual Users\n\ndef solve():\n    \"\"\"\n    Verification: Write a modular k6 load testing suite simulating an e-commerce checkout flow with ramping arrival ra\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.17", "subtopics_count": 6, "verification_criteria": "Write a modular k6 load testing suite simulating an e-commerce checkout flow with ramping arrival rate and strict p95 latency thresholds.", "subtopics": ["11.17.1 k6 engine architecture: Go-based multi-threaded execution engine with embedded JavaScript (Goja) runtime for test scripts", "11.17.2 Writing k6 scripts: Virtual Users (VUs), `setup()`, default function, `teardown()`, and lifecycle stages", "11.17.3 Execution scenarios: configuring ramping VUs, constant VUs, ramping arrival rate (open model), and constant arrival rate", "11.17.4 Custom metrics: Counters, Gauges, Rates, and Trends; defining thresholds (`thresholds: { ''http_req_duration'': [''p(95)<200''] }`)", "11.17.5 Checks vs Thresholds: verifying functional response correctness without halting tests vs failing CI builds on SLA violations", "11.17.6 Data-driven testing: parameterizing tests with real CSV/JSON user credentials, unique search queries, and realistic payloads"]}'::jsonb, '["Explain how this implementation prevents: Writing k6 scripts that execute heavy synchronous computational loops inside the VU iteration, choking the load generato", "How does Modern Load Testing with k6: JavaScript Scripting & Virtual Users scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-18', 'phase-11-lesson-18-distributed-load-testing-locust-cloud-sca', 'module-12', 18, 'Lesson 12.18: Distributed Load Testing: Locust & Cloud-Scale Traffic Injection', 'Prerequisites: Lesson 11.16, Lesson 11.17', 'Prerequisites: Lesson 11.16, Lesson 11.17 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 900.0, '# Lesson 11.18: Distributed Load Testing: Locust & Cloud-Scale Traffic Injection

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.16, Lesson 11.17
- **Subtopics**:
  - `11.18.1` Single-node load generator limits: network socket exhaustion (ephemeral port limits), client CPU saturation, and bandwidth ceilings
  - `11.18.2` Locust architecture: Python-based load testing framework with gevent coroutines; Master-Worker distributed topology
  - `11.18.3` Master node role: aggregating metrics, coordinating worker start/stop, and serving web UI dashboard
  - `11.18.4` Worker nodes role: executing greenlets injecting traffic against target systems across multiple VMs or Kubernetes pods
  - `11.18.5` Customizing traffic behavior in Locust: `FastHttpUser` (geventhttpclient) for $5\times$ higher throughput than standard `HttpUser`
  - `11.18.6` Running cloud-scale tests: deploying 50 Locust workers in Kubernetes to inject 200,000 QPS against target infrastructure
- **Key Failure Modes & Edge Cases**: Running distributed load tests from inside the same Kubernetes cluster as the target, bypassing realistic cloud ingress and firewalls.
- **Verification & Mastery Check**: Deploy a distributed Locust load testing cluster on Kubernetes with 1 master and 10 workers; generate 50,000 QPS against a test target.
- **Project Application**: ModelPulse: Distributed cloud-scale load testing harness.', '{"solution.py": "# Phase 11 // Lesson 11.18: Distributed Load Testing: Locust & Cloud-Scale Traffic Injection\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a distributed Locust load testing cluster on Kubernetes with 1 master and 10 workers; generat\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.18", "subtopics_count": 6, "verification_criteria": "Deploy a distributed Locust load testing cluster on Kubernetes with 1 master and 10 workers; generate 50,000 QPS against a test target.", "subtopics": ["11.18.1 Single-node load generator limits: network socket exhaustion (ephemeral port limits), client CPU saturation, and bandwidth ceilings", "11.18.2 Locust architecture: Python-based load testing framework with gevent coroutines; Master-Worker distributed topology", "11.18.3 Master node role: aggregating metrics, coordinating worker start/stop, and serving web UI dashboard", "11.18.4 Worker nodes role: executing greenlets injecting traffic against target systems across multiple VMs or Kubernetes pods", "11.18.5 Customizing traffic behavior in Locust: `FastHttpUser` (geventhttpclient) for $5\\times$ higher throughput than standard `HttpUser`", "11.18.6 Running cloud-scale tests: deploying 50 Locust workers in Kubernetes to inject 200,000 QPS against target infrastructure"]}'::jsonb, '["Explain how this implementation prevents: Running distributed load tests from inside the same Kubernetes cluster as the target, bypassing realistic cloud ingress ", "How does Distributed Load Testing: Locust & Cloud-Scale Traffic Injection scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-19', 'phase-11-lesson-19-network-kernel-tuning-for-high-concurrenc', 'module-12', 19, 'Lesson 12.19: Network & Kernel Tuning for High-Concurrency Systems', 'Prerequisites: Phase 0, Lesson 11.16', 'Prerequisites: Phase 0, Lesson 11.16 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 950.0, '# Lesson 11.19: Network & Kernel Tuning for High-Concurrency Systems

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 11.16
- **Subtopics**:
  - `11.19.1` Linux socket buffers: `rmem_max`, `wmem_max`, `tcp_rmem`, and `tcp_wmem` auto-tuning for high bandwidth-delay products
  - `11.19.2` File descriptor limits: configuring `nofile` limits in `/etc/security/limits.conf` and `fs.file-max` for 100,000+ open sockets
  - `11.19.3` TCP connection queues: SYN backlog (`tcp_max_syn_backlog`) and accept queue (`net.core.somaxconn`) preventing dropped handshakes
  - `11.19.4` Ephemeral port exhaustion: tuning `net.ipv4.ip_local_port_range` ($1024-65535$) and `tcp_tw_reuse` for high outbound connection rates
  - `11.19.5` TCP TIME_WAIT state mechanics: 2MSL (Maximum Segment Lifetime) delay; why reusing sockets safely requires timestamp support
  - `11.19.6` TCP Congestion Control algorithms: CUBIC (loss-based) vs Google BBR (Bottleneck Bandwidth and RTT-based) for high throughput
- **Key Failure Modes & Edge Cases**: Dropping client connections during load spikes because the Linux `somaxconn` listen backlog remained at the default 128.
- **Verification & Mastery Check**: Apply kernel `sysctl` network hardening configurations; verify that a server accepts 50,000 concurrent persistent TCP connections.
- **Project Application**: ModelPulse: Linux kernel network tuning automation script.', '{"solution.py": "# Phase 11 // Lesson 11.19: Network & Kernel Tuning for High-Concurrency Systems\n\ndef solve():\n    \"\"\"\n    Verification: Apply kernel `sysctl` network hardening configurations; verify that a server accepts 50,000 concurre\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.19", "subtopics_count": 6, "verification_criteria": "Apply kernel `sysctl` network hardening configurations; verify that a server accepts 50,000 concurrent persistent TCP connections.", "subtopics": ["11.19.1 Linux socket buffers: `rmem_max`, `wmem_max`, `tcp_rmem`, and `tcp_wmem` auto-tuning for high bandwidth-delay products", "11.19.2 File descriptor limits: configuring `nofile` limits in `/etc/security/limits.conf` and `fs.file-max` for 100,000+ open sockets", "11.19.3 TCP connection queues: SYN backlog (`tcp_max_syn_backlog`) and accept queue (`net.core.somaxconn`) preventing dropped handshakes", "11.19.4 Ephemeral port exhaustion: tuning `net.ipv4.ip_local_port_range` ($1024-65535$) and `tcp_tw_reuse` for high outbound connection rates", "11.19.5 TCP TIME_WAIT state mechanics: 2MSL (Maximum Segment Lifetime) delay; why reusing sockets safely requires timestamp support", "11.19.6 TCP Congestion Control algorithms: CUBIC (loss-based) vs Google BBR (Bottleneck Bandwidth and RTT-based) for high throughput"]}'::jsonb, '["Explain how this implementation prevents: Dropping client connections during load spikes because the Linux `somaxconn` listen backlog remained at the default 128.", "How does Network & Kernel Tuning for High-Concurrency Systems scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-20', 'phase-11-lesson-20-chaos-load-testing-blameless-failure-inje', 'module-12', 20, 'Lesson 12.20: Chaos Load Testing: Blameless Failure Injection under High Traffic', 'Prerequisites: Phase 7, Lesson 11.17', 'Prerequisites: Phase 7, Lesson 11.17 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 1000.0, '# Lesson 11.20: Chaos Load Testing: Blameless Failure Injection under High Traffic

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 11.17
- **Subtopics**:
  - `11.20.1` The objective of Chaos Load Testing: verifying that systems maintain SLAs and fail gracefully when components crash under peak load
  - `11.20.2` Combining load generators with chaos injectors: running sustained 20,000 QPS load while injecting simulated infrastructure faults
  - `11.20.3` Chaos injection scenarios: terminating primary database pods, injecting 200ms network latency to external payment gateways, killing random worker nodes
  - `11.20.4` Verifying system resilience properties: testing whether circuit breakers trip, read-replicas take over, and fallback caches engage
  - `11.20.5` Monitoring steady-state health: tracking error rates and user experience continuity throughout the chaos event
  - `11.20.6` Automated verification assertions: asserting that error rate remains $<0.5\%$ and 0 orphaned transactions linger in database
- **Key Failure Modes & Edge Cases**: Injecting chaos faults without a continuous active load test, failing to uncover race conditions that only manifest under concurrent load.
- **Verification & Mastery Check**: Execute a synchronized k6 load test while terminating the primary database replica; prove zero data corruption and self-healing under load.
- **Project Application**: ModelPulse: Automated chaos load testing verification suite.', '{"solution.py": "# Phase 11 // Lesson 11.20: Chaos Load Testing: Blameless Failure Injection under High Traffic\n\ndef solve():\n    \"\"\"\n    Verification: Execute a synchronized k6 load test while terminating the primary database replica; prove zero data \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.20", "subtopics_count": 6, "verification_criteria": "Execute a synchronized k6 load test while terminating the primary database replica; prove zero data corruption and self-healing under load.", "subtopics": ["11.20.1 The objective of Chaos Load Testing: verifying that systems maintain SLAs and fail gracefully when components crash under peak load", "11.20.2 Combining load generators with chaos injectors: running sustained 20,000 QPS load while injecting simulated infrastructure faults", "11.20.3 Chaos injection scenarios: terminating primary database pods, injecting 200ms network latency to external payment gateways, killing random worker nodes", "11.20.4 Verifying system resilience properties: testing whether circuit breakers trip, read-replicas take over, and fallback caches engage", "11.20.5 Monitoring steady-state health: tracking error rates and user experience continuity throughout the chaos event", "11.20.6 Automated verification assertions: asserting that error rate remains $<0.5\\%$ and 0 orphaned transactions linger in database"]}'::jsonb, '["Explain how this implementation prevents: Injecting chaos faults without a continuous active load test, failing to uncover race conditions that only manifest unde", "How does Chaos Load Testing: Blameless Failure Injection under High Traffic scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-21', 'phase-11-lesson-21-mlops-foundations-the-ml-lifecycle-techni', 'module-12', 21, 'Lesson 12.21: MLOps Foundations: The ML Lifecycle & Technical Debt in AI Systems', 'Prerequisites: Phase 9, Phase 10', 'Prerequisites: Phase 9, Phase 10 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 1050.0, '# Lesson 11.21: MLOps Foundations: The ML Lifecycle & Technical Debt in AI Systems

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 10
- **Subtopics**:
  - `11.21.1` The Hidden Technical Debt in Machine Learning Systems (Sculley et al.): ML code as a small fraction of real-world ML systems
  - `11.21.2` The ML lifecycle: Data Ingestion $\to$ Feature Engineering $\to$ Model Training $\to$ Evaluation $\to$ Registry $\to$ Deployment $\to$ Monitoring
  - `11.21.3` Reproducibility in MLOps: tracking the exact triplet of (Code Version, Data Version, Hyperparameters) for every trained model
  - `11.21.4` Configuration debt, pipeline jungles, dead experimental code branches, and boundary erosion in ML architectures
  - `11.21.5` Data versioning with DVC (Data Version Control): Git-like tracking of multi-gigabyte datasets using S3/GCS content hashes
  - `11.21.6` Automating the training pipeline: orchestrating end-to-end reproducible training jobs via Kubeflow Pipelines or GitHub Actions
- **Key Failure Modes & Edge Cases**: Deploying a high-performing model to production without recording its exact training commit hash or dataset snapshot, making retraining impossible.
- **Verification & Mastery Check**: Set up DVC tracking a 5GB dataset in Google Cloud Storage; link dataset version commit tags directly to a training script run.
- **Project Application**: ModelPulse: Dataset versioning and DVC pipeline.', '{"solution.py": "# Phase 11 // Lesson 11.21: MLOps Foundations: The ML Lifecycle & Technical Debt in AI Systems\n\ndef solve():\n    \"\"\"\n    Verification: Set up DVC tracking a 5GB dataset in Google Cloud Storage; link dataset version commit tags directly\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.21", "subtopics_count": 6, "verification_criteria": "Set up DVC tracking a 5GB dataset in Google Cloud Storage; link dataset version commit tags directly to a training script run.", "subtopics": ["11.21.1 The Hidden Technical Debt in Machine Learning Systems (Sculley et al.): ML code as a small fraction of real-world ML systems", "11.21.2 The ML lifecycle: Data Ingestion $\\to$ Feature Engineering $\\to$ Model Training $\\to$ Evaluation $\\to$ Registry $\\to$ Deployment $\\to$ Monitoring", "11.21.3 Reproducibility in MLOps: tracking the exact triplet of (Code Version, Data Version, Hyperparameters) for every trained model", "11.21.4 Configuration debt, pipeline jungles, dead experimental code branches, and boundary erosion in ML architectures", "11.21.5 Data versioning with DVC (Data Version Control): Git-like tracking of multi-gigabyte datasets using S3/GCS content hashes", "11.21.6 Automating the training pipeline: orchestrating end-to-end reproducible training jobs via Kubeflow Pipelines or GitHub Actions"]}'::jsonb, '["Explain how this implementation prevents: Deploying a high-performing model to production without recording its exact training commit hash or dataset snapshot, ma", "How does MLOps Foundations: The ML Lifecycle & Technical Debt in AI Systems scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-22', 'phase-11-lesson-22-model-registries-artifact-versioning-with', 'module-12', 22, 'Lesson 12.22: Model Registries & Artifact Versioning with MLflow', 'Prerequisites: Lesson 11.21', 'Prerequisites: Lesson 11.21 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 1100.0, '# Lesson 11.22: Model Registries & Artifact Versioning with MLflow

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.21
- **Subtopics**:
  - `11.22.1` MLflow architecture: MLflow Tracking (metrics/params), MLflow Models (standard packaging), and MLflow Model Registry
  - `11.22.2` Logging training runs: `mlflow.log_params()`, `mlflow.log_metrics()`, and logging training curves over epochs
  - `11.22.3` Model packaging: MLmodel format, Conda/Pip environment specifications, and universal pyfunc Python flavor
  - `11.22.4` Model Registry lifecycle: transitioning model versions across stages (`None` $\to$ `Staging` $\to$ `Production` $\to$ `Archived`)
  - `11.22.5` Model governance: assigning model descriptions, tagging accuracy metrics, tracking author provenance, and approval workflows
  - `11.22.6` Automated model promotion: promoting a candidate model to `Production` stage only if validation metrics exceed current production champion
- **Key Failure Modes & Edge Cases**: Deploying raw model weights without tracking dependencies, causing runtime import crashes due to mismatched library versions in production.
- **Verification & Mastery Check**: Deploy a central MLflow tracking server backed by PostgreSQL and GCS; log training runs and automate model promotion via Python SDK.
- **Project Application**: ModelPulse: Enterprise MLflow model registry infrastructure.', '{"solution.py": "# Phase 11 // Lesson 11.22: Model Registries & Artifact Versioning with MLflow\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a central MLflow tracking server backed by PostgreSQL and GCS; log training runs and automate\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.22", "subtopics_count": 6, "verification_criteria": "Deploy a central MLflow tracking server backed by PostgreSQL and GCS; log training runs and automate model promotion via Python SDK.", "subtopics": ["11.22.1 MLflow architecture: MLflow Tracking (metrics/params), MLflow Models (standard packaging), and MLflow Model Registry", "11.22.2 Logging training runs: `mlflow.log_params()`, `mlflow.log_metrics()`, and logging training curves over epochs", "11.22.3 Model packaging: MLmodel format, Conda/Pip environment specifications, and universal pyfunc Python flavor", "11.22.4 Model Registry lifecycle: transitioning model versions across stages (`None` $\\to$ `Staging` $\\to$ `Production` $\\to$ `Archived`)", "11.22.5 Model governance: assigning model descriptions, tagging accuracy metrics, tracking author provenance, and approval workflows", "11.22.6 Automated model promotion: promoting a candidate model to `Production` stage only if validation metrics exceed current production champion"]}'::jsonb, '["Explain how this implementation prevents: Deploying raw model weights without tracking dependencies, causing runtime import crashes due to mismatched library vers", "How does Model Registries & Artifact Versioning with MLflow scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-23', 'phase-11-lesson-23-high-performance-model-serving-triton-vll', 'module-12', 23, 'Lesson 12.23: High-Performance Model Serving: Triton, vLLM & TorchServe', 'Prerequisites: Phase 9, Phase 10', 'Prerequisites: Phase 9, Phase 10 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 1150.0, '# Lesson 11.23: High-Performance Model Serving: Triton, vLLM & TorchServe

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 10
- **Subtopics**:
  - `11.23.1` The model serving challenge: optimizing GPU utilization, memory bandwidth, latency, and throughput during inference
  - `11.23.2` Triton Inference Server (NVIDIA): multi-framework support (PyTorch, ONNX, TensorRT), dynamic batching, concurrent model execution
  - `11.23.3` Dynamic Batching mechanics: aggregating individual incoming requests into a single GPU tensor batch within a small time window (e.g. 5ms)
  - `11.23.4` vLLM engine internals: high-throughput LLM serving via PagedAttention (managing KV-cache memory like virtual memory pages)
  - `11.23.5` Continuous batching (iteration-level scheduling): scheduling new requests at every token generation step rather than waiting for full sequences
  - `11.23.6` Benchmarking model serving: measuring Time To First Token (TTFT), Inter-Token Latency (ITL), and Requests Per Second (RPS)
- **Key Failure Modes & Edge Cases**: Serving PyTorch models using naive Flask/FastAPI processes with concurrency=1, underutilizing expensive $30,000 GPUs by 90%.
- **Verification & Mastery Check**: Deploy an LLM using vLLM with PagedAttention; benchmark throughput against a naive HuggingFace baseline, demonstrating $4\times$ speedup.
- **Project Application**: ModelPulse: High-performance model serving deployment.', '{"solution.py": "# Phase 11 // Lesson 11.23: High-Performance Model Serving: Triton, vLLM & TorchServe\n\ndef solve():\n    \"\"\"\n    Verification: Deploy an LLM using vLLM with PagedAttention; benchmark throughput against a naive HuggingFace basel\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.23", "subtopics_count": 6, "verification_criteria": "Deploy an LLM using vLLM with PagedAttention; benchmark throughput against a naive HuggingFace baseline, demonstrating $4\\times$ speedup.", "subtopics": ["11.23.1 The model serving challenge: optimizing GPU utilization, memory bandwidth, latency, and throughput during inference", "11.23.2 Triton Inference Server (NVIDIA): multi-framework support (PyTorch, ONNX, TensorRT), dynamic batching, concurrent model execution", "11.23.3 Dynamic Batching mechanics: aggregating individual incoming requests into a single GPU tensor batch within a small time window (e.g. 5ms)", "11.23.4 vLLM engine internals: high-throughput LLM serving via PagedAttention (managing KV-cache memory like virtual memory pages)", "11.23.5 Continuous batching (iteration-level scheduling): scheduling new requests at every token generation step rather than waiting for full sequences", "11.23.6 Benchmarking model serving: measuring Time To First Token (TTFT), Inter-Token Latency (ITL), and Requests Per Second (RPS)"]}'::jsonb, '["Explain how this implementation prevents: Serving PyTorch models using naive Flask/FastAPI processes with concurrency=1, underutilizing expensive $30,000 GPUs by ", "How does High-Performance Model Serving: Triton, vLLM & TorchServe scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-24', 'phase-11-lesson-24-model-serialization-optimization-onnx-ten', 'module-12', 24, 'Lesson 12.24: Model Serialization & Optimization: ONNX, TensorRT & Quantization', 'Prerequisites: Phase 9, Lesson 11.23', 'Prerequisites: Phase 9, Lesson 11.23 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 1200.0, '# Lesson 11.24: Model Serialization & Optimization: ONNX, TensorRT & Quantization

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Lesson 11.23
- **Subtopics**:
  - `11.24.1` Open Neural Network Exchange (ONNX): open format representing computational graphs independently of source framework
  - `11.24.2` Exporting PyTorch models to ONNX: tracing (`torch.onnx.export`) vs script-based export, dynamic axes handling
  - `11.24.3` Graph optimization with TensorRT: layer fusion (fusing Conv+BatchNorm+ReLU into single kernel), kernel auto-tuning for specific GPU
  - `11.24.4` Quantization paradigms: Post-Training Quantization (PTQ) vs Quantization-Aware Training (QAT)
  - `11.24.5` INT8 quantization mechanics: symmetric vs asymmetric quantization, calibration datasets, and computing scaling factors
  - `11.24.6` FP8 and 4-bit quantization (AWQ, GPTQ): compressing large language models for high-throughput edge and data-center inference
- **Key Failure Modes & Edge Cases**: Exporting ONNX models with fixed batch sizes and sequence lengths, causing runtime failures when serving variable-length production requests.
- **Verification & Mastery Check**: Export a PyTorch transformer model to ONNX, optimize with TensorRT/ONNX Runtime, and measure $3\times$ latency reduction at identical accuracy.
- **Project Application**: ModelPulse: ONNX model optimization and quantization pipeline.', '{"solution.py": "# Phase 11 // Lesson 11.24: Model Serialization & Optimization: ONNX, TensorRT & Quantization\n\ndef solve():\n    \"\"\"\n    Verification: Export a PyTorch transformer model to ONNX, optimize with TensorRT/ONNX Runtime, and measure $3\\time\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.24", "subtopics_count": 6, "verification_criteria": "Export a PyTorch transformer model to ONNX, optimize with TensorRT/ONNX Runtime, and measure $3\\times$ latency reduction at identical accuracy.", "subtopics": ["11.24.1 Open Neural Network Exchange (ONNX): open format representing computational graphs independently of source framework", "11.24.2 Exporting PyTorch models to ONNX: tracing (`torch.onnx.export`) vs script-based export, dynamic axes handling", "11.24.3 Graph optimization with TensorRT: layer fusion (fusing Conv+BatchNorm+ReLU into single kernel), kernel auto-tuning for specific GPU", "11.24.4 Quantization paradigms: Post-Training Quantization (PTQ) vs Quantization-Aware Training (QAT)", "11.24.5 INT8 quantization mechanics: symmetric vs asymmetric quantization, calibration datasets, and computing scaling factors", "11.24.6 FP8 and 4-bit quantization (AWQ, GPTQ): compressing large language models for high-throughput edge and data-center inference"]}'::jsonb, '["Explain how this implementation prevents: Exporting ONNX models with fixed batch sizes and sequence lengths, causing runtime failures when serving variable-length", "How does Model Serialization & Optimization: ONNX, TensorRT & Quantization scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-25', 'phase-11-lesson-25-deployment-strategies-i-canary-releases-p', 'module-12', 25, 'Lesson 12.25: Deployment Strategies I: Canary Releases & Progressive Delivery with Flagger', 'Prerequisites: Phase 7, Lesson 11.22', 'Prerequisites: Phase 7, Lesson 11.22 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 1250.0, '# Lesson 11.25: Deployment Strategies I: Canary Releases & Progressive Delivery with Flagger

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 11.22
- **Subtopics**:
  - `11.25.1` Canary deployment principles: routing a small percentage of real production traffic (e.g. 5%) to the new version before full rollout
  - `11.25.2` Progressive Delivery with Flagger: automating progressive canary promotions on Kubernetes using Envoy, Istio, or NGINX Ingress
  - `11.25.3` Analysis metrics: automated validation of canary health using Prometheus metrics (HTTP 5xx error rate, p99 latency thresholds)
  - `11.25.4` Canary promotion workflow: shifting traffic $5\% \to 10\% \to 25\% \to 50\% \to 100\%$ over 15-minute analysis intervals
  - `11.25.5` Automated rollbacks: immediately routing 100% traffic back to stable primary if canary error rate exceeds 1% during analysis
  - `11.25.6` Alerting integration: sending real-time Slack/PagerDuty notifications during canary promotion stages and automated rollbacks
- **Key Failure Modes & Edge Cases**: Promoting canary deployments based on zero errors during low-traffic midnight hours, missing bugs that only manifest under peak load.
- **Verification & Mastery Check**: Configure a Flagger canary deployment on Kubernetes with automated Prometheus metric analysis and verified self-healing rollback.
- **Project Application**: ModelPulse: Progressive canary deployment infrastructure.', '{"solution.py": "# Phase 11 // Lesson 11.25: Deployment Strategies I: Canary Releases & Progressive Delivery with Flagger\n\ndef solve():\n    \"\"\"\n    Verification: Configure a Flagger canary deployment on Kubernetes with automated Prometheus metric analysis and ve\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.25", "subtopics_count": 6, "verification_criteria": "Configure a Flagger canary deployment on Kubernetes with automated Prometheus metric analysis and verified self-healing rollback.", "subtopics": ["11.25.1 Canary deployment principles: routing a small percentage of real production traffic (e.g. 5%) to the new version before full rollout", "11.25.2 Progressive Delivery with Flagger: automating progressive canary promotions on Kubernetes using Envoy, Istio, or NGINX Ingress", "11.25.3 Analysis metrics: automated validation of canary health using Prometheus metrics (HTTP 5xx error rate, p99 latency thresholds)", "11.25.4 Canary promotion workflow: shifting traffic $5\\% \\to 10\\% \\to 25\\% \\to 50\\% \\to 100\\%$ over 15-minute analysis intervals", "11.25.5 Automated rollbacks: immediately routing 100% traffic back to stable primary if canary error rate exceeds 1% during analysis", "11.25.6 Alerting integration: sending real-time Slack/PagerDuty notifications during canary promotion stages and automated rollbacks"]}'::jsonb, '["Explain how this implementation prevents: Promoting canary deployments based on zero errors during low-traffic midnight hours, missing bugs that only manifest und", "How does Deployment Strategies I: Canary Releases & Progressive Delivery with Flagger scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-1', 'phase-12-lesson-01-cognitive-agent-architectures-beyond-simp', 'module-13', 1, 'Lesson 13.1: Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains', 'Prerequisites: Phase 10, Lesson 10.2', 'Prerequisites: Phase 10, Lesson 10.2 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 50.0, '# Lesson 12.1: Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 10, Lesson 10.2
- **Subtopics**:
  - `12.1.1` The spectrum of autonomy: deterministic scripts vs prompt chains vs autonomous agents with dynamic branching
  - `12.1.2` Core components of an agent: Brain (LLM), Memory (short-term working state & long-term episodic memory), Tools, and Planning
  - `12.1.3` The Sense-Plan-Act cycle: perceiving environment feedback, updating internal beliefs, formulating plans, and executing actions
  - `12.1.4` Bounded rationality in LLM agents: token horizon limits, stochastic decision making, and cascading failure propagation
  - `12.1.5` Deterministic guardrails on non-deterministic models: constraining agent state transitions with state machines
  - `12.1.6` Architecture overview: designing agent workflows that guarantee business logic invariants while leveraging model flexibility
- **Key Failure Modes & Edge Cases**: Granting an un-constrained agent open loop execution without state boundaries, burning thousands of dollars in infinite tool loops.
- **Verification & Mastery Check**: Draft an architectural state chart comparing linear prompt chaining vs dynamic cyclic agent state execution.
- **Project Application**: CodeAgent: Agent architectural specification.', '{"solution.py": "# Phase 12 // Lesson 12.1: Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains\n\ndef solve():\n    \"\"\"\n    Verification: Draft an architectural state chart comparing linear prompt chaining vs dynamic cyclic agent state ex\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.1", "subtopics_count": 6, "verification_criteria": "Draft an architectural state chart comparing linear prompt chaining vs dynamic cyclic agent state execution.", "subtopics": ["12.1.1 The spectrum of autonomy: deterministic scripts vs prompt chains vs autonomous agents with dynamic branching", "12.1.2 Core components of an agent: Brain (LLM), Memory (short-term working state & long-term episodic memory), Tools, and Planning", "12.1.3 The Sense-Plan-Act cycle: perceiving environment feedback, updating internal beliefs, formulating plans, and executing actions", "12.1.4 Bounded rationality in LLM agents: token horizon limits, stochastic decision making, and cascading failure propagation", "12.1.5 Deterministic guardrails on non-deterministic models: constraining agent state transitions with state machines", "12.1.6 Architecture overview: designing agent workflows that guarantee business logic invariants while leveraging model flexibility"]}'::jsonb, '["Explain how this implementation prevents: Granting an un-constrained agent open loop execution without state boundaries, burning thousands of dollars in infinite ", "How does Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-2', 'phase-12-lesson-02-reasoning-action-paradigms-react-plan-and', 'module-13', 2, 'Lesson 13.2: Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion', 'Prerequisites: Lesson 12.1', 'Prerequisites: Lesson 12.1 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 100.0, '# Lesson 12.2: Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 12.1
- **Subtopics**:
  - `12.2.1` ReAct (Yao et al.): interleaving Reasoning (''Thought''), Action (''Tool Call''), and Observation (''Environment Feedback'')
  - `12.2.2` Failure modes of pure ReAct: local greedy planning, losing track of high-level goals, and cycling between similar actions
  - `12.2.3` Plan-and-Solve (Wang et al.): generating an explicit multi-step plan upfront, then executing sub-tasks systematically
  - `12.2.4` Reflexion (Shinn et al.): verbal self-reflection, evaluating task outcomes, writing critique into episodic memory, and retrying
  - `12.2.5` Tree-of-Thoughts (ToT) (Yao et al.): exploring multiple reasoning paths concurrently with backtracking and lookahead evaluation
  - `12.2.6` Selecting the right architecture: matching task complexity to cognitive overhead and latency budgets
- **Key Failure Modes & Edge Cases**: Using pure ReAct on complex 20-step software engineering tasks, causing the agent to get stuck in myopic 3-step loops.
- **Verification & Mastery Check**: Implement a Reflexion agent harness that critiques its own failed Python code executions and succeeds on the second attempt.
- **Project Application**: CodeAgent: Cognitive loop controller.', '{"solution.py": "# Phase 12 // Lesson 12.2: Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Reflexion agent harness that critiques its own failed Python code executions and succeed\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.2", "subtopics_count": 6, "verification_criteria": "Implement a Reflexion agent harness that critiques its own failed Python code executions and succeeds on the second attempt.", "subtopics": ["12.2.1 ReAct (Yao et al.): interleaving Reasoning (''Thought''), Action (''Tool Call''), and Observation (''Environment Feedback'')", "12.2.2 Failure modes of pure ReAct: local greedy planning, losing track of high-level goals, and cycling between similar actions", "12.2.3 Plan-and-Solve (Wang et al.): generating an explicit multi-step plan upfront, then executing sub-tasks systematically", "12.2.4 Reflexion (Shinn et al.): verbal self-reflection, evaluating task outcomes, writing critique into episodic memory, and retrying", "12.2.5 Tree-of-Thoughts (ToT) (Yao et al.): exploring multiple reasoning paths concurrently with backtracking and lookahead evaluation", "12.2.6 Selecting the right architecture: matching task complexity to cognitive overhead and latency budgets"]}'::jsonb, '["Explain how this implementation prevents: Using pure ReAct on complex 20-step software engineering tasks, causing the agent to get stuck in myopic 3-step loops.", "How does Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-3', 'phase-12-lesson-03-tool-engineering-i-dynamic-schema-generat', 'module-13', 3, 'Lesson 13.3: Tool Engineering I: Dynamic Schema Generation & Pydantic Validation', 'Prerequisites: Phase 1, Phase 10', 'Prerequisites: Phase 1, Phase 10 | Subtopics: 6 items', 'Systems project application', 340, 13, 3000.0, 150.0, '# Lesson 12.3: Tool Engineering I: Dynamic Schema Generation & Pydantic Validation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Phase 10
- **Subtopics**:
  - `12.3.1` Tools as typed RPC interfaces: exposing functions, APIs, and databases to LLMs via JSON Schema definitions
  - `12.3.2` Writing clear, unambiguous tool descriptions: specifying parameter types, required fields, constraints, and return schemas
  - `12.3.3` Pydantic schema generation: using `TypeAdapter` and Pydantic models to automatically generate clean OpenAPI/JSON schemas
  - `12.3.4` Input validation and sanitization: intercepting invalid LLM tool arguments before execution and returning structured errors
  - `12.3.5` Handling missing arguments: implementing conversational clarification loops when required tool parameters are omitted
  - `12.3.6` Security threat modeling for tools: preventing privilege escalation, SQL injection, and command injection via tool parameters
- **Key Failure Modes & Edge Cases**: Providing vague tool descriptions (''executes stuff''), causing the LLM to hallucinate invalid parameter names and argument types.
- **Verification & Mastery Check**: Build a tool registry library in Python that dynamically exports Pydantic-validated callable tools to OpenAI and Anthropic formats.
- **Project Application**: CodeAgent: Core tool registry engine.', '{"solution.py": "# Phase 12 // Lesson 12.3: Tool Engineering I: Dynamic Schema Generation & Pydantic Validation\n\ndef solve():\n    \"\"\"\n    Verification: Build a tool registry library in Python that dynamically exports Pydantic-validated callable tools t\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.3", "subtopics_count": 6, "verification_criteria": "Build a tool registry library in Python that dynamically exports Pydantic-validated callable tools to OpenAI and Anthropic formats.", "subtopics": ["12.3.1 Tools as typed RPC interfaces: exposing functions, APIs, and databases to LLMs via JSON Schema definitions", "12.3.2 Writing clear, unambiguous tool descriptions: specifying parameter types, required fields, constraints, and return schemas", "12.3.3 Pydantic schema generation: using `TypeAdapter` and Pydantic models to automatically generate clean OpenAPI/JSON schemas", "12.3.4 Input validation and sanitization: intercepting invalid LLM tool arguments before execution and returning structured errors", "12.3.5 Handling missing arguments: implementing conversational clarification loops when required tool parameters are omitted", "12.3.6 Security threat modeling for tools: preventing privilege escalation, SQL injection, and command injection via tool parameters"]}'::jsonb, '["Explain how this implementation prevents: Providing vague tool descriptions (''executes stuff''), causing the LLM to hallucinate invalid parameter names and argumen", "How does Tool Engineering I: Dynamic Schema Generation & Pydantic Validation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-4', 'phase-12-lesson-04-tool-engineering-ii-idempotency-timeouts-', 'module-13', 4, 'Lesson 13.4: Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery', 'Prerequisites: Phase 4, Lesson 12.3', 'Prerequisites: Phase 4, Lesson 12.3 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 200.0, '# Lesson 12.4: Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 12.3
- **Subtopics**:
  - `12.4.1` The unreliability of external environments: handling network timeouts, API rate limits, and non-deterministic tool failures
  - `12.4.2` Idempotent tool design: ensuring that duplicate tool executions do not produce unintended side effects (e.g. double charging)
  - `12.4.3` Structured error returns: why raising Python exceptions crashes agents; formatting errors as informative feedback strings
  - `12.4.4` Designing actionable error messages: providing the LLM with exact guidance on how to fix invalid inputs upon failure
  - `12.4.5` Execution timeouts: wrapping tool executions with strict `asyncio.timeout()` boundaries to prevent hung external processes
  - `12.4.6` Tool output truncation: summarizing massive tool return payloads (e.g. 50MB file reads) to prevent blowing the context window
- **Key Failure Modes & Edge Cases**: Allowing an unhandled tool exception to bubble up and crash the entire agent runtime, losing all conversational session state.
- **Verification & Mastery Check**: Implement a resilient tool execution wrapper supporting timeouts, exponential retries, and informative error formatting for LLMs.
- **Project Application**: CodeAgent: Resilient tool execution pipeline.', '{"solution.py": "# Phase 12 // Lesson 12.4: Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery\n\ndef solve():\n    \"\"\"\n    Verification: Implement a resilient tool execution wrapper supporting timeouts, exponential retries, and informati\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.4", "subtopics_count": 6, "verification_criteria": "Implement a resilient tool execution wrapper supporting timeouts, exponential retries, and informative error formatting for LLMs.", "subtopics": ["12.4.1 The unreliability of external environments: handling network timeouts, API rate limits, and non-deterministic tool failures", "12.4.2 Idempotent tool design: ensuring that duplicate tool executions do not produce unintended side effects (e.g. double charging)", "12.4.3 Structured error returns: why raising Python exceptions crashes agents; formatting errors as informative feedback strings", "12.4.4 Designing actionable error messages: providing the LLM with exact guidance on how to fix invalid inputs upon failure", "12.4.5 Execution timeouts: wrapping tool executions with strict `asyncio.timeout()` boundaries to prevent hung external processes", "12.4.6 Tool output truncation: summarizing massive tool return payloads (e.g. 50MB file reads) to prevent blowing the context window"]}'::jsonb, '["Explain how this implementation prevents: Allowing an unhandled tool exception to bubble up and crash the entire agent runtime, losing all conversational session ", "How does Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-5', 'phase-12-lesson-05-agent-memory-systems-working-memory-episo', 'module-13', 5, 'Lesson 13.5: Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory', 'Prerequisites: Phase 10, Lesson 12.1', 'Prerequisites: Phase 10, Lesson 12.1 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 250.0, '# Lesson 12.5: Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 10, Lesson 12.1
- **Subtopics**:
  - `12.5.1` Taxonomy of agent memory: Working Memory (active context), Episodic Memory (past task experiences), Semantic Memory (knowledge)
  - `12.5.2` Managing Working Memory: rolling window message history, summarization compression, and token budget management
  - `12.5.3` Episodic Memory with Vector Stores: embedding past execution trajectories, indexing task outcomes, and retrieving relevant past solutions
  - `12.5.4` Entity Memory: maintaining a structured JSON knowledge graph of extracted user preferences, project configurations, and facts
  - `12.5.5` Memory consolidation: background tasks that distill daily conversation logs into concise long-term user profiles
  - `12.5.6` Privacy and memory purging: implementing GDPR-compliant memory forgetfulness APIs to delete user history on demand
- **Key Failure Modes & Edge Cases**: Unbounded message history growth causing context window overflow and astronomical API token costs on long-running tasks.
- **Verification & Mastery Check**: Build a hybrid agent memory system combining in-memory message history with vector-indexed episodic retrieval of past task logs.
- **Project Application**: CodeAgent: Multi-tiered agent memory architecture.', '{"solution.py": "# Phase 12 // Lesson 12.5: Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory\n\ndef solve():\n    \"\"\"\n    Verification: Build a hybrid agent memory system combining in-memory message history with vector-indexed episodic \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.5", "subtopics_count": 6, "verification_criteria": "Build a hybrid agent memory system combining in-memory message history with vector-indexed episodic retrieval of past task logs.", "subtopics": ["12.5.1 Taxonomy of agent memory: Working Memory (active context), Episodic Memory (past task experiences), Semantic Memory (knowledge)", "12.5.2 Managing Working Memory: rolling window message history, summarization compression, and token budget management", "12.5.3 Episodic Memory with Vector Stores: embedding past execution trajectories, indexing task outcomes, and retrieving relevant past solutions", "12.5.4 Entity Memory: maintaining a structured JSON knowledge graph of extracted user preferences, project configurations, and facts", "12.5.5 Memory consolidation: background tasks that distill daily conversation logs into concise long-term user profiles", "12.5.6 Privacy and memory purging: implementing GDPR-compliant memory forgetfulness APIs to delete user history on demand"]}'::jsonb, '["Explain how this implementation prevents: Unbounded message history growth causing context window overflow and astronomical API token costs on long-running tasks.", "How does Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
