INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-12-26', 'phase-12-lesson-26-agent-trajectory-evaluation-benchmarking-', 'module-13', 26, 'Lesson 13.26: Agent Trajectory Evaluation: Benchmarking on SWE-bench & GAIA', 'Prerequisites: Phase 10, Lesson 12.20', 'Prerequisites: Phase 10, Lesson 12.20 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 1300.0, '# Lesson 12.26: Agent Trajectory Evaluation: Benchmarking on SWE-bench & GAIA

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 10, Lesson 12.20
- **Subtopics**:
  - `12.26.1` Benchmarking autonomous agents: moving from simple Q&A benchmarks to real-world software engineering benchmarks
  - `12.26.2` SWE-bench (Princeton): evaluating agents on resolving real GitHub issues from popular open-source repositories
  - `12.26.3` SWE-bench task anatomy: issue description, base repo commit, environment setup, and gold evaluation patch (`pytest` verification)
  - `12.26.4` General AI Assistants (GAIA) benchmark: multi-modal, tool-use, multi-step real-world assistant evaluation tasks
  - `12.26.5` Evaluation metrics: Pass@1, execution trajectory length (number of tool calls), total token cost, and wall-clock time
  - `12.26.6` Analyzing failure trajectories: classifying agent failures (bad plan, file editing error, test failure, context overflow)
- **Key Failure Modes & Edge Cases**: Evaluating agents on synthetic toy problems, failing to predict catastrophic failure rates on messy real-world codebases.
- **Verification & Mastery Check**: Set up a local SWE-bench evaluation runner; evaluate CodeAgent on 5 real GitHub issues and compute exact Pass@1 accuracy.
- **Project Application**: CodeAgent: SWE-bench evaluation and trajectory analysis harness.', '{"solution.py": "# Phase 12 // Lesson 12.26: Agent Trajectory Evaluation: Benchmarking on SWE-bench & GAIA\n\ndef solve():\n    \"\"\"\n    Verification: Set up a local SWE-bench evaluation runner; evaluate CodeAgent on 5 real GitHub issues and compute e\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.26", "subtopics_count": 6, "verification_criteria": "Set up a local SWE-bench evaluation runner; evaluate CodeAgent on 5 real GitHub issues and compute exact Pass@1 accuracy.", "subtopics": ["12.26.1 Benchmarking autonomous agents: moving from simple Q&A benchmarks to real-world software engineering benchmarks", "12.26.2 SWE-bench (Princeton): evaluating agents on resolving real GitHub issues from popular open-source repositories", "12.26.3 SWE-bench task anatomy: issue description, base repo commit, environment setup, and gold evaluation patch (`pytest` verification)", "12.26.4 General AI Assistants (GAIA) benchmark: multi-modal, tool-use, multi-step real-world assistant evaluation tasks", "12.26.5 Evaluation metrics: Pass@1, execution trajectory length (number of tool calls), total token cost, and wall-clock time", "12.26.6 Analyzing failure trajectories: classifying agent failures (bad plan, file editing error, test failure, context overflow)"]}'::jsonb, '["Explain how this implementation prevents: Evaluating agents on synthetic toy problems, failing to predict catastrophic failure rates on messy real-world codebases", "How does Agent Trajectory Evaluation: Benchmarking on SWE-bench & GAIA scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-27', 'phase-12-lesson-27-trajectory-mining-synthetic-distillation-', 'module-13', 27, 'Lesson 13.27: Trajectory Mining & Synthetic Distillation for Agent Fine-Tuning', 'Prerequisites: Phase 9, Phase 10, Lesson 12.26', 'Prerequisites: Phase 9, Phase 10, Lesson 12.26 | Subtopics: 6 items', 'Systems project application', 340, 13, 3000.0, 1350.0, '# Lesson 12.27: Trajectory Mining & Synthetic Distillation for Agent Fine-Tuning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 10, Lesson 12.26
- **Subtopics**:
  - `12.27.1` The cost bottleneck of frontier models: running agent loops on GPT-4 / Claude 3.5 Sonnet costs $0.50-$2.00 per task
  - `12.27.2` Trajectory Mining: collecting thousands of successful multi-step execution traces from frontier models
  - `12.27.3` Filtering high-quality trajectories: filtering for traces that solved tasks with minimal tool calls and zero syntax errors
  - `12.27.4` Formatting agent trajectories for supervised fine-tuning (SFT): tokenizing multi-turn messages, tool calls, and environment observations
  - `12.27.5` Fine-tuning open-source models (Llama-3-8B) on agent trajectories: teaching smaller models exact tool calling and reasoning habits
  - `12.27.6` Performance parity: achieving 90% of frontier model agent accuracy at 5% of the API cost using distilled local models
- **Key Failure Modes & Edge Cases**: Fine-tuning on failed or meandering agent trajectories, training the distilled model to repeat infinite loops and syntax bugs.
- **Verification & Mastery Check**: Mine 50 successful CodeAgent trajectories, clean into structured SFT format, and prepare a dataset for model distillation.
- **Project Application**: CodeAgent: Trajectory mining and training dataset generator.', '{"solution.py": "# Phase 12 // Lesson 12.27: Trajectory Mining & Synthetic Distillation for Agent Fine-Tuning\n\ndef solve():\n    \"\"\"\n    Verification: Mine 50 successful CodeAgent trajectories, clean into structured SFT format, and prepare a dataset f\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.27", "subtopics_count": 6, "verification_criteria": "Mine 50 successful CodeAgent trajectories, clean into structured SFT format, and prepare a dataset for model distillation.", "subtopics": ["12.27.1 The cost bottleneck of frontier models: running agent loops on GPT-4 / Claude 3.5 Sonnet costs $0.50-$2.00 per task", "12.27.2 Trajectory Mining: collecting thousands of successful multi-step execution traces from frontier models", "12.27.3 Filtering high-quality trajectories: filtering for traces that solved tasks with minimal tool calls and zero syntax errors", "12.27.4 Formatting agent trajectories for supervised fine-tuning (SFT): tokenizing multi-turn messages, tool calls, and environment observations", "12.27.5 Fine-tuning open-source models (Llama-3-8B) on agent trajectories: teaching smaller models exact tool calling and reasoning habits", "12.27.6 Performance parity: achieving 90% of frontier model agent accuracy at 5% of the API cost using distilled local models"]}'::jsonb, '["Explain how this implementation prevents: Fine-tuning on failed or meandering agent trajectories, training the distilled model to repeat infinite loops and syntax", "How does Trajectory Mining & Synthetic Distillation for Agent Fine-Tuning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-28', 'phase-12-lesson-28-production-agent-observability-tracing-tr', 'module-13', 28, 'Lesson 13.28: Production Agent Observability: Tracing Trajectories with Langfuse & Arize', 'Prerequisites: Phase 7, Phase 10, Lesson 12.8', 'Prerequisites: Phase 7, Phase 10, Lesson 12.8 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 1400.0, '# Lesson 12.28: Production Agent Observability: Tracing Trajectories with Langfuse & Arize

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Phase 10, Lesson 12.8
- **Subtopics**:
  - `12.28.1` The black-box agent problem: diagnosing why an agent took a wrong turn at step 14 of a 25-step execution trajectory
  - `12.28.2` Distributed tracing for agent graphs: instrumenting every node, tool call, LLM invocation, and state transition with OpenInference
  - `12.28.3` Visualizing agent execution trees: inspecting intermediate state updates, tool inputs/outputs, and token costs in Langfuse UI
  - `12.28.4` Latency profiling: pinpointing which specific tool executions or LLM calls dominated total execution duration
  - `12.28.5` Cost analytics: tracking dollar cost per task, token efficiency, and identifying prompt bloat across long trajectories
  - `12.28.6` Alerting on runaway agents: automated alerts for agents exceeding recursion thresholds or burning $> $5 on a single session
- **Key Failure Modes & Edge Cases**: Lacking granular span tracing, forcing engineers to manually comb through 10,000 lines of terminal stdout logs to find bugs.
- **Verification & Mastery Check**: Instrument CodeAgent with Langfuse; capture a complete 20-step execution trace and analyze token cost and tool latency bottlenecks.
- **Project Application**: CodeAgent: Production observability and trajectory tracing suite.', '{"solution.py": "# Phase 12 // Lesson 12.28: Production Agent Observability: Tracing Trajectories with Langfuse & Arize\n\ndef solve():\n    \"\"\"\n    Verification: Instrument CodeAgent with Langfuse; capture a complete 20-step execution trace and analyze token cos\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.28", "subtopics_count": 6, "verification_criteria": "Instrument CodeAgent with Langfuse; capture a complete 20-step execution trace and analyze token cost and tool latency bottlenecks.", "subtopics": ["12.28.1 The black-box agent problem: diagnosing why an agent took a wrong turn at step 14 of a 25-step execution trajectory", "12.28.2 Distributed tracing for agent graphs: instrumenting every node, tool call, LLM invocation, and state transition with OpenInference", "12.28.3 Visualizing agent execution trees: inspecting intermediate state updates, tool inputs/outputs, and token costs in Langfuse UI", "12.28.4 Latency profiling: pinpointing which specific tool executions or LLM calls dominated total execution duration", "12.28.5 Cost analytics: tracking dollar cost per task, token efficiency, and identifying prompt bloat across long trajectories", "12.28.6 Alerting on runaway agents: automated alerts for agents exceeding recursion thresholds or burning $> $5 on a single session"]}'::jsonb, '["Explain how this implementation prevents: Lacking granular span tracing, forcing engineers to manually comb through 10,000 lines of terminal stdout logs to find b", "How does Production Agent Observability: Tracing Trajectories with Langfuse & Arize scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-29', 'phase-12-lesson-29-agentic-security-guardrails-sandboxing-pr', 'module-13', 29, 'Lesson 13.29: Agentic Security & Guardrails: Sandboxing, Privilege Escalation & Blast Radius', 'Prerequisites: Phase 5, Lesson 12.13, Lesson 12.14', 'Prerequisites: Phase 5, Lesson 12.13, Lesson 12.14 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 1450.0, '# Lesson 12.29: Agentic Security & Guardrails: Sandboxing, Privilege Escalation & Blast Radius

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Lesson 12.13, Lesson 12.14
- **Subtopics**:
  - `12.29.1` Security threat landscape for autonomous agents: OWASP Top 10 for LLM Applications and Agentic Systems
  - `12.29.2` Indirect Prompt Injection in agents: external data (scraped web pages, cloned git repos, user issues) hijacking agent tool execution
  - `12.29.3` Privilege Escalation vectors: agent using low-privilege tools to modify high-privilege configuration files or credentials
  - `12.29.4` Blast Radius Containment: least privilege tool permissions, scoped API keys, sandboxed filesystem roots, and resource quotas
  - `12.29.5` Automated safety guardrails: intercepting dangerous bash commands (`rm -rf`, `curl | bash`, `chmod 777`) via pre-execution hooks
  - `12.29.6` Auditing and compliance: immutable cryptographic logging of all agent actions, approvals, and environment mutations
- **Key Failure Modes & Edge Cases**: Cloning a malicious repository containing a prompt injection in README.md that instructs CodeAgent to exfiltrate AWS credentials.
- **Verification & Mastery Check**: Execute an indirect prompt injection attack against CodeAgent; verify that pre-execution security hooks block malicious tool execution.
- **Project Application**: CodeAgent: Enterprise security guardrails and injection defense suite.', '{"solution.py": "# Phase 12 // Lesson 12.29: Agentic Security & Guardrails: Sandboxing, Privilege Escalation & Blast Radius\n\ndef solve():\n    \"\"\"\n    Verification: Execute an indirect prompt injection attack against CodeAgent; verify that pre-execution security ho\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.29", "subtopics_count": 6, "verification_criteria": "Execute an indirect prompt injection attack against CodeAgent; verify that pre-execution security hooks block malicious tool execution.", "subtopics": ["12.29.1 Security threat landscape for autonomous agents: OWASP Top 10 for LLM Applications and Agentic Systems", "12.29.2 Indirect Prompt Injection in agents: external data (scraped web pages, cloned git repos, user issues) hijacking agent tool execution", "12.29.3 Privilege Escalation vectors: agent using low-privilege tools to modify high-privilege configuration files or credentials", "12.29.4 Blast Radius Containment: least privilege tool permissions, scoped API keys, sandboxed filesystem roots, and resource quotas", "12.29.5 Automated safety guardrails: intercepting dangerous bash commands (`rm -rf`, `curl | bash`, `chmod 777`) via pre-execution hooks", "12.29.6 Auditing and compliance: immutable cryptographic logging of all agent actions, approvals, and environment mutations"]}'::jsonb, '["Explain how this implementation prevents: Cloning a malicious repository containing a prompt injection in README.md that instructs CodeAgent to exfiltrate AWS cre", "How does Agentic Security & Guardrails: Sandboxing, Privilege Escalation & Blast Radius scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-30', 'phase-12-lesson-30-codeagent-production-deployment-autonomou', 'module-13', 30, 'Lesson 13.30: CodeAgent Production Deployment & Autonomous Engineering Defense', 'Prerequisites: Phase 6, Phase 7, Lesson 12.28', 'Prerequisites: Phase 6, Phase 7, Lesson 12.28 | Subtopics: 6 items', 'Systems project application', 340, 13, 3000.0, 1500.0, '# Lesson 12.30: CodeAgent Production Deployment & Autonomous Engineering Defense

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 6, Phase 7, Lesson 12.28
- **Subtopics**:
  - `12.30.1` Assembling the complete autonomous software engineer: LangGraph state machine, PostgreSQL checkpointer, hardened Docker sandbox
  - `12.30.2` Full-stack agent integration: Next.js frontend streaming live agent thoughts, tool calls, diff previews, and HITL approval modals
  - `12.30.3` Deploying CodeAgent on Kubernetes: asynchronous Celery worker pods running sandboxed containers, isolated from host cluster
  - `12.30.4` Production readiness review: validating resilience against API outages, database restarts, and adversarial prompt attacks
  - `12.30.5` The Autonomous Engineering Benchmark: setting CodeAgent loose on an unfamiliar codebase to resolve an issue with zero human intervention
  - `12.30.6` Architectural defense: presenting system architecture, safety bounds, SWE-bench performance, and cost engineering to leadership
- **Key Failure Modes & Edge Cases**: Deploying CodeAgent directly into production repositories with write permissions without branch protection or PR gates.
- **Verification & Mastery Check**: Deploy CodeAgent to an isolated environment; assign it a real bug in a web app, and verify that it opens a verified PR with passing tests.
- **Project Application**: CodeAgent: Final end-to-end production deployment and system defense.', '{"solution.py": "# Phase 12 // Lesson 12.30: CodeAgent Production Deployment & Autonomous Engineering Defense\n\ndef solve():\n    \"\"\"\n    Verification: Deploy CodeAgent to an isolated environment; assign it a real bug in a web app, and verify that it o\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.30", "subtopics_count": 6, "verification_criteria": "Deploy CodeAgent to an isolated environment; assign it a real bug in a web app, and verify that it opens a verified PR with passing tests.", "subtopics": ["12.30.1 Assembling the complete autonomous software engineer: LangGraph state machine, PostgreSQL checkpointer, hardened Docker sandbox", "12.30.2 Full-stack agent integration: Next.js frontend streaming live agent thoughts, tool calls, diff previews, and HITL approval modals", "12.30.3 Deploying CodeAgent on Kubernetes: asynchronous Celery worker pods running sandboxed containers, isolated from host cluster", "12.30.4 Production readiness review: validating resilience against API outages, database restarts, and adversarial prompt attacks", "12.30.5 The Autonomous Engineering Benchmark: setting CodeAgent loose on an unfamiliar codebase to resolve an issue with zero human intervention", "12.30.6 Architectural defense: presenting system architecture, safety bounds, SWE-bench performance, and cost engineering to leadership"]}'::jsonb, '["Explain how this implementation prevents: Deploying CodeAgent directly into production repositories with write permissions without branch protection or PR gates.", "How does CodeAgent Production Deployment & Autonomous Engineering Defense scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-1', 'phase-13-lesson-01-track-a-micro-frontends-module-federation', 'module-14', 1, 'Lesson 14.1: Track A: Micro-Frontends & Module Federation at Enterprise Scale', 'Prerequisites: Phase 6, Lesson 6.16', 'Prerequisites: Phase 6, Lesson 6.16 | Subtopics: 6 items', 'Systems project application', 360, 14, 3310.0, 50.0, '# Lesson 13.1: Track A: Micro-Frontends & Module Federation at Enterprise Scale

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 6, Lesson 6.16
- **Subtopics**:
  - `13.1.1` Micro-frontend architectural patterns: independent deployments, autonomous team lifecycles, and shared app shells
  - `13.1.2` Webpack/Rspack Module Federation internals: host containers, remote containers, shared dependency singletons, and version negotiation
  - `13.1.3` Runtime integration vs build-time composition: dynamic script injection, sandboxed CSS styling, and global state isolation
  - `13.1.4` Cross-micro-frontend communication: event bus patterns, shared stores via custom browser events, and URL routing synchronization
  - `13.1.5` Shared dependency optimization: resolving React singleton conflicts (`shared: { react: { singleton: true } }`) and version mismatches
  - `13.1.6` Resilience and fault tolerance: graceful fallback rendering when remote micro-frontends experience deployment or network outages
- **Key Failure Modes & Edge Cases**: Duplicate React instances loaded in runtime breaking hook contexts; remote micro-frontend crash taking down entire host shell.
- **Verification & Mastery Check**: Build a host container dynamically loading two remote micro-frontends with shared React singletons and isolated CSS namespaces.
- **Project Application**: Track A Capstone: Enterprise micro-frontend platform.', '{"solution.py": "# Phase 13 // Lesson 13.1: Track A: Micro-Frontends & Module Federation at Enterprise Scale\n\ndef solve():\n    \"\"\"\n    Verification: Build a host container dynamically loading two remote micro-frontends with shared React singletons a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.1", "subtopics_count": 6, "verification_criteria": "Build a host container dynamically loading two remote micro-frontends with shared React singletons and isolated CSS namespaces.", "subtopics": ["13.1.1 Micro-frontend architectural patterns: independent deployments, autonomous team lifecycles, and shared app shells", "13.1.2 Webpack/Rspack Module Federation internals: host containers, remote containers, shared dependency singletons, and version negotiation", "13.1.3 Runtime integration vs build-time composition: dynamic script injection, sandboxed CSS styling, and global state isolation", "13.1.4 Cross-micro-frontend communication: event bus patterns, shared stores via custom browser events, and URL routing synchronization", "13.1.5 Shared dependency optimization: resolving React singleton conflicts (`shared: { react: { singleton: true } }`) and version mismatches", "13.1.6 Resilience and fault tolerance: graceful fallback rendering when remote micro-frontends experience deployment or network outages"]}'::jsonb, '["Explain how this implementation prevents: Duplicate React instances loaded in runtime breaking hook contexts; remote micro-frontend crash taking down entire host ", "How does Track A: Micro-Frontends & Module Federation at Enterprise Scale scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-2', 'phase-13-lesson-02-track-a-local-first-software-offline-real', 'module-14', 2, 'Lesson 14.2: Track A: Local-First Software & Offline Real-Time Sync with CRDTs (Yjs)', 'Prerequisites: Phase 6, Phase 7, Lesson 7.5', 'Prerequisites: Phase 6, Phase 7, Lesson 7.5 | Subtopics: 6 items', 'Systems project application', 360, 14, 3370.0, 100.0, '# Lesson 13.2: Track A: Local-First Software & Offline Real-Time Sync with CRDTs (Yjs)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 6, Phase 7, Lesson 7.5
- **Subtopics**:
  - `13.2.1` The Local-First software manifesto: immediate local read/write operations, full offline availability, and background synchronization
  - `13.2.2` Conflict-Free Replicated Data Types (CRDTs) in the browser: Yjs architecture, binary state vectors, and update encoding
  - `13.2.3` Shared types: Y.Doc, Y.Map, Y.Array, and Y.Text supporting collaborative rich text editing with zero merge conflicts
  - `13.2.4` Persistence layer: synchronizing Yjs binary documents to client-side IndexedDB via `y-indexeddb` for offline persistence
  - `13.2.5` Network synchronization providers: WebSockets (`y-websocket`) and WebRTC (`y-webrtc`) for peer-to-peer real-time updates
  - `13.2.6` Reconciliation and awareness: tracking user presence (cursors, selections, active status) across multi-user collaborative sessions
- **Key Failure Modes & Edge Cases**: State vector bloat causing client IndexedDB performance to degrade; unhandled connection dropouts losing offline document edits.
- **Verification & Mastery Check**: Build a local-first collaborative document editor that functions 100% offline, persists to IndexedDB, and syncs seamlessly upon reconnect.
- **Project Application**: Track A Capstone: Local-first collaborative editor.', '{"solution.py": "# Phase 13 // Lesson 13.2: Track A: Local-First Software & Offline Real-Time Sync with CRDTs (Yjs)\n\ndef solve():\n    \"\"\"\n    Verification: Build a local-first collaborative document editor that functions 100% offline, persists to IndexedDB\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.2", "subtopics_count": 6, "verification_criteria": "Build a local-first collaborative document editor that functions 100% offline, persists to IndexedDB, and syncs seamlessly upon reconnect.", "subtopics": ["13.2.1 The Local-First software manifesto: immediate local read/write operations, full offline availability, and background synchronization", "13.2.2 Conflict-Free Replicated Data Types (CRDTs) in the browser: Yjs architecture, binary state vectors, and update encoding", "13.2.3 Shared types: Y.Doc, Y.Map, Y.Array, and Y.Text supporting collaborative rich text editing with zero merge conflicts", "13.2.4 Persistence layer: synchronizing Yjs binary documents to client-side IndexedDB via `y-indexeddb` for offline persistence", "13.2.5 Network synchronization providers: WebSockets (`y-websocket`) and WebRTC (`y-webrtc`) for peer-to-peer real-time updates", "13.2.6 Reconciliation and awareness: tracking user presence (cursors, selections, active status) across multi-user collaborative sessions"]}'::jsonb, '["Explain how this implementation prevents: State vector bloat causing client IndexedDB performance to degrade; unhandled connection dropouts losing offline documen", "How does Track A: Local-First Software & Offline Real-Time Sync with CRDTs (Yjs) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-3', 'phase-13-lesson-03-track-a-high-performance-canvas-webgl-ren', 'module-14', 3, 'Lesson 14.3: Track A: High-Performance Canvas & WebGL Rendering', 'Prerequisites: Phase 0, Phase 6', 'Prerequisites: Phase 0, Phase 6 | Subtopics: 6 items', 'Systems project application', 360, 14, 3250.0, 150.0, '# Lesson 13.3: Track A: High-Performance Canvas & WebGL Rendering

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 6
- **Subtopics**:
  - `13.3.1` Browser graphics rendering: DOM/SVG limits (performance drops past 2,000 elements) vs HTML5 Canvas and WebGL
  - `13.3.2` Canvas 2D rendering context: immediate mode rendering, coordinate systems, transformation matrices, and path drawing
  - `13.3.3` Optimizing Canvas 2D: OffscreenCanvas, double buffering, spatial indexing (QuadTree) for fast viewport culling
  - `13.3.4` WebGL fundamentals: GPU pipeline, vertex shaders, fragment shaders, GLSL syntax, and buffer attributes
  - `13.3.5` Rendering 100,000 interactive data points at 60fps: instanced rendering, memory-packed Float32Array buffers, and GPU draw calls
  - `13.3.6` Hit testing at scale: GPU color picking vs spatial CPU QuadTree traversal for mouse hover and click interactions
- **Key Failure Modes & Edge Cases**: Executing expensive Canvas drawing calls on the main thread during scroll events, dropping frames to 15fps.
- **Verification & Mastery Check**: Build a real-time financial chart rendering 100,000 data points at a stable 60fps using OffscreenCanvas and QuadTree culling.
- **Project Application**: Track A Capstone: High-frequency charting engine.', '{"solution.py": "# Phase 13 // Lesson 13.3: Track A: High-Performance Canvas & WebGL Rendering\n\ndef solve():\n    \"\"\"\n    Verification: Build a real-time financial chart rendering 100,000 data points at a stable 60fps using OffscreenCan\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.3", "subtopics_count": 6, "verification_criteria": "Build a real-time financial chart rendering 100,000 data points at a stable 60fps using OffscreenCanvas and QuadTree culling.", "subtopics": ["13.3.1 Browser graphics rendering: DOM/SVG limits (performance drops past 2,000 elements) vs HTML5 Canvas and WebGL", "13.3.2 Canvas 2D rendering context: immediate mode rendering, coordinate systems, transformation matrices, and path drawing", "13.3.3 Optimizing Canvas 2D: OffscreenCanvas, double buffering, spatial indexing (QuadTree) for fast viewport culling", "13.3.4 WebGL fundamentals: GPU pipeline, vertex shaders, fragment shaders, GLSL syntax, and buffer attributes", "13.3.5 Rendering 100,000 interactive data points at 60fps: instanced rendering, memory-packed Float32Array buffers, and GPU draw calls", "13.3.6 Hit testing at scale: GPU color picking vs spatial CPU QuadTree traversal for mouse hover and click interactions"]}'::jsonb, '["Explain how this implementation prevents: Executing expensive Canvas drawing calls on the main thread during scroll events, dropping frames to 15fps.", "How does Track A: High-Performance Canvas & WebGL Rendering scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-4', 'phase-13-lesson-04-track-a-webassembly-wasm-frontend-modules', 'module-14', 4, 'Lesson 14.4: Track A: WebAssembly (Wasm) Frontend Modules & Rust Compilation', 'Prerequisites: Phase 0, Phase 1, Phase 6', 'Prerequisites: Phase 0, Phase 1, Phase 6 | Subtopics: 6 items', 'Systems project application', 360, 14, 3310.0, 200.0, '# Lesson 13.4: Track A: WebAssembly (Wasm) Frontend Modules & Rust Compilation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 1, Phase 6
- **Subtopics**:
  - `13.4.1` Why WebAssembly on the frontend: near-native execution speed for computationally intensive client-side tasks
  - `13.4.2` Compiling Rust to WebAssembly: `wasm-pack`, `wasm-bindgen`, and generating TypeScript declaration files
  - `13.4.3` Memory management between JS and Wasm: linear memory buffer, typed arrays, passing strings, and zero-copy pointer views
  - `13.4.4` Web Workers and Wasm concurrency: multi-threaded Wasm execution using `SharedArrayBuffer` and WebAssembly threads
  - `13.4.5` High-performance client-side audio/image processing: building client-side image filters, encryption, and video manipulation
  - `13.4.6` Benchmarking Wasm vs native JavaScript: measuring $5\times - 10\times$ speedup on heavy cryptographic hashing and image convolution
- **Key Failure Modes & Edge Cases**: Excessive serializing and deserializing of large JSON strings across the JS-Wasm boundary, negating all compute speedup benefits.
- **Verification & Mastery Check**: Write a high-performance image blurring kernel in Rust, compile to Wasm, and execute in browser at 10x the speed of pure JS.
- **Project Application**: Track A Capstone: Client-side Wasm media processing engine.', '{"solution.py": "# Phase 13 // Lesson 13.4: Track A: WebAssembly (Wasm) Frontend Modules & Rust Compilation\n\ndef solve():\n    \"\"\"\n    Verification: Write a high-performance image blurring kernel in Rust, compile to Wasm, and execute in browser at 1\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.4", "subtopics_count": 6, "verification_criteria": "Write a high-performance image blurring kernel in Rust, compile to Wasm, and execute in browser at 10x the speed of pure JS.", "subtopics": ["13.4.1 Why WebAssembly on the frontend: near-native execution speed for computationally intensive client-side tasks", "13.4.2 Compiling Rust to WebAssembly: `wasm-pack`, `wasm-bindgen`, and generating TypeScript declaration files", "13.4.3 Memory management between JS and Wasm: linear memory buffer, typed arrays, passing strings, and zero-copy pointer views", "13.4.4 Web Workers and Wasm concurrency: multi-threaded Wasm execution using `SharedArrayBuffer` and WebAssembly threads", "13.4.5 High-performance client-side audio/image processing: building client-side image filters, encryption, and video manipulation", "13.4.6 Benchmarking Wasm vs native JavaScript: measuring $5\\times - 10\\times$ speedup on heavy cryptographic hashing and image convolution"]}'::jsonb, '["Explain how this implementation prevents: Excessive serializing and deserializing of large JSON strings across the JS-Wasm boundary, negating all compute speedup ", "How does Track A: WebAssembly (Wasm) Frontend Modules & Rust Compilation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-5', 'phase-13-lesson-05-track-a-global-multi-tenant-billing-tax-c', 'module-14', 5, 'Lesson 14.5: Track A: Global Multi-Tenant Billing, Tax Compliance & Invoicing', 'Prerequisites: Phase 5, Phase 6, Lesson 6.40', 'Prerequisites: Phase 5, Phase 6, Lesson 6.40 | Subtopics: 6 items', 'Systems project application', 360, 14, 3370.0, 250.0, '# Lesson 13.5: Track A: Global Multi-Tenant Billing, Tax Compliance & Invoicing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Phase 6, Lesson 6.40
- **Subtopics**:
  - `13.5.1` Architecting global SaaS monetization: multi-currency support, localized pricing, and payment method diversity (Cards, SEPA, iDEAL)
  - `13.5.2` Global tax compliance: VAT (Europe), GST (Australia/India), state sales tax (US); integrating Stripe Tax / Avalara calculation APIs
  - `13.5.3` Complex billing models: tiered per-seat pricing, metered usage-based billing, minimum commitments, and overage calculations
  - `13.5.4` Invoice generation engine: PDF generation, immutable legal invoice numbering, tax breakdown compliance, and payment receipts
  - `13.5.5` Dunning management: automated retry schedules on failed charges, smart card updater, and customer grace period enforcement
  - `13.5.6` Revenue recognition (ASC 606): deferred revenue schedules, recognizing subscription revenue ratably over service delivery periods
- **Key Failure Modes & Edge Cases**: Incorrect tax calculation on digital services triggering legal non-compliance penalties across European Union jurisdictions.
- **Verification & Mastery Check**: Implement a complete multi-currency SaaS billing engine with automated tax calculation, invoice generation, and dunning retries.
- **Project Application**: Track A Capstone: Enterprise global billing and tax engine.', '{"solution.py": "# Phase 13 // Lesson 13.5: Track A: Global Multi-Tenant Billing, Tax Compliance & Invoicing\n\ndef solve():\n    \"\"\"\n    Verification: Implement a complete multi-currency SaaS billing engine with automated tax calculation, invoice gene\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.5", "subtopics_count": 6, "verification_criteria": "Implement a complete multi-currency SaaS billing engine with automated tax calculation, invoice generation, and dunning retries.", "subtopics": ["13.5.1 Architecting global SaaS monetization: multi-currency support, localized pricing, and payment method diversity (Cards, SEPA, iDEAL)", "13.5.2 Global tax compliance: VAT (Europe), GST (Australia/India), state sales tax (US); integrating Stripe Tax / Avalara calculation APIs", "13.5.3 Complex billing models: tiered per-seat pricing, metered usage-based billing, minimum commitments, and overage calculations", "13.5.4 Invoice generation engine: PDF generation, immutable legal invoice numbering, tax breakdown compliance, and payment receipts", "13.5.5 Dunning management: automated retry schedules on failed charges, smart card updater, and customer grace period enforcement", "13.5.6 Revenue recognition (ASC 606): deferred revenue schedules, recognizing subscription revenue ratably over service delivery periods"]}'::jsonb, '["Explain how this implementation prevents: Incorrect tax calculation on digital services triggering legal non-compliance penalties across European Union jurisdicti", "How does Track A: Global Multi-Tenant Billing, Tax Compliance & Invoicing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-6', 'phase-13-lesson-06-track-b-distributed-deep-learning-foundat', 'module-14', 6, 'Lesson 14.6: Track B: Distributed Deep Learning Foundations: Data Parallelism & AllReduce', 'Prerequisites: Phase 9, Phase 11', 'Prerequisites: Phase 9, Phase 11 | Subtopics: 6 items', 'Systems project application', 360, 14, 3250.0, 300.0, '# Lesson 13.6: Track B: Distributed Deep Learning Foundations: Data Parallelism & AllReduce

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 11
- **Subtopics**:
  - `13.6.1` The scale limit of single-GPU training: models and batch sizes exceeding 80GB VRAM on modern NVIDIA H100 GPUs
  - `13.6.2` Distributed training paradigms: Data Parallelism (DP), Tensor Parallelism (TP), Pipeline Parallelism (PP), and Sequence Parallelism
  - `13.6.3` Distributed Data Parallel (DDP): replicating model across $N$ GPUs, scattering mini-batches, and synchronizing gradients
  - `13.6.4` Collective communication primitives (NCCL): Broadcast, Scatter, Gather, AllGather, Reduce, and Ring-AllReduce
  - `13.6.5` Ring-AllReduce mathematical efficiency: optimal bandwidth utilization independent of the number of participating GPUs ($2 \frac{N-1}{N} S$)
  - `13.6.6` Gradient bucketing in PyTorch DDP: overlapping gradient communication with backward computation to hide network latency
- **Key Failure Modes & Edge Cases**: Using PyTorch `DataParallel` instead of `DistributedDataParallel`, suffering from single-process GIL lock bottlenecks.
- **Verification & Mastery Check**: Implement a Ring-AllReduce gradient synchronization simulation in Python using socket message passing across 4 virtual processes.
- **Project Application**: Track B Capstone: Distributed training communication harness.', '{"solution.py": "# Phase 13 // Lesson 13.6: Track B: Distributed Deep Learning Foundations: Data Parallelism & AllReduce\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Ring-AllReduce gradient synchronization simulation in Python using socket message passin\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.6", "subtopics_count": 6, "verification_criteria": "Implement a Ring-AllReduce gradient synchronization simulation in Python using socket message passing across 4 virtual processes.", "subtopics": ["13.6.1 The scale limit of single-GPU training: models and batch sizes exceeding 80GB VRAM on modern NVIDIA H100 GPUs", "13.6.2 Distributed training paradigms: Data Parallelism (DP), Tensor Parallelism (TP), Pipeline Parallelism (PP), and Sequence Parallelism", "13.6.3 Distributed Data Parallel (DDP): replicating model across $N$ GPUs, scattering mini-batches, and synchronizing gradients", "13.6.4 Collective communication primitives (NCCL): Broadcast, Scatter, Gather, AllGather, Reduce, and Ring-AllReduce", "13.6.5 Ring-AllReduce mathematical efficiency: optimal bandwidth utilization independent of the number of participating GPUs ($2 \\frac{N-1}{N} S$)", "13.6.6 Gradient bucketing in PyTorch DDP: overlapping gradient communication with backward computation to hide network latency"]}'::jsonb, '["Explain how this implementation prevents: Using PyTorch `DataParallel` instead of `DistributedDataParallel`, suffering from single-process GIL lock bottlenecks.", "How does Track B: Distributed Deep Learning Foundations: Data Parallelism & AllReduce scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-7', 'phase-13-lesson-07-track-b-fully-sharded-data-parallel-fsdp-', 'module-14', 7, 'Lesson 14.7: Track B: Fully Sharded Data Parallel (FSDP) & DeepSpeed ZeRO-3', 'Prerequisites: Phase 9, Lesson 13.6', 'Prerequisites: Phase 9, Lesson 13.6 | Subtopics: 6 items', 'Systems project application', 360, 14, 3310.0, 350.0, '# Lesson 13.7: Track B: Fully Sharded Data Parallel (FSDP) & DeepSpeed ZeRO-3

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Lesson 13.6
- **Subtopics**:
  - `13.7.1` The memory footprint of deep learning: Model Parameters ($1\times$), Gradients ($1\times$), Optimizer States ($4-8\times$ for AdamW)
  - `13.7.2` ZeRO (Zero Redundancy Optimizer) memory stages: ZeRO-1 (Optimizer State Sharding), ZeRO-2 (Gradient Sharding), ZeRO-3 (Parameter Sharding)
  - `13.7.3` PyTorch Fully Sharded Data Parallel (FSDP): native ZeRO-3 implementation sharding parameters, gradients, and optimizer states across GPUs
  - `13.7.4` Forward and backward passes in FSDP: AllGathering parameters just-in-time for layer computation, discarding them immediately after
  - `13.7.5` CPU Offloading: swapping partitioned optimizer states and parameters to system host RAM during memory-constrained training
  - `13.7.6` Training a 70-Billion parameter LLM across an 8-GPU cluster: configuring FSDP wrapping policies and backward prefetching
- **Key Failure Modes & Edge Cases**: Failing to configure fine-grained module wrapping in FSDP, causing FSDP to AllGather the entire model at once and trigger OOM.
- **Verification & Mastery Check**: Configure and run PyTorch FSDP training of a multi-billion parameter transformer across multiple GPUs with parameter sharding.
- **Project Application**: Track B Capstone: Large-scale FSDP distributed training pipeline.', '{"solution.py": "# Phase 13 // Lesson 13.7: Track B: Fully Sharded Data Parallel (FSDP) & DeepSpeed ZeRO-3\n\ndef solve():\n    \"\"\"\n    Verification: Configure and run PyTorch FSDP training of a multi-billion parameter transformer across multiple GPU\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.7", "subtopics_count": 6, "verification_criteria": "Configure and run PyTorch FSDP training of a multi-billion parameter transformer across multiple GPUs with parameter sharding.", "subtopics": ["13.7.1 The memory footprint of deep learning: Model Parameters ($1\\times$), Gradients ($1\\times$), Optimizer States ($4-8\\times$ for AdamW)", "13.7.2 ZeRO (Zero Redundancy Optimizer) memory stages: ZeRO-1 (Optimizer State Sharding), ZeRO-2 (Gradient Sharding), ZeRO-3 (Parameter Sharding)", "13.7.3 PyTorch Fully Sharded Data Parallel (FSDP): native ZeRO-3 implementation sharding parameters, gradients, and optimizer states across GPUs", "13.7.4 Forward and backward passes in FSDP: AllGathering parameters just-in-time for layer computation, discarding them immediately after", "13.7.5 CPU Offloading: swapping partitioned optimizer states and parameters to system host RAM during memory-constrained training", "13.7.6 Training a 70-Billion parameter LLM across an 8-GPU cluster: configuring FSDP wrapping policies and backward prefetching"]}'::jsonb, '["Explain how this implementation prevents: Failing to configure fine-grained module wrapping in FSDP, causing FSDP to AllGather the entire model at once and trigge", "How does Track B: Fully Sharded Data Parallel (FSDP) & DeepSpeed ZeRO-3 scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-8', 'phase-13-lesson-08-track-b-high-throughput-llm-inference-opt', 'module-14', 8, 'Lesson 14.8: Track B: High-Throughput LLM Inference Optimization: TensorRT-LLM & vLLM', 'Prerequisites: Phase 10, Phase 11, Lesson 11.23', 'Prerequisites: Phase 10, Phase 11, Lesson 11.23 | Subtopics: 6 items', 'Systems project application', 360, 14, 3370.0, 400.0, '# Lesson 13.8: Track B: High-Throughput LLM Inference Optimization: TensorRT-LLM & vLLM

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 10, Phase 11, Lesson 11.23
- **Subtopics**:
  - `13.8.1` Inference serving challenges at enterprise scale: optimizing TTFT, token generation throughput, and minimizing GPU idle time
  - `13.8.2` PagedAttention internals: eliminating KV-cache memory fragmentation by allocating non-contiguous virtual memory blocks
  - `13.8.3` Chunked Prefill: interleaving heavy prefill prompt processing with lightweight token decode passes to eliminate latency spikes
  - `13.8.4` Speculative Decoding: utilizing small draft models to propose multiple candidate tokens verified in parallel by target model
  - `13.8.5` NVIDIA TensorRT-LLM architecture: custom C++ runtime, fused multi-head attention kernels, and FP8 tensor core acceleration
  - `13.8.6` Benchmarking production serving: stress-testing vLLM and TensorRT-LLM across varying prompt lengths and batch sizes
- **Key Failure Modes & Edge Cases**: Serving LLMs with un-paged KV caches, wasting 60% of GPU memory on internal fragmentation and dropping maximum concurrency.
- **Verification & Mastery Check**: Deploy and benchmark a TensorRT-LLM and vLLM server; measure 4x throughput improvement over standard HuggingFace pipeline.
- **Project Application**: Track B Capstone: High-throughput GPU inference cluster.', '{"solution.py": "# Phase 13 // Lesson 13.8: Track B: High-Throughput LLM Inference Optimization: TensorRT-LLM & vLLM\n\ndef solve():\n    \"\"\"\n    Verification: Deploy and benchmark a TensorRT-LLM and vLLM server; measure 4x throughput improvement over standard\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.8", "subtopics_count": 6, "verification_criteria": "Deploy and benchmark a TensorRT-LLM and vLLM server; measure 4x throughput improvement over standard HuggingFace pipeline.", "subtopics": ["13.8.1 Inference serving challenges at enterprise scale: optimizing TTFT, token generation throughput, and minimizing GPU idle time", "13.8.2 PagedAttention internals: eliminating KV-cache memory fragmentation by allocating non-contiguous virtual memory blocks", "13.8.3 Chunked Prefill: interleaving heavy prefill prompt processing with lightweight token decode passes to eliminate latency spikes", "13.8.4 Speculative Decoding: utilizing small draft models to propose multiple candidate tokens verified in parallel by target model", "13.8.5 NVIDIA TensorRT-LLM architecture: custom C++ runtime, fused multi-head attention kernels, and FP8 tensor core acceleration", "13.8.6 Benchmarking production serving: stress-testing vLLM and TensorRT-LLM across varying prompt lengths and batch sizes"]}'::jsonb, '["Explain how this implementation prevents: Serving LLMs with un-paged KV caches, wasting 60% of GPU memory on internal fragmentation and dropping maximum concurren", "How does Track B: High-Throughput LLM Inference Optimization: TensorRT-LLM & vLLM scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-9', 'phase-13-lesson-09-track-b-distributed-orchestration-with-ra', 'module-14', 9, 'Lesson 14.9: Track B: Distributed Orchestration with Ray: Clusters, Actors & Workflows', 'Prerequisites: Phase 7, Lesson 13.6', 'Prerequisites: Phase 7, Lesson 13.6 | Subtopics: 6 items', 'Systems project application', 360, 14, 3250.0, 450.0, '# Lesson 13.9: Track B: Distributed Orchestration with Ray: Clusters, Actors & Workflows

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 13.6
- **Subtopics**:
  - `13.9.1` Ray architecture: universal framework for scaling AI and Python applications (Ray Core, Ray Train, Ray Serve, Ray Data)
  - `13.9.2` Ray Core primitives: Tasks (stateless distributed functions) and Actors (stateful distributed classes with managed lifecycle)
  - `13.9.3` Ray Cluster architecture: Head node (Global Control Store - GCS, scheduler), Worker nodes, and autoscaling cloud node pools
  - `13.9.4` Distributed data processing with Ray Data: streaming multi-terabyte datasets across GPU memory with zero-copy Plasma object store
  - `13.9.5` Distributed hyperparameter tuning with Ray Tune: population-based training, Bayesian optimization, and early stopping schedulers
  - `13.9.6` Fault tolerance in Ray: actor health checks, object lineage reconstruction, and automatic task retry on worker node preemption
- **Key Failure Modes & Edge Cases**: Storing large data objects inside task arguments rather than putting them into the Ray Plasma object store, causing network flooding.
- **Verification & Mastery Check**: Build a distributed data processing and model training pipeline using Ray Core and Ray Train across a multi-node cluster.
- **Project Application**: Track B Capstone: Distributed Ray cluster workflow engine.', '{"solution.py": "# Phase 13 // Lesson 13.9: Track B: Distributed Orchestration with Ray: Clusters, Actors & Workflows\n\ndef solve():\n    \"\"\"\n    Verification: Build a distributed data processing and model training pipeline using Ray Core and Ray Train across \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.9", "subtopics_count": 6, "verification_criteria": "Build a distributed data processing and model training pipeline using Ray Core and Ray Train across a multi-node cluster.", "subtopics": ["13.9.1 Ray architecture: universal framework for scaling AI and Python applications (Ray Core, Ray Train, Ray Serve, Ray Data)", "13.9.2 Ray Core primitives: Tasks (stateless distributed functions) and Actors (stateful distributed classes with managed lifecycle)", "13.9.3 Ray Cluster architecture: Head node (Global Control Store - GCS, scheduler), Worker nodes, and autoscaling cloud node pools", "13.9.4 Distributed data processing with Ray Data: streaming multi-terabyte datasets across GPU memory with zero-copy Plasma object store", "13.9.5 Distributed hyperparameter tuning with Ray Tune: population-based training, Bayesian optimization, and early stopping schedulers", "13.9.6 Fault tolerance in Ray: actor health checks, object lineage reconstruction, and automatic task retry on worker node preemption"]}'::jsonb, '["Explain how this implementation prevents: Storing large data objects inside task arguments rather than putting them into the Ray Plasma object store, causing netw", "How does Track B: Distributed Orchestration with Ray: Clusters, Actors & Workflows scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-10', 'phase-13-lesson-10-track-b-feature-stores-real-time-ml-pipel', 'module-14', 10, 'Lesson 14.10: Track B: Feature Stores & Real-Time ML Pipelines: Feast & Hopsworks', 'Prerequisites: Phase 4, Phase 7, Phase 11', 'Prerequisites: Phase 4, Phase 7, Phase 11 | Subtopics: 6 items', 'Systems project application', 360, 14, 3310.0, 500.0, '# Lesson 13.10: Track B: Feature Stores & Real-Time ML Pipelines: Feast & Hopsworks

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7, Phase 11
- **Subtopics**:
  - `13.10.1` The training-serving skew crisis: model features computed differently during offline training than during online production inference
  - `13.10.2` Feature Store architecture: unifying feature definitions across batch training pipelines and low-latency real-time inference APIs
  - `13.10.3` Offline Store vs Online Store: BigQuery/Snowflake/Parquet for historical batch point-in-time joins vs Redis/DynamoDB for <5ms lookups
  - `13.10.4` Point-in-Time Correctness (Time Travel): generating training datasets without data leakage from future timestamps
  - `13.10.5` Feature definitions in Feast: Entity, FeatureView, Source, and automated feature materialization pipelines from offline to online stores
  - `13.10.6` Feature monitoring: tracking feature drift, missing value rates, and schema violations in production feature serving
- **Key Failure Modes & Edge Cases**: Data leakage during training dataset generation by joining features from future dates, producing artificially inflated model accuracy.
- **Verification & Mastery Check**: Deploy Feast feature store; register batch and streaming feature views, and execute point-in-time joins for model training.
- **Project Application**: Track B Capstone: Production Feast feature store deployment.', '{"solution.py": "# Phase 13 // Lesson 13.10: Track B: Feature Stores & Real-Time ML Pipelines: Feast & Hopsworks\n\ndef solve():\n    \"\"\"\n    Verification: Deploy Feast feature store; register batch and streaming feature views, and execute point-in-time jo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.10", "subtopics_count": 6, "verification_criteria": "Deploy Feast feature store; register batch and streaming feature views, and execute point-in-time joins for model training.", "subtopics": ["13.10.1 The training-serving skew crisis: model features computed differently during offline training than during online production inference", "13.10.2 Feature Store architecture: unifying feature definitions across batch training pipelines and low-latency real-time inference APIs", "13.10.3 Offline Store vs Online Store: BigQuery/Snowflake/Parquet for historical batch point-in-time joins vs Redis/DynamoDB for <5ms lookups", "13.10.4 Point-in-Time Correctness (Time Travel): generating training datasets without data leakage from future timestamps", "13.10.5 Feature definitions in Feast: Entity, FeatureView, Source, and automated feature materialization pipelines from offline to online stores", "13.10.6 Feature monitoring: tracking feature drift, missing value rates, and schema violations in production feature serving"]}'::jsonb, '["Explain how this implementation prevents: Data leakage during training dataset generation by joining features from future dates, producing artificially inflated m", "How does Track B: Feature Stores & Real-Time ML Pipelines: Feast & Hopsworks scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-11', 'phase-13-lesson-11-track-c-ebpf-powered-security-observabili', 'module-14', 11, 'Lesson 14.11: Track C: eBPF-Powered Security Observability: Cilium & Tetragon', 'Prerequisites: Phase 0, Phase 7', 'Prerequisites: Phase 0, Phase 7 | Subtopics: 6 items', 'Systems project application', 360, 14, 3370.0, 550.0, '# Lesson 13.11: Track C: eBPF-Powered Security Observability: Cilium & Tetragon

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 7
- **Subtopics**:
  - `13.11.1` Extended Berkeley Packet Filter (eBPF) architecture: executing verified bytecode sandboxed directly inside the Linux kernel
  - `13.11.2` Why eBPF supersedes traditional user-space monitoring: zero context switches, kernel-level visibility, tamper-proof security
  - `13.11.3` Tetragon runtime security: hook points in kernel syscalls (`sys_execve`, `sys_open`, `sys_connect`), kprobes, and tracepoints
  - `13.11.4` Real-time threat detection: detecting privilege escalation, shell spawning inside containers, and namespace escapes instantly
  - `13.11.5` Cilium eBPF network security: Layer 3/4/7 network policies enforced at socket layer without iptables overhead
  - `13.11.6` Automated security remediation: killing malicious processes (`sigkill`) directly from the kernel before unauthorized actions complete
- **Key Failure Modes & Edge Cases**: Deploying user-space audit daemons that can be killed or disabled by attackers who gain root privileges in container namespaces.
- **Verification & Mastery Check**: Deploy Cilium and Tetragon on a Kubernetes cluster; write an eBPF security policy that detects and kills unauthorized shell execution.
- **Project Application**: Track C Capstone: Kernel-level eBPF security enforcement engine.', '{"solution.py": "# Phase 13 // Lesson 13.11: Track C: eBPF-Powered Security Observability: Cilium & Tetragon\n\ndef solve():\n    \"\"\"\n    Verification: Deploy Cilium and Tetragon on a Kubernetes cluster; write an eBPF security policy that detects and k\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.11", "subtopics_count": 6, "verification_criteria": "Deploy Cilium and Tetragon on a Kubernetes cluster; write an eBPF security policy that detects and kills unauthorized shell execution.", "subtopics": ["13.11.1 Extended Berkeley Packet Filter (eBPF) architecture: executing verified bytecode sandboxed directly inside the Linux kernel", "13.11.2 Why eBPF supersedes traditional user-space monitoring: zero context switches, kernel-level visibility, tamper-proof security", "13.11.3 Tetragon runtime security: hook points in kernel syscalls (`sys_execve`, `sys_open`, `sys_connect`), kprobes, and tracepoints", "13.11.4 Real-time threat detection: detecting privilege escalation, shell spawning inside containers, and namespace escapes instantly", "13.11.5 Cilium eBPF network security: Layer 3/4/7 network policies enforced at socket layer without iptables overhead", "13.11.6 Automated security remediation: killing malicious processes (`sigkill`) directly from the kernel before unauthorized actions complete"]}'::jsonb, '["Explain how this implementation prevents: Deploying user-space audit daemons that can be killed or disabled by attackers who gain root privileges in container nam", "How does Track C: eBPF-Powered Security Observability: Cilium & Tetragon scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-12', 'phase-13-lesson-12-track-c-zero-trust-architecture-mutual-tl', 'module-14', 12, 'Lesson 14.12: Track C: Zero-Trust Architecture: Mutual TLS & SPIFFE/SPIRE', 'Prerequisites: Phase 5, Phase 7', 'Prerequisites: Phase 5, Phase 7 | Subtopics: 6 items', 'Systems project application', 360, 14, 3250.0, 600.0, '# Lesson 13.12: Track C: Zero-Trust Architecture: Mutual TLS & SPIFFE/SPIRE

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Phase 7
- **Subtopics**:
  - `13.12.1` Zero-Trust principles: assume breach, never trust, verify explicitly, enforce least privilege access across all services
  - `13.12.2` Secure Production Identity Framework for Everyone (SPIFFE): standardized cryptographic identity specification for workloads
  - `13.12.3` SPIRE (SPIFFE Runtime Environment): SPIRE Server (CA, registration APIs) and SPIRE Agent (workload attestation, SVID issuance)
  - `13.12.4` Workload Attestation: verifying container image, UID, namespace, and binary hash before granting cryptographic identities
  - `13.12.5` SPIFFE Verifiable Identity Document (SVID): short-lived X.509 certificates rotated automatically every hour
  - `13.12.6` Enforcing end-to-end mutual TLS (mTLS): configuring Envoy sidecars with SPIRE SVIDs for automatic peer authentication
- **Key Failure Modes & Edge Cases**: Relying on long-lived static API tokens or network IP whitelists for microservice authentication in dynamic cloud environments.
- **Verification & Mastery Check**: Deploy SPIRE on Kubernetes; configure workload attestation and verify automated short-lived mTLS communication between microservices.
- **Project Application**: Track C Capstone: SPIFFE/SPIRE Zero-Trust identity infrastructure.', '{"solution.py": "# Phase 13 // Lesson 13.12: Track C: Zero-Trust Architecture: Mutual TLS & SPIFFE/SPIRE\n\ndef solve():\n    \"\"\"\n    Verification: Deploy SPIRE on Kubernetes; configure workload attestation and verify automated short-lived mTLS com\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.12", "subtopics_count": 6, "verification_criteria": "Deploy SPIRE on Kubernetes; configure workload attestation and verify automated short-lived mTLS communication between microservices.", "subtopics": ["13.12.1 Zero-Trust principles: assume breach, never trust, verify explicitly, enforce least privilege access across all services", "13.12.2 Secure Production Identity Framework for Everyone (SPIFFE): standardized cryptographic identity specification for workloads", "13.12.3 SPIRE (SPIFFE Runtime Environment): SPIRE Server (CA, registration APIs) and SPIRE Agent (workload attestation, SVID issuance)", "13.12.4 Workload Attestation: verifying container image, UID, namespace, and binary hash before granting cryptographic identities", "13.12.5 SPIFFE Verifiable Identity Document (SVID): short-lived X.509 certificates rotated automatically every hour", "13.12.6 Enforcing end-to-end mutual TLS (mTLS): configuring Envoy sidecars with SPIRE SVIDs for automatic peer authentication"]}'::jsonb, '["Explain how this implementation prevents: Relying on long-lived static API tokens or network IP whitelists for microservice authentication in dynamic cloud enviro", "How does Track C: Zero-Trust Architecture: Mutual TLS & SPIFFE/SPIRE scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-13', 'phase-13-lesson-13-track-c-enterprise-key-management-envelop', 'module-14', 13, 'Lesson 14.13: Track C: Enterprise Key Management, Envelope Encryption & HSMs', 'Prerequisites: Phase 5, Phase 7', 'Prerequisites: Phase 5, Phase 7 | Subtopics: 6 items', 'Systems project application', 360, 14, 3310.0, 650.0, '# Lesson 13.13: Track C: Enterprise Key Management, Envelope Encryption & HSMs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Phase 7
- **Subtopics**:
  - `13.13.1` Cryptographic security at scale: protecting multi-tenant data at rest using Hardware Security Modules (HSMs) and KMS
  - `13.13.2` Envelope Encryption mechanics: encrypting plaintext with unique Data Encryption Key (DEK); encrypting DEK with Key Encryption Key (KEK)
  - `13.13.3` Why envelope encryption is mandatory: avoiding sending multi-gigabyte data payloads to central KMS over the network
  - `13.13.4` Cloud KMS integration: Google Cloud KMS / AWS KMS, Customer-Managed Encryption Keys (CMEK), and key rotation policies
  - `13.13.5` Cryptographic erasure (Crypto-Shredding): fulfilling GDPR right-to-be-forgotten by destroying tenant KEKs in HSMs instantly
  - `13.13.6` FIPS 140-2 Level 3 HSM compliance: hardware tamper-resistance, zero extraction of master private keys, and audit logging
- **Key Failure Modes & Edge Cases**: Storing unencrypted Data Encryption Keys (DEKs) in database columns alongside encrypted data payloads.
- **Verification & Mastery Check**: Implement an Envelope Encryption pipeline in Python using Cloud KMS with automated DEK generation and Crypto-Shredding verification.
- **Project Application**: Track C Capstone: Enterprise envelope encryption and KMS pipeline.', '{"solution.py": "# Phase 13 // Lesson 13.13: Track C: Enterprise Key Management, Envelope Encryption & HSMs\n\ndef solve():\n    \"\"\"\n    Verification: Implement an Envelope Encryption pipeline in Python using Cloud KMS with automated DEK generation an\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.13", "subtopics_count": 6, "verification_criteria": "Implement an Envelope Encryption pipeline in Python using Cloud KMS with automated DEK generation and Crypto-Shredding verification.", "subtopics": ["13.13.1 Cryptographic security at scale: protecting multi-tenant data at rest using Hardware Security Modules (HSMs) and KMS", "13.13.2 Envelope Encryption mechanics: encrypting plaintext with unique Data Encryption Key (DEK); encrypting DEK with Key Encryption Key (KEK)", "13.13.3 Why envelope encryption is mandatory: avoiding sending multi-gigabyte data payloads to central KMS over the network", "13.13.4 Cloud KMS integration: Google Cloud KMS / AWS KMS, Customer-Managed Encryption Keys (CMEK), and key rotation policies", "13.13.5 Cryptographic erasure (Crypto-Shredding): fulfilling GDPR right-to-be-forgotten by destroying tenant KEKs in HSMs instantly", "13.13.6 FIPS 140-2 Level 3 HSM compliance: hardware tamper-resistance, zero extraction of master private keys, and audit logging"]}'::jsonb, '["Explain how this implementation prevents: Storing unencrypted Data Encryption Keys (DEKs) in database columns alongside encrypted data payloads.", "How does Track C: Enterprise Key Management, Envelope Encryption & HSMs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-14', 'phase-13-lesson-14-track-c-devsecops-ci-cd-automation-static', 'module-14', 14, 'Lesson 14.14: Track C: DevSecOps CI/CD Automation: Static & Dynamic Security Scanning', 'Prerequisites: Phase 5, Phase 7', 'Prerequisites: Phase 5, Phase 7 | Subtopics: 6 items', 'Systems project application', 360, 14, 3370.0, 700.0, '# Lesson 13.14: Track C: DevSecOps CI/CD Automation: Static & Dynamic Security Scanning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Phase 7
- **Subtopics**:
  - `13.14.1` DevSecOps philosophy: shifting security left into developer workflows and automated CI/CD deployment pipelines
  - `13.14.2` Static Application Security Testing (SAST): AST-based vulnerability scanning with Semgrep, custom security rules, and CVE detection
  - `13.14.3` Software Bill of Materials (SBOM): generating standardized CycloneDX / SPDX component inventories in CI builds
  - `13.14.4` Dependency vulnerability management: automated vulnerability scanning with Snyk / Trivy, tracking CVSS scores and remediation paths
  - `13.14.5` Dynamic Application Security Testing (DAST): automated vulnerability probing of running staging environments with OWASP ZAP
  - `13.14.6` Policy as Code with Open Policy Agent (OPA) / Conftest: blocking Kubernetes deployments violating security benchmarks (e.g. root containers)
- **Key Failure Modes & Edge Cases**: Failing to block CI builds on critical CVSS 10.0 vulnerabilities, allowing known remote code execution bugs into production.
- **Verification & Mastery Check**: Build a GitHub Actions DevSecOps pipeline with Semgrep SAST, Trivy SBOM generation, and OPA Conftest deployment gate enforcement.
- **Project Application**: Track C Capstone: Automated DevSecOps security pipeline.', '{"solution.py": "# Phase 13 // Lesson 13.14: Track C: DevSecOps CI/CD Automation: Static & Dynamic Security Scanning\n\ndef solve():\n    \"\"\"\n    Verification: Build a GitHub Actions DevSecOps pipeline with Semgrep SAST, Trivy SBOM generation, and OPA Conftest\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.14", "subtopics_count": 6, "verification_criteria": "Build a GitHub Actions DevSecOps pipeline with Semgrep SAST, Trivy SBOM generation, and OPA Conftest deployment gate enforcement.", "subtopics": ["13.14.1 DevSecOps philosophy: shifting security left into developer workflows and automated CI/CD deployment pipelines", "13.14.2 Static Application Security Testing (SAST): AST-based vulnerability scanning with Semgrep, custom security rules, and CVE detection", "13.14.3 Software Bill of Materials (SBOM): generating standardized CycloneDX / SPDX component inventories in CI builds", "13.14.4 Dependency vulnerability management: automated vulnerability scanning with Snyk / Trivy, tracking CVSS scores and remediation paths", "13.14.5 Dynamic Application Security Testing (DAST): automated vulnerability probing of running staging environments with OWASP ZAP", "13.14.6 Policy as Code with Open Policy Agent (OPA) / Conftest: blocking Kubernetes deployments violating security benchmarks (e.g. root containers)"]}'::jsonb, '["Explain how this implementation prevents: Failing to block CI builds on critical CVSS 10.0 vulnerabilities, allowing known remote code execution bugs into product", "How does Track C: DevSecOps CI/CD Automation: Static & Dynamic Security Scanning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-13-15', 'phase-13-lesson-15-track-c-red-teaming-penetration-testing-v', 'module-14', 15, 'Lesson 14.15: Track C: Red-Teaming, Penetration Testing & Vulnerability Disclosure', 'Prerequisites: Phase 5, Phase 10', 'Prerequisites: Phase 5, Phase 10 | Subtopics: 6 items', 'Systems project application', 360, 14, 3250.0, 750.0, '# Lesson 13.15: Track C: Red-Teaming, Penetration Testing & Vulnerability Disclosure

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Phase 10
- **Subtopics**:
  - `13.15.1` Red-Teaming methodology: simulating real-world sophisticated adversary attacks across systems, infrastructure, and personnel
  - `13.15.2` Penetration testing phases: Reconnaissance, Vulnerability Scanning, Exploitation, Privilege Escalation, Lateral Movement, Exfiltration
  - `13.15.3` Web application exploitation: chaining SSRF, deserialization bugs, and SQL injection into remote shell access on backend servers
  - `13.15.4` Cloud infrastructure attacks: exploiting misconfigured IAM roles, metadata server access (SSRF to `169.254.169.254`), and bucket permissions
  - `13.15.5` Vulnerability disclosure protocols: coordinated vulnerability disclosure (CVD), bug bounty program management, and CVE assignment
  - `13.15.6` Authoring executive security reports: translating technical vulnerabilities into business risk impacts and remediation roadmaps
- **Key Failure Modes & Edge Cases**: Failing to protect the cloud metadata server (IMDSv2), allowing an SSRF vulnerability to dump cloud IAM credentials.
- **Verification & Mastery Check**: Execute a comprehensive penetration test on a mock cloud architecture; document findings and author an executive remediation report.
- **Project Application**: Track C Capstone: Red-team penetration audit and defense report.', '{"solution.py": "# Phase 13 // Lesson 13.15: Track C: Red-Teaming, Penetration Testing & Vulnerability Disclosure\n\ndef solve():\n    \"\"\"\n    Verification: Execute a comprehensive penetration test on a mock cloud architecture; document findings and author \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "13.15", "subtopics_count": 6, "verification_criteria": "Execute a comprehensive penetration test on a mock cloud architecture; document findings and author an executive remediation report.", "subtopics": ["13.15.1 Red-Teaming methodology: simulating real-world sophisticated adversary attacks across systems, infrastructure, and personnel", "13.15.2 Penetration testing phases: Reconnaissance, Vulnerability Scanning, Exploitation, Privilege Escalation, Lateral Movement, Exfiltration", "13.15.3 Web application exploitation: chaining SSRF, deserialization bugs, and SQL injection into remote shell access on backend servers", "13.15.4 Cloud infrastructure attacks: exploiting misconfigured IAM roles, metadata server access (SSRF to `169.254.169.254`), and bucket permissions", "13.15.5 Vulnerability disclosure protocols: coordinated vulnerability disclosure (CVD), bug bounty program management, and CVE assignment", "13.15.6 Authoring executive security reports: translating technical vulnerabilities into business risk impacts and remediation roadmaps"]}'::jsonb, '["Explain how this implementation prevents: Failing to protect the cloud metadata server (IMDSv2), allowing an SSRF vulnerability to dump cloud IAM credentials.", "How does Track C: Red-Teaming, Penetration Testing & Vulnerability Disclosure scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
