INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-10-16', 'phase-10-lesson-16-metadata-enrichment-temporal-tags-entity-', 'module-11', 16, 'Lesson 11.16: Metadata Enrichment: Temporal Tags, Entity Extraction & Hierarchy', 'Prerequisites: Lesson 10.3, Lesson 10.14', 'Prerequisites: Lesson 10.3, Lesson 10.14 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 800.0, '# Lesson 10.16: Metadata Enrichment: Temporal Tags, Entity Extraction & Hierarchy

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.3, Lesson 10.14
- **Subtopics**:
  - `10.16.1` Why pure vector similarity is insufficient: handling queries like ''What was our Q3 2024 revenue for customer X?''
  - `10.16.2` Automatic metadata extraction via small LLMs: extracting document dates, author, organization, product category, and document type
  - `10.16.3` Named Entity Recognition (NER): extracting people, organizations, locations, and unique identifier codes (e.g. ticket IDs)
  - `10.16.4` Document hierarchy tagging: injecting breadcrumb trails (e.g. `Document > Section 2 > Subsection A`) directly into chunk text
  - `10.16.5` Hypothetical question generation: using an LLM to generate 3 prospective user questions that each chunk answers, embedded alongside chunk
  - `10.16.6` Storing enriched metadata: JSONB payloads in pgvector or structured metadata payloads in dedicated vector stores
- **Key Failure Modes & Edge Cases**: Omitting temporal metadata, causing RAG to retrieve outdated 2021 corporate policies instead of updated 2024 policies for current questions.
- **Verification & Mastery Check**: Implement an automated metadata enrichment pipeline extracting dates, entities, and hypothetical questions for every ingested chunk.
- **Project Application**: DocuMind: Automated chunk metadata enrichment pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.16: Metadata Enrichment: Temporal Tags, Entity Extraction & Hierarchy\n\ndef solve():\n    \"\"\"\n    Verification: Implement an automated metadata enrichment pipeline extracting dates, entities, and hypothetical que\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.16", "subtopics_count": 6, "verification_criteria": "Implement an automated metadata enrichment pipeline extracting dates, entities, and hypothetical questions for every ingested chunk.", "subtopics": ["10.16.1 Why pure vector similarity is insufficient: handling queries like ''What was our Q3 2024 revenue for customer X?''", "10.16.2 Automatic metadata extraction via small LLMs: extracting document dates, author, organization, product category, and document type", "10.16.3 Named Entity Recognition (NER): extracting people, organizations, locations, and unique identifier codes (e.g. ticket IDs)", "10.16.4 Document hierarchy tagging: injecting breadcrumb trails (e.g. `Document > Section 2 > Subsection A`) directly into chunk text", "10.16.5 Hypothetical question generation: using an LLM to generate 3 prospective user questions that each chunk answers, embedded alongside chunk", "10.16.6 Storing enriched metadata: JSONB payloads in pgvector or structured metadata payloads in dedicated vector stores"]}'::jsonb, '["Explain how this implementation prevents: Omitting temporal metadata, causing RAG to retrieve outdated 2021 corporate policies instead of updated 2024 policies fo", "How does Metadata Enrichment: Temporal Tags, Entity Extraction & Hierarchy scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-17', 'phase-10-lesson-17-embedding-model-selection-mteb-leaderboar', 'module-11', 17, 'Lesson 11.17: Embedding Model Selection: MTEB Leaderboard, Bi-Encoders & Domain Tuning', 'Prerequisites: Lesson 10.6, Phase 9', 'Prerequisites: Lesson 10.6, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 850.0, '# Lesson 10.17: Embedding Model Selection: MTEB Leaderboard, Bi-Encoders & Domain Tuning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.6, Phase 9
- **Subtopics**:
  - `10.17.1` Massive Text Embedding Benchmark (MTEB): evaluating models across Retrieval, Reranking, Clustering, Classification, and STS tasks
  - `10.17.2` Bi-Encoder architecture: Siamese networks encoding query and document independently into fixed-size vectors ($u = f(q), v = f(d)$)
  - `10.17.3` Commercial vs Open-Source embedding models: OpenAI `text-embedding-3-large`, Cohere `embed-v3`, BAAI `bge-large-en-v1.5`, Voyage AI
  - `10.17.4` Asymmetric retrieval tasks: why some models require instruction prefixes (e.g. `query: ` vs `passage: `) for optimal scoring
  - `10.17.5` Domain-specific embeddings: why general-purpose embeddings degrade on medical, legal, or proprietary codebases
  - `10.17.6` Matryoshka Representation Learning (MRL): models trained to produce embeddings that can be truncated to 256 or 512 dimensions without loss
- **Key Failure Modes & Edge Cases**: Forgetting the required query prefix (`Represent this sentence for searching relevant passages:`) on models like E5, dropping retrieval accuracy by 25%.
- **Verification & Mastery Check**: Evaluate 3 open-source embedding models from MTEB on a domain-specific dataset; benchmark recall@5 and compute latency.
- **Project Application**: DocuMind: Multi-model embedding evaluation harness.', '{"solution.py": "# Phase 10 // Lesson 10.17: Embedding Model Selection: MTEB Leaderboard, Bi-Encoders & Domain Tuning\n\ndef solve():\n    \"\"\"\n    Verification: Evaluate 3 open-source embedding models from MTEB on a domain-specific dataset; benchmark recall@5 a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.17", "subtopics_count": 6, "verification_criteria": "Evaluate 3 open-source embedding models from MTEB on a domain-specific dataset; benchmark recall@5 and compute latency.", "subtopics": ["10.17.1 Massive Text Embedding Benchmark (MTEB): evaluating models across Retrieval, Reranking, Clustering, Classification, and STS tasks", "10.17.2 Bi-Encoder architecture: Siamese networks encoding query and document independently into fixed-size vectors ($u = f(q), v = f(d)$)", "10.17.3 Commercial vs Open-Source embedding models: OpenAI `text-embedding-3-large`, Cohere `embed-v3`, BAAI `bge-large-en-v1.5`, Voyage AI", "10.17.4 Asymmetric retrieval tasks: why some models require instruction prefixes (e.g. `query: ` vs `passage: `) for optimal scoring", "10.17.5 Domain-specific embeddings: why general-purpose embeddings degrade on medical, legal, or proprietary codebases", "10.17.6 Matryoshka Representation Learning (MRL): models trained to produce embeddings that can be truncated to 256 or 512 dimensions without loss"]}'::jsonb, '["Explain how this implementation prevents: Forgetting the required query prefix (`Represent this sentence for searching relevant passages:`) on models like E5, dro", "How does Embedding Model Selection: MTEB Leaderboard, Bi-Encoders & Domain Tuning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-18', 'phase-10-lesson-18-ingestion-pipeline-orchestration-idempote', 'module-11', 18, 'Lesson 11.18: Ingestion Pipeline Orchestration: Idempotency, Change Data Capture & Deduplication', 'Prerequisites: Phase 4, Phase 7, Lesson 10.14', 'Prerequisites: Phase 4, Phase 7, Lesson 10.14 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 900.0, '# Lesson 10.18: Ingestion Pipeline Orchestration: Idempotency, Change Data Capture & Deduplication

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7, Lesson 10.14
- **Subtopics**:
  - `10.18.1` Building production-grade ingestion pipelines: handling millions of documents continuously without data corruption
  - `10.18.2` Idempotency in vector ingestion: content-based hashing (SHA-256 of raw chunk) as deterministic vector primary keys
  - `10.18.3` Change Data Capture (CDC): detecting document modifications, deletions, and additions via database triggers or Kafka streams
  - `10.18.4` Incremental re-indexing: updating only modified chunks while pruning deleted document vectors to prevent stale ghost retrievals
  - `10.18.5` Near-duplicate document detection: MinHash and Locality-Sensitive Hashing (LSH) detecting duplicate documents before ingestion
  - `10.18.6` Pipeline failure resilience: dead-letter queues for unparseable documents, retry policies, and progress checkpoints in Redis
- **Key Failure Modes & Edge Cases**: Re-running an ingestion job re-inserting all documents with random UUIDs, duplicating millions of vectors and doubling cloud costs.
- **Verification & Mastery Check**: Build an idempotent document ingestion pipeline backed by SHA-256 chunk hashing that gracefully skips unchanged documents upon re-run.
- **Project Application**: DocuMind: Enterprise idempotent ingestion worker fleet.', '{"solution.py": "# Phase 10 // Lesson 10.18: Ingestion Pipeline Orchestration: Idempotency, Change Data Capture & Deduplication\n\ndef solve():\n    \"\"\"\n    Verification: Build an idempotent document ingestion pipeline backed by SHA-256 chunk hashing that gracefully skip\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.18", "subtopics_count": 6, "verification_criteria": "Build an idempotent document ingestion pipeline backed by SHA-256 chunk hashing that gracefully skips unchanged documents upon re-run.", "subtopics": ["10.18.1 Building production-grade ingestion pipelines: handling millions of documents continuously without data corruption", "10.18.2 Idempotency in vector ingestion: content-based hashing (SHA-256 of raw chunk) as deterministic vector primary keys", "10.18.3 Change Data Capture (CDC): detecting document modifications, deletions, and additions via database triggers or Kafka streams", "10.18.4 Incremental re-indexing: updating only modified chunks while pruning deleted document vectors to prevent stale ghost retrievals", "10.18.5 Near-duplicate document detection: MinHash and Locality-Sensitive Hashing (LSH) detecting duplicate documents before ingestion", "10.18.6 Pipeline failure resilience: dead-letter queues for unparseable documents, retry policies, and progress checkpoints in Redis"]}'::jsonb, '["Explain how this implementation prevents: Re-running an ingestion job re-inserting all documents with random UUIDs, duplicating millions of vectors and doubling c", "How does Ingestion Pipeline Orchestration: Idempotency, Change Data Capture & Deduplication scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-19', 'phase-10-lesson-19-hybrid-retrieval-architectures-dense-vect', 'module-11', 19, 'Lesson 11.19: Hybrid Retrieval Architectures: Dense Vector Search + Sparse Lexical Search', 'Prerequisites: Lesson 10.6, Lesson 10.10', 'Prerequisites: Lesson 10.6, Lesson 10.10 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 950.0, '# Lesson 10.19: Hybrid Retrieval Architectures: Dense Vector Search + Sparse Lexical Search

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.6, Lesson 10.10
- **Subtopics**:
  - `10.19.1` The fundamental limitations of dense vector search: struggle with exact keyword matches, SKU numbers, product codes, and acronyms
  - `10.19.2` The fundamental limitations of lexical search: vocabulary mismatch problem, inability to understand synonyms, paraphrases, and context
  - `10.19.3` Hybrid search paradigm: executing dense semantic vector search and sparse lexical keyword search in parallel
  - `10.19.4` Sparse representation models: BM25 traditional lexical scoring vs learned sparse representations (SPLADE, BM42)
  - `10.19.5` Combining dense and sparse results: score normalization, linear weighted score interpolation, and rank-based fusion
  - `10.19.6` Architecture of hybrid query engines: orchestrating parallel queries against pgvector and PostgreSQL full-text search (`tsvector`)
- **Key Failure Modes & Edge Cases**: Relying solely on vector search for product ID queries (`XJ-9000`), returning semantically similar models instead of the exact match.
- **Verification & Mastery Check**: Implement a dual-stream hybrid search engine executing dense vector search and sparse lexical search against PostgreSQL in parallel.
- **Project Application**: DocuMind: Hybrid retrieval orchestration layer.', '{"solution.py": "# Phase 10 // Lesson 10.19: Hybrid Retrieval Architectures: Dense Vector Search + Sparse Lexical Search\n\ndef solve():\n    \"\"\"\n    Verification: Implement a dual-stream hybrid search engine executing dense vector search and sparse lexical search\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.19", "subtopics_count": 6, "verification_criteria": "Implement a dual-stream hybrid search engine executing dense vector search and sparse lexical search against PostgreSQL in parallel.", "subtopics": ["10.19.1 The fundamental limitations of dense vector search: struggle with exact keyword matches, SKU numbers, product codes, and acronyms", "10.19.2 The fundamental limitations of lexical search: vocabulary mismatch problem, inability to understand synonyms, paraphrases, and context", "10.19.3 Hybrid search paradigm: executing dense semantic vector search and sparse lexical keyword search in parallel", "10.19.4 Sparse representation models: BM25 traditional lexical scoring vs learned sparse representations (SPLADE, BM42)", "10.19.5 Combining dense and sparse results: score normalization, linear weighted score interpolation, and rank-based fusion", "10.19.6 Architecture of hybrid query engines: orchestrating parallel queries against pgvector and PostgreSQL full-text search (`tsvector`)"]}'::jsonb, '["Explain how this implementation prevents: Relying solely on vector search for product ID queries (`XJ-9000`), returning semantically similar models instead of the", "How does Hybrid Retrieval Architectures: Dense Vector Search + Sparse Lexical Search scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-20', 'phase-10-lesson-20-bm25-lexical-retrieval-mechanics-inverted', 'module-11', 20, 'Lesson 11.20: BM25 Lexical Retrieval Mechanics & Inverted Indexes', 'Prerequisites: Phase 3, Lesson 8.21, Lesson 10.19', 'Prerequisites: Phase 3, Lesson 8.21, Lesson 10.19 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1000.0, '# Lesson 10.20: BM25 Lexical Retrieval Mechanics & Inverted Indexes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Lesson 8.21, Lesson 10.19
- **Subtopics**:
  - `10.20.1` The BM25 (Best Matching 25) probabilistic relevance framework derived from the Okapi information retrieval system
  - `10.20.2` Term Frequency (TF) saturation: why BM25 limits the impact of repeatedly repeating a keyword via parameter $k_1$ (typically 1.2-2.0)
  - `10.20.3` Inverse Document Frequency (IDF): $\text{IDF}(q_i) = \ln\left(\frac{N - n(q_i) + 0.5}{n(q_i) + 0.5} + 1\right)$; penalizing ubiquitous common words
  - `10.20.4` Document length normalization: parameter $b$ (typically 0.75) penalizing excessively long documents to prevent unfair length advantages
  - `10.20.5` BM25 formula derivation: $\sum_{i=1}^m \text{IDF}(q_i) \cdot \frac{f(q_i, D) \cdot (k_1 + 1)}{f(q_i, D) + k_1 \cdot (1 - b + b \cdot \frac{|D|}{\text{avgdl}})}$
  - `10.20.6` Implementing BM25 from scratch: tokenization, stop-words, term-document posting lists, and document length tracking
- **Key Failure Modes & Edge Cases**: Failing to normalize document length ($b=0$), causing 50-page documents to dominate search results over concise 1-paragraph answers.
- **Verification & Mastery Check**: Build a standalone BM25 retrieval engine from scratch in pure Python; verify scoring correctness against rank-bm25 library.
- **Project Application**: DocuMind: Core BM25 lexical retrieval engine.', '{"solution.py": "# Phase 10 // Lesson 10.20: BM25 Lexical Retrieval Mechanics & Inverted Indexes\n\ndef solve():\n    \"\"\"\n    Verification: Build a standalone BM25 retrieval engine from scratch in pure Python; verify scoring correctness aga\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.20", "subtopics_count": 6, "verification_criteria": "Build a standalone BM25 retrieval engine from scratch in pure Python; verify scoring correctness against rank-bm25 library.", "subtopics": ["10.20.1 The BM25 (Best Matching 25) probabilistic relevance framework derived from the Okapi information retrieval system", "10.20.2 Term Frequency (TF) saturation: why BM25 limits the impact of repeatedly repeating a keyword via parameter $k_1$ (typically 1.2-2.0)", "10.20.3 Inverse Document Frequency (IDF): $\\text{IDF}(q_i) = \\ln\\left(\\frac{N - n(q_i) + 0.5}{n(q_i) + 0.5} + 1\\right)$; penalizing ubiquitous common words", "10.20.4 Document length normalization: parameter $b$ (typically 0.75) penalizing excessively long documents to prevent unfair length advantages", "10.20.5 BM25 formula derivation: $\\sum_{i=1}^m \\text{IDF}(q_i) \\cdot \\frac{f(q_i, D) \\cdot (k_1 + 1)}{f(q_i, D) + k_1 \\cdot (1 - b + b \\cdot \\frac{|D|}{\\text{avgdl}})}$", "10.20.6 Implementing BM25 from scratch: tokenization, stop-words, term-document posting lists, and document length tracking"]}'::jsonb, '["Explain how this implementation prevents: Failing to normalize document length ($b=0$), causing 50-page documents to dominate search results over concise 1-paragr", "How does BM25 Lexical Retrieval Mechanics & Inverted Indexes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-21', 'phase-10-lesson-21-reciprocal-rank-fusion-rrf-weighted-score', 'module-11', 21, 'Lesson 11.21: Reciprocal Rank Fusion (RRF) & Weighted Score Combination', 'Prerequisites: Lesson 10.19, Lesson 10.20', 'Prerequisites: Lesson 10.19, Lesson 10.20 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 1050.0, '# Lesson 10.21: Reciprocal Rank Fusion (RRF) & Weighted Score Combination

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.19, Lesson 10.20
- **Subtopics**:
  - `10.21.1` The score normalization challenge: dense cosine similarity ($[0, 1]$) and BM25 scores ($[0, \infty)$) live on non-comparable mathematical scales
  - `10.21.2` Min-Max score normalization pitfalls: extreme outliers skewing normalized distribution, making linear combinations unreliable
  - `10.21.3` Reciprocal Rank Fusion (RRF) algorithm (Cormack et al.): rank-based fusion agnostic to raw score distributions
  - `10.21.4` RRF mathematical formulation: $\text{RRF\_Score}(d) = \sum_{m \in M} \frac{1}{k + r_m(d)}$ where $r_m(d)$ is document rank in system $m$
  - `10.21.5` The smoothing constant $k$ (typically $k=60$): dampening the advantage of top-ranked items and stabilizing multi-list aggregation
  - `10.21.6` Weighted RRF: applying domain-specific weight coefficients ($w_{dense} \cdot \text{RRF}_{dense} + w_{sparse} \cdot \text{RRF}_{sparse}$)
- **Key Failure Modes & Edge Cases**: Directly adding raw BM25 score (42.5) to raw cosine similarity (0.82), completely erasing the influence of the vector score.
- **Verification & Mastery Check**: Implement Reciprocal Rank Fusion (RRF) combining top-50 dense and top-50 sparse search result lists into a unified ranked list.
- **Project Application**: DocuMind: RRF result fusion module.', '{"solution.py": "# Phase 10 // Lesson 10.21: Reciprocal Rank Fusion (RRF) & Weighted Score Combination\n\ndef solve():\n    \"\"\"\n    Verification: Implement Reciprocal Rank Fusion (RRF) combining top-50 dense and top-50 sparse search result lists \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.21", "subtopics_count": 6, "verification_criteria": "Implement Reciprocal Rank Fusion (RRF) combining top-50 dense and top-50 sparse search result lists into a unified ranked list.", "subtopics": ["10.21.1 The score normalization challenge: dense cosine similarity ($[0, 1]$) and BM25 scores ($[0, \\infty)$) live on non-comparable mathematical scales", "10.21.2 Min-Max score normalization pitfalls: extreme outliers skewing normalized distribution, making linear combinations unreliable", "10.21.3 Reciprocal Rank Fusion (RRF) algorithm (Cormack et al.): rank-based fusion agnostic to raw score distributions", "10.21.4 RRF mathematical formulation: $\\text{RRF\\_Score}(d) = \\sum_{m \\in M} \\frac{1}{k + r_m(d)}$ where $r_m(d)$ is document rank in system $m$", "10.21.5 The smoothing constant $k$ (typically $k=60$): dampening the advantage of top-ranked items and stabilizing multi-list aggregation", "10.21.6 Weighted RRF: applying domain-specific weight coefficients ($w_{dense} \\cdot \\text{RRF}_{dense} + w_{sparse} \\cdot \\text{RRF}_{sparse}$)"]}'::jsonb, '["Explain how this implementation prevents: Directly adding raw BM25 score (42.5) to raw cosine similarity (0.82), completely erasing the influence of the vector sc", "How does Reciprocal Rank Fusion (RRF) & Weighted Score Combination scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-22', 'phase-10-lesson-22-query-transformation-multi-query-sub-ques', 'module-11', 22, 'Lesson 11.22: Query Transformation: Multi-Query, Sub-Question Decomposition & HyDE', 'Prerequisites: Lesson 10.2, Lesson 10.19', 'Prerequisites: Lesson 10.2, Lesson 10.19 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 1100.0, '# Lesson 10.22: Query Transformation: Multi-Query, Sub-Question Decomposition & HyDE

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.2, Lesson 10.19
- **Subtopics**:
  - `10.22.1` Why raw user queries fail: ambiguous phrasing, colloquial language, multiple questions in one, or lack of domain keywords
  - `10.22.2` Query Rewriting: using an LLM to rewrite ambiguous conversational prompts into clear, self-contained standalone search queries
  - `10.22.3` Multi-Query Generation: generating 3-5 diverse semantic variations of the user prompt to execute parallel multi-vector retrieval
  - `10.22.4` Sub-Question Decomposition: breaking complex compound questions into individual atomic questions retrieved independently
  - `10.22.5` Hypothetical Document Embeddings (HyDE) (Gao et al.): prompting an LLM to generate a hypothetical ideal answer, then embedding the answer
  - `10.22.6` Why HyDE works: mapping from query space into document passage space, bridging the semantic gap between questions and answers
- **Key Failure Modes & Edge Cases**: Using HyDE for factual numerical lookups where the LLM''s hallucinated hypothetical numbers distort vector search away from real facts.
- **Verification & Mastery Check**: Implement an automated query transformation pipeline featuring Multi-Query generation, Sub-Question decomposition, and HyDE.
- **Project Application**: DocuMind: Query rewriting and transformation engine.', '{"solution.py": "# Phase 10 // Lesson 10.22: Query Transformation: Multi-Query, Sub-Question Decomposition & HyDE\n\ndef solve():\n    \"\"\"\n    Verification: Implement an automated query transformation pipeline featuring Multi-Query generation, Sub-Question \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.22", "subtopics_count": 6, "verification_criteria": "Implement an automated query transformation pipeline featuring Multi-Query generation, Sub-Question decomposition, and HyDE.", "subtopics": ["10.22.1 Why raw user queries fail: ambiguous phrasing, colloquial language, multiple questions in one, or lack of domain keywords", "10.22.2 Query Rewriting: using an LLM to rewrite ambiguous conversational prompts into clear, self-contained standalone search queries", "10.22.3 Multi-Query Generation: generating 3-5 diverse semantic variations of the user prompt to execute parallel multi-vector retrieval", "10.22.4 Sub-Question Decomposition: breaking complex compound questions into individual atomic questions retrieved independently", "10.22.5 Hypothetical Document Embeddings (HyDE) (Gao et al.): prompting an LLM to generate a hypothetical ideal answer, then embedding the answer", "10.22.6 Why HyDE works: mapping from query space into document passage space, bridging the semantic gap between questions and answers"]}'::jsonb, '["Explain how this implementation prevents: Using HyDE for factual numerical lookups where the LLM''s hallucinated hypothetical numbers distort vector search away fr", "How does Query Transformation: Multi-Query, Sub-Question Decomposition & HyDE scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-23', 'phase-10-lesson-23-query-routing-semantic-classification-int', 'module-11', 23, 'Lesson 11.23: Query Routing: Semantic Classification, Intent Detection & Tool Dispatch', 'Prerequisites: Lesson 10.3, Lesson 10.22', 'Prerequisites: Lesson 10.3, Lesson 10.22 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1150.0, '# Lesson 10.23: Query Routing: Semantic Classification, Intent Detection & Tool Dispatch

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.3, Lesson 10.22
- **Subtopics**:
  - `10.23.1` The multi-index enterprise reality: code repositories, customer tickets, financial tables, and general wikis needing different retrieval paths
  - `10.23.2` Query Routing architectures: determining which retrieval strategy, index, or external database is best suited for a user request
  - `10.23.3` LLM-based routing: passing prompt to a fast small model (e.g. Claude 3 Haiku / GPT-4o-mini) with structured classification outputs
  - `10.23.4` Semantic Router (embedding classification): computing cosine similarity between query embedding and pre-defined intent centroid clusters (<5ms)
  - `10.23.5` Direct answering bypass: routing greeting, small-talk, or pure reasoning queries directly to the LLM without triggering expensive RAG searches
  - `10.23.6` Multi-hop routing: dynamically chaining SQL queries, vector search, and web search for complex hybrid research questions
- **Key Failure Modes & Edge Cases**: Executing expensive hybrid RAG retrievals on simple conversational greetings like ''Hello, how are you today?''.
- **Verification & Mastery Check**: Build an ultra-fast semantic query router in Python classifying incoming prompts into vector search, SQL search, or direct LLM bypass.
- **Project Application**: DocuMind: Dynamic semantic query router.', '{"solution.py": "# Phase 10 // Lesson 10.23: Query Routing: Semantic Classification, Intent Detection & Tool Dispatch\n\ndef solve():\n    \"\"\"\n    Verification: Build an ultra-fast semantic query router in Python classifying incoming prompts into vector search,\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.23", "subtopics_count": 6, "verification_criteria": "Build an ultra-fast semantic query router in Python classifying incoming prompts into vector search, SQL search, or direct LLM bypass.", "subtopics": ["10.23.1 The multi-index enterprise reality: code repositories, customer tickets, financial tables, and general wikis needing different retrieval paths", "10.23.2 Query Routing architectures: determining which retrieval strategy, index, or external database is best suited for a user request", "10.23.3 LLM-based routing: passing prompt to a fast small model (e.g. Claude 3 Haiku / GPT-4o-mini) with structured classification outputs", "10.23.4 Semantic Router (embedding classification): computing cosine similarity between query embedding and pre-defined intent centroid clusters (<5ms)", "10.23.5 Direct answering bypass: routing greeting, small-talk, or pure reasoning queries directly to the LLM without triggering expensive RAG searches", "10.23.6 Multi-hop routing: dynamically chaining SQL queries, vector search, and web search for complex hybrid research questions"]}'::jsonb, '["Explain how this implementation prevents: Executing expensive hybrid RAG retrievals on simple conversational greetings like ''Hello, how are you today?''.", "How does Query Routing: Semantic Classification, Intent Detection & Tool Dispatch scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-24', 'phase-10-lesson-24-cross-encoder-re-ranking-architecture-pre', 'module-11', 24, 'Lesson 11.24: Cross-Encoder Re-Ranking: Architecture, Precision Gains & Latency', 'Prerequisites: Lesson 10.17, Lesson 10.21', 'Prerequisites: Lesson 10.17, Lesson 10.21 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 1200.0, '# Lesson 10.24: Cross-Encoder Re-Ranking: Architecture, Precision Gains & Latency

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.17, Lesson 10.21
- **Subtopics**:
  - `10.24.1` Bi-Encoders vs Cross-Encoders: independent sentence encoding ($f(q), f(d)$) vs joint token-level cross-attention ($f(q, d)$)
  - `10.24.2` Why Cross-Encoders achieve superior ranking precision: all tokens of the query directly attend to all tokens of the candidate passage
  - `10.24.3` The computational cost of Cross-Encoders: $O(N)$ full forward passes at query time; why Cross-Encoders cannot be pre-indexed into vector stores
  - `10.24.4` The Two-Stage Retrieval Architecture: Stage 1 (retrieve top-100 via fast hybrid Bi-Encoder/BM25) $\to$ Stage 2 (re-rank top-100 to top-5 via Cross-Encoder)
  - `10.24.5` Production Cross-Encoder models: Cohere Rerank v3, BAAI `bge-reranker-large`, and mixed-precision execution
  - `10.24.6` Latency budget management: batching re-ranking candidates and enforcing timeouts to keep total retrieval latency under 200ms
- **Key Failure Modes & Edge Cases**: Attempting to re-rank 2,000 candidate documents with a heavy Cross-Encoder, blowing the API response latency budget past 5 seconds.
- **Verification & Mastery Check**: Implement a Two-Stage retrieval pipeline: retrieve 50 candidates via hybrid search, re-rank to top-5 via Cross-Encoder, measure MRR improvements.
- **Project Application**: DocuMind: Two-stage retrieval and cross-encoder re-ranking pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.24: Cross-Encoder Re-Ranking: Architecture, Precision Gains & Latency\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Two-Stage retrieval pipeline: retrieve 50 candidates via hybrid search, re-rank to top-5\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.24", "subtopics_count": 6, "verification_criteria": "Implement a Two-Stage retrieval pipeline: retrieve 50 candidates via hybrid search, re-rank to top-5 via Cross-Encoder, measure MRR improvements.", "subtopics": ["10.24.1 Bi-Encoders vs Cross-Encoders: independent sentence encoding ($f(q), f(d)$) vs joint token-level cross-attention ($f(q, d)$)", "10.24.2 Why Cross-Encoders achieve superior ranking precision: all tokens of the query directly attend to all tokens of the candidate passage", "10.24.3 The computational cost of Cross-Encoders: $O(N)$ full forward passes at query time; why Cross-Encoders cannot be pre-indexed into vector stores", "10.24.4 The Two-Stage Retrieval Architecture: Stage 1 (retrieve top-100 via fast hybrid Bi-Encoder/BM25) $\\to$ Stage 2 (re-rank top-100 to top-5 via Cross-Encoder)", "10.24.5 Production Cross-Encoder models: Cohere Rerank v3, BAAI `bge-reranker-large`, and mixed-precision execution", "10.24.6 Latency budget management: batching re-ranking candidates and enforcing timeouts to keep total retrieval latency under 200ms"]}'::jsonb, '["Explain how this implementation prevents: Attempting to re-rank 2,000 candidate documents with a heavy Cross-Encoder, blowing the API response latency budget past", "How does Cross-Encoder Re-Ranking: Architecture, Precision Gains & Latency scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-25', 'phase-10-lesson-25-context-compression-prompt-filtering-extr', 'module-11', 25, 'Lesson 11.25: Context Compression & Prompt Filtering: Extractive Summarization & LLMLingua', 'Prerequisites: Lesson 10.4, Lesson 10.24', 'Prerequisites: Lesson 10.4, Lesson 10.24 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 1250.0, '# Lesson 10.25: Context Compression & Prompt Filtering: Extractive Summarization & LLMLingua

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.4, Lesson 10.24
- **Subtopics**:
  - `10.25.1` The bloated context problem: re-ranked chunks still containing irrelevant sentences that inflate token costs and degrade LLM reasoning
  - `10.25.2` Extractive sentence compression: scoring individual sentences within retrieved chunks and pruning sentences below relevance thresholds
  - `10.25.3` LLMLingua (Microsoft Research): using small language models (e.g. LLaMA-2-7B) to compute token perplexity and compress prompts by up to 5x
  - `10.25.4` Token pruning mechanics: removing redundant structural tokens, whitespace, and low-information words while preserving semantic integrity
  - `10.25.5` Information density optimization: formatting retrieved context with clean XML tags (`<doc id=''1''>...</doc>`) for optimal model parsing
  - `10.25.6` Context deduplication: identifying and collapsing overlapping paragraphs from different retrieved documents
- **Key Failure Modes & Edge Cases**: Aggressive context compression stripping critical negation words (''not'', ''never''), reversing the factual meaning of retrieved policies.
- **Verification & Mastery Check**: Integrate LLMLingua prompt compression into a RAG pipeline; compress retrieved context by 40% while maintaining 100% answer accuracy.
- **Project Application**: DocuMind: Context compression and token pruning module.', '{"solution.py": "# Phase 10 // Lesson 10.25: Context Compression & Prompt Filtering: Extractive Summarization & LLMLingua\n\ndef solve():\n    \"\"\"\n    Verification: Integrate LLMLingua prompt compression into a RAG pipeline; compress retrieved context by 40% while \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.25", "subtopics_count": 6, "verification_criteria": "Integrate LLMLingua prompt compression into a RAG pipeline; compress retrieved context by 40% while maintaining 100% answer accuracy.", "subtopics": ["10.25.1 The bloated context problem: re-ranked chunks still containing irrelevant sentences that inflate token costs and degrade LLM reasoning", "10.25.2 Extractive sentence compression: scoring individual sentences within retrieved chunks and pruning sentences below relevance thresholds", "10.25.3 LLMLingua (Microsoft Research): using small language models (e.g. LLaMA-2-7B) to compute token perplexity and compress prompts by up to 5x", "10.25.4 Token pruning mechanics: removing redundant structural tokens, whitespace, and low-information words while preserving semantic integrity", "10.25.5 Information density optimization: formatting retrieved context with clean XML tags (`<doc id=''1''>...</doc>`) for optimal model parsing", "10.25.6 Context deduplication: identifying and collapsing overlapping paragraphs from different retrieved documents"]}'::jsonb, '["Explain how this implementation prevents: Aggressive context compression stripping critical negation words (''not'', ''never''), reversing the factual meaning of retr", "How does Context Compression & Prompt Filtering: Extractive Summarization & LLMLingua scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-26', 'phase-10-lesson-26-advanced-rag-patterns-parent-document-ret', 'module-11', 26, 'Lesson 11.26: Advanced RAG Patterns: Parent-Document Retrieval & Contextual RAG', 'Prerequisites: Lesson 10.14, Lesson 10.24', 'Prerequisites: Lesson 10.14, Lesson 10.24 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1300.0, '# Lesson 10.26: Advanced RAG Patterns: Parent-Document Retrieval & Contextual RAG

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.14, Lesson 10.24
- **Subtopics**:
  - `10.26.1` The dilemma: small chunks are best for accurate vector retrieval; large chunks are best for comprehensive LLM synthesis
  - `10.26.2` Parent-Document Retrieval architecture: split document into large parent chunks (e.g. 1500 tokens), then subdivide into small child chunks (200 tokens)
  - `10.26.3` Parent retrieval mechanics: embed and search child chunks; upon match, fetch and supply the parent chunk to the LLM context
  - `10.26.4` Contextual Retrieval (Anthropic): prepending concise document-level context to every individual chunk before embedding and indexing
  - `10.26.5` Contextual chunk generation: using a prompt pipeline to generate a 50-token contextual header per chunk (''This chunk discusses Q3 marketing budget...'')
  - `10.26.6` Evaluating Contextual RAG: empirical benchmarks showing 35-49% reduction in retrieval failure rates across enterprise corpora
- **Key Failure Modes & Edge Cases**: Returning disconnected tiny child chunks without parent context, leaving the LLM unable to resolve pronouns or table references.
- **Verification & Mastery Check**: Build a Parent-Document and Contextual Retrieval engine; benchmark retrieval accuracy against baseline single-chunk indexing.
- **Project Application**: DocuMind: Parent-Document and Contextual Retrieval engine.', '{"solution.py": "# Phase 10 // Lesson 10.26: Advanced RAG Patterns: Parent-Document Retrieval & Contextual RAG\n\ndef solve():\n    \"\"\"\n    Verification: Build a Parent-Document and Contextual Retrieval engine; benchmark retrieval accuracy against baseli\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.26", "subtopics_count": 6, "verification_criteria": "Build a Parent-Document and Contextual Retrieval engine; benchmark retrieval accuracy against baseline single-chunk indexing.", "subtopics": ["10.26.1 The dilemma: small chunks are best for accurate vector retrieval; large chunks are best for comprehensive LLM synthesis", "10.26.2 Parent-Document Retrieval architecture: split document into large parent chunks (e.g. 1500 tokens), then subdivide into small child chunks (200 tokens)", "10.26.3 Parent retrieval mechanics: embed and search child chunks; upon match, fetch and supply the parent chunk to the LLM context", "10.26.4 Contextual Retrieval (Anthropic): prepending concise document-level context to every individual chunk before embedding and indexing", "10.26.5 Contextual chunk generation: using a prompt pipeline to generate a 50-token contextual header per chunk (''This chunk discusses Q3 marketing budget...'')", "10.26.6 Evaluating Contextual RAG: empirical benchmarks showing 35-49% reduction in retrieval failure rates across enterprise corpora"]}'::jsonb, '["Explain how this implementation prevents: Returning disconnected tiny child chunks without parent context, leaving the LLM unable to resolve pronouns or table ref", "How does Advanced RAG Patterns: Parent-Document Retrieval & Contextual RAG scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-27', 'phase-10-lesson-27-evaluation-science-in-rag-the-rag-triad-f', 'module-11', 27, 'Lesson 11.27: Evaluation Science in RAG: The RAG Triad Framework', 'Prerequisites: Lesson 10.1, Lesson 10.24', 'Prerequisites: Lesson 10.1, Lesson 10.24 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 1350.0, '# Lesson 10.27: Evaluation Science in RAG: The RAG Triad Framework

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.1, Lesson 10.24
- **Subtopics**:
  - `10.27.1` Why standard NLP metrics (BLEU, ROUGE) fail for RAG: measuring n-gram overlap rather than semantic correctness and factual truth
  - `10.27.2` The RAG Triad framework: decomposing evaluation into three orthogonal, independently measurable axes
  - `10.27.3` Axis 1: Context Relevance: is the retrieved context strictly relevant and necessary to answer the user''s question?
  - `10.27.4` Axis 2: Groundedness / Faithfulness: is the generated answer completely supported by the retrieved context (zero hallucinations)?
  - `10.27.5` Axis 3: Answer Relevance: does the generated answer directly and fully address the user''s original query?
  - `10.27.6` Diagnosing failures via the Triad: isolating whether a bad response is caused by poor retrieval (Axis 1) or model hallucination (Axis 2)
- **Key Failure Modes & Edge Cases**: Attempting to fix RAG hallucinations by re-prompting the generation LLM when the root cause was retrieving irrelevant empty context.
- **Verification & Mastery Check**: Implement the mathematical scoring formulas for Context Relevance, Groundedness, and Answer Relevance from scratch.
- **Project Application**: EvalKit: Core RAG Triad evaluation metrics engine.', '{"solution.py": "# Phase 10 // Lesson 10.27: Evaluation Science in RAG: The RAG Triad Framework\n\ndef solve():\n    \"\"\"\n    Verification: Implement the mathematical scoring formulas for Context Relevance, Groundedness, and Answer Relevanc\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.27", "subtopics_count": 6, "verification_criteria": "Implement the mathematical scoring formulas for Context Relevance, Groundedness, and Answer Relevance from scratch.", "subtopics": ["10.27.1 Why standard NLP metrics (BLEU, ROUGE) fail for RAG: measuring n-gram overlap rather than semantic correctness and factual truth", "10.27.2 The RAG Triad framework: decomposing evaluation into three orthogonal, independently measurable axes", "10.27.3 Axis 1: Context Relevance: is the retrieved context strictly relevant and necessary to answer the user''s question?", "10.27.4 Axis 2: Groundedness / Faithfulness: is the generated answer completely supported by the retrieved context (zero hallucinations)?", "10.27.5 Axis 3: Answer Relevance: does the generated answer directly and fully address the user''s original query?", "10.27.6 Diagnosing failures via the Triad: isolating whether a bad response is caused by poor retrieval (Axis 1) or model hallucination (Axis 2)"]}'::jsonb, '["Explain how this implementation prevents: Attempting to fix RAG hallucinations by re-prompting the generation LLM when the root cause was retrieving irrelevant em", "How does Evaluation Science in RAG: The RAG Triad Framework scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-28', 'phase-10-lesson-28-automated-evaluation-frameworks-ragas-tru', 'module-11', 28, 'Lesson 11.28: Automated Evaluation Frameworks: Ragas, TruLens & DeepEval', 'Prerequisites: Lesson 10.27', 'Prerequisites: Lesson 10.27 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 1400.0, '# Lesson 10.28: Automated Evaluation Frameworks: Ragas, TruLens & DeepEval

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.27
- **Subtopics**:
  - `10.28.1` Automated RAG evaluation architectures: automating evaluation across thousands of queries without human bottleneck
  - `10.28.2` Ragas (Retrieval Augmented Generation Assessment) library internals: evaluation metrics, prompt templates, and scoring logic
  - `10.28.3` TruLens feedback functions: measuring groundedness, question-answering relevance, and toxic language detection
  - `10.28.4` DeepEval framework: G-Eval metric (NLG evaluation using GPT-4 with chain-of-thought grading criteria)
  - `10.28.5` Building automated CI/CD evaluation pipelines: blocking PR merges if RAG retrieval recall or faithfulness drops below threshold
  - `10.28.6` Continuous evaluation in production: sampling live user interactions for asynchronous background evaluation
- **Key Failure Modes & Edge Cases**: Trusting raw evaluation framework scores without inspecting underlying judge prompts, leading to undetected systematic scoring drift.
- **Verification & Mastery Check**: Construct an automated regression test suite using Ragas that evaluates 100 test cases and outputs a comprehensive quality scorecard.
- **Project Application**: EvalKit: Automated Ragas evaluation pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.28: Automated Evaluation Frameworks: Ragas, TruLens & DeepEval\n\ndef solve():\n    \"\"\"\n    Verification: Construct an automated regression test suite using Ragas that evaluates 100 test cases and outputs a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.28", "subtopics_count": 6, "verification_criteria": "Construct an automated regression test suite using Ragas that evaluates 100 test cases and outputs a comprehensive quality scorecard.", "subtopics": ["10.28.1 Automated RAG evaluation architectures: automating evaluation across thousands of queries without human bottleneck", "10.28.2 Ragas (Retrieval Augmented Generation Assessment) library internals: evaluation metrics, prompt templates, and scoring logic", "10.28.3 TruLens feedback functions: measuring groundedness, question-answering relevance, and toxic language detection", "10.28.4 DeepEval framework: G-Eval metric (NLG evaluation using GPT-4 with chain-of-thought grading criteria)", "10.28.5 Building automated CI/CD evaluation pipelines: blocking PR merges if RAG retrieval recall or faithfulness drops below threshold", "10.28.6 Continuous evaluation in production: sampling live user interactions for asynchronous background evaluation"]}'::jsonb, '["Explain how this implementation prevents: Trusting raw evaluation framework scores without inspecting underlying judge prompts, leading to undetected systematic s", "How does Automated Evaluation Frameworks: Ragas, TruLens & DeepEval scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-29', 'phase-10-lesson-29-synthetic-testset-generation-evol-instruc', 'module-11', 29, 'Lesson 11.29: Synthetic Testset Generation: Evol-Instruct & Multi-Hop Query Synthesis', 'Prerequisites: Lesson 10.2, Lesson 10.28', 'Prerequisites: Lesson 10.2, Lesson 10.28 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1450.0, '# Lesson 10.29: Synthetic Testset Generation: Evol-Instruct & Multi-Hop Query Synthesis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.2, Lesson 10.28
- **Subtopics**:
  - `10.29.1` The golden dataset bottleneck: human manual question-answer curation is slow, expensive, and unrepresentative of edge cases
  - `10.29.2` Automated synthetic dataset generation: generating high-quality (Question, Context, Ground Truth) triplets from raw corpora
  - `10.29.3` Evol-Instruct methodology: starting with simple questions and iteratively mutating them to increase complexity (reasoning, constraints, multi-hop)
  - `10.29.4` Generating diverse query distributions: factual queries, analytical queries, multi-document synthesis queries, and unanswerable queries
  - `10.29.5` Filtering synthetic testsets: validating that synthetic answers are strictly answerable from provided context before adding to test suite
  - `10.29.6` Negative testing: generating adversarial unanswerable questions to verify that the RAG system politely declines rather than hallucinates
- **Key Failure Modes & Edge Cases**: Generating synthetic questions that contain the answer verbatim, resulting in artificially inflated 99% retrieval scores.
- **Verification & Mastery Check**: Build an automated synthetic testset generator producing 200 varied (simple, multi-hop, unanswerable) test cases from enterprise documents.
- **Project Application**: EvalKit: Synthetic testset generation harness.', '{"solution.py": "# Phase 10 // Lesson 10.29: Synthetic Testset Generation: Evol-Instruct & Multi-Hop Query Synthesis\n\ndef solve():\n    \"\"\"\n    Verification: Build an automated synthetic testset generator producing 200 varied (simple, multi-hop, unanswerable\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.29", "subtopics_count": 6, "verification_criteria": "Build an automated synthetic testset generator producing 200 varied (simple, multi-hop, unanswerable) test cases from enterprise documents.", "subtopics": ["10.29.1 The golden dataset bottleneck: human manual question-answer curation is slow, expensive, and unrepresentative of edge cases", "10.29.2 Automated synthetic dataset generation: generating high-quality (Question, Context, Ground Truth) triplets from raw corpora", "10.29.3 Evol-Instruct methodology: starting with simple questions and iteratively mutating them to increase complexity (reasoning, constraints, multi-hop)", "10.29.4 Generating diverse query distributions: factual queries, analytical queries, multi-document synthesis queries, and unanswerable queries", "10.29.5 Filtering synthetic testsets: validating that synthetic answers are strictly answerable from provided context before adding to test suite", "10.29.6 Negative testing: generating adversarial unanswerable questions to verify that the RAG system politely declines rather than hallucinates"]}'::jsonb, '["Explain how this implementation prevents: Generating synthetic questions that contain the answer verbatim, resulting in artificially inflated 99% retrieval scores", "How does Synthetic Testset Generation: Evol-Instruct & Multi-Hop Query Synthesis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-30', 'phase-10-lesson-30-llm-as-a-judge-alignment-biases-mitigatio', 'module-11', 30, 'Lesson 11.30: LLM-as-a-Judge: Alignment, Biases & Mitigation Protocols', 'Prerequisites: Lesson 10.27, Lesson 10.28', 'Prerequisites: Lesson 10.27, Lesson 10.28 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 1500.0, '# Lesson 10.30: LLM-as-a-Judge: Alignment, Biases & Mitigation Protocols

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.27, Lesson 10.28
- **Subtopics**:
  - `10.30.1` The LLM-as-a-Judge paradigm (Zheng et al.): using frontier models (GPT-4, Claude 3.5 Sonnet) to evaluate model outputs
  - `10.30.2` Pairwise comparison vs Single-answer grading: comparing Model A vs Model B vs scoring on a 1-5 Likert scale
  - `10.30.3` Position Bias: the tendency of judges to favor the first presented option (Model A); mitigation via position swapping ($A/B \to B/A$)
  - `10.30.4` Verbosity Bias: the strong tendency of LLM judges to favor longer, wordier responses regardless of factual quality
  - `10.30.5` Self-Preference Bias: models rating responses generated by their own family higher than responses from other model families
  - `10.30.6` Chain-of-Thought Judge prompts: requiring the judge to write out explicit factual rubrics and evidence citations before outputting a score
- **Key Failure Modes & Edge Cases**: Relying on single-pass pairwise judgments, letting position bias skew evaluation results by up to 20%.
- **Verification & Mastery Check**: Build a bias-mitigated LLM-as-a-Judge evaluation engine implementing position swapping, verbosity normalization, and CoT rubrics.
- **Project Application**: EvalKit: Bias-mitigated LLM judge engine.', '{"solution.py": "# Phase 10 // Lesson 10.30: LLM-as-a-Judge: Alignment, Biases & Mitigation Protocols\n\ndef solve():\n    \"\"\"\n    Verification: Build a bias-mitigated LLM-as-a-Judge evaluation engine implementing position swapping, verbosity no\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.30", "subtopics_count": 6, "verification_criteria": "Build a bias-mitigated LLM-as-a-Judge evaluation engine implementing position swapping, verbosity normalization, and CoT rubrics.", "subtopics": ["10.30.1 The LLM-as-a-Judge paradigm (Zheng et al.): using frontier models (GPT-4, Claude 3.5 Sonnet) to evaluate model outputs", "10.30.2 Pairwise comparison vs Single-answer grading: comparing Model A vs Model B vs scoring on a 1-5 Likert scale", "10.30.3 Position Bias: the tendency of judges to favor the first presented option (Model A); mitigation via position swapping ($A/B \\to B/A$)", "10.30.4 Verbosity Bias: the strong tendency of LLM judges to favor longer, wordier responses regardless of factual quality", "10.30.5 Self-Preference Bias: models rating responses generated by their own family higher than responses from other model families", "10.30.6 Chain-of-Thought Judge prompts: requiring the judge to write out explicit factual rubrics and evidence citations before outputting a score"]}'::jsonb, '["Explain how this implementation prevents: Relying on single-pass pairwise judgments, letting position bias skew evaluation results by up to 20%.", "How does LLM-as-a-Judge: Alignment, Biases & Mitigation Protocols scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
