INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-10-1', 'phase-10-lesson-01-llm-apis-interaction-paradigms-rest-strea', 'module-11', 1, 'Lesson 11.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs', 'Prerequisites: Phase 4, Phase 9', 'Prerequisites: Phase 4, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 50.0, '# Lesson 10.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 9
- **Subtopics**:
  - `10.1.1` Foundation model API architectures: OpenAI, Anthropic, and Google Gemini API surface comparison
  - `10.1.2` HTTP streaming with Server-Sent Events (SSE): chunked transfer encoding, `data: [DONE]` markers, and low-latency token streaming
  - `10.1.3` Client-side consumption of streaming LLM outputs: handling partial JSON buffers and smooth rendering loops
  - `10.1.4` API parameters: Temperature (softmax scaling), Top-p (nucleus sampling), frequency_penalty, and presence_penalty
  - `10.1.5` Statelessness of LLM endpoints: passing multi-turn conversational message history (`system`, `user`, `assistant`)
  - `10.1.6` Rate limits: Tiered TPM (Tokens Per Minute) and RPM (Requests Per Minute); exponential backoff with jitter on HTTP 429
- **Key Failure Modes & Edge Cases**: Buffering the entire LLM response on the server before sending to the client, destroying perceived user response latency.
- **Verification & Mastery Check**: Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token rendering and retry backoff.
- **Project Application**: DocuMind: Streaming LLM gateway.', '{"solution.py": "# Phase 10 // Lesson 10.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs\n\ndef solve():\n    \"\"\"\n    Verification: Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token ren\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.1", "subtopics_count": 6, "verification_criteria": "Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token rendering and retry backoff.", "subtopics": ["10.1.1 Foundation model API architectures: OpenAI, Anthropic, and Google Gemini API surface comparison", "10.1.2 HTTP streaming with Server-Sent Events (SSE): chunked transfer encoding, `data: [DONE]` markers, and low-latency token streaming", "10.1.3 Client-side consumption of streaming LLM outputs: handling partial JSON buffers and smooth rendering loops", "10.1.4 API parameters: Temperature (softmax scaling), Top-p (nucleus sampling), frequency_penalty, and presence_penalty", "10.1.5 Statelessness of LLM endpoints: passing multi-turn conversational message history (`system`, `user`, `assistant`)", "10.1.6 Rate limits: Tiered TPM (Tokens Per Minute) and RPM (Requests Per Minute); exponential backoff with jitter on HTTP 429"]}'::jsonb, '["Explain how this implementation prevents: Buffering the entire LLM response on the server before sending to the client, destroying perceived user response latency", "How does LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-2', 'phase-10-lesson-02-prompt-engineering-science-zero-shot-few-', 'module-11', 2, 'Lesson 11.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct', 'Prerequisites: Lesson 10.1', 'Prerequisites: Lesson 10.1 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 100.0, '# Lesson 10.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.1
- **Subtopics**:
  - `10.2.1` Prompt engineering as programmatic programming: system instructions, contextual framing, and role specification
  - `10.2.2` Zero-Shot vs Few-Shot learning: in-context demonstrations, format conditioning, and selection of representative exemplars
  - `10.2.3` Chain-of-Thought (CoT) prompting (Wei et al.): eliciting step-by-step intermediate reasoning paths for complex logic
  - `10.2.4` Least-to-Most prompting: decomposing complex multi-step queries into sub-problems solved iteratively
  - `10.2.5` ReAct framework (Yao et al.): interleaving Reasoning (''Thought'') and Action (''Act'' / tool call) to interact with external tools
  - `10.2.6` Prompt fragility: why formatting quirks, whitespace, and capitalization trigger dramatic model accuracy variations
- **Key Failure Modes & Edge Cases**: Over-prompting with contradictory multi-page instructions causing the model to hallucinate or ignore negative constraints.
- **Verification & Mastery Check**: Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy on mathematical word problems.
- **Project Application**: DocuMind: Prompt orchestration and template library.', '{"solution.py": "# Phase 10 // Lesson 10.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct\n\ndef solve():\n    \"\"\"\n    Verification: Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.2", "subtopics_count": 6, "verification_criteria": "Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy on mathematical word problems.", "subtopics": ["10.2.1 Prompt engineering as programmatic programming: system instructions, contextual framing, and role specification", "10.2.2 Zero-Shot vs Few-Shot learning: in-context demonstrations, format conditioning, and selection of representative exemplars", "10.2.3 Chain-of-Thought (CoT) prompting (Wei et al.): eliciting step-by-step intermediate reasoning paths for complex logic", "10.2.4 Least-to-Most prompting: decomposing complex multi-step queries into sub-problems solved iteratively", "10.2.5 ReAct framework (Yao et al.): interleaving Reasoning (''Thought'') and Action (''Act'' / tool call) to interact with external tools", "10.2.6 Prompt fragility: why formatting quirks, whitespace, and capitalization trigger dramatic model accuracy variations"]}'::jsonb, '["Explain how this implementation prevents: Over-prompting with contradictory multi-page instructions causing the model to hallucinate or ignore negative constraint", "How does Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-3', 'phase-10-lesson-03-structured-outputs-function-calling-json-', 'module-11', 3, 'Lesson 11.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding', 'Prerequisites: Phase 1, Lesson 10.1', 'Prerequisites: Phase 1, Lesson 10.1 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 150.0, '# Lesson 10.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Lesson 10.1
- **Subtopics**:
  - `10.3.1` Why natural language outputs fail in production pipelines: parsing errors, non-deterministic formatting, and markdown fences
  - `10.3.2` OpenAI Function Calling / Tool Calling specification: JSON Schema declarations for functions, parameters, and types
  - `10.3.3` Pydantic integration: automatic generation of JSON Schemas from Python type annotations (`model_json_schema()`)
  - `10.3.4` OpenAI Structured Outputs (`response_format={''type'': ''json_schema''}`): 100% schema adherence guarantees
  - `10.3.5` Constrained Decoding mechanics: how inference engines mask invalid token vocabulary logits during autoregressive sampling based on CFG/grammar
  - `10.3.6` Open-source grammar-constrained decoding: Outlines, Guidance, and llama.cpp GBNF grammar files
- **Key Failure Modes & Edge Cases**: Relying on naive regex parsing to extract JSON from raw model strings, causing crashes when models wrap output in markdown code blocks.
- **Verification & Mastery Check**: Build an automated data extraction pipeline using Pydantic models and strict constrained decoding with 100% schema compliance.
- **Project Application**: DocuMind: Structured schema extraction engine.', '{"solution.py": "# Phase 10 // Lesson 10.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding\n\ndef solve():\n    \"\"\"\n    Verification: Build an automated data extraction pipeline using Pydantic models and strict constrained decoding wi\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.3", "subtopics_count": 6, "verification_criteria": "Build an automated data extraction pipeline using Pydantic models and strict constrained decoding with 100% schema compliance.", "subtopics": ["10.3.1 Why natural language outputs fail in production pipelines: parsing errors, non-deterministic formatting, and markdown fences", "10.3.2 OpenAI Function Calling / Tool Calling specification: JSON Schema declarations for functions, parameters, and types", "10.3.3 Pydantic integration: automatic generation of JSON Schemas from Python type annotations (`model_json_schema()`)", "10.3.4 OpenAI Structured Outputs (`response_format={''type'': ''json_schema''}`): 100% schema adherence guarantees", "10.3.5 Constrained Decoding mechanics: how inference engines mask invalid token vocabulary logits during autoregressive sampling based on CFG/grammar", "10.3.6 Open-source grammar-constrained decoding: Outlines, Guidance, and llama.cpp GBNF grammar files"]}'::jsonb, '["Explain how this implementation prevents: Relying on naive regex parsing to extract JSON from raw model strings, causing crashes when models wrap output in markdo", "How does Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-4', 'phase-10-lesson-04-context-window-dynamics-lost-in-the-middl', 'module-11', 4, 'Lesson 11.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution', 'Prerequisites: Phase 9, Lesson 10.2', 'Prerequisites: Phase 9, Lesson 10.2 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 200.0, '# Lesson 10.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Lesson 10.2
- **Subtopics**:
  - `10.4.1` Context window evolution: from 4K (GPT-3) to 128K (GPT-4) to 1M-2M tokens (Gemini 1.5)
  - `10.4.2` The ''Lost in the Middle'' phenomenon (Liu et al.): attention bias toward the beginning and end of long contexts
  - `10.4.3` Needle-in-a-Haystack (NIAH) evaluation: inserting synthetic facts at varying depth percentages ($0\%$ to $100\%$) to measure retrieval recall
  - `10.4.4` Attention dilution: performance degradation and reasoning degradation as context length increases with irrelevant noise
  - `10.4.5` Cost and latency implications: linear cost scaling and quadratic/linear latency increases with massive input prompts
  - `10.4.6` Strategic context placement: placing primary instructions at the very end and grounding documents near the top/bottom
- **Key Failure Modes & Edge Cases**: Stuffing 200 pages of raw un-filtered documentation into an LLM prompt, causing the model to miss critical instructions buried in the middle.
- **Verification & Mastery Check**: Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the resulting retrieval accuracy heatmap.
- **Project Application**: EvalKit: Context window diagnostic and needle benchmark suite.', '{"solution.py": "# Phase 10 // Lesson 10.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution\n\ndef solve():\n    \"\"\"\n    Verification: Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the r\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.4", "subtopics_count": 6, "verification_criteria": "Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the resulting retrieval accuracy heatmap.", "subtopics": ["10.4.1 Context window evolution: from 4K (GPT-3) to 128K (GPT-4) to 1M-2M tokens (Gemini 1.5)", "10.4.2 The ''Lost in the Middle'' phenomenon (Liu et al.): attention bias toward the beginning and end of long contexts", "10.4.3 Needle-in-a-Haystack (NIAH) evaluation: inserting synthetic facts at varying depth percentages ($0\\%$ to $100\\%$) to measure retrieval recall", "10.4.4 Attention dilution: performance degradation and reasoning degradation as context length increases with irrelevant noise", "10.4.5 Cost and latency implications: linear cost scaling and quadratic/linear latency increases with massive input prompts", "10.4.6 Strategic context placement: placing primary instructions at the very end and grounding documents near the top/bottom"]}'::jsonb, '["Explain how this implementation prevents: Stuffing 200 pages of raw un-filtered documentation into an LLM prompt, causing the model to miss critical instructions ", "How does Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-5', 'phase-10-lesson-05-tokenization-mechanics-bpe-wordpiece-tikt', 'module-11', 5, 'Lesson 11.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math', 'Prerequisites: Phase 3, Phase 9', 'Prerequisites: Phase 3, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 250.0, '# Lesson 10.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Phase 9
- **Subtopics**:
  - `10.5.1` Tokenization paradigms: Character-level vs Word-level vs Subword tokenization (Byte-Pair Encoding, WordPiece, Unigram)
  - `10.5.2` Byte-Pair Encoding (BPE) algorithm: starting with single bytes, iteratively merging most frequent byte pairs into vocabulary
  - `10.5.3` Byte-level BPE: handling arbitrary Unicode characters without unknown token (`<unk>`) out-of-vocabulary fallbacks
  - `10.5.4` Tiktoken library internals: fast Rust-backed BPE tokenizer for OpenAI models (`cl100k_base`, `o200k_base`)
  - `10.5.5` Tokenization quirks and vulnerabilities: space prefix sensitivity, arithmetic failure modes (numbers split into uneven chunks)
  - `10.5.6` Financial cost and latency estimation: calculating token consumption formulas ($1\text{ token} \approx 0.75\text{ words}$ in English; higher for code/non-English)
- **Key Failure Modes & Edge Cases**: Assuming 1 character = 1 token, underestimating API costs and context window consumption by 300% on multilingual text.
- **Verification & Mastery Check**: Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and visualize merge operations.
- **Project Application**: DocuMind: Tokenization and cost accounting module.', '{"solution.py": "# Phase 10 // Lesson 10.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.5", "subtopics_count": 6, "verification_criteria": "Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and visualize merge operations.", "subtopics": ["10.5.1 Tokenization paradigms: Character-level vs Word-level vs Subword tokenization (Byte-Pair Encoding, WordPiece, Unigram)", "10.5.2 Byte-Pair Encoding (BPE) algorithm: starting with single bytes, iteratively merging most frequent byte pairs into vocabulary", "10.5.3 Byte-level BPE: handling arbitrary Unicode characters without unknown token (`<unk>`) out-of-vocabulary fallbacks", "10.5.4 Tiktoken library internals: fast Rust-backed BPE tokenizer for OpenAI models (`cl100k_base`, `o200k_base`)", "10.5.5 Tokenization quirks and vulnerabilities: space prefix sensitivity, arithmetic failure modes (numbers split into uneven chunks)", "10.5.6 Financial cost and latency estimation: calculating token consumption formulas ($1\\text{ token} \\approx 0.75\\text{ words}$ in English; higher for code/non-English)"]}'::jsonb, '["Explain how this implementation prevents: Assuming 1 character = 1 token, underestimating API costs and context window consumption by 300% on multilingual text.", "How does Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-6', 'phase-10-lesson-06-vector-embeddings-semantic-space-cosine-s', 'module-11', 6, 'Lesson 11.6: Vector Embeddings: Semantic Space, Cosine Similarity & Distance Metrics', 'Prerequisites: Phase 2, Phase 9', 'Prerequisites: Phase 2, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 300.0, '# Lesson 10.6: Vector Embeddings: Semantic Space, Cosine Similarity & Distance Metrics

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2, Phase 9
- **Subtopics**:
  - `10.6.1` Embedding concept: mapping unstructured text into continuous high-dimensional vector spaces ($\mathbb{R}^D$, typically $D=768, 1536, 3072$)
  - `10.6.2` Geometric semantic representation: spatial proximity encoding semantic similarity; analogies ($v_{king} - v_{man} + v_{woman} \approx v_{queen}$)
  - `10.6.3` Cosine Similarity: $\cos(\theta) = \frac{u \cdot v}{\|u\|_2 \|v\|_2}$; scale-invariant angle measurement in range $[-1, 1]$
  - `10.6.4` Dot Product: $u \cdot v = \|u\|_2 \|v\|_2 \cos(\theta)$; equivalent to cosine similarity when vectors are $L_2$-normalized
  - `10.6.5` Euclidean Distance ($L_2$ distance): $\|u - v\|_2 = \sqrt{\sum (u_i - v_i)^2}$; monotonic relationship with cosine similarity on normalized vectors
  - `10.6.6` Manhattan Distance ($L_1$ distance) and inner product space trade-offs across different vector dimensions
- **Key Failure Modes & Edge Cases**: Computing dot products on un-normalized embeddings expecting cosine similarity scores, producing invalid ranking orders.
- **Verification & Mastery Check**: Write a vectorized similarity engine in NumPy computing pairwise Cosine, Dot Product, and Euclidean distances across 10,000 vectors.
- **Project Application**: DocuMind: Vector mathematical operations foundation.', '{"solution.py": "# Phase 10 // Lesson 10.6: Vector Embeddings: Semantic Space, Cosine Similarity & Distance Metrics\n\ndef solve():\n    \"\"\"\n    Verification: Write a vectorized similarity engine in NumPy computing pairwise Cosine, Dot Product, and Euclidean \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.6", "subtopics_count": 6, "verification_criteria": "Write a vectorized similarity engine in NumPy computing pairwise Cosine, Dot Product, and Euclidean distances across 10,000 vectors.", "subtopics": ["10.6.1 Embedding concept: mapping unstructured text into continuous high-dimensional vector spaces ($\\mathbb{R}^D$, typically $D=768, 1536, 3072$)", "10.6.2 Geometric semantic representation: spatial proximity encoding semantic similarity; analogies ($v_{king} - v_{man} + v_{woman} \\approx v_{queen}$)", "10.6.3 Cosine Similarity: $\\cos(\\theta) = \\frac{u \\cdot v}{\\|u\\|_2 \\|v\\|_2}$; scale-invariant angle measurement in range $[-1, 1]$", "10.6.4 Dot Product: $u \\cdot v = \\|u\\|_2 \\|v\\|_2 \\cos(\\theta)$; equivalent to cosine similarity when vectors are $L_2$-normalized", "10.6.5 Euclidean Distance ($L_2$ distance): $\\|u - v\\|_2 = \\sqrt{\\sum (u_i - v_i)^2}$; monotonic relationship with cosine similarity on normalized vectors", "10.6.6 Manhattan Distance ($L_1$ distance) and inner product space trade-offs across different vector dimensions"]}'::jsonb, '["Explain how this implementation prevents: Computing dot products on un-normalized embeddings expecting cosine similarity scores, producing invalid ranking orders.", "How does Vector Embeddings: Semantic Space, Cosine Similarity & Distance Metrics scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-7', 'phase-10-lesson-07-vector-indexing-i-flat-vs-inverted-file-i', 'module-11', 7, 'Lesson 11.7: Vector Indexing I: Flat vs Inverted File Index (IVF) Clustering', 'Prerequisites: Phase 3, Lesson 10.6', 'Prerequisites: Phase 3, Lesson 10.6 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 350.0, '# Lesson 10.7: Vector Indexing I: Flat vs Inverted File Index (IVF) Clustering

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Lesson 10.6
- **Subtopics**:
  - `10.7.1` Exact Nearest Neighbor search (Flat index): brute-force pairwise distance calculation, $O(N \cdot D)$ complexity, 100% recall
  - `10.7.2` The scale boundary: why Flat index becomes unusable for latency-sensitive applications when $N > 100,000$
  - `10.7.3` Approximate Nearest Neighbor (ANN) search: trading small recall degradation for orders-of-magnitude faster query latency
  - `10.7.4` Inverted File Index (IVF) architecture: partitioning vector space into $K$ Voronoi cells using $k$-means clustering
  - `10.7.5` IVF search mechanics: indexing centroid vectors; at query time, finding the $n_{probe}$ closest centroids and searching only those lists
  - `10.7.6` Tuning IVF trade-offs: $nlist$ (number of clusters) vs $nprobe$ (number of visited clusters); recall vs QPS trade-off curve
- **Key Failure Modes & Edge Cases**: Setting `nprobe=1` on an IVF index with high clustering variance, causing recall@10 to plummet to below 50%.
- **Verification & Mastery Check**: Implement an IVF vector index from scratch in Python with $k$-means centroid training, inverted posting lists, and tunable `nprobe`.
- **Project Application**: DocuMind: Core IVF index implementation.', '{"solution.py": "# Phase 10 // Lesson 10.7: Vector Indexing I: Flat vs Inverted File Index (IVF) Clustering\n\ndef solve():\n    \"\"\"\n    Verification: Implement an IVF vector index from scratch in Python with $k$-means centroid training, inverted post\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.7", "subtopics_count": 6, "verification_criteria": "Implement an IVF vector index from scratch in Python with $k$-means centroid training, inverted posting lists, and tunable `nprobe`.", "subtopics": ["10.7.1 Exact Nearest Neighbor search (Flat index): brute-force pairwise distance calculation, $O(N \\cdot D)$ complexity, 100% recall", "10.7.2 The scale boundary: why Flat index becomes unusable for latency-sensitive applications when $N > 100,000$", "10.7.3 Approximate Nearest Neighbor (ANN) search: trading small recall degradation for orders-of-magnitude faster query latency", "10.7.4 Inverted File Index (IVF) architecture: partitioning vector space into $K$ Voronoi cells using $k$-means clustering", "10.7.5 IVF search mechanics: indexing centroid vectors; at query time, finding the $n_{probe}$ closest centroids and searching only those lists", "10.7.6 Tuning IVF trade-offs: $nlist$ (number of clusters) vs $nprobe$ (number of visited clusters); recall vs QPS trade-off curve"]}'::jsonb, '["Explain how this implementation prevents: Setting `nprobe=1` on an IVF index with high clustering variance, causing recall@10 to plummet to below 50%.", "How does Vector Indexing I: Flat vs Inverted File Index (IVF) Clustering scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-8', 'phase-10-lesson-08-vector-indexing-ii-hierarchical-navigable', 'module-11', 8, 'Lesson 11.8: Vector Indexing II: Hierarchical Navigable Small World (HNSW) Graphs', 'Prerequisites: Phase 3, Lesson 10.7', 'Prerequisites: Phase 3, Lesson 10.7 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 400.0, '# Lesson 10.8: Vector Indexing II: Hierarchical Navigable Small World (HNSW) Graphs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Lesson 10.7
- **Subtopics**:
  - `10.8.1` Small World networks: high clustering coefficient and short average path lengths (six degrees of separation)
  - `10.8.2` SkipList 1D intuition: multi-layer linked lists with probabilistic exponential layer promotion for $O(\log N)$ search
  - `10.8.3` HNSW graph architecture: multi-layer proximity graphs where layer 0 contains all vectors, and higher layers contain sparser subsets
  - `10.8.4` Greedy graph routing algorithm: greedy search at top layer, descending layers at local minima until reaching layer 0
  - `10.8.5` Graph construction parameters: $M$ (max connections per node), $M_0$ (max connections in layer 0), $efConstruction$ (search depth during build)
  - `10.8.6` Query parameter $efSearch$: controlling dynamic candidate list size during search; direct dial for tuning Recall vs QPS
- **Key Failure Modes & Edge Cases**: Setting $efConstruction$ too low during graph building, creating disconnected graph clusters that cause permanent blind spots in search.
- **Verification & Mastery Check**: Build a working Hierarchical Navigable Small World (HNSW) graph search engine in Python; evaluate routing hops across layers.
- **Project Application**: DocuMind: HNSW graph indexing engine.', '{"solution.py": "# Phase 10 // Lesson 10.8: Vector Indexing II: Hierarchical Navigable Small World (HNSW) Graphs\n\ndef solve():\n    \"\"\"\n    Verification: Build a working Hierarchical Navigable Small World (HNSW) graph search engine in Python; evaluate ro\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.8", "subtopics_count": 6, "verification_criteria": "Build a working Hierarchical Navigable Small World (HNSW) graph search engine in Python; evaluate routing hops across layers.", "subtopics": ["10.8.1 Small World networks: high clustering coefficient and short average path lengths (six degrees of separation)", "10.8.2 SkipList 1D intuition: multi-layer linked lists with probabilistic exponential layer promotion for $O(\\log N)$ search", "10.8.3 HNSW graph architecture: multi-layer proximity graphs where layer 0 contains all vectors, and higher layers contain sparser subsets", "10.8.4 Greedy graph routing algorithm: greedy search at top layer, descending layers at local minima until reaching layer 0", "10.8.5 Graph construction parameters: $M$ (max connections per node), $M_0$ (max connections in layer 0), $efConstruction$ (search depth during build)", "10.8.6 Query parameter $efSearch$: controlling dynamic candidate list size during search; direct dial for tuning Recall vs QPS"]}'::jsonb, '["Explain how this implementation prevents: Setting $efConstruction$ too low during graph building, creating disconnected graph clusters that cause permanent blind ", "How does Vector Indexing II: Hierarchical Navigable Small World (HNSW) Graphs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-9', 'phase-10-lesson-09-vector-indexing-iii-product-quantization-', 'module-11', 9, 'Lesson 11.9: Vector Indexing III: Product Quantization (PQ) & Scalar Quantization', 'Prerequisites: Phase 0, Lesson 10.7', 'Prerequisites: Phase 0, Lesson 10.7 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 450.0, '# Lesson 10.9: Vector Indexing III: Product Quantization (PQ) & Scalar Quantization

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 10.7
- **Subtopics**:
  - `10.9.1` Memory consumption of high-dimensional vectors: storing 1M 1536-dim FP32 vectors requires $10^6 \times 1536 \times 4 \approx 6.14\text{GB}$ RAM
  - `10.9.2` Scalar Quantization (SQ8): converting 32-bit floating point numbers to 8-bit integers; $4\times$ memory reduction with minimal recall loss
  - `10.9.3` Product Quantization (PQ) architecture: splitting $D$-dimensional vector into $M$ sub-vectors, clustering each subspace into $K$ centroids
  - `10.9.4` Quantized representation: replacing sub-vectors with 8-bit centroid IDs; compressing 1536-dim FP32 to 96 bytes ($16\times$ compression)
  - `10.9.5` Asymmetric Distance Computation (ADC): querying unquantized query vector against quantized database vectors using lookup tables
  - `10.9.6` Combining IVF and PQ (IVF-PQ): clustering coarse centroids with IVF, then compressing residual vectors with PQ for massive scale
- **Key Failure Modes & Edge Cases**: Excessive PQ sub-vector decomposition destroying subtle semantic vector nuances; attempting PQ on low-dimensional spaces.
- **Verification & Mastery Check**: Implement Product Quantization (PQ) from scratch in NumPy; compress 50,000 vectors by $8\times$ and benchmark recall vs uncompressed Flat search.
- **Project Application**: DocuMind: Vector compression and quantization pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.9: Vector Indexing III: Product Quantization (PQ) & Scalar Quantization\n\ndef solve():\n    \"\"\"\n    Verification: Implement Product Quantization (PQ) from scratch in NumPy; compress 50,000 vectors by $8\\times$ and \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.9", "subtopics_count": 6, "verification_criteria": "Implement Product Quantization (PQ) from scratch in NumPy; compress 50,000 vectors by $8\\times$ and benchmark recall vs uncompressed Flat search.", "subtopics": ["10.9.1 Memory consumption of high-dimensional vectors: storing 1M 1536-dim FP32 vectors requires $10^6 \\times 1536 \\times 4 \\approx 6.14\\text{GB}$ RAM", "10.9.2 Scalar Quantization (SQ8): converting 32-bit floating point numbers to 8-bit integers; $4\\times$ memory reduction with minimal recall loss", "10.9.3 Product Quantization (PQ) architecture: splitting $D$-dimensional vector into $M$ sub-vectors, clustering each subspace into $K$ centroids", "10.9.4 Quantized representation: replacing sub-vectors with 8-bit centroid IDs; compressing 1536-dim FP32 to 96 bytes ($16\\times$ compression)", "10.9.5 Asymmetric Distance Computation (ADC): querying unquantized query vector against quantized database vectors using lookup tables", "10.9.6 Combining IVF and PQ (IVF-PQ): clustering coarse centroids with IVF, then compressing residual vectors with PQ for massive scale"]}'::jsonb, '["Explain how this implementation prevents: Excessive PQ sub-vector decomposition destroying subtle semantic vector nuances; attempting PQ on low-dimensional spaces", "How does Vector Indexing III: Product Quantization (PQ) & Scalar Quantization scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-10', 'phase-10-lesson-10-postgresql-vector-extensions-pgvector-arc', 'module-11', 10, 'Lesson 11.10: PostgreSQL Vector Extensions: pgvector Architecture & HNSW Tuning', 'Prerequisites: Phase 4, Lesson 10.8', 'Prerequisites: Phase 4, Lesson 10.8 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 500.0, '# Lesson 10.10: PostgreSQL Vector Extensions: pgvector Architecture & HNSW Tuning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 10.8
- **Subtopics**:
  - `10.10.1` Why vector search inside relational databases: eliminating dual-database synchronization lag and enabling unified SQL filtering
  - `10.10.2` `pgvector` extension internals: custom `vector` data type, operators (`<->` L2, `<#>` inner product, `<=>` cosine distance)
  - `10.10.3` Index types in `pgvector`: IVFFlat vs HNSW (pgvector 0.5.0+)
  - `10.10.4` Creating and tuning HNSW indexes: `CREATE INDEX ... USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)`
  - `10.10.5` Runtime query tuning: setting `SET hnsw.ef_search = 100` per session to balance query latency vs recall
  - `10.10.6` Hybrid queries in SQL: combining vector similarity with relational constraints (`WHERE organization_id = X AND created_at > Y`)
- **Key Failure Modes & Edge Cases**: Creating an IVFFlat index on an empty table before inserting data, resulting in empty or completely skewed cluster centroids.
- **Verification & Mastery Check**: Set up a PostgreSQL instance with `pgvector`; populate 100,000 1536-dim embeddings, build an HNSW index, and optimize query latency to <5ms.
- **Project Application**: DocuMind: Database storage and pgvector retrieval engine.', '{"solution.py": "# Phase 10 // Lesson 10.10: PostgreSQL Vector Extensions: pgvector Architecture & HNSW Tuning\n\ndef solve():\n    \"\"\"\n    Verification: Set up a PostgreSQL instance with `pgvector`; populate 100,000 1536-dim embeddings, build an HNSW in\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.10", "subtopics_count": 6, "verification_criteria": "Set up a PostgreSQL instance with `pgvector`; populate 100,000 1536-dim embeddings, build an HNSW index, and optimize query latency to <5ms.", "subtopics": ["10.10.1 Why vector search inside relational databases: eliminating dual-database synchronization lag and enabling unified SQL filtering", "10.10.2 `pgvector` extension internals: custom `vector` data type, operators (`<->` L2, `<#>` inner product, `<=>` cosine distance)", "10.10.3 Index types in `pgvector`: IVFFlat vs HNSW (pgvector 0.5.0+)", "10.10.4 Creating and tuning HNSW indexes: `CREATE INDEX ... USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)`", "10.10.5 Runtime query tuning: setting `SET hnsw.ef_search = 100` per session to balance query latency vs recall", "10.10.6 Hybrid queries in SQL: combining vector similarity with relational constraints (`WHERE organization_id = X AND created_at > Y`)"]}'::jsonb, '["Explain how this implementation prevents: Creating an IVFFlat index on an empty table before inserting data, resulting in empty or completely skewed cluster centr", "How does PostgreSQL Vector Extensions: pgvector Architecture & HNSW Tuning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-11', 'phase-10-lesson-11-vector-database-landscape-dedicated-vs-ge', 'module-11', 11, 'Lesson 11.11: Vector Database Landscape: Dedicated vs General-Purpose Stores', 'Prerequisites: Lesson 10.10', 'Prerequisites: Lesson 10.10 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 550.0, '# Lesson 10.11: Vector Database Landscape: Dedicated vs General-Purpose Stores

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.10
- **Subtopics**:
  - `10.11.1` Dedicated vector databases: Pinecone (managed SaaS), Qdrant (Rust, payload filtering), Milvus (distributed Go/C++), Weaviate (modular GraphQL)
  - `10.11.2` General-purpose extensions: pgvector (PostgreSQL), Redis Search (in-memory HNSW), Elasticsearch / OpenSearch dense_vector
  - `10.11.3` Architectural comparison matrix: scale (millions vs billions of vectors), indexing speed, filtering ergonomics, and operational cost
  - `10.11.4` Payload filtering mechanics: Pre-filtering (filter metadata first, then search vector subset) vs Post-filtering vs Single-stage filtered HNSW
  - `10.11.5` The filter-vector dilemma: why naive post-filtering fails when metadata filters exclude 99% of top vector matches
  - `10.11.6` Single-stage iterative graph traversal: Qdrant''s payload-aware HNSW traversing only graph nodes that satisfy metadata predicates
- **Key Failure Modes & Edge Cases**: Using post-filtering on restrictive metadata predicates, returning 0 search results because top vector neighbors were stripped post-hoc.
- **Verification & Mastery Check**: Benchmark Qdrant vs pgvector on 500,000 vectors with restrictive metadata filters; measure QPS and recall under high concurrency.
- **Project Application**: DocuMind: Vector storage engine selection benchmark.', '{"solution.py": "# Phase 10 // Lesson 10.11: Vector Database Landscape: Dedicated vs General-Purpose Stores\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark Qdrant vs pgvector on 500,000 vectors with restrictive metadata filters; measure QPS and r\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.11", "subtopics_count": 6, "verification_criteria": "Benchmark Qdrant vs pgvector on 500,000 vectors with restrictive metadata filters; measure QPS and recall under high concurrency.", "subtopics": ["10.11.1 Dedicated vector databases: Pinecone (managed SaaS), Qdrant (Rust, payload filtering), Milvus (distributed Go/C++), Weaviate (modular GraphQL)", "10.11.2 General-purpose extensions: pgvector (PostgreSQL), Redis Search (in-memory HNSW), Elasticsearch / OpenSearch dense_vector", "10.11.3 Architectural comparison matrix: scale (millions vs billions of vectors), indexing speed, filtering ergonomics, and operational cost", "10.11.4 Payload filtering mechanics: Pre-filtering (filter metadata first, then search vector subset) vs Post-filtering vs Single-stage filtered HNSW", "10.11.5 The filter-vector dilemma: why naive post-filtering fails when metadata filters exclude 99% of top vector matches", "10.11.6 Single-stage iterative graph traversal: Qdrant''s payload-aware HNSW traversing only graph nodes that satisfy metadata predicates"]}'::jsonb, '["Explain how this implementation prevents: Using post-filtering on restrictive metadata predicates, returning 0 search results because top vector neighbors were st", "How does Vector Database Landscape: Dedicated vs General-Purpose Stores scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-12', 'phase-10-lesson-12-approximate-nearest-neighbors-ann-benchma', 'module-11', 12, 'Lesson 11.12: Approximate Nearest Neighbors (ANN) Benchmarking: Recall@K vs QPS', 'Prerequisites: Lesson 10.7, Lesson 10.8', 'Prerequisites: Lesson 10.7, Lesson 10.8 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 600.0, '# Lesson 10.12: Approximate Nearest Neighbors (ANN) Benchmarking: Recall@K vs QPS

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.7, Lesson 10.8
- **Subtopics**:
  - `10.12.1` ANN benchmarking methodology: ground truth generation using exact brute-force Flat index search
  - `10.12.2` Recall@K definition: $\frac{|\text{Top } K \text{ approximate results} \cap \text{Top } K \text{ true results}|}{K}$
  - `10.12.3` Query throughput: Queries Per Second (QPS) under varying concurrency levels (single-threaded vs multi-threaded)
  - `10.12.4` Latency percentiles: p50, p95, p99 search latency distributions under sustained query load
  - `10.12.5` Generating Pareto frontiers: plotting Recall@K on the x-axis vs QPS on the y-axis across varying $efSearch$ / $nprobe$ configurations
  - `10.12.6` ann-benchmarks standard: understanding standardized datasets (GloVe, SIFT, Deep1B) and reproducing standardized evaluation runs
- **Key Failure Modes & Edge Cases**: Reporting 99% Recall@1 without measuring Recall@10 or p99 tail latency; evaluating on synthetic random vectors rather than clustered text embeddings.
- **Verification & Mastery Check**: Build an automated ANN benchmark harness evaluating recall@10 vs QPS curves across 5 index parameter configurations on a real dataset.
- **Project Application**: EvalKit: ANN benchmark and Pareto frontier generator.', '{"solution.py": "# Phase 10 // Lesson 10.12: Approximate Nearest Neighbors (ANN) Benchmarking: Recall@K vs QPS\n\ndef solve():\n    \"\"\"\n    Verification: Build an automated ANN benchmark harness evaluating recall@10 vs QPS curves across 5 index parameter\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.12", "subtopics_count": 6, "verification_criteria": "Build an automated ANN benchmark harness evaluating recall@10 vs QPS curves across 5 index parameter configurations on a real dataset.", "subtopics": ["10.12.1 ANN benchmarking methodology: ground truth generation using exact brute-force Flat index search", "10.12.2 Recall@K definition: $\\frac{|\\text{Top } K \\text{ approximate results} \\cap \\text{Top } K \\text{ true results}|}{K}$", "10.12.3 Query throughput: Queries Per Second (QPS) under varying concurrency levels (single-threaded vs multi-threaded)", "10.12.4 Latency percentiles: p50, p95, p99 search latency distributions under sustained query load", "10.12.5 Generating Pareto frontiers: plotting Recall@K on the x-axis vs QPS on the y-axis across varying $efSearch$ / $nprobe$ configurations", "10.12.6 ann-benchmarks standard: understanding standardized datasets (GloVe, SIFT, Deep1B) and reproducing standardized evaluation runs"]}'::jsonb, '["Explain how this implementation prevents: Reporting 99% Recall@1 without measuring Recall@10 or p99 tail latency; evaluating on synthetic random vectors rather th", "How does Approximate Nearest Neighbors (ANN) Benchmarking: Recall@K vs QPS scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-13', 'phase-10-lesson-13-document-ingestion-pipelines-parsing-pdfs', 'module-11', 13, 'Lesson 11.13: Document Ingestion Pipelines: Parsing PDFs, Markdown, HTML & OCR', 'Prerequisites: Phase 4, Lesson 10.5', 'Prerequisites: Phase 4, Lesson 10.5 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 650.0, '# Lesson 10.13: Document Ingestion Pipelines: Parsing PDFs, Markdown, HTML & OCR

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 10.5
- **Subtopics**:
  - `10.13.1` The messy reality of enterprise data: semi-structured PDFs, Word documents, scanned invoices, HTML wikis, and markdown
  - `10.13.2` PDF parsing internals: content streams, text positioning matrices ($Tm$), font glyph encodings, and reading order extraction
  - `10.13.3` Why naive PDF parsers fail: multi-column layouts read horizontally across columns, scrambled headers, and stripped formatting
  - `10.13.4` Advanced layout-aware parsers: PyMuPDF, pdfplumber, and layout-detection neural networks (LayoutLM, Marker)
  - `10.13.5` HTML and Markdown extraction: DOM element traversal, stripping script/nav tags, preserving markdown header hierarchy with BeautifulSoup
  - `10.13.6` Optical Character Recognition (OCR): Tesseract, easyOCR, and vision-language models for scanned document transcription
- **Key Failure Modes & Edge Cases**: Naive PDF parser reading two-column legal contracts horizontally across columns, interweaving unrelated sentences into nonsense.
- **Verification & Mastery Check**: Build a robust layout-aware PDF ingestion pipeline that correctly extracts two-column articles with preserved paragraph boundaries.
- **Project Application**: DocuMind: Enterprise multi-format document parser.', '{"solution.py": "# Phase 10 // Lesson 10.13: Document Ingestion Pipelines: Parsing PDFs, Markdown, HTML & OCR\n\ndef solve():\n    \"\"\"\n    Verification: Build a robust layout-aware PDF ingestion pipeline that correctly extracts two-column articles with \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.13", "subtopics_count": 6, "verification_criteria": "Build a robust layout-aware PDF ingestion pipeline that correctly extracts two-column articles with preserved paragraph boundaries.", "subtopics": ["10.13.1 The messy reality of enterprise data: semi-structured PDFs, Word documents, scanned invoices, HTML wikis, and markdown", "10.13.2 PDF parsing internals: content streams, text positioning matrices ($Tm$), font glyph encodings, and reading order extraction", "10.13.3 Why naive PDF parsers fail: multi-column layouts read horizontally across columns, scrambled headers, and stripped formatting", "10.13.4 Advanced layout-aware parsers: PyMuPDF, pdfplumber, and layout-detection neural networks (LayoutLM, Marker)", "10.13.5 HTML and Markdown extraction: DOM element traversal, stripping script/nav tags, preserving markdown header hierarchy with BeautifulSoup", "10.13.6 Optical Character Recognition (OCR): Tesseract, easyOCR, and vision-language models for scanned document transcription"]}'::jsonb, '["Explain how this implementation prevents: Naive PDF parser reading two-column legal contracts horizontally across columns, interweaving unrelated sentences into n", "How does Document Ingestion Pipelines: Parsing PDFs, Markdown, HTML & OCR scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-14', 'phase-10-lesson-14-chunking-strategies-fixed-size-sentence-r', 'module-11', 14, 'Lesson 11.14: Chunking Strategies: Fixed-Size, Sentence, Recursive & Semantic', 'Prerequisites: Lesson 10.13', 'Prerequisites: Lesson 10.13 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 700.0, '# Lesson 10.14: Chunking Strategies: Fixed-Size, Sentence, Recursive & Semantic

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.13
- **Subtopics**:
  - `10.14.1` Why chunking is mandatory: embedding model context length limits (typically 512 or 8192 tokens) and retrieval specificity
  - `10.14.2` Fixed-size chunking with overlap: character/token count thresholds (e.g. 500 tokens with 50 token overlap); simplicity vs boundary slicing
  - `10.14.3` Sentence-aware chunking: splitting strictly on sentence boundaries (using NLTK or SpaCy) to preserve linguistic semantics
  - `10.14.4` Recursive character chunking (LangChain-style): hierarchical separators (`[''\n\n'', ''\n'', '' '', '''']`) keeping structural paragraphs intact
  - `10.14.5` Semantic chunking: embedding consecutive sentences, computing cosine distance between adjacent sentences, and splitting on semantic drops
  - `10.14.6` The chunk size trade-off: small chunks (high precision retrieval, lost context) vs large chunks (rich context, diluted retrieval precision)
- **Key Failure Modes & Edge Cases**: Splitting chunks across hyphenated words or code blocks, destroying syntax and semantics; 0 chunk overlap causing lost context at seams.
- **Verification & Mastery Check**: Implement fixed, recursive, and semantic chunking algorithms from scratch in Python; evaluate semantic cohesion across chunk boundaries.
- **Project Application**: DocuMind: Modular chunking engine.', '{"solution.py": "# Phase 10 // Lesson 10.14: Chunking Strategies: Fixed-Size, Sentence, Recursive & Semantic\n\ndef solve():\n    \"\"\"\n    Verification: Implement fixed, recursive, and semantic chunking algorithms from scratch in Python; evaluate semant\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.14", "subtopics_count": 6, "verification_criteria": "Implement fixed, recursive, and semantic chunking algorithms from scratch in Python; evaluate semantic cohesion across chunk boundaries.", "subtopics": ["10.14.1 Why chunking is mandatory: embedding model context length limits (typically 512 or 8192 tokens) and retrieval specificity", "10.14.2 Fixed-size chunking with overlap: character/token count thresholds (e.g. 500 tokens with 50 token overlap); simplicity vs boundary slicing", "10.14.3 Sentence-aware chunking: splitting strictly on sentence boundaries (using NLTK or SpaCy) to preserve linguistic semantics", "10.14.4 Recursive character chunking (LangChain-style): hierarchical separators (`[''\\n\\n'', ''\\n'', '' '', '''']`) keeping structural paragraphs intact", "10.14.5 Semantic chunking: embedding consecutive sentences, computing cosine distance between adjacent sentences, and splitting on semantic drops", "10.14.6 The chunk size trade-off: small chunks (high precision retrieval, lost context) vs large chunks (rich context, diluted retrieval precision)"]}'::jsonb, '["Explain how this implementation prevents: Splitting chunks across hyphenated words or code blocks, destroying syntax and semantics; 0 chunk overlap causing lost c", "How does Chunking Strategies: Fixed-Size, Sentence, Recursive & Semantic scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-15', 'phase-10-lesson-15-multi-modal-document-parsing-tables-chart', 'module-11', 15, 'Lesson 11.15: Multi-Modal Document Parsing: Tables, Charts & Visual Layouts', 'Prerequisites: Lesson 10.13, Lesson 10.14', 'Prerequisites: Lesson 10.13, Lesson 10.14 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 750.0, '# Lesson 10.15: Multi-Modal Document Parsing: Tables, Charts & Visual Layouts

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.13, Lesson 10.14
- **Subtopics**:
  - `10.15.1` The tabular data crisis in RAG: flat text embeddings destroying 2D row/column relational alignment
  - `10.15.2` Table extraction techniques: structural HTML table representations vs Markdown tables vs CSV serialization
  - `10.15.3` Vision-Language Model (VLM) parsing: passing document page images to Gemini 1.5 Pro / GPT-4o for markdown table transcription
  - `10.15.4` Chart and infographic extraction: generating natural language descriptive summaries of visual charts for vector indexing
  - `10.15.5` Bounding box metadata: tracking $(x_0, y_0, x_1, y_1)$ page coordinates per chunk to enable visual citation highlighting in UIs
  - `10.15.6` Hierarchical section mapping: associating chunks with parent document title, chapter header, and subsection breadcrumbs
- **Key Failure Modes & Edge Cases**: Flattening financial balance sheets into unstructured paragraphs, causing LLM to swap columns and hallucinate revenue numbers.
- **Verification & Mastery Check**: Build a multi-modal document pipeline extracting complex nested financial tables into clean Markdown tables with coordinates.
- **Project Application**: DocuMind: Visual document and table extraction pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.15: Multi-Modal Document Parsing: Tables, Charts & Visual Layouts\n\ndef solve():\n    \"\"\"\n    Verification: Build a multi-modal document pipeline extracting complex nested financial tables into clean Markdown\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.15", "subtopics_count": 6, "verification_criteria": "Build a multi-modal document pipeline extracting complex nested financial tables into clean Markdown tables with coordinates.", "subtopics": ["10.15.1 The tabular data crisis in RAG: flat text embeddings destroying 2D row/column relational alignment", "10.15.2 Table extraction techniques: structural HTML table representations vs Markdown tables vs CSV serialization", "10.15.3 Vision-Language Model (VLM) parsing: passing document page images to Gemini 1.5 Pro / GPT-4o for markdown table transcription", "10.15.4 Chart and infographic extraction: generating natural language descriptive summaries of visual charts for vector indexing", "10.15.5 Bounding box metadata: tracking $(x_0, y_0, x_1, y_1)$ page coordinates per chunk to enable visual citation highlighting in UIs", "10.15.6 Hierarchical section mapping: associating chunks with parent document title, chapter header, and subsection breadcrumbs"]}'::jsonb, '["Explain how this implementation prevents: Flattening financial balance sheets into unstructured paragraphs, causing LLM to swap columns and hallucinate revenue nu", "How does Multi-Modal Document Parsing: Tables, Charts & Visual Layouts scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
