INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-2-31', 'phase-02-lesson-31-functions-injections-surjections-bijectio', 'module-3', 31, 'Lesson 3.31: Functions: Injections, Surjections, & Bijections', 'Prerequisites: Lesson 2.30', 'Prerequisites: Lesson 2.30 | Subtopics: 4 items', 'Systems project application', 140, 3, 560.0, 1550.0, '# Lesson 2.31: Functions: Injections, Surjections, & Bijections

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.30
- **Subtopics**:
  - `2.31.1` Domain, codomain, and range (image) of mathematical mappings.
  - `2.31.2` Injective (one-to-one) functions: uniqueness of outputs ($f(a) = f(b) \implies a = b$).
  - `2.31.3` Surjective (onto) functions: every element of codomain is mapped.
  - `2.31.4` Bijective functions: one-to-one correspondences, invertibility, and applications in cryptography and data encoding.
- **Key Failure Modes & Edge Cases**: Assuming a hash function is invertible or collision-free without verifying bijective properties.
- **Verification & Mastery Check**: Prove that Base62 encoding is a bijection between non-negative integers and alphanumeric strings.
- **Project Application**: Phase 8: URL shortener encoding.', '{"solution.py": "# Phase 2 // Lesson 2.31: Functions: Injections, Surjections, & Bijections\n\ndef solve():\n    \"\"\"\n    Verification: Prove that Base62 encoding is a bijection between non-negative integers and alphanumeric strings.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.31", "subtopics_count": 4, "verification_criteria": "Prove that Base62 encoding is a bijection between non-negative integers and alphanumeric strings.", "subtopics": ["2.31.1 Domain, codomain, and range (image) of mathematical mappings.", "2.31.2 Injective (one-to-one) functions: uniqueness of outputs ($f(a) = f(b) \\implies a = b$).", "2.31.3 Surjective (onto) functions: every element of codomain is mapped.", "2.31.4 Bijective functions: one-to-one correspondences, invertibility, and applications in cryptography and data encoding."]}'::jsonb, '["Explain how this implementation prevents: Assuming a hash function is invertible or collision-free without verifying bijective properties.", "How does Functions: Injections, Surjections, & Bijections scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-32', 'phase-02-lesson-32-combinatorics-permutations-combinations-p', 'module-3', 32, 'Lesson 3.32: Combinatorics: Permutations, Combinations, & Pigeonhole', 'Prerequisites: Lesson 2.30', 'Prerequisites: Lesson 2.30 | Subtopics: 4 items', 'Systems project application', 140, 3, 620.0, 1600.0, '# Lesson 2.32: Combinatorics: Permutations, Combinations, & Pigeonhole

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.30
- **Subtopics**:
  - `2.32.1` The Multiplication Principle and Addition Principle of counting.
  - `2.32.2` Permutations: ordered selections with and without repetition ($n! / (n-k)!$).
  - `2.32.3` Combinations: unordered selections ($nCr = rac{n!}{k!(n-k)!}$); Pascal''s triangle identity.
  - `2.32.4` The Pigeonhole Principle: if $n+1$ items occupy $n$ containers, at least one container holds $\ge 2$ items; hash collision inevitability.
- **Key Failure Modes & Edge Cases**: Combinatorial explosion: underestimating search spaces in brute-force algorithms ($O(n!)$ vs $O(2^n)$).
- **Verification & Mastery Check**: Calculate the exact collision probability threshold for a 32-bit hash function using the Pigeonhole Principle.
- **Project Application**: Phase 3: Backtracking search spaces.', '{"solution.py": "# Phase 2 // Lesson 2.32: Combinatorics: Permutations, Combinations, & Pigeonhole\n\ndef solve():\n    \"\"\"\n    Verification: Calculate the exact collision probability threshold for a 32-bit hash function using the Pigeonhole \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.32", "subtopics_count": 4, "verification_criteria": "Calculate the exact collision probability threshold for a 32-bit hash function using the Pigeonhole Principle.", "subtopics": ["2.32.1 The Multiplication Principle and Addition Principle of counting.", "2.32.2 Permutations: ordered selections with and without repetition ($n! / (n-k)!$).", "2.32.3 Combinations: unordered selections ($nCr = \frac{n!}{k!(n-k)!}$); Pascal''s triangle identity.", "2.32.4 The Pigeonhole Principle: if $n+1$ items occupy $n$ containers, at least one container holds $\\ge 2$ items; hash collision inevitability."]}'::jsonb, '["Explain how this implementation prevents: Combinatorial explosion: underestimating search spaces in brute-force algorithms ($O(n!)$ vs $O(2^n)$).", "How does Combinatorics: Permutations, Combinations, & Pigeonhole scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-33', 'phase-02-lesson-33-graph-theory-definitions-topologies-isomo', 'module-3', 33, 'Lesson 3.33: Graph Theory: Definitions, Topologies, & Isomorphisms', 'Prerequisites: Lesson 2.30', 'Prerequisites: Lesson 2.30 | Subtopics: 4 items', 'Systems project application', 140, 3, 500.0, 1650.0, '# Lesson 2.33: Graph Theory: Definitions, Topologies, & Isomorphisms

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.30
- **Subtopics**:
  - `2.33.1` Graph components: vertices ($V$), edges ($E$), directed vs undirected, weighted vs unweighted.
  - `2.33.2` Vertex degrees, in-degree, out-degree, and the Handshaking Lemma ($\sum \deg(v) = 2|E|$).
  - `2.33.3` Paths, cycles, connectivity, bipartite graphs, and tree definitions (connected acyclic graph with $|V|-1$ edges).
  - `2.33.4` Graph Isomorphism: determining structural equivalence between graph representations.
- **Key Failure Modes & Edge Cases**: Failing to check for cycles in directed graphs, causing infinite loops in dependency resolution engines.
- **Verification & Mastery Check**: Prove that an undirected graph with $V$ vertices and $V-1$ edges is a tree if and only if it is acyclic.
- **Project Application**: MathKit: `mathkit.graph` module.', '{"solution.py": "# Phase 2 // Lesson 2.33: Graph Theory: Definitions, Topologies, & Isomorphisms\n\ndef solve():\n    \"\"\"\n    Verification: Prove that an undirected graph with $V$ vertices and $V-1$ edges is a tree if and only if it is acyc\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.33", "subtopics_count": 4, "verification_criteria": "Prove that an undirected graph with $V$ vertices and $V-1$ edges is a tree if and only if it is acyclic.", "subtopics": ["2.33.1 Graph components: vertices ($V$), edges ($E$), directed vs undirected, weighted vs unweighted.", "2.33.2 Vertex degrees, in-degree, out-degree, and the Handshaking Lemma ($\\sum \\deg(v) = 2|E|$).", "2.33.3 Paths, cycles, connectivity, bipartite graphs, and tree definitions (connected acyclic graph with $|V|-1$ edges).", "2.33.4 Graph Isomorphism: determining structural equivalence between graph representations."]}'::jsonb, '["Explain how this implementation prevents: Failing to check for cycles in directed graphs, causing infinite loops in dependency resolution engines.", "How does Graph Theory: Definitions, Topologies, & Isomorphisms scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-34', 'phase-02-lesson-34-directed-acyclic-graphs-dags-topological-', 'module-3', 34, 'Lesson 3.34: Directed Acyclic Graphs (DAGs) & Topological Properties', 'Prerequisites: Lesson 2.33', 'Prerequisites: Lesson 2.33 | Subtopics: 4 items', 'Systems project application', 140, 3, 560.0, 1700.0, '# Lesson 2.34: Directed Acyclic Graphs (DAGs) & Topological Properties

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.33
- **Subtopics**:
  - `2.34.1` DAG properties: directed edges with zero directed cycles.
  - `2.34.2` Sources and Sinks in DAGs; reachability analysis and transitive reduction.
  - `2.34.3` Topological Ordering: linear ordering of vertices where every directed edge $(u, v)$ has $u$ before $v$.
  - `2.34.4` Why DAGs underpin computational workflows: task scheduling, build systems, neural network backpropagation.
- **Key Failure Modes & Edge Cases**: Circular dependency deadlocks in software build systems and package managers.
- **Verification & Mastery Check**: Implement a mathematical cycle detector that outputs the exact cycle path if a graph fails to be a DAG.
- **Project Application**: GradFlow: Computational graph evaluation in Phase 9.', '{"solution.py": "# Phase 2 // Lesson 2.34: Directed Acyclic Graphs (DAGs) & Topological Properties\n\ndef solve():\n    \"\"\"\n    Verification: Implement a mathematical cycle detector that outputs the exact cycle path if a graph fails to be a D\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.34", "subtopics_count": 4, "verification_criteria": "Implement a mathematical cycle detector that outputs the exact cycle path if a graph fails to be a DAG.", "subtopics": ["2.34.1 DAG properties: directed edges with zero directed cycles.", "2.34.2 Sources and Sinks in DAGs; reachability analysis and transitive reduction.", "2.34.3 Topological Ordering: linear ordering of vertices where every directed edge $(u, v)$ has $u$ before $v$.", "2.34.4 Why DAGs underpin computational workflows: task scheduling, build systems, neural network backpropagation."]}'::jsonb, '["Explain how this implementation prevents: Circular dependency deadlocks in software build systems and package managers.", "How does Directed Acyclic Graphs (DAGs) & Topological Properties scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-2-35', 'phase-02-lesson-35-asymptotic-complexity-formal-big-o-big-om', 'module-3', 35, 'Lesson 3.35: Asymptotic Complexity: Formal Big-O, Big-Omega, Big-Theta', 'Prerequisites: Lesson 2.26', 'Prerequisites: Lesson 2.26 | Subtopics: 4 items', 'Systems project application', 140, 3, 620.0, 1750.0, '# Lesson 2.35: Asymptotic Complexity: Formal Big-O, Big-Omega, Big-Theta

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 2.26
- **Subtopics**:
  - `2.35.1` Formal definition of Big-$O$: $f(n) \in O(g(n)) \iff \exists c > 0, n_0 > 0 	ext{ s.t. } f(n) \le c \cdot g(n) \quad orall n \ge n_0$.
  - `2.35.2` Formal definition of Big-$\Omega$ (lower bound) and Big-$\Theta$ (tight asymptotic bound).
  - `2.35.3` Little-$o$ and Little-$\omega$ definitions: strict asymptotic dominance.
  - `2.35.4` Limit test for complexity: $\lim_{n 	o \infty} rac{f(n)}{g(n)}$ to classify relative growth rates.
- **Key Failure Modes & Edge Cases**: Claiming an algorithm is $O(1)$ based on a small benchmark without analyzing asymptotic behavior at scale.
- **Verification & Mastery Check**: Formally prove using limit definitions that $3n^2 + 5n\log n \in \Theta(n^2)$.
- **Project Application**: Phase 3: Algorithmic complexity proofs.', '{"solution.py": "# Phase 2 // Lesson 2.35: Asymptotic Complexity: Formal Big-O, Big-Omega, Big-Theta\n\ndef solve():\n    \"\"\"\n    Verification: Formally prove using limit definitions that $3n^2 + 5n\\log n \\in \\Theta(n^2)$.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "2.35", "subtopics_count": 4, "verification_criteria": "Formally prove using limit definitions that $3n^2 + 5n\\log n \\in \\Theta(n^2)$.", "subtopics": ["2.35.1 Formal definition of Big-$O$: $f(n) \\in O(g(n)) \\iff \\exists c > 0, n_0 > 0 \text{ s.t. } f(n) \\le c \\cdot g(n) \\quad \forall n \\ge n_0$.", "2.35.2 Formal definition of Big-$\\Omega$ (lower bound) and Big-$\\Theta$ (tight asymptotic bound).", "2.35.3 Little-$o$ and Little-$\\omega$ definitions: strict asymptotic dominance.", "2.35.4 Limit test for complexity: $\\lim_{n \to \\infty} \frac{f(n)}{g(n)}$ to classify relative growth rates."]}'::jsonb, '["Explain how this implementation prevents: Claiming an algorithm is $O(1)$ based on a small benchmark without analyzing asymptotic behavior at scale.", "How does Asymptotic Complexity: Formal Big-O, Big-Omega, Big-Theta scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
