INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-6-1', 'phase-06-lesson-01-the-document-object-model-dom-tree-node-i', 'module-8', 1, 'Lesson 8.1: The Document Object Model (DOM) Tree & Node Interface', 'Prerequisites: Phase 0, Phase 1', 'Prerequisites: Phase 0, Phase 1 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 50.0, '# Lesson 6.1: The Document Object Model (DOM) Tree & Node Interface

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 1
- **Subtopics**:
  - `6.1.1` HTML parsing tokenization and DOM tree construction algorithms
  - `6.1.2` Node interface hierarchy: Document, Element, CharacterData, and Text nodes
  - `6.1.3` Live NodeLists versus static NodeLists: querySelectorAll vs getElementsByTagName memory implications
  - `6.1.4` DOM mutation operations: DocumentFragment, createElement, appendChild, and batch tree insertions
  - `6.1.5` The Shadow DOM boundary: ShadowRoot, open vs closed encapsulation modes, and slot distribution
  - `6.1.6` DOM traversal performance: TreeWalker vs NodeIterator memory benchmarks
- **Key Failure Modes & Edge Cases**: Mutating live NodeLists inside for-loops causing infinite re-indexing; excessive reflows from incremental appendChild calls.
- **Verification & Mastery Check**: Implement an in-memory Virtual-to-Real DOM batch mounting engine using DocumentFragment; verify 10,000 node render under 16ms.
- **Project Application**: CompKit: Core DOM rendering abstraction layer.', '{"solution.py": "# Phase 6 // Lesson 6.1: The Document Object Model (DOM) Tree & Node Interface\n\ndef solve():\n    \"\"\"\n    Verification: Implement an in-memory Virtual-to-Real DOM batch mounting engine using DocumentFragment; verify 10,0\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.1", "subtopics_count": 6, "verification_criteria": "Implement an in-memory Virtual-to-Real DOM batch mounting engine using DocumentFragment; verify 10,000 node render under 16ms.", "subtopics": ["6.1.1 HTML parsing tokenization and DOM tree construction algorithms", "6.1.2 Node interface hierarchy: Document, Element, CharacterData, and Text nodes", "6.1.3 Live NodeLists versus static NodeLists: querySelectorAll vs getElementsByTagName memory implications", "6.1.4 DOM mutation operations: DocumentFragment, createElement, appendChild, and batch tree insertions", "6.1.5 The Shadow DOM boundary: ShadowRoot, open vs closed encapsulation modes, and slot distribution", "6.1.6 DOM traversal performance: TreeWalker vs NodeIterator memory benchmarks"]}'::jsonb, '["Explain how this implementation prevents: Mutating live NodeLists inside for-loops causing infinite re-indexing; excessive reflows from incremental appendChild ca", "How does The Document Object Model (DOM) Tree & Node Interface scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-2', 'phase-06-lesson-02-browser-event-dispatch-loop-event-archite', 'module-8', 2, 'Lesson 8.2: Browser Event Dispatch Loop & Event Architecture', 'Prerequisites: Lesson 6.1', 'Prerequisites: Lesson 6.1 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 100.0, '# Lesson 6.2: Browser Event Dispatch Loop & Event Architecture

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.1
- **Subtopics**:
  - `6.2.1` Event flow phases: capturing phase, target phase, and bubbling phase
  - `6.2.2` Synthetic vs native Event objects: bubbles, cancelable, composed, and defaultPrevented properties
  - `6.2.3` Event delegation patterns: handling dynamic children with matching selectors and memory minimization
  - `6.2.4` Event cancellation semantics: stopPropagation vs stopImmediatePropagation vs preventDefault
  - `6.2.5` Passive event listeners: optimizing touch and wheel scroll performance by unblocking compositor threads
  - `6.2.6` CustomEvent dispatching and inter-component decoupled bus architectures
- **Key Failure Modes & Edge Cases**: Calling stopPropagation breaking analytics tracking scripts; scroll jank caused by non-passive touchmove listeners.
- **Verification & Mastery Check**: Write an event delegation manager handling nested dynamic elements with capture-phase boundary interceptors.
- **Project Application**: CompKit: Headless accessible interactive component dispatchers.', '{"solution.py": "# Phase 6 // Lesson 6.2: Browser Event Dispatch Loop & Event Architecture\n\ndef solve():\n    \"\"\"\n    Verification: Write an event delegation manager handling nested dynamic elements with capture-phase boundary inter\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.2", "subtopics_count": 6, "verification_criteria": "Write an event delegation manager handling nested dynamic elements with capture-phase boundary interceptors.", "subtopics": ["6.2.1 Event flow phases: capturing phase, target phase, and bubbling phase", "6.2.2 Synthetic vs native Event objects: bubbles, cancelable, composed, and defaultPrevented properties", "6.2.3 Event delegation patterns: handling dynamic children with matching selectors and memory minimization", "6.2.4 Event cancellation semantics: stopPropagation vs stopImmediatePropagation vs preventDefault", "6.2.5 Passive event listeners: optimizing touch and wheel scroll performance by unblocking compositor threads", "6.2.6 CustomEvent dispatching and inter-component decoupled bus architectures"]}'::jsonb, '["Explain how this implementation prevents: Calling stopPropagation breaking analytics tracking scripts; scroll jank caused by non-passive touchmove listeners.", "How does Browser Event Dispatch Loop & Event Architecture scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-3', 'phase-06-lesson-03-html5-semantic-architecture-structured-do', 'module-8', 3, 'Lesson 8.3: HTML5 Semantic Architecture & Structured Document Outlines', 'Prerequisites: Lesson 6.1', 'Prerequisites: Lesson 6.1 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 150.0, '# Lesson 6.3: HTML5 Semantic Architecture & Structured Document Outlines

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.1
- **Subtopics**:
  - `6.3.1` Semantic elements vs generic containers: header, nav, main, article, section, aside, footer
  - `6.3.2` Heading levels (h1-h6) and document outline algorithms in modern search and accessibility engines
  - `6.3.3` HTML forms specification: form controls, formnovalidate, enctype, autocomplete attributes, and fieldsets
  - `6.3.4` Embedded media elements: picture element with art direction media queries and source srcset fallbacks
  - `6.3.5` Dialog element lifecycle: show(), showModal(), top-layer positioning, and backdrop pseudo-elements
  - `6.3.6` Microdata and JSON-LD schema integration for rich machine-readable metadata
- **Key Failure Modes & Edge Cases**: Using multiple h1 elements haphazardly destroying accessibility tree outlines; unclosed modal dialogs trapping focus.
- **Verification & Mastery Check**: Build a zero-JS accessible modal dialog and form submission pipeline validating native constraint validation API.
- **Project Application**: TenantIQ: Public onboarding landing pages and registration forms.', '{"solution.py": "# Phase 6 // Lesson 6.3: HTML5 Semantic Architecture & Structured Document Outlines\n\ndef solve():\n    \"\"\"\n    Verification: Build a zero-JS accessible modal dialog and form submission pipeline validating native constraint va\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.3", "subtopics_count": 6, "verification_criteria": "Build a zero-JS accessible modal dialog and form submission pipeline validating native constraint validation API.", "subtopics": ["6.3.1 Semantic elements vs generic containers: header, nav, main, article, section, aside, footer", "6.3.2 Heading levels (h1-h6) and document outline algorithms in modern search and accessibility engines", "6.3.3 HTML forms specification: form controls, formnovalidate, enctype, autocomplete attributes, and fieldsets", "6.3.4 Embedded media elements: picture element with art direction media queries and source srcset fallbacks", "6.3.5 Dialog element lifecycle: show(), showModal(), top-layer positioning, and backdrop pseudo-elements", "6.3.6 Microdata and JSON-LD schema integration for rich machine-readable metadata"]}'::jsonb, '["Explain how this implementation prevents: Using multiple h1 elements haphazardly destroying accessibility tree outlines; unclosed modal dialogs trapping focus.", "How does HTML5 Semantic Architecture & Structured Document Outlines scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-4', 'phase-06-lesson-04-web-accessibility-a11y-wcag-2-2-aaa-the-a', 'module-8', 4, 'Lesson 8.4: Web Accessibility (a11y), WCAG 2.2 AAA & The Accessibility Tree', 'Prerequisites: Lesson 6.2, Lesson 6.3', 'Prerequisites: Lesson 6.2, Lesson 6.3 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 200.0, '# Lesson 6.4: Web Accessibility (a11y), WCAG 2.2 AAA & The Accessibility Tree

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.2, Lesson 6.3
- **Subtopics**:
  - `6.4.1` How browsers transform the DOM tree into the platform-specific Accessibility Tree (AOM)
  - `6.4.2` ARIA roles, states, and properties: role landmark usage, aria-expanded, aria-controls, aria-live regions
  - `6.4.3` Keyboard accessibility: tabindex rules (0 vs -1 vs positive integers), keyboard focus traps, and roaming tabindex
  - `6.4.4` Color contrast ratios: WCAG 2.2 AA (4.5:1) vs AAA (7:1) mathematical luminance formulas
  - `6.4.5` Screen reader interaction paradigms: NVDA, VoiceOver rotor navigation, and virtual cursor modes
  - `6.4.6` Automated auditing integration with axe-core and Pa11y in CI/CD test suites
- **Key Failure Modes & Edge Cases**: Overusing ARIA attributes (first rule of ARIA: don''t use ARIA if native HTML exists); broken keyboard focus traps.
- **Verification & Mastery Check**: Audit and refactor an inaccessible combobox component to pass WCAG 2.2 AAA compliance with full keyboard navigation.
- **Project Application**: CompKit: Fully accessible headless combobox and modal components.', '{"solution.py": "# Phase 6 // Lesson 6.4: Web Accessibility (a11y), WCAG 2.2 AAA & The Accessibility Tree\n\ndef solve():\n    \"\"\"\n    Verification: Audit and refactor an inaccessible combobox component to pass WCAG 2.2 AAA compliance with full keyb\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.4", "subtopics_count": 6, "verification_criteria": "Audit and refactor an inaccessible combobox component to pass WCAG 2.2 AAA compliance with full keyboard navigation.", "subtopics": ["6.4.1 How browsers transform the DOM tree into the platform-specific Accessibility Tree (AOM)", "6.4.2 ARIA roles, states, and properties: role landmark usage, aria-expanded, aria-controls, aria-live regions", "6.4.3 Keyboard accessibility: tabindex rules (0 vs -1 vs positive integers), keyboard focus traps, and roaming tabindex", "6.4.4 Color contrast ratios: WCAG 2.2 AA (4.5:1) vs AAA (7:1) mathematical luminance formulas", "6.4.5 Screen reader interaction paradigms: NVDA, VoiceOver rotor navigation, and virtual cursor modes", "6.4.6 Automated auditing integration with axe-core and Pa11y in CI/CD test suites"]}'::jsonb, '["Explain how this implementation prevents: Overusing ARIA attributes (first rule of ARIA: don''t use ARIA if native HTML exists); broken keyboard focus traps.", "How does Web Accessibility (a11y), WCAG 2.2 AAA & The Accessibility Tree scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-5', 'phase-06-lesson-05-browser-storage-systems-quotas-eviction-p', 'module-8', 5, 'Lesson 8.5: Browser Storage Systems, Quotas & Eviction Policies', 'Prerequisites: Phase 0, Lesson 6.1', 'Prerequisites: Phase 0, Lesson 6.1 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 250.0, '# Lesson 6.5: Browser Storage Systems, Quotas & Eviction Policies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 6.1
- **Subtopics**:
  - `6.5.1` Storage comparison: Cookies, Web Storage (localStorage/sessionStorage), IndexedDB, and Cache API
  - `6.5.2` Storage quotas and eviction priorities: best-effort vs persistent storage requests (navigator.storage.persist)
  - `6.5.3` IndexedDB architecture: Object stores, primary keys, key paths, auto-increment, and index cursors
  - `6.5.4` IndexedDB transaction lifecycles: readonly vs readwrite, auto-commit behavior, and error handling
  - `6.5.5` Client-side database versioning and onupgradeneeded schema migration pipelines
  - `6.5.6` Storage security: Same-Origin Policy enforcement, path isolation, and encryption of sensitive tokens at rest
- **Key Failure Modes & Edge Cases**: Blocking main thread with synchronous localStorage reads of multi-megabyte JSON; unhandled IndexedDB VersionError.
- **Verification & Mastery Check**: Build a robust IndexedDB wrapper supporting promise-based transactions, secondary indexing, and automatic migrations.
- **Project Application**: TenantIQ: Client-side offline cache for multi-tenant draft documents.', '{"solution.py": "# Phase 6 // Lesson 6.5: Browser Storage Systems, Quotas & Eviction Policies\n\ndef solve():\n    \"\"\"\n    Verification: Build a robust IndexedDB wrapper supporting promise-based transactions, secondary indexing, and auto\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.5", "subtopics_count": 6, "verification_criteria": "Build a robust IndexedDB wrapper supporting promise-based transactions, secondary indexing, and automatic migrations.", "subtopics": ["6.5.1 Storage comparison: Cookies, Web Storage (localStorage/sessionStorage), IndexedDB, and Cache API", "6.5.2 Storage quotas and eviction priorities: best-effort vs persistent storage requests (navigator.storage.persist)", "6.5.3 IndexedDB architecture: Object stores, primary keys, key paths, auto-increment, and index cursors", "6.5.4 IndexedDB transaction lifecycles: readonly vs readwrite, auto-commit behavior, and error handling", "6.5.5 Client-side database versioning and onupgradeneeded schema migration pipelines", "6.5.6 Storage security: Same-Origin Policy enforcement, path isolation, and encryption of sensitive tokens at rest"]}'::jsonb, '["Explain how this implementation prevents: Blocking main thread with synchronous localStorage reads of multi-megabyte JSON; unhandled IndexedDB VersionError.", "How does Browser Storage Systems, Quotas & Eviction Policies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-6', 'phase-06-lesson-06-web-security-fundamentals-sop-cors-csp-co', 'module-8', 6, 'Lesson 8.6: Web Security Fundamentals: SOP, CORS, CSP & Cookies', 'Prerequisites: Phase 4, Lesson 6.5', 'Prerequisites: Phase 4, Lesson 6.5 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 300.0, '# Lesson 6.6: Web Security Fundamentals: SOP, CORS, CSP & Cookies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 6.5
- **Subtopics**:
  - `6.6.1` Same-Origin Policy (SOP) deep dive: protocol, host, and port matching boundaries
  - `6.6.2` Cross-Origin Resource Sharing (CORS): preflight OPTIONS requests, allowed headers, credentials, and wildcard perils
  - `6.6.3` Content Security Policy (CSP Level 3): script-src, style-src, nonce-based script whitelisting, and report-uri
  - `6.6.4` Cross-Site Scripting (XSS) prevention: stored, reflected, and DOM-based XSS vectors and sanitization (DOMPurify)
  - `6.6.5` Cross-Site Request Forgery (CSRF): anti-CSRF token verification vs SameSite cookie attributes (Strict vs Lax)
  - `6.6.6` Cookie security flags: Secure, HttpOnly, SameSite, Domain scoping, and Path isolation
- **Key Failure Modes & Edge Cases**: Misconfiguring Access-Control-Allow-Origin to ''*'' with Allow-Credentials true; naive innerHTML usage exposing XSS.
- **Verification & Mastery Check**: Construct an impenetrable CSP header policy and verify zero-vulnerability execution under automated XSS payload suites.
- **Project Application**: TenantIQ: Security policy headers and authentication session cookie management.', '{"solution.py": "# Phase 6 // Lesson 6.6: Web Security Fundamentals: SOP, CORS, CSP & Cookies\n\ndef solve():\n    \"\"\"\n    Verification: Construct an impenetrable CSP header policy and verify zero-vulnerability execution under automated \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.6", "subtopics_count": 6, "verification_criteria": "Construct an impenetrable CSP header policy and verify zero-vulnerability execution under automated XSS payload suites.", "subtopics": ["6.6.1 Same-Origin Policy (SOP) deep dive: protocol, host, and port matching boundaries", "6.6.2 Cross-Origin Resource Sharing (CORS): preflight OPTIONS requests, allowed headers, credentials, and wildcard perils", "6.6.3 Content Security Policy (CSP Level 3): script-src, style-src, nonce-based script whitelisting, and report-uri", "6.6.4 Cross-Site Scripting (XSS) prevention: stored, reflected, and DOM-based XSS vectors and sanitization (DOMPurify)", "6.6.5 Cross-Site Request Forgery (CSRF): anti-CSRF token verification vs SameSite cookie attributes (Strict vs Lax)", "6.6.6 Cookie security flags: Secure, HttpOnly, SameSite, Domain scoping, and Path isolation"]}'::jsonb, '["Explain how this implementation prevents: Misconfiguring Access-Control-Allow-Origin to ''*'' with Allow-Credentials true; naive innerHTML usage exposing XSS.", "How does Web Security Fundamentals: SOP, CORS, CSP & Cookies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-7', 'phase-06-lesson-07-css-box-model-formatting-contexts-collaps', 'module-8', 7, 'Lesson 8.7: CSS Box Model, Formatting Contexts & Collapsing Margins', 'Prerequisites: Lesson 6.1', 'Prerequisites: Lesson 6.1 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 350.0, '# Lesson 6.7: CSS Box Model, Formatting Contexts & Collapsing Margins

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.1
- **Subtopics**:
  - `6.7.1` Box model mechanics: content-box vs border-box sizing calculations and margin/padding arithmetic
  - `6.7.2` Block Formatting Context (BFC) creation triggers: overflow != visible, display: flow-root, flex/grid containers
  - `6.7.3` Vertical margin collapsing rules: parent-child collapsing, sibling collapsing, and empty block collapsing triggers
  - `6.7.4` Inline formatting contexts: baseline alignment, line-height calculations, and strut sizing
  - `6.7.5` CSS visual formatting model: normal flow, out-of-flow positioning (relative, absolute, fixed, sticky)
  - `6.7.6` Stacking contexts and z-index arithmetic: opacity, transform, filter, and will-change side effects on stacking
- **Key Failure Modes & Edge Cases**: Unintended margin collapse breaking grid layouts; z-index battles caused by misunderstanding parent stacking contexts.
- **Verification & Mastery Check**: Construct a diagnostic test suite demonstrating margin collapsing mitigation using `display: flow-root` across 10 edge cases.
- **Project Application**: CompKit: Foundational layout primitives and container boxes.', '{"solution.py": "# Phase 6 // Lesson 6.7: CSS Box Model, Formatting Contexts & Collapsing Margins\n\ndef solve():\n    \"\"\"\n    Verification: Construct a diagnostic test suite demonstrating margin collapsing mitigation using `display: flow-ro\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.7", "subtopics_count": 6, "verification_criteria": "Construct a diagnostic test suite demonstrating margin collapsing mitigation using `display: flow-root` across 10 edge cases.", "subtopics": ["6.7.1 Box model mechanics: content-box vs border-box sizing calculations and margin/padding arithmetic", "6.7.2 Block Formatting Context (BFC) creation triggers: overflow != visible, display: flow-root, flex/grid containers", "6.7.3 Vertical margin collapsing rules: parent-child collapsing, sibling collapsing, and empty block collapsing triggers", "6.7.4 Inline formatting contexts: baseline alignment, line-height calculations, and strut sizing", "6.7.5 CSS visual formatting model: normal flow, out-of-flow positioning (relative, absolute, fixed, sticky)", "6.7.6 Stacking contexts and z-index arithmetic: opacity, transform, filter, and will-change side effects on stacking"]}'::jsonb, '["Explain how this implementation prevents: Unintended margin collapse breaking grid layouts; z-index battles caused by misunderstanding parent stacking contexts.", "How does CSS Box Model, Formatting Contexts & Collapsing Margins scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-8', 'phase-06-lesson-08-css-layout-engine-i-flexbox-internal-mech', 'module-8', 8, 'Lesson 8.8: CSS Layout Engine I: Flexbox Internal Mechanics & Algorithms', 'Prerequisites: Lesson 6.7', 'Prerequisites: Lesson 6.7 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 400.0, '# Lesson 6.8: CSS Layout Engine I: Flexbox Internal Mechanics & Algorithms

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.7
- **Subtopics**:
  - `6.8.1` Flex container vs flex item properties: main axis vs cross axis spatial coordinate systems
  - `6.8.2` Flex sizing algorithm: flex-basis resolution, flex-grow expansion factor, and flex-shrink contraction arithmetic
  - `6.8.3` Negative space distribution calculations during flex item shrinking and min-content constraints
  - `6.8.4` Cross axis alignment algorithms: align-items, align-self, and align-content multi-line distribution
  - `6.8.5` Flex item wrapping behavior: flex-wrap, row-gap/column-gap distribution, and reordering with `order`
  - `6.8.6` Flexbox accessibility pitfalls: visual order disruption relative to DOM document order
- **Key Failure Modes & Edge Cases**: Items overflowing containers due to default min-width: auto overriding flex-shrink; visual reading order diverging from screen reader flow.
- **Verification & Mastery Check**: Build a responsive navigation header and sidebar system with pure flexbox without hardcoded pixel widths.
- **Project Application**: CompKit: App shell layout and responsive navigation bar.', '{"solution.py": "# Phase 6 // Lesson 6.8: CSS Layout Engine I: Flexbox Internal Mechanics & Algorithms\n\ndef solve():\n    \"\"\"\n    Verification: Build a responsive navigation header and sidebar system with pure flexbox without hardcoded pixel wi\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.8", "subtopics_count": 6, "verification_criteria": "Build a responsive navigation header and sidebar system with pure flexbox without hardcoded pixel widths.", "subtopics": ["6.8.1 Flex container vs flex item properties: main axis vs cross axis spatial coordinate systems", "6.8.2 Flex sizing algorithm: flex-basis resolution, flex-grow expansion factor, and flex-shrink contraction arithmetic", "6.8.3 Negative space distribution calculations during flex item shrinking and min-content constraints", "6.8.4 Cross axis alignment algorithms: align-items, align-self, and align-content multi-line distribution", "6.8.5 Flex item wrapping behavior: flex-wrap, row-gap/column-gap distribution, and reordering with `order`", "6.8.6 Flexbox accessibility pitfalls: visual order disruption relative to DOM document order"]}'::jsonb, '["Explain how this implementation prevents: Items overflowing containers due to default min-width: auto overriding flex-shrink; visual reading order diverging from ", "How does CSS Layout Engine I: Flexbox Internal Mechanics & Algorithms scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-9', 'phase-06-lesson-09-css-layout-engine-ii-css-grid-sizing-temp', 'module-8', 9, 'Lesson 8.9: CSS Layout Engine II: CSS Grid Sizing, Templates & Algorithms', 'Prerequisites: Lesson 6.8', 'Prerequisites: Lesson 6.8 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 450.0, '# Lesson 6.9: CSS Layout Engine II: CSS Grid Sizing, Templates & Algorithms

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.8
- **Subtopics**:
  - `6.9.1` Grid tracks, lines, cells, and grid areas: explicit grid vs implicit grid generation
  - `6.9.2` Track sizing functions: fr units, percentages, minmax(), fit-content(), and auto resolution algorithms
  - `6.9.3` Auto-placement algorithm: sparse vs dense packing modes and grid-auto-flow mechanics
  - `6.9.4` Subgrid specification: inheriting row and column track sizing from parent grid contexts
  - `6.9.5` Named grid lines and grid-template-areas for complex multi-column responsive dashboard layouts
  - `6.9.6` Grid alignment and justify/align properties along inline and block coordinate axes
- **Key Failure Modes & Edge Cases**: Subgrid rendering glitches in legacy engines; accidental creation of millions of implicit tracks causing browser hangs.
- **Verification & Mastery Check**: Create a complex SaaS dashboard grid with sticky headers, collapsible sidebars, and subgrid card alignments.
- **Project Application**: TenantIQ: Multi-tenant analytics dashboard layout.', '{"solution.py": "# Phase 6 // Lesson 6.9: CSS Layout Engine II: CSS Grid Sizing, Templates & Algorithms\n\ndef solve():\n    \"\"\"\n    Verification: Create a complex SaaS dashboard grid with sticky headers, collapsible sidebars, and subgrid card ali\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.9", "subtopics_count": 6, "verification_criteria": "Create a complex SaaS dashboard grid with sticky headers, collapsible sidebars, and subgrid card alignments.", "subtopics": ["6.9.1 Grid tracks, lines, cells, and grid areas: explicit grid vs implicit grid generation", "6.9.2 Track sizing functions: fr units, percentages, minmax(), fit-content(), and auto resolution algorithms", "6.9.3 Auto-placement algorithm: sparse vs dense packing modes and grid-auto-flow mechanics", "6.9.4 Subgrid specification: inheriting row and column track sizing from parent grid contexts", "6.9.5 Named grid lines and grid-template-areas for complex multi-column responsive dashboard layouts", "6.9.6 Grid alignment and justify/align properties along inline and block coordinate axes"]}'::jsonb, '["Explain how this implementation prevents: Subgrid rendering glitches in legacy engines; accidental creation of millions of implicit tracks causing browser hangs.", "How does CSS Layout Engine II: CSS Grid Sizing, Templates & Algorithms scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-10', 'phase-06-lesson-10-css-specificity-cascade-layers-layer-inhe', 'module-8', 10, 'Lesson 8.10: CSS Specificity, Cascade Layers (@layer) & Inheritance', 'Prerequisites: Lesson 6.7', 'Prerequisites: Lesson 6.7 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 500.0, '# Lesson 6.10: CSS Specificity, Cascade Layers (@layer) & Inheritance

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.7
- **Subtopics**:
  - `6.10.1` The CSS Cascade algorithm: Importance (!important), Origin (User Agent, User, Author), Specificity, Order of Appearance
  - `6.10.2` Specificity calculation vectors: (Inline, IDs, Classes/Attributes/Pseudo-classes, Elements/Pseudo-elements)
  - `6.10.3` The :is(), :where(), and :has() relational selector specificity rules (0 specificity for :where)
  - `6.10.4` CSS Cascade Layers (@layer): defining explicit layer priority, unlayered style precedence, and layer reordering
  - `6.10.5` Inherited properties vs non-inherited properties: currentColor, inherit, initial, unset, and revert keywords
  - `6.10.6` Scoped CSS architectures: BEM methodology vs CSS Modules vs Scoped Shadow DOM
- **Key Failure Modes & Edge Cases**: Uncontrollable specificity inflation through deep nesting; !important wars between design system and application overrides.
- **Verification & Mastery Check**: Refactor an unlayered monolithic stylesheet into cleanly prioritized `@layer reset, base, components, utilities`.
- **Project Application**: CompKit: Modular CSS architecture with explicit cascade layers.', '{"solution.py": "# Phase 6 // Lesson 6.10: CSS Specificity, Cascade Layers (@layer) & Inheritance\n\ndef solve():\n    \"\"\"\n    Verification: Refactor an unlayered monolithic stylesheet into cleanly prioritized `@layer reset, base, components\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.10", "subtopics_count": 6, "verification_criteria": "Refactor an unlayered monolithic stylesheet into cleanly prioritized `@layer reset, base, components, utilities`.", "subtopics": ["6.10.1 The CSS Cascade algorithm: Importance (!important), Origin (User Agent, User, Author), Specificity, Order of Appearance", "6.10.2 Specificity calculation vectors: (Inline, IDs, Classes/Attributes/Pseudo-classes, Elements/Pseudo-elements)", "6.10.3 The :is(), :where(), and :has() relational selector specificity rules (0 specificity for :where)", "6.10.4 CSS Cascade Layers (@layer): defining explicit layer priority, unlayered style precedence, and layer reordering", "6.10.5 Inherited properties vs non-inherited properties: currentColor, inherit, initial, unset, and revert keywords", "6.10.6 Scoped CSS architectures: BEM methodology vs CSS Modules vs Scoped Shadow DOM"]}'::jsonb, '["Explain how this implementation prevents: Uncontrollable specificity inflation through deep nesting; !important wars between design system and application overrid", "How does CSS Specificity, Cascade Layers (@layer) & Inheritance scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-11', 'phase-06-lesson-11-modern-css-container-queries-custom-prope', 'module-8', 11, 'Lesson 8.11: Modern CSS: Container Queries, Custom Properties & Math Functions', 'Prerequisites: Lesson 6.10', 'Prerequisites: Lesson 6.10 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 550.0, '# Lesson 6.11: Modern CSS: Container Queries, Custom Properties & Math Functions

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.10
- **Subtopics**:
  - `6.11.1` Container queries: container-type (inline-size, size), container-name, and @container rule matching
  - `6.11.2` Container query units: cqw, cqh, cqi, cqb, and responsive component self-adaptation independent of viewport
  - `6.11.3` CSS Custom Properties (CSS variables): inheritance, fallback values, and dynamic runtime manipulation via JavaScript
  - `6.11.4` Advanced CSS math functions: clamp(), min(), max(), round(), mod(), rem(), and calc() nesting
  - `6.11.5` The relational pseudo-class `:has()`: parent selection, previous sibling styling, and state-driven styling without JS
  - `6.11.6` Color manipulation: color-mix(), relative color syntax (e.g. `rgb(from var(--primary) r g b / 0.5)`), and OKLCH color space
- **Key Failure Modes & Edge Cases**: Infinite layout loops caused by container queries modifying container inline-size; invalid custom property fallback cascading.
- **Verification & Mastery Check**: Develop a card component that automatically restyles from vertical list to horizontal multi-column layout based on container width.
- **Project Application**: CompKit: Responsive container-adaptive UI widgets.', '{"solution.py": "# Phase 6 // Lesson 6.11: Modern CSS: Container Queries, Custom Properties & Math Functions\n\ndef solve():\n    \"\"\"\n    Verification: Develop a card component that automatically restyles from vertical list to horizontal multi-column l\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.11", "subtopics_count": 6, "verification_criteria": "Develop a card component that automatically restyles from vertical list to horizontal multi-column layout based on container width.", "subtopics": ["6.11.1 Container queries: container-type (inline-size, size), container-name, and @container rule matching", "6.11.2 Container query units: cqw, cqh, cqi, cqb, and responsive component self-adaptation independent of viewport", "6.11.3 CSS Custom Properties (CSS variables): inheritance, fallback values, and dynamic runtime manipulation via JavaScript", "6.11.4 Advanced CSS math functions: clamp(), min(), max(), round(), mod(), rem(), and calc() nesting", "6.11.5 The relational pseudo-class `:has()`: parent selection, previous sibling styling, and state-driven styling without JS", "6.11.6 Color manipulation: color-mix(), relative color syntax (e.g. `rgb(from var(--primary) r g b / 0.5)`), and OKLCH color space"]}'::jsonb, '["Explain how this implementation prevents: Infinite layout loops caused by container queries modifying container inline-size; invalid custom property fallback casc", "How does Modern CSS: Container Queries, Custom Properties & Math Functions scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-12', 'phase-06-lesson-12-css-transitions-animations-compositor-dri', 'module-8', 12, 'Lesson 8.12: CSS Transitions, Animations & Compositor-Driven Performance', 'Prerequisites: Phase 0, Lesson 6.7', 'Prerequisites: Phase 0, Lesson 6.7 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 600.0, '# Lesson 6.12: CSS Transitions, Animations & Compositor-Driven Performance

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 6.7
- **Subtopics**:
  - `6.12.1` CSS transitions: transition-property, transition-duration, timing-functions (cubic-bezier), and transition-delay
  - `6.12.2` CSS keyframe animations: animation lifecycle, fill-modes (forwards, backwards, both), and animation-play-state
  - `6.12.3` Hardware acceleration: offloading animations to GPU compositor threads using `transform` and `opacity`
  - `6.12.4` The `will-change` property: proactive compositor layer promotion and catastrophic memory leak pitfalls
  - `6.12.5` View Transitions API: page-level and element-level seamless state transitions with `document.startViewTransition`
  - `6.12.6` User preferences: @media (prefers-reduced-motion: reduce) and accessible animation cancellation patterns
- **Key Failure Modes & Edge Cases**: Animating `width`, `height`, or `top` triggering layout thrashing and 15fps jank; overusing will-change blowing GPU memory.
- **Verification & Mastery Check**: Build a 60fps smooth drawer and toast notification system animated strictly via compositor-promoted properties.
- **Project Application**: CompKit: Micro-animations and drawer transitions.', '{"solution.py": "# Phase 6 // Lesson 6.12: CSS Transitions, Animations & Compositor-Driven Performance\n\ndef solve():\n    \"\"\"\n    Verification: Build a 60fps smooth drawer and toast notification system animated strictly via compositor-promoted \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.12", "subtopics_count": 6, "verification_criteria": "Build a 60fps smooth drawer and toast notification system animated strictly via compositor-promoted properties.", "subtopics": ["6.12.1 CSS transitions: transition-property, transition-duration, timing-functions (cubic-bezier), and transition-delay", "6.12.2 CSS keyframe animations: animation lifecycle, fill-modes (forwards, backwards, both), and animation-play-state", "6.12.3 Hardware acceleration: offloading animations to GPU compositor threads using `transform` and `opacity`", "6.12.4 The `will-change` property: proactive compositor layer promotion and catastrophic memory leak pitfalls", "6.12.5 View Transitions API: page-level and element-level seamless state transitions with `document.startViewTransition`", "6.12.6 User preferences: @media (prefers-reduced-motion: reduce) and accessible animation cancellation patterns"]}'::jsonb, '["Explain how this implementation prevents: Animating `width`, `height`, or `top` triggering layout thrashing and 15fps jank; overusing will-change blowing GPU memo", "How does CSS Transitions, Animations & Compositor-Driven Performance scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-13', 'phase-06-lesson-13-browser-rendering-pipeline-parse-style-la', 'module-8', 13, 'Lesson 8.13: Browser Rendering Pipeline: Parse, Style, Layout, Paint & Composite', 'Prerequisites: Phase 0, Lesson 6.12', 'Prerequisites: Phase 0, Lesson 6.12 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 650.0, '# Lesson 6.13: Browser Rendering Pipeline: Parse, Style, Layout, Paint & Composite

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 6.12
- **Subtopics**:
  - `6.13.1` The Critical Rendering Path (CRP): HTML tokenization, DOM creation, CSSOM creation, and Render Tree construction
  - `6.13.2` Layout phase (Reflow): geometry calculations, box coordinate computation, and recursive dirty-subtree passes
  - `6.13.3` Paint phase: rasterization, converting vector rendering commands into bitmap pixel buffers in memory
  - `6.13.4` Compositing phase: dividing page into GPU layers, tiling, and compositing layers via compositor threads
  - `6.13.5` Layout Thrashing: forced synchronous layouts caused by interleaving DOM writes with geometry reads (offsetHeight)
  - `6.13.6` Using Chrome DevTools Performance panel: recording timeline traces, identifying long frames, and raster bottlenecks
- **Key Failure Modes & Edge Cases**: Forced synchronous layouts inside loops causing catastrophic UI freezing; unexpected layer explosions crashing mobile browsers.
- **Verification & Mastery Check**: Profile an unoptimized rendering script; eliminate forced reflows by decoupling DOM read/write phases via requestAnimationFrame.
- **Project Application**: CompKit: Layout engine benchmarks and zero-thrash DOM utilities.', '{"solution.py": "# Phase 6 // Lesson 6.13: Browser Rendering Pipeline: Parse, Style, Layout, Paint & Composite\n\ndef solve():\n    \"\"\"\n    Verification: Profile an unoptimized rendering script; eliminate forced reflows by decoupling DOM read/write phase\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.13", "subtopics_count": 6, "verification_criteria": "Profile an unoptimized rendering script; eliminate forced reflows by decoupling DOM read/write phases via requestAnimationFrame.", "subtopics": ["6.13.1 The Critical Rendering Path (CRP): HTML tokenization, DOM creation, CSSOM creation, and Render Tree construction", "6.13.2 Layout phase (Reflow): geometry calculations, box coordinate computation, and recursive dirty-subtree passes", "6.13.3 Paint phase: rasterization, converting vector rendering commands into bitmap pixel buffers in memory", "6.13.4 Compositing phase: dividing page into GPU layers, tiling, and compositing layers via compositor threads", "6.13.5 Layout Thrashing: forced synchronous layouts caused by interleaving DOM writes with geometry reads (offsetHeight)", "6.13.6 Using Chrome DevTools Performance panel: recording timeline traces, identifying long frames, and raster bottlenecks"]}'::jsonb, '["Explain how this implementation prevents: Forced synchronous layouts inside loops causing catastrophic UI freezing; unexpected layer explosions crashing mobile br", "How does Browser Rendering Pipeline: Parse, Style, Layout, Paint & Composite scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-14', 'phase-06-lesson-14-browser-networking-http-2-http-3-fetch-ap', 'module-8', 14, 'Lesson 8.14: Browser Networking: HTTP/2, HTTP/3, Fetch API & Beacon', 'Prerequisites: Phase 4, Lesson 6.13', 'Prerequisites: Phase 4, Lesson 6.13 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 700.0, '# Lesson 6.14: Browser Networking: HTTP/2, HTTP/3, Fetch API & Beacon

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 6.13
- **Subtopics**:
  - `6.14.1` HTTP/2 multiplexing vs HTTP/1.1 head-of-line blocking: stream prioritization and header compression (HPACK)
  - `6.14.2` HTTP/3 and QUIC: UDP-based transport, 0-RTT handshakes, and packet loss independence
  - `6.14.3` Fetch API deep dive: Request, Response, Headers objects, streaming response bodies with ReadableStream
  - `6.14.4` Request abort mechanics: AbortController, AbortSignal, timeout signals (AbortSignal.timeout), and cleanup
  - `6.14.5` navigator.sendBeacon vs fetch keepalive: guarantees for telemetry and analytics dispatch during page unload
  - `6.14.6` Resource hints: preload, prefetch, preconnect, dns-prefetch, and modulepreload semantics
- **Key Failure Modes & Edge Cases**: Memory leaks from un-aborted fetch requests on unmounted views; beacon calls dropped due to payload size limit (>64KB).
- **Verification & Mastery Check**: Construct a resilient HTTP client wrapper supporting automatic retries with exponential backoff, AbortSignal cancellation, and stream decoding.
- **Project Application**: TenantIQ: Telemetry and resilient API communication layer.', '{"solution.py": "# Phase 6 // Lesson 6.14: Browser Networking: HTTP/2, HTTP/3, Fetch API & Beacon\n\ndef solve():\n    \"\"\"\n    Verification: Construct a resilient HTTP client wrapper supporting automatic retries with exponential backoff, Abo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.14", "subtopics_count": 6, "verification_criteria": "Construct a resilient HTTP client wrapper supporting automatic retries with exponential backoff, AbortSignal cancellation, and stream decoding.", "subtopics": ["6.14.1 HTTP/2 multiplexing vs HTTP/1.1 head-of-line blocking: stream prioritization and header compression (HPACK)", "6.14.2 HTTP/3 and QUIC: UDP-based transport, 0-RTT handshakes, and packet loss independence", "6.14.3 Fetch API deep dive: Request, Response, Headers objects, streaming response bodies with ReadableStream", "6.14.4 Request abort mechanics: AbortController, AbortSignal, timeout signals (AbortSignal.timeout), and cleanup", "6.14.5 navigator.sendBeacon vs fetch keepalive: guarantees for telemetry and analytics dispatch during page unload", "6.14.6 Resource hints: preload, prefetch, preconnect, dns-prefetch, and modulepreload semantics"]}'::jsonb, '["Explain how this implementation prevents: Memory leaks from un-aborted fetch requests on unmounted views; beacon calls dropped due to payload size limit (>64KB).", "How does Browser Networking: HTTP/2, HTTP/3, Fetch API & Beacon scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-15', 'phase-06-lesson-15-browser-concurrency-web-workers-sharedwor', 'module-8', 15, 'Lesson 8.15: Browser Concurrency: Web Workers, SharedWorkers & Atomics', 'Prerequisites: Phase 0, Phase 4, Lesson 6.13', 'Prerequisites: Phase 0, Phase 4, Lesson 6.13 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 750.0, '# Lesson 6.15: Browser Concurrency: Web Workers, SharedWorkers & Atomics

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 4, Lesson 6.13
- **Subtopics**:
  - `6.15.1` Browser execution threads: main UI thread, worker threads, compositor threads, and network threads
  - `6.15.2` Dedicated Web Workers: instantiation, postMessage serialization, Structured Clone Algorithm, and terminate()
  - `6.15.3` SharedArrayBuffer and Atomics: lock-free shared memory synchronization, Atomics.wait(), and Atomics.notify()
  - `6.15.4` Cross-Origin Opener Policy (COOP) and Cross-Origin Embedder Policy (COEP) requirements for high-resolution timers
  - `6.15.5` SharedWorkers: multi-tab state coordination, shared WebSocket connections, and port communication lifecycles
  - `6.15.6` Service Workers introduction: registration, lifecycle events (install, activate, fetch), and offline asset caching
- **Key Failure Modes & Edge Cases**: Structured clone serialization overhead exceeding compute time; race conditions on SharedArrayBuffer without Atomics locks.
- **Verification & Mastery Check**: Offload heavy JSON data parsing and cryptographic hashing (100MB dataset) to a Web Worker, keeping main thread at 60fps.
- **Project Application**: TenantIQ: Background cryptographic tenant verification engine.', '{"solution.py": "# Phase 6 // Lesson 6.15: Browser Concurrency: Web Workers, SharedWorkers & Atomics\n\ndef solve():\n    \"\"\"\n    Verification: Offload heavy JSON data parsing and cryptographic hashing (100MB dataset) to a Web Worker, keeping m\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.15", "subtopics_count": 6, "verification_criteria": "Offload heavy JSON data parsing and cryptographic hashing (100MB dataset) to a Web Worker, keeping main thread at 60fps.", "subtopics": ["6.15.1 Browser execution threads: main UI thread, worker threads, compositor threads, and network threads", "6.15.2 Dedicated Web Workers: instantiation, postMessage serialization, Structured Clone Algorithm, and terminate()", "6.15.3 SharedArrayBuffer and Atomics: lock-free shared memory synchronization, Atomics.wait(), and Atomics.notify()", "6.15.4 Cross-Origin Opener Policy (COOP) and Cross-Origin Embedder Policy (COEP) requirements for high-resolution timers", "6.15.5 SharedWorkers: multi-tab state coordination, shared WebSocket connections, and port communication lifecycles", "6.15.6 Service Workers introduction: registration, lifecycle events (install, activate, fetch), and offline asset caching"]}'::jsonb, '["Explain how this implementation prevents: Structured clone serialization overhead exceeding compute time; race conditions on SharedArrayBuffer without Atomics loc", "How does Browser Concurrency: Web Workers, SharedWorkers & Atomics scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
