INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-14-11', 'phase-14-lesson-11-enterprise-capstone-xi-production-profili', 'module-14', 31, 'Lesson 14.31: Enterprise Capstone XI: Production Profiling & Performance Tuning', 'Prerequisites: Phase 11', 'Prerequisites: Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3620.0, 550.0, '# Lesson 14.11: Enterprise Capstone XI: Production Profiling & Performance Tuning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 11
- **Subtopics**:
  - `14.11.1` Profiling under load: identifying CPU and memory bottlenecks using `py-spy` and `memray` under sustained traffic
  - `14.11.2` Database query tuning: analyzing `pg_stat_statements`, eliminating slow sequential scans via optimized composite indexes
  - `14.11.3` Connection pool optimization: tuning PgBouncer transaction pooling to handle 5,000 concurrent client connections smoothly
  - `14.11.4` Memory leak elimination: locating and resolving reference cycles and uncollected buffers in background worker processes
  - `14.11.5` Kernel network tuning: applying Linux `sysctl` socket buffer and connection queue optimizations on worker nodes
  - `14.11.6` Performance validation: proving that API p99 latency decreased by $\ge 40\%$ and memory consumption dropped by $\ge 25\%$
- **Key Failure Modes & Edge Cases**: Premature optimization of non-critical code paths without empirical flame graph evidence of performance impact.
- **Verification & Mastery Check**: Profile the production system under load; eliminate the top 2 bottlenecks and document verified before/after flame graphs.
- **Project Application**: Enterprise Capstone: Performance audit report and optimization patches.', '{"solution.py": "# Phase 14 // Lesson 14.11: Enterprise Capstone XI: Production Profiling & Performance Tuning\n\ndef solve():\n    \"\"\"\n    Verification: Profile the production system under load; eliminate the top 2 bottlenecks and document verified befo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.11", "subtopics_count": 6, "verification_criteria": "Profile the production system under load; eliminate the top 2 bottlenecks and document verified before/after flame graphs.", "subtopics": ["14.11.1 Profiling under load: identifying CPU and memory bottlenecks using `py-spy` and `memray` under sustained traffic", "14.11.2 Database query tuning: analyzing `pg_stat_statements`, eliminating slow sequential scans via optimized composite indexes", "14.11.3 Connection pool optimization: tuning PgBouncer transaction pooling to handle 5,000 concurrent client connections smoothly", "14.11.4 Memory leak elimination: locating and resolving reference cycles and uncollected buffers in background worker processes", "14.11.5 Kernel network tuning: applying Linux `sysctl` socket buffer and connection queue optimizations on worker nodes", "14.11.6 Performance validation: proving that API p99 latency decreased by $\\ge 40\\%$ and memory consumption dropped by $\\ge 25\\%$"]}'::jsonb, '["Explain how this implementation prevents: Premature optimization of non-critical code paths without empirical flame graph evidence of performance impact.", "How does Enterprise Capstone XI: Production Profiling & Performance Tuning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-12', 'phase-14-lesson-12-enterprise-capstone-xii-high-concurrency-', 'module-14', 32, 'Lesson 14.32: Enterprise Capstone XII: High-Concurrency Load Testing with k6', 'Prerequisites: Phase 11', 'Prerequisites: Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3500.0, 600.0, '# Lesson 14.12: Enterprise Capstone XII: High-Concurrency Load Testing with k6

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 11
- **Subtopics**:
  - `14.12.1` Designing realistic load testing scenarios: modeling peak traffic spikes, diurnal user patterns, and concurrent agent runs
  - `14.12.2` Writing modular k6 test scripts: simulating 10,000 concurrent Virtual Users (VUs) executing mixed read/write/streaming flows
  - `14.12.3` Executing distributed stress testing: running distributed k6 load generators generating 25,000 requests/second
  - `14.12.4` SLA verification under load: asserting that error rate remains $<0.01\%$ and p95 latency remains $<200$ms under peak load
  - `14.12.5` Identifying breaking points: pushing system load beyond capacity until throughput plateaus and graceful load shedding engages
  - `14.12.6` Authoring the Load Test Verification Report: documenting system capacity limits, bottleneck analysis, and scaling recommendations
- **Key Failure Modes & Edge Cases**: Conducting load tests with static identical data payloads, triggering unrealistic 100% cache hit rates on all requests.
- **Verification & Mastery Check**: Execute a 25,000 QPS distributed k6 load test; verify that system maintains all SLA latency thresholds without crashing.
- **Project Application**: Enterprise Capstone: Comprehensive load testing report and k6 test suite.', '{"solution.py": "# Phase 14 // Lesson 14.12: Enterprise Capstone XII: High-Concurrency Load Testing with k6\n\ndef solve():\n    \"\"\"\n    Verification: Execute a 25,000 QPS distributed k6 load test; verify that system maintains all SLA latency threshol\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.12", "subtopics_count": 6, "verification_criteria": "Execute a 25,000 QPS distributed k6 load test; verify that system maintains all SLA latency thresholds without crashing.", "subtopics": ["14.12.1 Designing realistic load testing scenarios: modeling peak traffic spikes, diurnal user patterns, and concurrent agent runs", "14.12.2 Writing modular k6 test scripts: simulating 10,000 concurrent Virtual Users (VUs) executing mixed read/write/streaming flows", "14.12.3 Executing distributed stress testing: running distributed k6 load generators generating 25,000 requests/second", "14.12.4 SLA verification under load: asserting that error rate remains $<0.01\\%$ and p95 latency remains $<200$ms under peak load", "14.12.5 Identifying breaking points: pushing system load beyond capacity until throughput plateaus and graceful load shedding engages", "14.12.6 Authoring the Load Test Verification Report: documenting system capacity limits, bottleneck analysis, and scaling recommendations"]}'::jsonb, '["Explain how this implementation prevents: Conducting load tests with static identical data payloads, triggering unrealistic 100% cache hit rates on all requests.", "How does Enterprise Capstone XII: High-Concurrency Load Testing with k6 scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-13', 'phase-14-lesson-13-enterprise-capstone-xiii-chaos-engineerin', 'module-14', 33, 'Lesson 14.33: Enterprise Capstone XIII: Chaos Engineering & Resilience Validation', 'Prerequisites: Phase 7, Phase 11', 'Prerequisites: Phase 7, Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3560.0, 650.0, '# Lesson 14.13: Enterprise Capstone XIII: Chaos Engineering & Resilience Validation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Phase 11
- **Subtopics**:
  - `14.13.1` Validating system self-healing: testing whether the system survives component failures under active production load
  - `14.13.2` LitmusChaos experiment execution: terminating primary database pods, injecting 30% packet loss, killing Kubernetes worker nodes
  - `14.13.3` Verifying fault tolerance: testing automated database failover, Kafka consumer rebalancing, and circuit breaker trip mechanics
  - `14.13.4` Evaluating user impact during chaos: proving that customer API requests experience zero data loss and $<0.5\%$ transient errors
  - `14.13.5` Disaster recovery drill: executing an automated cluster restoration drill from Velero backups into a secondary cloud region
  - `14.13.6` Resilience certification: compiling the Chaos Verification Report proving compliance with five-nines availability principles
- **Key Failure Modes & Edge Cases**: Failing to automate chaos experiments, leaving critical failover procedures untested until an actual production outage strikes.
- **Verification & Mastery Check**: Execute a multi-fault LitmusChaos experiment during active load testing; prove zero data corruption and automated recovery under 60s.
- **Project Application**: Enterprise Capstone: Chaos engineering verification report.', '{"solution.py": "# Phase 14 // Lesson 14.13: Enterprise Capstone XIII: Chaos Engineering & Resilience Validation\n\ndef solve():\n    \"\"\"\n    Verification: Execute a multi-fault LitmusChaos experiment during active load testing; prove zero data corruption \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.13", "subtopics_count": 6, "verification_criteria": "Execute a multi-fault LitmusChaos experiment during active load testing; prove zero data corruption and automated recovery under 60s.", "subtopics": ["14.13.1 Validating system self-healing: testing whether the system survives component failures under active production load", "14.13.2 LitmusChaos experiment execution: terminating primary database pods, injecting 30% packet loss, killing Kubernetes worker nodes", "14.13.3 Verifying fault tolerance: testing automated database failover, Kafka consumer rebalancing, and circuit breaker trip mechanics", "14.13.4 Evaluating user impact during chaos: proving that customer API requests experience zero data loss and $<0.5\\%$ transient errors", "14.13.5 Disaster recovery drill: executing an automated cluster restoration drill from Velero backups into a secondary cloud region", "14.13.6 Resilience certification: compiling the Chaos Verification Report proving compliance with five-nines availability principles"]}'::jsonb, '["Explain how this implementation prevents: Failing to automate chaos experiments, leaving critical failover procedures untested until an actual production outage s", "How does Enterprise Capstone XIII: Chaos Engineering & Resilience Validation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-14', 'phase-14-lesson-14-enterprise-capstone-xiv-security-audit-pe', 'module-14', 34, 'Lesson 14.34: Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance', 'Prerequisites: Phase 5, Phase 10, Phase 13', 'Prerequisites: Phase 5, Phase 10, Phase 13 | Subtopics: 6 items', 'Systems project application', 380, 15, 3620.0, 700.0, '# Lesson 14.14: Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Phase 10, Phase 13
- **Subtopics**:
  - `14.14.1` Executing a comprehensive pre-launch security audit: scanning all codebases with Semgrep SAST and containers with Trivy
  - `14.14.2` Penetration testing: conducting authenticated and unauthenticated penetration attacks against web APIs and agent sandboxes
  - `14.14.3` Prompt injection red-teaming: testing 20 direct and indirect prompt injection attacks against the autonomous agent pipelines
  - `14.14.4` PII and data privacy audit: verifying Microsoft Presidio PII redaction and testing GDPR data deletion workflows
  - `14.14.5` Zero-Trust verification: inspecting mTLS certificate rotation and Kubernetes network policy default-deny enforcement
  - `14.14.6` Compiling the Security & Compliance Dossier: documenting threat mitigations, SOC2 Type II controls, and vulnerability remediation
- **Key Failure Modes & Edge Cases**: Launching an enterprise platform with open container egress or un-redacted user PII in distributed application logs.
- **Verification & Mastery Check**: Pass the automated security and penetration audit with 0 critical or high vulnerabilities; verify 100% prompt injection containment.
- **Project Application**: Enterprise Capstone: Security audit dossier and penetration test report.', '{"solution.py": "# Phase 14 // Lesson 14.14: Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance\n\ndef solve():\n    \"\"\"\n    Verification: Pass the automated security and penetration audit with 0 critical or high vulnerabilities; verify 10\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.14", "subtopics_count": 6, "verification_criteria": "Pass the automated security and penetration audit with 0 critical or high vulnerabilities; verify 100% prompt injection containment.", "subtopics": ["14.14.1 Executing a comprehensive pre-launch security audit: scanning all codebases with Semgrep SAST and containers with Trivy", "14.14.2 Penetration testing: conducting authenticated and unauthenticated penetration attacks against web APIs and agent sandboxes", "14.14.3 Prompt injection red-teaming: testing 20 direct and indirect prompt injection attacks against the autonomous agent pipelines", "14.14.4 PII and data privacy audit: verifying Microsoft Presidio PII redaction and testing GDPR data deletion workflows", "14.14.5 Zero-Trust verification: inspecting mTLS certificate rotation and Kubernetes network policy default-deny enforcement", "14.14.6 Compiling the Security & Compliance Dossier: documenting threat mitigations, SOC2 Type II controls, and vulnerability remediation"]}'::jsonb, '["Explain how this implementation prevents: Launching an enterprise platform with open container egress or un-redacted user PII in distributed application logs.", "How does Enterprise Capstone XIV: Security Audit, Penetration Testing & Compliance scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-14-15', 'phase-14-lesson-15-enterprise-capstone-xv-production-runbook', 'module-14', 35, 'Lesson 14.35: Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense', 'Prerequisites: Phase 8, Phase 11', 'Prerequisites: Phase 8, Phase 11 | Subtopics: 6 items', 'Systems project application', 380, 15, 3500.0, 750.0, '# Lesson 14.15: Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 8, Phase 11
- **Subtopics**:
  - `14.15.1` Authoring Production Runbooks: step-by-step diagnostic workflows for alert triage, database failbacks, and incident escalation
  - `14.15.2` Service Level Agreement (SLA) contract defense: presenting documented error budget policies and disaster recovery runbooks
  - `14.15.3` Disaster Recovery (DR) sign-off: proving Recovery Point Objective (RPO) $< 1\text{ minute}$ and Recovery Time Objective (RTO) $< 15\text{ minutes}$
  - `14.15.4` The Production Engineering Live Defense: delivering a 60-minute technical architectural presentation to senior engineering staff
  - `14.15.5` Defending architectural trade-offs: answering rigorous interrogation on consistency models, scaling bottlenecks, and cost trade-offs
  - `14.15.6` Final project certification: signing off on code quality, test coverage, deployment automation, and production readiness
- **Key Failure Modes & Edge Cases**: Inability to explain why an architectural decision was chosen over alternatives when questioned by senior engineering leadership.
- **Verification & Mastery Check**: Successfully defend the entire Enterprise Capstone architecture in a 60-minute live presentation, answering all technical challenges.
- **Project Application**: Enterprise Capstone: Production Runbooks, DR Plan, and Capstone Sign-off.', '{"solution.py": "# Phase 14 // Lesson 14.15: Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense\n\ndef solve():\n    \"\"\"\n    Verification: Successfully defend the entire Enterprise Capstone architecture in a 60-minute live presentation, an\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "14.15", "subtopics_count": 6, "verification_criteria": "Successfully defend the entire Enterprise Capstone architecture in a 60-minute live presentation, answering all technical challenges.", "subtopics": ["14.15.1 Authoring Production Runbooks: step-by-step diagnostic workflows for alert triage, database failbacks, and incident escalation", "14.15.2 Service Level Agreement (SLA) contract defense: presenting documented error budget policies and disaster recovery runbooks", "14.15.3 Disaster Recovery (DR) sign-off: proving Recovery Point Objective (RPO) $< 1\\text{ minute}$ and Recovery Time Objective (RTO) $< 15\\text{ minutes}$", "14.15.4 The Production Engineering Live Defense: delivering a 60-minute technical architectural presentation to senior engineering staff", "14.15.5 Defending architectural trade-offs: answering rigorous interrogation on consistency models, scaling bottlenecks, and cost trade-offs", "14.15.6 Final project certification: signing off on code quality, test coverage, deployment automation, and production readiness"]}'::jsonb, '["Explain how this implementation prevents: Inability to explain why an architectural decision was chosen over alternatives when questioned by senior engineering le", "How does Enterprise Capstone XV: Production Runbooks, Disaster Recovery & Live Defense scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
