INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-1-1', 'phase-01-lesson-01-object-oriented-programming-mental-model', 'module-2', 1, 'Lesson 2.1: Object-Oriented Programming Mental Model', 'Prerequisites: Phase 0', 'Prerequisites: Phase 0 | Subtopics: 4 items', 'Systems project application', 120, 2, 310.0, 50.0, '# Lesson 1.1: Object-Oriented Programming Mental Model

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0
- **Subtopics**:
  - `1.1.1` Real-world mental model: modeling software entities as objects with attributes and behaviors.
  - `1.1.2` Classes as blueprints: defining templates for creating multiple independent instances.
  - `1.1.3` Instances as physical objects: how each object maintains its own isolated memory state.
  - `1.1.4` Why OOP matters in AI engineering: modeling PromptTemplates, ChatMessages, and AgentSessions as clean objects.
- **Key Failure Modes & Edge Cases**: Treating a class definition as an active object rather than instantiating it with parentheses ().
- **Verification & Mastery Check**: Define a ChatMessage class representing an AI message, create instances for user and assistant, and inspect them.
- **Project Application**: SchemaAgent: Message domain models.', '{"solution.py": "# Phase 1 // Lesson 1.1: Object-Oriented Programming Mental Model\n\ndef solve():\n    \"\"\"\n    Verification: Define a ChatMessage class representing an AI message, create instances for user and assistant, and \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.1", "subtopics_count": 4, "verification_criteria": "Define a ChatMessage class representing an AI message, create instances for user and assistant, and inspect them.", "subtopics": ["1.1.1 Real-world mental model: modeling software entities as objects with attributes and behaviors.", "1.1.2 Classes as blueprints: defining templates for creating multiple independent instances.", "1.1.3 Instances as physical objects: how each object maintains its own isolated memory state.", "1.1.4 Why OOP matters in AI engineering: modeling PromptTemplates, ChatMessages, and AgentSessions as clean objects."]}'::jsonb, '["Explain how this implementation prevents: Treating a class definition as an active object rather than instantiating it with parentheses ().", "How does Object-Oriented Programming Mental Model scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-2', 'phase-01-lesson-02-constructors-init-and-instance-attributes', 'module-2', 2, 'Lesson 2.2: Constructors: __init__ and Instance Attributes', 'Prerequisites: Lesson 1.1', 'Prerequisites: Lesson 1.1 | Subtopics: 4 items', 'Systems project application', 120, 2, 370.0, 100.0, '# Lesson 1.2: Constructors: __init__ and Instance Attributes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.1
- **Subtopics**:
  - `1.2.1` The constructor method: initializing new instances automatically using __init__.
  - `1.2.2` The self parameter: how methods know which specific object instance they are working with.
  - `1.2.3` Instance attributes: binding state directly to self.attribute_name.
  - `1.2.4` Input validation in constructors: checking that required parameters are provided cleanly.
- **Key Failure Modes & Edge Cases**: Omitting self as the first parameter of __init__, triggering TypeError: takes 0 positional arguments.
- **Verification & Mastery Check**: Build a ModelConfig class that validates temperature (0.0 to 2.0) and raises ValueError if out of bounds.
- **Project Application**: SchemaAgent: LLM configuration builder.', '{"solution.py": "# Phase 1 // Lesson 1.2: Constructors: __init__ and Instance Attributes\n\ndef solve():\n    \"\"\"\n    Verification: Build a ModelConfig class that validates temperature (0.0 to 2.0) and raises ValueError if out of bo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.2", "subtopics_count": 4, "verification_criteria": "Build a ModelConfig class that validates temperature (0.0 to 2.0) and raises ValueError if out of bounds.", "subtopics": ["1.2.1 The constructor method: initializing new instances automatically using __init__.", "1.2.2 The self parameter: how methods know which specific object instance they are working with.", "1.2.3 Instance attributes: binding state directly to self.attribute_name.", "1.2.4 Input validation in constructors: checking that required parameters are provided cleanly."]}'::jsonb, '["Explain how this implementation prevents: Omitting self as the first parameter of __init__, triggering TypeError: takes 0 positional arguments.", "How does Constructors: __init__ and Instance Attributes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-3', 'phase-01-lesson-03-instance-methods-vs-class-methods-vs-stat', 'module-2', 3, 'Lesson 2.3: Instance Methods vs Class Methods vs Static Methods', 'Prerequisites: Lesson 1.2', 'Prerequisites: Lesson 1.2 | Subtopics: 4 items', 'Systems project application', 120, 2, 250.0, 150.0, '# Lesson 1.3: Instance Methods vs Class Methods vs Static Methods

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.2
- **Subtopics**:
  - `1.3.1` Instance methods: regular methods operating on self and modifying instance state.
  - `1.3.2` Class methods with @classmethod: operating on the class (cls) for alternative constructors.
  - `1.3.3` Static methods with @staticmethod: utility functions that live inside a class without needing self or cls.
  - `1.3.4` When to choose each method type in clean software architecture.
- **Key Failure Modes & Edge Cases**: Accidentally calling an instance method from a class without creating an instance first.
- **Verification & Mastery Check**: Implement a Prompt class with an instance method .render() and a @classmethod .from_file(path).
- **Project Application**: SchemaAgent: Alternative constructor factory methods.', '{"solution.py": "# Phase 1 // Lesson 1.3: Instance Methods vs Class Methods vs Static Methods\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Prompt class with an instance method .render() and a @classmethod .from_file(path).\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.3", "subtopics_count": 4, "verification_criteria": "Implement a Prompt class with an instance method .render() and a @classmethod .from_file(path).", "subtopics": ["1.3.1 Instance methods: regular methods operating on self and modifying instance state.", "1.3.2 Class methods with @classmethod: operating on the class (cls) for alternative constructors.", "1.3.3 Static methods with @staticmethod: utility functions that live inside a class without needing self or cls.", "1.3.4 When to choose each method type in clean software architecture."]}'::jsonb, '["Explain how this implementation prevents: Accidentally calling an instance method from a class without creating an instance first.", "How does Instance Methods vs Class Methods vs Static Methods scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-4', 'phase-01-lesson-04-encapsulation-private-attribute-conventio', 'module-2', 4, 'Lesson 2.4: Encapsulation & Private Attribute Conventions', 'Prerequisites: Lesson 1.2', 'Prerequisites: Lesson 1.2 | Subtopics: 4 items', 'Systems project application', 120, 2, 310.0, 200.0, '# Lesson 1.4: Encapsulation & Private Attribute Conventions

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.2
- **Subtopics**:
  - `1.4.1` Encapsulation principle: bundling data and methods together while protecting internal state.
  - `1.4.2` Private variable naming conventions in Python: using leading underscores (_variable and __variable).
  - `1.4.3` Name mangling in Python: how __attribute is transformed to prevent accidental child class overrides.
  - `1.4.4` Public interfaces: exposing only what consumers need to use, hiding internal implementation details.
- **Key Failure Modes & Edge Cases**: Reaching directly into private internal attributes of external libraries, breaking when the library updates.
- **Verification & Mastery Check**: Create an ApiClient class that keeps API keys private while exposing a clean public .generate() method.
- **Project Application**: SchemaAgent: Secure credential encapsulation.', '{"solution.py": "# Phase 1 // Lesson 1.4: Encapsulation & Private Attribute Conventions\n\ndef solve():\n    \"\"\"\n    Verification: Create an ApiClient class that keeps API keys private while exposing a clean public .generate() meth\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.4", "subtopics_count": 4, "verification_criteria": "Create an ApiClient class that keeps API keys private while exposing a clean public .generate() method.", "subtopics": ["1.4.1 Encapsulation principle: bundling data and methods together while protecting internal state.", "1.4.2 Private variable naming conventions in Python: using leading underscores (_variable and __variable).", "1.4.3 Name mangling in Python: how __attribute is transformed to prevent accidental child class overrides.", "1.4.4 Public interfaces: exposing only what consumers need to use, hiding internal implementation details."]}'::jsonb, '["Explain how this implementation prevents: Reaching directly into private internal attributes of external libraries, breaking when the library updates.", "How does Encapsulation & Private Attribute Conventions scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-5', 'phase-01-lesson-05-properties-property-getters-setters', 'module-2', 5, 'Lesson 2.5: Properties: @property Getters & Setters', 'Prerequisites: Lesson 1.4', 'Prerequisites: Lesson 1.4 | Subtopics: 4 items', 'Systems project application', 120, 2, 370.0, 250.0, '# Lesson 1.5: Properties: @property Getters & Setters

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.4
- **Subtopics**:
  - `1.5.1` Pythonic attribute access: accessing methods like normal attributes using @property.
  - `1.5.2` Getters: calculating values on-the-fly when an attribute is read.
  - `1.5.3` Setters with @attribute.setter: intercepting assignments to validate data before saving.
  - `1.5.4` Refactoring legacy code: turning raw attributes into validated properties without breaking existing callers.
- **Key Failure Modes & Edge Cases**: Creating an infinite recursion loop by setting self.name inside a setter that defines name.
- **Verification & Mastery Check**: Add a validated @property for temperature that rejects negative numbers and rounds floats to 2 decimal places.
- **Project Application**: SchemaAgent: Attribute validation descriptors.', '{"solution.py": "# Phase 1 // Lesson 1.5: Properties: @property Getters & Setters\n\ndef solve():\n    \"\"\"\n    Verification: Add a validated @property for temperature that rejects negative numbers and rounds floats to 2 decim\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.5", "subtopics_count": 4, "verification_criteria": "Add a validated @property for temperature that rejects negative numbers and rounds floats to 2 decimal places.", "subtopics": ["1.5.1 Pythonic attribute access: accessing methods like normal attributes using @property.", "1.5.2 Getters: calculating values on-the-fly when an attribute is read.", "1.5.3 Setters with @attribute.setter: intercepting assignments to validate data before saving.", "1.5.4 Refactoring legacy code: turning raw attributes into validated properties without breaking existing callers."]}'::jsonb, '["Explain how this implementation prevents: Creating an infinite recursion loop by setting self.name inside a setter that defines name.", "How does Properties: @property Getters & Setters scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-6', 'phase-01-lesson-06-inheritance-subclasses-polymorphism', 'module-2', 6, 'Lesson 2.6: Inheritance: Subclasses & Polymorphism', 'Prerequisites: Lesson 1.1', 'Prerequisites: Lesson 1.1 | Subtopics: 4 items', 'Systems project application', 120, 2, 250.0, 300.0, '# Lesson 1.6: Inheritance: Subclasses & Polymorphism

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.1
- **Subtopics**:
  - `1.6.1` Code reuse through inheritance: creating specialized child classes from a common parent class.
  - `1.6.2` Method overriding: customizing or replacing a parent method inside a child class.
  - `1.6.3` Polymorphism principle: treating different child classes through a single common interface.
  - `1.6.4` When inheritance is appropriate vs when it creates rigid, fragile hierarchies.
- **Key Failure Modes & Edge Cases**: Creating deeply nested 5-level inheritance hierarchies that are impossible to maintain or debug.
- **Verification & Mastery Check**: Create a base Tool class and two child classes (SearchTool and CalculatorTool) implementing .run().
- **Project Application**: SchemaAgent: Tool execution polymorphism.', '{"solution.py": "# Phase 1 // Lesson 1.6: Inheritance: Subclasses & Polymorphism\n\ndef solve():\n    \"\"\"\n    Verification: Create a base Tool class and two child classes (SearchTool and CalculatorTool) implementing .run().\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.6", "subtopics_count": 4, "verification_criteria": "Create a base Tool class and two child classes (SearchTool and CalculatorTool) implementing .run().", "subtopics": ["1.6.1 Code reuse through inheritance: creating specialized child classes from a common parent class.", "1.6.2 Method overriding: customizing or replacing a parent method inside a child class.", "1.6.3 Polymorphism principle: treating different child classes through a single common interface.", "1.6.4 When inheritance is appropriate vs when it creates rigid, fragile hierarchies."]}'::jsonb, '["Explain how this implementation prevents: Creating deeply nested 5-level inheritance hierarchies that are impossible to maintain or debug.", "How does Inheritance: Subclasses & Polymorphism scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-7', 'phase-01-lesson-07-super-method-resolution-order-mro', 'module-2', 7, 'Lesson 2.7: Super(): Method Resolution Order (MRO)', 'Prerequisites: Lesson 1.6', 'Prerequisites: Lesson 1.6 | Subtopics: 4 items', 'Systems project application', 120, 2, 310.0, 350.0, '# Lesson 1.7: Super(): Method Resolution Order (MRO)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.6
- **Subtopics**:
  - `1.7.1` Calling parent methods: using super().__init__() to ensure parent initialization runs.
  - `1.7.2` Extending parent behavior: calling super().method() before or after adding child-specific logic.
  - `1.7.3` Method Resolution Order (MRO): the exact order Python uses to search for methods in class hierarchies.
  - `1.7.4` Inspecting class order: using ClassName.mro() to see the inheritance chain.
- **Key Failure Modes & Edge Cases**: Forgetting to call super().__init__() in a subclass, leaving parent attributes uninitialized.
- **Verification & Mastery Check**: Build a SafeTool subclass that calls super().run() and adds automated execution time logging.
- **Project Application**: SchemaAgent: Middleware tool wrapping.', '{"solution.py": "# Phase 1 // Lesson 1.7: Super(): Method Resolution Order (MRO)\n\ndef solve():\n    \"\"\"\n    Verification: Build a SafeTool subclass that calls super().run() and adds automated execution time logging.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.7", "subtopics_count": 4, "verification_criteria": "Build a SafeTool subclass that calls super().run() and adds automated execution time logging.", "subtopics": ["1.7.1 Calling parent methods: using super().__init__() to ensure parent initialization runs.", "1.7.2 Extending parent behavior: calling super().method() before or after adding child-specific logic.", "1.7.3 Method Resolution Order (MRO): the exact order Python uses to search for methods in class hierarchies.", "1.7.4 Inspecting class order: using ClassName.mro() to see the inheritance chain."]}'::jsonb, '["Explain how this implementation prevents: Forgetting to call super().__init__() in a subclass, leaving parent attributes uninitialized.", "How does Super(): Method Resolution Order (MRO) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-8', 'phase-01-lesson-08-composition-over-inheritance', 'module-2', 8, 'Lesson 2.8: Composition Over Inheritance', 'Prerequisites: Lesson 1.6', 'Prerequisites: Lesson 1.6 | Subtopics: 4 items', 'Systems project application', 120, 2, 370.0, 400.0, '# Lesson 1.8: Composition Over Inheritance

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.6
- **Subtopics**:
  - `1.8.1` The architectural golden rule: favor object composition (''has-a'') over class inheritance (''is-a'').
  - `1.8.2` Building systems out of modular parts: assembling an agent from a model, a memory buffer, and tools.
  - `1.8.3` Flexibility benefits: easily swapping components at runtime without changing class inheritance.
  - `1.8.4` Refactoring rigid class hierarchies into clean composed objects.
- **Key Failure Modes & Edge Cases**: Forcing a class to inherit from a parent just to reuse a single helper function.
- **Verification & Mastery Check**: Build an AIAgent class that takes an LLMClient instance and a MemoryBuffer instance via its constructor.
- **Project Application**: SchemaAgent: Composable agent architecture.', '{"solution.py": "# Phase 1 // Lesson 1.8: Composition Over Inheritance\n\ndef solve():\n    \"\"\"\n    Verification: Build an AIAgent class that takes an LLMClient instance and a MemoryBuffer instance via its construc\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.8", "subtopics_count": 4, "verification_criteria": "Build an AIAgent class that takes an LLMClient instance and a MemoryBuffer instance via its constructor.", "subtopics": ["1.8.1 The architectural golden rule: favor object composition (''has-a'') over class inheritance (''is-a'').", "1.8.2 Building systems out of modular parts: assembling an agent from a model, a memory buffer, and tools.", "1.8.3 Flexibility benefits: easily swapping components at runtime without changing class inheritance.", "1.8.4 Refactoring rigid class hierarchies into clean composed objects."]}'::jsonb, '["Explain how this implementation prevents: Forcing a class to inherit from a parent just to reuse a single helper function.", "How does Composition Over Inheritance scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-9', 'phase-01-lesson-09-dunder-methods-repr-and-str', 'module-2', 9, 'Lesson 2.9: Dunder Methods: __repr__ and __str__', 'Prerequisites: Lesson 1.2', 'Prerequisites: Lesson 1.2 | Subtopics: 4 items', 'Systems project application', 120, 2, 250.0, 450.0, '# Lesson 1.9: Dunder Methods: __repr__ and __str__

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.2
- **Subtopics**:
  - `1.9.1` Special double-underscore methods: customizing how Python handles your custom objects.
  - `1.9.2` The duality of display: __str__ for human-friendly messages vs __repr__ for unambiguous debugging.
  - `1.9.3` Default object printing: why omitting these methods shows useless <Object at 0x7f...> pointers.
  - `1.9.4` Formatting best practices: making repr(obj) look like valid Python code to recreate the object.
- **Key Failure Modes & Edge Cases**: Failing to implement __repr__, making log files and debugger inspection frustratingly opaque.
- **Verification & Mastery Check**: Implement clean __str__ and __repr__ methods for an AgentAction class showing tool name and arguments.
- **Project Application**: SchemaAgent: Clear debugging telemetry.', '{"solution.py": "# Phase 1 // Lesson 1.9: Dunder Methods: __repr__ and __str__\n\ndef solve():\n    \"\"\"\n    Verification: Implement clean __str__ and __repr__ methods for an AgentAction class showing tool name and argument\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.9", "subtopics_count": 4, "verification_criteria": "Implement clean __str__ and __repr__ methods for an AgentAction class showing tool name and arguments.", "subtopics": ["1.9.1 Special double-underscore methods: customizing how Python handles your custom objects.", "1.9.2 The duality of display: __str__ for human-friendly messages vs __repr__ for unambiguous debugging.", "1.9.3 Default object printing: why omitting these methods shows useless <Object at 0x7f...> pointers.", "1.9.4 Formatting best practices: making repr(obj) look like valid Python code to recreate the object."]}'::jsonb, '["Explain how this implementation prevents: Failing to implement __repr__, making log files and debugger inspection frustratingly opaque.", "How does Dunder Methods: __repr__ and __str__ scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-10', 'phase-01-lesson-10-operator-overloading-add-eq-lt', 'module-2', 10, 'Lesson 2.10: Operator Overloading: __add__, __eq__, __lt__', 'Prerequisites: Lesson 1.9', 'Prerequisites: Lesson 1.9 | Subtopics: 4 items', 'Systems project application', 120, 2, 310.0, 500.0, '# Lesson 1.10: Operator Overloading: __add__, __eq__, __lt__

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.9
- **Subtopics**:
  - `1.10.1` Teaching custom objects to use math operators: overloading +, ==, <, and >.
  - `1.10.2` Value equality with __eq__: comparing object contents rather than memory addresses.
  - `1.10.3` Adding objects with __add__: combining two PromptTemplates into a single merged template.
  - `1.10.4` Ordering objects with __lt__: enabling Python''s sorted() to sort custom objects automatically.
- **Key Failure Modes & Edge Cases**: Implementing __eq__ without handling type checks, causing crashes when comparing with None.
- **Verification & Mastery Check**: Implement __add__ on PromptSegment so that prompt_a + prompt_b cleanly concatenates their text blocks.
- **Project Application**: SchemaAgent: Composable prompt segments.', '{"solution.py": "# Phase 1 // Lesson 1.10: Operator Overloading: __add__, __eq__, __lt__\n\ndef solve():\n    \"\"\"\n    Verification: Implement __add__ on PromptSegment so that prompt_a + prompt_b cleanly concatenates their text block\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.10", "subtopics_count": 4, "verification_criteria": "Implement __add__ on PromptSegment so that prompt_a + prompt_b cleanly concatenates their text blocks.", "subtopics": ["1.10.1 Teaching custom objects to use math operators: overloading +, ==, <, and >.", "1.10.2 Value equality with __eq__: comparing object contents rather than memory addresses.", "1.10.3 Adding objects with __add__: combining two PromptTemplates into a single merged template.", "1.10.4 Ordering objects with __lt__: enabling Python''s sorted() to sort custom objects automatically."]}'::jsonb, '["Explain how this implementation prevents: Implementing __eq__ without handling type checks, causing crashes when comparing with None.", "How does Operator Overloading: __add__, __eq__, __lt__ scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-11', 'phase-01-lesson-11-containers-protocol-len-and-getitem', 'module-2', 11, 'Lesson 2.11: Containers Protocol: __len__ and __getitem__', 'Prerequisites: Lesson 1.9', 'Prerequisites: Lesson 1.9 | Subtopics: 4 items', 'Systems project application', 120, 2, 370.0, 550.0, '# Lesson 1.11: Containers Protocol: __len__ and __getitem__

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.9
- **Subtopics**:
  - `1.11.1` Creating custom collections: making your classes behave like native Python lists or dicts.
  - `1.11.2` Supporting len(): implementing __len__ to return the item count.
  - `1.11.3` Supporting indexing: implementing __getitem__ to allow square bracket access obj[key] or obj[index].
  - `1.11.4` Iteration for free: how Python automatically loops over objects that implement __getitem__.
- **Key Failure Modes & Edge Cases**: Returning negative numbers or non-integers from __len__, triggering TypeError.
- **Verification & Mastery Check**: Build a MessageHistory class that supports len(history) and indexing history[0] to get messages.
- **Project Application**: SchemaAgent: Custom collection containers.', '{"solution.py": "# Phase 1 // Lesson 1.11: Containers Protocol: __len__ and __getitem__\n\ndef solve():\n    \"\"\"\n    Verification: Build a MessageHistory class that supports len(history) and indexing history[0] to get messages.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.11", "subtopics_count": 4, "verification_criteria": "Build a MessageHistory class that supports len(history) and indexing history[0] to get messages.", "subtopics": ["1.11.1 Creating custom collections: making your classes behave like native Python lists or dicts.", "1.11.2 Supporting len(): implementing __len__ to return the item count.", "1.11.3 Supporting indexing: implementing __getitem__ to allow square bracket access obj[key] or obj[index].", "1.11.4 Iteration for free: how Python automatically loops over objects that implement __getitem__."]}'::jsonb, '["Explain how this implementation prevents: Returning negative numbers or non-integers from __len__, triggering TypeError.", "How does Containers Protocol: __len__ and __getitem__ scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-12', 'phase-01-lesson-12-context-managers-enter-and-exit', 'module-2', 12, 'Lesson 2.12: Context Managers: __enter__ and __exit__', 'Prerequisites: Lesson 1.2, Phase 0 (Lesson 0.15)', 'Prerequisites: Lesson 1.2, Phase 0 (Lesson 0.15) | Subtopics: 4 items', 'Systems project application', 120, 2, 250.0, 600.0, '# Lesson 1.12: Context Managers: __enter__ and __exit__

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.2, Phase 0 (Lesson 0.15)
- **Subtopics**:
  - `1.12.1` Resource safety: managing setup and teardown automatically with the with statement.
  - `1.12.2` The context manager protocol: implementing __enter__ and __exit__.
  - `1.12.3` Exception handling in __exit__: inspecting errors and deciding whether to suppress them.
  - `1.12.4` Writing lightweight context managers with the @contextmanager decorator from contextlib.
- **Key Failure Modes & Edge Cases**: Unconditionally returning True from __exit__, which silently swallows catastrophic syntax errors.
- **Verification & Mastery Check**: Write a Timer context manager that measures and prints the exact execution time of any code block.
- **Project Application**: SchemaAgent: Automated latency profiling context.', '{"solution.py": "# Phase 1 // Lesson 1.12: Context Managers: __enter__ and __exit__\n\ndef solve():\n    \"\"\"\n    Verification: Write a Timer context manager that measures and prints the exact execution time of any code block.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.12", "subtopics_count": 4, "verification_criteria": "Write a Timer context manager that measures and prints the exact execution time of any code block.", "subtopics": ["1.12.1 Resource safety: managing setup and teardown automatically with the with statement.", "1.12.2 The context manager protocol: implementing __enter__ and __exit__.", "1.12.3 Exception handling in __exit__: inspecting errors and deciding whether to suppress them.", "1.12.4 Writing lightweight context managers with the @contextmanager decorator from contextlib."]}'::jsonb, '["Explain how this implementation prevents: Unconditionally returning True from __exit__, which silently swallows catastrophic syntax errors.", "How does Context Managers: __enter__ and __exit__ scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-13', 'phase-01-lesson-13-iterators-protocol-iter-and-next', 'module-2', 13, 'Lesson 2.13: Iterators Protocol: __iter__ and __next__', 'Prerequisites: Lesson 1.11', 'Prerequisites: Lesson 1.11 | Subtopics: 4 items', 'Systems project application', 120, 2, 310.0, 650.0, '# Lesson 1.13: Iterators Protocol: __iter__ and __next__

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.11
- **Subtopics**:
  - `1.13.1` How iteration works behind the scenes: the Iterator design pattern in Python.
  - `1.13.2` The __iter__ method: returning an iterator object.
  - `1.13.3` The __next__ method: producing the next item or raising StopIteration when finished.
  - `1.13.4` Building custom stream iterators that process endless streams of incoming AI tokens.
- **Key Failure Modes & Edge Cases**: Forgetting to raise StopIteration, causing for loops over your custom object to run forever.
- **Verification & Mastery Check**: Build a TokenStream class that yields words from a response one-by-one with simulated delays.
- **Project Application**: SchemaAgent: Simulated token streaming iterator.', '{"solution.py": "# Phase 1 // Lesson 1.13: Iterators Protocol: __iter__ and __next__\n\ndef solve():\n    \"\"\"\n    Verification: Build a TokenStream class that yields words from a response one-by-one with simulated delays.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.13", "subtopics_count": 4, "verification_criteria": "Build a TokenStream class that yields words from a response one-by-one with simulated delays.", "subtopics": ["1.13.1 How iteration works behind the scenes: the Iterator design pattern in Python.", "1.13.2 The __iter__ method: returning an iterator object.", "1.13.3 The __next__ method: producing the next item or raising StopIteration when finished.", "1.13.4 Building custom stream iterators that process endless streams of incoming AI tokens."]}'::jsonb, '["Explain how this implementation prevents: Forgetting to raise StopIteration, causing for loops over your custom object to run forever.", "How does Iterators Protocol: __iter__ and __next__ scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-14', 'phase-01-lesson-14-generators-the-yield-keyword', 'module-2', 14, 'Lesson 2.14: Generators & The yield Keyword', 'Prerequisites: Lesson 1.13', 'Prerequisites: Lesson 1.13 | Subtopics: 4 items', 'Systems project application', 120, 2, 370.0, 700.0, '# Lesson 1.14: Generators & The yield Keyword

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.13
- **Subtopics**:
  - `1.14.1` Lightweight stream producers: writing generator functions using the yield keyword.
  - `1.14.2` Memory efficiency: why generators use zero extra memory even when yielding billions of items.
  - `1.14.3` Generator state preservation: pausing function execution and resuming seamlessly on next().
  - `1.14.4` Generator expressions: writing single-line memory-efficient streaming pipelines.
- **Key Failure Modes & Edge Cases**: Treating a generator like a reusable list; once consumed, a generator is empty and cannot be re-run!
- **Verification & Mastery Check**: Write a generator function stream_chunks(text, chunk_size) that yields fixed-size text segments.
- **Project Application**: SchemaAgent: Memory-bounded document chunking.', '{"solution.py": "# Phase 1 // Lesson 1.14: Generators & The yield Keyword\n\ndef solve():\n    \"\"\"\n    Verification: Write a generator function stream_chunks(text, chunk_size) that yields fixed-size text segments.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.14", "subtopics_count": 4, "verification_criteria": "Write a generator function stream_chunks(text, chunk_size) that yields fixed-size text segments.", "subtopics": ["1.14.1 Lightweight stream producers: writing generator functions using the yield keyword.", "1.14.2 Memory efficiency: why generators use zero extra memory even when yielding billions of items.", "1.14.3 Generator state preservation: pausing function execution and resuming seamlessly on next().", "1.14.4 Generator expressions: writing single-line memory-efficient streaming pipelines."]}'::jsonb, '["Explain how this implementation prevents: Treating a generator like a reusable list; once consumed, a generator is empty and cannot be re-run!", "How does Generators & The yield Keyword scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-1-15', 'phase-01-lesson-15-decorators-function-wrapping-wraps', 'module-2', 15, 'Lesson 2.15: Decorators: Function Wrapping & Wraps', 'Prerequisites: Lesson 1.2, Phase 0 (Lesson 0.8)', 'Prerequisites: Lesson 1.2, Phase 0 (Lesson 0.8) | Subtopics: 4 items', 'Systems project application', 120, 2, 250.0, 750.0, '# Lesson 1.15: Decorators: Function Wrapping & Wraps

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 1.2, Phase 0 (Lesson 0.8)
- **Subtopics**:
  - `1.15.1` Decorators as function wrappers: augmenting function behavior without modifying original code.
  - `1.15.2` Higher-order functions: functions that accept functions as arguments and return new functions.
  - `1.15.3` Preserving metadata: using @functools.wraps to protect the original function name and docstring.
  - `1.15.4` Practical use cases: automated logging, timing, authentication checks, and input sanitization.
- **Key Failure Modes & Edge Cases**: Forgetting @functools.wraps, causing decorated functions to lose their name and breaking debugging tools.
- **Verification & Mastery Check**: Write a @log_call decorator that prints the function name, arguments, and return value for every invocation.
- **Project Application**: SchemaAgent: Observability logging wrappers.', '{"solution.py": "# Phase 1 // Lesson 1.15: Decorators: Function Wrapping & Wraps\n\ndef solve():\n    \"\"\"\n    Verification: Write a @log_call decorator that prints the function name, arguments, and return value for every inv\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "1.15", "subtopics_count": 4, "verification_criteria": "Write a @log_call decorator that prints the function name, arguments, and return value for every invocation.", "subtopics": ["1.15.1 Decorators as function wrappers: augmenting function behavior without modifying original code.", "1.15.2 Higher-order functions: functions that accept functions as arguments and return new functions.", "1.15.3 Preserving metadata: using @functools.wraps to protect the original function name and docstring.", "1.15.4 Practical use cases: automated logging, timing, authentication checks, and input sanitization."]}'::jsonb, '["Explain how this implementation prevents: Forgetting @functools.wraps, causing decorated functions to lose their name and breaking debugging tools.", "How does Decorators: Function Wrapping & Wraps scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
