INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-3-1', 'phase-03-lesson-01-algorithmic-complexity-big-o-intuition', 'module-5', 1, 'Lesson 5.1: Algorithmic Complexity & Big-O Intuition', 'Prerequisites: Phase 0, Phase 2', 'Prerequisites: Phase 0, Phase 2 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 50.0, '# Lesson 3.1: Algorithmic Complexity & Big-O Intuition

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 2
- **Subtopics**:
  - `3.1.1` Why algorithmic efficiency matters: code that works on 10 items can completely freeze on 1,000,000 items.
  - `3.1.2` Measuring scale, not clock time: why benchmarking milliseconds is misleading across different hardware.
  - `3.1.3` The Big-O notation mental model: describing how runtime grows as input size N increases.
  - `3.1.4` The Big-O hierarchy: O(1) constant, O(log N) logarithmic, O(N) linear, O(N log N), O(N^2) quadratic.
- **Key Failure Modes & Edge Cases**: Confusing the best-case runtime with worst-case or average-case Big-O guarantees.
- **Verification & Mastery Check**: Analyze three code snippets and write down their exact Big-O time and space complexity with justification.
- **Project Application**: StreamBuffer: Complexity auditing.', '{"solution.py": "# Phase 3 // Lesson 3.1: Algorithmic Complexity & Big-O Intuition\n\ndef solve():\n    \"\"\"\n    Verification: Analyze three code snippets and write down their exact Big-O time and space complexity with justific\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.1", "subtopics_count": 4, "verification_criteria": "Analyze three code snippets and write down their exact Big-O time and space complexity with justification.", "subtopics": ["3.1.1 Why algorithmic efficiency matters: code that works on 10 items can completely freeze on 1,000,000 items.", "3.1.2 Measuring scale, not clock time: why benchmarking milliseconds is misleading across different hardware.", "3.1.3 The Big-O notation mental model: describing how runtime grows as input size N increases.", "3.1.4 The Big-O hierarchy: O(1) constant, O(log N) logarithmic, O(N) linear, O(N log N), O(N^2) quadratic."]}'::jsonb, '["Explain how this implementation prevents: Confusing the best-case runtime with worst-case or average-case Big-O guarantees.", "How does Algorithmic Complexity & Big-O Intuition scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-2', 'phase-03-lesson-02-constant-o-1-vs-linear-o-n-complexity', 'module-5', 2, 'Lesson 5.2: Constant O(1) vs Linear O(N) Complexity', 'Prerequisites: Lesson 3.1', 'Prerequisites: Lesson 3.1 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 100.0, '# Lesson 3.2: Constant O(1) vs Linear O(N) Complexity

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.1
- **Subtopics**:
  - `3.2.1` Constant time O(1): operations that take the exact same amount of time regardless of dataset size.
  - `3.2.2` Examples of O(1): looking up an array index, appending to a list, looking up a key in a dictionary.
  - `3.2.3` Linear time O(N): operations whose execution time doubles whenever the input dataset doubles.
  - `3.2.4` Examples of O(N): scanning an unsorted list with for, calculating sum(list), counting character matches.
- **Key Failure Modes & Edge Cases**: Accidentally placing an O(N) operation inside a loop, unintentionally creating a quadratic O(N^2) disaster.
- **Verification & Mastery Check**: Benchmark array index lookup vs linear scan across 10, 1,000, and 1,000,000 elements to prove O(1) vs O(N).
- **Project Application**: StreamBuffer: Constant-time buffer indexing.', '{"solution.py": "# Phase 3 // Lesson 3.2: Constant O(1) vs Linear O(N) Complexity\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark array index lookup vs linear scan across 10, 1,000, and 1,000,000 elements to prove O(1) v\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.2", "subtopics_count": 4, "verification_criteria": "Benchmark array index lookup vs linear scan across 10, 1,000, and 1,000,000 elements to prove O(1) vs O(N).", "subtopics": ["3.2.1 Constant time O(1): operations that take the exact same amount of time regardless of dataset size.", "3.2.2 Examples of O(1): looking up an array index, appending to a list, looking up a key in a dictionary.", "3.2.3 Linear time O(N): operations whose execution time doubles whenever the input dataset doubles.", "3.2.4 Examples of O(N): scanning an unsorted list with for, calculating sum(list), counting character matches."]}'::jsonb, '["Explain how this implementation prevents: Accidentally placing an O(N) operation inside a loop, unintentionally creating a quadratic O(N^2) disaster.", "How does Constant O(1) vs Linear O(N) Complexity scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-3', 'phase-03-lesson-03-quadratic-o-n-2-the-nested-loop-trap', 'module-5', 3, 'Lesson 5.3: Quadratic O(N^2) & The Nested Loop Trap', 'Prerequisites: Lesson 3.2', 'Prerequisites: Lesson 3.2 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 150.0, '# Lesson 3.3: Quadratic O(N^2) & The Nested Loop Trap

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.2
- **Subtopics**:
  - `3.3.1` The nested loop trap: running a loop of size N inside another loop of size N.
  - `3.3.2` Why O(N^2) breaks at scale: processing 1,000 items takes 1,000,000 steps; 100,000 items takes 10 billion steps!
  - `3.3.3` Common hidden nested loops: calling item in list or list.count() inside an outer for loop.
  - `3.3.4` How to identify quadratic bottlenecks in code reviews before they reach production.
- **Key Failure Modes & Edge Cases**: Writing nested loops to check for duplicates across two lists instead of using a hash set.
- **Verification & Mastery Check**: Take an O(N^2) duplicate finder and measure its runtime on a 50,000-item list.
- **Project Application**: StreamBuffer: Identifying algorithmic bottlenecks.', '{"solution.py": "# Phase 3 // Lesson 3.3: Quadratic O(N^2) & The Nested Loop Trap\n\ndef solve():\n    \"\"\"\n    Verification: Take an O(N^2) duplicate finder and measure its runtime on a 50,000-item list.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.3", "subtopics_count": 4, "verification_criteria": "Take an O(N^2) duplicate finder and measure its runtime on a 50,000-item list.", "subtopics": ["3.3.1 The nested loop trap: running a loop of size N inside another loop of size N.", "3.3.2 Why O(N^2) breaks at scale: processing 1,000 items takes 1,000,000 steps; 100,000 items takes 10 billion steps!", "3.3.3 Common hidden nested loops: calling item in list or list.count() inside an outer for loop.", "3.3.4 How to identify quadratic bottlenecks in code reviews before they reach production."]}'::jsonb, '["Explain how this implementation prevents: Writing nested loops to check for duplicates across two lists instead of using a hash set.", "How does Quadratic O(N^2) & The Nested Loop Trap scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-4', 'phase-03-lesson-04-logarithmic-o-log-n-divide-and-conquer', 'module-5', 4, 'Lesson 5.4: Logarithmic O(log N) & Divide and Conquer', 'Prerequisites: Lesson 3.1', 'Prerequisites: Lesson 3.1 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 200.0, '# Lesson 3.4: Logarithmic O(log N) & Divide and Conquer

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.1
- **Subtopics**:
  - `3.4.1` The power of cutting problems in half: why dividing search spaces is so blindingly fast.
  - `3.4.2` The phone book analogy: finding a name by opening to the middle and discarding half the book.
  - `3.4.3` Logarithmic scaling: searching 1,000 items takes 10 steps; searching 1,000,000,000 items takes only 30 steps!
  - `3.4.4` Identifying divide-and-conquer algorithms in real-world systems (binary search, balanced trees).
- **Key Failure Modes & Edge Cases**: Applying binary search to an unsorted list without sorting it first, producing completely wrong results.
- **Verification & Mastery Check**: Calculate how many comparison steps binary search needs to locate an item in a dataset of 4 billion records.
- **Project Application**: StreamBuffer: Scalable search mechanics.', '{"solution.py": "# Phase 3 // Lesson 3.4: Logarithmic O(log N) & Divide and Conquer\n\ndef solve():\n    \"\"\"\n    Verification: Calculate how many comparison steps binary search needs to locate an item in a dataset of 4 billion \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.4", "subtopics_count": 4, "verification_criteria": "Calculate how many comparison steps binary search needs to locate an item in a dataset of 4 billion records.", "subtopics": ["3.4.1 The power of cutting problems in half: why dividing search spaces is so blindingly fast.", "3.4.2 The phone book analogy: finding a name by opening to the middle and discarding half the book.", "3.4.3 Logarithmic scaling: searching 1,000 items takes 10 steps; searching 1,000,000,000 items takes only 30 steps!", "3.4.4 Identifying divide-and-conquer algorithms in real-world systems (binary search, balanced trees)."]}'::jsonb, '["Explain how this implementation prevents: Applying binary search to an unsorted list without sorting it first, producing completely wrong results.", "How does Logarithmic O(log N) & Divide and Conquer scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-5', 'phase-03-lesson-05-two-pointers-opposing-direction-convergin', 'module-5', 5, 'Lesson 5.5: Two Pointers: Opposing Direction Converging', 'Prerequisites: Lesson 3.2', 'Prerequisites: Lesson 3.2 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 250.0, '# Lesson 3.5: Two Pointers: Opposing Direction Converging

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.2
- **Subtopics**:
  - `3.5.1` The two-pointer technique: using two coordinate indices simultaneously to inspect an array.
  - `3.5.2` Opposing pointers: starting Left at index 0 and Right at index N-1, stepping inward toward each other.
  - `3.5.3` Solving Two-Sum on sorted arrays: moving Left when sum is too small, moving Right when sum is too large.
  - `3.5.4` Why two pointers turns an O(N^2) brute-force nested search into an optimal single-pass O(N) solution.
- **Key Failure Modes & Edge Cases**: Pointer crossing bugs: forgetting the while left < right boundary condition, causing pointers to cross.
- **Verification & Mastery Check**: Implement two-pointer Two-Sum on a sorted list and prove it finds target pairs in single-pass O(N) time.
- **Project Application**: StreamBuffer: Paired token matching.', '{"solution.py": "# Phase 3 // Lesson 3.5: Two Pointers: Opposing Direction Converging\n\ndef solve():\n    \"\"\"\n    Verification: Implement two-pointer Two-Sum on a sorted list and prove it finds target pairs in single-pass O(N) t\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.5", "subtopics_count": 4, "verification_criteria": "Implement two-pointer Two-Sum on a sorted list and prove it finds target pairs in single-pass O(N) time.", "subtopics": ["3.5.1 The two-pointer technique: using two coordinate indices simultaneously to inspect an array.", "3.5.2 Opposing pointers: starting Left at index 0 and Right at index N-1, stepping inward toward each other.", "3.5.3 Solving Two-Sum on sorted arrays: moving Left when sum is too small, moving Right when sum is too large.", "3.5.4 Why two pointers turns an O(N^2) brute-force nested search into an optimal single-pass O(N) solution."]}'::jsonb, '["Explain how this implementation prevents: Pointer crossing bugs: forgetting the while left < right boundary condition, causing pointers to cross.", "How does Two Pointers: Opposing Direction Converging scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-6', 'phase-03-lesson-06-two-pointers-fast-slow-pointer-cycle-dete', 'module-5', 6, 'Lesson 5.6: Two Pointers: Fast & Slow Pointer (Cycle Detection)', 'Prerequisites: Lesson 3.5', 'Prerequisites: Lesson 3.5 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 300.0, '# Lesson 3.6: Two Pointers: Fast & Slow Pointer (Cycle Detection)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.5
- **Subtopics**:
  - `3.6.1` Same-direction pointers: two pointers starting at the beginning and moving forward at different speeds.
  - `3.6.2` The Tortoise and Hare algorithm: slow pointer moves 1 step while fast pointer moves 2 steps.
  - `3.6.3` Cycle detection intuition: if a runner and a walker circle a closed track, the runner will eventually lap the walker.
  - `3.6.4` Applications: detecting infinite loops, finding list midpoints, and cycle detection in state graphs.
- **Key Failure Modes & Edge Cases**: Dereferencing null pointer in fast.next.next without checking if fast or fast.next is None.
- **Verification & Mastery Check**: Implement Floyd''s cycle-finding algorithm to detect whether a linked sequence contains an infinite loop.
- **Project Application**: StreamBuffer: Agent loop cycle detection.', '{"solution.py": "# Phase 3 // Lesson 3.6: Two Pointers: Fast & Slow Pointer (Cycle Detection)\n\ndef solve():\n    \"\"\"\n    Verification: Implement Floyd''s cycle-finding algorithm to detect whether a linked sequence contains an infinite l\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.6", "subtopics_count": 4, "verification_criteria": "Implement Floyd''s cycle-finding algorithm to detect whether a linked sequence contains an infinite loop.", "subtopics": ["3.6.1 Same-direction pointers: two pointers starting at the beginning and moving forward at different speeds.", "3.6.2 The Tortoise and Hare algorithm: slow pointer moves 1 step while fast pointer moves 2 steps.", "3.6.3 Cycle detection intuition: if a runner and a walker circle a closed track, the runner will eventually lap the walker.", "3.6.4 Applications: detecting infinite loops, finding list midpoints, and cycle detection in state graphs."]}'::jsonb, '["Explain how this implementation prevents: Dereferencing null pointer in fast.next.next without checking if fast or fast.next is None.", "How does Two Pointers: Fast & Slow Pointer (Cycle Detection) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-7', 'phase-03-lesson-07-sliding-window-fixed-size-subarrays', 'module-5', 7, 'Lesson 5.7: Sliding Window: Fixed Size Subarrays', 'Prerequisites: Lesson 3.2', 'Prerequisites: Lesson 3.2 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 350.0, '# Lesson 3.7: Sliding Window: Fixed Size Subarrays

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.2
- **Subtopics**:
  - `3.7.1` The sliding window paradigm: maintaining a visible slice of size K across a continuous stream of data.
  - `3.7.2` Incremental updates: sliding the window by adding the new element on the right and subtracting the old on left.
  - `3.7.3` Why sliding windows achieve O(N): avoiding re-calculating the entire window from scratch on every step.
  - `3.7.4` Practical applications: calculating rolling average CPU usage, moving token limits, and network throughput.
- **Key Failure Modes & Edge Cases**: Recomputing sum(window) inside every step, degenerating the algorithm back to O(N * K).
- **Verification & Mastery Check**: Write a function that calculates the maximum sum of any contiguous subarray of fixed length K in O(N) time.
- **Project Application**: StreamBuffer: Rolling metrics sliding window.', '{"solution.py": "# Phase 3 // Lesson 3.7: Sliding Window: Fixed Size Subarrays\n\ndef solve():\n    \"\"\"\n    Verification: Write a function that calculates the maximum sum of any contiguous subarray of fixed length K in O(N\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.7", "subtopics_count": 4, "verification_criteria": "Write a function that calculates the maximum sum of any contiguous subarray of fixed length K in O(N) time.", "subtopics": ["3.7.1 The sliding window paradigm: maintaining a visible slice of size K across a continuous stream of data.", "3.7.2 Incremental updates: sliding the window by adding the new element on the right and subtracting the old on left.", "3.7.3 Why sliding windows achieve O(N): avoiding re-calculating the entire window from scratch on every step.", "3.7.4 Practical applications: calculating rolling average CPU usage, moving token limits, and network throughput."]}'::jsonb, '["Explain how this implementation prevents: Recomputing sum(window) inside every step, degenerating the algorithm back to O(N * K).", "How does Sliding Window: Fixed Size Subarrays scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-8', 'phase-03-lesson-08-sliding-window-dynamic-size-subarrays', 'module-5', 8, 'Lesson 5.8: Sliding Window: Dynamic Size Subarrays', 'Prerequisites: Lesson 3.7', 'Prerequisites: Lesson 3.7 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 400.0, '# Lesson 3.8: Sliding Window: Dynamic Size Subarrays

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.7
- **Subtopics**:
  - `3.8.1` Flexible windows: expanding the right edge until a condition is met, then contracting the left edge.
  - `3.8.2` The dynamic pattern: expand right to explore, shrink left to satisfy constraints.
  - `3.8.3` Tracking window state: keeping character frequency counts or running sums inside the window.
  - `3.8.4` Canonical problems: shortest subarray with sum >= target, longest substring without repeating characters.
- **Key Failure Modes & Edge Cases**: Shrinking the left pointer past the right pointer or failing to update the window state dictionary.
- **Verification & Mastery Check**: Find the length of the longest substring without repeating characters using a dynamic sliding window in O(N).
- **Project Application**: StreamBuffer: Variable-length context buffer slicing.', '{"solution.py": "# Phase 3 // Lesson 3.8: Sliding Window: Dynamic Size Subarrays\n\ndef solve():\n    \"\"\"\n    Verification: Find the length of the longest substring without repeating characters using a dynamic sliding window\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.8", "subtopics_count": 4, "verification_criteria": "Find the length of the longest substring without repeating characters using a dynamic sliding window in O(N).", "subtopics": ["3.8.1 Flexible windows: expanding the right edge until a condition is met, then contracting the left edge.", "3.8.2 The dynamic pattern: expand right to explore, shrink left to satisfy constraints.", "3.8.3 Tracking window state: keeping character frequency counts or running sums inside the window.", "3.8.4 Canonical problems: shortest subarray with sum >= target, longest substring without repeating characters."]}'::jsonb, '["Explain how this implementation prevents: Shrinking the left pointer past the right pointer or failing to update the window state dictionary.", "How does Sliding Window: Dynamic Size Subarrays scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-9', 'phase-03-lesson-09-prefix-sums-range-sum-query-in-o-1', 'module-5', 9, 'Lesson 5.9: Prefix Sums: Range Sum Query in O(1)', 'Prerequisites: Lesson 3.2', 'Prerequisites: Lesson 3.2 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 450.0, '# Lesson 3.9: Prefix Sums: Range Sum Query in O(1)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.2
- **Subtopics**:
  - `3.9.1` Pre-computing cumulative sums: building an array where prefix[i] stores the sum of all elements up to i.
  - `3.9.2` Instant range queries: calculating the sum between index L and R in exact O(1) time: prefix[R] - prefix[L-1].
  - `3.9.3` Trading memory for speed: spending O(N) storage to make all future range calculations instantaneous.
  - `3.9.4` Applications: computing cumulative cost over time windows and fast 2D image box filtering.
- **Key Failure Modes & Edge Cases**: Off-by-one errors when querying ranges that start at index 0, requiring a padded 0 at prefix[0].
- **Verification & Mastery Check**: Build a PrefixSum class that takes an array of numbers and answers 1,000 range sum queries in O(1) each.
- **Project Application**: StreamBuffer: Rapid range query calculations.', '{"solution.py": "# Phase 3 // Lesson 3.9: Prefix Sums: Range Sum Query in O(1)\n\ndef solve():\n    \"\"\"\n    Verification: Build a PrefixSum class that takes an array of numbers and answers 1,000 range sum queries in O(1) e\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.9", "subtopics_count": 4, "verification_criteria": "Build a PrefixSum class that takes an array of numbers and answers 1,000 range sum queries in O(1) each.", "subtopics": ["3.9.1 Pre-computing cumulative sums: building an array where prefix[i] stores the sum of all elements up to i.", "3.9.2 Instant range queries: calculating the sum between index L and R in exact O(1) time: prefix[R] - prefix[L-1].", "3.9.3 Trading memory for speed: spending O(N) storage to make all future range calculations instantaneous.", "3.9.4 Applications: computing cumulative cost over time windows and fast 2D image box filtering."]}'::jsonb, '["Explain how this implementation prevents: Off-by-one errors when querying ranges that start at index 0, requiring a padded 0 at prefix[0].", "How does Prefix Sums: Range Sum Query in O(1) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-10', 'phase-03-lesson-10-frequency-maps-counting-elements-with-dic', 'module-5', 10, 'Lesson 5.10: Frequency Maps: Counting Elements with Dicts', 'Prerequisites: Phase 0 (Lesson 0.13), Lesson 3.2', 'Prerequisites: Phase 0 (Lesson 0.13), Lesson 3.2 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 500.0, '# Lesson 3.10: Frequency Maps: Counting Elements with Dicts

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.13), Lesson 3.2
- **Subtopics**:
  - `3.10.1` Counting frequencies: using hash maps to track how many times each item appears in a collection.
  - `3.10.2` The Python collections.Counter helper: counting elements in one line with high performance.
  - `3.10.3` Finding most common elements: getting top-K frequencies efficiently.
  - `3.10.4` Detecting anagrams and character distributions in text streams.
- **Key Failure Modes & Edge Cases**: Looking up keys without default values, triggering KeyError when encountering new elements.
- **Verification & Mastery Check**: Given a stream of user messages, count word frequencies and return the top 5 most common words.
- **Project Application**: StreamBuffer: Stream token frequency analyzer.', '{"solution.py": "# Phase 3 // Lesson 3.10: Frequency Maps: Counting Elements with Dicts\n\ndef solve():\n    \"\"\"\n    Verification: Given a stream of user messages, count word frequencies and return the top 5 most common words.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.10", "subtopics_count": 4, "verification_criteria": "Given a stream of user messages, count word frequencies and return the top 5 most common words.", "subtopics": ["3.10.1 Counting frequencies: using hash maps to track how many times each item appears in a collection.", "3.10.2 The Python collections.Counter helper: counting elements in one line with high performance.", "3.10.3 Finding most common elements: getting top-K frequencies efficiently.", "3.10.4 Detecting anagrams and character distributions in text streams."]}'::jsonb, '["Explain how this implementation prevents: Looking up keys without default values, triggering KeyError when encountering new elements.", "How does Frequency Maps: Counting Elements with Dicts scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-11', 'phase-03-lesson-11-binary-search-standard-sorted-array-looku', 'module-5', 11, 'Lesson 5.11: Binary Search: Standard Sorted Array Lookup', 'Prerequisites: Lesson 3.4', 'Prerequisites: Lesson 3.4 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 550.0, '# Lesson 3.11: Binary Search: Standard Sorted Array Lookup

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.4
- **Subtopics**:
  - `3.11.1` Binary search requirements: why the underlying collection MUST be sorted before binary search can work.
  - `3.11.2` The three pointers: low, mid, and high.
  - `3.11.3` Avoiding integer overflow: calculating mid as low + (high - low) // 2.
  - `3.11.4` Updating bounds: mid + 1 when target is larger, mid - 1 when target is smaller.
- **Key Failure Modes & Edge Cases**: Forgetting to add or subtract 1 when updating high and low, causing infinite while loops.
- **Verification & Mastery Check**: Implement binary search from memory in pure Python and prove it finds targets in a 1,000,000-item sorted list.
- **Project Application**: StreamBuffer: Fast log index lookup.', '{"solution.py": "# Phase 3 // Lesson 3.11: Binary Search: Standard Sorted Array Lookup\n\ndef solve():\n    \"\"\"\n    Verification: Implement binary search from memory in pure Python and prove it finds targets in a 1,000,000-item so\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.11", "subtopics_count": 4, "verification_criteria": "Implement binary search from memory in pure Python and prove it finds targets in a 1,000,000-item sorted list.", "subtopics": ["3.11.1 Binary search requirements: why the underlying collection MUST be sorted before binary search can work.", "3.11.2 The three pointers: low, mid, and high.", "3.11.3 Avoiding integer overflow: calculating mid as low + (high - low) // 2.", "3.11.4 Updating bounds: mid + 1 when target is larger, mid - 1 when target is smaller."]}'::jsonb, '["Explain how this implementation prevents: Forgetting to add or subtract 1 when updating high and low, causing infinite while loops.", "How does Binary Search: Standard Sorted Array Lookup scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-12', 'phase-03-lesson-12-binary-search-finding-lower-and-upper-bou', 'module-5', 12, 'Lesson 5.12: Binary Search: Finding Lower and Upper Bounds', 'Prerequisites: Lesson 3.11', 'Prerequisites: Lesson 3.11 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 600.0, '# Lesson 3.12: Binary Search: Finding Lower and Upper Bounds

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.11
- **Subtopics**:
  - `3.12.1` Handling duplicates in sorted data: finding the first or last occurrence of a target value.
  - `3.12.2` Lower bound: finding the smallest index where array[index] >= target.
  - `3.12.3` Upper bound: finding the smallest index where array[index] > target.
  - `3.12.4` Range queries: counting how many times a value appears in a sorted list using upper_bound - lower_bound.
- **Key Failure Modes & Edge Cases**: Returning the first match found without continuing search toward the left boundary when duplicates exist.
- **Verification & Mastery Check**: Find the starting and ending index of a target value in a sorted array containing duplicate numbers.
- **Project Application**: StreamBuffer: Timestamp boundary searches.', '{"solution.py": "# Phase 3 // Lesson 3.12: Binary Search: Finding Lower and Upper Bounds\n\ndef solve():\n    \"\"\"\n    Verification: Find the starting and ending index of a target value in a sorted array containing duplicate numbers.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.12", "subtopics_count": 4, "verification_criteria": "Find the starting and ending index of a target value in a sorted array containing duplicate numbers.", "subtopics": ["3.12.1 Handling duplicates in sorted data: finding the first or last occurrence of a target value.", "3.12.2 Lower bound: finding the smallest index where array[index] >= target.", "3.12.3 Upper bound: finding the smallest index where array[index] > target.", "3.12.4 Range queries: counting how many times a value appears in a sorted list using upper_bound - lower_bound."]}'::jsonb, '["Explain how this implementation prevents: Returning the first match found without continuing search toward the left boundary when duplicates exist.", "How does Binary Search: Finding Lower and Upper Bounds scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-13', 'phase-03-lesson-13-binary-search-on-solution-space', 'module-5', 13, 'Lesson 5.13: Binary Search on Solution Space', 'Prerequisites: Lesson 3.11', 'Prerequisites: Lesson 3.11 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 650.0, '# Lesson 3.13: Binary Search on Solution Space

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.11
- **Subtopics**:
  - `3.13.1` Searching without an array: using binary search to find an optimal answer value directly.
  - `3.13.2` Monotonic condition: if an answer X is possible, all values > X are also possible (or vice versa).
  - `3.13.3` The feasibility function: a helper function that checks can_fulfill(capacity) in O(N).
  - `3.13.4` Canonical problems: capacity to ship packages within D days, splitting arrays to minimize largest sum.
- **Key Failure Modes & Edge Cases**: Setting improper search range boundaries (low and high) that fail to include the true optimal solution.
- **Verification & Mastery Check**: Calculate the minimum rate limit bucket capacity needed to process a stream of jobs within a fixed deadline.
- **Project Application**: StreamBuffer: Adaptive rate limit capacity tuning.', '{"solution.py": "# Phase 3 // Lesson 3.13: Binary Search on Solution Space\n\ndef solve():\n    \"\"\"\n    Verification: Calculate the minimum rate limit bucket capacity needed to process a stream of jobs within a fixed d\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.13", "subtopics_count": 4, "verification_criteria": "Calculate the minimum rate limit bucket capacity needed to process a stream of jobs within a fixed deadline.", "subtopics": ["3.13.1 Searching without an array: using binary search to find an optimal answer value directly.", "3.13.2 Monotonic condition: if an answer X is possible, all values > X are also possible (or vice versa).", "3.13.3 The feasibility function: a helper function that checks can_fulfill(capacity) in O(N).", "3.13.4 Canonical problems: capacity to ship packages within D days, splitting arrays to minimize largest sum."]}'::jsonb, '["Explain how this implementation prevents: Setting improper search range boundaries (low and high) that fail to include the true optimal solution.", "How does Binary Search on Solution Space scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-14', 'phase-03-lesson-14-recursion-base-cases-call-stack-frames', 'module-5', 14, 'Lesson 5.14: Recursion: Base Cases & Call Stack Frames', 'Prerequisites: Phase 0 (Lesson 0.8)', 'Prerequisites: Phase 0 (Lesson 0.8) | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 700.0, '# Lesson 3.14: Recursion: Base Cases & Call Stack Frames

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.8)
- **Subtopics**:
  - `3.14.1` What is recursion: a function that solves a problem by calling itself on smaller sub-problems.
  - `3.14.2` The two essential parts: the Base Case (when to stop) and the Recursive Case (the step forward).
  - `3.14.3` The Call Stack: how Python allocates a new stack frame in memory for every recursive invocation.
  - `3.14.4` Recursion depth limits: understanding why Python stops at 1,000 nested calls to prevent stack overflow.
- **Key Failure Modes & Edge Cases**: Omitting or incorrectly defining the base case, triggering RecursionError: maximum recursion depth exceeded.
- **Verification & Mastery Check**: Write a recursive function that reverses a string and visualize its call stack frames on paper.
- **Project Application**: StreamBuffer: Recursive document parsing.', '{"solution.py": "# Phase 3 // Lesson 3.14: Recursion: Base Cases & Call Stack Frames\n\ndef solve():\n    \"\"\"\n    Verification: Write a recursive function that reverses a string and visualize its call stack frames on paper.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.14", "subtopics_count": 4, "verification_criteria": "Write a recursive function that reverses a string and visualize its call stack frames on paper.", "subtopics": ["3.14.1 What is recursion: a function that solves a problem by calling itself on smaller sub-problems.", "3.14.2 The two essential parts: the Base Case (when to stop) and the Recursive Case (the step forward).", "3.14.3 The Call Stack: how Python allocates a new stack frame in memory for every recursive invocation.", "3.14.4 Recursion depth limits: understanding why Python stops at 1,000 nested calls to prevent stack overflow."]}'::jsonb, '["Explain how this implementation prevents: Omitting or incorrectly defining the base case, triggering RecursionError: maximum recursion depth exceeded.", "How does Recursion: Base Cases & Call Stack Frames scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-15', 'phase-03-lesson-15-tree-traversals-pre-order-in-order-post-o', 'module-5', 15, 'Lesson 5.15: Tree Traversals: Pre-Order, In-Order, Post-Order', 'Prerequisites: Lesson 3.14', 'Prerequisites: Lesson 3.14 | Subtopics: 5 items', 'Systems project application', 160, 4, 750.0, 750.0, '# Lesson 3.15: Tree Traversals: Pre-Order, In-Order, Post-Order

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.14
- **Subtopics**:
  - `3.15.1` Hierarchical data structures: trees composed of root, child nodes, and leaves.
  - `3.15.2` Binary trees: trees where each node has at most two children (left and right).
  - `3.15.3` Pre-Order traversal (Root, Left, Right): useful for copying or serializing trees.
  - `3.15.4` In-Order traversal (Left, Root, Right): visiting sorted binary search trees in ascending numerical order.
  - `3.15.5` Post-Order traversal (Left, Right, Root): useful for deleting trees or calculating bottom-up sizes.
- **Key Failure Modes & Edge Cases**: Failing to check if current node is None before attempting to access node.left or node.right.
- **Verification & Mastery Check**: Construct a simple 5-node binary tree and implement all three depth-first traversal orders.
- **Project Application**: StreamBuffer: AST node traversal.', '{"solution.py": "# Phase 3 // Lesson 3.15: Tree Traversals: Pre-Order, In-Order, Post-Order\n\ndef solve():\n    \"\"\"\n    Verification: Construct a simple 5-node binary tree and implement all three depth-first traversal orders.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.15", "subtopics_count": 5, "verification_criteria": "Construct a simple 5-node binary tree and implement all three depth-first traversal orders.", "subtopics": ["3.15.1 Hierarchical data structures: trees composed of root, child nodes, and leaves.", "3.15.2 Binary trees: trees where each node has at most two children (left and right).", "3.15.3 Pre-Order traversal (Root, Left, Right): useful for copying or serializing trees.", "3.15.4 In-Order traversal (Left, Root, Right): visiting sorted binary search trees in ascending numerical order.", "3.15.5 Post-Order traversal (Left, Right, Root): useful for deleting trees or calculating bottom-up sizes."]}'::jsonb, '["Explain how this implementation prevents: Failing to check if current node is None before attempting to access node.left or node.right.", "How does Tree Traversals: Pre-Order, In-Order, Post-Order scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
