INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-6-16', 'phase-06-lesson-16-modern-typescript-frontend-tooling-vite-e', 'module-8', 16, 'Lesson 8.16: Modern TypeScript Frontend Tooling: Vite, ESBuild & Monorepos', 'Prerequisites: Phase 1, Lesson 6.1', 'Prerequisites: Phase 1, Lesson 6.1 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 800.0, '# Lesson 6.16: Modern TypeScript Frontend Tooling: Vite, ESBuild & Monorepos

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Lesson 6.1
- **Subtopics**:
  - `6.16.1` Vite architecture: unbundled native ES Modules in development vs Rollup tree-shaken production bundles
  - `6.16.2` ESBuild internals: Go-based compilation, AST transformation, and lightning-fast transpilation speeds
  - `6.16.3` Module resolution algorithms: Node16/NodeNext vs Bundler resolution in tsconfig.json
  - `6.16.4` Monorepo architecture with Turborepo: task pipelines, remote caching, workspace dependency graphs, and package scoping
  - `6.16.5` Environment variable hygiene: import.meta.env, compile-time variable injection, and leaking secrets mitigation
  - `6.16.6` Source maps: VLQ encoding, production security implications, and error boundary stack trace remapping
- **Key Failure Modes & Edge Cases**: Accidentally leaking server environment variables into Vite client bundles; broken ESM interop with CommonJS packages.
- **Verification & Mastery Check**: Set up a high-performance Turborepo containing shared TypeScript UI libraries, linting rules, and Vite-powered dev environments.
- **Project Application**: CompKit & TenantIQ: Monorepo workspace orchestration.', '{"solution.py": "# Phase 6 // Lesson 6.16: Modern TypeScript Frontend Tooling: Vite, ESBuild & Monorepos\n\ndef solve():\n    \"\"\"\n    Verification: Set up a high-performance Turborepo containing shared TypeScript UI libraries, linting rules, and Vi\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.16", "subtopics_count": 6, "verification_criteria": "Set up a high-performance Turborepo containing shared TypeScript UI libraries, linting rules, and Vite-powered dev environments.", "subtopics": ["6.16.1 Vite architecture: unbundled native ES Modules in development vs Rollup tree-shaken production bundles", "6.16.2 ESBuild internals: Go-based compilation, AST transformation, and lightning-fast transpilation speeds", "6.16.3 Module resolution algorithms: Node16/NodeNext vs Bundler resolution in tsconfig.json", "6.16.4 Monorepo architecture with Turborepo: task pipelines, remote caching, workspace dependency graphs, and package scoping", "6.16.5 Environment variable hygiene: import.meta.env, compile-time variable injection, and leaking secrets mitigation", "6.16.6 Source maps: VLQ encoding, production security implications, and error boundary stack trace remapping"]}'::jsonb, '["Explain how this implementation prevents: Accidentally leaking server environment variables into Vite client bundles; broken ESM interop with CommonJS packages.", "How does Modern TypeScript Frontend Tooling: Vite, ESBuild & Monorepos scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-17', 'phase-06-lesson-17-react-architectural-evolution-the-virtual', 'module-8', 17, 'Lesson 8.17: React Architectural Evolution & The Virtual DOM Paradigm', 'Prerequisites: Lesson 6.1, Lesson 6.13', 'Prerequisites: Lesson 6.1, Lesson 6.13 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 850.0, '# Lesson 6.17: React Architectural Evolution & The Virtual DOM Paradigm

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.1, Lesson 6.13
- **Subtopics**:
  - `6.17.1` Why Virtual DOM: historical context, declarative UI vs imperative DOM manipulation trade-offs
  - `6.17.2` React elements: lightweight immutable JS objects representing UI trees (`$$typeof: Symbol(react.element)`)
  - `6.17.3` Reconciliation algorithm: diffing heuristics, O(n) assumptions, element type matching, and the role of `key`
  - `6.17.4` Keys in lists: index as key anti-pattern, state preservation bugs, and structural tree reconciliation
  - `6.17.5` Component purity: deterministic rendering, idempotency, side-effect boundaries, and StrictMode double-rendering
  - `6.17.6` JSX transpilation: classic runtime (`React.createElement`) vs modern automatic runtime (`_jsx`)
- **Key Failure Modes & Edge Cases**: Using math.random() or array index as list keys causing input focus loss and internal component state corruptions.
- **Verification & Mastery Check**: Write a mini-reconciler in pure TypeScript that diffs two nested JSON UI trees and emits minimal DOM mutations.
- **Project Application**: CompKit: Declarative component abstraction foundations.', '{"solution.py": "# Phase 6 // Lesson 6.17: React Architectural Evolution & The Virtual DOM Paradigm\n\ndef solve():\n    \"\"\"\n    Verification: Write a mini-reconciler in pure TypeScript that diffs two nested JSON UI trees and emits minimal DOM\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.17", "subtopics_count": 6, "verification_criteria": "Write a mini-reconciler in pure TypeScript that diffs two nested JSON UI trees and emits minimal DOM mutations.", "subtopics": ["6.17.1 Why Virtual DOM: historical context, declarative UI vs imperative DOM manipulation trade-offs", "6.17.2 React elements: lightweight immutable JS objects representing UI trees (`$$typeof: Symbol(react.element)`)", "6.17.3 Reconciliation algorithm: diffing heuristics, O(n) assumptions, element type matching, and the role of `key`", "6.17.4 Keys in lists: index as key anti-pattern, state preservation bugs, and structural tree reconciliation", "6.17.5 Component purity: deterministic rendering, idempotency, side-effect boundaries, and StrictMode double-rendering", "6.17.6 JSX transpilation: classic runtime (`React.createElement`) vs modern automatic runtime (`_jsx`)"]}'::jsonb, '["Explain how this implementation prevents: Using math.random() or array index as list keys causing input focus loss and internal component state corruptions.", "How does React Architectural Evolution & The Virtual DOM Paradigm scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-18', 'phase-06-lesson-18-react-fiber-architecture-reconciler-mecha', 'module-8', 18, 'Lesson 8.18: React Fiber Architecture & Reconciler Mechanics', 'Prerequisites: Lesson 6.17', 'Prerequisites: Lesson 6.17 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 900.0, '# Lesson 6.18: React Fiber Architecture & Reconciler Mechanics

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.17
- **Subtopics**:
  - `6.18.1` The Stack reconciler limitations: blocking recursive call stack causing frame drops and unresponsive UIs
  - `6.18.2` Fiber node data structure: child, sibling, return pointers, alternate fibers, and workInProgress trees
  - `6.18.3` Double buffering technique: current tree vs workInProgress tree swapping upon commit
  - `6.18.4` Two-phase processing: Render Phase (cooperative, interruptible, asynchronous) vs Commit Phase (synchronous, DOM mutations)
  - `6.18.5` Scheduler mechanics: cooperative scheduling, MessageChannel task queuing, and browser frame budget management
  - `6.18.6` Priority lanes: SyncLane, InputContinuousLane, DefaultLane, and IdleLane bitmask prioritization
- **Key Failure Modes & Edge Cases**: Triggering side-effects inside render phase leading to multi-execution bugs during interrupted concurrent renders.
- **Verification & Mastery Check**: Inspect React Fiber nodes via browser console symbols; trace fiber tree links and verify lane priority scheduling.
- **Project Application**: CompKit: High-performance rendering pipeline optimization.', '{"solution.py": "# Phase 6 // Lesson 6.18: React Fiber Architecture & Reconciler Mechanics\n\ndef solve():\n    \"\"\"\n    Verification: Inspect React Fiber nodes via browser console symbols; trace fiber tree links and verify lane priori\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.18", "subtopics_count": 6, "verification_criteria": "Inspect React Fiber nodes via browser console symbols; trace fiber tree links and verify lane priority scheduling.", "subtopics": ["6.18.1 The Stack reconciler limitations: blocking recursive call stack causing frame drops and unresponsive UIs", "6.18.2 Fiber node data structure: child, sibling, return pointers, alternate fibers, and workInProgress trees", "6.18.3 Double buffering technique: current tree vs workInProgress tree swapping upon commit", "6.18.4 Two-phase processing: Render Phase (cooperative, interruptible, asynchronous) vs Commit Phase (synchronous, DOM mutations)", "6.18.5 Scheduler mechanics: cooperative scheduling, MessageChannel task queuing, and browser frame budget management", "6.18.6 Priority lanes: SyncLane, InputContinuousLane, DefaultLane, and IdleLane bitmask prioritization"]}'::jsonb, '["Explain how this implementation prevents: Triggering side-effects inside render phase leading to multi-execution bugs during interrupted concurrent renders.", "How does React Fiber Architecture & Reconciler Mechanics scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-19', 'phase-06-lesson-19-react-component-lifecycle-strictmode-inva', 'module-8', 19, 'Lesson 8.19: React Component Lifecycle & StrictMode Invariants', 'Prerequisites: Lesson 6.18', 'Prerequisites: Lesson 6.18 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 950.0, '# Lesson 6.19: React Component Lifecycle & StrictMode Invariants

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.18
- **Subtopics**:
  - `6.19.1` Component lifecycle stages: Mount, Update, Unmount, and Error capture boundaries
  - `6.19.2` React StrictMode deep dive: intentionally double-invoking render functions, state updaters, and effect hooks
  - `6.19.3` Detecting accidental impurity: spotting memory leaks, dangling listeners, and non-resilient effect logic
  - `6.19.4` React Error Boundaries: componentDidCatch, getDerivedStateFromError, and declarative fallback UI rendering
  - `6.19.5` Component composition patterns: compound components, render props, and slot-based layout distribution
  - `6.19.6` Dynamic component loading: React.lazy, Suspense boundaries, and code-splitting waterfall mitigation
- **Key Failure Modes & Edge Cases**: Failure to cleanup event listeners in useEffect manifesting only after unmount in production; unhandled render crash taking down entire app.
- **Verification & Mastery Check**: Implement a battle-tested ErrorBoundary component with crash telemetry reporting and state-reset recovery actions.
- **Project Application**: CompKit: Resilient production Error Boundary and compound modal primitives.', '{"solution.py": "# Phase 6 // Lesson 6.19: React Component Lifecycle & StrictMode Invariants\n\ndef solve():\n    \"\"\"\n    Verification: Implement a battle-tested ErrorBoundary component with crash telemetry reporting and state-reset rec\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.19", "subtopics_count": 6, "verification_criteria": "Implement a battle-tested ErrorBoundary component with crash telemetry reporting and state-reset recovery actions.", "subtopics": ["6.19.1 Component lifecycle stages: Mount, Update, Unmount, and Error capture boundaries", "6.19.2 React StrictMode deep dive: intentionally double-invoking render functions, state updaters, and effect hooks", "6.19.3 Detecting accidental impurity: spotting memory leaks, dangling listeners, and non-resilient effect logic", "6.19.4 React Error Boundaries: componentDidCatch, getDerivedStateFromError, and declarative fallback UI rendering", "6.19.5 Component composition patterns: compound components, render props, and slot-based layout distribution", "6.19.6 Dynamic component loading: React.lazy, Suspense boundaries, and code-splitting waterfall mitigation"]}'::jsonb, '["Explain how this implementation prevents: Failure to cleanup event listeners in useEffect manifesting only after unmount in production; unhandled render crash tak", "How does React Component Lifecycle & StrictMode Invariants scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-20', 'phase-06-lesson-20-react-hooks-internals-usestate-usereducer', 'module-8', 20, 'Lesson 8.20: React Hooks Internals: useState, useReducer & State Queues', 'Prerequisites: Lesson 6.18, Lesson 6.19', 'Prerequisites: Lesson 6.18, Lesson 6.19 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 1000.0, '# Lesson 6.20: React Hooks Internals: useState, useReducer & State Queues

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.18, Lesson 6.19
- **Subtopics**:
  - `6.20.1` Hooks data structure: singly linked list of hook records anchored to the current Fiber node (`memoizedState`)
  - `6.20.2` The Rules of Hooks: why hooks must be called unconditionally at top level to maintain linked list index parity
  - `6.20.3` useState internals: update queues, pending update circular lists, and eager state evaluation optimizations
  - `6.20.4` useReducer mechanics: action dispatching, reducer pure functions, and shared underlying implementation with useState
  - `6.20.5` Batching in React 18: Automatic batching across promises, setTimeout, and native event handlers
  - `6.20.6` Functional state updates (`setCount(c => c + 1)`) vs direct value passing under stale closure conditions
- **Key Failure Modes & Edge Cases**: Violating the rules of hooks with conditional statements; stale closures reading outdated state values inside callbacks.
- **Verification & Mastery Check**: Implement an in-memory clone of `useState` and `useReducer` backed by an array of linked hook records.
- **Project Application**: CompKit: State primitives and custom form-state hooks.', '{"solution.py": "# Phase 6 // Lesson 6.20: React Hooks Internals: useState, useReducer & State Queues\n\ndef solve():\n    \"\"\"\n    Verification: Implement an in-memory clone of `useState` and `useReducer` backed by an array of linked hook record\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.20", "subtopics_count": 6, "verification_criteria": "Implement an in-memory clone of `useState` and `useReducer` backed by an array of linked hook records.", "subtopics": ["6.20.1 Hooks data structure: singly linked list of hook records anchored to the current Fiber node (`memoizedState`)", "6.20.2 The Rules of Hooks: why hooks must be called unconditionally at top level to maintain linked list index parity", "6.20.3 useState internals: update queues, pending update circular lists, and eager state evaluation optimizations", "6.20.4 useReducer mechanics: action dispatching, reducer pure functions, and shared underlying implementation with useState", "6.20.5 Batching in React 18: Automatic batching across promises, setTimeout, and native event handlers", "6.20.6 Functional state updates (`setCount(c => c + 1)`) vs direct value passing under stale closure conditions"]}'::jsonb, '["Explain how this implementation prevents: Violating the rules of hooks with conditional statements; stale closures reading outdated state values inside callbacks.", "How does React Hooks Internals: useState, useReducer & State Queues scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-21', 'phase-06-lesson-21-react-effect-hooks-useeffect-uselayouteff', 'module-8', 21, 'Lesson 8.21: React Effect Hooks: useEffect, useLayoutEffect & useInsertionEffect', 'Prerequisites: Lesson 6.20', 'Prerequisites: Lesson 6.20 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 1050.0, '# Lesson 6.21: React Effect Hooks: useEffect, useLayoutEffect & useInsertionEffect

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.20
- **Subtopics**:
  - `6.21.1` useEffect lifecycle: execution timing after browser paint, asynchronous nature, and cleanup functions
  - `6.21.2` useLayoutEffect mechanics: synchronous execution after DOM mutation but before browser paint to prevent visual flicker
  - `6.21.3` useInsertionEffect: execution before DOM mutations for CSS-in-JS library style injection
  - `6.21.4` Dependency array ergonomics: reference equality (`Object.is`), primitive vs object dependencies, and eslint-plugin-react-hooks
  - `6.21.5` Common useEffect anti-patterns: transforming data for rendering, handling user events, and synchronization misuse
  - `6.21.6` Effect cleanup guarantees: unmounting vs re-execution cleanup order and AbortController integrations
- **Key Failure Modes & Edge Cases**: Visual flickering caused by measuring DOM in useEffect instead of useLayoutEffect; infinite effect loops from object reference dependencies.
- **Verification & Mastery Check**: Build a smooth auto-resizing textarea that measures DOM scrollHeight without flickering or layout thrashing.
- **Project Application**: CompKit: Accessible auto-resizing text fields and tooltips.', '{"solution.py": "# Phase 6 // Lesson 6.21: React Effect Hooks: useEffect, useLayoutEffect & useInsertionEffect\n\ndef solve():\n    \"\"\"\n    Verification: Build a smooth auto-resizing textarea that measures DOM scrollHeight without flickering or layout th\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.21", "subtopics_count": 6, "verification_criteria": "Build a smooth auto-resizing textarea that measures DOM scrollHeight without flickering or layout thrashing.", "subtopics": ["6.21.1 useEffect lifecycle: execution timing after browser paint, asynchronous nature, and cleanup functions", "6.21.2 useLayoutEffect mechanics: synchronous execution after DOM mutation but before browser paint to prevent visual flicker", "6.21.3 useInsertionEffect: execution before DOM mutations for CSS-in-JS library style injection", "6.21.4 Dependency array ergonomics: reference equality (`Object.is`), primitive vs object dependencies, and eslint-plugin-react-hooks", "6.21.5 Common useEffect anti-patterns: transforming data for rendering, handling user events, and synchronization misuse", "6.21.6 Effect cleanup guarantees: unmounting vs re-execution cleanup order and AbortController integrations"]}'::jsonb, '["Explain how this implementation prevents: Visual flickering caused by measuring DOM in useEffect instead of useLayoutEffect; infinite effect loops from object ref", "How does React Effect Hooks: useEffect, useLayoutEffect & useInsertionEffect scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-22', 'phase-06-lesson-22-react-memoization-optimization-usememo-us', 'module-8', 22, 'Lesson 8.22: React Memoization & Optimization: useMemo, useCallback & React.memo', 'Prerequisites: Lesson 6.20, Lesson 6.21', 'Prerequisites: Lesson 6.20, Lesson 6.21 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 1100.0, '# Lesson 6.22: React Memoization & Optimization: useMemo, useCallback & React.memo

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.20, Lesson 6.21
- **Subtopics**:
  - `6.22.1` Referential stability in JavaScript: why inline objects and functions break child memoization (`{} !== {}`)
  - `6.22.2` React.memo mechanics: shallow comparison of props, custom comparison functions, and when memoization hurts performance
  - `6.22.3` useMemo deep dive: caching expensive algorithmic calculations and stabilizing object references
  - `6.22.4` useCallback deep dive: stabilizing callback references for memoized child components
  - `6.22.5` The cost of memoization: memory allocations for dependency arrays and comparison overhead vs re-render cost
  - `6.22.6` Profiling re-renders: React DevTools Profiler, flame graphs, ranked charts, and ''Why did this render?'' analysis
- **Key Failure Modes & Edge Cases**: Blindly wrapping every primitive in useMemo adding memory overhead; passing un-memoized callbacks to React.memo children.
- **Verification & Mastery Check**: Profile an unoptimized list view of 5,000 items; apply targeted memoization to cut frame render time from 48ms to 3ms.
- **Project Application**: TenantIQ: High-frequency live analytics tabular dashboard.', '{"solution.py": "# Phase 6 // Lesson 6.22: React Memoization & Optimization: useMemo, useCallback & React.memo\n\ndef solve():\n    \"\"\"\n    Verification: Profile an unoptimized list view of 5,000 items; apply targeted memoization to cut frame render time\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.22", "subtopics_count": 6, "verification_criteria": "Profile an unoptimized list view of 5,000 items; apply targeted memoization to cut frame render time from 48ms to 3ms.", "subtopics": ["6.22.1 Referential stability in JavaScript: why inline objects and functions break child memoization (`{} !== {}`)", "6.22.2 React.memo mechanics: shallow comparison of props, custom comparison functions, and when memoization hurts performance", "6.22.3 useMemo deep dive: caching expensive algorithmic calculations and stabilizing object references", "6.22.4 useCallback deep dive: stabilizing callback references for memoized child components", "6.22.5 The cost of memoization: memory allocations for dependency arrays and comparison overhead vs re-render cost", "6.22.6 Profiling re-renders: React DevTools Profiler, flame graphs, ranked charts, and ''Why did this render?'' analysis"]}'::jsonb, '["Explain how this implementation prevents: Blindly wrapping every primitive in useMemo adding memory overhead; passing un-memoized callbacks to React.memo children", "How does React Memoization & Optimization: useMemo, useCallback & React.memo scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-23', 'phase-06-lesson-23-react-ref-systems-useref-forwardref-useim', 'module-8', 23, 'Lesson 8.23: React Ref Systems: useRef, forwardRef & useImperativeHandle', 'Prerequisites: Lesson 6.1, Lesson 6.20', 'Prerequisites: Lesson 6.1, Lesson 6.20 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 1150.0, '# Lesson 6.23: React Ref Systems: useRef, forwardRef & useImperativeHandle

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.1, Lesson 6.20
- **Subtopics**:
  - `6.23.1` useRef mechanics: mutable container object (`{ current: initialValue }`) persisting across renders without triggering re-render
  - `6.23.2` DOM refs vs instance variables: storing timer IDs, previous prop values, and mutable flags
  - `6.23.3` Ref forwarding with `forwardRef`: passing DOM refs through higher-order and wrapper components
  - `6.23.4` Custom imperative APIs with `useImperativeHandle`: exposing controlled subset of methods (focus, scrollIntoView) to parents
  - `6.23.5` Callback refs: fine-grained control over DOM node mounting and unmounting notifications
  - `6.23.6` Ref timing: when refs are attached during commit phase and why reading refs during render is unsafe
- **Key Failure Modes & Edge Cases**: Reading or writing `ref.current` during the render phase causing nondeterministic concurrent mode bugs.
- **Verification & Mastery Check**: Construct a custom video player component using `forwardRef` and `useImperativeHandle` exposing only safe play/pause/scrub methods.
- **Project Application**: CompKit: Media player and accessible custom input components.', '{"solution.py": "# Phase 6 // Lesson 6.23: React Ref Systems: useRef, forwardRef & useImperativeHandle\n\ndef solve():\n    \"\"\"\n    Verification: Construct a custom video player component using `forwardRef` and `useImperativeHandle` exposing only\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.23", "subtopics_count": 6, "verification_criteria": "Construct a custom video player component using `forwardRef` and `useImperativeHandle` exposing only safe play/pause/scrub methods.", "subtopics": ["6.23.1 useRef mechanics: mutable container object (`{ current: initialValue }`) persisting across renders without triggering re-render", "6.23.2 DOM refs vs instance variables: storing timer IDs, previous prop values, and mutable flags", "6.23.3 Ref forwarding with `forwardRef`: passing DOM refs through higher-order and wrapper components", "6.23.4 Custom imperative APIs with `useImperativeHandle`: exposing controlled subset of methods (focus, scrollIntoView) to parents", "6.23.5 Callback refs: fine-grained control over DOM node mounting and unmounting notifications", "6.23.6 Ref timing: when refs are attached during commit phase and why reading refs during render is unsafe"]}'::jsonb, '["Explain how this implementation prevents: Reading or writing `ref.current` during the render phase causing nondeterministic concurrent mode bugs.", "How does React Ref Systems: useRef, forwardRef & useImperativeHandle scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-24', 'phase-06-lesson-24-react-context-architecture-performance-bo', 'module-8', 24, 'Lesson 8.24: React Context Architecture, Performance Bottlenecks & Selectors', 'Prerequisites: Lesson 6.20, Lesson 6.22', 'Prerequisites: Lesson 6.20, Lesson 6.22 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 1200.0, '# Lesson 6.24: React Context Architecture, Performance Bottlenecks & Selectors

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.20, Lesson 6.22
- **Subtopics**:
  - `6.24.1` React Context API: createContext, Provider, and useContext subscription mechanics
  - `6.24.2` The Context re-render problem: all consumers re-rendering whenever provider value reference changes
  - `6.24.3` Mitigating context re-renders: splitting state and dispatch providers, memoizing provider value objects
  - `6.24.4` Compound providers architecture: organizing nested global application state cleanly
  - `6.24.5` Alternative state selector patterns: why context is not a universal replacement for specialized state stores
  - `6.24.6` useSyncExternalStore introduction: concurrent-safe subscription to external stores without tearing
- **Key Failure Modes & Edge Cases**: Stashing an entire monolithic global state object in a single Context Provider, forcing full-app re-renders on minor keystrokes.
- **Verification & Mastery Check**: Build a modular split-context theme and authentication manager; verify via React Profiler that consumer components render independently.
- **Project Application**: TenantIQ: Multi-tenant global workspace and auth context.', '{"solution.py": "# Phase 6 // Lesson 6.24: React Context Architecture, Performance Bottlenecks & Selectors\n\ndef solve():\n    \"\"\"\n    Verification: Build a modular split-context theme and authentication manager; verify via React Profiler that consu\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.24", "subtopics_count": 6, "verification_criteria": "Build a modular split-context theme and authentication manager; verify via React Profiler that consumer components render independently.", "subtopics": ["6.24.1 React Context API: createContext, Provider, and useContext subscription mechanics", "6.24.2 The Context re-render problem: all consumers re-rendering whenever provider value reference changes", "6.24.3 Mitigating context re-renders: splitting state and dispatch providers, memoizing provider value objects", "6.24.4 Compound providers architecture: organizing nested global application state cleanly", "6.24.5 Alternative state selector patterns: why context is not a universal replacement for specialized state stores", "6.24.6 useSyncExternalStore introduction: concurrent-safe subscription to external stores without tearing"]}'::jsonb, '["Explain how this implementation prevents: Stashing an entire monolithic global state object in a single Context Provider, forcing full-app re-renders on minor key", "How does React Context Architecture, Performance Bottlenecks & Selectors scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-25', 'phase-06-lesson-25-custom-react-hooks-architecture-state-mac', 'module-8', 25, 'Lesson 8.25: Custom React Hooks Architecture & State Machines', 'Prerequisites: Lesson 6.20, Lesson 6.24', 'Prerequisites: Lesson 6.20, Lesson 6.24 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 1250.0, '# Lesson 6.25: Custom React Hooks Architecture & State Machines

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.20, Lesson 6.24
- **Subtopics**:
  - `6.25.1` Design principles for robust custom hooks: single responsibility, clear return contracts, and composability
  - `6.25.2` Building stateful primitives: useDebounce, useThrottle, useLocalStorage, and useMediaQuery
  - `6.25.3` Asynchronous data-fetching hooks: managing idle, loading, success, and error states with cancellation
  - `6.25.4` Finite state machines in custom hooks: replacing complex boolean flags (`isLoading`, `isError`, `isSuccess`) with state transitions
  - `6.25.5` Event listener hooks: useEventListener with passive options and automatic window/document unbinding
  - `6.25.6` Publishing and testing hooks: unit testing custom hooks with `@testing-library/react-hooks`
- **Key Failure Modes & Edge Cases**: State explosion with conflicting boolean flags; memory leaks from uncleaned window event listeners in custom hooks.
- **Verification & Mastery Check**: Implement a comprehensive `useAsyncOperation` hook modeling an explicit state machine with retry and cancellation support.
- **Project Application**: CompKit: Shared hook library for modal, tooltip, and table behaviors.', '{"solution.py": "# Phase 6 // Lesson 6.25: Custom React Hooks Architecture & State Machines\n\ndef solve():\n    \"\"\"\n    Verification: Implement a comprehensive `useAsyncOperation` hook modeling an explicit state machine with retry and\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.25", "subtopics_count": 6, "verification_criteria": "Implement a comprehensive `useAsyncOperation` hook modeling an explicit state machine with retry and cancellation support.", "subtopics": ["6.25.1 Design principles for robust custom hooks: single responsibility, clear return contracts, and composability", "6.25.2 Building stateful primitives: useDebounce, useThrottle, useLocalStorage, and useMediaQuery", "6.25.3 Asynchronous data-fetching hooks: managing idle, loading, success, and error states with cancellation", "6.25.4 Finite state machines in custom hooks: replacing complex boolean flags (`isLoading`, `isError`, `isSuccess`) with state transitions", "6.25.5 Event listener hooks: useEventListener with passive options and automatic window/document unbinding", "6.25.6 Publishing and testing hooks: unit testing custom hooks with `@testing-library/react-hooks`"]}'::jsonb, '["Explain how this implementation prevents: State explosion with conflicting boolean flags; memory leaks from uncleaned window event listeners in custom hooks.", "How does Custom React Hooks Architecture & State Machines scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-26', 'phase-06-lesson-26-react-18-19-concurrent-features-usetransi', 'module-8', 26, 'Lesson 8.26: React 18/19 Concurrent Features: useTransition & useDeferredValue', 'Prerequisites: Lesson 6.18, Lesson 6.22', 'Prerequisites: Lesson 6.18, Lesson 6.22 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 1300.0, '# Lesson 6.26: React 18/19 Concurrent Features: useTransition & useDeferredValue

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.18, Lesson 6.22
- **Subtopics**:
  - `6.26.1` Concurrent React overview: non-blocking rendering, interruptible UI updates, and prioritizing user interactions
  - `6.26.2` useTransition deep dive: marking state updates as low-priority transitions (`isPending` flag)
  - `6.26.3` useDeferredValue deep dive: deferring expensive subtree updates until critical input renders complete
  - `6.26.4` Suspense for data fetching: coordinating loading states across deep component hierarchies without spinner cascades
  - `6.26.5` Streaming HTML and progressive hydration: sending early HTML chunks before server data completes
  - `6.26.6` Selective hydration: prioritizing user-interacted elements before background components finish hydrating
- **Key Failure Modes & Edge Cases**: Wrapping user keystroke state updates directly in useTransition causing perceived typing latency.
- **Verification & Mastery Check**: Build a live search filter over 20,000 records using useTransition to keep typing input responsive at 60fps.
- **Project Application**: TenantIQ: Tenant-wide instant search and filtering interface.', '{"solution.py": "# Phase 6 // Lesson 6.26: React 18/19 Concurrent Features: useTransition & useDeferredValue\n\ndef solve():\n    \"\"\"\n    Verification: Build a live search filter over 20,000 records using useTransition to keep typing input responsive a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.26", "subtopics_count": 6, "verification_criteria": "Build a live search filter over 20,000 records using useTransition to keep typing input responsive at 60fps.", "subtopics": ["6.26.1 Concurrent React overview: non-blocking rendering, interruptible UI updates, and prioritizing user interactions", "6.26.2 useTransition deep dive: marking state updates as low-priority transitions (`isPending` flag)", "6.26.3 useDeferredValue deep dive: deferring expensive subtree updates until critical input renders complete", "6.26.4 Suspense for data fetching: coordinating loading states across deep component hierarchies without spinner cascades", "6.26.5 Streaming HTML and progressive hydration: sending early HTML chunks before server data completes", "6.26.6 Selective hydration: prioritizing user-interacted elements before background components finish hydrating"]}'::jsonb, '["Explain how this implementation prevents: Wrapping user keystroke state updates directly in useTransition causing perceived typing latency.", "How does React 18/19 Concurrent Features: useTransition & useDeferredValue scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-27', 'phase-06-lesson-27-modern-forms-architecture-controlled-vs-u', 'module-8', 27, 'Lesson 8.27: Modern Forms Architecture: Controlled vs Uncontrolled & Formik/RHF', 'Prerequisites: Lesson 6.3, Lesson 6.20', 'Prerequisites: Lesson 6.3, Lesson 6.20 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 1350.0, '# Lesson 6.27: Modern Forms Architecture: Controlled vs Uncontrolled & Formik/RHF

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.3, Lesson 6.20
- **Subtopics**:
  - `6.27.1` Controlled components: state-driven form inputs, single source of truth, and render overhead on keystrokes
  - `6.27.2` Uncontrolled components: DOM-driven inputs, defaultValue, and ref-based value harvesting
  - `6.27.3` React Hook Form architecture: ref-based uncontrolled inputs, subscriptions, and isolated re-renders
  - `6.27.4` Form validation schemas: Zod schema integration, type inference, and runtime payload validation
  - `6.27.5` Form submission lifecycle: dirty state tracking, touch state, error mapping, and server-side validation error mapping
  - `6.27.6` Accessibility in complex forms: aria-invalid, aria-describedby for error messages, and programmatic error focusing
- **Key Failure Modes & Edge Cases**: Controlled form state at page root causing massive input lag on typing; missing aria-describedby disconnecting errors from inputs.
- **Verification & Mastery Check**: Construct a multi-step tenant onboarding form with dynamic arrays, Zod validation, and zero unnecessary re-renders.
- **Project Application**: TenantIQ: Organization settings and tenant provisioning forms.', '{"solution.py": "# Phase 6 // Lesson 6.27: Modern Forms Architecture: Controlled vs Uncontrolled & Formik/RHF\n\ndef solve():\n    \"\"\"\n    Verification: Construct a multi-step tenant onboarding form with dynamic arrays, Zod validation, and zero unnecess\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.27", "subtopics_count": 6, "verification_criteria": "Construct a multi-step tenant onboarding form with dynamic arrays, Zod validation, and zero unnecessary re-renders.", "subtopics": ["6.27.1 Controlled components: state-driven form inputs, single source of truth, and render overhead on keystrokes", "6.27.2 Uncontrolled components: DOM-driven inputs, defaultValue, and ref-based value harvesting", "6.27.3 React Hook Form architecture: ref-based uncontrolled inputs, subscriptions, and isolated re-renders", "6.27.4 Form validation schemas: Zod schema integration, type inference, and runtime payload validation", "6.27.5 Form submission lifecycle: dirty state tracking, touch state, error mapping, and server-side validation error mapping", "6.27.6 Accessibility in complex forms: aria-invalid, aria-describedby for error messages, and programmatic error focusing"]}'::jsonb, '["Explain how this implementation prevents: Controlled form state at page root causing massive input lag on typing; missing aria-describedby disconnecting errors fr", "How does Modern Forms Architecture: Controlled vs Uncontrolled & Formik/RHF scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-28', 'phase-06-lesson-28-frontend-client-side-state-management-zus', 'module-8', 28, 'Lesson 8.28: Frontend Client-Side State Management: Zustand & Jotai', 'Prerequisites: Lesson 6.24', 'Prerequisites: Lesson 6.24 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 1400.0, '# Lesson 6.28: Frontend Client-Side State Management: Zustand & Jotai

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.24
- **Subtopics**:
  - `6.28.1` Zustand architecture: un-opinionated, external store, hook-based selector subscriptions via useSyncExternalStore
  - `6.28.2` Zustand actions, middleware, devtools integration, and persistent storage synchronization
  - `6.28.3` Atomic state model with Jotai: atoms, derived atoms, async atoms, and fine-grained dependency tracking
  - `6.28.4` Comparison of state paradigms: Single Store (Zustand/Redux) vs Atomic State (Jotai/Recoil) vs Context
  - `6.28.5` Transient state updates: updating DOM directly from store subscriptions without triggering React render cycles
  - `6.28.6` State hydration in SSR/Next.js environments: avoiding hydration mismatches with client-side persisted stores
- **Key Failure Modes & Edge Cases**: Hydration mismatch when reading client storage on initial render; store selector returning new object reference triggering infinite renders.
- **Verification & Mastery Check**: Build a real-time notification and preferences engine with Zustand featuring fine-grained selector subscriptions.
- **Project Application**: TenantIQ: Notification center and global UI state.', '{"solution.py": "# Phase 6 // Lesson 6.28: Frontend Client-Side State Management: Zustand & Jotai\n\ndef solve():\n    \"\"\"\n    Verification: Build a real-time notification and preferences engine with Zustand featuring fine-grained selector s\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.28", "subtopics_count": 6, "verification_criteria": "Build a real-time notification and preferences engine with Zustand featuring fine-grained selector subscriptions.", "subtopics": ["6.28.1 Zustand architecture: un-opinionated, external store, hook-based selector subscriptions via useSyncExternalStore", "6.28.2 Zustand actions, middleware, devtools integration, and persistent storage synchronization", "6.28.3 Atomic state model with Jotai: atoms, derived atoms, async atoms, and fine-grained dependency tracking", "6.28.4 Comparison of state paradigms: Single Store (Zustand/Redux) vs Atomic State (Jotai/Recoil) vs Context", "6.28.5 Transient state updates: updating DOM directly from store subscriptions without triggering React render cycles", "6.28.6 State hydration in SSR/Next.js environments: avoiding hydration mismatches with client-side persisted stores"]}'::jsonb, '["Explain how this implementation prevents: Hydration mismatch when reading client storage on initial render; store selector returning new object reference triggeri", "How does Frontend Client-Side State Management: Zustand & Jotai scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-29', 'phase-06-lesson-29-server-state-management-caching-tanstack-', 'module-8', 29, 'Lesson 8.29: Server State Management & Caching: TanStack Query (React Query)', 'Prerequisites: Lesson 6.14, Lesson 6.28', 'Prerequisites: Lesson 6.14, Lesson 6.28 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 1450.0, '# Lesson 6.29: Server State Management & Caching: TanStack Query (React Query)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.14, Lesson 6.28
- **Subtopics**:
  - `6.29.1` Server state vs Client state: asynchronous, shared, potentially outdated, and multi-consumer characteristics
  - `6.29.2` TanStack Query core concepts: query keys, query functions, staleTime vs gcTime (cacheTime)
  - `6.29.3` Query lifecycles: fetching, fresh, stale, inactive, and garbage collection mechanisms
  - `6.29.4` Mutations and optimistic updates: onMutate, onError rollback, and query invalidation pipelines
  - `6.29.5` Infinite scrolling and pagination: useInfiniteQuery, getNextPageParam, and virtualized list integration
  - `6.29.6` Network status and background refetching: refetchOnWindowFocus, reconnect refetching, and offline caching
- **Key Failure Modes & Edge Cases**: Confusing staleTime with gcTime causing immediate re-fetches; failing to rollback optimistic UI updates on network failure.
- **Verification & Mastery Check**: Implement a full CRUD interface with optimistic UI updates and automated query cache invalidation on error.
- **Project Application**: TenantIQ: Tenant user management and subscription plan manager.', '{"solution.py": "# Phase 6 // Lesson 6.29: Server State Management & Caching: TanStack Query (React Query)\n\ndef solve():\n    \"\"\"\n    Verification: Implement a full CRUD interface with optimistic UI updates and automated query cache invalidation on\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.29", "subtopics_count": 6, "verification_criteria": "Implement a full CRUD interface with optimistic UI updates and automated query cache invalidation on error.", "subtopics": ["6.29.1 Server state vs Client state: asynchronous, shared, potentially outdated, and multi-consumer characteristics", "6.29.2 TanStack Query core concepts: query keys, query functions, staleTime vs gcTime (cacheTime)", "6.29.3 Query lifecycles: fetching, fresh, stale, inactive, and garbage collection mechanisms", "6.29.4 Mutations and optimistic updates: onMutate, onError rollback, and query invalidation pipelines", "6.29.5 Infinite scrolling and pagination: useInfiniteQuery, getNextPageParam, and virtualized list integration", "6.29.6 Network status and background refetching: refetchOnWindowFocus, reconnect refetching, and offline caching"]}'::jsonb, '["Explain how this implementation prevents: Confusing staleTime with gcTime causing immediate re-fetches; failing to rollback optimistic UI updates on network failu", "How does Server State Management & Caching: TanStack Query (React Query) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-30', 'phase-06-lesson-30-next-js-fundamentals-app-router-architect', 'module-8', 30, 'Lesson 8.30: Next.js Fundamentals: App Router Architecture & File System Conventions', 'Prerequisites: Lesson 6.16, Lesson 6.17', 'Prerequisites: Lesson 6.16, Lesson 6.17 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 1500.0, '# Lesson 6.30: Next.js Fundamentals: App Router Architecture & File System Conventions

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.16, Lesson 6.17
- **Subtopics**:
  - `6.30.1` Evolution of Next.js: Pages Router (`_app.tsx`, `_document.tsx`) vs App Router (`app/` directory)
  - `6.30.2` File-system routing conventions: layout.tsx, page.tsx, loading.tsx, error.tsx, not-found.tsx, and route.ts
  - `6.30.3` Nested layouts and route groups: preserving layout state, selective re-rendering, and `(group)` directory isolation
  - `6.30.4` Dynamic routes and catch-all segments: `[slug]`, `[...slug]`, and optional catch-all `[[...slug]]` parameters
  - `6.30.5` Parallel routes and intercepting routes: `@modal` slots, conditional rendering, and soft navigation modals
  - `6.30.6` Metadata API: static and dynamic generateMetadata for SEO, OpenGraph, and Twitter card injection
- **Key Failure Modes & Edge Cases**: Accidental full-page unmounts caused by putting state inside route layouts that re-render; bad catch-all route matching precedence.
- **Verification & Mastery Check**: Build an App Router layout hierarchy with nested persistent navigation, loading skeletons, and route-level error boundaries.
- **Project Application**: TenantIQ: App Router workspace structure.', '{"solution.py": "# Phase 6 // Lesson 6.30: Next.js Fundamentals: App Router Architecture & File System Conventions\n\ndef solve():\n    \"\"\"\n    Verification: Build an App Router layout hierarchy with nested persistent navigation, loading skeletons, and route\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.30", "subtopics_count": 6, "verification_criteria": "Build an App Router layout hierarchy with nested persistent navigation, loading skeletons, and route-level error boundaries.", "subtopics": ["6.30.1 Evolution of Next.js: Pages Router (`_app.tsx`, `_document.tsx`) vs App Router (`app/` directory)", "6.30.2 File-system routing conventions: layout.tsx, page.tsx, loading.tsx, error.tsx, not-found.tsx, and route.ts", "6.30.3 Nested layouts and route groups: preserving layout state, selective re-rendering, and `(group)` directory isolation", "6.30.4 Dynamic routes and catch-all segments: `[slug]`, `[...slug]`, and optional catch-all `[[...slug]]` parameters", "6.30.5 Parallel routes and intercepting routes: `@modal` slots, conditional rendering, and soft navigation modals", "6.30.6 Metadata API: static and dynamic generateMetadata for SEO, OpenGraph, and Twitter card injection"]}'::jsonb, '["Explain how this implementation prevents: Accidental full-page unmounts caused by putting state inside route layouts that re-render; bad catch-all route matching ", "How does Next.js Fundamentals: App Router Architecture & File System Conventions scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
