INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-10-31', 'phase-10-lesson-31-golden-datasets-curation-versioning-regre', 'module-11', 31, 'Lesson 11.31: Golden Datasets: Curation, Versioning & Regression Testing', 'Prerequisites: Lesson 10.29, Lesson 10.30', 'Prerequisites: Lesson 10.29, Lesson 10.30 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 1550.0, '# Lesson 10.31: Golden Datasets: Curation, Versioning & Regression Testing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.29, Lesson 10.30
- **Subtopics**:
  - `10.31.1` What constitutes a true Golden Dataset: curated, human-verified, representative question-answer-context benchmark suites
  - `10.31.2` Stratified sampling: ensuring golden datasets cover diverse document types, difficulty levels, and domain topics proportionally
  - `10.31.3` Versioning golden datasets: tracking dataset git hashes, schema versions, and ground truth updates alongside model code
  - `10.31.4` Regression testing pipelines: detecting breaking changes in retrieval or synthesis when updating embedding models or prompts
  - `10.31.5` Establishing performance baselines: tracking precision@K, recall@K, MRR, NDCG, and RAG Triad scores across model releases
  - `10.31.6` Continuous dataset updating: harvesting hard production queries and user-reported bad answers into the regression suite
- **Key Failure Modes & Edge Cases**: Modifying prompt templates in production without running the golden regression suite, silently degrading edge-case answer quality.
- **Verification & Mastery Check**: Establish a version-controlled 250-sample Golden Dataset and automated regression test suite running in GitHub Actions.
- **Project Application**: EvalKit: Golden dataset repository and CI/CD test harness.', '{"solution.py": "# Phase 10 // Lesson 10.31: Golden Datasets: Curation, Versioning & Regression Testing\n\ndef solve():\n    \"\"\"\n    Verification: Establish a version-controlled 250-sample Golden Dataset and automated regression test suite running\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.31", "subtopics_count": 6, "verification_criteria": "Establish a version-controlled 250-sample Golden Dataset and automated regression test suite running in GitHub Actions.", "subtopics": ["10.31.1 What constitutes a true Golden Dataset: curated, human-verified, representative question-answer-context benchmark suites", "10.31.2 Stratified sampling: ensuring golden datasets cover diverse document types, difficulty levels, and domain topics proportionally", "10.31.3 Versioning golden datasets: tracking dataset git hashes, schema versions, and ground truth updates alongside model code", "10.31.4 Regression testing pipelines: detecting breaking changes in retrieval or synthesis when updating embedding models or prompts", "10.31.5 Establishing performance baselines: tracking precision@K, recall@K, MRR, NDCG, and RAG Triad scores across model releases", "10.31.6 Continuous dataset updating: harvesting hard production queries and user-reported bad answers into the regression suite"]}'::jsonb, '["Explain how this implementation prevents: Modifying prompt templates in production without running the golden regression suite, silently degrading edge-case answe", "How does Golden Datasets: Curation, Versioning & Regression Testing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-32', 'phase-10-lesson-32-statistical-inter-rater-reliability-cohen', 'module-11', 32, 'Lesson 11.32: Statistical Inter-Rater Reliability: Cohen''s Kappa & Krippendorff''s Alpha', 'Prerequisites: Phase 2, Lesson 10.30', 'Prerequisites: Phase 2, Lesson 10.30 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1600.0, '# Lesson 10.32: Statistical Inter-Rater Reliability: Cohen''s Kappa & Krippendorff''s Alpha

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2, Lesson 10.30
- **Subtopics**:
  - `10.32.1` Why measuring agreement is essential: validating whether automated LLM judges agree with human expert evaluators
  - `10.32.2` Observed agreement vs Chance agreement: why raw percent agreement ($P_o$) is mathematically misleading
  - `10.32.3` Cohen''s Kappa ($\kappa$): $\kappa = \frac{P_o - P_e}{1 - P_e}$; correcting for agreement occurring purely by chance
  - `10.32.4` Interpreting Kappa: $<0.20$ (poor), $0.41-0.60$ (moderate), $0.61-0.80$ (substantial), $0.81-1.00$ (almost perfect agreement)
  - `10.32.5` Krippendorff''s Alpha ($\alpha$): generalized reliability metric handling multiple raters, missing data, and ordinal/interval scales
  - `10.32.6` Calibrating LLM judges: iterating on judge prompt rubrics until agreement with domain experts achieves $\kappa > 0.75$
- **Key Failure Modes & Edge Cases**: Deploying an automated LLM judge that has a Cohen''s Kappa of 0.15 with human experts, making automated metrics completely uncorrelated with reality.
- **Verification & Mastery Check**: Implement Cohen''s Kappa and Krippendorff''s Alpha from scratch; measure statistical agreement between an LLM judge and human ratings.
- **Project Application**: EvalKit: Statistical inter-rater reliability calculation suite.', '{"solution.py": "# Phase 10 // Lesson 10.32: Statistical Inter-Rater Reliability: Cohen''s Kappa & Krippendorff''s Alpha\n\ndef solve():\n    \"\"\"\n    Verification: Implement Cohen''s Kappa and Krippendorff''s Alpha from scratch; measure statistical agreement between\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.32", "subtopics_count": 6, "verification_criteria": "Implement Cohen''s Kappa and Krippendorff''s Alpha from scratch; measure statistical agreement between an LLM judge and human ratings.", "subtopics": ["10.32.1 Why measuring agreement is essential: validating whether automated LLM judges agree with human expert evaluators", "10.32.2 Observed agreement vs Chance agreement: why raw percent agreement ($P_o$) is mathematically misleading", "10.32.3 Cohen''s Kappa ($\\kappa$): $\\kappa = \\frac{P_o - P_e}{1 - P_e}$; correcting for agreement occurring purely by chance", "10.32.4 Interpreting Kappa: $<0.20$ (poor), $0.41-0.60$ (moderate), $0.61-0.80$ (substantial), $0.81-1.00$ (almost perfect agreement)", "10.32.5 Krippendorff''s Alpha ($\\alpha$): generalized reliability metric handling multiple raters, missing data, and ordinal/interval scales", "10.32.6 Calibrating LLM judges: iterating on judge prompt rubrics until agreement with domain experts achieves $\\kappa > 0.75$"]}'::jsonb, '["Explain how this implementation prevents: Deploying an automated LLM judge that has a Cohen''s Kappa of 0.15 with human experts, making automated metrics completel", "How does Statistical Inter-Rater Reliability: Cohen''s Kappa & Krippendorff''s Alpha scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-33', 'phase-10-lesson-33-human-in-the-loop-hitl-annotation-discord', 'module-11', 33, 'Lesson 11.33: Human-in-the-Loop (HITL) Annotation & Discordance Analysis', 'Prerequisites: Lesson 10.31, Lesson 10.32', 'Prerequisites: Lesson 10.31, Lesson 10.32 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 1650.0, '# Lesson 10.33: Human-in-the-Loop (HITL) Annotation & Discordance Analysis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.31, Lesson 10.32
- **Subtopics**:
  - `10.33.1` Designing annotation interfaces: building ergonomic web UIs for human domain experts to review and rate RAG outputs
  - `10.33.2` Annotation guidelines: creating unambiguous, deterministic rubric documentation to minimize human annotator variance
  - `10.33.3` Discordance Analysis: systematic analysis of edge cases where human annotators disagree with each other or with LLM judges
  - `10.33.4` Root cause taxonomy for discordance: ambiguous questions, incomplete context, subjective criteria, or annotation fatigue
  - `10.33.5` Feedback loops: routing low-confidence production queries to human expert review queues for ongoing active learning
  - `10.33.6` Privacy and compliance in annotation: masking PII and sensitive enterprise data before presenting to internal or external raters
- **Key Failure Modes & Edge Cases**: Providing vague annotation guidelines (''rate quality 1-5''), causing human annotator agreement to collapse into random noise.
- **Verification & Mastery Check**: Conduct a structured discordance analysis on 50 contested evaluations; refine rubric guidelines to resolve 90% of ambiguities.
- **Project Application**: EvalKit: Human evaluation protocol and discordance report.', '{"solution.py": "# Phase 10 // Lesson 10.33: Human-in-the-Loop (HITL) Annotation & Discordance Analysis\n\ndef solve():\n    \"\"\"\n    Verification: Conduct a structured discordance analysis on 50 contested evaluations; refine rubric guidelines to r\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.33", "subtopics_count": 6, "verification_criteria": "Conduct a structured discordance analysis on 50 contested evaluations; refine rubric guidelines to resolve 90% of ambiguities.", "subtopics": ["10.33.1 Designing annotation interfaces: building ergonomic web UIs for human domain experts to review and rate RAG outputs", "10.33.2 Annotation guidelines: creating unambiguous, deterministic rubric documentation to minimize human annotator variance", "10.33.3 Discordance Analysis: systematic analysis of edge cases where human annotators disagree with each other or with LLM judges", "10.33.4 Root cause taxonomy for discordance: ambiguous questions, incomplete context, subjective criteria, or annotation fatigue", "10.33.5 Feedback loops: routing low-confidence production queries to human expert review queues for ongoing active learning", "10.33.6 Privacy and compliance in annotation: masking PII and sensitive enterprise data before presenting to internal or external raters"]}'::jsonb, '["Explain how this implementation prevents: Providing vague annotation guidelines (''rate quality 1-5''), causing human annotator agreement to collapse into random no", "How does Human-in-the-Loop (HITL) Annotation & Discordance Analysis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-34', 'phase-10-lesson-34-failure-mode-triage-retrieval-failures-vs', 'module-11', 34, 'Lesson 11.34: Failure Mode Triage: Retrieval Failures vs Synthesis Failures', 'Prerequisites: Lesson 10.27, Lesson 10.30', 'Prerequisites: Lesson 10.27, Lesson 10.30 | Subtopics: 7 items', 'Systems project application', 300, 11, 2560.0, 1700.0, '# Lesson 10.34: Failure Mode Triage: Retrieval Failures vs Synthesis Failures

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.27, Lesson 10.30
- **Subtopics**:
  - `10.34.1` Systematic failure categorization: decomposing RAG errors into precise failure modes across the pipeline
  - `10.34.2` Failure Mode 1: Missing Content: the answer does not exist anywhere in the source corpus (knowledge gap)
  - `10.34.3` Failure Mode 2: Missed Retrieval: the answer exists in corpus, but retrieval failed to include it in top-$K$ candidates
  - `10.34.4` Failure Mode 3: Out of Context: the chunk was retrieved, but dropped during re-ranking or context compression
  - `10.34.5` Failure Mode 4: Synthesis Failure: the answer was present in context, but the LLM failed to extract it or hallucinated
  - `10.34.6` Failure Mode 5: Wrong Format: the LLM extracted the right answer but violated schema or format constraints
  - `10.34.7` Building automated diagnostic decision trees to categorize user bug reports instantly into the exact responsible component
- **Key Failure Modes & Edge Cases**: Spending weeks tuning vector search indexes to fix a problem where the requested information was never ingested into the database.
- **Verification & Mastery Check**: Build an automated diagnostic triager that takes a failed RAG query and categorizes it into one of the 5 canonical failure modes.
- **Project Application**: DocuMind: Automated failure diagnostic harness.', '{"solution.py": "# Phase 10 // Lesson 10.34: Failure Mode Triage: Retrieval Failures vs Synthesis Failures\n\ndef solve():\n    \"\"\"\n    Verification: Build an automated diagnostic triager that takes a failed RAG query and categorizes it into one of t\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.34", "subtopics_count": 7, "verification_criteria": "Build an automated diagnostic triager that takes a failed RAG query and categorizes it into one of the 5 canonical failure modes.", "subtopics": ["10.34.1 Systematic failure categorization: decomposing RAG errors into precise failure modes across the pipeline", "10.34.2 Failure Mode 1: Missing Content: the answer does not exist anywhere in the source corpus (knowledge gap)", "10.34.3 Failure Mode 2: Missed Retrieval: the answer exists in corpus, but retrieval failed to include it in top-$K$ candidates", "10.34.4 Failure Mode 3: Out of Context: the chunk was retrieved, but dropped during re-ranking or context compression", "10.34.5 Failure Mode 4: Synthesis Failure: the answer was present in context, but the LLM failed to extract it or hallucinated", "10.34.6 Failure Mode 5: Wrong Format: the LLM extracted the right answer but violated schema or format constraints", "10.34.7 Building automated diagnostic decision trees to categorize user bug reports instantly into the exact responsible component"]}'::jsonb, '["Explain how this implementation prevents: Spending weeks tuning vector search indexes to fix a problem where the requested information was never ingested into the", "How does Failure Mode Triage: Retrieval Failures vs Synthesis Failures scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-35', 'phase-10-lesson-35-production-observability-for-genai-langfu', 'module-11', 35, 'Lesson 11.35: Production Observability for GenAI: Langfuse, Arize Phoenix & OpenInference', 'Prerequisites: Phase 7, Lesson 10.1', 'Prerequisites: Phase 7, Lesson 10.1 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1750.0, '# Lesson 10.35: Production Observability for GenAI: Langfuse, Arize Phoenix & OpenInference

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 10.1
- **Subtopics**:
  - `10.35.1` The GenAI observability challenge: tracking complex multi-step nested traces across prompts, embeddings, retrievals, and tools
  - `10.35.2` OpenInference semantic conventions: standardized tracing attributes for LLM calls, vector DB queries, and retrieval spans
  - `10.35.3` Langfuse / Arize Phoenix architecture: collecting distributed spans, visualizing execution DAGs, and tracking token costs
  - `10.35.4` Latency profiling: measuring latency bottlenecks across individual stages (prompt prep, vector search, re-ranking, first-token time)
  - `10.35.5` User feedback tracking: capturing user thumbs-up / thumbs-down and explicit corrections linked directly to specific trace IDs
  - `10.35.6` Alerting on GenAI anomalies: triggering alerts on spike in token usage, elevated latency, or sudden drops in retrieval score averages
- **Key Failure Modes & Edge Cases**: Treating the entire RAG pipeline as a black box without span tracing, leaving on-call engineers unable to diagnose production latency spikes.
- **Verification & Mastery Check**: Instrument a production RAG pipeline with OpenInference and Langfuse; visualize full execution traces with latency and token cost breakdowns.
- **Project Application**: DocuMind: Production GenAI observability and tracing pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.35: Production Observability for GenAI: Langfuse, Arize Phoenix & OpenInference\n\ndef solve():\n    \"\"\"\n    Verification: Instrument a production RAG pipeline with OpenInference and Langfuse; visualize full execution trace\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.35", "subtopics_count": 6, "verification_criteria": "Instrument a production RAG pipeline with OpenInference and Langfuse; visualize full execution traces with latency and token cost breakdowns.", "subtopics": ["10.35.1 The GenAI observability challenge: tracking complex multi-step nested traces across prompts, embeddings, retrievals, and tools", "10.35.2 OpenInference semantic conventions: standardized tracing attributes for LLM calls, vector DB queries, and retrieval spans", "10.35.3 Langfuse / Arize Phoenix architecture: collecting distributed spans, visualizing execution DAGs, and tracking token costs", "10.35.4 Latency profiling: measuring latency bottlenecks across individual stages (prompt prep, vector search, re-ranking, first-token time)", "10.35.5 User feedback tracking: capturing user thumbs-up / thumbs-down and explicit corrections linked directly to specific trace IDs", "10.35.6 Alerting on GenAI anomalies: triggering alerts on spike in token usage, elevated latency, or sudden drops in retrieval score averages"]}'::jsonb, '["Explain how this implementation prevents: Treating the entire RAG pipeline as a black box without span tracing, leaving on-call engineers unable to diagnose produ", "How does Production Observability for GenAI: Langfuse, Arize Phoenix & OpenInference scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
