INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-4-11', 'phase-04-lesson-11-kernel-threads-vs-user-space-green-thread', 'module-6', 11, 'Lesson 6.11: Kernel Threads vs User-Space Green Threads', 'Prerequisites: Phase 1 (Lesson 1.31)', 'Prerequisites: Phase 1 (Lesson 1.31) | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 550.0, '# Lesson 4.11: Kernel Threads vs User-Space Green Threads

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.31)
- **Subtopics**:
  - `4.11.1` 1:1 Threading Model: each application thread maps directly to a Linux kernel thread (NPTL - Native POSIX Thread Library).
  - `4.11.2` M:N Threading Model: $M$ user-space green threads multiplexed over $N$ OS threads (Go goroutines, Erlang actors).
  - `4.11.3` Context-switch cost: saving CPU registers, flushing pipeline, kernel transition overhead (~1–2 microseconds).
  - `4.11.4` Thread stack allocation: 8MB default stack vs customizable thread stack sizes (`pthread_attr_setstacksize`).
- **Key Failure Modes & Edge Cases**: Spawning 10,000 OS threads simultaneously, exhausting virtual memory and collapsing system under context switching.
- **Verification & Mastery Check**: Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 coroutines.
- **Project Application**: NanoHTTP: Version 1 (Multi-Threaded Server).', '{"solution.py": "# Phase 4 // Lesson 4.11: Kernel Threads vs User-Space Green Threads\n\ndef solve():\n    \"\"\"\n    Verification: Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 corout\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.11", "subtopics_count": 4, "verification_criteria": "Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 coroutines.", "subtopics": ["4.11.1 1:1 Threading Model: each application thread maps directly to a Linux kernel thread (NPTL - Native POSIX Thread Library).", "4.11.2 M:N Threading Model: $M$ user-space green threads multiplexed over $N$ OS threads (Go goroutines, Erlang actors).", "4.11.3 Context-switch cost: saving CPU registers, flushing pipeline, kernel transition overhead (~1\u20132 microseconds).", "4.11.4 Thread stack allocation: 8MB default stack vs customizable thread stack sizes (`pthread_attr_setstacksize`)."]}'::jsonb, '["Explain how this implementation prevents: Spawning 10,000 OS threads simultaneously, exhausting virtual memory and collapsing system under context switching.", "How does Kernel Threads vs User-Space Green Threads scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-12', 'phase-04-lesson-12-race-conditions-critical-sections-mutual-', 'module-6', 12, 'Lesson 6.12: Race Conditions, Critical Sections, & Mutual Exclusion', 'Prerequisites: Lesson 4.11', 'Prerequisites: Lesson 4.11 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 600.0, '# Lesson 4.12: Race Conditions, Critical Sections, & Mutual Exclusion

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.11
- **Subtopics**:
  - `4.12.1` Race conditions defined: output non-deterministically dependent on relative execution timing of concurrent threads.
  - `4.12.2` Critical Section: code block accessing shared mutable state that must execute atomically.
  - `4.12.3` Mutual Exclusion (Mutex): binary lock ensuring at most one thread executes inside the critical section.
  - `4.12.4` Mutex performance: futex (Fast Userspace Mutex) in Linux — avoiding syscalls on uncontended lock acquisitions.
- **Key Failure Modes & Edge Cases**: Data corruption in concurrent bank account balances caused by unprotected read-modify-write operations.
- **Verification & Mastery Check**: Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it using a Mutex.
- **Project Application**: NanoHTTP: Shared connection metrics.', '{"solution.py": "# Phase 4 // Lesson 4.12: Race Conditions, Critical Sections, & Mutual Exclusion\n\ndef solve():\n    \"\"\"\n    Verification: Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.12", "subtopics_count": 4, "verification_criteria": "Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it using a Mutex.", "subtopics": ["4.12.1 Race conditions defined: output non-deterministically dependent on relative execution timing of concurrent threads.", "4.12.2 Critical Section: code block accessing shared mutable state that must execute atomically.", "4.12.3 Mutual Exclusion (Mutex): binary lock ensuring at most one thread executes inside the critical section.", "4.12.4 Mutex performance: futex (Fast Userspace Mutex) in Linux \u2014 avoiding syscalls on uncontended lock acquisitions."]}'::jsonb, '["Explain how this implementation prevents: Data corruption in concurrent bank account balances caused by unprotected read-modify-write operations.", "How does Race Conditions, Critical Sections, & Mutual Exclusion scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-13', 'phase-04-lesson-13-deadlocks-coffman-conditions-lock-orderin', 'module-6', 13, 'Lesson 6.13: Deadlocks, Coffman Conditions, & Lock Ordering', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 650.0, '# Lesson 4.13: Deadlocks, Coffman Conditions, & Lock Ordering

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.13.1` Deadlock definition: two or more threads permanently blocked, each waiting for a lock held by the other.
  - `4.13.2` The Four Coffman Conditions: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait.
  - `4.13.3` Deadlock prevention via strict Lock Ordering: establishing a global lock hierarchy (always acquire Lock A before Lock B).
  - `4.13.4` Deadlock detection: resource allocation graphs and cycle detection; lock acquisition timeouts (`try_lock`).
- **Key Failure Modes & Edge Cases**: Intermittent production deadlocks occurring when two background jobs acquire database table locks in reverse order.
- **Verification & Mastery Check**: Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using strict lock hierarchies.
- **Project Application**: Database transaction concurrency in Phase 5.', '{"solution.py": "# Phase 4 // Lesson 4.13: Deadlocks, Coffman Conditions, & Lock Ordering\n\ndef solve():\n    \"\"\"\n    Verification: Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using st\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.13", "subtopics_count": 4, "verification_criteria": "Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using strict lock hierarchies.", "subtopics": ["4.13.1 Deadlock definition: two or more threads permanently blocked, each waiting for a lock held by the other.", "4.13.2 The Four Coffman Conditions: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait.", "4.13.3 Deadlock prevention via strict Lock Ordering: establishing a global lock hierarchy (always acquire Lock A before Lock B).", "4.13.4 Deadlock detection: resource allocation graphs and cycle detection; lock acquisition timeouts (`try_lock`)."]}'::jsonb, '["Explain how this implementation prevents: Intermittent production deadlocks occurring when two background jobs acquire database table locks in reverse order.", "How does Deadlocks, Coffman Conditions, & Lock Ordering scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-14', 'phase-04-lesson-14-condition-variables-thread-signaling', 'module-6', 14, 'Lesson 6.14: Condition Variables & Thread Signaling', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 700.0, '# Lesson 4.14: Condition Variables & Thread Signaling

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.14.1` The need for Condition Variables: waiting for a state condition to become true without busy-waiting (spinning).
  - `4.14.2` Condition Variable primitives: `wait(mutex)` (atomically releases mutex and sleeps), `signal()` / `notify()`, `broadcast()`.
  - `4.14.3` Spurious Wakeups: why condition variables must ALWAYS be checked inside a `while (!condition)` loop.
  - `4.14.4` Lost Wakeups: signaling a condition variable before a waiting thread has entered the wait state.
- **Key Failure Modes & Edge Cases**: Using an `if` statement instead of `while` with condition variables, causing data corruption on spurious wakeups.
- **Verification & Mastery Check**: Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`, `not_empty`).
- **Project Application**: NanoHTTP: Thread pool task queue.', '{"solution.py": "# Phase 4 // Lesson 4.14: Condition Variables & Thread Signaling\n\ndef solve():\n    \"\"\"\n    Verification: Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.14", "subtopics_count": 4, "verification_criteria": "Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`, `not_empty`).", "subtopics": ["4.14.1 The need for Condition Variables: waiting for a state condition to become true without busy-waiting (spinning).", "4.14.2 Condition Variable primitives: `wait(mutex)` (atomically releases mutex and sleeps), `signal()` / `notify()`, `broadcast()`.", "4.14.3 Spurious Wakeups: why condition variables must ALWAYS be checked inside a `while (!condition)` loop.", "4.14.4 Lost Wakeups: signaling a condition variable before a waiting thread has entered the wait state."]}'::jsonb, '["Explain how this implementation prevents: Using an `if` statement instead of `while` with condition variables, causing data corruption on spurious wakeups.", "How does Condition Variables & Thread Signaling scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-15', 'phase-04-lesson-15-read-write-locks-reader-writer-priority-d', 'module-6', 15, 'Lesson 6.15: Read-Write Locks & Reader-Writer Priority Dilemmas', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 750.0, '# Lesson 4.15: Read-Write Locks & Reader-Writer Priority Dilemmas

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.15.1` Shared-Exclusive Locking (Read-Write Lock / `rwlock`): multiple concurrent readers OR single exclusive writer.
  - `4.15.2` Reader-Preference locks: allows continuous readers; risks Writer Starvation under heavy read traffic.
  - `4.15.3` Writer-Preference locks: incoming readers wait once a writer requests the lock; prevents writer starvation.
  - `4.15.4` Fair Read-Write locks: FIFO ordering of readers and writers.
- **Key Failure Modes & Edge Cases**: Writer starvation in read-heavy caches where writers are permanently blocked from updating expired cache keys.
- **Verification & Mastery Check**: Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read throughput vs standard mutex.
- **Project Application**: CacheKit: Multi-threaded cache design.', '{"solution.py": "# Phase 4 // Lesson 4.15: Read-Write Locks & Reader-Writer Priority Dilemmas\n\ndef solve():\n    \"\"\"\n    Verification: Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read thro\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.15", "subtopics_count": 4, "verification_criteria": "Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read throughput vs standard mutex.", "subtopics": ["4.15.1 Shared-Exclusive Locking (Read-Write Lock / `rwlock`): multiple concurrent readers OR single exclusive writer.", "4.15.2 Reader-Preference locks: allows continuous readers; risks Writer Starvation under heavy read traffic.", "4.15.3 Writer-Preference locks: incoming readers wait once a writer requests the lock; prevents writer starvation.", "4.15.4 Fair Read-Write locks: FIFO ordering of readers and writers."]}'::jsonb, '["Explain how this implementation prevents: Writer starvation in read-heavy caches where writers are permanently blocked from updating expired cache keys.", "How does Read-Write Locks & Reader-Writer Priority Dilemmas scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-16', 'phase-04-lesson-16-spinlocks-atomic-operations-compare-and-s', 'module-6', 16, 'Lesson 6.16: Spinlocks, Atomic Operations, & Compare-And-Swap (CAS)', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 800.0, '# Lesson 4.16: Spinlocks, Atomic Operations, & Compare-And-Swap (CAS)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.16.1` Spinlocks: busy-waiting in a tight loop checking a lock flag; optimal when lock hold time is less than context-switch cost.
  - `4.16.2` Atomic CPU Instructions: `LOCK CMPXCHG` (Compare-And-Swap), `LOCK XADD` (Fetch-And-Add).
  - `4.16.3` Lock-Free Programming concepts: building concurrent data structures without mutexes using CAS loops.
  - `4.16.4` The ABA Problem in lock-free structures: memory reuse masking intermediate state modifications.
- **Key Failure Modes & Edge Cases**: Using spinlocks on single-core systems or holding spinlocks while performing blocking I/O, freezing the CPU core.
- **Verification & Mastery Check**: Implement a lock-free concurrent counter using atomic Compare-And-Swap operations.
- **Project Application**: High-performance concurrency foundation.', '{"solution.py": "# Phase 4 // Lesson 4.16: Spinlocks, Atomic Operations, & Compare-And-Swap (CAS)\n\ndef solve():\n    \"\"\"\n    Verification: Implement a lock-free concurrent counter using atomic Compare-And-Swap operations.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.16", "subtopics_count": 4, "verification_criteria": "Implement a lock-free concurrent counter using atomic Compare-And-Swap operations.", "subtopics": ["4.16.1 Spinlocks: busy-waiting in a tight loop checking a lock flag; optimal when lock hold time is less than context-switch cost.", "4.16.2 Atomic CPU Instructions: `LOCK CMPXCHG` (Compare-And-Swap), `LOCK XADD` (Fetch-And-Add).", "4.16.3 Lock-Free Programming concepts: building concurrent data structures without mutexes using CAS loops.", "4.16.4 The ABA Problem in lock-free structures: memory reuse masking intermediate state modifications."]}'::jsonb, '["Explain how this implementation prevents: Using spinlocks on single-core systems or holding spinlocks while performing blocking I/O, freezing the CPU core.", "How does Spinlocks, Atomic Operations, & Compare-And-Swap (CAS) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-17', 'phase-04-lesson-17-the-producer-consumer-pattern-thread-pool', 'module-6', 17, 'Lesson 6.17: The Producer-Consumer Pattern & Thread Pools', 'Prerequisites: Lesson 4.14', 'Prerequisites: Lesson 4.14 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 850.0, '# Lesson 4.17: The Producer-Consumer Pattern & Thread Pools

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.14
- **Subtopics**:
  - `4.17.1` Architecture of the Producer-Consumer pattern: decoupling task generation from task processing via bounded buffer.
  - `4.17.2` Backpressure handling: blocking producers when the task buffer reaches high-water mark capacity.
  - `4.17.3` Thread Pool architecture: pre-allocated worker threads listening on a shared task queue.
  - `4.17.4` Graceful thread pool shutdown: poison pill / sentinel task patterns to terminate idle worker threads.
- **Key Failure Modes & Edge Cases**: Unbounded task queues growing infinitely during traffic spikes until the process crashes via Out-Of-Memory.
- **Verification & Mastery Check**: Build a complete multi-threaded Thread Pool from scratch in C or Python supporting task submission and graceful shutdown.
- **Project Application**: NanoHTTP: Multi-threaded request worker pool.', '{"solution.py": "# Phase 4 // Lesson 4.17: The Producer-Consumer Pattern & Thread Pools\n\ndef solve():\n    \"\"\"\n    Verification: Build a complete multi-threaded Thread Pool from scratch in C or Python supporting task submission a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.17", "subtopics_count": 4, "verification_criteria": "Build a complete multi-threaded Thread Pool from scratch in C or Python supporting task submission and graceful shutdown.", "subtopics": ["4.17.1 Architecture of the Producer-Consumer pattern: decoupling task generation from task processing via bounded buffer.", "4.17.2 Backpressure handling: blocking producers when the task buffer reaches high-water mark capacity.", "4.17.3 Thread Pool architecture: pre-allocated worker threads listening on a shared task queue.", "4.17.4 Graceful thread pool shutdown: poison pill / sentinel task patterns to terminate idle worker threads."]}'::jsonb, '["Explain how this implementation prevents: Unbounded task queues growing infinitely during traffic spikes until the process crashes via Out-Of-Memory.", "How does The Producer-Consumer Pattern & Thread Pools scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-18', 'phase-04-lesson-18-livelock-priority-inversion-starvation', 'module-6', 18, 'Lesson 6.18: Livelock, Priority Inversion, & Starvation', 'Prerequisites: Lesson 4.13', 'Prerequisites: Lesson 4.13 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 900.0, '# Lesson 4.18: Livelock, Priority Inversion, & Starvation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.13
- **Subtopics**:
  - `4.18.1` Livelock: threads actively changing state in response to each other without making forward progress (e.g., hallway passing problem).
  - `4.18.2` Starvation: thread repeatedly denied access to shared resources due to scheduling imbalances or greedy competitors.
  - `4.18.3` Priority Inversion: low-priority thread holding a lock required by high-priority thread; preempted by medium-priority thread.
  - `4.18.4` Priority Inheritance Protocol: temporarily boosting low-priority thread''s priority to match waiting high-priority thread.
- **Key Failure Modes & Edge Cases**: The Mars Pathfinder spacecraft reset incident: classic priority inversion between audio task and bus task.
- **Verification & Mastery Check**: Construct a simulation demonstrating priority inversion and implement a priority inheritance wrapper to resolve it.
- **Project Application**: Systems concurrency mastery.', '{"solution.py": "# Phase 4 // Lesson 4.18: Livelock, Priority Inversion, & Starvation\n\ndef solve():\n    \"\"\"\n    Verification: Construct a simulation demonstrating priority inversion and implement a priority inheritance wrapper\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.18", "subtopics_count": 4, "verification_criteria": "Construct a simulation demonstrating priority inversion and implement a priority inheritance wrapper to resolve it.", "subtopics": ["4.18.1 Livelock: threads actively changing state in response to each other without making forward progress (e.g., hallway passing problem).", "4.18.2 Starvation: thread repeatedly denied access to shared resources due to scheduling imbalances or greedy competitors.", "4.18.3 Priority Inversion: low-priority thread holding a lock required by high-priority thread; preempted by medium-priority thread.", "4.18.4 Priority Inheritance Protocol: temporarily boosting low-priority thread''s priority to match waiting high-priority thread."]}'::jsonb, '["Explain how this implementation prevents: The Mars Pathfinder spacecraft reset incident: classic priority inversion between audio task and bus task.", "How does Livelock, Priority Inversion, & Starvation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-19', 'phase-04-lesson-19-socket-abstractions-non-blocking-file-des', 'module-6', 19, 'Lesson 6.19: Socket Abstractions & Non-Blocking File Descriptors', 'Prerequisites: Phase 0 (Lesson 0.20)', 'Prerequisites: Phase 0 (Lesson 0.20) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 950.0, '# Lesson 4.19: Socket Abstractions & Non-Blocking File Descriptors

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.20)
- **Subtopics**:
  - `4.19.1` BSD Socket API: `socket()`, `bind()`, `listen()`, `accept()`, `connect()`, `send()`, `recv()`.
  - `4.19.2` Blocking Sockets: calls block thread execution until data arrives or OS buffer drains.
  - `4.19.3` Non-Blocking Sockets: setting `O_NONBLOCK` via `fcntl()`; returning `EWOULDBLOCK` or `EAGAIN` immediately.
  - `4.19.4` The C10K Problem: why thread-per-connection architectures collapse when scaling past 10,000 concurrent sockets.
- **Key Failure Modes & Edge Cases**: Calling `recv()` in a tight while loop on non-blocking sockets without I/O multiplexing, pinning CPU at 100%.
- **Verification & Mastery Check**: Create a non-blocking TCP socket server and handle `EWOULDBLOCK` exceptions cleanly.
- **Project Application**: NanoHTTP: Socket configuration.', '{"solution.py": "# Phase 4 // Lesson 4.19: Socket Abstractions & Non-Blocking File Descriptors\n\ndef solve():\n    \"\"\"\n    Verification: Create a non-blocking TCP socket server and handle `EWOULDBLOCK` exceptions cleanly.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.19", "subtopics_count": 4, "verification_criteria": "Create a non-blocking TCP socket server and handle `EWOULDBLOCK` exceptions cleanly.", "subtopics": ["4.19.1 BSD Socket API: `socket()`, `bind()`, `listen()`, `accept()`, `connect()`, `send()`, `recv()`.", "4.19.2 Blocking Sockets: calls block thread execution until data arrives or OS buffer drains.", "4.19.3 Non-Blocking Sockets: setting `O_NONBLOCK` via `fcntl()`; returning `EWOULDBLOCK` or `EAGAIN` immediately.", "4.19.4 The C10K Problem: why thread-per-connection architectures collapse when scaling past 10,000 concurrent sockets."]}'::jsonb, '["Explain how this implementation prevents: Calling `recv()` in a tight while loop on non-blocking sockets without I/O multiplexing, pinning CPU at 100%.", "How does Socket Abstractions & Non-Blocking File Descriptors scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-20', 'phase-04-lesson-20-evolution-of-multiplexing-select-and-poll', 'module-6', 20, 'Lesson 6.20: Evolution of Multiplexing: `select()` and `poll()`', 'Prerequisites: Lesson 4.19', 'Prerequisites: Lesson 4.19 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 1000.0, '# Lesson 4.20: Evolution of Multiplexing: `select()` and `poll()`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.19
- **Subtopics**:
  - `4.20.1` I/O Multiplexing concept: asking the OS kernel to monitor multiple file descriptors and notify when any are ready.
  - `4.20.2` `select()` mechanics: bitmap arrays of file descriptors (`fd_set`); 1024 FD limit (`FD_SETSIZE`); $O(n)$ scanning.
  - `4.20.3` `poll()` mechanics: array of `pollfd` structs; removing 1024 limit; still suffers from $O(n)$ kernel-user scanning.
  - `4.20.4` Why `select` and `poll` scale poorly: copying file descriptor arrays back and forth between user and kernel space on every call.
- **Key Failure Modes & Edge Cases**: Attempting to monitor 10,000 connections with `select()`, triggering buffer overflow or severe $O(n)$ latency penalties.
- **Verification & Mastery Check**: Write a server using `select()` that multiplexes 50 client connections and measure performance degradation as connection count increases.
- **Project Application**: Systems evolution understanding.', '{"solution.py": "# Phase 4 // Lesson 4.20: Evolution of Multiplexing: `select()` and `poll()`\n\ndef solve():\n    \"\"\"\n    Verification: Write a server using `select()` that multiplexes 50 client connections and measure performance degra\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.20", "subtopics_count": 4, "verification_criteria": "Write a server using `select()` that multiplexes 50 client connections and measure performance degradation as connection count increases.", "subtopics": ["4.20.1 I/O Multiplexing concept: asking the OS kernel to monitor multiple file descriptors and notify when any are ready.", "4.20.2 `select()` mechanics: bitmap arrays of file descriptors (`fd_set`); 1024 FD limit (`FD_SETSIZE`); $O(n)$ scanning.", "4.20.3 `poll()` mechanics: array of `pollfd` structs; removing 1024 limit; still suffers from $O(n)$ kernel-user scanning.", "4.20.4 Why `select` and `poll` scale poorly: copying file descriptor arrays back and forth between user and kernel space on every call."]}'::jsonb, '["Explain how this implementation prevents: Attempting to monitor 10,000 connections with `select()`, triggering buffer overflow or severe $O(n)$ latency penalties.", "How does Evolution of Multiplexing: `select()` and `poll()` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-21', 'phase-04-lesson-21-linux-epoll-architecture-red-black-trees-', 'module-6', 21, 'Lesson 6.21: Linux `epoll` Architecture: Red-Black Trees & Ready Lists', 'Prerequisites: Lesson 4.20', 'Prerequisites: Lesson 4.20 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 1050.0, '# Lesson 4.21: Linux `epoll` Architecture: Red-Black Trees & Ready Lists

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.20
- **Subtopics**:
  - `4.21.1` Why `epoll` is $O(1)$: kernel-maintained data structures persisting across system calls.
  - `4.21.2` The Interest List: Red-Black tree storing monitored file descriptors; efficient insertion, deletion, modification in $O(\log n)$.
  - `4.21.3` The Ready List: doubly linked list of file descriptors with ready I/O events; populated asynchronously by kernel driver callbacks.
  - `4.21.4` `epoll` system calls: `epoll_create1(EPOLL_CLOEXEC)`, `epoll_ctl()` (EPOLL_CTL_ADD, MOD, DEL), `epoll_wait()`.
- **Key Failure Modes & Edge Cases**: Failing to remove closed file descriptors from epoll sets, leading to spurious wakeups or memory leaks in older kernels.
- **Verification & Mastery Check**: Write a raw C or Python script invoking `epoll_create1`, registering sockets, and handling events via `epoll_wait`.
- **Project Application**: NanoHTTP: Version 2 (Async/Event-driven server).', '{"solution.py": "# Phase 4 // Lesson 4.21: Linux `epoll` Architecture: Red-Black Trees & Ready Lists\n\ndef solve():\n    \"\"\"\n    Verification: Write a raw C or Python script invoking `epoll_create1`, registering sockets, and handling events vi\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.21", "subtopics_count": 4, "verification_criteria": "Write a raw C or Python script invoking `epoll_create1`, registering sockets, and handling events via `epoll_wait`.", "subtopics": ["4.21.1 Why `epoll` is $O(1)$: kernel-maintained data structures persisting across system calls.", "4.21.2 The Interest List: Red-Black tree storing monitored file descriptors; efficient insertion, deletion, modification in $O(\\log n)$.", "4.21.3 The Ready List: doubly linked list of file descriptors with ready I/O events; populated asynchronously by kernel driver callbacks.", "4.21.4 `epoll` system calls: `epoll_create1(EPOLL_CLOEXEC)`, `epoll_ctl()` (EPOLL_CTL_ADD, MOD, DEL), `epoll_wait()`."]}'::jsonb, '["Explain how this implementation prevents: Failing to remove closed file descriptors from epoll sets, leading to spurious wakeups or memory leaks in older kernels.", "How does Linux `epoll` Architecture: Red-Black Trees & Ready Lists scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-22', 'phase-04-lesson-22-level-triggered-lt-vs-edge-triggered-et-e', 'module-6', 22, 'Lesson 6.22: Level-Triggered (LT) vs Edge-Triggered (ET) epoll', 'Prerequisites: Lesson 4.21', 'Prerequisites: Lesson 4.21 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 1100.0, '# Lesson 4.22: Level-Triggered (LT) vs Edge-Triggered (ET) epoll

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.21
- **Subtopics**:
  - `4.22.1` Level-Triggered (LT) mode: `epoll_wait()` returns as long as buffer has unread data (safe, forgiving default).
  - `4.22.2` Edge-Triggered (ET) mode (`EPOLLET`): `epoll_wait()` notifies ONLY on state change (data arrival transition).
  - `4.22.3` The Edge-Triggered contract: must read socket in a loop until it returns `EAGAIN` / `EWOULDBLOCK`.
  - `4.22.4` Starvation in ET: long-running loops reading a single chatty socket while other sockets wait in ready list.
- **Key Failure Modes & Edge Cases**: Using Edge-Triggered epoll but reading only once, causing the connection to hang indefinitely waiting for the next packet.
- **Verification & Mastery Check**: Implement an Edge-Triggered epoll event loop that correctly reads until `EAGAIN` and handles concurrent connections.
- **Project Application**: NanoHTTP: High-concurrency socket engine.', '{"solution.py": "# Phase 4 // Lesson 4.22: Level-Triggered (LT) vs Edge-Triggered (ET) epoll\n\ndef solve():\n    \"\"\"\n    Verification: Implement an Edge-Triggered epoll event loop that correctly reads until `EAGAIN` and handles concurr\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.22", "subtopics_count": 4, "verification_criteria": "Implement an Edge-Triggered epoll event loop that correctly reads until `EAGAIN` and handles concurrent connections.", "subtopics": ["4.22.1 Level-Triggered (LT) mode: `epoll_wait()` returns as long as buffer has unread data (safe, forgiving default).", "4.22.2 Edge-Triggered (ET) mode (`EPOLLET`): `epoll_wait()` notifies ONLY on state change (data arrival transition).", "4.22.3 The Edge-Triggered contract: must read socket in a loop until it returns `EAGAIN` / `EWOULDBLOCK`.", "4.22.4 Starvation in ET: long-running loops reading a single chatty socket while other sockets wait in ready list."]}'::jsonb, '["Explain how this implementation prevents: Using Edge-Triggered epoll but reading only once, causing the connection to hang indefinitely waiting for the next packe", "How does Level-Triggered (LT) vs Edge-Triggered (ET) epoll scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-23', 'phase-04-lesson-23-event-loop-architectures-reactor-vs-proac', 'module-6', 23, 'Lesson 6.23: Event Loop Architectures: Reactor vs Proactor Patterns', 'Prerequisites: Lesson 4.21', 'Prerequisites: Lesson 4.21 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 1150.0, '# Lesson 4.23: Event Loop Architectures: Reactor vs Proactor Patterns

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.21
- **Subtopics**:
  - `4.23.1` The Reactor Pattern: synchronous event demultiplexer notifying application event handlers when resources are ready (Node.js, Redis, Nginx, Python asyncio).
  - `4.23.2` The Proactor Pattern: asynchronous I/O completion framework; OS initiates I/O and notifies handlers upon completion (Windows IOCP, Linux io_uring).
  - `4.23.3` Linux `io_uring`: modern submission and completion ring buffers sharing memory between kernel and user space; zero syscalls.
  - `4.23.4` Thread-safe event loops: wake-up pipes / eventfd primitives for signaling event loops from other threads.
- **Key Failure Modes & Edge Cases**: Blocking the single-threaded Reactor event loop with synchronous CPU work, freezing all concurrent network connections.
- **Verification & Mastery Check**: Design and implement a single-threaded Reactor event loop from scratch handling timer events and network events.
- **Project Application**: Foundation for Phase 1 Python asyncio and Node.js in Phase 6.', '{"solution.py": "# Phase 4 // Lesson 4.23: Event Loop Architectures: Reactor vs Proactor Patterns\n\ndef solve():\n    \"\"\"\n    Verification: Design and implement a single-threaded Reactor event loop from scratch handling timer events and net\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.23", "subtopics_count": 4, "verification_criteria": "Design and implement a single-threaded Reactor event loop from scratch handling timer events and network events.", "subtopics": ["4.23.1 The Reactor Pattern: synchronous event demultiplexer notifying application event handlers when resources are ready (Node.js, Redis, Nginx, Python asyncio).", "4.23.2 The Proactor Pattern: asynchronous I/O completion framework; OS initiates I/O and notifies handlers upon completion (Windows IOCP, Linux io_uring).", "4.23.3 Linux `io_uring`: modern submission and completion ring buffers sharing memory between kernel and user space; zero syscalls.", "4.23.4 Thread-safe event loops: wake-up pipes / eventfd primitives for signaling event loops from other threads."]}'::jsonb, '["Explain how this implementation prevents: Blocking the single-threaded Reactor event loop with synchronous CPU work, freezing all concurrent network connections.", "How does Event Loop Architectures: Reactor vs Proactor Patterns scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-24', 'phase-04-lesson-24-socket-options-tuning-so-reuseaddr-so-reu', 'module-6', 24, 'Lesson 6.24: Socket Options & Tuning: `SO_REUSEADDR`, `SO_REUSEPORT`, `TCP_NODELAY`', 'Prerequisites: Phase 0 (Lesson 0.20), Lesson 4.19', 'Prerequisites: Phase 0 (Lesson 0.20), Lesson 4.19 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 1200.0, '# Lesson 4.24: Socket Options & Tuning: `SO_REUSEADDR`, `SO_REUSEPORT`, `TCP_NODELAY`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.20), Lesson 4.19
- **Subtopics**:
  - `4.24.1` `SO_REUSEADDR`: allowing immediate binding to a local address in `TIME_WAIT` state upon server restarts.
  - `4.24.2` `SO_REUSEPORT`: allowing multiple independent server sockets to bind to the exact same port; kernel-level load balancing across processes.
  - `4.24.3` `TCP_NODELAY`: disabling Nagle''s algorithm to eliminate artificial packet batching latency in real-time RPC protocols.
  - `4.24.4` Socket buffer sizing: `SO_RCVBUF` and `SO_SNDBUF`; TCP auto-tuning and bandwidth-delay product.
- **Key Failure Modes & Edge Cases**: `OSError: [Errno 98] Address already in use` upon server restarts caused by omitting `SO_REUSEADDR`.
- **Verification & Mastery Check**: Demonstrate server restart failure without `SO_REUSEADDR`, fix it, and benchmark latency reduction of `TCP_NODELAY`.
- **Project Application**: NanoHTTP: Mandatory socket configuration.', '{"solution.py": "# Phase 4 // Lesson 4.24: Socket Options & Tuning: `SO_REUSEADDR`, `SO_REUSEPORT`, `TCP_NODELAY`\n\ndef solve():\n    \"\"\"\n    Verification: Demonstrate server restart failure without `SO_REUSEADDR`, fix it, and benchmark latency reduction o\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.24", "subtopics_count": 4, "verification_criteria": "Demonstrate server restart failure without `SO_REUSEADDR`, fix it, and benchmark latency reduction of `TCP_NODELAY`.", "subtopics": ["4.24.1 `SO_REUSEADDR`: allowing immediate binding to a local address in `TIME_WAIT` state upon server restarts.", "4.24.2 `SO_REUSEPORT`: allowing multiple independent server sockets to bind to the exact same port; kernel-level load balancing across processes.", "4.24.3 `TCP_NODELAY`: disabling Nagle''s algorithm to eliminate artificial packet batching latency in real-time RPC protocols.", "4.24.4 Socket buffer sizing: `SO_RCVBUF` and `SO_SNDBUF`; TCP auto-tuning and bandwidth-delay product."]}'::jsonb, '["Explain how this implementation prevents: `OSError: [Errno 98] Address already in use` upon server restarts caused by omitting `SO_REUSEADDR`.", "How does Socket Options & Tuning: `SO_REUSEADDR`, `SO_REUSEPORT`, `TCP_NODELAY` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-25', 'phase-04-lesson-25-the-tcp-three-way-handshake-connection-st', 'module-6', 25, 'Lesson 6.25: The TCP Three-Way Handshake & Connection State Machine', 'Prerequisites: Phase 0 (Lesson 0.6)', 'Prerequisites: Phase 0 (Lesson 0.6) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 1250.0, '# Lesson 4.25: The TCP Three-Way Handshake & Connection State Machine

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.6)
- **Subtopics**:
  - `4.25.1` TCP Three-Way Handshake: SYN (Seq=x) $	o$ SYN-ACK (Seq=y, Ack=x+1) $	o$ ACK (Seq=x+1, Ack=y+1).
  - `4.25.2` TCP State Machine: LISTEN, SYN_SENT, SYN_RECEIVED, ESTABLISHED, FIN_WAIT_1, FIN_WAIT_2, CLOSE_WAIT, CLOSING, LAST_ACK, TIME_WAIT, CLOSED.
  - `4.25.3` SYN Flood attacks: half-open connections exhausting backlog queues; defense via SYN Cookies (`tcp_syncookies`).
  - `4.25.4` Connection teardown: four-way FIN handshake and `TIME_WAIT` duration (2MSL - Maximum Segment Lifetime, typically 60s).
- **Key Failure Modes & Edge Cases**: SYN backlog exhaustion crashing production servers during sudden traffic spikes.
- **Verification & Mastery Check**: Capture a complete TCP three-way handshake using `tcpdump` and inspect sequence numbers in Wireshark.
- **Project Application**: NanoHTTP: Connection lifecycle.', '{"solution.py": "# Phase 4 // Lesson 4.25: The TCP Three-Way Handshake & Connection State Machine\n\ndef solve():\n    \"\"\"\n    Verification: Capture a complete TCP three-way handshake using `tcpdump` and inspect sequence numbers in Wireshark\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.25", "subtopics_count": 4, "verification_criteria": "Capture a complete TCP three-way handshake using `tcpdump` and inspect sequence numbers in Wireshark.", "subtopics": ["4.25.1 TCP Three-Way Handshake: SYN (Seq=x) $\to$ SYN-ACK (Seq=y, Ack=x+1) $\to$ ACK (Seq=x+1, Ack=y+1).", "4.25.2 TCP State Machine: LISTEN, SYN_SENT, SYN_RECEIVED, ESTABLISHED, FIN_WAIT_1, FIN_WAIT_2, CLOSE_WAIT, CLOSING, LAST_ACK, TIME_WAIT, CLOSED.", "4.25.3 SYN Flood attacks: half-open connections exhausting backlog queues; defense via SYN Cookies (`tcp_syncookies`).", "4.25.4 Connection teardown: four-way FIN handshake and `TIME_WAIT` duration (2MSL - Maximum Segment Lifetime, typically 60s)."]}'::jsonb, '["Explain how this implementation prevents: SYN backlog exhaustion crashing production servers during sudden traffic spikes.", "How does The TCP Three-Way Handshake & Connection State Machine scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-26', 'phase-04-lesson-26-tcp-reliability-flow-control-congestion-c', 'module-6', 26, 'Lesson 6.26: TCP Reliability, Flow Control, & Congestion Control', 'Prerequisites: Lesson 4.25', 'Prerequisites: Lesson 4.25 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 1300.0, '# Lesson 4.26: TCP Reliability, Flow Control, & Congestion Control

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.25
- **Subtopics**:
  - `4.26.1` Sequence numbers and cumulative ACKs: detecting packet loss, duplicates, and out-of-order delivery.
  - `4.26.2` Sliding Window Flow Control: receiver''s Advertised Window (`rwnd`) preventing sender from overwhelming receiver''s buffer.
  - `4.26.3` Zero Window Probing: sender probing receiver when window drops to 0.
  - `4.26.4` Congestion Control: Congestion Window (`cwnd`), Slow Start, Congestion Avoidance, Fast Retransmit (3 duplicate ACKs), Fast Recovery; TCP CUBIC and BBR.
- **Key Failure Modes & Edge Cases**: Packet buffer bloat causing severe latency spikes on lossy network connections.
- **Verification & Mastery Check**: Simulate packet loss using Linux `tc` (traffic control) and observe TCP window contraction and retransmission behavior.
- **Project Application**: Systems network optimization.', '{"solution.py": "# Phase 4 // Lesson 4.26: TCP Reliability, Flow Control, & Congestion Control\n\ndef solve():\n    \"\"\"\n    Verification: Simulate packet loss using Linux `tc` (traffic control) and observe TCP window contraction and retra\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.26", "subtopics_count": 4, "verification_criteria": "Simulate packet loss using Linux `tc` (traffic control) and observe TCP window contraction and retransmission behavior.", "subtopics": ["4.26.1 Sequence numbers and cumulative ACKs: detecting packet loss, duplicates, and out-of-order delivery.", "4.26.2 Sliding Window Flow Control: receiver''s Advertised Window (`rwnd`) preventing sender from overwhelming receiver''s buffer.", "4.26.3 Zero Window Probing: sender probing receiver when window drops to 0.", "4.26.4 Congestion Control: Congestion Window (`cwnd`), Slow Start, Congestion Avoidance, Fast Retransmit (3 duplicate ACKs), Fast Recovery; TCP CUBIC and BBR."]}'::jsonb, '["Explain how this implementation prevents: Packet buffer bloat causing severe latency spikes on lossy network connections.", "How does TCP Reliability, Flow Control, & Congestion Control scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-27', 'phase-04-lesson-27-dns-resolution-record-types-caching-hiera', 'module-6', 27, 'Lesson 6.27: DNS Resolution, Record Types, & Caching Hierarchies', 'Prerequisites: Lesson 4.25', 'Prerequisites: Lesson 4.25 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 1350.0, '# Lesson 4.27: DNS Resolution, Record Types, & Caching Hierarchies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.25
- **Subtopics**:
  - `4.27.1` DNS hierarchy: Root servers (13 named authorities), Top-Level Domain (TLD) servers, Authoritative nameservers.
  - `4.27.2` Recursive Resolvers vs Iterative Resolvers; caching and Time-To-Live (TTL) expiration.
  - `4.27.3` Record types: `A` (IPv4), `AAAA` (IPv6), `CNAME` (canonical alias), `MX` (mail), `TXT` (SPF/verification), `SRV` (service discovery).
  - `4.27.4` Debugging DNS with `dig`: `dig +trace`, `dig +short`, inspecting EDNS client subnet headers.
- **Key Failure Modes & Edge Cases**: DNS TTL misconfigurations causing multi-day customer outages after cloud IP address migrations.
- **Verification & Mastery Check**: Perform a full recursive trace of a domain from root servers to authoritative nameservers using `dig +trace`.
- **Project Application**: InfraBlueprint: Cloud DNS configuration in Phase 7.', '{"solution.py": "# Phase 4 // Lesson 4.27: DNS Resolution, Record Types, & Caching Hierarchies\n\ndef solve():\n    \"\"\"\n    Verification: Perform a full recursive trace of a domain from root servers to authoritative nameservers using `dig\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.27", "subtopics_count": 4, "verification_criteria": "Perform a full recursive trace of a domain from root servers to authoritative nameservers using `dig +trace`.", "subtopics": ["4.27.1 DNS hierarchy: Root servers (13 named authorities), Top-Level Domain (TLD) servers, Authoritative nameservers.", "4.27.2 Recursive Resolvers vs Iterative Resolvers; caching and Time-To-Live (TTL) expiration.", "4.27.3 Record types: `A` (IPv4), `AAAA` (IPv6), `CNAME` (canonical alias), `MX` (mail), `TXT` (SPF/verification), `SRV` (service discovery).", "4.27.4 Debugging DNS with `dig`: `dig +trace`, `dig +short`, inspecting EDNS client subnet headers."]}'::jsonb, '["Explain how this implementation prevents: DNS TTL misconfigurations causing multi-day customer outages after cloud IP address migrations.", "How does DNS Resolution, Record Types, & Caching Hierarchies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-28', 'phase-04-lesson-28-tls-1-3-handshake-perfect-forward-secrecy', 'module-6', 28, 'Lesson 6.28: TLS 1.3 Handshake, Perfect Forward Secrecy, & PKI', 'Prerequisites: Lesson 4.25', 'Prerequisites: Lesson 4.25 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 1400.0, '# Lesson 4.28: TLS 1.3 Handshake, Perfect Forward Secrecy, & PKI

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.25
- **Subtopics**:
  - `4.28.1` Transport Layer Security (TLS 1.3) vs legacy TLS 1.2: removing insecure ciphers, mandating 1-RTT handshake.
  - `4.28.2` Key Exchange via Ephemeral Diffie-Hellman (ECDHE): deriving session keys over insecure channels without transmitting secrets.
  - `4.28.3` Perfect Forward Secrecy (PFS): compromising server private key does NOT compromise previously recorded session traffic.
  - `4.28.4` Public Key Infrastructure (PKI): X.509 certificate format, Certificate Authorities, intermediate chains, OCSP stapling.
- **Key Failure Modes & Edge Cases**: Serving broken certificate chains lacking intermediate CA certificates, causing untrusted certificate warnings on mobile clients.
- **Verification & Mastery Check**: Inspect a TLS 1.3 handshake using `openssl s_client -connect host:443 -tls1_3` and verify cipher suite and certificate chain.
- **Project Application**: InfraBlueprint: SSL termination.', '{"solution.py": "# Phase 4 // Lesson 4.28: TLS 1.3 Handshake, Perfect Forward Secrecy, & PKI\n\ndef solve():\n    \"\"\"\n    Verification: Inspect a TLS 1.3 handshake using `openssl s_client -connect host:443 -tls1_3` and verify cipher sui\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.28", "subtopics_count": 4, "verification_criteria": "Inspect a TLS 1.3 handshake using `openssl s_client -connect host:443 -tls1_3` and verify cipher suite and certificate chain.", "subtopics": ["4.28.1 Transport Layer Security (TLS 1.3) vs legacy TLS 1.2: removing insecure ciphers, mandating 1-RTT handshake.", "4.28.2 Key Exchange via Ephemeral Diffie-Hellman (ECDHE): deriving session keys over insecure channels without transmitting secrets.", "4.28.3 Perfect Forward Secrecy (PFS): compromising server private key does NOT compromise previously recorded session traffic.", "4.28.4 Public Key Infrastructure (PKI): X.509 certificate format, Certificate Authorities, intermediate chains, OCSP stapling."]}'::jsonb, '["Explain how this implementation prevents: Serving broken certificate chains lacking intermediate CA certificates, causing untrusted certificate warnings on mobile", "How does TLS 1.3 Handshake, Perfect Forward Secrecy, & PKI scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-29', 'phase-04-lesson-29-http-1-1-vs-http-2-vs-http-3-quic-framing', 'module-6', 29, 'Lesson 6.29: HTTP/1.1 vs HTTP/2 vs HTTP/3 (QUIC) Framing', 'Prerequisites: Lesson 4.25', 'Prerequisites: Lesson 4.25 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 1450.0, '# Lesson 4.29: HTTP/1.1 vs HTTP/2 vs HTTP/3 (QUIC) Framing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.25
- **Subtopics**:
  - `4.29.1` HTTP/1.1 limitations: plaintext framing, Head-of-Line (HoL) blocking on TCP connection, persistent connection reuse.
  - `4.29.2` HTTP/2 binary framing: Streams, Frames (HEADERS, DATA, SETTINGS), stream multiplexing over a single TCP connection, HPACK compression.
  - `4.29.3` HTTP/2 Head-of-Line blocking at TCP level: a single dropped packet stalls all multiplexed streams.
  - `4.29.4` HTTP/3 & QUIC: running over UDP; independent streams eliminating TCP HoL blocking; 0-RTT connection resumption; connection migration across IP changes.
- **Key Failure Modes & Edge Cases**: Creating dozens of parallel TCP connections for HTTP/1.1 domain sharding when HTTP/2 multiplexing makes it an anti-pattern.
- **Verification & Mastery Check**: Capture and decode HTTP/2 binary frames using Wireshark, identifying stream IDs and HPACK header compression.
- **Project Application**: NanoHTTP and API gateway architectures.', '{"solution.py": "# Phase 4 // Lesson 4.29: HTTP/1.1 vs HTTP/2 vs HTTP/3 (QUIC) Framing\n\ndef solve():\n    \"\"\"\n    Verification: Capture and decode HTTP/2 binary frames using Wireshark, identifying stream IDs and HPACK header com\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.29", "subtopics_count": 4, "verification_criteria": "Capture and decode HTTP/2 binary frames using Wireshark, identifying stream IDs and HPACK header compression.", "subtopics": ["4.29.1 HTTP/1.1 limitations: plaintext framing, Head-of-Line (HoL) blocking on TCP connection, persistent connection reuse.", "4.29.2 HTTP/2 binary framing: Streams, Frames (HEADERS, DATA, SETTINGS), stream multiplexing over a single TCP connection, HPACK compression.", "4.29.3 HTTP/2 Head-of-Line blocking at TCP level: a single dropped packet stalls all multiplexed streams.", "4.29.4 HTTP/3 & QUIC: running over UDP; independent streams eliminating TCP HoL blocking; 0-RTT connection resumption; connection migration across IP changes."]}'::jsonb, '["Explain how this implementation prevents: Creating dozens of parallel TCP connections for HTTP/1.1 domain sharding when HTTP/2 multiplexing makes it an anti-patte", "How does HTTP/1.1 vs HTTP/2 vs HTTP/3 (QUIC) Framing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-30', 'phase-04-lesson-30-network-socket-benchmarking-with-wrk', 'module-6', 30, 'Lesson 6.30: Network & Socket Benchmarking with `wrk`', 'Prerequisites: Lesson 4.25', 'Prerequisites: Lesson 4.25 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 1500.0, '# Lesson 4.30: Network & Socket Benchmarking with `wrk`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.25
- **Subtopics**:
  - `4.30.1` Benchmarking methodology: open vs closed workload models; Coordinated Omission problem and latency percentile skew.
  - `4.30.2` The `wrk` benchmarking engine: multi-threaded, epoll-driven load generation; executing Lua scripts for dynamic payloads.
  - `4.30.3` Interpreting metrics: Throughput (RPS), Latency percentiles (p50, p90, p99, p99.9), Error counts.
  - `4.30.4` OS kernel tuning for high load: `sysctl` parameters (`net.core.somaxconn`, `net.ipv4.tcp_max_syn_backlog`, ephemeral port ranges).
- **Key Failure Modes & Edge Cases**: Reporting average latency instead of p99/p99.9 tail latencies, hiding severe multi-second stutter affecting 1% of users.
- **Verification & Mastery Check**: Execute a load test with `wrk -t4 -c100 -d30s` against an HTTP server, measure p99 latency, and identify kernel bottlenecks.
- **Project Application**: NanoHTTP: Performance benchmarking.', '{"solution.py": "# Phase 4 // Lesson 4.30: Network & Socket Benchmarking with `wrk`\n\ndef solve():\n    \"\"\"\n    Verification: Execute a load test with `wrk -t4 -c100 -d30s` against an HTTP server, measure p99 latency, and iden\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.30", "subtopics_count": 4, "verification_criteria": "Execute a load test with `wrk -t4 -c100 -d30s` against an HTTP server, measure p99 latency, and identify kernel bottlenecks.", "subtopics": ["4.30.1 Benchmarking methodology: open vs closed workload models; Coordinated Omission problem and latency percentile skew.", "4.30.2 The `wrk` benchmarking engine: multi-threaded, epoll-driven load generation; executing Lua scripts for dynamic payloads.", "4.30.3 Interpreting metrics: Throughput (RPS), Latency percentiles (p50, p90, p99, p99.9), Error counts.", "4.30.4 OS kernel tuning for high load: `sysctl` parameters (`net.core.somaxconn`, `net.ipv4.tcp_max_syn_backlog`, ephemeral port ranges)."]}'::jsonb, '["Explain how this implementation prevents: Reporting average latency instead of p99/p99.9 tail latencies, hiding severe multi-second stutter affecting 1% of users.", "How does Network & Socket Benchmarking with `wrk` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-31', 'phase-04-lesson-31-operating-system-metrics-cpu-load-average', 'module-6', 31, 'Lesson 6.31: Operating System Metrics: CPU, Load Average, & Runqueues', 'Prerequisites: Phase 0 (Lesson 0.5)', 'Prerequisites: Phase 0 (Lesson 0.5) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 1550.0, '# Lesson 4.31: Operating System Metrics: CPU, Load Average, & Runqueues

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.5)
- **Subtopics**:
  - `4.31.1` CPU metrics: User time (%usr), System time (%sys), I/O wait (%iowait), Idle time (%idle), Steal time (%steal).
  - `4.31.2` Understanding Linux Load Average: 1, 5, 15-minute metrics; count of processes in TASK_RUNNING and TASK_UNINTERRUPTIBLE states.
  - `4.31.3` CPU Runqueues: measuring thread scheduling queues via `vmstat` and identifying CPU saturation.
  - `4.31.4` Distinguishing CPU saturation from I/O bottleneck using `vmstat` and `iostat`.
- **Key Failure Modes & Edge Cases**: Misinterpreting high `%iowait` as a CPU processing bottleneck when the disk storage array is saturated.
- **Verification & Mastery Check**: Run a CPU stress script, observe load average and runqueue depth using `vmstat 1`, and analyze metric changes.
- **Project Application**: SysTrace: System health dashboard.', '{"solution.py": "# Phase 4 // Lesson 4.31: Operating System Metrics: CPU, Load Average, & Runqueues\n\ndef solve():\n    \"\"\"\n    Verification: Run a CPU stress script, observe load average and runqueue depth using `vmstat 1`, and analyze metri\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.31", "subtopics_count": 4, "verification_criteria": "Run a CPU stress script, observe load average and runqueue depth using `vmstat 1`, and analyze metric changes.", "subtopics": ["4.31.1 CPU metrics: User time (%usr), System time (%sys), I/O wait (%iowait), Idle time (%idle), Steal time (%steal).", "4.31.2 Understanding Linux Load Average: 1, 5, 15-minute metrics; count of processes in TASK_RUNNING and TASK_UNINTERRUPTIBLE states.", "4.31.3 CPU Runqueues: measuring thread scheduling queues via `vmstat` and identifying CPU saturation.", "4.31.4 Distinguishing CPU saturation from I/O bottleneck using `vmstat` and `iostat`."]}'::jsonb, '["Explain how this implementation prevents: Misinterpreting high `%iowait` as a CPU processing bottleneck when the disk storage array is saturated.", "How does Operating System Metrics: CPU, Load Average, & Runqueues scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-32', 'phase-04-lesson-32-disk-i-o-profiling-iops-latency-iostat', 'module-6', 32, 'Lesson 6.32: Disk I/O Profiling: IOPS, Latency, & `iostat`', 'Prerequisites: Lesson 4.31', 'Prerequisites: Lesson 4.31 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 1600.0, '# Lesson 4.32: Disk I/O Profiling: IOPS, Latency, & `iostat`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.31
- **Subtopics**:
  - `4.32.1` Disk performance primitives: Throughput (MB/s) vs Input/Output Operations Per Second (IOPS).
  - `4.32.2` Rotational latency and seek time (HDD) vs NAND flash memory cell wear and page read/write (SSD/NVMe).
  - `4.32.3` Using `iostat -xz 1`: r/s (read IOPS), w/s (write IOPS), r_await / w_await (I/O latency in ms), %util (device saturation).
  - `4.32.4` Write Amplification in SSDs and file system page cache flushing (`sync`, `fsync`).
- **Key Failure Modes & Edge Cases**: Saturating disk IOPS with unbuffered random small writes, causing global application latency spikes.
- **Verification & Mastery Check**: Generate random disk write workloads using `dd` and profile IOPS, wait times, and utilization using `iostat`.
- **Project Application**: Database performance tuning in Phase 5.', '{"solution.py": "# Phase 4 // Lesson 4.32: Disk I/O Profiling: IOPS, Latency, & `iostat`\n\ndef solve():\n    \"\"\"\n    Verification: Generate random disk write workloads using `dd` and profile IOPS, wait times, and utilization using \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.32", "subtopics_count": 4, "verification_criteria": "Generate random disk write workloads using `dd` and profile IOPS, wait times, and utilization using `iostat`.", "subtopics": ["4.32.1 Disk performance primitives: Throughput (MB/s) vs Input/Output Operations Per Second (IOPS).", "4.32.2 Rotational latency and seek time (HDD) vs NAND flash memory cell wear and page read/write (SSD/NVMe).", "4.32.3 Using `iostat -xz 1`: r/s (read IOPS), w/s (write IOPS), r_await / w_await (I/O latency in ms), %util (device saturation).", "4.32.4 Write Amplification in SSDs and file system page cache flushing (`sync`, `fsync`)."]}'::jsonb, '["Explain how this implementation prevents: Saturating disk IOPS with unbuffered random small writes, causing global application latency spikes.", "How does Disk I/O Profiling: IOPS, Latency, & `iostat` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-33', 'phase-04-lesson-33-network-profiling-sockets-drops-ss-netsta', 'module-6', 33, 'Lesson 6.33: Network Profiling: Sockets, Drops, & `ss` / `netstat`', 'Prerequisites: Lesson 4.25', 'Prerequisites: Lesson 4.25 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 1650.0, '# Lesson 4.33: Network Profiling: Sockets, Drops, & `ss` / `netstat`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.25
- **Subtopics**:
  - `4.33.1` Socket statistics with `ss`: inspecting TCP socket states (`ss -tulpn`), send/receive buffer queues.
  - `4.33.2` Detecting dropped packets: parsing `/proc/net/snmp` and `netstat -s` (ListenOverflows, ListenDrops).
  - `4.33.3` Socket buffer queue filling: identifying slow application processing when Recv-Q remains non-zero.
  - `4.33.4` Bandwidth monitoring with `iftop` and `nload`; packet loss detection with `mtr`.
- **Key Failure Modes & Edge Cases**: Ignoring `ListenOverflows` in `ss -s`, missing silent kernel TCP connection drops during traffic bursts.
- **Verification & Mastery Check**: Simulate socket backlog saturation on an HTTP server and observe `ListenDrops` counters incrementing in real time.
- **Project Application**: SysTrace and InfraBlueprint.', '{"solution.py": "# Phase 4 // Lesson 4.33: Network Profiling: Sockets, Drops, & `ss` / `netstat`\n\ndef solve():\n    \"\"\"\n    Verification: Simulate socket backlog saturation on an HTTP server and observe `ListenDrops` counters incrementing\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.33", "subtopics_count": 4, "verification_criteria": "Simulate socket backlog saturation on an HTTP server and observe `ListenDrops` counters incrementing in real time.", "subtopics": ["4.33.1 Socket statistics with `ss`: inspecting TCP socket states (`ss -tulpn`), send/receive buffer queues.", "4.33.2 Detecting dropped packets: parsing `/proc/net/snmp` and `netstat -s` (ListenOverflows, ListenDrops).", "4.33.3 Socket buffer queue filling: identifying slow application processing when Recv-Q remains non-zero.", "4.33.4 Bandwidth monitoring with `iftop` and `nload`; packet loss detection with `mtr`."]}'::jsonb, '["Explain how this implementation prevents: Ignoring `ListenOverflows` in `ss -s`, missing silent kernel TCP connection drops during traffic bursts.", "How does Network Profiling: Sockets, Drops, & `ss` / `netstat` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-34', 'phase-04-lesson-34-dynamic-tracing-with-strace-kernel-call-p', 'module-6', 34, 'Lesson 6.34: Dynamic Tracing with `strace` & Kernel Call Profiling', 'Prerequisites: Phase 0 (Lesson 0.17)', 'Prerequisites: Phase 0 (Lesson 0.17) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 1700.0, '# Lesson 4.34: Dynamic Tracing with `strace` & Kernel Call Profiling

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.17)
- **Subtopics**:
  - `4.34.1` Attaching `strace` to running processes (`strace -p <PID> -f`): following child forks and threads.
  - `4.34.2` Syscall timing analysis: `strace -T` measuring elapsed time spent inside individual kernel system calls.
  - `4.34.3` Syscall aggregation: `strace -c` producing summary tables of calls, errors, and percentage time spent.
  - `4.34.4` The performance overhead of ptrace: why `strace` slows target processes by 10x and must be used with caution in production.
- **Key Failure Modes & Edge Cases**: Running `strace` on high-traffic production databases, causing severe performance degradation due to ptrace breakpoint traps.
- **Verification & Mastery Check**: Diagnose an unfamiliar hanging process using `strace -p <PID>` and identify the blocking system call.
- **Project Application**: SysTrace: Core debugging foundation.', '{"solution.py": "# Phase 4 // Lesson 4.34: Dynamic Tracing with `strace` & Kernel Call Profiling\n\ndef solve():\n    \"\"\"\n    Verification: Diagnose an unfamiliar hanging process using `strace -p <PID>` and identify the blocking system call\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.34", "subtopics_count": 4, "verification_criteria": "Diagnose an unfamiliar hanging process using `strace -p <PID>` and identify the blocking system call.", "subtopics": ["4.34.1 Attaching `strace` to running processes (`strace -p <PID> -f`): following child forks and threads.", "4.34.2 Syscall timing analysis: `strace -T` measuring elapsed time spent inside individual kernel system calls.", "4.34.3 Syscall aggregation: `strace -c` producing summary tables of calls, errors, and percentage time spent.", "4.34.4 The performance overhead of ptrace: why `strace` slows target processes by 10x and must be used with caution in production."]}'::jsonb, '["Explain how this implementation prevents: Running `strace` on high-traffic production databases, causing severe performance degradation due to ptrace breakpoint t", "How does Dynamic Tracing with `strace` & Kernel Call Profiling scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-35', 'phase-04-lesson-35-linux-namespaces-process-mount-uts-isolat', 'module-6', 35, 'Lesson 6.35: Linux Namespaces: Process, Mount, & UTS Isolation', 'Prerequisites: Phase 0 (Lesson 0.2)', 'Prerequisites: Phase 0 (Lesson 0.2) | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 1750.0, '# Lesson 4.35: Linux Namespaces: Process, Mount, & UTS Isolation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.2)
- **Subtopics**:
  - `4.35.1` Demystifying containers: containers are standard Linux processes isolated via kernel namespaces and cgroups.
  - `4.35.2` PID Namespace: virtualizing process IDs; process becoming PID 1 inside container while having standard PID on host.
  - `4.35.3` Mount Namespace (`mnt`): isolated filesystem hierarchy view; `pivot_root` and `chroot` mechanics.
  - `4.35.4` UTS Namespace: isolating hostnames and domain names without affecting host system.
- **Key Failure Modes & Edge Cases**: Running applications in containers with broken PID 1 setups, leading to un-reaped zombie processes and signal handling failures.
- **Verification & Mastery Check**: Create an isolated process manually using `unshare --pid --mount --uts --fork /bin/bash` and observe PID 1 mapping.
- **Project Application**: Core container architecture.', '{"solution.py": "# Phase 4 // Lesson 4.35: Linux Namespaces: Process, Mount, & UTS Isolation\n\ndef solve():\n    \"\"\"\n    Verification: Create an isolated process manually using `unshare --pid --mount --uts --fork /bin/bash` and observe\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.35", "subtopics_count": 4, "verification_criteria": "Create an isolated process manually using `unshare --pid --mount --uts --fork /bin/bash` and observe PID 1 mapping.", "subtopics": ["4.35.1 Demystifying containers: containers are standard Linux processes isolated via kernel namespaces and cgroups.", "4.35.2 PID Namespace: virtualizing process IDs; process becoming PID 1 inside container while having standard PID on host.", "4.35.3 Mount Namespace (`mnt`): isolated filesystem hierarchy view; `pivot_root` and `chroot` mechanics.", "4.35.4 UTS Namespace: isolating hostnames and domain names without affecting host system."]}'::jsonb, '["Explain how this implementation prevents: Running applications in containers with broken PID 1 setups, leading to un-reaped zombie processes and signal handling f", "How does Linux Namespaces: Process, Mount, & UTS Isolation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
