INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-7-16', 'phase-07-lesson-16-kubernetes-core-workloads-pods-deployment', 'module-10', 16, 'Lesson 10.16: Kubernetes Core Workloads: Pods, Deployments & ReplicaSets', 'Prerequisites: Lesson 7.15', 'Prerequisites: Lesson 7.15 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 800.0, '# Lesson 7.16: Kubernetes Core Workloads: Pods, Deployments & ReplicaSets

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.15
- **Subtopics**:
  - `7.16.1` Pod lifecycle and phases: Pending, Running, Succeeded, Failed, Unknown, and container statuses
  - `7.16.2` Init containers vs application containers vs ephemeral debug containers: execution ordering and shared volumes
  - `7.16.3` Deployment reconciliation mechanics: ReplicaSet management, maxSurge, and maxUnavailable rolling update arithmetic
  - `7.16.4` Pod termination lifecycle: SIGTERM signal propagation, terminationGracePeriodSeconds, preStop hooks, and endpoint deregistration
  - `7.16.5` Liveness, Readiness, and Startup probes: failure thresholds, probe types (HTTP, Exec, gRPC), and restart loops
  - `7.16.6` Resource management: requests (scheduling baseline) vs limits (cgroup ceiling), CPU throttling, and Memory OOM-Kills (Exit Code 137)
- **Key Failure Modes & Edge Cases**: Readiness probe misconfigured as liveness probe triggering infinite restart cascades when services face temporary overload.
- **Verification & Mastery Check**: Deploy a zero-downtime rolling update deployment with calibrated preStop hooks and readiness probes passing load testing without dropped packets.
- **Project Application**: InfraBlueprint: Zero-downtime microservice workload manifests.', '{"solution.py": "# Phase 7 // Lesson 7.16: Kubernetes Core Workloads: Pods, Deployments & ReplicaSets\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a zero-downtime rolling update deployment with calibrated preStop hooks and readiness probes \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.16", "subtopics_count": 6, "verification_criteria": "Deploy a zero-downtime rolling update deployment with calibrated preStop hooks and readiness probes passing load testing without dropped packets.", "subtopics": ["7.16.1 Pod lifecycle and phases: Pending, Running, Succeeded, Failed, Unknown, and container statuses", "7.16.2 Init containers vs application containers vs ephemeral debug containers: execution ordering and shared volumes", "7.16.3 Deployment reconciliation mechanics: ReplicaSet management, maxSurge, and maxUnavailable rolling update arithmetic", "7.16.4 Pod termination lifecycle: SIGTERM signal propagation, terminationGracePeriodSeconds, preStop hooks, and endpoint deregistration", "7.16.5 Liveness, Readiness, and Startup probes: failure thresholds, probe types (HTTP, Exec, gRPC), and restart loops", "7.16.6 Resource management: requests (scheduling baseline) vs limits (cgroup ceiling), CPU throttling, and Memory OOM-Kills (Exit Code 137)"]}'::jsonb, '["Explain how this implementation prevents: Readiness probe misconfigured as liveness probe triggering infinite restart cascades when services face temporary overlo", "How does Kubernetes Core Workloads: Pods, Deployments & ReplicaSets scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-17', 'phase-07-lesson-17-kubernetes-advanced-workloads-statefulset', 'module-10', 17, 'Lesson 10.17: Kubernetes Advanced Workloads: StatefulSets, DaemonSets & Jobs', 'Prerequisites: Lesson 7.16', 'Prerequisites: Lesson 7.16 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 850.0, '# Lesson 7.17: Kubernetes Advanced Workloads: StatefulSets, DaemonSets & Jobs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.16
- **Subtopics**:
  - `7.17.1` StatefulSet architecture: stable unique network identities (`pod-0`, `pod-1`), persistent storage binding (volumeClaimTemplates)
  - `7.17.2` StatefulSet ordering guarantees: ordered deployment, sequential rolling updates, and parallel pod management policies
  - `7.17.3` Headless Services (`clusterIP: None`): direct DNS SRV record resolution to individual stateful pod IP addresses
  - `7.17.4` DaemonSet architecture: scheduling exactly one pod per eligible node, hostPort/hostNetwork usage, and node taints bypass
  - `7.17.5` Jobs and CronJobs: batch execution, completions, parallelism, backoffLimit, and dead-lock prevention with activeDeadlineSeconds
  - `7.17.6` Pod disruption budgets (PDB): minAvailable vs maxUnavailable protecting stateful services during node draining and upgrades
- **Key Failure Modes & Edge Cases**: Deleting a StatefulSet pod expecting storage cleanup; running database replicas without Pod Disruption Budgets during node pools upgrades.
- **Verification & Mastery Check**: Deploy a 3-node clustered Raft/etcd service as a StatefulSet with automated headless DNS discovery and persistent volume claims.
- **Project Application**: InfraBlueprint: Clustered stateful database deployment on Kubernetes.', '{"solution.py": "# Phase 7 // Lesson 7.17: Kubernetes Advanced Workloads: StatefulSets, DaemonSets & Jobs\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a 3-node clustered Raft/etcd service as a StatefulSet with automated headless DNS discovery a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.17", "subtopics_count": 6, "verification_criteria": "Deploy a 3-node clustered Raft/etcd service as a StatefulSet with automated headless DNS discovery and persistent volume claims.", "subtopics": ["7.17.1 StatefulSet architecture: stable unique network identities (`pod-0`, `pod-1`), persistent storage binding (volumeClaimTemplates)", "7.17.2 StatefulSet ordering guarantees: ordered deployment, sequential rolling updates, and parallel pod management policies", "7.17.3 Headless Services (`clusterIP: None`): direct DNS SRV record resolution to individual stateful pod IP addresses", "7.17.4 DaemonSet architecture: scheduling exactly one pod per eligible node, hostPort/hostNetwork usage, and node taints bypass", "7.17.5 Jobs and CronJobs: batch execution, completions, parallelism, backoffLimit, and dead-lock prevention with activeDeadlineSeconds", "7.17.6 Pod disruption budgets (PDB): minAvailable vs maxUnavailable protecting stateful services during node draining and upgrades"]}'::jsonb, '["Explain how this implementation prevents: Deleting a StatefulSet pod expecting storage cleanup; running database replicas without Pod Disruption Budgets during no", "How does Kubernetes Advanced Workloads: StatefulSets, DaemonSets & Jobs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-18', 'phase-07-lesson-18-kubernetes-networking-i-pod-to-pod-cni-cl', 'module-10', 18, 'Lesson 10.18: Kubernetes Networking I: Pod-to-Pod, CNI & ClusterIP', 'Prerequisites: Phase 0, Lesson 7.15', 'Prerequisites: Phase 0, Lesson 7.15 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 900.0, '# Lesson 7.18: Kubernetes Networking I: Pod-to-Pod, CNI & ClusterIP

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 7.15
- **Subtopics**:
  - `7.18.1` The Kubernetes networking model: every pod gets its own unique, routable IP address without NAT across nodes
  - `7.18.2` Container Network Interface (CNI): plugin architecture, Cilium (eBPF-based) vs Calico (BGP/iptables) vs GCP VPC-Native CNI
  - `7.18.3` Pod network namespaces and veth pairs: routing packets from container namespace into host bridge and physical interfaces
  - `7.18.4` Service abstraction mechanics: ClusterIP allocation, virtual IP ranges, and why ClusterIPs don''t respond to ICMP ping
  - `7.18.5` kube-proxy internals: iptables mode (linear chain traversal overhead) vs IPVS mode (hash tables) vs eBPF (direct socket routing)
  - `7.18.6` CoreDNS architecture: in-cluster DNS resolution, search paths (`ndots: 5` latency pitfall), and DNS caching
- **Key Failure Modes & Edge Cases**: Massive DNS latency amplification caused by `ndots: 5` appending search domains to external queries; iptables table exhaustion.
- **Verification & Mastery Check**: Inspect container veth pairs and host routing tables using `ip route` and `iptables-save`; trace a packet between pods across nodes.
- **Project Application**: InfraBlueprint: Cilium eBPF-powered Kubernetes network topology.', '{"solution.py": "# Phase 7 // Lesson 7.18: Kubernetes Networking I: Pod-to-Pod, CNI & ClusterIP\n\ndef solve():\n    \"\"\"\n    Verification: Inspect container veth pairs and host routing tables using `ip route` and `iptables-save`; trace a p\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.18", "subtopics_count": 6, "verification_criteria": "Inspect container veth pairs and host routing tables using `ip route` and `iptables-save`; trace a packet between pods across nodes.", "subtopics": ["7.18.1 The Kubernetes networking model: every pod gets its own unique, routable IP address without NAT across nodes", "7.18.2 Container Network Interface (CNI): plugin architecture, Cilium (eBPF-based) vs Calico (BGP/iptables) vs GCP VPC-Native CNI", "7.18.3 Pod network namespaces and veth pairs: routing packets from container namespace into host bridge and physical interfaces", "7.18.4 Service abstraction mechanics: ClusterIP allocation, virtual IP ranges, and why ClusterIPs don''t respond to ICMP ping", "7.18.5 kube-proxy internals: iptables mode (linear chain traversal overhead) vs IPVS mode (hash tables) vs eBPF (direct socket routing)", "7.18.6 CoreDNS architecture: in-cluster DNS resolution, search paths (`ndots: 5` latency pitfall), and DNS caching"]}'::jsonb, '["Explain how this implementation prevents: Massive DNS latency amplification caused by `ndots: 5` appending search domains to external queries; iptables table exha", "How does Kubernetes Networking I: Pod-to-Pod, CNI & ClusterIP scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-19', 'phase-07-lesson-19-kubernetes-networking-ii-nodeport-loadbal', 'module-10', 19, 'Lesson 10.19: Kubernetes Networking II: NodePort, LoadBalancer, Ingress & Gateway API', 'Prerequisites: Lesson 7.18', 'Prerequisites: Lesson 7.18 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 950.0, '# Lesson 7.19: Kubernetes Networking II: NodePort, LoadBalancer, Ingress & Gateway API

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.18
- **Subtopics**:
  - `7.19.1` External traffic entrypoints: NodePort mechanics, high-port allocations (30000-32767), and `externalTrafficPolicy: Local` vs `Cluster`
  - `7.19.2` LoadBalancer services: cloud provider integration, cloud load balancer provisioning, and SNAT IP preservation
  - `7.19.3` Ingress controllers: NGINX Ingress vs Envoy-based Ingress, TLS termination, path-based and host-based routing rules
  - `7.19.4` Cert-Manager integration: automated ACME Let''s Encrypt TLS certificate provisioning and renewal via DNS-01/HTTP-01 challenges
  - `7.19.5` The Gateway API evolution: GatewayClass, Gateway, and HTTPRoute decoupling infrastructure provisioning from application routing
  - `7.19.6` Traffic shaping with Gateway API: header matching, traffic splitting (canary releases), and cross-namespace routing permissions
- **Key Failure Modes & Edge Cases**: `externalTrafficPolicy: Cluster` hiding client source IP addresses behind SNAT; Ingress controller regex routing collisions.
- **Verification & Mastery Check**: Configure a Gateway API setup with HTTPRoute performing 90/10 canary traffic splitting and automated Let''s Encrypt TLS termination.
- **Project Application**: InfraBlueprint: Gateway API ingress and canary routing infrastructure.', '{"solution.py": "# Phase 7 // Lesson 7.19: Kubernetes Networking II: NodePort, LoadBalancer, Ingress & Gateway API\n\ndef solve():\n    \"\"\"\n    Verification: Configure a Gateway API setup with HTTPRoute performing 90/10 canary traffic splitting and automated\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.19", "subtopics_count": 6, "verification_criteria": "Configure a Gateway API setup with HTTPRoute performing 90/10 canary traffic splitting and automated Let''s Encrypt TLS termination.", "subtopics": ["7.19.1 External traffic entrypoints: NodePort mechanics, high-port allocations (30000-32767), and `externalTrafficPolicy: Local` vs `Cluster`", "7.19.2 LoadBalancer services: cloud provider integration, cloud load balancer provisioning, and SNAT IP preservation", "7.19.3 Ingress controllers: NGINX Ingress vs Envoy-based Ingress, TLS termination, path-based and host-based routing rules", "7.19.4 Cert-Manager integration: automated ACME Let''s Encrypt TLS certificate provisioning and renewal via DNS-01/HTTP-01 challenges", "7.19.5 The Gateway API evolution: GatewayClass, Gateway, and HTTPRoute decoupling infrastructure provisioning from application routing", "7.19.6 Traffic shaping with Gateway API: header matching, traffic splitting (canary releases), and cross-namespace routing permissions"]}'::jsonb, '["Explain how this implementation prevents: `externalTrafficPolicy: Cluster` hiding client source IP addresses behind SNAT; Ingress controller regex routing collisi", "How does Kubernetes Networking II: NodePort, LoadBalancer, Ingress & Gateway API scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-20', 'phase-07-lesson-20-kubernetes-storage-csi-storageclasses-pvc', 'module-10', 20, 'Lesson 10.20: Kubernetes Storage: CSI, StorageClasses, PVCs & Dynamic Provisioning', 'Prerequisites: Lesson 7.17', 'Prerequisites: Lesson 7.17 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1000.0, '# Lesson 7.20: Kubernetes Storage: CSI, StorageClasses, PVCs & Dynamic Provisioning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.17
- **Subtopics**:
  - `7.20.1` Container Storage Interface (CSI): plugin architecture, node-driver-registrar, csi-provisioner, and csi-attacher
  - `7.20.2` PersistentVolume (PV) vs PersistentVolumeClaim (PVC): declarative storage provisioning abstraction layer
  - `7.20.3` StorageClass mechanics: provisioners (e.g. `pd.csi.storage.gke.io`), volumeBindingMode (`WaitForFirstConsumer`), and reclaim policies
  - `7.20.4` Access modes: ReadWriteOnce (RWO), ReadOnlyMany (ROX), ReadWriteMany (RWX), and ReadWriteOncePod (RWOP)
  - `7.20.5` Volume volume lifecycle: provisioning, binding, attaching (to node), and mounting (into container mount namespace)
  - `7.20.6` Volume snapshots and resizing: CSISnapshot, online filesystem expansion, and backup automation
- **Key Failure Modes & Edge Cases**: Storage provisioned in an Availability Zone different from scheduled pod due to `volumeBindingMode: Immediate`.
- **Verification & Mastery Check**: Provision dynamic GCP Persistent Disk storage via CSI with `WaitForFirstConsumer` and perform an online volume expansion without pod restart.
- **Project Application**: InfraBlueprint: CSI dynamic storage infrastructure with automated snapshots.', '{"solution.py": "# Phase 7 // Lesson 7.20: Kubernetes Storage: CSI, StorageClasses, PVCs & Dynamic Provisioning\n\ndef solve():\n    \"\"\"\n    Verification: Provision dynamic GCP Persistent Disk storage via CSI with `WaitForFirstConsumer` and perform an onl\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.20", "subtopics_count": 6, "verification_criteria": "Provision dynamic GCP Persistent Disk storage via CSI with `WaitForFirstConsumer` and perform an online volume expansion without pod restart.", "subtopics": ["7.20.1 Container Storage Interface (CSI): plugin architecture, node-driver-registrar, csi-provisioner, and csi-attacher", "7.20.2 PersistentVolume (PV) vs PersistentVolumeClaim (PVC): declarative storage provisioning abstraction layer", "7.20.3 StorageClass mechanics: provisioners (e.g. `pd.csi.storage.gke.io`), volumeBindingMode (`WaitForFirstConsumer`), and reclaim policies", "7.20.4 Access modes: ReadWriteOnce (RWO), ReadOnlyMany (ROX), ReadWriteMany (RWX), and ReadWriteOncePod (RWOP)", "7.20.5 Volume volume lifecycle: provisioning, binding, attaching (to node), and mounting (into container mount namespace)", "7.20.6 Volume snapshots and resizing: CSISnapshot, online filesystem expansion, and backup automation"]}'::jsonb, '["Explain how this implementation prevents: Storage provisioned in an Availability Zone different from scheduled pod due to `volumeBindingMode: Immediate`.", "How does Kubernetes Storage: CSI, StorageClasses, PVCs & Dynamic Provisioning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-21', 'phase-07-lesson-21-kubernetes-configuration-configmaps-secre', 'module-10', 21, 'Lesson 10.21: Kubernetes Configuration: ConfigMaps, Secrets, External Secrets & SOPS', 'Prerequisites: Phase 5, Lesson 7.16', 'Prerequisites: Phase 5, Lesson 7.16 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 1050.0, '# Lesson 7.21: Kubernetes Configuration: ConfigMaps, Secrets, External Secrets & SOPS

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Lesson 7.16
- **Subtopics**:
  - `7.21.1` ConfigMap architecture: environment variable injection vs mounted volume directories, subPath pitfalls, and atomic updates
  - `7.21.2` Kubernetes Secrets: base64 encoding limitations, encryption at rest in etcd using KMS envelope encryption
  - `7.21.3` External Secrets Operator (ESO): synchronizing secrets securely from Google Cloud Secret Manager / HashiCorp Vault into Kubernetes
  - `7.21.4` GitOps secrets management: Mozilla SOPS, age encryption, and SealedSecrets for safe repository storage
  - `7.21.5` Secret rotation workflows: dynamic pod reloads via Stakater Reloader vs in-memory application watcher loops
  - `7.21.6` Preventing secrets leakage: restricting RBAC `secrets` permissions and disabling secret environment variable reflection in crash logs
- **Key Failure Modes & Edge Cases**: Treating raw Kubernetes base64 Secrets as secure; subPath volume mounts failing to receive live ConfigMap updates.
- **Verification & Mastery Check**: Implement External Secrets Operator synchronizing credentials from GCP Secret Manager with automated pod rolling updates on rotation.
- **Project Application**: InfraBlueprint: Production secret management pipeline with ESO.', '{"solution.py": "# Phase 7 // Lesson 7.21: Kubernetes Configuration: ConfigMaps, Secrets, External Secrets & SOPS\n\ndef solve():\n    \"\"\"\n    Verification: Implement External Secrets Operator synchronizing credentials from GCP Secret Manager with automated\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.21", "subtopics_count": 6, "verification_criteria": "Implement External Secrets Operator synchronizing credentials from GCP Secret Manager with automated pod rolling updates on rotation.", "subtopics": ["7.21.1 ConfigMap architecture: environment variable injection vs mounted volume directories, subPath pitfalls, and atomic updates", "7.21.2 Kubernetes Secrets: base64 encoding limitations, encryption at rest in etcd using KMS envelope encryption", "7.21.3 External Secrets Operator (ESO): synchronizing secrets securely from Google Cloud Secret Manager / HashiCorp Vault into Kubernetes", "7.21.4 GitOps secrets management: Mozilla SOPS, age encryption, and SealedSecrets for safe repository storage", "7.21.5 Secret rotation workflows: dynamic pod reloads via Stakater Reloader vs in-memory application watcher loops", "7.21.6 Preventing secrets leakage: restricting RBAC `secrets` permissions and disabling secret environment variable reflection in crash logs"]}'::jsonb, '["Explain how this implementation prevents: Treating raw Kubernetes base64 Secrets as secure; subPath volume mounts failing to receive live ConfigMap updates.", "How does Kubernetes Configuration: ConfigMaps, Secrets, External Secrets & SOPS scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-22', 'phase-07-lesson-22-kubernetes-security-rbac-pod-security-sta', 'module-10', 22, 'Lesson 10.22: Kubernetes Security: RBAC, Pod Security Standards & NetworkPolicies', 'Prerequisites: Phase 5, Lesson 7.15', 'Prerequisites: Phase 5, Lesson 7.15 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 1100.0, '# Lesson 7.22: Kubernetes Security: RBAC, Pod Security Standards & NetworkPolicies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Lesson 7.15
- **Subtopics**:
  - `7.22.1` Role-Based Access Control (RBAC): Roles, ClusterRoles, RoleBindings, and ClusterRoleBindings principle of least privilege
  - `7.22.2` ServiceAccounts: automountServiceAccountToken dangers, projected service account tokens, and short-lived credentials
  - `7.22.3` Pod Security Standards (PSS): Privileged, Baseline, and Restricted admission levels enforced via namespace labels
  - `7.22.4` Hardening security contexts: `runAsNonRoot: true`, `readOnlyRootFilesystem: true`, `allowPrivilegeEscalation: false`
  - `7.22.5` Kubernetes NetworkPolicies: default-deny ingress and egress rules, podSelector, and namespaceSelector enforcement
  - `7.22.6` Runtime container auditing: Falco eBPF security monitoring detecting anomalous shell spawning and root file modifications
- **Key Failure Modes & Edge Cases**: Wildcard `*` verbs in ClusterRoles granting cluster-admin privileges; un-isolated namespaces allowing cross-tenant pod network tapping.
- **Verification & Mastery Check**: Construct a hardened namespace with Restricted PSS, non-root security contexts, and default-deny NetworkPolicies blocking unauthorized egress.
- **Project Application**: InfraBlueprint: Zero-trust Kubernetes security hardening manifests.', '{"solution.py": "# Phase 7 // Lesson 7.22: Kubernetes Security: RBAC, Pod Security Standards & NetworkPolicies\n\ndef solve():\n    \"\"\"\n    Verification: Construct a hardened namespace with Restricted PSS, non-root security contexts, and default-deny Net\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.22", "subtopics_count": 6, "verification_criteria": "Construct a hardened namespace with Restricted PSS, non-root security contexts, and default-deny NetworkPolicies blocking unauthorized egress.", "subtopics": ["7.22.1 Role-Based Access Control (RBAC): Roles, ClusterRoles, RoleBindings, and ClusterRoleBindings principle of least privilege", "7.22.2 ServiceAccounts: automountServiceAccountToken dangers, projected service account tokens, and short-lived credentials", "7.22.3 Pod Security Standards (PSS): Privileged, Baseline, and Restricted admission levels enforced via namespace labels", "7.22.4 Hardening security contexts: `runAsNonRoot: true`, `readOnlyRootFilesystem: true`, `allowPrivilegeEscalation: false`", "7.22.5 Kubernetes NetworkPolicies: default-deny ingress and egress rules, podSelector, and namespaceSelector enforcement", "7.22.6 Runtime container auditing: Falco eBPF security monitoring detecting anomalous shell spawning and root file modifications"]}'::jsonb, '["Explain how this implementation prevents: Wildcard `*` verbs in ClusterRoles granting cluster-admin privileges; un-isolated namespaces allowing cross-tenant pod n", "How does Kubernetes Security: RBAC, Pod Security Standards & NetworkPolicies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-23', 'phase-07-lesson-23-kubernetes-autoscaling-hpa-vpa-cluster-au', 'module-10', 23, 'Lesson 10.23: Kubernetes Autoscaling: HPA, VPA & Cluster Autoscaler / Karpenter', 'Prerequisites: Lesson 7.16, Lesson 7.18', 'Prerequisites: Lesson 7.16, Lesson 7.18 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1150.0, '# Lesson 7.23: Kubernetes Autoscaling: HPA, VPA & Cluster Autoscaler / Karpenter

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.16, Lesson 7.18
- **Subtopics**:
  - `7.23.1` Horizontal Pod Autoscaler (HPA v2): scaling based on CPU/memory utilization and custom metrics (Prometheus metrics adapter)
  - `7.23.2` HPA scaling algorithm: $\text{desiredReplicas} = \lceil \text{currentReplicas} \times (\text{currentMetricValue} / \text{desiredMetricValue}) \rceil$
  - `7.23.3` HPA stabilization windows and rate-limiting scaling behavior to prevent rapid flapping (thrashing)
  - `7.23.4` Vertical Pod Autoscaler (VPA): Recommender, Updater, and Admission Controller automatically tuning CPU/memory requests
  - `7.23.5` Cluster Autoscaler (CA): scaling node groups based on pending unschedulable pods and underutilized node drain conditions
  - `7.23.6` Karpenter high-performance autoscaling: node-less direct EC2/GCE instance provisioning bypassing managed node groups for rapid scale-up
- **Key Failure Modes & Edge Cases**: HPA and VPA conflicting on the same resource metrics causing oscillating scale actions; scaling lag dropping traffic during sharp traffic spikes.
- **Verification & Mastery Check**: Configure HPA scaling an API service based on real-time HTTP requests-per-second custom metrics from Prometheus; stress-test with k6.
- **Project Application**: InfraBlueprint: Metric-driven horizontal autoscaling engine.', '{"solution.py": "# Phase 7 // Lesson 7.23: Kubernetes Autoscaling: HPA, VPA & Cluster Autoscaler / Karpenter\n\ndef solve():\n    \"\"\"\n    Verification: Configure HPA scaling an API service based on real-time HTTP requests-per-second custom metrics from\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.23", "subtopics_count": 6, "verification_criteria": "Configure HPA scaling an API service based on real-time HTTP requests-per-second custom metrics from Prometheus; stress-test with k6.", "subtopics": ["7.23.1 Horizontal Pod Autoscaler (HPA v2): scaling based on CPU/memory utilization and custom metrics (Prometheus metrics adapter)", "7.23.2 HPA scaling algorithm: $\\text{desiredReplicas} = \\lceil \\text{currentReplicas} \\times (\\text{currentMetricValue} / \\text{desiredMetricValue}) \\rceil$", "7.23.3 HPA stabilization windows and rate-limiting scaling behavior to prevent rapid flapping (thrashing)", "7.23.4 Vertical Pod Autoscaler (VPA): Recommender, Updater, and Admission Controller automatically tuning CPU/memory requests", "7.23.5 Cluster Autoscaler (CA): scaling node groups based on pending unschedulable pods and underutilized node drain conditions", "7.23.6 Karpenter high-performance autoscaling: node-less direct EC2/GCE instance provisioning bypassing managed node groups for rapid scale-up"]}'::jsonb, '["Explain how this implementation prevents: HPA and VPA conflicting on the same resource metrics causing oscillating scale actions; scaling lag dropping traffic dur", "How does Kubernetes Autoscaling: HPA, VPA & Cluster Autoscaler / Karpenter scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-24', 'phase-07-lesson-24-kubernetes-extensibility-custom-resource-', 'module-10', 24, 'Lesson 10.24: Kubernetes Extensibility: Custom Resource Definitions (CRDs) & Operator SDK', 'Prerequisites: Phase 1, Lesson 7.15', 'Prerequisites: Phase 1, Lesson 7.15 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 1200.0, '# Lesson 7.24: Kubernetes Extensibility: Custom Resource Definitions (CRDs) & Operator SDK

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Lesson 7.15
- **Subtopics**:
  - `7.24.1` Custom Resource Definitions (CRD): extending the Kubernetes API with OpenAPI v3 validation schemas and subresources (`/status`, `/scale`)
  - `7.24.2` The Operator Pattern: encoding human operational domain knowledge into software automation loops
  - `7.24.3` Controller runtime architecture: Informers, SharedIndexInformer, Lister caches, work queues, and reconciliation loops
  - `7.24.4` Level-triggered vs Edge-triggered control loops: why reconciliation must be idempotent and resilient to missed events
  - `7.24.5` Building an Operator with Kubebuilder / Operator SDK: scaffolding controllers, generating RBAC manifests, and manager lifecycle
  - `7.24.6` Validating and Mutating Admission Webhooks: intercepting, mutating, and rejecting custom resource submissions
- **Key Failure Modes & Edge Cases**: Writing non-idempotent reconciliation loops causing infinite update loops against the Kubernetes API server.
- **Verification & Mastery Check**: Build a production Kubernetes Operator in Go that provisions and monitors Postgres database instances on-demand via custom resources.
- **Project Application**: InfraBlueprint: Custom Database Provisioning Operator.', '{"solution.py": "# Phase 7 // Lesson 7.24: Kubernetes Extensibility: Custom Resource Definitions (CRDs) & Operator SDK\n\ndef solve():\n    \"\"\"\n    Verification: Build a production Kubernetes Operator in Go that provisions and monitors Postgres database instance\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.24", "subtopics_count": 6, "verification_criteria": "Build a production Kubernetes Operator in Go that provisions and monitors Postgres database instances on-demand via custom resources.", "subtopics": ["7.24.1 Custom Resource Definitions (CRD): extending the Kubernetes API with OpenAPI v3 validation schemas and subresources (`/status`, `/scale`)", "7.24.2 The Operator Pattern: encoding human operational domain knowledge into software automation loops", "7.24.3 Controller runtime architecture: Informers, SharedIndexInformer, Lister caches, work queues, and reconciliation loops", "7.24.4 Level-triggered vs Edge-triggered control loops: why reconciliation must be idempotent and resilient to missed events", "7.24.5 Building an Operator with Kubebuilder / Operator SDK: scaffolding controllers, generating RBAC manifests, and manager lifecycle", "7.24.6 Validating and Mutating Admission Webhooks: intercepting, mutating, and rejecting custom resource submissions"]}'::jsonb, '["Explain how this implementation prevents: Writing non-idempotent reconciliation loops causing infinite update loops against the Kubernetes API server.", "How does Kubernetes Extensibility: Custom Resource Definitions (CRDs) & Operator SDK scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-25', 'phase-07-lesson-25-helm-packaging-kustomize-overlays-configu', 'module-10', 25, 'Lesson 10.25: Helm Packaging, Kustomize Overlays & Configuration Management', 'Prerequisites: Lesson 7.16, Lesson 7.21', 'Prerequisites: Lesson 7.16, Lesson 7.21 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 1250.0, '# Lesson 7.25: Helm Packaging, Kustomize Overlays & Configuration Management

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.16, Lesson 7.21
- **Subtopics**:
  - `7.25.1` Helm architecture: chart structure, values.yaml, Go template functions, built-in objects, and release management
  - `7.25.2` Helm lifecycle hooks: pre-install, post-install, pre-upgrade hooks for database migrations and schema checks
  - `7.25.3` Kustomize declarative configuration: template-free customization using base and environment overlays (dev, staging, prod)
  - `7.25.4` Kustomize transformations: patches, configMapGenerators, secretGenerators, and image tag substitutions
  - `7.25.5` Helm vs Kustomize comparison: parameterized packages vs declarative overlay composition, and combining Helm with Kustomize
  - `7.25.6` Validating manifests: `kubeconform`, `conftest` (Rego policies), and static linting in CI before cluster deployment
- **Key Failure Modes & Edge Cases**: Template expansion rendering invalid YAML; unpinned chart dependencies pulling breaking changes into production releases.
- **Verification & Mastery Check**: Build a base Kustomize architecture with staging/production overlays patching replica counts, resources, and environment secrets.
- **Project Application**: InfraBlueprint: Enterprise Kustomize configuration repository.', '{"solution.py": "# Phase 7 // Lesson 7.25: Helm Packaging, Kustomize Overlays & Configuration Management\n\ndef solve():\n    \"\"\"\n    Verification: Build a base Kustomize architecture with staging/production overlays patching replica counts, resour\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.25", "subtopics_count": 6, "verification_criteria": "Build a base Kustomize architecture with staging/production overlays patching replica counts, resources, and environment secrets.", "subtopics": ["7.25.1 Helm architecture: chart structure, values.yaml, Go template functions, built-in objects, and release management", "7.25.2 Helm lifecycle hooks: pre-install, post-install, pre-upgrade hooks for database migrations and schema checks", "7.25.3 Kustomize declarative configuration: template-free customization using base and environment overlays (dev, staging, prod)", "7.25.4 Kustomize transformations: patches, configMapGenerators, secretGenerators, and image tag substitutions", "7.25.5 Helm vs Kustomize comparison: parameterized packages vs declarative overlay composition, and combining Helm with Kustomize", "7.25.6 Validating manifests: `kubeconform`, `conftest` (Rego policies), and static linting in CI before cluster deployment"]}'::jsonb, '["Explain how this implementation prevents: Template expansion rendering invalid YAML; unpinned chart dependencies pulling breaking changes into production releases", "How does Helm Packaging, Kustomize Overlays & Configuration Management scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-26', 'phase-07-lesson-26-gitops-continuous-delivery-argocd-fluxcd-', 'module-10', 26, 'Lesson 10.26: GitOps Continuous Delivery: ArgoCD & FluxCD Engine', 'Prerequisites: Lesson 7.24, Lesson 7.25', 'Prerequisites: Lesson 7.24, Lesson 7.25 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1300.0, '# Lesson 7.26: GitOps Continuous Delivery: ArgoCD & FluxCD Engine

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.24, Lesson 7.25
- **Subtopics**:
  - `7.26.1` GitOps principles: declarative descriptions, version-controlled source of truth, automated pull-based state convergence
  - `7.26.2` Push-based CI/CD (Jenkins, GitLab CI) vs Pull-based GitOps (ArgoCD): eliminating long-lived cluster credentials in CI
  - `7.26.3` ArgoCD architecture: Application controller, API server, repository server, and custom resource definitions (Application, AppProject)
  - `7.26.4` Sync policies: automated sync, self-healing, pruning unmanaged resources, and sync waves for ordered resource provisioning
  - `7.26.5` Managing multi-tenant clusters with App-of-Apps and ApplicationSet generators (Git directory, cluster, and matrix generators)
  - `7.26.6` Disaster recovery via GitOps: reconstructing an entire multi-node cluster from scratch exclusively from the Git repository
- **Key Failure Modes & Edge Cases**: Disabling automated pruning leading to orphaned, zombie resources lingering in clusters; Git commit loops from automated in-cluster updates.
- **Verification & Mastery Check**: Deploy a multi-environment microservice fleet using ArgoCD with sync waves, automated self-healing, and Slack deployment notifications.
- **Project Application**: InfraBlueprint: ArgoCD continuous delivery pipeline.', '{"solution.py": "# Phase 7 // Lesson 7.26: GitOps Continuous Delivery: ArgoCD & FluxCD Engine\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a multi-environment microservice fleet using ArgoCD with sync waves, automated self-healing, \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.26", "subtopics_count": 6, "verification_criteria": "Deploy a multi-environment microservice fleet using ArgoCD with sync waves, automated self-healing, and Slack deployment notifications.", "subtopics": ["7.26.1 GitOps principles: declarative descriptions, version-controlled source of truth, automated pull-based state convergence", "7.26.2 Push-based CI/CD (Jenkins, GitLab CI) vs Pull-based GitOps (ArgoCD): eliminating long-lived cluster credentials in CI", "7.26.3 ArgoCD architecture: Application controller, API server, repository server, and custom resource definitions (Application, AppProject)", "7.26.4 Sync policies: automated sync, self-healing, pruning unmanaged resources, and sync waves for ordered resource provisioning", "7.26.5 Managing multi-tenant clusters with App-of-Apps and ApplicationSet generators (Git directory, cluster, and matrix generators)", "7.26.6 Disaster recovery via GitOps: reconstructing an entire multi-node cluster from scratch exclusively from the Git repository"]}'::jsonb, '["Explain how this implementation prevents: Disabling automated pruning leading to orphaned, zombie resources lingering in clusters; Git commit loops from automated", "How does GitOps Continuous Delivery: ArgoCD & FluxCD Engine scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-27', 'phase-07-lesson-27-cloud-foundations-google-cloud-platform-g', 'module-10', 27, 'Lesson 10.27: Cloud Foundations: Google Cloud Platform (GCP) Resource Hierarchy & IAM', 'Prerequisites: Phase 5, Lesson 7.1', 'Prerequisites: Phase 5, Lesson 7.1 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 1350.0, '# Lesson 7.27: Cloud Foundations: Google Cloud Platform (GCP) Resource Hierarchy & IAM

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Lesson 7.1
- **Subtopics**:
  - `7.27.1` GCP Resource Hierarchy: Organization, Folders, Projects, and Resources; policy inheritance and overriding rules
  - `7.27.2` GCP Identity and Access Management (IAM): Principal, Roles (Primitive, Predefined, Custom), and Permissions ($service.resource.action)
  - `7.27.3` IAM Conditions: context-aware access based on date/time, destination IP, resource tags, and request attributes
  - `7.27.4` Service Accounts: user-managed vs default service accounts, service account keys security vulnerabilities, and keyless architectures
  - `7.27.5` Workload Identity Federation: mapping external identities (GitHub Actions, AWS) to GCP IAM without static credentials
  - `7.27.6` GKE Workload Identity: binding Kubernetes ServiceAccounts directly to GCP ServiceAccounts via annotations and OIDC
- **Key Failure Modes & Edge Cases**: Using default Compute Engine service accounts with broad Editor privileges; committing JSON service account keys to Git.
- **Verification & Mastery Check**: Configure keyless CI/CD deployments from GitHub Actions to GCP using Workload Identity Federation with restricted custom IAM roles.
- **Project Application**: InfraBlueprint: GCP enterprise resource hierarchy and keyless IAM architecture.', '{"solution.py": "# Phase 7 // Lesson 7.27: Cloud Foundations: Google Cloud Platform (GCP) Resource Hierarchy & IAM\n\ndef solve():\n    \"\"\"\n    Verification: Configure keyless CI/CD deployments from GitHub Actions to GCP using Workload Identity Federation wi\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.27", "subtopics_count": 6, "verification_criteria": "Configure keyless CI/CD deployments from GitHub Actions to GCP using Workload Identity Federation with restricted custom IAM roles.", "subtopics": ["7.27.1 GCP Resource Hierarchy: Organization, Folders, Projects, and Resources; policy inheritance and overriding rules", "7.27.2 GCP Identity and Access Management (IAM): Principal, Roles (Primitive, Predefined, Custom), and Permissions ($service.resource.action)", "7.27.3 IAM Conditions: context-aware access based on date/time, destination IP, resource tags, and request attributes", "7.27.4 Service Accounts: user-managed vs default service accounts, service account keys security vulnerabilities, and keyless architectures", "7.27.5 Workload Identity Federation: mapping external identities (GitHub Actions, AWS) to GCP IAM without static credentials", "7.27.6 GKE Workload Identity: binding Kubernetes ServiceAccounts directly to GCP ServiceAccounts via annotations and OIDC"]}'::jsonb, '["Explain how this implementation prevents: Using default Compute Engine service accounts with broad Editor privileges; committing JSON service account keys to Git.", "How does Cloud Foundations: Google Cloud Platform (GCP) Resource Hierarchy & IAM scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-28', 'phase-07-lesson-28-gcp-networking-vpcs-subnets-firewalls-clo', 'module-10', 28, 'Lesson 10.28: GCP Networking: VPCs, Subnets, Firewalls & Cloud NAT', 'Prerequisites: Phase 0, Lesson 7.27', 'Prerequisites: Phase 0, Lesson 7.27 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 1400.0, '# Lesson 7.28: GCP Networking: VPCs, Subnets, Firewalls & Cloud NAT

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 7.27
- **Subtopics**:
  - `7.28.1` GCP Virtual Private Cloud (VPC) architecture: global VPCs, regional subnets, and custom-mode vs auto-mode VPC networks
  - `7.28.2` VPC Peering vs Cloud VPN vs Dedicated Interconnect: latency, bandwidth, and transitive routing limitations
  - `7.28.3` VPC Firewall Rules: ingress/egress policies, target tags, service account tags, and priority ordering
  - `7.28.4` Private Google Access and Private Service Connect: accessing GCP APIs and managed databases without public IP addresses
  - `7.28.5` Cloud NAT: outbound internet connectivity for private GKE nodes and VMs without exposing ingress public IPs
  - `7.28.6` Shared VPC architecture: separating central network host projects from application service projects in enterprise setups
- **Key Failure Modes & Edge Cases**: Asymmetric routing drops; creating overlapping CIDR blocks preventing future VPC peering or hybrid interconnects.
- **Verification & Mastery Check**: Construct a multi-region custom-mode VPC with private subnets, Cloud NAT gateways, and Private Google Access routes.
- **Project Application**: InfraBlueprint: Multi-region VPC and network topology.', '{"solution.py": "# Phase 7 // Lesson 7.28: GCP Networking: VPCs, Subnets, Firewalls & Cloud NAT\n\ndef solve():\n    \"\"\"\n    Verification: Construct a multi-region custom-mode VPC with private subnets, Cloud NAT gateways, and Private Googl\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.28", "subtopics_count": 6, "verification_criteria": "Construct a multi-region custom-mode VPC with private subnets, Cloud NAT gateways, and Private Google Access routes.", "subtopics": ["7.28.1 GCP Virtual Private Cloud (VPC) architecture: global VPCs, regional subnets, and custom-mode vs auto-mode VPC networks", "7.28.2 VPC Peering vs Cloud VPN vs Dedicated Interconnect: latency, bandwidth, and transitive routing limitations", "7.28.3 VPC Firewall Rules: ingress/egress policies, target tags, service account tags, and priority ordering", "7.28.4 Private Google Access and Private Service Connect: accessing GCP APIs and managed databases without public IP addresses", "7.28.5 Cloud NAT: outbound internet connectivity for private GKE nodes and VMs without exposing ingress public IPs", "7.28.6 Shared VPC architecture: separating central network host projects from application service projects in enterprise setups"]}'::jsonb, '["Explain how this implementation prevents: Asymmetric routing drops; creating overlapping CIDR blocks preventing future VPC peering or hybrid interconnects.", "How does GCP Networking: VPCs, Subnets, Firewalls & Cloud NAT scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-29', 'phase-07-lesson-29-gcp-compute-managed-kubernetes-gke-enterp', 'module-10', 29, 'Lesson 10.29: GCP Compute & Managed Kubernetes: GKE Enterprise & Cloud Run', 'Prerequisites: Lesson 7.22, Lesson 7.28', 'Prerequisites: Lesson 7.22, Lesson 7.28 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1450.0, '# Lesson 7.29: GCP Compute & Managed Kubernetes: GKE Enterprise & Cloud Run

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.22, Lesson 7.28
- **Subtopics**:
  - `7.29.1` Google Kubernetes Engine (GKE) architecture: GKE Standard vs GKE Autopilot (fully managed nodes and control plane)
  - `7.29.2` VPC-Native GKE Clusters: alias IP allocations, direct VPC routability, and eliminating overlay network overhead
  - `7.29.3` Private GKE Clusters: private control plane endpoints, authorized networks, and private worker nodes
  - `7.29.4` Cloud Run internals: serverless containers, scale-to-zero, request concurrency limits, and Knative architecture
  - `7.29.5` Comparing GKE vs Cloud Run: operational overhead, stateful workload support, cold starts, and network connectivity
  - `7.29.6` Cost optimization: preemptible VMs / Spot instances, committed use discounts (CUD), and node auto-provisioning
- **Key Failure Modes & Edge Cases**: Exposing GKE control plane endpoint to 0.0.0.0/0; over-provisioning container resources triggering massive cloud bills.
- **Verification & Mastery Check**: Provision a private, VPC-native GKE cluster with Autopilot security posture, network policies, and Cloud Operations logging.
- **Project Application**: InfraBlueprint: Production private GKE cluster infrastructure.', '{"solution.py": "# Phase 7 // Lesson 7.29: GCP Compute & Managed Kubernetes: GKE Enterprise & Cloud Run\n\ndef solve():\n    \"\"\"\n    Verification: Provision a private, VPC-native GKE cluster with Autopilot security posture, network policies, and C\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.29", "subtopics_count": 6, "verification_criteria": "Provision a private, VPC-native GKE cluster with Autopilot security posture, network policies, and Cloud Operations logging.", "subtopics": ["7.29.1 Google Kubernetes Engine (GKE) architecture: GKE Standard vs GKE Autopilot (fully managed nodes and control plane)", "7.29.2 VPC-Native GKE Clusters: alias IP allocations, direct VPC routability, and eliminating overlay network overhead", "7.29.3 Private GKE Clusters: private control plane endpoints, authorized networks, and private worker nodes", "7.29.4 Cloud Run internals: serverless containers, scale-to-zero, request concurrency limits, and Knative architecture", "7.29.5 Comparing GKE vs Cloud Run: operational overhead, stateful workload support, cold starts, and network connectivity", "7.29.6 Cost optimization: preemptible VMs / Spot instances, committed use discounts (CUD), and node auto-provisioning"]}'::jsonb, '["Explain how this implementation prevents: Exposing GKE control plane endpoint to 0.0.0.0/0; over-provisioning container resources triggering massive cloud bills.", "How does GCP Compute & Managed Kubernetes: GKE Enterprise & Cloud Run scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-30', 'phase-07-lesson-30-infrastructure-as-code-iac-with-terraform', 'module-10', 30, 'Lesson 10.30: Infrastructure as Code (IaC) with Terraform: Core Mechanics & State', 'Prerequisites: Phase 1, Lesson 7.27', 'Prerequisites: Phase 1, Lesson 7.27 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 1500.0, '# Lesson 7.30: Infrastructure as Code (IaC) with Terraform: Core Mechanics & State

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Lesson 7.27
- **Subtopics**:
  - `7.30.1` IaC principles: declarative infrastructure, version control, idempotency, and automated provisioning pipelines
  - `7.30.2` Terraform engine architecture: Core vs Providers, schema generation, dependency graph resolution, and execution plans
  - `7.30.3` The Terraform State file: mapping real-world cloud resources to configuration, metadata, and state locking
  - `7.30.4` Remote State management: Google Cloud Storage (GCS) backend, object versioning, and state locking via GCS/DynamoDB
  - `7.30.5` State security: why state files contain plaintext secrets and must be encrypted with customer-managed KMS keys
  - `7.30.6` Terraform commands deep dive: init, plan, apply, destroy, import, state mv, and refreshing resources
- **Key Failure Modes & Edge Cases**: Concurrent team applies corrupting state due to missing state locks; checking unencrypted state files containing passwords into Git.
- **Verification & Mastery Check**: Initialize a remote GCS backend with state locking and encryption; import an existing GCP VPC into Terraform management cleanly.
- **Project Application**: InfraBlueprint: Terraform remote state and foundational infrastructure.', '{"solution.py": "# Phase 7 // Lesson 7.30: Infrastructure as Code (IaC) with Terraform: Core Mechanics & State\n\ndef solve():\n    \"\"\"\n    Verification: Initialize a remote GCS backend with state locking and encryption; import an existing GCP VPC into T\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.30", "subtopics_count": 6, "verification_criteria": "Initialize a remote GCS backend with state locking and encryption; import an existing GCP VPC into Terraform management cleanly.", "subtopics": ["7.30.1 IaC principles: declarative infrastructure, version control, idempotency, and automated provisioning pipelines", "7.30.2 Terraform engine architecture: Core vs Providers, schema generation, dependency graph resolution, and execution plans", "7.30.3 The Terraform State file: mapping real-world cloud resources to configuration, metadata, and state locking", "7.30.4 Remote State management: Google Cloud Storage (GCS) backend, object versioning, and state locking via GCS/DynamoDB", "7.30.5 State security: why state files contain plaintext secrets and must be encrypted with customer-managed KMS keys", "7.30.6 Terraform commands deep dive: init, plan, apply, destroy, import, state mv, and refreshing resources"]}'::jsonb, '["Explain how this implementation prevents: Concurrent team applies corrupting state due to missing state locks; checking unencrypted state files containing passwor", "How does Infrastructure as Code (IaC) with Terraform: Core Mechanics & State scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-31', 'phase-07-lesson-31-terraform-modules-workspaces-production-a', 'module-10', 31, 'Lesson 10.31: Terraform Modules, Workspaces & Production Architecture', 'Prerequisites: Lesson 7.30', 'Prerequisites: Lesson 7.30 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 1550.0, '# Lesson 7.31: Terraform Modules, Workspaces & Production Architecture

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.30
- **Subtopics**:
  - `7.31.1` Terraform module architecture: root modules, child modules, input variables, outputs, and validation blocks
  - `7.31.2` Module design best practices: single responsibility, version pinning, and publishing to private registries
  - `7.31.3` Environment segregation: Terraform Workspaces vs directory-based layout (separate root modules per environment)
  - `7.31.4` Why directory-based segregation (`environments/prod`, `environments/stage`) is superior to workspaces for blast radius control
  - `7.31.5` Terraform expressions: for_each, count, dynamic blocks, splat operators, and conditional expressions
  - `7.31.6` Static analysis and policy-as-code: `tflint`, `tfsec`, and Open Policy Agent (OPA) / Conftest compliance validation in CI
- **Key Failure Modes & Edge Cases**: Using `count` instead of `for_each` causing massive cascading resource destructions when reordering list elements.
- **Verification & Mastery Check**: Build a reusable, versioned Terraform module for multi-zone GKE clusters with strict input variable validations.
- **Project Application**: InfraBlueprint: Production Terraform module library.', '{"solution.py": "# Phase 7 // Lesson 7.31: Terraform Modules, Workspaces & Production Architecture\n\ndef solve():\n    \"\"\"\n    Verification: Build a reusable, versioned Terraform module for multi-zone GKE clusters with strict input variable \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.31", "subtopics_count": 6, "verification_criteria": "Build a reusable, versioned Terraform module for multi-zone GKE clusters with strict input variable validations.", "subtopics": ["7.31.1 Terraform module architecture: root modules, child modules, input variables, outputs, and validation blocks", "7.31.2 Module design best practices: single responsibility, version pinning, and publishing to private registries", "7.31.3 Environment segregation: Terraform Workspaces vs directory-based layout (separate root modules per environment)", "7.31.4 Why directory-based segregation (`environments/prod`, `environments/stage`) is superior to workspaces for blast radius control", "7.31.5 Terraform expressions: for_each, count, dynamic blocks, splat operators, and conditional expressions", "7.31.6 Static analysis and policy-as-code: `tflint`, `tfsec`, and Open Policy Agent (OPA) / Conftest compliance validation in CI"]}'::jsonb, '["Explain how this implementation prevents: Using `count` instead of `for_each` causing massive cascading resource destructions when reordering list elements.", "How does Terraform Modules, Workspaces & Production Architecture scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-32', 'phase-07-lesson-32-terraform-drift-detection-refactoring-ter', 'module-10', 32, 'Lesson 10.32: Terraform Drift Detection, Refactoring & Terragrunt', 'Prerequisites: Lesson 7.31', 'Prerequisites: Lesson 7.31 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1600.0, '# Lesson 7.32: Terraform Drift Detection, Refactoring & Terragrunt

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.31
- **Subtopics**:
  - `7.32.1` Infrastructure drift: out-of-band manual console edits, silent cloud provider API changes, and reconciling state
  - `7.32.2` Automated drift detection: running scheduled `terraform plan -detailed-exitcode` pipelines in CI/CD
  - `7.32.3` Refactoring Terraform configurations: `moved` blocks for seamless resource renaming without destroying live infrastructure
  - `7.32.4` Targeted operations: `-target` flag usage, emergency manual state surgery (`state rm`, `state import`), and risks
  - `7.32.5` DRY Terraform with Terragrunt: centralized backend generation, common provider inheritance, and dependency graphs
  - `7.32.6` Handling breaking provider upgrades: managing provider lock files (`.terraform.lock.hcl`) across teams
- **Key Failure Modes & Edge Cases**: Manual console modifications creating unresolvable drift; dangerous `-target` applications leaving state partially updated.
- **Verification & Mastery Check**: Refactor an existing monolithic Terraform configuration using `moved` blocks to relocate resources into modules with zero recreations.
- **Project Application**: InfraBlueprint: Drift detection automation and Terragrunt orchestrations.', '{"solution.py": "# Phase 7 // Lesson 7.32: Terraform Drift Detection, Refactoring & Terragrunt\n\ndef solve():\n    \"\"\"\n    Verification: Refactor an existing monolithic Terraform configuration using `moved` blocks to relocate resources i\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.32", "subtopics_count": 6, "verification_criteria": "Refactor an existing monolithic Terraform configuration using `moved` blocks to relocate resources into modules with zero recreations.", "subtopics": ["7.32.1 Infrastructure drift: out-of-band manual console edits, silent cloud provider API changes, and reconciling state", "7.32.2 Automated drift detection: running scheduled `terraform plan -detailed-exitcode` pipelines in CI/CD", "7.32.3 Refactoring Terraform configurations: `moved` blocks for seamless resource renaming without destroying live infrastructure", "7.32.4 Targeted operations: `-target` flag usage, emergency manual state surgery (`state rm`, `state import`), and risks", "7.32.5 DRY Terraform with Terragrunt: centralized backend generation, common provider inheritance, and dependency graphs", "7.32.6 Handling breaking provider upgrades: managing provider lock files (`.terraform.lock.hcl`) across teams"]}'::jsonb, '["Explain how this implementation prevents: Manual console modifications creating unresolvable drift; dangerous `-target` applications leaving state partially updat", "How does Terraform Drift Detection, Refactoring & Terragrunt scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-33', 'phase-07-lesson-33-event-streaming-fundamentals-apache-kafka', 'module-10', 33, 'Lesson 10.33: Event Streaming Fundamentals: Apache Kafka Architecture & Storage Internals', 'Prerequisites: Phase 4, Lesson 7.4', 'Prerequisites: Phase 4, Lesson 7.4 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 1650.0, '# Lesson 7.33: Event Streaming Fundamentals: Apache Kafka Architecture & Storage Internals

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 7.4
- **Subtopics**:
  - `7.33.1` Message queues (RabbitMQ) vs Event streaming platforms (Kafka): push vs pull, message consumption vs durable logs
  - `7.33.2` Kafka core concepts: Topics, Partitions, Brokers, Clusters, and Replication Factor
  - `7.33.3` Storage internals on disk: commit log, segments, `.log` data files, `.index` offset indexes, and `.timeindex` files
  - `7.33.4` Sequential I/O and Zero-Copy optimization: page cache utilization and `sendfile()` kernel syscall eliminating context switches
  - `7.33.5` Log retention and compaction: time-based retention, size-based retention, clean/dirty log compaction, and tombstone markers
  - `7.33.6` Kafka metadata architectures: legacy ZooKeeper coordination vs modern KRaft (Kafka Raft metadata mode)
- **Key Failure Modes & Edge Cases**: High partition counts exceeding broker memory and file descriptor limits; broker disk filling up due to uncompacted tombstone keys.
- **Verification & Mastery Check**: Deploy a multi-broker Kafka KRaft cluster; inspect partition segment files on disk with `kafka-run-class.sh kafka.tools.DumpLogSegments`.
- **Project Application**: InfraBlueprint: Distributed Kafka event streaming infrastructure.', '{"solution.py": "# Phase 7 // Lesson 7.33: Event Streaming Fundamentals: Apache Kafka Architecture & Storage Internals\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a multi-broker Kafka KRaft cluster; inspect partition segment files on disk with `kafka-run-c\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.33", "subtopics_count": 6, "verification_criteria": "Deploy a multi-broker Kafka KRaft cluster; inspect partition segment files on disk with `kafka-run-class.sh kafka.tools.DumpLogSegments`.", "subtopics": ["7.33.1 Message queues (RabbitMQ) vs Event streaming platforms (Kafka): push vs pull, message consumption vs durable logs", "7.33.2 Kafka core concepts: Topics, Partitions, Brokers, Clusters, and Replication Factor", "7.33.3 Storage internals on disk: commit log, segments, `.log` data files, `.index` offset indexes, and `.timeindex` files", "7.33.4 Sequential I/O and Zero-Copy optimization: page cache utilization and `sendfile()` kernel syscall eliminating context switches", "7.33.5 Log retention and compaction: time-based retention, size-based retention, clean/dirty log compaction, and tombstone markers", "7.33.6 Kafka metadata architectures: legacy ZooKeeper coordination vs modern KRaft (Kafka Raft metadata mode)"]}'::jsonb, '["Explain how this implementation prevents: High partition counts exceeding broker memory and file descriptor limits; broker disk filling up due to uncompacted tomb", "How does Event Streaming Fundamentals: Apache Kafka Architecture & Storage Internals scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-34', 'phase-07-lesson-34-kafka-producers-consumers-guarantees-prot', 'module-10', 34, 'Lesson 10.34: Kafka Producers & Consumers: Guarantees & Protocols', 'Prerequisites: Lesson 7.33', 'Prerequisites: Lesson 7.33 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 1700.0, '# Lesson 7.34: Kafka Producers & Consumers: Guarantees & Protocols

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.33
- **Subtopics**:
  - `7.34.1` Producer mechanics: message keys, partitioners (Murmur2 hash), batching (`batch.size`, `linger.ms`), and compression (snappy, zstd)
  - `7.34.2` Producer durability guarantees: `acks=0`, `acks=1`, and `acks=all` (`min.insync.replicas` interaction)
  - `7.34.3` Idempotent producers: sequence numbers, producer IDs (PID), and eliminating message duplication on network retry
  - `7.34.4` Consumer groups architecture: partition assignment, group coordinators, and rebalance protocols (Eager vs Incremental Cooperative)
  - `7.34.5` Offset commit semantics: at-most-once, at-least-once, and exactly-once processing (Kafka Transactions and Read-Committed)
  - `7.34.6` Handling poisoned messages: Dead Letter Queues (DLQ), non-blocking retry topics with exponential backoff delay
- **Key Failure Modes & Edge Cases**: Silent message loss caused by `acks=1` during broker crashes; consumer rebalance storms freezing stream consumption.
- **Verification & Mastery Check**: Implement a resilient Kafka consumer with non-blocking retry topics, incremental cooperative rebalancing, and dead-letter queues.
- **Project Application**: TenantIQ: Asynchronous tenant event ingestion and audit pipeline.', '{"solution.py": "# Phase 7 // Lesson 7.34: Kafka Producers & Consumers: Guarantees & Protocols\n\ndef solve():\n    \"\"\"\n    Verification: Implement a resilient Kafka consumer with non-blocking retry topics, incremental cooperative rebalan\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.34", "subtopics_count": 6, "verification_criteria": "Implement a resilient Kafka consumer with non-blocking retry topics, incremental cooperative rebalancing, and dead-letter queues.", "subtopics": ["7.34.1 Producer mechanics: message keys, partitioners (Murmur2 hash), batching (`batch.size`, `linger.ms`), and compression (snappy, zstd)", "7.34.2 Producer durability guarantees: `acks=0`, `acks=1`, and `acks=all` (`min.insync.replicas` interaction)", "7.34.3 Idempotent producers: sequence numbers, producer IDs (PID), and eliminating message duplication on network retry", "7.34.4 Consumer groups architecture: partition assignment, group coordinators, and rebalance protocols (Eager vs Incremental Cooperative)", "7.34.5 Offset commit semantics: at-most-once, at-least-once, and exactly-once processing (Kafka Transactions and Read-Committed)", "7.34.6 Handling poisoned messages: Dead Letter Queues (DLQ), non-blocking retry topics with exponential backoff delay"]}'::jsonb, '["Explain how this implementation prevents: Silent message loss caused by `acks=1` during broker crashes; consumer rebalance storms freezing stream consumption.", "How does Kafka Producers & Consumers: Guarantees & Protocols scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-35', 'phase-07-lesson-35-chaos-engineering-principles-fault-inject', 'module-10', 35, 'Lesson 10.35: Chaos Engineering: Principles, Fault Injection & LitmusChaos', 'Prerequisites: Lesson 7.1, Lesson 7.12', 'Prerequisites: Lesson 7.1, Lesson 7.12 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1750.0, '# Lesson 7.35: Chaos Engineering: Principles, Fault Injection & LitmusChaos

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.1, Lesson 7.12
- **Subtopics**:
  - `7.35.1` Principles of Chaos Engineering: forming steady-state hypotheses, introducing real-world events, and minimizing blast radius
  - `7.35.2` Fault injection techniques: killing pods, terminating VMs, network latency injection, packet loss, and CPU/memory pressure
  - `7.35.3` Linux network chaos with `tc` (Traffic Control) and `netem`: adding jitter, artificial delay, and packet corruption
  - `7.35.4` LitmusChaos on Kubernetes: ChaosEngine, ChaosExperiment CRDs, and automated validation probes
  - `7.35.5` Game Days: designing team chaos exercises to validate monitoring, alerts, runbooks, and self-healing systems
  - `7.35.6` Automated continuous chaos testing in CI/CD staging environments before major production releases
- **Key Failure Modes & Edge Cases**: Running un-scoped chaos experiments in production taking down core shared databases; lacking automated abort switches.
- **Verification & Mastery Check**: Execute a LitmusChaos experiment injecting 500ms network latency and 20% packet drop; verify circuit breakers trip without user errors.
- **Project Application**: InfraBlueprint: Automated chaos engineering verification harness.', '{"solution.py": "# Phase 7 // Lesson 7.35: Chaos Engineering: Principles, Fault Injection & LitmusChaos\n\ndef solve():\n    \"\"\"\n    Verification: Execute a LitmusChaos experiment injecting 500ms network latency and 20% packet drop; verify circuit\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.35", "subtopics_count": 6, "verification_criteria": "Execute a LitmusChaos experiment injecting 500ms network latency and 20% packet drop; verify circuit breakers trip without user errors.", "subtopics": ["7.35.1 Principles of Chaos Engineering: forming steady-state hypotheses, introducing real-world events, and minimizing blast radius", "7.35.2 Fault injection techniques: killing pods, terminating VMs, network latency injection, packet loss, and CPU/memory pressure", "7.35.3 Linux network chaos with `tc` (Traffic Control) and `netem`: adding jitter, artificial delay, and packet corruption", "7.35.4 LitmusChaos on Kubernetes: ChaosEngine, ChaosExperiment CRDs, and automated validation probes", "7.35.5 Game Days: designing team chaos exercises to validate monitoring, alerts, runbooks, and self-healing systems", "7.35.6 Automated continuous chaos testing in CI/CD staging environments before major production releases"]}'::jsonb, '["Explain how this implementation prevents: Running un-scoped chaos experiments in production taking down core shared databases; lacking automated abort switches.", "How does Chaos Engineering: Principles, Fault Injection & LitmusChaos scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-1', 'phase-10-lesson-01-llm-apis-interaction-paradigms-rest-strea', 'module-11', 1, 'Lesson 11.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs', 'Prerequisites: Phase 4, Phase 9', 'Prerequisites: Phase 4, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 50.0, '# Lesson 10.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 9
- **Subtopics**:
  - `10.1.1` Foundation model API architectures: OpenAI, Anthropic, and Google Gemini API surface comparison
  - `10.1.2` HTTP streaming with Server-Sent Events (SSE): chunked transfer encoding, `data: [DONE]` markers, and low-latency token streaming
  - `10.1.3` Client-side consumption of streaming LLM outputs: handling partial JSON buffers and smooth rendering loops
  - `10.1.4` API parameters: Temperature (softmax scaling), Top-p (nucleus sampling), frequency_penalty, and presence_penalty
  - `10.1.5` Statelessness of LLM endpoints: passing multi-turn conversational message history (`system`, `user`, `assistant`)
  - `10.1.6` Rate limits: Tiered TPM (Tokens Per Minute) and RPM (Requests Per Minute); exponential backoff with jitter on HTTP 429
- **Key Failure Modes & Edge Cases**: Buffering the entire LLM response on the server before sending to the client, destroying perceived user response latency.
- **Verification & Mastery Check**: Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token rendering and retry backoff.
- **Project Application**: DocuMind: Streaming LLM gateway.', '{"solution.py": "# Phase 10 // Lesson 10.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs\n\ndef solve():\n    \"\"\"\n    Verification: Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token ren\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.1", "subtopics_count": 6, "verification_criteria": "Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token rendering and retry backoff.", "subtopics": ["10.1.1 Foundation model API architectures: OpenAI, Anthropic, and Google Gemini API surface comparison", "10.1.2 HTTP streaming with Server-Sent Events (SSE): chunked transfer encoding, `data: [DONE]` markers, and low-latency token streaming", "10.1.3 Client-side consumption of streaming LLM outputs: handling partial JSON buffers and smooth rendering loops", "10.1.4 API parameters: Temperature (softmax scaling), Top-p (nucleus sampling), frequency_penalty, and presence_penalty", "10.1.5 Statelessness of LLM endpoints: passing multi-turn conversational message history (`system`, `user`, `assistant`)", "10.1.6 Rate limits: Tiered TPM (Tokens Per Minute) and RPM (Requests Per Minute); exponential backoff with jitter on HTTP 429"]}'::jsonb, '["Explain how this implementation prevents: Buffering the entire LLM response on the server before sending to the client, destroying perceived user response latency", "How does LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-2', 'phase-10-lesson-02-prompt-engineering-science-zero-shot-few-', 'module-11', 2, 'Lesson 11.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct', 'Prerequisites: Lesson 10.1', 'Prerequisites: Lesson 10.1 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 100.0, '# Lesson 10.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.1
- **Subtopics**:
  - `10.2.1` Prompt engineering as programmatic programming: system instructions, contextual framing, and role specification
  - `10.2.2` Zero-Shot vs Few-Shot learning: in-context demonstrations, format conditioning, and selection of representative exemplars
  - `10.2.3` Chain-of-Thought (CoT) prompting (Wei et al.): eliciting step-by-step intermediate reasoning paths for complex logic
  - `10.2.4` Least-to-Most prompting: decomposing complex multi-step queries into sub-problems solved iteratively
  - `10.2.5` ReAct framework (Yao et al.): interleaving Reasoning (''Thought'') and Action (''Act'' / tool call) to interact with external tools
  - `10.2.6` Prompt fragility: why formatting quirks, whitespace, and capitalization trigger dramatic model accuracy variations
- **Key Failure Modes & Edge Cases**: Over-prompting with contradictory multi-page instructions causing the model to hallucinate or ignore negative constraints.
- **Verification & Mastery Check**: Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy on mathematical word problems.
- **Project Application**: DocuMind: Prompt orchestration and template library.', '{"solution.py": "# Phase 10 // Lesson 10.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct\n\ndef solve():\n    \"\"\"\n    Verification: Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.2", "subtopics_count": 6, "verification_criteria": "Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy on mathematical word problems.", "subtopics": ["10.2.1 Prompt engineering as programmatic programming: system instructions, contextual framing, and role specification", "10.2.2 Zero-Shot vs Few-Shot learning: in-context demonstrations, format conditioning, and selection of representative exemplars", "10.2.3 Chain-of-Thought (CoT) prompting (Wei et al.): eliciting step-by-step intermediate reasoning paths for complex logic", "10.2.4 Least-to-Most prompting: decomposing complex multi-step queries into sub-problems solved iteratively", "10.2.5 ReAct framework (Yao et al.): interleaving Reasoning (''Thought'') and Action (''Act'' / tool call) to interact with external tools", "10.2.6 Prompt fragility: why formatting quirks, whitespace, and capitalization trigger dramatic model accuracy variations"]}'::jsonb, '["Explain how this implementation prevents: Over-prompting with contradictory multi-page instructions causing the model to hallucinate or ignore negative constraint", "How does Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-3', 'phase-10-lesson-03-structured-outputs-function-calling-json-', 'module-11', 3, 'Lesson 11.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding', 'Prerequisites: Phase 1, Lesson 10.1', 'Prerequisites: Phase 1, Lesson 10.1 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 150.0, '# Lesson 10.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Lesson 10.1
- **Subtopics**:
  - `10.3.1` Why natural language outputs fail in production pipelines: parsing errors, non-deterministic formatting, and markdown fences
  - `10.3.2` OpenAI Function Calling / Tool Calling specification: JSON Schema declarations for functions, parameters, and types
  - `10.3.3` Pydantic integration: automatic generation of JSON Schemas from Python type annotations (`model_json_schema()`)
  - `10.3.4` OpenAI Structured Outputs (`response_format={''type'': ''json_schema''}`): 100% schema adherence guarantees
  - `10.3.5` Constrained Decoding mechanics: how inference engines mask invalid token vocabulary logits during autoregressive sampling based on CFG/grammar
  - `10.3.6` Open-source grammar-constrained decoding: Outlines, Guidance, and llama.cpp GBNF grammar files
- **Key Failure Modes & Edge Cases**: Relying on naive regex parsing to extract JSON from raw model strings, causing crashes when models wrap output in markdown code blocks.
- **Verification & Mastery Check**: Build an automated data extraction pipeline using Pydantic models and strict constrained decoding with 100% schema compliance.
- **Project Application**: DocuMind: Structured schema extraction engine.', '{"solution.py": "# Phase 10 // Lesson 10.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding\n\ndef solve():\n    \"\"\"\n    Verification: Build an automated data extraction pipeline using Pydantic models and strict constrained decoding wi\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.3", "subtopics_count": 6, "verification_criteria": "Build an automated data extraction pipeline using Pydantic models and strict constrained decoding with 100% schema compliance.", "subtopics": ["10.3.1 Why natural language outputs fail in production pipelines: parsing errors, non-deterministic formatting, and markdown fences", "10.3.2 OpenAI Function Calling / Tool Calling specification: JSON Schema declarations for functions, parameters, and types", "10.3.3 Pydantic integration: automatic generation of JSON Schemas from Python type annotations (`model_json_schema()`)", "10.3.4 OpenAI Structured Outputs (`response_format={''type'': ''json_schema''}`): 100% schema adherence guarantees", "10.3.5 Constrained Decoding mechanics: how inference engines mask invalid token vocabulary logits during autoregressive sampling based on CFG/grammar", "10.3.6 Open-source grammar-constrained decoding: Outlines, Guidance, and llama.cpp GBNF grammar files"]}'::jsonb, '["Explain how this implementation prevents: Relying on naive regex parsing to extract JSON from raw model strings, causing crashes when models wrap output in markdo", "How does Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-4', 'phase-10-lesson-04-context-window-dynamics-lost-in-the-middl', 'module-11', 4, 'Lesson 11.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution', 'Prerequisites: Phase 9, Lesson 10.2', 'Prerequisites: Phase 9, Lesson 10.2 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 200.0, '# Lesson 10.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Lesson 10.2
- **Subtopics**:
  - `10.4.1` Context window evolution: from 4K (GPT-3) to 128K (GPT-4) to 1M-2M tokens (Gemini 1.5)
  - `10.4.2` The ''Lost in the Middle'' phenomenon (Liu et al.): attention bias toward the beginning and end of long contexts
  - `10.4.3` Needle-in-a-Haystack (NIAH) evaluation: inserting synthetic facts at varying depth percentages ($0\%$ to $100\%$) to measure retrieval recall
  - `10.4.4` Attention dilution: performance degradation and reasoning degradation as context length increases with irrelevant noise
  - `10.4.5` Cost and latency implications: linear cost scaling and quadratic/linear latency increases with massive input prompts
  - `10.4.6` Strategic context placement: placing primary instructions at the very end and grounding documents near the top/bottom
- **Key Failure Modes & Edge Cases**: Stuffing 200 pages of raw un-filtered documentation into an LLM prompt, causing the model to miss critical instructions buried in the middle.
- **Verification & Mastery Check**: Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the resulting retrieval accuracy heatmap.
- **Project Application**: EvalKit: Context window diagnostic and needle benchmark suite.', '{"solution.py": "# Phase 10 // Lesson 10.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution\n\ndef solve():\n    \"\"\"\n    Verification: Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the r\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.4", "subtopics_count": 6, "verification_criteria": "Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the resulting retrieval accuracy heatmap.", "subtopics": ["10.4.1 Context window evolution: from 4K (GPT-3) to 128K (GPT-4) to 1M-2M tokens (Gemini 1.5)", "10.4.2 The ''Lost in the Middle'' phenomenon (Liu et al.): attention bias toward the beginning and end of long contexts", "10.4.3 Needle-in-a-Haystack (NIAH) evaluation: inserting synthetic facts at varying depth percentages ($0\\%$ to $100\\%$) to measure retrieval recall", "10.4.4 Attention dilution: performance degradation and reasoning degradation as context length increases with irrelevant noise", "10.4.5 Cost and latency implications: linear cost scaling and quadratic/linear latency increases with massive input prompts", "10.4.6 Strategic context placement: placing primary instructions at the very end and grounding documents near the top/bottom"]}'::jsonb, '["Explain how this implementation prevents: Stuffing 200 pages of raw un-filtered documentation into an LLM prompt, causing the model to miss critical instructions ", "How does Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-5', 'phase-10-lesson-05-tokenization-mechanics-bpe-wordpiece-tikt', 'module-11', 5, 'Lesson 11.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math', 'Prerequisites: Phase 3, Phase 9', 'Prerequisites: Phase 3, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 250.0, '# Lesson 10.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Phase 9
- **Subtopics**:
  - `10.5.1` Tokenization paradigms: Character-level vs Word-level vs Subword tokenization (Byte-Pair Encoding, WordPiece, Unigram)
  - `10.5.2` Byte-Pair Encoding (BPE) algorithm: starting with single bytes, iteratively merging most frequent byte pairs into vocabulary
  - `10.5.3` Byte-level BPE: handling arbitrary Unicode characters without unknown token (`<unk>`) out-of-vocabulary fallbacks
  - `10.5.4` Tiktoken library internals: fast Rust-backed BPE tokenizer for OpenAI models (`cl100k_base`, `o200k_base`)
  - `10.5.5` Tokenization quirks and vulnerabilities: space prefix sensitivity, arithmetic failure modes (numbers split into uneven chunks)
  - `10.5.6` Financial cost and latency estimation: calculating token consumption formulas ($1\text{ token} \approx 0.75\text{ words}$ in English; higher for code/non-English)
- **Key Failure Modes & Edge Cases**: Assuming 1 character = 1 token, underestimating API costs and context window consumption by 300% on multilingual text.
- **Verification & Mastery Check**: Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and visualize merge operations.
- **Project Application**: DocuMind: Tokenization and cost accounting module.', '{"solution.py": "# Phase 10 // Lesson 10.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.5", "subtopics_count": 6, "verification_criteria": "Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and visualize merge operations.", "subtopics": ["10.5.1 Tokenization paradigms: Character-level vs Word-level vs Subword tokenization (Byte-Pair Encoding, WordPiece, Unigram)", "10.5.2 Byte-Pair Encoding (BPE) algorithm: starting with single bytes, iteratively merging most frequent byte pairs into vocabulary", "10.5.3 Byte-level BPE: handling arbitrary Unicode characters without unknown token (`<unk>`) out-of-vocabulary fallbacks", "10.5.4 Tiktoken library internals: fast Rust-backed BPE tokenizer for OpenAI models (`cl100k_base`, `o200k_base`)", "10.5.5 Tokenization quirks and vulnerabilities: space prefix sensitivity, arithmetic failure modes (numbers split into uneven chunks)", "10.5.6 Financial cost and latency estimation: calculating token consumption formulas ($1\\text{ token} \\approx 0.75\\text{ words}$ in English; higher for code/non-English)"]}'::jsonb, '["Explain how this implementation prevents: Assuming 1 character = 1 token, underestimating API costs and context window consumption by 300% on multilingual text.", "How does Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
