INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-5-1', 'phase-05-lesson-01-restful-architecture-resource-modeling-ve', 'module-7', 1, 'Lesson 7.1: RESTful Architecture: Resource Modeling & Verbs', 'Prerequisites: Phase 4 (Lesson 4.29)', 'Prerequisites: Phase 4 (Lesson 4.29) | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 50.0, '# Lesson 5.1: RESTful Architecture: Resource Modeling & Verbs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4 (Lesson 4.29)
- **Subtopics**:
  - `5.1.1` Resource-oriented URI design: resources as plural nouns (`/api/v1/projects/{id}/artifacts`).
  - `5.1.2` HTTP verb semantic contracts: `GET` (safe, idempotent), `POST` (non-idempotent), `PUT` (idempotent replace), `PATCH` (partial update), `DELETE`.
  - `5.1.3` Nesting resources vs flat resource paths: trade-offs in sub-resource modeling.
  - `5.1.4` Hypermedia and HATEOAS: dynamic discoverability of API action links.
- **Key Failure Modes & Edge Cases**: Exposing RPC verbs in REST paths (e.g., `POST /api/v1/deleteUser`), violating HTTP caching and semantic specifications.
- **Verification & Mastery Check**: Design a RESTful API specification for a multi-tenant project management platform adhering strictly to RFC specifications.
- **Project Application**: AuthForge and TenantIQ API surfaces.', '{"solution.py": "# Phase 5 // Lesson 5.1: RESTful Architecture: Resource Modeling & Verbs\n\ndef solve():\n    \"\"\"\n    Verification: Design a RESTful API specification for a multi-tenant project management platform adhering strictly \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.1", "subtopics_count": 4, "verification_criteria": "Design a RESTful API specification for a multi-tenant project management platform adhering strictly to RFC specifications.", "subtopics": ["5.1.1 Resource-oriented URI design: resources as plural nouns (`/api/v1/projects/{id}/artifacts`).", "5.1.2 HTTP verb semantic contracts: `GET` (safe, idempotent), `POST` (non-idempotent), `PUT` (idempotent replace), `PATCH` (partial update), `DELETE`.", "5.1.3 Nesting resources vs flat resource paths: trade-offs in sub-resource modeling.", "5.1.4 Hypermedia and HATEOAS: dynamic discoverability of API action links."]}'::jsonb, '["Explain how this implementation prevents: Exposing RPC verbs in REST paths (e.g., `POST /api/v1/deleteUser`), violating HTTP caching and semantic specifications.", "How does RESTful Architecture: Resource Modeling & Verbs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-2', 'phase-05-lesson-02-http-status-codes-precision-rfc-semantics', 'module-7', 2, 'Lesson 7.2: HTTP Status Codes Precision & RFC Semantics', 'Prerequisites: Lesson 5.1', 'Prerequisites: Lesson 5.1 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 100.0, '# Lesson 5.2: HTTP Status Codes Precision & RFC Semantics

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.1
- **Subtopics**:
  - `5.2.1` 2xx Success: 200 OK, 201 Created (with `Location` header), 204 No Content.
  - `5.2.2` 4xx Client Errors: 400 Bad Request, 401 Unauthorized (unauthenticated), 403 Forbidden (authenticated, unauthorized), 404 Not Found, 409 Conflict, 422 Unprocessable Entity, 429 Too Many Requests.
  - `5.2.3` 5xx Server Errors: 500 Internal Error, 502 Bad Gateway, 503 Service Unavailable, 504 Gateway Timeout.
  - `5.2.4` Error response standards: RFC 7807 Problem Details for HTTP APIs (`type`, `title`, `status`, `detail`, `instance`).
- **Key Failure Modes & Edge Cases**: Returning `200 OK` with `{"error": true}` in the JSON payload, breaking client error handling and upstream HTTP proxies.
- **Verification & Mastery Check**: Implement custom error handlers in FastAPI returning standardized RFC 7807 problem detail payloads.
- **Project Application**: AuthForge: API error handling.', '{"solution.py": "# Phase 5 // Lesson 5.2: HTTP Status Codes Precision & RFC Semantics\n\ndef solve():\n    \"\"\"\n    Verification: Implement custom error handlers in FastAPI returning standardized RFC 7807 problem detail payloads.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.2", "subtopics_count": 4, "verification_criteria": "Implement custom error handlers in FastAPI returning standardized RFC 7807 problem detail payloads.", "subtopics": ["5.2.1 2xx Success: 200 OK, 201 Created (with `Location` header), 204 No Content.", "5.2.2 4xx Client Errors: 400 Bad Request, 401 Unauthorized (unauthenticated), 403 Forbidden (authenticated, unauthorized), 404 Not Found, 409 Conflict, 422 Unprocessable Entity, 429 Too Many Requests.", "5.2.3 5xx Server Errors: 500 Internal Error, 502 Bad Gateway, 503 Service Unavailable, 504 Gateway Timeout.", "5.2.4 Error response standards: RFC 7807 Problem Details for HTTP APIs (`type`, `title`, `status`, `detail`, `instance`)."]}'::jsonb, '["Explain how this implementation prevents: Returning `200 OK` with `{\"error\": true}` in the JSON payload, breaking client error handling and upstream HTTP proxies.", "How does HTTP Status Codes Precision & RFC Semantics scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-3', 'phase-05-lesson-03-safe-retries-idempotency-key-architecture', 'module-7', 3, 'Lesson 7.3: Safe Retries & Idempotency Key Architecture', 'Prerequisites: Lesson 5.1', 'Prerequisites: Lesson 5.1 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 150.0, '# Lesson 5.3: Safe Retries & Idempotency Key Architecture

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.1
- **Subtopics**:
  - `5.3.1` The network retry hazard: network timeout on `POST` requests causing duplicate credit card charges or order creation.
  - `5.3.2` Idempotency Key mechanism: client transmits UUID in `Idempotency-Key` header.
  - `5.3.3` Server-side idempotency state machine in Redis: Pending, Processing, Completed; storing response payload with TTL.
  - `5.3.4` Concurrency handling: locking idempotency keys to reject simultaneous duplicate requests with `409 Conflict`.
- **Key Failure Modes & Edge Cases**: Double-charging customers during network blips due to non-idempotent order submission endpoints.
- **Verification & Mastery Check**: Build an Idempotency Middleware in FastAPI using Redis that guarantees zero duplicate executions for repeated identical requests.
- **Project Application**: AuthForge and TenantIQ: Stripe payment and mutation endpoints.', '{"solution.py": "# Phase 5 // Lesson 5.3: Safe Retries & Idempotency Key Architecture\n\ndef solve():\n    \"\"\"\n    Verification: Build an Idempotency Middleware in FastAPI using Redis that guarantees zero duplicate executions for\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.3", "subtopics_count": 4, "verification_criteria": "Build an Idempotency Middleware in FastAPI using Redis that guarantees zero duplicate executions for repeated identical requests.", "subtopics": ["5.3.1 The network retry hazard: network timeout on `POST` requests causing duplicate credit card charges or order creation.", "5.3.2 Idempotency Key mechanism: client transmits UUID in `Idempotency-Key` header.", "5.3.3 Server-side idempotency state machine in Redis: Pending, Processing, Completed; storing response payload with TTL.", "5.3.4 Concurrency handling: locking idempotency keys to reject simultaneous duplicate requests with `409 Conflict`."]}'::jsonb, '["Explain how this implementation prevents: Double-charging customers during network blips due to non-idempotent order submission endpoints.", "How does Safe Retries & Idempotency Key Architecture scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-4', 'phase-05-lesson-04-pagination-architectures-offset-vs-keyset', 'module-7', 4, 'Lesson 7.4: Pagination Architectures: Offset vs Keyset Cursors', 'Prerequisites: Lesson 5.1, Phase 3 (Lesson 3.26)', 'Prerequisites: Lesson 5.1, Phase 3 (Lesson 3.26) | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 200.0, '# Lesson 5.4: Pagination Architectures: Offset vs Keyset Cursors

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.1, Phase 3 (Lesson 3.26)
- **Subtopics**:
  - `5.4.1` Offset-based pagination: `LIMIT 20 OFFSET 1000`; $O(n)$ database scan overhead; offset drift (missing or duplicate rows during insertions).
  - `5.4.2` Keyset / Cursor-based pagination: `WHERE (created_at, id) < (:cursor_time, :cursor_id) ORDER BY created_at DESC, id DESC LIMIT 20`.
  - `5.4.3` Cursor encoding: base64 encoding opaque composite cursor strings.
  - `5.4.4` Performance comparison: $O(1)$ indexed seek vs $O(n)$ full scan across deep pagination pages.
- **Key Failure Modes & Edge Cases**: Database CPU saturation caused by web crawlers scraping deep pages on offset-paginated tables with 10M rows.
- **Verification & Mastery Check**: Implement keyset cursor pagination on a high-throughput table, verify constant-time query latency across deep offsets.
- **Project Application**: TenantIQ: Activity feed pagination.', '{"solution.py": "# Phase 5 // Lesson 5.4: Pagination Architectures: Offset vs Keyset Cursors\n\ndef solve():\n    \"\"\"\n    Verification: Implement keyset cursor pagination on a high-throughput table, verify constant-time query latency ac\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.4", "subtopics_count": 4, "verification_criteria": "Implement keyset cursor pagination on a high-throughput table, verify constant-time query latency across deep offsets.", "subtopics": ["5.4.1 Offset-based pagination: `LIMIT 20 OFFSET 1000`; $O(n)$ database scan overhead; offset drift (missing or duplicate rows during insertions).", "5.4.2 Keyset / Cursor-based pagination: `WHERE (created_at, id) < (:cursor_time, :cursor_id) ORDER BY created_at DESC, id DESC LIMIT 20`.", "5.4.3 Cursor encoding: base64 encoding opaque composite cursor strings.", "5.4.4 Performance comparison: $O(1)$ indexed seek vs $O(n)$ full scan across deep pagination pages."]}'::jsonb, '["Explain how this implementation prevents: Database CPU saturation caused by web crawlers scraping deep pages on offset-paginated tables with 10M rows.", "How does Pagination Architectures: Offset vs Keyset Cursors scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-5', 'phase-05-lesson-05-api-versioning-methodologies-deprecation-', 'module-7', 5, 'Lesson 7.5: API Versioning Methodologies & Deprecation Policies', 'Prerequisites: Lesson 5.1', 'Prerequisites: Lesson 5.1 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 250.0, '# Lesson 5.5: API Versioning Methodologies & Deprecation Policies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.1
- **Subtopics**:
  - `5.5.1` URI Path versioning (`/v1/users`): clarity, simple caching, routing isolation.
  - `5.5.2` Header versioning: `Accept: application/vnd.app.v1+json`; clean URIs, client complexity.
  - `5.5.3` Query parameter versioning: `/users?version=1`.
  - `5.5.4` Managing backward compatibility: additive schema updates, Sunset headers (`Sunset: Wed, 11 Nov 2026 00:00:00 GMT`), graceful migration windows.
- **Key Failure Modes & Edge Cases**: Breaking mobile client applications by removing or modifying fields on active API versions without backward compatibility.
- **Verification & Mastery Check**: Design and implement a versioned API supporting both v1 and v2 simultaneously with automated deprecation warning headers.
- **Project Application**: AuthForge and TenantIQ API versioning.', '{"solution.py": "# Phase 5 // Lesson 5.5: API Versioning Methodologies & Deprecation Policies\n\ndef solve():\n    \"\"\"\n    Verification: Design and implement a versioned API supporting both v1 and v2 simultaneously with automated depreca\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.5", "subtopics_count": 4, "verification_criteria": "Design and implement a versioned API supporting both v1 and v2 simultaneously with automated deprecation warning headers.", "subtopics": ["5.5.1 URI Path versioning (`/v1/users`): clarity, simple caching, routing isolation.", "5.5.2 Header versioning: `Accept: application/vnd.app.v1+json`; clean URIs, client complexity.", "5.5.3 Query parameter versioning: `/users?version=1`.", "5.5.4 Managing backward compatibility: additive schema updates, Sunset headers (`Sunset: Wed, 11 Nov 2026 00:00:00 GMT`), graceful migration windows."]}'::jsonb, '["Explain how this implementation prevents: Breaking mobile client applications by removing or modifying fields on active API versions without backward compatibilit", "How does API Versioning Methodologies & Deprecation Policies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-6', 'phase-05-lesson-06-fastapi-architecture-uvicorn-the-asgi-spe', 'module-7', 6, 'Lesson 7.6: FastAPI Architecture, Uvicorn, & The ASGI Specification', 'Prerequisites: Phase 1 (Lesson 1.32), Phase 4 (Lesson 4.23)', 'Prerequisites: Phase 1 (Lesson 1.32), Phase 4 (Lesson 4.23) | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 300.0, '# Lesson 5.6: FastAPI Architecture, Uvicorn, & The ASGI Specification

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.32), Phase 4 (Lesson 4.23)
- **Subtopics**:
  - `5.6.1` Asynchronous Server Gateway Interface (ASGI): scope dictionary, receive callable, send callable.
  - `5.6.2` Uvicorn server: libuv/asyncio-backed ASGI HTTP server.
  - `5.6.3` Starlette core: routing, middleware stack, request/response cycle.
  - `5.6.4` FastAPI enhancements: automatic OpenAPI documentation (`/docs`), Swagger UI, ReDoc, and validation integration.
- **Key Failure Modes & Edge Cases**: Running CPU-intensive tasks inside FastAPI async route handlers, blocking the single event loop thread for all requests.
- **Verification & Mastery Check**: Write a raw ASGI application callable from scratch without frameworks, and run it directly with Uvicorn.
- **Project Application**: AuthForge: Core web service engine.', '{"solution.py": "# Phase 5 // Lesson 5.6: FastAPI Architecture, Uvicorn, & The ASGI Specification\n\ndef solve():\n    \"\"\"\n    Verification: Write a raw ASGI application callable from scratch without frameworks, and run it directly with Uvic\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.6", "subtopics_count": 4, "verification_criteria": "Write a raw ASGI application callable from scratch without frameworks, and run it directly with Uvicorn.", "subtopics": ["5.6.1 Asynchronous Server Gateway Interface (ASGI): scope dictionary, receive callable, send callable.", "5.6.2 Uvicorn server: libuv/asyncio-backed ASGI HTTP server.", "5.6.3 Starlette core: routing, middleware stack, request/response cycle.", "5.6.4 FastAPI enhancements: automatic OpenAPI documentation (`/docs`), Swagger UI, ReDoc, and validation integration."]}'::jsonb, '["Explain how this implementation prevents: Running CPU-intensive tasks inside FastAPI async route handlers, blocking the single event loop thread for all requests.", "How does FastAPI Architecture, Uvicorn, & The ASGI Specification scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-7', 'phase-05-lesson-07-pydantic-v2-internals-high-speed-schema-v', 'module-7', 7, 'Lesson 7.7: Pydantic v2 Internals & High-Speed Schema Validation', 'Prerequisites: Phase 1 (Lesson 1.4)', 'Prerequisites: Phase 1 (Lesson 1.4) | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 350.0, '# Lesson 5.7: Pydantic v2 Internals & High-Speed Schema Validation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.4)
- **Subtopics**:
  - `5.7.1` Pydantic v2 core: `pydantic-core` C/Rust validation engine delivering 5x–20x speedups over v1.
  - `5.7.2` Data validation with `BaseModel`: field types, constraints (`Field(gt=0, max_length=100)`), custom regex.
  - `5.7.3` Field validators (`@field_validator`) vs Model validators (`@model_validator(mode=''before'')`).
  - `5.7.4` Serialization: `model_dump()`, `model_dump_json()`, excluding unset fields (`exclude_unset=True`).
- **Key Failure Modes & Edge Cases**: Using Pydantic models for high-throughput batch transformations without understanding serialization overhead.
- **Verification & Mastery Check**: Define strict nested Pydantic models validating complex API payloads with cross-field conditional validation.
- **Project Application**: AuthForge: Request/Response validation schemas.', '{"solution.py": "# Phase 5 // Lesson 5.7: Pydantic v2 Internals & High-Speed Schema Validation\n\ndef solve():\n    \"\"\"\n    Verification: Define strict nested Pydantic models validating complex API payloads with cross-field conditional va\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.7", "subtopics_count": 4, "verification_criteria": "Define strict nested Pydantic models validating complex API payloads with cross-field conditional validation.", "subtopics": ["5.7.1 Pydantic v2 core: `pydantic-core` C/Rust validation engine delivering 5x\u201320x speedups over v1.", "5.7.2 Data validation with `BaseModel`: field types, constraints (`Field(gt=0, max_length=100)`), custom regex.", "5.7.3 Field validators (`@field_validator`) vs Model validators (`@model_validator(mode=''before'')`).", "5.7.4 Serialization: `model_dump()`, `model_dump_json()`, excluding unset fields (`exclude_unset=True`)."]}'::jsonb, '["Explain how this implementation prevents: Using Pydantic models for high-throughput batch transformations without understanding serialization overhead.", "How does Pydantic v2 Internals & High-Speed Schema Validation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-8', 'phase-05-lesson-08-fastapi-dependency-injection-hierarchy-li', 'module-7', 8, 'Lesson 7.8: FastAPI Dependency Injection Hierarchy & Lifespan Hooks', 'Prerequisites: Phase 1 (Lesson 1.50), Lesson 5.6', 'Prerequisites: Phase 1 (Lesson 1.50), Lesson 5.6 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 400.0, '# Lesson 5.8: FastAPI Dependency Injection Hierarchy & Lifespan Hooks

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.50), Lesson 5.6
- **Subtopics**:
  - `5.8.1` FastAPI Dependency Injection: `fastapi.Depends`, sub-dependencies, hierarchical dependency resolution.
  - `5.8.2` Yield dependencies: resource provisioning and cleanup (database sessions, transaction scopes).
  - `5.8.3` Authentication dependencies: extracting Bearer tokens, decoding claims, injecting `CurrentUser` models.
  - `5.8.4` Application Lifespan: `lifespan(app)` context manager for managing global connection pools on startup/shutdown.
- **Key Failure Modes & Edge Cases**: Opening database connections inside individual route dependencies without pooling or cleanup yields, leaking connections.
- **Verification & Mastery Check**: Build a multi-level dependency tree that validates API keys, checks database tenancy, and injects a scoped DB session.
- **Project Application**: AuthForge: Route security dependencies.', '{"solution.py": "# Phase 5 // Lesson 5.8: FastAPI Dependency Injection Hierarchy & Lifespan Hooks\n\ndef solve():\n    \"\"\"\n    Verification: Build a multi-level dependency tree that validates API keys, checks database tenancy, and injects a \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.8", "subtopics_count": 4, "verification_criteria": "Build a multi-level dependency tree that validates API keys, checks database tenancy, and injects a scoped DB session.", "subtopics": ["5.8.1 FastAPI Dependency Injection: `fastapi.Depends`, sub-dependencies, hierarchical dependency resolution.", "5.8.2 Yield dependencies: resource provisioning and cleanup (database sessions, transaction scopes).", "5.8.3 Authentication dependencies: extracting Bearer tokens, decoding claims, injecting `CurrentUser` models.", "5.8.4 Application Lifespan: `lifespan(app)` context manager for managing global connection pools on startup/shutdown."]}'::jsonb, '["Explain how this implementation prevents: Opening database connections inside individual route dependencies without pooling or cleanup yields, leaking connections", "How does FastAPI Dependency Injection Hierarchy & Lifespan Hooks scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-9', 'phase-05-lesson-09-relational-algebra-normalization-1nf-2nf-', 'module-7', 9, 'Lesson 7.9: Relational Algebra & Normalization: 1NF, 2NF, 3NF, BCNF', 'Prerequisites: Phase 2 (Lesson 2.5)', 'Prerequisites: Phase 2 (Lesson 2.5) | Subtopics: 5 items', 'Systems project application', 200, 6, 1250.0, 450.0, '# Lesson 5.9: Relational Algebra & Normalization: 1NF, 2NF, 3NF, BCNF

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2 (Lesson 2.5)
- **Subtopics**:
  - `5.9.1` Relational Algebra primitives: Selection ($\sigma$), Projection ($\pi$), Cartesian Product ($	imes$), Join ($owtie$).
  - `5.9.2` First Normal Form (1NF): atomic values, unique column names, primary key defined.
  - `5.9.3` Second Normal Form (2NF): 1NF + no partial dependencies (non-key attributes dependent on full composite key).
  - `5.9.4` Third Normal Form (3NF): 2NF + no transitive dependencies (non-key attributes dependent only on primary key).
  - `5.9.5` Boyce-Codd Normal Form (BCNF): every determinant is a candidate key; anomalies eliminated.
- **Key Failure Modes & Edge Cases**: Storing comma-separated lists in database columns (violating 1NF), making indexing and joins impossible.
- **Verification & Mastery Check**: Take an un-normalized, redundant spreadsheet schema and normalize it through 1NF, 2NF, and 3NF into relational tables.
- **Project Application**: SchemaVault: Normalized relational models.', '{"solution.py": "# Phase 5 // Lesson 5.9: Relational Algebra & Normalization: 1NF, 2NF, 3NF, BCNF\n\ndef solve():\n    \"\"\"\n    Verification: Take an un-normalized, redundant spreadsheet schema and normalize it through 1NF, 2NF, and 3NF into \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.9", "subtopics_count": 5, "verification_criteria": "Take an un-normalized, redundant spreadsheet schema and normalize it through 1NF, 2NF, and 3NF into relational tables.", "subtopics": ["5.9.1 Relational Algebra primitives: Selection ($\\sigma$), Projection ($\\pi$), Cartesian Product ($\times$), Join ($\bowtie$).", "5.9.2 First Normal Form (1NF): atomic values, unique column names, primary key defined.", "5.9.3 Second Normal Form (2NF): 1NF + no partial dependencies (non-key attributes dependent on full composite key).", "5.9.4 Third Normal Form (3NF): 2NF + no transitive dependencies (non-key attributes dependent only on primary key).", "5.9.5 Boyce-Codd Normal Form (BCNF): every determinant is a candidate key; anomalies eliminated."]}'::jsonb, '["Explain how this implementation prevents: Storing comma-separated lists in database columns (violating 1NF), making indexing and joins impossible.", "How does Relational Algebra & Normalization: 1NF, 2NF, 3NF, BCNF scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-10', 'phase-05-lesson-10-pragmatic-denormalization-write-amplifica', 'module-7', 10, 'Lesson 7.10: Pragmatic Denormalization & Write Amplification', 'Prerequisites: Lesson 5.9', 'Prerequisites: Lesson 5.9 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 500.0, '# Lesson 5.10: Pragmatic Denormalization & Write Amplification

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.9
- **Subtopics**:
  - `5.10.1` When to violate 3NF: read-heavy workloads where joins across 8 tables cause severe latency.
  - `5.10.2` Denormalization strategies: pre-computed counters, caching parent status in child records, summary tables.
  - `5.10.3` Maintaining consistency in denormalized data: database triggers vs application-level transactions.
  - `5.10.4` Write Amplification: calculating the extra disk writes incurred across multiple denormalized copies during updates.
- **Key Failure Modes & Edge Cases**: Denormalizing data without transactional synchronization, causing permanent data divergence between tables.
- **Verification & Mastery Check**: Benchmark query performance between a fully normalized 3NF schema and a pragmatic denormalized schema under read/write load.
- **Project Application**: TenantIQ: Precomputed DORA metric summaries.', '{"solution.py": "# Phase 5 // Lesson 5.10: Pragmatic Denormalization & Write Amplification\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark query performance between a fully normalized 3NF schema and a pragmatic denormalized schem\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.10", "subtopics_count": 4, "verification_criteria": "Benchmark query performance between a fully normalized 3NF schema and a pragmatic denormalized schema under read/write load.", "subtopics": ["5.10.1 When to violate 3NF: read-heavy workloads where joins across 8 tables cause severe latency.", "5.10.2 Denormalization strategies: pre-computed counters, caching parent status in child records, summary tables.", "5.10.3 Maintaining consistency in denormalized data: database triggers vs application-level transactions.", "5.10.4 Write Amplification: calculating the extra disk writes incurred across multiple denormalized copies during updates."]}'::jsonb, '["Explain how this implementation prevents: Denormalizing data without transactional synchronization, causing permanent data divergence between tables.", "How does Pragmatic Denormalization & Write Amplification scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-11', 'phase-05-lesson-11-sql-execution-order-core-dialect-mechanic', 'module-7', 11, 'Lesson 7.11: SQL Execution Order & Core Dialect Mechanics', 'Prerequisites: Phase 2 (Lesson 2.1)', 'Prerequisites: Phase 2 (Lesson 2.1) | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 550.0, '# Lesson 5.11: SQL Execution Order & Core Dialect Mechanics

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2 (Lesson 2.1)
- **Subtopics**:
  - `5.11.1` SQL physical processing order: `FROM` $	o$ `JOIN` $	o$ `WHERE` $	o$ `GROUP BY` $	o$ `HAVING` $	o$ `SELECT` $	o$ `DISTINCT` $	o$ `ORDER BY` $	o$ `LIMIT`.
  - `5.11.2` Why column aliases defined in `SELECT` cannot be referenced in `WHERE` clauses.
  - `5.11.3` NULL semantics: Three-Valued Logic (True, False, Unknown); `IS NULL` vs `= NULL` (which always evaluates to Unknown).
  - `5.11.4` Filtering grouped data: `WHERE` (filters rows before aggregation) vs `HAVING` (filters groups after aggregation).
- **Key Failure Modes & Edge Cases**: Writing `WHERE col = NULL` instead of `IS NULL`, causing queries to silently return zero rows.
- **Verification & Mastery Check**: Demonstrate how three-valued logic produces counter-intuitive results in `NOT IN` subqueries containing nulls.
- **Project Application**: SchemaVault: Raw SQL queries.', '{"solution.py": "# Phase 5 // Lesson 5.11: SQL Execution Order & Core Dialect Mechanics\n\ndef solve():\n    \"\"\"\n    Verification: Demonstrate how three-valued logic produces counter-intuitive results in `NOT IN` subqueries contain\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.11", "subtopics_count": 4, "verification_criteria": "Demonstrate how three-valued logic produces counter-intuitive results in `NOT IN` subqueries containing nulls.", "subtopics": ["5.11.1 SQL physical processing order: `FROM` $\to$ `JOIN` $\to$ `WHERE` $\to$ `GROUP BY` $\to$ `HAVING` $\to$ `SELECT` $\to$ `DISTINCT` $\to$ `ORDER BY` $\to$ `LIMIT`.", "5.11.2 Why column aliases defined in `SELECT` cannot be referenced in `WHERE` clauses.", "5.11.3 NULL semantics: Three-Valued Logic (True, False, Unknown); `IS NULL` vs `= NULL` (which always evaluates to Unknown).", "5.11.4 Filtering grouped data: `WHERE` (filters rows before aggregation) vs `HAVING` (filters groups after aggregation)."]}'::jsonb, '["Explain how this implementation prevents: Writing `WHERE col = NULL` instead of `IS NULL`, causing queries to silently return zero rows.", "How does SQL Execution Order & Core Dialect Mechanics scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-12', 'phase-05-lesson-12-joins-deep-dive-inner-outer-cross-self-jo', 'module-7', 12, 'Lesson 7.12: Joins Deep Dive: Inner, Outer, Cross, & Self Joins', 'Prerequisites: Lesson 5.11', 'Prerequisites: Lesson 5.11 | Subtopics: 6 items', 'Systems project application', 200, 6, 1250.0, 600.0, '# Lesson 5.12: Joins Deep Dive: Inner, Outer, Cross, & Self Joins

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.11
- **Subtopics**:
  - `5.12.1` Join mechanics: combining rows from two or more tables based on join predicates.
  - `5.12.2` `INNER JOIN`: intersection of matching rows.
  - `5.12.3` `LEFT OUTER JOIN` / `RIGHT OUTER JOIN`: preserving unmatched rows from left/right table with null-padding.
  - `5.12.4` `FULL OUTER JOIN`: union of matches and un-matches from both tables.
  - `5.12.5` `CROSS JOIN`: Cartesian product ($M 	imes N$ rows); generating test permutations.
  - `5.12.6` Self-Joins: joining a table to itself for hierarchical parent-child relationships.
- **Key Failure Modes & Edge Cases**: Accidental Cartesian explosion: missing join predicates in multi-table queries producing millions of unwanted rows.
- **Verification & Mastery Check**: Write a self-join query that identifies employees who earn more than their direct managers in a single query.
- **Project Application**: DataSift and SchemaVault.', '{"solution.py": "# Phase 5 // Lesson 5.12: Joins Deep Dive: Inner, Outer, Cross, & Self Joins\n\ndef solve():\n    \"\"\"\n    Verification: Write a self-join query that identifies employees who earn more than their direct managers in a sing\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.12", "subtopics_count": 6, "verification_criteria": "Write a self-join query that identifies employees who earn more than their direct managers in a single query.", "subtopics": ["5.12.1 Join mechanics: combining rows from two or more tables based on join predicates.", "5.12.2 `INNER JOIN`: intersection of matching rows.", "5.12.3 `LEFT OUTER JOIN` / `RIGHT OUTER JOIN`: preserving unmatched rows from left/right table with null-padding.", "5.12.4 `FULL OUTER JOIN`: union of matches and un-matches from both tables.", "5.12.5 `CROSS JOIN`: Cartesian product ($M \times N$ rows); generating test permutations.", "5.12.6 Self-Joins: joining a table to itself for hierarchical parent-child relationships."]}'::jsonb, '["Explain how this implementation prevents: Accidental Cartesian explosion: missing join predicates in multi-table queries producing millions of unwanted rows.", "How does Joins Deep Dive: Inner, Outer, Cross, & Self Joins scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-13', 'phase-05-lesson-13-subqueries-correlated-scalar-set-membersh', 'module-7', 13, 'Lesson 7.13: Subqueries: Correlated, Scalar, & Set Membership', 'Prerequisites: Lesson 5.12', 'Prerequisites: Lesson 5.12 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 650.0, '# Lesson 5.13: Subqueries: Correlated, Scalar, & Set Membership

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.12
- **Subtopics**:
  - `5.13.1` Scalar Subqueries: subqueries returning a single row and single column for use in expressions.
  - `5.13.2` Subqueries in `FROM` clauses (Derived Tables): aliasing and materialization.
  - `5.13.3` `IN` vs `EXISTS`: why `EXISTS` short-circuits upon finding the first matching row.
  - `5.13.4` Correlated Subqueries: subqueries referencing columns from the outer query; row-by-row execution penalties.
- **Key Failure Modes & Edge Cases**: Using correlated subqueries inside `SELECT` lists across 100,000 rows, forcing 100,000 separate subquery executions.
- **Verification & Mastery Check**: Refactor an inefficient correlated subquery into a set-based `JOIN` with aggregation, measuring query speedup.
- **Project Application**: SchemaVault: Database migration queries.', '{"solution.py": "# Phase 5 // Lesson 5.13: Subqueries: Correlated, Scalar, & Set Membership\n\ndef solve():\n    \"\"\"\n    Verification: Refactor an inefficient correlated subquery into a set-based `JOIN` with aggregation, measuring quer\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.13", "subtopics_count": 4, "verification_criteria": "Refactor an inefficient correlated subquery into a set-based `JOIN` with aggregation, measuring query speedup.", "subtopics": ["5.13.1 Scalar Subqueries: subqueries returning a single row and single column for use in expressions.", "5.13.2 Subqueries in `FROM` clauses (Derived Tables): aliasing and materialization.", "5.13.3 `IN` vs `EXISTS`: why `EXISTS` short-circuits upon finding the first matching row.", "5.13.4 Correlated Subqueries: subqueries referencing columns from the outer query; row-by-row execution penalties."]}'::jsonb, '["Explain how this implementation prevents: Using correlated subqueries inside `SELECT` lists across 100,000 rows, forcing 100,000 separate subquery executions.", "How does Subqueries: Correlated, Scalar, & Set Membership scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-14', 'phase-05-lesson-14-data-manipulation-language-dml-upserts-re', 'module-7', 14, 'Lesson 7.14: Data Manipulation Language (DML): Upserts & RETURNING', 'Prerequisites: Lesson 5.11', 'Prerequisites: Lesson 5.11 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 700.0, '# Lesson 5.14: Data Manipulation Language (DML): Upserts & RETURNING

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.11
- **Subtopics**:
  - `5.14.1` Atomic Upserts: `INSERT ... ON CONFLICT (id) DO UPDATE SET ...`.
  - `5.14.2` `ON CONFLICT DO NOTHING`: idempotent insertion patterns.
  - `5.14.3` The `RETURNING` clause: returning modified rows (`RETURNING id, created_at`) without issuing secondary queries.
  - `5.14.4` Multi-row batch inserts: parameterized batch syntax to maximize database throughput.
- **Key Failure Modes & Edge Cases**: Performing check-then-insert operations in separate application statements, introducing race conditions under concurrency.
- **Verification & Mastery Check**: Write an atomic batch upsert query in PostgreSQL using `ON CONFLICT` and `RETURNING`.
- **Project Application**: AuthForge: User profile upserts.', '{"solution.py": "# Phase 5 // Lesson 5.14: Data Manipulation Language (DML): Upserts & RETURNING\n\ndef solve():\n    \"\"\"\n    Verification: Write an atomic batch upsert query in PostgreSQL using `ON CONFLICT` and `RETURNING`.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.14", "subtopics_count": 4, "verification_criteria": "Write an atomic batch upsert query in PostgreSQL using `ON CONFLICT` and `RETURNING`.", "subtopics": ["5.14.1 Atomic Upserts: `INSERT ... ON CONFLICT (id) DO UPDATE SET ...`.", "5.14.2 `ON CONFLICT DO NOTHING`: idempotent insertion patterns.", "5.14.3 The `RETURNING` clause: returning modified rows (`RETURNING id, created_at`) without issuing secondary queries.", "5.14.4 Multi-row batch inserts: parameterized batch syntax to maximize database throughput."]}'::jsonb, '["Explain how this implementation prevents: Performing check-then-insert operations in separate application statements, introducing race conditions under concurrenc", "How does Data Manipulation Language (DML): Upserts & RETURNING scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-15', 'phase-05-lesson-15-data-definition-language-ddl-constraints-', 'module-7', 15, 'Lesson 7.15: Data Definition Language (DDL): Constraints & Alter Table', 'Prerequisites: Lesson 5.9', 'Prerequisites: Lesson 5.9 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 750.0, '# Lesson 5.15: Data Definition Language (DDL): Constraints & Alter Table

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.9
- **Subtopics**:
  - `5.15.1` Integrity constraints: `PRIMARY KEY`, `FOREIGN KEY` (referential integrity), `UNIQUE`, `CHECK`, `NOT NULL`.
  - `5.15.2` Foreign key cascade options: `ON DELETE CASCADE`, `ON DELETE SET NULL`, `ON DELETE RESTRICT`.
  - `5.15.3` Zero-downtime schema changes: adding nullable columns vs columns with default values.
  - `5.15.4` PostgreSQL Table Locks during `ALTER TABLE`: avoiding exclusive `ACCESS EXCLUSIVE` table locks in production.
- **Key Failure Modes & Edge Cases**: Adding a column with a dynamic default value on a 50M-row table, taking an exclusive lock and freezing web traffic for minutes.
- **Verification & Mastery Check**: Execute a zero-downtime migration in PostgreSQL that safely adds a column with default values to an active table.
- **Project Application**: SchemaVault: Core migration tool features.', '{"solution.py": "# Phase 5 // Lesson 5.15: Data Definition Language (DDL): Constraints & Alter Table\n\ndef solve():\n    \"\"\"\n    Verification: Execute a zero-downtime migration in PostgreSQL that safely adds a column with default values to an \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.15", "subtopics_count": 4, "verification_criteria": "Execute a zero-downtime migration in PostgreSQL that safely adds a column with default values to an active table.", "subtopics": ["5.15.1 Integrity constraints: `PRIMARY KEY`, `FOREIGN KEY` (referential integrity), `UNIQUE`, `CHECK`, `NOT NULL`.", "5.15.2 Foreign key cascade options: `ON DELETE CASCADE`, `ON DELETE SET NULL`, `ON DELETE RESTRICT`.", "5.15.3 Zero-downtime schema changes: adding nullable columns vs columns with default values.", "5.15.4 PostgreSQL Table Locks during `ALTER TABLE`: avoiding exclusive `ACCESS EXCLUSIVE` table locks in production."]}'::jsonb, '["Explain how this implementation prevents: Adding a column with a dynamic default value on a 50M-row table, taking an exclusive lock and freezing web traffic for m", "How does Data Definition Language (DDL): Constraints & Alter Table scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-16', 'phase-05-lesson-16-postgresql-power-features-jsonb-arrays-tr', 'module-7', 16, 'Lesson 7.16: PostgreSQL Power Features: JSONB, Arrays, & Trigrams', 'Prerequisites: Lesson 5.15', 'Prerequisites: Lesson 5.15 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 800.0, '# Lesson 5.16: PostgreSQL Power Features: JSONB, Arrays, & Trigrams

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.15
- **Subtopics**:
  - `5.16.1` `JSONB` datatype: binary-format indexed JSON storage; containment operators (`@>`), key extraction (`->`, `->>`).
  - `5.16.2` Indexing JSONB: GIN (Generalized Inverted Index) for fast key/value queries on unstructured attributes.
  - `5.16.3` PostgreSQL native Arrays: `text[]`, `integer[]`, array containment (`&&`, `@>`).
  - `5.16.4` Fuzzy text search with `pg_trgm`: trigram matching and GIN/GiST similarity queries (`%` operator).
- **Key Failure Modes & Edge Cases**: Using `JSON` instead of `JSONB`, losing binary compression and forcing re-parsing on every query.
- **Verification & Mastery Check**: Build a fuzzy product search query using `pg_trgm` that handles misspellings on an indexed million-row table.
- **Project Application**: DocuMind and TenantIQ.', '{"solution.py": "# Phase 5 // Lesson 5.16: PostgreSQL Power Features: JSONB, Arrays, & Trigrams\n\ndef solve():\n    \"\"\"\n    Verification: Build a fuzzy product search query using `pg_trgm` that handles misspellings on an indexed million-r\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.16", "subtopics_count": 4, "verification_criteria": "Build a fuzzy product search query using `pg_trgm` that handles misspellings on an indexed million-row table.", "subtopics": ["5.16.1 `JSONB` datatype: binary-format indexed JSON storage; containment operators (`@>`), key extraction (`->`, `->>`).", "5.16.2 Indexing JSONB: GIN (Generalized Inverted Index) for fast key/value queries on unstructured attributes.", "5.16.3 PostgreSQL native Arrays: `text[]`, `integer[]`, array containment (`&&`, `@>`).", "5.16.4 Fuzzy text search with `pg_trgm`: trigram matching and GIN/GiST similarity queries (`%` operator)."]}'::jsonb, '["Explain how this implementation prevents: Using `JSON` instead of `JSONB`, losing binary compression and forcing re-parsing on every query.", "How does PostgreSQL Power Features: JSONB, Arrays, & Trigrams scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-17', 'phase-05-lesson-17-window-functions-foundations-partitions-o', 'module-7', 17, 'Lesson 7.17: Window Functions Foundations: Partitions & Ordering', 'Prerequisites: Lesson 5.11', 'Prerequisites: Lesson 5.11 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 850.0, '# Lesson 5.17: Window Functions Foundations: Partitions & Ordering

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.11
- **Subtopics**:
  - `5.17.1` The Window Function concept: computing row-level analytics across subsets without collapsing rows via `GROUP BY`.
  - `5.17.2` The `OVER()` clause: `PARTITION BY` (segmenting data) and `ORDER BY` (establishing evaluation sequence).
  - `5.17.3` Aggregate window functions: `SUM() OVER(...)`, `AVG() OVER(...)`, `COUNT() OVER(...)`.
  - `5.17.4` Mixing row attributes with group aggregates in a single query pass.
- **Key Failure Modes & Edge Cases**: Confusing `PARTITION BY` in window functions with `GROUP BY`, expecting rows to collapse.
- **Verification & Mastery Check**: Write a query calculating each transaction''s percentage contribution to its user''s total monthly spend.
- **Project Application**: TenantIQ: DORA metrics calculation.', '{"solution.py": "# Phase 5 // Lesson 5.17: Window Functions Foundations: Partitions & Ordering\n\ndef solve():\n    \"\"\"\n    Verification: Write a query calculating each transaction''s percentage contribution to its user''s total monthly spe\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.17", "subtopics_count": 4, "verification_criteria": "Write a query calculating each transaction''s percentage contribution to its user''s total monthly spend.", "subtopics": ["5.17.1 The Window Function concept: computing row-level analytics across subsets without collapsing rows via `GROUP BY`.", "5.17.2 The `OVER()` clause: `PARTITION BY` (segmenting data) and `ORDER BY` (establishing evaluation sequence).", "5.17.3 Aggregate window functions: `SUM() OVER(...)`, `AVG() OVER(...)`, `COUNT() OVER(...)`.", "5.17.4 Mixing row attributes with group aggregates in a single query pass."]}'::jsonb, '["Explain how this implementation prevents: Confusing `PARTITION BY` in window functions with `GROUP BY`, expecting rows to collapse.", "How does Window Functions Foundations: Partitions & Ordering scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-18', 'phase-05-lesson-18-ranking-window-functions-row-number-rank-', 'module-7', 18, 'Lesson 7.18: Ranking Window Functions: `ROW_NUMBER`, `RANK`, `DENSE_RANK`', 'Prerequisites: Lesson 5.17', 'Prerequisites: Lesson 5.17 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 900.0, '# Lesson 5.18: Ranking Window Functions: `ROW_NUMBER`, `RANK`, `DENSE_RANK`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.17
- **Subtopics**:
  - `5.18.1` `ROW_NUMBER()`: sequential integer assigned to each row within partition, breaking ties deterministically.
  - `5.18.2` `RANK()`: assigns identical rank to tied values, skipping subsequent ranks (1, 2, 2, 4).
  - `5.18.3` `DENSE_RANK()`: assigns identical rank to tied values without skipping subsequent ranks (1, 2, 2, 3).
  - `5.18.4` `NTILE(n)`: dividing partitions into $n$ equal frequency buckets (percentiles, quartiles).
- **Key Failure Modes & Edge Cases**: Using `ROW_NUMBER` for leaderboards where ties exist, arbitrarily ranking tied users differently without deterministic secondary sorts.
- **Verification & Mastery Check**: Write a query that extracts the top 3 highest spending customers per region using `DENSE_RANK()`.
- **Project Application**: DataSift: Top-N analysis.', '{"solution.py": "# Phase 5 // Lesson 5.18: Ranking Window Functions: `ROW_NUMBER`, `RANK`, `DENSE_RANK`\n\ndef solve():\n    \"\"\"\n    Verification: Write a query that extracts the top 3 highest spending customers per region using `DENSE_RANK()`.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.18", "subtopics_count": 4, "verification_criteria": "Write a query that extracts the top 3 highest spending customers per region using `DENSE_RANK()`.", "subtopics": ["5.18.1 `ROW_NUMBER()`: sequential integer assigned to each row within partition, breaking ties deterministically.", "5.18.2 `RANK()`: assigns identical rank to tied values, skipping subsequent ranks (1, 2, 2, 4).", "5.18.3 `DENSE_RANK()`: assigns identical rank to tied values without skipping subsequent ranks (1, 2, 2, 3).", "5.18.4 `NTILE(n)`: dividing partitions into $n$ equal frequency buckets (percentiles, quartiles)."]}'::jsonb, '["Explain how this implementation prevents: Using `ROW_NUMBER` for leaderboards where ties exist, arbitrarily ranking tied users differently without deterministic s", "How does Ranking Window Functions: `ROW_NUMBER`, `RANK`, `DENSE_RANK` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-19', 'phase-05-lesson-19-value-window-functions-lag-lead-offsets', 'module-7', 19, 'Lesson 7.19: Value Window Functions: `LAG`, `LEAD`, & Offsets', 'Prerequisites: Lesson 5.17', 'Prerequisites: Lesson 5.17 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 950.0, '# Lesson 5.19: Value Window Functions: `LAG`, `LEAD`, & Offsets

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.17
- **Subtopics**:
  - `5.19.1` `LAG(col, offset, default)`: accessing values from preceding rows within partition.
  - `5.19.2` `LEAD(col, offset, default)`: accessing values from subsequent rows within partition.
  - `5.19.3` `FIRST_VALUE()` and `LAST_VALUE()`: boundary value retrieval.
  - `5.19.4` Period-over-period calculations: computing day-over-day growth rates and time elapsed between user events.
- **Key Failure Modes & Edge Cases**: Calling `LAST_VALUE()` with default window framing, returning current row value instead of true partition end.
- **Verification & Mastery Check**: Calculate the time delta in minutes between consecutive user login events across a dataset using `LAG()`.
- **Project Application**: TenantIQ: Lead Time for Changes calculation.', '{"solution.py": "# Phase 5 // Lesson 5.19: Value Window Functions: `LAG`, `LEAD`, & Offsets\n\ndef solve():\n    \"\"\"\n    Verification: Calculate the time delta in minutes between consecutive user login events across a dataset using `LA\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.19", "subtopics_count": 4, "verification_criteria": "Calculate the time delta in minutes between consecutive user login events across a dataset using `LAG()`.", "subtopics": ["5.19.1 `LAG(col, offset, default)`: accessing values from preceding rows within partition.", "5.19.2 `LEAD(col, offset, default)`: accessing values from subsequent rows within partition.", "5.19.3 `FIRST_VALUE()` and `LAST_VALUE()`: boundary value retrieval.", "5.19.4 Period-over-period calculations: computing day-over-day growth rates and time elapsed between user events."]}'::jsonb, '["Explain how this implementation prevents: Calling `LAST_VALUE()` with default window framing, returning current row value instead of true partition end.", "How does Value Window Functions: `LAG`, `LEAD`, & Offsets scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-20', 'phase-05-lesson-20-window-framing-physical-rows-vs-logical-r', 'module-7', 20, 'Lesson 7.20: Window Framing: Physical Rows vs Logical Ranges', 'Prerequisites: Lesson 5.17', 'Prerequisites: Lesson 5.17 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 1000.0, '# Lesson 5.20: Window Framing: Physical Rows vs Logical Ranges

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.17
- **Subtopics**:
  - `5.20.1` The Window Frame: specifying exact sliding row subsets within the ordered partition.
  - `5.20.2` `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`: cumulative running totals.
  - `5.20.3` `ROWS BETWEEN 6 PRECEDING AND CURRENT ROW`: 7-day rolling moving averages.
  - `5.20.4` `RANGE` framing: evaluating offsets based on logical value differences rather than physical row counts.
- **Key Failure Modes & Edge Cases**: Omitting explicit window framing on `ORDER BY` window queries, triggering default framing that degrades query speed.
- **Verification & Mastery Check**: Implement a 30-day moving average and a cumulative sum of daily active users in a single SQL query.
- **Project Application**: TenantIQ: DORA metrics rolling averages.', '{"solution.py": "# Phase 5 // Lesson 5.20: Window Framing: Physical Rows vs Logical Ranges\n\ndef solve():\n    \"\"\"\n    Verification: Implement a 30-day moving average and a cumulative sum of daily active users in a single SQL query.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.20", "subtopics_count": 4, "verification_criteria": "Implement a 30-day moving average and a cumulative sum of daily active users in a single SQL query.", "subtopics": ["5.20.1 The Window Frame: specifying exact sliding row subsets within the ordered partition.", "5.20.2 `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`: cumulative running totals.", "5.20.3 `ROWS BETWEEN 6 PRECEDING AND CURRENT ROW`: 7-day rolling moving averages.", "5.20.4 `RANGE` framing: evaluating offsets based on logical value differences rather than physical row counts."]}'::jsonb, '["Explain how this implementation prevents: Omitting explicit window framing on `ORDER BY` window queries, triggering default framing that degrades query speed.", "How does Window Framing: Physical Rows vs Logical Ranges scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-21', 'phase-05-lesson-21-common-table-expressions-ctes-clean-query', 'module-7', 21, 'Lesson 7.21: Common Table Expressions (CTEs): Clean Query Pipelines', 'Prerequisites: Lesson 5.11', 'Prerequisites: Lesson 5.11 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 1050.0, '# Lesson 5.21: Common Table Expressions (CTEs): Clean Query Pipelines

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.11
- **Subtopics**:
  - `5.21.1` The CTE syntax: `WITH cte_name AS (SELECT ...) SELECT ... FROM cte_name`.
  - `5.21.2` Query readability: breaking massive, unmaintainable subquery joins into step-by-step readable modules.
  - `5.21.3` PostgreSQL CTE Optimization: `AS MATERIALIZED` vs `AS NOT MATERIALIZED` (inlined query pushdown).
  - `5.21.4` Multiple CTE chaining: composing multi-stage transformation pipelines.
- **Key Failure Modes & Edge Cases**: Accidental materialization fences in older PostgreSQL versions preventing index pushdown predicates into CTEs.
- **Verification & Mastery Check**: Refactor an unreadable 4-level nested subquery into a clean 3-stage CTE pipeline.
- **Project Application**: SchemaVault and TenantIQ.', '{"solution.py": "# Phase 5 // Lesson 5.21: Common Table Expressions (CTEs): Clean Query Pipelines\n\ndef solve():\n    \"\"\"\n    Verification: Refactor an unreadable 4-level nested subquery into a clean 3-stage CTE pipeline.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.21", "subtopics_count": 4, "verification_criteria": "Refactor an unreadable 4-level nested subquery into a clean 3-stage CTE pipeline.", "subtopics": ["5.21.1 The CTE syntax: `WITH cte_name AS (SELECT ...) SELECT ... FROM cte_name`.", "5.21.2 Query readability: breaking massive, unmaintainable subquery joins into step-by-step readable modules.", "5.21.3 PostgreSQL CTE Optimization: `AS MATERIALIZED` vs `AS NOT MATERIALIZED` (inlined query pushdown).", "5.21.4 Multiple CTE chaining: composing multi-stage transformation pipelines."]}'::jsonb, '["Explain how this implementation prevents: Accidental materialization fences in older PostgreSQL versions preventing index pushdown predicates into CTEs.", "How does Common Table Expressions (CTEs): Clean Query Pipelines scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-22', 'phase-05-lesson-22-recursive-ctes-hierarchies-trees-graphs-i', 'module-7', 22, 'Lesson 7.22: Recursive CTEs: Hierarchies, Trees, & Graphs in SQL', 'Prerequisites: Lesson 5.21', 'Prerequisites: Lesson 5.21 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 1100.0, '# Lesson 5.22: Recursive CTEs: Hierarchies, Trees, & Graphs in SQL

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.21
- **Subtopics**:
  - `5.22.1` Recursive CTE architecture: `WITH RECURSIVE`; Anchor member $	o$ `UNION ALL` $	o$ Recursive member.
  - `5.22.2` Termination conditions: recursion halting when recursive member returns zero rows.
  - `5.22.3` Tree traversal in SQL: calculating node depth, path strings, and subtree aggregations (org charts, categories).
  - `5.22.4` Cycle prevention: tracking visited node arrays (`ARRAY[id]`) to prevent infinite recursion on cyclic graphs.
- **Key Failure Modes & Edge Cases**: Infinite recursion in recursive CTEs caused by cyclic graph data, crashing database backends via memory exhaustion.
- **Verification & Mastery Check**: Write a recursive CTE that traverses a category hierarchy of arbitrary depth and outputs the full breadcrumb path for every node.
- **Project Application**: TenantIQ: Team and organization permission hierarchy.', '{"solution.py": "# Phase 5 // Lesson 5.22: Recursive CTEs: Hierarchies, Trees, & Graphs in SQL\n\ndef solve():\n    \"\"\"\n    Verification: Write a recursive CTE that traverses a category hierarchy of arbitrary depth and outputs the full br\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.22", "subtopics_count": 4, "verification_criteria": "Write a recursive CTE that traverses a category hierarchy of arbitrary depth and outputs the full breadcrumb path for every node.", "subtopics": ["5.22.1 Recursive CTE architecture: `WITH RECURSIVE`; Anchor member $\to$ `UNION ALL` $\to$ Recursive member.", "5.22.2 Termination conditions: recursion halting when recursive member returns zero rows.", "5.22.3 Tree traversal in SQL: calculating node depth, path strings, and subtree aggregations (org charts, categories).", "5.22.4 Cycle prevention: tracking visited node arrays (`ARRAY[id]`) to prevent infinite recursion on cyclic graphs."]}'::jsonb, '["Explain how this implementation prevents: Infinite recursion in recursive CTEs caused by cyclic graph data, crashing database backends via memory exhaustion.", "How does Recursive CTEs: Hierarchies, Trees, & Graphs in SQL scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-23', 'phase-05-lesson-23-postgresql-physical-storage-heap-files-pa', 'module-7', 23, 'Lesson 7.23: PostgreSQL Physical Storage: Heap Files, Pages, & Tuples', 'Prerequisites: Phase 0 (Lesson 0.9)', 'Prerequisites: Phase 0 (Lesson 0.9) | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 1150.0, '# Lesson 5.23: PostgreSQL Physical Storage: Heap Files, Pages, & Tuples

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.9)
- **Subtopics**:
  - `5.23.1` Database Cluster architecture: Database $	o$ Tablespace $	o$ Relational File $	o$ 8KB Pages.
  - `5.23.2` Page anatomy: Page Header (24 bytes), Item Identifiers (Line Pointers), Free Space, Tuple Data.
  - `5.23.3` The Tuple ID (`ctid`): physical address identifier `(block_number, offset_number)`.
  - `5.23.4` Heap-Only Tuples (HOT): updating tuples within the same 8KB page without modifying index pointers.
- **Key Failure Modes & Edge Cases**: Assuming database rows are stored contiguously on disk in primary key order (PostgreSQL uses un-ordered heap files).
- **Verification & Mastery Check**: Inspect raw tuple headers and `ctid` pointers using the `pageinspect` PostgreSQL extension.
- **Project Application**: Database internals mastery.', '{"solution.py": "# Phase 5 // Lesson 5.23: PostgreSQL Physical Storage: Heap Files, Pages, & Tuples\n\ndef solve():\n    \"\"\"\n    Verification: Inspect raw tuple headers and `ctid` pointers using the `pageinspect` PostgreSQL extension.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.23", "subtopics_count": 4, "verification_criteria": "Inspect raw tuple headers and `ctid` pointers using the `pageinspect` PostgreSQL extension.", "subtopics": ["5.23.1 Database Cluster architecture: Database $\to$ Tablespace $\to$ Relational File $\to$ 8KB Pages.", "5.23.2 Page anatomy: Page Header (24 bytes), Item Identifiers (Line Pointers), Free Space, Tuple Data.", "5.23.3 The Tuple ID (`ctid`): physical address identifier `(block_number, offset_number)`.", "5.23.4 Heap-Only Tuples (HOT): updating tuples within the same 8KB page without modifying index pointers."]}'::jsonb, '["Explain how this implementation prevents: Assuming database rows are stored contiguously on disk in primary key order (PostgreSQL uses un-ordered heap files).", "How does PostgreSQL Physical Storage: Heap Files, Pages, & Tuples scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-24', 'phase-05-lesson-24-b-tree-index-architecture-search-depth', 'module-7', 24, 'Lesson 7.24: B-Tree Index Architecture & Search Depth', 'Prerequisites: Phase 3 (Lesson 3.15), Lesson 5.23', 'Prerequisites: Phase 3 (Lesson 3.15), Lesson 5.23 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 1200.0, '# Lesson 5.24: B-Tree Index Architecture & Search Depth

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3 (Lesson 3.15), Lesson 5.23
- **Subtopics**:
  - `5.24.1` B-Tree index structure in PostgreSQL: Metapage, Root page, Internal branch pages, Leaf pages.
  - `5.24.2` High Fan-Out: each 8KB index page storing hundreds of keys; logarithmic search depth ($O(\log n)$, depth 3 for 10M rows).
  - `5.24.3` Leaf page structure: sorted keys and pointer arrays to heap `ctid` entries; bidirectional sibling pointers.
  - `5.24.4` Index Traversal: traversing from root to leaf to obtain `ctid`, then fetching physical page from heap.
- **Key Failure Modes & Edge Cases**: Creating single-column indexes on every table column, multiplying write amplification without aiding composite queries.
- **Verification & Mastery Check**: Calculate the exact B-Tree depth and page count for a table with 50 million 64-bit integer records.
- **Project Application**: SchemaVault: Index design.', '{"solution.py": "# Phase 5 // Lesson 5.24: B-Tree Index Architecture & Search Depth\n\ndef solve():\n    \"\"\"\n    Verification: Calculate the exact B-Tree depth and page count for a table with 50 million 64-bit integer records.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.24", "subtopics_count": 4, "verification_criteria": "Calculate the exact B-Tree depth and page count for a table with 50 million 64-bit integer records.", "subtopics": ["5.24.1 B-Tree index structure in PostgreSQL: Metapage, Root page, Internal branch pages, Leaf pages.", "5.24.2 High Fan-Out: each 8KB index page storing hundreds of keys; logarithmic search depth ($O(\\log n)$, depth 3 for 10M rows).", "5.24.3 Leaf page structure: sorted keys and pointer arrays to heap `ctid` entries; bidirectional sibling pointers.", "5.24.4 Index Traversal: traversing from root to leaf to obtain `ctid`, then fetching physical page from heap."]}'::jsonb, '["Explain how this implementation prevents: Creating single-column indexes on every table column, multiplying write amplification without aiding composite queries.", "How does B-Tree Index Architecture & Search Depth scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-25', 'phase-05-lesson-25-composite-indexes-the-leftmost-prefix-rul', 'module-7', 25, 'Lesson 7.25: Composite Indexes & The Leftmost Prefix Rule', 'Prerequisites: Lesson 5.24', 'Prerequisites: Lesson 5.24 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 1250.0, '# Lesson 5.25: Composite Indexes & The Leftmost Prefix Rule

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.24
- **Subtopics**:
  - `5.25.1` Composite Index structure: index on multiple columns `(tenant_id, status, created_at)`.
  - `5.25.2` The Leftmost Prefix Rule: an index on `(A, B, C)` accelerates queries on `A`, `(A, B)`, and `(A, B, C)`; useless for queries on `B` alone.
  - `5.25.3` Column ordering heuristics: placing equality columns first, followed by range/sort columns.
  - `5.25.4` Index Skip Scans: how modern engines emulate multi-column indexing across low-cardinality prefixes.
- **Key Failure Modes & Edge Cases**: Ordering composite index columns as `(created_at, tenant_id)`, rendering the index useless for queries filtering on `tenant_id` alone.
- **Verification & Mastery Check**: Design the optimal composite index for an API query filtering by tenant, filtering by date range, and sorting by ID.
- **Project Application**: TenantIQ: Composite metric indexes.', '{"solution.py": "# Phase 5 // Lesson 5.25: Composite Indexes & The Leftmost Prefix Rule\n\ndef solve():\n    \"\"\"\n    Verification: Design the optimal composite index for an API query filtering by tenant, filtering by date range, an\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.25", "subtopics_count": 4, "verification_criteria": "Design the optimal composite index for an API query filtering by tenant, filtering by date range, and sorting by ID.", "subtopics": ["5.25.1 Composite Index structure: index on multiple columns `(tenant_id, status, created_at)`.", "5.25.2 The Leftmost Prefix Rule: an index on `(A, B, C)` accelerates queries on `A`, `(A, B)`, and `(A, B, C)`; useless for queries on `B` alone.", "5.25.3 Column ordering heuristics: placing equality columns first, followed by range/sort columns.", "5.25.4 Index Skip Scans: how modern engines emulate multi-column indexing across low-cardinality prefixes."]}'::jsonb, '["Explain how this implementation prevents: Ordering composite index columns as `(created_at, tenant_id)`, rendering the index useless for queries filtering on `ten", "How does Composite Indexes & The Leftmost Prefix Rule scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
