INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-3-31', 'phase-03-lesson-31-memory-contiguity-cache-locality-in-data-', 'module-5', 31, 'Lesson 5.31: Memory Contiguity & Cache Locality in Data Structures', 'Prerequisites: Phase 0 (Lesson 0.6), Phase 2 (Lesson 2.11)', 'Prerequisites: Phase 0 (Lesson 0.6), Phase 2 (Lesson 2.11) | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1550.0, '# Lesson 3.31: Memory Contiguity & Cache Locality in Data Structures

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.6), Phase 2 (Lesson 2.11)
- **Subtopics**:
  - `3.31.1` Physical memory layouts: contiguous memory allocations vs node-pointer graph allocations.
  - `3.31.2` Cache line utilization: iterating contiguous arrays vs dereferencing scattered linked-list pointers.
  - `3.31.3` Memory overhead per element: 8 bytes for 64-bit int array vs 32+ bytes for linked-list node.
  - `3.31.4` Spatial prefetching in hardware: CPU prefetching contiguous memory blocks automatically.
- **Key Failure Modes & Edge Cases**: Assuming linked lists are faster than arrays for insertion without accounting for cache miss penalties.
- **Verification & Mastery Check**: Benchmark traversal time of 10,000,000 integers in a flat array vs a pointer-linked list, demonstrating a 20x delta.
- **Project Application**: DataSift: Chunk memory layout.', '{"solution.py": "# Phase 3 // Lesson 3.31: Memory Contiguity & Cache Locality in Data Structures\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark traversal time of 10,000,000 integers in a flat array vs a pointer-linked list, demonstrat\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.31", "subtopics_count": 4, "verification_criteria": "Benchmark traversal time of 10,000,000 integers in a flat array vs a pointer-linked list, demonstrating a 20x delta.", "subtopics": ["3.31.1 Physical memory layouts: contiguous memory allocations vs node-pointer graph allocations.", "3.31.2 Cache line utilization: iterating contiguous arrays vs dereferencing scattered linked-list pointers.", "3.31.3 Memory overhead per element: 8 bytes for 64-bit int array vs 32+ bytes for linked-list node.", "3.31.4 Spatial prefetching in hardware: CPU prefetching contiguous memory blocks automatically."]}'::jsonb, '["Explain how this implementation prevents: Assuming linked lists are faster than arrays for insertion without accounting for cache miss penalties.", "How does Memory Contiguity & Cache Locality in Data Structures scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-32', 'phase-03-lesson-32-dynamic-array-architecture-resizing-amort', 'module-5', 32, 'Lesson 5.32: Dynamic Array Architecture: Resizing & Amortized Analysis', 'Prerequisites: Lesson 3.31', 'Prerequisites: Lesson 3.31 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1600.0, '# Lesson 3.32: Dynamic Array Architecture: Resizing & Amortized Analysis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.31
- **Subtopics**:
  - `3.32.1` Dynamic array structure: pointer to contiguous heap buffer, capacity, length.
  - `3.32.2` The Resizing Strategy: allocating new buffer of size $k 	imes 	ext{capacity}$ and copying elements.
  - `3.32.3` Resize multiplier trade-offs: $2.0	imes$ vs $1.5	imes$ (reusing previously freed memory chunks).
  - `3.32.4` Amortized $O(1)$ proof: Aggregate method and Potential method proving constant average append time.
- **Key Failure Modes & Edge Cases**: Resizing with a constant additive increase ($	ext{capacity} + 1000$), degrading appends to quadratic $O(n^2)$ time.
- **Verification & Mastery Check**: Implement a dynamic array from scratch with a custom geometric growth factor and prove $O(1)$ amortized append.
- **Project Application**: DataSift: Dynamic accumulator buffers.', '{"solution.py": "# Phase 3 // Lesson 3.32: Dynamic Array Architecture: Resizing & Amortized Analysis\n\ndef solve():\n    \"\"\"\n    Verification: Implement a dynamic array from scratch with a custom geometric growth factor and prove $O(1)$ amorti\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.32", "subtopics_count": 4, "verification_criteria": "Implement a dynamic array from scratch with a custom geometric growth factor and prove $O(1)$ amortized append.", "subtopics": ["3.32.1 Dynamic array structure: pointer to contiguous heap buffer, capacity, length.", "3.32.2 The Resizing Strategy: allocating new buffer of size $k \times \text{capacity}$ and copying elements.", "3.32.3 Resize multiplier trade-offs: $2.0\times$ vs $1.5\times$ (reusing previously freed memory chunks).", "3.32.4 Amortized $O(1)$ proof: Aggregate method and Potential method proving constant average append time."]}'::jsonb, '["Explain how this implementation prevents: Resizing with a constant additive increase ($\text{capacity} + 1000$), degrading appends to quadratic $O(n^2)$ time.", "How does Dynamic Array Architecture: Resizing & Amortized Analysis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-33', 'phase-03-lesson-33-singly-linked-lists-pointer-manipulation-', 'module-5', 33, 'Lesson 5.33: Singly Linked Lists: Pointer Manipulation & Invariants', 'Prerequisites: Phase 1 (Lesson 1.1)', 'Prerequisites: Phase 1 (Lesson 1.1) | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1650.0, '# Lesson 3.33: Singly Linked Lists: Pointer Manipulation & Invariants

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.1)
- **Subtopics**:
  - `3.33.1` Node structure: payload value and pointer to next node.
  - `3.33.2` Insertion and deletion: head insertion ($O(1)$), tail insertion ($O(n)$ or $O(1)$ with tail pointer), arbitrary deletion ($O(n)$).
  - `3.33.3` Pointer manipulation discipline: maintaining invariants to avoid losing references to remaining list.
  - `3.33.4` The Sentinel / Dummy Node pattern: eliminating edge-case code for empty lists and head deletions.
- **Key Failure Modes & Edge Cases**: Losing the reference to `curr.next` before updating pointers, resulting in dangling memory and broken lists.
- **Verification & Mastery Check**: Implement a Singly Linked List with dummy head and prove zero memory leaks or lost nodes on edge cases.
- **Project Application**: LoxLang: Environment scope chains.', '{"solution.py": "# Phase 3 // Lesson 3.33: Singly Linked Lists: Pointer Manipulation & Invariants\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Singly Linked List with dummy head and prove zero memory leaks or lost nodes on edge cas\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.33", "subtopics_count": 4, "verification_criteria": "Implement a Singly Linked List with dummy head and prove zero memory leaks or lost nodes on edge cases.", "subtopics": ["3.33.1 Node structure: payload value and pointer to next node.", "3.33.2 Insertion and deletion: head insertion ($O(1)$), tail insertion ($O(n)$ or $O(1)$ with tail pointer), arbitrary deletion ($O(n)$).", "3.33.3 Pointer manipulation discipline: maintaining invariants to avoid losing references to remaining list.", "3.33.4 The Sentinel / Dummy Node pattern: eliminating edge-case code for empty lists and head deletions."]}'::jsonb, '["Explain how this implementation prevents: Losing the reference to `curr.next` before updating pointers, resulting in dangling memory and broken lists.", "How does Singly Linked Lists: Pointer Manipulation & Invariants scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-34', 'phase-03-lesson-34-doubly-linked-lists-sentinels', 'module-5', 34, 'Lesson 5.34: Doubly Linked Lists & Sentinels', 'Prerequisites: Lesson 3.33', 'Prerequisites: Lesson 3.33 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1700.0, '# Lesson 3.34: Doubly Linked Lists & Sentinels

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.33
- **Subtopics**:
  - `3.34.1` Node structure: payload, pointer to next node, pointer to previous node.
  - `3.34.2` Bidirectional traversal: traversing forward and backward.
  - `3.34.3` Constant-time node removal: deleting a known node reference in $O(1)$ without searching from head.
  - `3.34.4` Circular doubly linked lists with a single sentinel node: simplifying insertion and deletion logic.
- **Key Failure Modes & Edge Cases**: Failing to update `prev` pointers during node splicing, breaking backward traversals.
- **Verification & Mastery Check**: Implement a Doubly Linked List supporting $O(1)$ insertion and deletion at both ends and of arbitrary known nodes.
- **Project Application**: Phase 5: Foundation for CacheKit LRU cache.', '{"solution.py": "# Phase 3 // Lesson 3.34: Doubly Linked Lists & Sentinels\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Doubly Linked List supporting $O(1)$ insertion and deletion at both ends and of arbitrar\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.34", "subtopics_count": 4, "verification_criteria": "Implement a Doubly Linked List supporting $O(1)$ insertion and deletion at both ends and of arbitrary known nodes.", "subtopics": ["3.34.1 Node structure: payload, pointer to next node, pointer to previous node.", "3.34.2 Bidirectional traversal: traversing forward and backward.", "3.34.3 Constant-time node removal: deleting a known node reference in $O(1)$ without searching from head.", "3.34.4 Circular doubly linked lists with a single sentinel node: simplifying insertion and deletion logic."]}'::jsonb, '["Explain how this implementation prevents: Failing to update `prev` pointers during node splicing, breaking backward traversals.", "How does Doubly Linked Lists & Sentinels scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-35', 'phase-03-lesson-35-floyd-s-cycle-finding-algorithm-tortoise-', 'module-5', 35, 'Lesson 5.35: Floyd''s Cycle-Finding Algorithm (Tortoise and Hare)', 'Prerequisites: Lesson 3.33', 'Prerequisites: Lesson 3.33 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1750.0, '# Lesson 3.35: Floyd''s Cycle-Finding Algorithm (Tortoise and Hare)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.33
- **Subtopics**:
  - `3.35.1` The linked list cycle problem: detecting infinite loops in pointer structures.
  - `3.35.2` Two-pointer approach: Slow pointer (1 step) and Fast pointer (2 steps).
  - `3.35.3` Cycle detection proof: why fast and slow pointers must collide within the cycle in $O(n)$ time.
  - `3.35.4` Finding the cycle start node: resetting one pointer to head and advancing both by 1 step.
- **Key Failure Modes & Edge Cases**: Creating infinite loops in traversal routines when circular references exist in linked structures.
- **Verification & Mastery Check**: Implement Floyd''s cycle detection from memory and return the exact node where the cycle begins in $O(1)$ memory.
- **Project Application**: DevAudit: Cycle detection in linked imports.', '{"solution.py": "# Phase 3 // Lesson 3.35: Floyd''s Cycle-Finding Algorithm (Tortoise and Hare)\n\ndef solve():\n    \"\"\"\n    Verification: Implement Floyd''s cycle detection from memory and return the exact node where the cycle begins in $O\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.35", "subtopics_count": 4, "verification_criteria": "Implement Floyd''s cycle detection from memory and return the exact node where the cycle begins in $O(1)$ memory.", "subtopics": ["3.35.1 The linked list cycle problem: detecting infinite loops in pointer structures.", "3.35.2 Two-pointer approach: Slow pointer (1 step) and Fast pointer (2 steps).", "3.35.3 Cycle detection proof: why fast and slow pointers must collide within the cycle in $O(n)$ time.", "3.35.4 Finding the cycle start node: resetting one pointer to head and advancing both by 1 step."]}'::jsonb, '["Explain how this implementation prevents: Creating infinite loops in traversal routines when circular references exist in linked structures.", "How does Floyd''s Cycle-Finding Algorithm (Tortoise and Hare) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-36', 'phase-03-lesson-36-the-stack-abstract-data-type-array-vs-lin', 'module-5', 36, 'Lesson 5.36: The Stack Abstract Data Type: Array vs Linked Implementations', 'Prerequisites: Lesson 3.32, 3.3', 'Prerequisites: Lesson 3.32, 3.3 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1800.0, '# Lesson 3.36: The Stack Abstract Data Type: Array vs Linked Implementations

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.32, 3.3
- **Subtopics**:
  - `3.36.1` Stack LIFO (Last-In, First-Out) semantics: `push`, `pop`, `peek`, `is_empty`.
  - `3.36.2` Array-backed stack: memory contiguity, cache efficiency, amortized $O(1)$ push.
  - `3.36.3` Linked-list-backed stack: strict $O(1)$ worst-case push/pop, pointer memory overhead.
  - `3.36.4` Stack overflow and capacity limits in fixed-size hardware/virtual stacks.
- **Key Failure Modes & Edge Cases**: Calling `pop()` on an empty stack without bounds checks, causing index out-of-range crashes.
- **Verification & Mastery Check**: Implement a generic Stack supporting `push`, `pop`, and `min()` in constant $O(1)$ time and $O(n)$ space.
- **Project Application**: LoxLang: Expression evaluation stack.', '{"solution.py": "# Phase 3 // Lesson 3.36: The Stack Abstract Data Type: Array vs Linked Implementations\n\ndef solve():\n    \"\"\"\n    Verification: Implement a generic Stack supporting `push`, `pop`, and `min()` in constant $O(1)$ time and $O(n)$ s\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.36", "subtopics_count": 4, "verification_criteria": "Implement a generic Stack supporting `push`, `pop`, and `min()` in constant $O(1)$ time and $O(n)$ space.", "subtopics": ["3.36.1 Stack LIFO (Last-In, First-Out) semantics: `push`, `pop`, `peek`, `is_empty`.", "3.36.2 Array-backed stack: memory contiguity, cache efficiency, amortized $O(1)$ push.", "3.36.3 Linked-list-backed stack: strict $O(1)$ worst-case push/pop, pointer memory overhead.", "3.36.4 Stack overflow and capacity limits in fixed-size hardware/virtual stacks."]}'::jsonb, '["Explain how this implementation prevents: Calling `pop()` on an empty stack without bounds checks, causing index out-of-range crashes.", "How does The Stack Abstract Data Type: Array vs Linked Implementations scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-37', 'phase-03-lesson-37-the-queue-circular-buffer-deque', 'module-5', 37, 'Lesson 5.37: The Queue & Circular Buffer Deque', 'Prerequisites: Lesson 3.32', 'Prerequisites: Lesson 3.32 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1850.0, '# Lesson 3.37: The Queue & Circular Buffer Deque

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.32
- **Subtopics**:
  - `3.37.1` Queue FIFO (First-In, First-Out) semantics: `enqueue`, `dequeue`, `peek`.
  - `3.37.2` The flaw of naive array queues: `list.pop(0)` requiring $O(n)$ element shifts.
  - `3.37.3` Circular Buffer array queue: head pointer, tail pointer, modulo arithmetic (`(tail + 1) % capacity`).
  - `3.37.4` Double-Ended Queue (Deque): $O(1)$ insertions and removals at both head and tail.
- **Key Failure Modes & Edge Cases**: Using a standard Python list as a FIFO queue in high-throughput services, incurring massive $O(n)$ CPU penalties.
- **Verification & Mastery Check**: Implement a high-performance Circular Buffer Deque with zero element shifts passing all FIFO unit tests.
- **Project Application**: NanoHTTP: Request socket queues in Phase 4.', '{"solution.py": "# Phase 3 // Lesson 3.37: The Queue & Circular Buffer Deque\n\ndef solve():\n    \"\"\"\n    Verification: Implement a high-performance Circular Buffer Deque with zero element shifts passing all FIFO unit te\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.37", "subtopics_count": 4, "verification_criteria": "Implement a high-performance Circular Buffer Deque with zero element shifts passing all FIFO unit tests.", "subtopics": ["3.37.1 Queue FIFO (First-In, First-Out) semantics: `enqueue`, `dequeue`, `peek`.", "3.37.2 The flaw of naive array queues: `list.pop(0)` requiring $O(n)$ element shifts.", "3.37.3 Circular Buffer array queue: head pointer, tail pointer, modulo arithmetic (`(tail + 1) % capacity`).", "3.37.4 Double-Ended Queue (Deque): $O(1)$ insertions and removals at both head and tail."]}'::jsonb, '["Explain how this implementation prevents: Using a standard Python list as a FIFO queue in high-throughput services, incurring massive $O(n)$ CPU penalties.", "How does The Queue & Circular Buffer Deque scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-38', 'phase-03-lesson-38-hash-functions-uniformity-avalanche-rolli', 'module-5', 38, 'Lesson 5.38: Hash Functions: Uniformity, Avalanche, & Rolling Hashes', 'Prerequisites: Phase 2 (Lesson 2.1)', 'Prerequisites: Phase 2 (Lesson 2.1) | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1900.0, '# Lesson 3.38: Hash Functions: Uniformity, Avalanche, & Rolling Hashes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2 (Lesson 2.1)
- **Subtopics**:
  - `3.38.1` Hash function criteria: deterministic, uniform distribution across buckets, fast evaluation.
  - `3.38.2` The Avalanche Effect: a single bit change in input flips approximately 50% of output bits.
  - `3.38.3` Non-cryptographic hash functions: FNV-1a, MurmurHash3, CityHash, xxHash.
  - `3.38.4` Polynomial Rolling Hash for strings: $H = \sum s[i] \cdot p^i \pmod m$; sliding window string searches.
- **Key Failure Modes & Edge Cases**: Using trivial sum-of-characters hash functions, causing massive collision clusters on anagram strings.
- **Verification & Mastery Check**: Implement a polynomial rolling hash function and prove avalanche properties across single-character mutations.
- **Project Application**: DataSift: Fast string hashing.', '{"solution.py": "# Phase 3 // Lesson 3.38: Hash Functions: Uniformity, Avalanche, & Rolling Hashes\n\ndef solve():\n    \"\"\"\n    Verification: Implement a polynomial rolling hash function and prove avalanche properties across single-character \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.38", "subtopics_count": 4, "verification_criteria": "Implement a polynomial rolling hash function and prove avalanche properties across single-character mutations.", "subtopics": ["3.38.1 Hash function criteria: deterministic, uniform distribution across buckets, fast evaluation.", "3.38.2 The Avalanche Effect: a single bit change in input flips approximately 50% of output bits.", "3.38.3 Non-cryptographic hash functions: FNV-1a, MurmurHash3, CityHash, xxHash.", "3.38.4 Polynomial Rolling Hash for strings: $H = \\sum s[i] \\cdot p^i \\pmod m$; sliding window string searches."]}'::jsonb, '["Explain how this implementation prevents: Using trivial sum-of-characters hash functions, causing massive collision clusters on anagram strings.", "How does Hash Functions: Uniformity, Avalanche, & Rolling Hashes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-39', 'phase-03-lesson-39-hash-collision-resolution-separate-chaini', 'module-5', 39, 'Lesson 5.39: Hash Collision Resolution: Separate Chaining vs Open Addressing', 'Prerequisites: Lesson 3.38', 'Prerequisites: Lesson 3.38 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1950.0, '# Lesson 3.39: Hash Collision Resolution: Separate Chaining vs Open Addressing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.38
- **Subtopics**:
  - `3.39.1` The Birthday Paradox in hashing: collisions occur much earlier than capacity limit.
  - `3.39.2` Separate Chaining: bucket linked lists; worst-case degradation to $O(n)$ on adversarial keys.
  - `3.39.3` Open Addressing: storing all elements directly in the array; finding open slots via probing sequences.
  - `3.39.4` Load Factor ($lpha = n/k$): collision frequency scaling as load factor increases.
- **Key Failure Modes & Edge Cases**: Failing to resize a separate chaining hash map when load factor exceeds 1.0, degrading queries to linear scans.
- **Verification & Mastery Check**: Implement Separate Chaining with red-black tree bucket thresholding on collision chains.
- **Project Application**: DataSift: Key cardinality counting.', '{"solution.py": "# Phase 3 // Lesson 3.39: Hash Collision Resolution: Separate Chaining vs Open Addressing\n\ndef solve():\n    \"\"\"\n    Verification: Implement Separate Chaining with red-black tree bucket thresholding on collision chains.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.39", "subtopics_count": 4, "verification_criteria": "Implement Separate Chaining with red-black tree bucket thresholding on collision chains.", "subtopics": ["3.39.1 The Birthday Paradox in hashing: collisions occur much earlier than capacity limit.", "3.39.2 Separate Chaining: bucket linked lists; worst-case degradation to $O(n)$ on adversarial keys.", "3.39.3 Open Addressing: storing all elements directly in the array; finding open slots via probing sequences.", "3.39.4 Load Factor ($\u0007lpha = n/k$): collision frequency scaling as load factor increases."]}'::jsonb, '["Explain how this implementation prevents: Failing to resize a separate chaining hash map when load factor exceeds 1.0, degrading queries to linear scans.", "How does Hash Collision Resolution: Separate Chaining vs Open Addressing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-40', 'phase-03-lesson-40-open-addressing-linear-probing-quadratic-', 'module-5', 40, 'Lesson 5.40: Open Addressing: Linear Probing, Quadratic, & Double Hashing', 'Prerequisites: Lesson 3.39', 'Prerequisites: Lesson 3.39 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 2000.0, '# Lesson 3.40: Open Addressing: Linear Probing, Quadratic, & Double Hashing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.39
- **Subtopics**:
  - `3.40.1` Linear Probing: probing index $(h(k) + i) \pmod m$; primary clustering phenomena.
  - `3.40.2` Quadratic Probing: probing index $(h(k) + c_1 i + c_2 i^2) \pmod m$; secondary clustering.
  - `3.40.3` Double Hashing: probing index $(h_1(k) + i \cdot h_2(k)) \pmod m$; eliminating clustering.
  - `3.40.4` Tombstones for deletion: marking deleted slots as `TOMBSTONE` to preserve search probe chains.
- **Key Failure Modes & Edge Cases**: Failing to handle tombstones during deletion, prematurely terminating lookups for subsequent inserted keys.
- **Verification & Mastery Check**: Build an Open-Addressed hash table from scratch using double hashing and tombstone deletion.
- **Project Application**: DataSift: Core hash map.', '{"solution.py": "# Phase 3 // Lesson 3.40: Open Addressing: Linear Probing, Quadratic, & Double Hashing\n\ndef solve():\n    \"\"\"\n    Verification: Build an Open-Addressed hash table from scratch using double hashing and tombstone deletion.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.40", "subtopics_count": 4, "verification_criteria": "Build an Open-Addressed hash table from scratch using double hashing and tombstone deletion.", "subtopics": ["3.40.1 Linear Probing: probing index $(h(k) + i) \\pmod m$; primary clustering phenomena.", "3.40.2 Quadratic Probing: probing index $(h(k) + c_1 i + c_2 i^2) \\pmod m$; secondary clustering.", "3.40.3 Double Hashing: probing index $(h_1(k) + i \\cdot h_2(k)) \\pmod m$; eliminating clustering.", "3.40.4 Tombstones for deletion: marking deleted slots as `TOMBSTONE` to preserve search probe chains."]}'::jsonb, '["Explain how this implementation prevents: Failing to handle tombstones during deletion, prematurely terminating lookups for subsequent inserted keys.", "How does Open Addressing: Linear Probing, Quadratic, & Double Hashing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-41', 'phase-03-lesson-41-cpython-dict-architecture-compact-dict-pe', 'module-5', 41, 'Lesson 5.41: CPython `dict` Architecture: Compact Dict & Perturb Probing', 'Prerequisites: Lesson 3.40', 'Prerequisites: Lesson 3.40 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 2050.0, '# Lesson 3.41: CPython `dict` Architecture: Compact Dict & Perturb Probing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.40
- **Subtopics**:
  - `3.41.1` Historical Python dict memory layout: 24-byte entries containing sparse unallocated rows.
  - `3.41.2` Modern Compact Dict (PEP 468): dense `entries` array + sparse byte `indices` array; 30%–95% memory savings.
  - `3.41.3` CPython Perturb Probing formula: `j = ((5*j) + 1 + perturb) % m; perturb >>= 5`.
  - `3.41.4` Preserving insertion order: how compact dicts naturally make Python dictionaries ordered.
- **Key Failure Modes & Edge Cases**: Relying on dictionary insertion order in older runtime environments or cross-language serialization.
- **Verification & Mastery Check**: Implement a compact dictionary prototype matching CPython''s indices/entries array architecture.
- **Project Application**: DataSift: High-cardinality aggregation.', '{"solution.py": "# Phase 3 // Lesson 3.41: CPython `dict` Architecture: Compact Dict & Perturb Probing\n\ndef solve():\n    \"\"\"\n    Verification: Implement a compact dictionary prototype matching CPython''s indices/entries array architecture.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.41", "subtopics_count": 4, "verification_criteria": "Implement a compact dictionary prototype matching CPython''s indices/entries array architecture.", "subtopics": ["3.41.1 Historical Python dict memory layout: 24-byte entries containing sparse unallocated rows.", "3.41.2 Modern Compact Dict (PEP 468): dense `entries` array + sparse byte `indices` array; 30%\u201395% memory savings.", "3.41.3 CPython Perturb Probing formula: `j = ((5*j) + 1 + perturb) % m; perturb >>= 5`.", "3.41.4 Preserving insertion order: how compact dicts naturally make Python dictionaries ordered."]}'::jsonb, '["Explain how this implementation prevents: Relying on dictionary insertion order in older runtime environments or cross-language serialization.", "How does CPython `dict` Architecture: Compact Dict & Perturb Probing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-42', 'phase-03-lesson-42-bloom-filters-probabilistic-set-membershi', 'module-5', 42, 'Lesson 5.42: Bloom Filters & Probabilistic Set Membership', 'Prerequisites: Lesson 3.38', 'Prerequisites: Lesson 3.38 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 2100.0, '# Lesson 3.42: Bloom Filters & Probabilistic Set Membership

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.38
- **Subtopics**:
  - `3.42.1` The memory limit of exact hash sets: tracking billions of keys exceeding available physical RAM.
  - `3.42.2` Bloom Filter architecture: bit array of size $m$, $k$ independent hash functions.
  - `3.42.3` Operations: `add(key)` sets $k$ bits to 1; `contains(key)` checks if all $k$ bits are 1.
  - `3.42.4` Error bounds: zero false negatives guaranteed; mathematical false positive rate: $(1 - e^{-kn/m})^k$.
- **Key Failure Modes & Edge Cases**: Assuming a Bloom filter can confirm presence with 100% certainty (it only confirms *absence* with certainty).
- **Verification & Mastery Check**: Implement a Bloom Filter from scratch, calculate optimal $m$ and $k$ for 1M keys at 1% false positive rate, and empirically verify error rate.
- **Project Application**: Phase 8: Web crawler URL deduplication.', '{"solution.py": "# Phase 3 // Lesson 3.42: Bloom Filters & Probabilistic Set Membership\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Bloom Filter from scratch, calculate optimal $m$ and $k$ for 1M keys at 1% false positiv\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.42", "subtopics_count": 4, "verification_criteria": "Implement a Bloom Filter from scratch, calculate optimal $m$ and $k$ for 1M keys at 1% false positive rate, and empirically verify error rate.", "subtopics": ["3.42.1 The memory limit of exact hash sets: tracking billions of keys exceeding available physical RAM.", "3.42.2 Bloom Filter architecture: bit array of size $m$, $k$ independent hash functions.", "3.42.3 Operations: `add(key)` sets $k$ bits to 1; `contains(key)` checks if all $k$ bits are 1.", "3.42.4 Error bounds: zero false negatives guaranteed; mathematical false positive rate: $(1 - e^{-kn/m})^k$."]}'::jsonb, '["Explain how this implementation prevents: Assuming a Bloom filter can confirm presence with 100% certainty (it only confirms *absence* with certainty).", "How does Bloom Filters & Probabilistic Set Membership scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-43', 'phase-03-lesson-43-binary-trees-tree-traversals-depth-analys', 'module-5', 43, 'Lesson 5.43: Binary Trees: Tree Traversals & Depth Analysis', 'Prerequisites: Phase 2 (Lesson 2.8)', 'Prerequisites: Phase 2 (Lesson 2.8) | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 2150.0, '# Lesson 3.43: Binary Trees: Tree Traversals & Depth Analysis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2 (Lesson 2.8)
- **Subtopics**:
  - `3.43.1` Tree recursive definition: root node, left subtree, right subtree, leaves.
  - `3.43.2` Depth-First Traversals: Pre-order ($N-L-R$), In-order ($L-N-R$), Post-order ($L-R-N$); call stack visualization.
  - `3.43.3` Breadth-First Traversal (Level-order): queue-based level-by-level breadth exploration.
  - `3.43.4` Tree properties: height, depth, diameter, complete vs full vs degenerate trees.
- **Key Failure Modes & Edge Cases**: Unbounded recursion in tree traversals exceeding call stack limits on skewed, degenerate trees.
- **Verification & Mastery Check**: Implement all four tree traversals both recursively and iteratively using an explicit stack/queue.
- **Project Application**: LoxLang: AST traversals.', '{"solution.py": "# Phase 3 // Lesson 3.43: Binary Trees: Tree Traversals & Depth Analysis\n\ndef solve():\n    \"\"\"\n    Verification: Implement all four tree traversals both recursively and iteratively using an explicit stack/queue.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.43", "subtopics_count": 4, "verification_criteria": "Implement all four tree traversals both recursively and iteratively using an explicit stack/queue.", "subtopics": ["3.43.1 Tree recursive definition: root node, left subtree, right subtree, leaves.", "3.43.2 Depth-First Traversals: Pre-order ($N-L-R$), In-order ($L-N-R$), Post-order ($L-R-N$); call stack visualization.", "3.43.3 Breadth-First Traversal (Level-order): queue-based level-by-level breadth exploration.", "3.43.4 Tree properties: height, depth, diameter, complete vs full vs degenerate trees."]}'::jsonb, '["Explain how this implementation prevents: Unbounded recursion in tree traversals exceeding call stack limits on skewed, degenerate trees.", "How does Binary Trees: Tree Traversals & Depth Analysis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-44', 'phase-03-lesson-44-binary-search-trees-bst-invariants-node-d', 'module-5', 44, 'Lesson 5.44: Binary Search Trees (BST): Invariants & Node Deletion', 'Prerequisites: Lesson 3.43', 'Prerequisites: Lesson 3.43 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 2200.0, '# Lesson 3.44: Binary Search Trees (BST): Invariants & Node Deletion

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.43
- **Subtopics**:
  - `3.44.1` The BST Invariant: for every node, all left subtree values are smaller, all right subtree values are larger.
  - `3.44.2` Search and Insertion: $O(h)$ time where $h$ is tree height.
  - `3.44.3` Node Deletion algorithm: 3 cases (Leaf node, Node with one child, Node with two children / in-order successor swap).
  - `3.44.4` The Degeneracy hazard: sorted insertions degrading a BST into an $O(n)$ linked list.
- **Key Failure Modes & Edge Cases**: Deleting a node with two children incorrectly, severing subtree linkages and violating BST invariants.
- **Verification & Mastery Check**: Implement a full BST from scratch supporting search, insertion, and 3-case node deletion.
- **Project Application**: DataSift: Sorted indexing.', '{"solution.py": "# Phase 3 // Lesson 3.44: Binary Search Trees (BST): Invariants & Node Deletion\n\ndef solve():\n    \"\"\"\n    Verification: Implement a full BST from scratch supporting search, insertion, and 3-case node deletion.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.44", "subtopics_count": 4, "verification_criteria": "Implement a full BST from scratch supporting search, insertion, and 3-case node deletion.", "subtopics": ["3.44.1 The BST Invariant: for every node, all left subtree values are smaller, all right subtree values are larger.", "3.44.2 Search and Insertion: $O(h)$ time where $h$ is tree height.", "3.44.3 Node Deletion algorithm: 3 cases (Leaf node, Node with one child, Node with two children / in-order successor swap).", "3.44.4 The Degeneracy hazard: sorted insertions degrading a BST into an $O(n)$ linked list."]}'::jsonb, '["Explain how this implementation prevents: Deleting a node with two children incorrectly, severing subtree linkages and violating BST invariants.", "How does Binary Search Trees (BST): Invariants & Node Deletion scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-45', 'phase-03-lesson-45-balanced-search-trees-avl-tree-rotations', 'module-5', 45, 'Lesson 5.45: Balanced Search Trees: AVL Tree Rotations', 'Prerequisites: Lesson 3.44', 'Prerequisites: Lesson 3.44 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 2250.0, '# Lesson 3.45: Balanced Search Trees: AVL Tree Rotations

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.44
- **Subtopics**:
  - `3.45.1` Why balance matters: guaranteeing $O(\log n)$ height under all insertion sequences.
  - `3.45.2` AVL Balance Factor: $	ext{height}(	ext{left}) - 	ext{height}(	ext{right}) \in \{-1, 0, 1\}$.
  - `3.45.3` Single Rotations: Left Rotation (LL) and Right Rotation (RR).
  - `3.45.4` Double Rotations: Left-Right Rotation (LR) and Right-Left Rotation (RL).
- **Key Failure Modes & Edge Cases**: Failing to update tree heights after rotations, causing subsequent balance factor calculations to fail.
- **Verification & Mastery Check**: Implement an AVL Tree with automatic self-balancing via rotations on insertion.
- **Project Application**: DataSift: Range query indexes.', '{"solution.py": "# Phase 3 // Lesson 3.45: Balanced Search Trees: AVL Tree Rotations\n\ndef solve():\n    \"\"\"\n    Verification: Implement an AVL Tree with automatic self-balancing via rotations on insertion.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.45", "subtopics_count": 4, "verification_criteria": "Implement an AVL Tree with automatic self-balancing via rotations on insertion.", "subtopics": ["3.45.1 Why balance matters: guaranteeing $O(\\log n)$ height under all insertion sequences.", "3.45.2 AVL Balance Factor: $\text{height}(\text{left}) - \text{height}(\text{right}) \\in \\{-1, 0, 1\\}$.", "3.45.3 Single Rotations: Left Rotation (LL) and Right Rotation (RR).", "3.45.4 Double Rotations: Left-Right Rotation (LR) and Right-Left Rotation (RL)."]}'::jsonb, '["Explain how this implementation prevents: Failing to update tree heights after rotations, causing subsequent balance factor calculations to fail.", "How does Balanced Search Trees: AVL Tree Rotations scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-1', 'phase-04-lesson-01-process-address-space-segments-memory-lay', 'module-6', 1, 'Lesson 6.1: Process Address Space: Segments & Memory Layout', 'Prerequisites: Phase 0 (Lesson 0.9)', 'Prerequisites: Phase 0 (Lesson 0.9) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 50.0, '# Lesson 4.1: Process Address Space: Segments & Memory Layout

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.9)
- **Subtopics**:
  - `4.1.1` The 64-bit virtual memory address space: user space (lower addresses) vs kernel space (upper canonical addresses).
  - `4.1.2` Segment breakdown: Text (.text), Initialized Data (.data), Uninitialized Data (.bss), Heap, Memory Mapping, Stack.
  - `4.1.3` Address Space Layout Randomization (ASLR): randomizing base addresses to prevent buffer overflow exploits.
  - `4.1.4` Inspecting process memory maps via `/proc/<pid>/maps` and runtime segment boundaries.
- **Key Failure Modes & Edge Cases**: Assuming fixed memory addresses across program executions, broken by ASLR security mitigations.
- **Verification & Mastery Check**: Write a C/Python script to inspect and print the memory addresses of stack, heap, and text variables in real time.
- **Project Application**: NanoHTTP: Memory-mapped static file buffers.', '{"solution.py": "# Phase 4 // Lesson 4.1: Process Address Space: Segments & Memory Layout\n\ndef solve():\n    \"\"\"\n    Verification: Write a C/Python script to inspect and print the memory addresses of stack, heap, and text variables\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.1", "subtopics_count": 4, "verification_criteria": "Write a C/Python script to inspect and print the memory addresses of stack, heap, and text variables in real time.", "subtopics": ["4.1.1 The 64-bit virtual memory address space: user space (lower addresses) vs kernel space (upper canonical addresses).", "4.1.2 Segment breakdown: Text (.text), Initialized Data (.data), Uninitialized Data (.bss), Heap, Memory Mapping, Stack.", "4.1.3 Address Space Layout Randomization (ASLR): randomizing base addresses to prevent buffer overflow exploits.", "4.1.4 Inspecting process memory maps via `/proc/<pid>/maps` and runtime segment boundaries."]}'::jsonb, '["Explain how this implementation prevents: Assuming fixed memory addresses across program executions, broken by ASLR security mitigations.", "How does Process Address Space: Segments & Memory Layout scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-2', 'phase-04-lesson-02-multi-level-page-tables-page-directory-po', 'module-6', 2, 'Lesson 6.2: Multi-Level Page Tables & Page Directory Pointers', 'Prerequisites: Lesson 4.1', 'Prerequisites: Lesson 4.1 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 100.0, '# Lesson 4.2: Multi-Level Page Tables & Page Directory Pointers

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.1
- **Subtopics**:
  - `4.2.1` 4-level paging in x86-64: Page Map Level 4 (PML4), Page Directory Pointer Table (PDPT), Page Directory (PD), Page Table (PT).
  - `4.2.2` Virtual Address Bit Breakdown: 9 bits per level ($4 	imes 9 = 36$ bits) + 12-bit page offset ($2^{12} = 4096$ bytes).
  - `4.2.3` Page Table Entries (PTE): Present bit, Read/Write bit, User/Supervisor bit, Accessed/Dirty bits, No-Execute (NX) bit.
  - `4.2.4` 5-level paging (PML5): extending virtual address space to 57 bits (128 petabytes) in modern enterprise datacenters.
- **Key Failure Modes & Edge Cases**: Paging memory overhead: allocating millions of tiny sparse mappings causing excessive page table memory consumption.
- **Verification & Mastery Check**: Calculate the physical memory required to store the page table for a process mapping 10GB of fragmented RAM.
- **Project Application**: Systems foundation for OS memory understanding.', '{"solution.py": "# Phase 4 // Lesson 4.2: Multi-Level Page Tables & Page Directory Pointers\n\ndef solve():\n    \"\"\"\n    Verification: Calculate the physical memory required to store the page table for a process mapping 10GB of fragmen\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.2", "subtopics_count": 4, "verification_criteria": "Calculate the physical memory required to store the page table for a process mapping 10GB of fragmented RAM.", "subtopics": ["4.2.1 4-level paging in x86-64: Page Map Level 4 (PML4), Page Directory Pointer Table (PDPT), Page Directory (PD), Page Table (PT).", "4.2.2 Virtual Address Bit Breakdown: 9 bits per level ($4 \times 9 = 36$ bits) + 12-bit page offset ($2^{12} = 4096$ bytes).", "4.2.3 Page Table Entries (PTE): Present bit, Read/Write bit, User/Supervisor bit, Accessed/Dirty bits, No-Execute (NX) bit.", "4.2.4 5-level paging (PML5): extending virtual address space to 57 bits (128 petabytes) in modern enterprise datacenters."]}'::jsonb, '["Explain how this implementation prevents: Paging memory overhead: allocating millions of tiny sparse mappings causing excessive page table memory consumption.", "How does Multi-Level Page Tables & Page Directory Pointers scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-3', 'phase-04-lesson-03-translation-lookaside-buffer-tlb-hardware', 'module-6', 3, 'Lesson 6.3: Translation Lookaside Buffer (TLB) & Hardware Walkers', 'Prerequisites: Lesson 4.2', 'Prerequisites: Lesson 4.2 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 150.0, '# Lesson 4.3: Translation Lookaside Buffer (TLB) & Hardware Walkers

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.2
- **Subtopics**:
  - `4.3.1` TLB hardware cache: associative lookups converting virtual page numbers to physical frame numbers in $<1$ clock cycle.
  - `4.3.2` TLB Miss penalty: hardware page table walker traversing physical RAM across 4 memory references.
  - `4.3.3` TLB Shootdowns: multi-core cache coherency inter-processor interrupts (IPI) invalidating TLB entries across cores.
  - `4.3.4` HugePages (2MB, 1GB): reducing TLB misses by covering $512	imes$ to $262,144	imes$ more memory per TLB entry.
- **Key Failure Modes & Edge Cases**: Severe multi-threaded latency spikes caused by frequent TLB shootdowns during active memory re-mapping.
- **Verification & Mastery Check**: Configure Linux Transparent HugePages (THP) and benchmark memory access latency on a 10GB array.
- **Project Application**: High-performance memory tuning for vector search in Phase 10.', '{"solution.py": "# Phase 4 // Lesson 4.3: Translation Lookaside Buffer (TLB) & Hardware Walkers\n\ndef solve():\n    \"\"\"\n    Verification: Configure Linux Transparent HugePages (THP) and benchmark memory access latency on a 10GB array.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.3", "subtopics_count": 4, "verification_criteria": "Configure Linux Transparent HugePages (THP) and benchmark memory access latency on a 10GB array.", "subtopics": ["4.3.1 TLB hardware cache: associative lookups converting virtual page numbers to physical frame numbers in $<1$ clock cycle.", "4.3.2 TLB Miss penalty: hardware page table walker traversing physical RAM across 4 memory references.", "4.3.3 TLB Shootdowns: multi-core cache coherency inter-processor interrupts (IPI) invalidating TLB entries across cores.", "4.3.4 HugePages (2MB, 1GB): reducing TLB misses by covering $512\times$ to $262,144\times$ more memory per TLB entry."]}'::jsonb, '["Explain how this implementation prevents: Severe multi-threaded latency spikes caused by frequent TLB shootdowns during active memory re-mapping.", "How does Translation Lookaside Buffer (TLB) & Hardware Walkers scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-4', 'phase-04-lesson-04-zero-copy-i-o-memory-mapped-files-with-mm', 'module-6', 4, 'Lesson 6.4: Zero-Copy I/O & Memory-Mapped Files with `mmap`', 'Prerequisites: Lesson 4.1', 'Prerequisites: Lesson 4.1 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 200.0, '# Lesson 4.4: Zero-Copy I/O & Memory-Mapped Files with `mmap`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.1
- **Subtopics**:
  - `4.4.1` Traditional file I/O overhead: disk $	o$ kernel page cache $	o$ user space buffer (`read`) $	o$ socket buffer (`write`).
  - `4.4.2` `mmap()` zero-copy architecture: mapping disk blocks directly into the process virtual address space.
  - `4.4.3` Memory protection flags: `PROT_READ`, `PROT_WRITE`, `PROT_EXEC`; sharing modes: `MAP_SHARED` vs `MAP_PRIVATE` (COW).
  - `4.4.4` Kernel zero-copy syscalls: `sendfile()` transferring bytes directly from page cache to socket descriptor.
- **Key Failure Modes & Edge Cases**: Triggering `SIGBUS` crashes when reading from an `mmap` region after another process truncates the underlying file.
- **Verification & Mastery Check**: Implement a static file server using `sendfile()` and `mmap()` that serves multi-gigabyte files with zero user-space copying.
- **Project Application**: NanoHTTP: Static file serving engine.', '{"solution.py": "# Phase 4 // Lesson 4.4: Zero-Copy I/O & Memory-Mapped Files with `mmap`\n\ndef solve():\n    \"\"\"\n    Verification: Implement a static file server using `sendfile()` and `mmap()` that serves multi-gigabyte files with\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.4", "subtopics_count": 4, "verification_criteria": "Implement a static file server using `sendfile()` and `mmap()` that serves multi-gigabyte files with zero user-space copying.", "subtopics": ["4.4.1 Traditional file I/O overhead: disk $\to$ kernel page cache $\to$ user space buffer (`read`) $\to$ socket buffer (`write`).", "4.4.2 `mmap()` zero-copy architecture: mapping disk blocks directly into the process virtual address space.", "4.4.3 Memory protection flags: `PROT_READ`, `PROT_WRITE`, `PROT_EXEC`; sharing modes: `MAP_SHARED` vs `MAP_PRIVATE` (COW).", "4.4.4 Kernel zero-copy syscalls: `sendfile()` transferring bytes directly from page cache to socket descriptor."]}'::jsonb, '["Explain how this implementation prevents: Triggering `SIGBUS` crashes when reading from an `mmap` region after another process truncates the underlying file.", "How does Zero-Copy I/O & Memory-Mapped Files with `mmap` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-5', 'phase-04-lesson-05-the-linux-out-of-memory-oom-killer-memory', 'module-6', 5, 'Lesson 6.5: The Linux Out-Of-Memory (OOM) Killer & Memory Cgroups', 'Prerequisites: Lesson 4.1', 'Prerequisites: Lesson 4.1 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 250.0, '# Lesson 4.5: The Linux Out-Of-Memory (OOM) Killer & Memory Cgroups

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.1
- **Subtopics**:
  - `4.5.1` Memory overcommit (`vm.overcommit_memory`): why Linux permits allocating more virtual memory than physical RAM exists.
  - `4.5.2` The OOM Killer invocation: kernel heuristics evaluating `oom_score` and `oom_score_adj` (-1000 to +1000).
  - `4.5.3` Control Groups (cgroups v2) Memory limits: `memory.max`, `memory.high`, and container OOM termination (`OOMKilled: 137`).
  - `4.5.4` Swap space dynamics: page swapping mechanics, swappiness tuning (`vm.swappiness`), and swap thrashing.
- **Key Failure Modes & Edge Cases**: Production container terminations with exit code 137 caused by exceeding cgroup `memory.max` limits without metrics visibility.
- **Verification & Mastery Check**: Simulate an OOM condition inside a constrained cgroup and analyze the kernel dmesg OOM kill log.
- **Project Application**: Docker container memory limit configuration in Phase 4 and Phase 7.', '{"solution.py": "# Phase 4 // Lesson 4.5: The Linux Out-Of-Memory (OOM) Killer & Memory Cgroups\n\ndef solve():\n    \"\"\"\n    Verification: Simulate an OOM condition inside a constrained cgroup and analyze the kernel dmesg OOM kill log.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.5", "subtopics_count": 4, "verification_criteria": "Simulate an OOM condition inside a constrained cgroup and analyze the kernel dmesg OOM kill log.", "subtopics": ["4.5.1 Memory overcommit (`vm.overcommit_memory`): why Linux permits allocating more virtual memory than physical RAM exists.", "4.5.2 The OOM Killer invocation: kernel heuristics evaluating `oom_score` and `oom_score_adj` (-1000 to +1000).", "4.5.3 Control Groups (cgroups v2) Memory limits: `memory.max`, `memory.high`, and container OOM termination (`OOMKilled: 137`).", "4.5.4 Swap space dynamics: page swapping mechanics, swappiness tuning (`vm.swappiness`), and swap thrashing."]}'::jsonb, '["Explain how this implementation prevents: Production container terminations with exit code 137 caused by exceeding cgroup `memory.max` limits without metrics visi", "How does The Linux Out-Of-Memory (OOM) Killer & Memory Cgroups scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-6', 'phase-04-lesson-06-process-forking-copy-on-write-cow-execve', 'module-6', 6, 'Lesson 6.6: Process Forking, Copy-On-Write (COW), & `execve`', 'Prerequisites: Phase 0 (Lesson 0.21)', 'Prerequisites: Phase 0 (Lesson 0.21) | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 300.0, '# Lesson 4.6: Process Forking, Copy-On-Write (COW), & `execve`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.21)
- **Subtopics**:
  - `4.6.1` The `fork()` system call: duplicating process address space, file descriptors, and signal masks.
  - `4.6.2` Copy-On-Write (COW) mechanics: sharing identical physical pages marked read-only until a process writes to a page.
  - `4.6.3` The `execve()` system call: clearing virtual address space, loading new ELF binary, initializing new stack and heap.
  - `4.6.4` The `posix_spawn()` optimized interface: avoiding memory table duplication overhead on modern Linux.
- **Key Failure Modes & Edge Cases**: Redis background save (`BGSAVE`) memory spikes: COW dirty page copies exhausting RAM when writes are heavy during saves.
- **Verification & Mastery Check**: Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW in action.
- **Project Application**: NanoHTTP and systems tooling.', '{"solution.py": "# Phase 4 // Lesson 4.6: Process Forking, Copy-On-Write (COW), & `execve`\n\ndef solve():\n    \"\"\"\n    Verification: Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.6", "subtopics_count": 4, "verification_criteria": "Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW in action.", "subtopics": ["4.6.1 The `fork()` system call: duplicating process address space, file descriptors, and signal masks.", "4.6.2 Copy-On-Write (COW) mechanics: sharing identical physical pages marked read-only until a process writes to a page.", "4.6.3 The `execve()` system call: clearing virtual address space, loading new ELF binary, initializing new stack and heap.", "4.6.4 The `posix_spawn()` optimized interface: avoiding memory table duplication overhead on modern Linux."]}'::jsonb, '["Explain how this implementation prevents: Redis background save (`BGSAVE`) memory spikes: COW dirty page copies exhausting RAM when writes are heavy during saves.", "How does Process Forking, Copy-On-Write (COW), & `execve` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-7', 'phase-04-lesson-07-inter-process-communication-pipes-named-f', 'module-6', 7, 'Lesson 6.7: Inter-Process Communication: Pipes & Named FIFOs', 'Prerequisites: Phase 0 (Lesson 0.24)', 'Prerequisites: Phase 0 (Lesson 0.24) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 350.0, '# Lesson 4.7: Inter-Process Communication: Pipes & Named FIFOs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.24)
- **Subtopics**:
  - `4.7.1` Anonymous pipes (`pipe()`): unidirectional kernel ring buffer (64KB default capacity).
  - `4.7.2` Blocking behavior: `write()` blocks when pipe buffer is full; `read()` blocks when pipe buffer is empty.
  - `4.7.3` Broken pipe signal: `SIGPIPE` generated when writing to a pipe with zero active read file descriptors.
  - `4.7.4` Named pipes (`mkfifo()`): filesystem entries enabling IPC between unrelated processes without parent-child ancestry.
- **Key Failure Modes & Edge Cases**: Crashing on unhandled `SIGPIPE` when downstream readers close connections abruptly while writer continues writing.
- **Verification & Mastery Check**: Implement a bidirectional IPC communication channel between two processes using a pair of named FIFOs.
- **Project Application**: SysTrace and systems IPC.', '{"solution.py": "# Phase 4 // Lesson 4.7: Inter-Process Communication: Pipes & Named FIFOs\n\ndef solve():\n    \"\"\"\n    Verification: Implement a bidirectional IPC communication channel between two processes using a pair of named FIFO\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.7", "subtopics_count": 4, "verification_criteria": "Implement a bidirectional IPC communication channel between two processes using a pair of named FIFOs.", "subtopics": ["4.7.1 Anonymous pipes (`pipe()`): unidirectional kernel ring buffer (64KB default capacity).", "4.7.2 Blocking behavior: `write()` blocks when pipe buffer is full; `read()` blocks when pipe buffer is empty.", "4.7.3 Broken pipe signal: `SIGPIPE` generated when writing to a pipe with zero active read file descriptors.", "4.7.4 Named pipes (`mkfifo()`): filesystem entries enabling IPC between unrelated processes without parent-child ancestry."]}'::jsonb, '["Explain how this implementation prevents: Crashing on unhandled `SIGPIPE` when downstream readers close connections abruptly while writer continues writing.", "How does Inter-Process Communication: Pipes & Named FIFOs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-8', 'phase-04-lesson-08-unix-domain-sockets-passing-file-descript', 'module-6', 8, 'Lesson 6.8: Unix Domain Sockets & Passing File Descriptors', 'Prerequisites: Lesson 4.7', 'Prerequisites: Lesson 4.7 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 400.0, '# Lesson 4.8: Unix Domain Sockets & Passing File Descriptors

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.7
- **Subtopics**:
  - `4.8.1` Unix Domain Sockets (`AF_UNIX`): bidirectional local IPC bypassing network stack, checksums, and TCP headers.
  - `4.8.2` Stream (`SOCK_STREAM`) vs Datagram (`SOCK_DGRAM`) Unix sockets; filesystem socket nodes.
  - `4.8.3` Passing Open File Descriptors: utilizing `sendmsg()` and `recvmsg()` with `SCM_RIGHTS` ancillary control messages.
  - `4.8.4` Why UDS outperforms loopback TCP (`127.0.0.1`): 2x throughput, lower latency, filesystem permission security.
- **Key Failure Modes & Edge Cases**: Dangling socket files on filesystem after unclean process termination preventing service restarts.
- **Verification & Mastery Check**: Build a parent process that opens a TCP socket and passes the active file descriptor to a child worker via UDS.
- **Project Application**: PgBouncer local connections in Phase 5.', '{"solution.py": "# Phase 4 // Lesson 4.8: Unix Domain Sockets & Passing File Descriptors\n\ndef solve():\n    \"\"\"\n    Verification: Build a parent process that opens a TCP socket and passes the active file descriptor to a child work\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.8", "subtopics_count": 4, "verification_criteria": "Build a parent process that opens a TCP socket and passes the active file descriptor to a child worker via UDS.", "subtopics": ["4.8.1 Unix Domain Sockets (`AF_UNIX`): bidirectional local IPC bypassing network stack, checksums, and TCP headers.", "4.8.2 Stream (`SOCK_STREAM`) vs Datagram (`SOCK_DGRAM`) Unix sockets; filesystem socket nodes.", "4.8.3 Passing Open File Descriptors: utilizing `sendmsg()` and `recvmsg()` with `SCM_RIGHTS` ancillary control messages.", "4.8.4 Why UDS outperforms loopback TCP (`127.0.0.1`): 2x throughput, lower latency, filesystem permission security."]}'::jsonb, '["Explain how this implementation prevents: Dangling socket files on filesystem after unclean process termination preventing service restarts.", "How does Unix Domain Sockets & Passing File Descriptors scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-9', 'phase-04-lesson-09-posix-signals-asynchronous-interruption-r', 'module-6', 9, 'Lesson 6.9: POSIX Signals: Asynchronous Interruption & Re-entrancy', 'Prerequisites: Phase 0 (Lesson 0.25)', 'Prerequisites: Phase 0 (Lesson 0.25) | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 450.0, '# Lesson 4.9: POSIX Signals: Asynchronous Interruption & Re-entrancy

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.25)
- **Subtopics**:
  - `4.9.1` Signal delivery mechanics: kernel interrupting user-space instruction stream and executing registered signal handler.
  - `4.9.2` Signal masks: blocking and unblocking signals via `sigprocmask()` during critical sections.
  - `4.9.3` Signal Re-entrancy: why calling non-reentrant functions (`printf`, `malloc`, `free`) inside signal handlers causes deadlocks.
  - `4.9.4` Async-signal-safe functions list: POSIX standard guarantees; setting `sig_atomic_t` or `volatile` flags.
- **Key Failure Modes & Edge Cases**: Deadlocks in production signal handlers caused by attempting to acquire a mutex or allocate memory inside the handler.
- **Verification & Mastery Check**: Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self-pipe trick.
- **Project Application**: NanoHTTP: Graceful shutdown signal engine.', '{"solution.py": "# Phase 4 // Lesson 4.9: POSIX Signals: Asynchronous Interruption & Re-entrancy\n\ndef solve():\n    \"\"\"\n    Verification: Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.9", "subtopics_count": 4, "verification_criteria": "Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self-pipe trick.", "subtopics": ["4.9.1 Signal delivery mechanics: kernel interrupting user-space instruction stream and executing registered signal handler.", "4.9.2 Signal masks: blocking and unblocking signals via `sigprocmask()` during critical sections.", "4.9.3 Signal Re-entrancy: why calling non-reentrant functions (`printf`, `malloc`, `free`) inside signal handlers causes deadlocks.", "4.9.4 Async-signal-safe functions list: POSIX standard guarantees; setting `sig_atomic_t` or `volatile` flags."]}'::jsonb, '["Explain how this implementation prevents: Deadlocks in production signal handlers caused by attempting to acquire a mutex or allocate memory inside the handler.", "How does POSIX Signals: Asynchronous Interruption & Re-entrancy scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-10', 'phase-04-lesson-10-zombie-processes-orphan-reaping-waitpid', 'module-6', 10, 'Lesson 6.10: Zombie Processes, Orphan Reaping, & `waitpid`', 'Prerequisites: Lesson 4.6', 'Prerequisites: Lesson 4.6 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 500.0, '# Lesson 4.10: Zombie Processes, Orphan Reaping, & `waitpid`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.6
- **Subtopics**:
  - `4.10.1` Process termination lifecycle: child process exits, becomes Zombie (`Z` state), retains exit status in PCB.
  - `4.10.2` Reaping zombies: parent calling `wait()` or `waitpid()` to read child exit status and release kernel PCB memory.
  - `4.10.3` Orphan processes: parent terminating before child; child adopted by init process (PID 1 / systemd).
  - `4.10.4` Subreaper processes: using `prctl(PR_SET_CHILD_SUBREAPER)` in process managers to reap orphaned descendant trees.
- **Key Failure Modes & Edge Cases**: Zombie accumulation exhausting kernel PID limits in container environments where PID 1 fails to reap children.
- **Verification & Mastery Check**: Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated workers immediately.
- **Project Application**: Container process management in Phase 4 and Phase 7.', '{"solution.py": "# Phase 4 // Lesson 4.10: Zombie Processes, Orphan Reaping, & `waitpid`\n\ndef solve():\n    \"\"\"\n    Verification: Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated wor\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.10", "subtopics_count": 4, "verification_criteria": "Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated workers immediately.", "subtopics": ["4.10.1 Process termination lifecycle: child process exits, becomes Zombie (`Z` state), retains exit status in PCB.", "4.10.2 Reaping zombies: parent calling `wait()` or `waitpid()` to read child exit status and release kernel PCB memory.", "4.10.3 Orphan processes: parent terminating before child; child adopted by init process (PID 1 / systemd).", "4.10.4 Subreaper processes: using `prctl(PR_SET_CHILD_SUBREAPER)` in process managers to reap orphaned descendant trees."]}'::jsonb, '["Explain how this implementation prevents: Zombie accumulation exhausting kernel PID limits in container environments where PID 1 fails to reap children.", "How does Zombie Processes, Orphan Reaping, & `waitpid` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
