INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-6-31', 'phase-06-lesson-31-react-server-components-rsc-architecture-', 'module-8', 31, 'Lesson 8.31: React Server Components (RSC) Architecture & The Server-Client Divide', 'Prerequisites: Lesson 6.30', 'Prerequisites: Lesson 6.30 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 1550.0, '# Lesson 6.31: React Server Components (RSC) Architecture & The Server-Client Divide

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.30
- **Subtopics**:
  - `6.31.1` RSC mental model: zero-bundle-size server components executing exclusively in Node.js/Edge runtimes
  - `6.31.2` The ''use client'' boundary: marking transition points between server rendering and client-side interactivity
  - `6.31.3` Component composition rules: passing Server Components as children/props to Client Components to avoid client bundle bloating
  - `6.31.4` Serialization boundary: why props passed from Server to Client Components must be JSON-serializable
  - `6.31.5` Data fetching in Server Components: direct database access, async/await component syntax, and eliminating client waterfalls
  - `6.31.6` RSC wire format: binary streaming protocol encoding component trees, props, and Suspense placeholders
- **Key Failure Modes & Edge Cases**: Marking root layouts with ''use client'', accidentally bundling entire application to client; attempting to pass functions across RSC boundary.
- **Verification & Mastery Check**: Build a zero-JS data-dense analytics view that fetches data directly from PostgreSQL inside a Server Component.
- **Project Application**: TenantIQ: Server-rendered tenant executive dashboard.', '{"solution.py": "# Phase 6 // Lesson 6.31: React Server Components (RSC) Architecture & The Server-Client Divide\n\ndef solve():\n    \"\"\"\n    Verification: Build a zero-JS data-dense analytics view that fetches data directly from PostgreSQL inside a Server\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.31", "subtopics_count": 6, "verification_criteria": "Build a zero-JS data-dense analytics view that fetches data directly from PostgreSQL inside a Server Component.", "subtopics": ["6.31.1 RSC mental model: zero-bundle-size server components executing exclusively in Node.js/Edge runtimes", "6.31.2 The ''use client'' boundary: marking transition points between server rendering and client-side interactivity", "6.31.3 Component composition rules: passing Server Components as children/props to Client Components to avoid client bundle bloating", "6.31.4 Serialization boundary: why props passed from Server to Client Components must be JSON-serializable", "6.31.5 Data fetching in Server Components: direct database access, async/await component syntax, and eliminating client waterfalls", "6.31.6 RSC wire format: binary streaming protocol encoding component trees, props, and Suspense placeholders"]}'::jsonb, '["Explain how this implementation prevents: Marking root layouts with ''use client'', accidentally bundling entire application to client; attempting to pass functions", "How does React Server Components (RSC) Architecture & The Server-Client Divide scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-32', 'phase-06-lesson-32-next-js-data-fetching-caching-layers-reva', 'module-8', 32, 'Lesson 8.32: Next.js Data Fetching, Caching Layers & Revalidation Strategies', 'Prerequisites: Lesson 6.30, Lesson 6.31', 'Prerequisites: Lesson 6.30, Lesson 6.31 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 1600.0, '# Lesson 6.32: Next.js Data Fetching, Caching Layers & Revalidation Strategies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.30, Lesson 6.31
- **Subtopics**:
  - `6.32.1` Next.js cache architecture: Request Memoization, Data Cache, Full Route Cache, and Router Cache
  - `6.32.2` Extended fetch options: `cache: ''force-cache''`, `cache: ''no-store''`, and `next: { revalidate: 3600 }`
  - `6.32.3` On-demand revalidation: revalidateTag and revalidatePath triggered via Server Actions and webhooks
  - `6.32.4` Static Site Generation (SSG) vs Dynamic Server-Side Rendering (SSR) vs Incremental Static Regeneration (ISR)
  - `6.32.5` Dynamic functions that opt routes out of static caching: cookies(), headers(), and searchParams access
  - `6.32.6` Segment Config Options: `dynamic = ''force-dynamic''`, `revalidate`, and `runtime = ''edge''`
- **Key Failure Modes & Edge Cases**: Accidental dynamic bailouts caused by reading cookies in root layout; stale cache serving outdated multi-tenant records.
- **Verification & Mastery Check**: Configure a robust multi-tiered caching strategy with instant webhook-triggered on-demand tag revalidation.
- **Project Application**: TenantIQ: Public marketing blog and dynamic multi-tenant documentation hub.', '{"solution.py": "# Phase 6 // Lesson 6.32: Next.js Data Fetching, Caching Layers & Revalidation Strategies\n\ndef solve():\n    \"\"\"\n    Verification: Configure a robust multi-tiered caching strategy with instant webhook-triggered on-demand tag revali\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.32", "subtopics_count": 6, "verification_criteria": "Configure a robust multi-tiered caching strategy with instant webhook-triggered on-demand tag revalidation.", "subtopics": ["6.32.1 Next.js cache architecture: Request Memoization, Data Cache, Full Route Cache, and Router Cache", "6.32.2 Extended fetch options: `cache: ''force-cache''`, `cache: ''no-store''`, and `next: { revalidate: 3600 }`", "6.32.3 On-demand revalidation: revalidateTag and revalidatePath triggered via Server Actions and webhooks", "6.32.4 Static Site Generation (SSG) vs Dynamic Server-Side Rendering (SSR) vs Incremental Static Regeneration (ISR)", "6.32.5 Dynamic functions that opt routes out of static caching: cookies(), headers(), and searchParams access", "6.32.6 Segment Config Options: `dynamic = ''force-dynamic''`, `revalidate`, and `runtime = ''edge''`"]}'::jsonb, '["Explain how this implementation prevents: Accidental dynamic bailouts caused by reading cookies in root layout; stale cache serving outdated multi-tenant records.", "How does Next.js Data Fetching, Caching Layers & Revalidation Strategies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-33', 'phase-06-lesson-33-next-js-server-actions-form-mutations', 'module-8', 33, 'Lesson 8.33: Next.js Server Actions & Form Mutations', 'Prerequisites: Lesson 6.27, Lesson 6.31', 'Prerequisites: Lesson 6.27, Lesson 6.31 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 1650.0, '# Lesson 6.33: Next.js Server Actions & Form Mutations

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.27, Lesson 6.31
- **Subtopics**:
  - `6.33.1` Server Actions architecture: ''use server'' directives, RPC mechanism, and progressive enhancement support
  - `6.33.2` Invoking Server Actions from forms: native HTML `<form action={action}>` working without client-side JavaScript
  - `6.33.3` useActionState and useFormStatus hooks: managing pending states, returned data, and optimistic submissions
  - `6.33.4` Server Action security: validating inputs with Zod, authentication verification, and CSRF protection guarantees
  - `6.33.5` Cache mutations within Server Actions: coordinating revalidatePath, revalidateTag, and redirect()
  - `6.33.6` Error handling patterns in Server Actions: returning serializable error state objects vs throwing unhandled exceptions
- **Key Failure Modes & Edge Cases**: Exposing internal server database functions directly without authentication checks; throwing raw errors exposing database stack traces.
- **Verification & Mastery Check**: Create a secure Server Action pipeline for tenant creation with input sanitization, database mutation, and cache revalidation.
- **Project Application**: TenantIQ: Organization creation and member invitation actions.', '{"solution.py": "# Phase 6 // Lesson 6.33: Next.js Server Actions & Form Mutations\n\ndef solve():\n    \"\"\"\n    Verification: Create a secure Server Action pipeline for tenant creation with input sanitization, database mutatio\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.33", "subtopics_count": 6, "verification_criteria": "Create a secure Server Action pipeline for tenant creation with input sanitization, database mutation, and cache revalidation.", "subtopics": ["6.33.1 Server Actions architecture: ''use server'' directives, RPC mechanism, and progressive enhancement support", "6.33.2 Invoking Server Actions from forms: native HTML `<form action={action}>` working without client-side JavaScript", "6.33.3 useActionState and useFormStatus hooks: managing pending states, returned data, and optimistic submissions", "6.33.4 Server Action security: validating inputs with Zod, authentication verification, and CSRF protection guarantees", "6.33.5 Cache mutations within Server Actions: coordinating revalidatePath, revalidateTag, and redirect()", "6.33.6 Error handling patterns in Server Actions: returning serializable error state objects vs throwing unhandled exceptions"]}'::jsonb, '["Explain how this implementation prevents: Exposing internal server database functions directly without authentication checks; throwing raw errors exposing databas", "How does Next.js Server Actions & Form Mutations scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-34', 'phase-06-lesson-34-next-js-route-handlers-edge-runtime-api-r', 'module-8', 34, 'Lesson 8.34: Next.js Route Handlers & Edge Runtime API Routes', 'Prerequisites: Phase 4, Lesson 6.30', 'Prerequisites: Phase 4, Lesson 6.30 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 1700.0, '# Lesson 6.34: Next.js Route Handlers & Edge Runtime API Routes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 6.30
- **Subtopics**:
  - `6.34.1` Route Handlers architecture: `route.ts` file convention and HTTP verb exports (GET, POST, PUT, DELETE, PATCH)
  - `6.34.2` NextRequest and NextResponse abstractions: reading headers, cookies, URL searchParams, and geo/ip metadata
  - `6.34.3` Runtime environments: Node.js runtime vs Edge Runtime (V8 isolates, low cold-starts, limited API surface)
  - `6.34.4` Streaming responses from Route Handlers: ReadableStream, TextEncoder, and chunked transfer encoding
  - `6.34.5` Webhook endpoint implementation: raw body signature verification (e.g. Stripe webhooks) and idempotent processing
  - `6.34.6` Rate limiting at the route level: token bucket algorithms backed by Redis/Upstash inside Edge functions
- **Key Failure Modes & Edge Cases**: Attempting to use unsupported Node.js native modules (fs, child_process) inside Edge Runtime; consuming raw body twice breaking signatures.
- **Verification & Mastery Check**: Build an Edge-compatible Stripe webhook handler verifying cryptographic signatures and updating database records idempotently.
- **Project Application**: TenantIQ: Stripe webhook ingestion API.', '{"solution.py": "# Phase 6 // Lesson 6.34: Next.js Route Handlers & Edge Runtime API Routes\n\ndef solve():\n    \"\"\"\n    Verification: Build an Edge-compatible Stripe webhook handler verifying cryptographic signatures and updating data\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.34", "subtopics_count": 6, "verification_criteria": "Build an Edge-compatible Stripe webhook handler verifying cryptographic signatures and updating database records idempotently.", "subtopics": ["6.34.1 Route Handlers architecture: `route.ts` file convention and HTTP verb exports (GET, POST, PUT, DELETE, PATCH)", "6.34.2 NextRequest and NextResponse abstractions: reading headers, cookies, URL searchParams, and geo/ip metadata", "6.34.3 Runtime environments: Node.js runtime vs Edge Runtime (V8 isolates, low cold-starts, limited API surface)", "6.34.4 Streaming responses from Route Handlers: ReadableStream, TextEncoder, and chunked transfer encoding", "6.34.5 Webhook endpoint implementation: raw body signature verification (e.g. Stripe webhooks) and idempotent processing", "6.34.6 Rate limiting at the route level: token bucket algorithms backed by Redis/Upstash inside Edge functions"]}'::jsonb, '["Explain how this implementation prevents: Attempting to use unsupported Node.js native modules (fs, child_process) inside Edge Runtime; consuming raw body twice b", "How does Next.js Route Handlers & Edge Runtime API Routes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-35', 'phase-06-lesson-35-next-js-middleware-routing-interception-m', 'module-8', 35, 'Lesson 8.35: Next.js Middleware, Routing Interception & Multi-Tenant Wildcards', 'Prerequisites: Lesson 6.30, Lesson 6.34', 'Prerequisites: Lesson 6.30, Lesson 6.34 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 1750.0, '# Lesson 6.35: Next.js Middleware, Routing Interception & Multi-Tenant Wildcards

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.30, Lesson 6.34
- **Subtopics**:
  - `6.35.1` Middleware lifecycle: executing at the edge before request matching and static asset serving
  - `6.35.2` Middleware matcher configurations: regex filtering, bypassing static files, and performance optimization
  - `6.35.3` Multi-tenant routing mechanics: hostname extraction, subdomain parsing, and URL rewriting via `NextResponse.rewrite`
  - `6.35.4` Authentication guarding in Middleware: inspecting session JWTs, redirecting unauthenticated traffic, and setting custom headers
  - `6.35.5` Security headers in Middleware: setting strict CSP, HSTS, X-Frame-Options, and Referrer-Policy headers
  - `6.35.6` Cookie manipulation inside middleware: reading and setting session cookies across subdomain boundaries
- **Key Failure Modes & Edge Cases**: Excessive latency from heavy database lookups inside Middleware; infinite redirect loops caused by bad matcher rules.
- **Verification & Mastery Check**: Implement multi-tenant wildcard subdomain routing (`[tenant].platform.com`) using Next.js Middleware and URL rewriting.
- **Project Application**: TenantIQ: Dynamic multi-tenant subdomain resolution engine.', '{"solution.py": "# Phase 6 // Lesson 6.35: Next.js Middleware, Routing Interception & Multi-Tenant Wildcards\n\ndef solve():\n    \"\"\"\n    Verification: Implement multi-tenant wildcard subdomain routing (`[tenant].platform.com`) using Next.js Middleware\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.35", "subtopics_count": 6, "verification_criteria": "Implement multi-tenant wildcard subdomain routing (`[tenant].platform.com`) using Next.js Middleware and URL rewriting.", "subtopics": ["6.35.1 Middleware lifecycle: executing at the edge before request matching and static asset serving", "6.35.2 Middleware matcher configurations: regex filtering, bypassing static files, and performance optimization", "6.35.3 Multi-tenant routing mechanics: hostname extraction, subdomain parsing, and URL rewriting via `NextResponse.rewrite`", "6.35.4 Authentication guarding in Middleware: inspecting session JWTs, redirecting unauthenticated traffic, and setting custom headers", "6.35.5 Security headers in Middleware: setting strict CSP, HSTS, X-Frame-Options, and Referrer-Policy headers", "6.35.6 Cookie manipulation inside middleware: reading and setting session cookies across subdomain boundaries"]}'::jsonb, '["Explain how this implementation prevents: Excessive latency from heavy database lookups inside Middleware; infinite redirect loops caused by bad matcher rules.", "How does Next.js Middleware, Routing Interception & Multi-Tenant Wildcards scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-36', 'phase-06-lesson-36-component-design-systems-headless-ui-arch', 'module-8', 36, 'Lesson 8.36: Component Design Systems & Headless UI Architecture', 'Prerequisites: Lesson 6.4, Lesson 6.11', 'Prerequisites: Lesson 6.4, Lesson 6.11 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 1800.0, '# Lesson 6.36: Component Design Systems & Headless UI Architecture

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.4, Lesson 6.11
- **Subtopics**:
  - `6.36.1` Design system architecture: design tokens, semantic naming (color, spacing, typography), and dark mode theming
  - `6.36.2` Headless UI pattern: separating component accessibility, keyboard navigation, and state logic from visual styling
  - `6.36.3` Radix UI / Floating UI primitives: anchor positioning, collision detection, portal rendering, and focus containment
  - `6.36.4` Tailwind CSS integration vs CSS Modules: class variance authority (cva), clsx, and tailwind-merge utility patterns
  - `6.36.5` Component polymorphism: the `asChild` pattern and polymorphic `as` prop implementations in TypeScript
  - `6.36.6` Building compound components: Select, DropdownMenu, Tabs, and Accordion with context communication
- **Key Failure Modes & Edge Cases**: Class name conflicts overriding critical design tokens; headless portal components breaking keyboard navigation order.
- **Verification & Mastery Check**: Build a production-ready, accessible, theme-aware DropdownMenu component using Radix primitives and Tailwind styling.
- **Project Application**: CompKit: Core design system component catalog.', '{"solution.py": "# Phase 6 // Lesson 6.36: Component Design Systems & Headless UI Architecture\n\ndef solve():\n    \"\"\"\n    Verification: Build a production-ready, accessible, theme-aware DropdownMenu component using Radix primitives and \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.36", "subtopics_count": 6, "verification_criteria": "Build a production-ready, accessible, theme-aware DropdownMenu component using Radix primitives and Tailwind styling.", "subtopics": ["6.36.1 Design system architecture: design tokens, semantic naming (color, spacing, typography), and dark mode theming", "6.36.2 Headless UI pattern: separating component accessibility, keyboard navigation, and state logic from visual styling", "6.36.3 Radix UI / Floating UI primitives: anchor positioning, collision detection, portal rendering, and focus containment", "6.36.4 Tailwind CSS integration vs CSS Modules: class variance authority (cva), clsx, and tailwind-merge utility patterns", "6.36.5 Component polymorphism: the `asChild` pattern and polymorphic `as` prop implementations in TypeScript", "6.36.6 Building compound components: Select, DropdownMenu, Tabs, and Accordion with context communication"]}'::jsonb, '["Explain how this implementation prevents: Class name conflicts overriding critical design tokens; headless portal components breaking keyboard navigation order.", "How does Component Design Systems & Headless UI Architecture scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-37', 'phase-06-lesson-37-advanced-frontend-virtualization-infinite', 'module-8', 37, 'Lesson 8.37: Advanced Frontend Virtualization & Infinite Scrolling', 'Prerequisites: Lesson 6.1, Lesson 6.13', 'Prerequisites: Lesson 6.1, Lesson 6.13 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 1850.0, '# Lesson 6.37: Advanced Frontend Virtualization & Infinite Scrolling

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.1, Lesson 6.13
- **Subtopics**:
  - `6.37.1` DOM node explosion problem: memory consumption and layout calculation degradation with thousands of DOM nodes
  - `6.37.2` Virtualization architecture: viewport windowing, calculating visible row indices, and absolute item positioning
  - `6.37.3` TanStack Virtual (React Virtual) deep dive: fixed-size vs dynamic-size item height measurement
  - `6.37.4` Handling dynamic item heights: ResizeObserver, layout measuring, and scroll position correction
  - `6.37.5` Infinite scrolling integration: IntersectionObserver triggering batch page queries ahead of viewport bottom
  - `6.37.6` Scroll restoration: preserving exact scroll coordinates across client-side page transitions and browser back navigation
- **Key Failure Modes & Edge Cases**: Scroll jumping and jitter caused by uncalibrated dynamic item height changes; scrollbar thumb resizing erratically.
- **Verification & Mastery Check**: Build a virtualized data table rendering 100,000 live log rows smoothly at 60fps with variable row heights.
- **Project Application**: TenantIQ: Audit log viewer and real-time event streaming table.', '{"solution.py": "# Phase 6 // Lesson 6.37: Advanced Frontend Virtualization & Infinite Scrolling\n\ndef solve():\n    \"\"\"\n    Verification: Build a virtualized data table rendering 100,000 live log rows smoothly at 60fps with variable row h\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.37", "subtopics_count": 6, "verification_criteria": "Build a virtualized data table rendering 100,000 live log rows smoothly at 60fps with variable row heights.", "subtopics": ["6.37.1 DOM node explosion problem: memory consumption and layout calculation degradation with thousands of DOM nodes", "6.37.2 Virtualization architecture: viewport windowing, calculating visible row indices, and absolute item positioning", "6.37.3 TanStack Virtual (React Virtual) deep dive: fixed-size vs dynamic-size item height measurement", "6.37.4 Handling dynamic item heights: ResizeObserver, layout measuring, and scroll position correction", "6.37.5 Infinite scrolling integration: IntersectionObserver triggering batch page queries ahead of viewport bottom", "6.37.6 Scroll restoration: preserving exact scroll coordinates across client-side page transitions and browser back navigation"]}'::jsonb, '["Explain how this implementation prevents: Scroll jumping and jitter caused by uncalibrated dynamic item height changes; scrollbar thumb resizing erratically.", "How does Advanced Frontend Virtualization & Infinite Scrolling scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-38', 'phase-06-lesson-38-real-time-frontend-communication-server-s', 'module-8', 38, 'Lesson 8.38: Real-Time Frontend Communication: Server-Sent Events (SSE) & WebSockets', 'Prerequisites: Phase 4, Lesson 6.14', 'Prerequisites: Phase 4, Lesson 6.14 | Subtopics: 6 items', 'Systems project application', 220, 7, 1620.0, 1900.0, '# Lesson 6.38: Real-Time Frontend Communication: Server-Sent Events (SSE) & WebSockets

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 6.14
- **Subtopics**:
  - `6.38.1` Real-time paradigms comparison: Polling vs Long Polling vs Server-Sent Events (SSE) vs WebSockets
  - `6.38.2` EventSource API: connection lifecycle, automatic reconnection, event types, and Last-Event-ID header
  - `6.38.3` ReadableStream fetch for SSE: overcoming HTTP/1.1 connection limits (6 per domain) using HTTP/2 multiplexed streams
  - `6.38.4` WebSocket client implementation: connection handshake, binary vs text frames, heartbeats (ping/pong), and backoff
  - `6.38.5` Reconnection resilience: managing network dropouts, offline queues, and state synchronization upon reconnect
  - `6.38.6` Integrating streaming data into React: dispatching real-time updates into state without causing frame-dropping re-renders
- **Key Failure Modes & Edge Cases**: Browser exhausting 6-connection HTTP/1.1 limit with raw EventSource; UI freezing from high-frequency WebSocket message flood.
- **Verification & Mastery Check**: Build a real-time collaborative activity feed consuming SSE streams with automatic reconnection and token refresh.
- **Project Application**: TenantIQ: Real-time tenant collaborative notification feed.', '{"solution.py": "# Phase 6 // Lesson 6.38: Real-Time Frontend Communication: Server-Sent Events (SSE) & WebSockets\n\ndef solve():\n    \"\"\"\n    Verification: Build a real-time collaborative activity feed consuming SSE streams with automatic reconnection and \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.38", "subtopics_count": 6, "verification_criteria": "Build a real-time collaborative activity feed consuming SSE streams with automatic reconnection and token refresh.", "subtopics": ["6.38.1 Real-time paradigms comparison: Polling vs Long Polling vs Server-Sent Events (SSE) vs WebSockets", "6.38.2 EventSource API: connection lifecycle, automatic reconnection, event types, and Last-Event-ID header", "6.38.3 ReadableStream fetch for SSE: overcoming HTTP/1.1 connection limits (6 per domain) using HTTP/2 multiplexed streams", "6.38.4 WebSocket client implementation: connection handshake, binary vs text frames, heartbeats (ping/pong), and backoff", "6.38.5 Reconnection resilience: managing network dropouts, offline queues, and state synchronization upon reconnect", "6.38.6 Integrating streaming data into React: dispatching real-time updates into state without causing frame-dropping re-renders"]}'::jsonb, '["Explain how this implementation prevents: Browser exhausting 6-connection HTTP/1.1 limit with raw EventSource; UI freezing from high-frequency WebSocket message f", "How does Real-Time Frontend Communication: Server-Sent Events (SSE) & WebSockets scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-39', 'phase-06-lesson-39-frontend-authentication-flows-oauth2-open', 'module-8', 39, 'Lesson 8.39: Frontend Authentication Flows: OAuth2, OpenID Connect & Session Storage', 'Prerequisites: Phase 5, Lesson 6.6', 'Prerequisites: Phase 5, Lesson 6.6 | Subtopics: 6 items', 'Systems project application', 220, 7, 1500.0, 1950.0, '# Lesson 6.39: Frontend Authentication Flows: OAuth2, OpenID Connect & Session Storage

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Lesson 6.6
- **Subtopics**:
  - `6.39.1` OAuth2 & OIDC on the client: Authorization Code Flow with PKCE (Proof Key for Code Exchange) mechanics
  - `6.39.2` Token storage debate: LocalStorage vs In-Memory + Refresh Cookie vs HttpOnly SameSite Session Cookies
  - `6.39.3` Silent token refreshing: proactive token rotation before expiration using background iframe or fetch calls
  - `6.39.4` Handling authentication state in React: auth providers, route protection, and preventing flash-of-unauthenticated-content
  - `6.39.5` Multi-factor authentication (MFA) UI flows: TOTP code entry, recovery codes, and step-up authentication
  - `6.39.6` Single Sign-On (SSO) integration: SAML/OIDC enterprise redirects and directory synchronization concepts
- **Key Failure Modes & Edge Cases**: Storing access tokens in LocalStorage exposing them to XSS exfiltration; race conditions during simultaneous token refresh calls.
- **Verification & Mastery Check**: Implement a secure PKCE client-side auth flow with HttpOnly refresh cookies and seamless automatic background token rotation.
- **Project Application**: TenantIQ: Multi-tenant auth pipeline supporting magic links and Google OAuth.', '{"solution.py": "# Phase 6 // Lesson 6.39: Frontend Authentication Flows: OAuth2, OpenID Connect & Session Storage\n\ndef solve():\n    \"\"\"\n    Verification: Implement a secure PKCE client-side auth flow with HttpOnly refresh cookies and seamless automatic b\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.39", "subtopics_count": 6, "verification_criteria": "Implement a secure PKCE client-side auth flow with HttpOnly refresh cookies and seamless automatic background token rotation.", "subtopics": ["6.39.1 OAuth2 & OIDC on the client: Authorization Code Flow with PKCE (Proof Key for Code Exchange) mechanics", "6.39.2 Token storage debate: LocalStorage vs In-Memory + Refresh Cookie vs HttpOnly SameSite Session Cookies", "6.39.3 Silent token refreshing: proactive token rotation before expiration using background iframe or fetch calls", "6.39.4 Handling authentication state in React: auth providers, route protection, and preventing flash-of-unauthenticated-content", "6.39.5 Multi-factor authentication (MFA) UI flows: TOTP code entry, recovery codes, and step-up authentication", "6.39.6 Single Sign-On (SSO) integration: SAML/OIDC enterprise redirects and directory synchronization concepts"]}'::jsonb, '["Explain how this implementation prevents: Storing access tokens in LocalStorage exposing them to XSS exfiltration; race conditions during simultaneous token refre", "How does Frontend Authentication Flows: OAuth2, OpenID Connect & Session Storage scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-6-40', 'phase-06-lesson-40-payment-integration-stripe-elements-subsc', 'module-8', 40, 'Lesson 8.40: Payment Integration: Stripe Elements, Subscriptions & Checkout', 'Prerequisites: Lesson 6.34, Lesson 6.39', 'Prerequisites: Lesson 6.34, Lesson 6.39 | Subtopics: 6 items', 'Systems project application', 220, 7, 1560.0, 2000.0, '# Lesson 6.40: Payment Integration: Stripe Elements, Subscriptions & Checkout

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 6.34, Lesson 6.39
- **Subtopics**:
  - `6.40.1` Payment Card Industry Data Security Standard (PCI-DSS) client-side compliance: why raw card details never touch servers
  - `6.40.2` Stripe Elements architecture: sandboxed iframes, PaymentElement, and unified payment methods
  - `6.40.3` Subscription billing lifecycles: products, prices, billing intervals (monthly/annual), and trial periods
  - `6.40.4` Multi-tenant SaaS billing models: per-seat pricing, metered usage-based billing, and plan tiers
  - `6.40.5` Handling payment failures: 3D Secure authentication popups, SCA compliance, and invoice past_due recovery flows
  - `6.40.6` Customer Portal integration: delegating payment method updates, invoice downloads, and subscription cancellations to Stripe
- **Key Failure Modes & Edge Cases**: Failing to handle 3D Secure modal challenges causing payment abandonment; webhook processing races during checkout completion.
- **Verification & Mastery Check**: Implement a multi-tier SaaS billing upgrade flow with Stripe PaymentElement, subscription management, and webhook reconciliation.
- **Project Application**: TenantIQ: Billing checkout and subscription tier upgrade pipeline.', '{"solution.py": "# Phase 6 // Lesson 6.40: Payment Integration: Stripe Elements, Subscriptions & Checkout\n\ndef solve():\n    \"\"\"\n    Verification: Implement a multi-tier SaaS billing upgrade flow with Stripe PaymentElement, subscription management\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "6.40", "subtopics_count": 6, "verification_criteria": "Implement a multi-tier SaaS billing upgrade flow with Stripe PaymentElement, subscription management, and webhook reconciliation.", "subtopics": ["6.40.1 Payment Card Industry Data Security Standard (PCI-DSS) client-side compliance: why raw card details never touch servers", "6.40.2 Stripe Elements architecture: sandboxed iframes, PaymentElement, and unified payment methods", "6.40.3 Subscription billing lifecycles: products, prices, billing intervals (monthly/annual), and trial periods", "6.40.4 Multi-tenant SaaS billing models: per-seat pricing, metered usage-based billing, and plan tiers", "6.40.5 Handling payment failures: 3D Secure authentication popups, SCA compliance, and invoice past_due recovery flows", "6.40.6 Customer Portal integration: delegating payment method updates, invoice downloads, and subscription cancellations to Stripe"]}'::jsonb, '["Explain how this implementation prevents: Failing to handle 3D Secure modal challenges causing payment abandonment; webhook processing races during checkout compl", "How does Payment Integration: Stripe Elements, Subscriptions & Checkout scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-1', 'phase-08-lesson-01-the-4-step-system-design-interview-framew', 'module-9', 1, 'Lesson 9.1: The 4-Step System Design Interview Framework & Requirement Scoping', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 50.0, '# Lesson 8.1: The 4-Step System Design Interview Framework & Requirement Scoping

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `8.1.1` Step 1: Scoping functional requirements (core user journeys) vs non-functional requirements (latency, availability, scale)
  - `8.1.2` Defining out-of-scope boundaries to prevent architectural derailment during interview discussions
  - `8.1.3` Step 2: Back-of-the-envelope capacity estimation: QPS, bandwidth, storage, memory, and cache projections
  - `8.1.4` Step 3: High-Level Architecture (HLA): client, CDN, load balancer, API gateway, stateless services, cache, and database
  - `8.1.5` Step 4: Deep Dive & Bottlenecks: identifying single points of failure, partition tolerance, and failover workflows
  - `8.1.6` Collaborative communication: driving the discussion, active listening, asking clarifying questions, and managing time
- **Key Failure Modes & Edge Cases**: Jumping straight into database schemas or microservices without scoping functional and non-functional requirements.
- **Verification & Mastery Check**: Write a structured 1-page system requirements specification (SRS) for a global link shortening platform under 15 minutes.
- **Project Application**: System Design Portfolio: Requirement scoping templates.', '{"solution.py": "# Phase 8 // Lesson 8.1: The 4-Step System Design Interview Framework & Requirement Scoping\n\ndef solve():\n    \"\"\"\n    Verification: Write a structured 1-page system requirements specification (SRS) for a global link shortening platf\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.1", "subtopics_count": 6, "verification_criteria": "Write a structured 1-page system requirements specification (SRS) for a global link shortening platform under 15 minutes.", "subtopics": ["8.1.1 Step 1: Scoping functional requirements (core user journeys) vs non-functional requirements (latency, availability, scale)", "8.1.2 Defining out-of-scope boundaries to prevent architectural derailment during interview discussions", "8.1.3 Step 2: Back-of-the-envelope capacity estimation: QPS, bandwidth, storage, memory, and cache projections", "8.1.4 Step 3: High-Level Architecture (HLA): client, CDN, load balancer, API gateway, stateless services, cache, and database", "8.1.5 Step 4: Deep Dive & Bottlenecks: identifying single points of failure, partition tolerance, and failover workflows", "8.1.6 Collaborative communication: driving the discussion, active listening, asking clarifying questions, and managing time"]}'::jsonb, '["Explain how this implementation prevents: Jumping straight into database schemas or microservices without scoping functional and non-functional requirements.", "How does The 4-Step System Design Interview Framework & Requirement Scoping scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-2', 'phase-08-lesson-02-back-of-the-envelope-estimation-numbers-e', 'module-9', 2, 'Lesson 9.2: Back-of-the-Envelope Estimation: Numbers Every Engineer Must Know', 'Prerequisites: Phase 0, Lesson 8.1', 'Prerequisites: Phase 0, Lesson 8.1 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 100.0, '# Lesson 8.2: Back-of-the-Envelope Estimation: Numbers Every Engineer Must Know

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 8.1
- **Subtopics**:
  - `8.2.1` Latency numbers to memorize: L1 cache (1ns), RAM (100ns), SSD read (100µs), HDD seek (10ms), cross-datacenter RTT (150ms)
  - `8.2.2` Throughput calculations: converting Monthly Active Users (MAU) and Daily Active Users (DAU) to Read/Write QPS
  - `8.2.3` Peak multiplier heuristics: average QPS vs peak QPS (typically $2\times$ to $5\times$ average load)
  - `8.2.4` Storage volumetric estimation: bytes per record $\times$ records per day $\times$ retention years $\times$ replication factor
  - `8.2.5` Bandwidth volumetric estimation: ingress bandwidth (write QPS $\times$ payload size) vs egress bandwidth (read QPS $\times$ payload size)
  - `8.2.6` Memory and cache sizing: 80/20 Pareto rule (20% of hot data generates 80% of read traffic) memory provisioning
- **Key Failure Modes & Edge Cases**: Confusing bits (Gbps) with bytes (GB/s); failing to account for peak load spikes leading to 50% infrastructure under-provisioning.
- **Verification & Mastery Check**: Calculate exact QPS, storage (5-year), RAM cache, and bandwidth requirements for Twitter (500M DAU) with zero calculator aids.
- **Project Application**: System Design Portfolio: Automated capacity planning spreadsheet.', '{"solution.py": "# Phase 8 // Lesson 8.2: Back-of-the-Envelope Estimation: Numbers Every Engineer Must Know\n\ndef solve():\n    \"\"\"\n    Verification: Calculate exact QPS, storage (5-year), RAM cache, and bandwidth requirements for Twitter (500M DAU) \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.2", "subtopics_count": 6, "verification_criteria": "Calculate exact QPS, storage (5-year), RAM cache, and bandwidth requirements for Twitter (500M DAU) with zero calculator aids.", "subtopics": ["8.2.1 Latency numbers to memorize: L1 cache (1ns), RAM (100ns), SSD read (100\u00b5s), HDD seek (10ms), cross-datacenter RTT (150ms)", "8.2.2 Throughput calculations: converting Monthly Active Users (MAU) and Daily Active Users (DAU) to Read/Write QPS", "8.2.3 Peak multiplier heuristics: average QPS vs peak QPS (typically $2\\times$ to $5\\times$ average load)", "8.2.4 Storage volumetric estimation: bytes per record $\\times$ records per day $\\times$ retention years $\\times$ replication factor", "8.2.5 Bandwidth volumetric estimation: ingress bandwidth (write QPS $\\times$ payload size) vs egress bandwidth (read QPS $\\times$ payload size)", "8.2.6 Memory and cache sizing: 80/20 Pareto rule (20% of hot data generates 80% of read traffic) memory provisioning"]}'::jsonb, '["Explain how this implementation prevents: Confusing bits (Gbps) with bytes (GB/s); failing to account for peak load spikes leading to 50% infrastructure under-pro", "How does Back-of-the-Envelope Estimation: Numbers Every Engineer Must Know scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-3', 'phase-08-lesson-03-data-storage-paradigms-database-selection', 'module-9', 3, 'Lesson 9.3: Data Storage Paradigms & Database Selection Matrix', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 150.0, '# Lesson 8.3: Data Storage Paradigms & Database Selection Matrix

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `8.3.1` Relational (RDBMS) vs NoSQL: ACID guarantees vs horizontal scalability, schema flexibility, and query patterns
  - `8.3.2` Document stores (MongoDB): nested denormalized hierarchical documents, index structures, and write-heavy workloads
  - `8.3.3` Wide-column stores (Cassandra, ScyllaDB): log-structured merge trees (LSM), tunable consistency, high write throughput
  - `8.3.4` Key-Value stores (Redis, DynamoDB): lightning sub-millisecond lookups, TTL expirations, and partition keys
  - `8.3.5` Graph databases (Neo4j): vertex and edge traversal, index-free adjacency, and social graph fraud detection
  - `8.3.6` Time-series databases (InfluxDB, TimescaleDB): columnar compression, downsampling, and high-frequency sensor/metric ingestion
- **Key Failure Modes & Edge Cases**: Choosing NoSQL for financial balances without transactional multi-record atomicity; choosing RDBMS for petabyte append-only logs.
- **Verification & Mastery Check**: Draft a comprehensive technical decision matrix comparing PostgreSQL, Cassandra, DynamoDB, and Redis across 8 operational criteria.
- **Project Application**: System Design Portfolio: Database architectural selection guide.', '{"solution.py": "# Phase 8 // Lesson 8.3: Data Storage Paradigms & Database Selection Matrix\n\ndef solve():\n    \"\"\"\n    Verification: Draft a comprehensive technical decision matrix comparing PostgreSQL, Cassandra, DynamoDB, and Redis\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.3", "subtopics_count": 6, "verification_criteria": "Draft a comprehensive technical decision matrix comparing PostgreSQL, Cassandra, DynamoDB, and Redis across 8 operational criteria.", "subtopics": ["8.3.1 Relational (RDBMS) vs NoSQL: ACID guarantees vs horizontal scalability, schema flexibility, and query patterns", "8.3.2 Document stores (MongoDB): nested denormalized hierarchical documents, index structures, and write-heavy workloads", "8.3.3 Wide-column stores (Cassandra, ScyllaDB): log-structured merge trees (LSM), tunable consistency, high write throughput", "8.3.4 Key-Value stores (Redis, DynamoDB): lightning sub-millisecond lookups, TTL expirations, and partition keys", "8.3.5 Graph databases (Neo4j): vertex and edge traversal, index-free adjacency, and social graph fraud detection", "8.3.6 Time-series databases (InfluxDB, TimescaleDB): columnar compression, downsampling, and high-frequency sensor/metric ingestion"]}'::jsonb, '["Explain how this implementation prevents: Choosing NoSQL for financial balances without transactional multi-record atomicity; choosing RDBMS for petabyte append-o", "How does Data Storage Paradigms & Database Selection Matrix scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-4', 'phase-08-lesson-04-caching-architectures-invalidation-thunde', 'module-9', 4, 'Lesson 9.4: Caching Architectures: Invalidation, Thundering Herd & Topologies', 'Prerequisites: Phase 4, Lesson 8.2', 'Prerequisites: Phase 4, Lesson 8.2 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 200.0, '# Lesson 8.4: Caching Architectures: Invalidation, Thundering Herd & Topologies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 8.2
- **Subtopics**:
  - `8.4.1` Caching topologies: In-memory local cache vs Distributed cache clusters (Redis, Memcached) vs Multi-tier caching
  - `8.4.2` Cache access patterns: Cache-Aside (Lazy Loading), Read-Through, Write-Through, and Write-Behind (Write-Back)
  - `8.4.3` Cache eviction policies: Least Recently Used (LRU), Least Frequently Used (LFU), First In First Out (FIFO)
  - `8.4.4` Cache Invalidation problems: cache stampede / thundering herd mitigation using mutex locking, probabilistic early expiration (XFetch)
  - `8.4.5` Cache Penetration (queries for non-existent keys): mitigating via null caching and Bloom filters
  - `8.4.6` Cache Breakdown (hot key expiry) and Cache Avalanche (simultaneous massive key expirations) mitigation with TTL jitter
- **Key Failure Modes & Edge Cases**: Cache avalanche crashing core databases when 100,000 keys expire at midnight simultaneously without randomized TTL jitter.
- **Verification & Mastery Check**: Implement the XFetch probabilistic early cache expiration algorithm in Python; simulate high-concurrency read traffic under load.
- **Project Application**: System Design Portfolio: High-throughput caching architectural patterns.', '{"solution.py": "# Phase 8 // Lesson 8.4: Caching Architectures: Invalidation, Thundering Herd & Topologies\n\ndef solve():\n    \"\"\"\n    Verification: Implement the XFetch probabilistic early cache expiration algorithm in Python; simulate high-concurr\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.4", "subtopics_count": 6, "verification_criteria": "Implement the XFetch probabilistic early cache expiration algorithm in Python; simulate high-concurrency read traffic under load.", "subtopics": ["8.4.1 Caching topologies: In-memory local cache vs Distributed cache clusters (Redis, Memcached) vs Multi-tier caching", "8.4.2 Cache access patterns: Cache-Aside (Lazy Loading), Read-Through, Write-Through, and Write-Behind (Write-Back)", "8.4.3 Cache eviction policies: Least Recently Used (LRU), Least Frequently Used (LFU), First In First Out (FIFO)", "8.4.4 Cache Invalidation problems: cache stampede / thundering herd mitigation using mutex locking, probabilistic early expiration (XFetch)", "8.4.5 Cache Penetration (queries for non-existent keys): mitigating via null caching and Bloom filters", "8.4.6 Cache Breakdown (hot key expiry) and Cache Avalanche (simultaneous massive key expirations) mitigation with TTL jitter"]}'::jsonb, '["Explain how this implementation prevents: Cache avalanche crashing core databases when 100,000 keys expire at midnight simultaneously without randomized TTL jitte", "How does Caching Architectures: Invalidation, Thundering Herd & Topologies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-5', 'phase-08-lesson-05-load-balancing-reverse-proxies-anycast-ro', 'module-9', 5, 'Lesson 9.5: Load Balancing, Reverse Proxies & Anycast Routing', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 250.0, '# Lesson 8.5: Load Balancing, Reverse Proxies & Anycast Routing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `8.5.1` Layer 4 (Transport, TCP/UDP) vs Layer 7 (Application, HTTP/gRPC) load balancing trade-offs and SSL termination
  - `8.5.2` Load balancing algorithms: Round Robin, Weighted Least Connections, IP Hash, and Consistent Hashing
  - `8.5.3` Anycast BGP routing: announcing the same IP address globally to route client traffic to the nearest topological datacenter
  - `8.5.4` Reverse proxy mechanics: NGINX and Envoy proxy internals, connection pooling, buffer management, and gzip/brotli compression
  - `8.5.5` Direct Server Return (DSR): high-throughput video streaming optimization bypassing load balancers for egress traffic
  - `8.5.6` High-availability load balancers: Active-Passive configurations using VRRP (Virtual Router Redundancy Protocol) and Keepalived
- **Key Failure Modes & Edge Cases**: Layer 7 load balancer becoming CPU-bound due to un-offloaded TLS handshakes without dedicated cryptographic hardware.
- **Verification & Mastery Check**: Configure an Envoy proxy topology demonstrating Layer 7 content-based routing, weighted canary traffic splitting, and circuit breaking.
- **Project Application**: System Design Portfolio: Global edge routing and load balancing blueprints.', '{"solution.py": "# Phase 8 // Lesson 8.5: Load Balancing, Reverse Proxies & Anycast Routing\n\ndef solve():\n    \"\"\"\n    Verification: Configure an Envoy proxy topology demonstrating Layer 7 content-based routing, weighted canary traff\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.5", "subtopics_count": 6, "verification_criteria": "Configure an Envoy proxy topology demonstrating Layer 7 content-based routing, weighted canary traffic splitting, and circuit breaking.", "subtopics": ["8.5.1 Layer 4 (Transport, TCP/UDP) vs Layer 7 (Application, HTTP/gRPC) load balancing trade-offs and SSL termination", "8.5.2 Load balancing algorithms: Round Robin, Weighted Least Connections, IP Hash, and Consistent Hashing", "8.5.3 Anycast BGP routing: announcing the same IP address globally to route client traffic to the nearest topological datacenter", "8.5.4 Reverse proxy mechanics: NGINX and Envoy proxy internals, connection pooling, buffer management, and gzip/brotli compression", "8.5.5 Direct Server Return (DSR): high-throughput video streaming optimization bypassing load balancers for egress traffic", "8.5.6 High-availability load balancers: Active-Passive configurations using VRRP (Virtual Router Redundancy Protocol) and Keepalived"]}'::jsonb, '["Explain how this implementation prevents: Layer 7 load balancer becoming CPU-bound due to un-offloaded TLS handshakes without dedicated cryptographic hardware.", "How does Load Balancing, Reverse Proxies & Anycast Routing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-6', 'phase-08-lesson-06-api-gateway-architectures-rate-limiting-a', 'module-9', 6, 'Lesson 9.6: API Gateway Architectures, Rate Limiting & Aggregation', 'Prerequisites: Phase 4, Lesson 8.5', 'Prerequisites: Phase 4, Lesson 8.5 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 300.0, '# Lesson 8.6: API Gateway Architectures, Rate Limiting & Aggregation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 8.5
- **Subtopics**:
  - `8.6.1` API Gateway responsibilities: request routing, protocol translation (gRPC to JSON), authentication, and telemetry
  - `8.6.2` Backend-For-Frontend (BFF) pattern: tailored API gateways for mobile, web, and public developer clients
  - `8.6.3` Distributed Rate Limiting algorithms: Token Bucket, Leaky Bucket, Sliding Window Counter with Redis and Lua scripts
  - `8.6.4` Distributed rate limiting synchronization: centralized Redis vs local memory with gossip protocol synchronization
  - `8.6.5` Request aggregation and batching: combining multiple microservice calls into single client responses to reduce latency
  - `8.6.6` Security controls at the gateway: IP whitelisting, geo-blocking, DDoS mitigation, and WAF rule evaluation
- **Key Failure Modes & Edge Cases**: Centralized Redis rate limiter creating a single point of failure and adding 10ms latency overhead to every API request.
- **Verification & Mastery Check**: Implement a sliding window counter rate limiter in Redis Lua script handling 50,000 concurrent requests with zero race conditions.
- **Project Application**: System Design Portfolio: Enterprise API Gateway and rate limiting architecture.', '{"solution.py": "# Phase 8 // Lesson 8.6: API Gateway Architectures, Rate Limiting & Aggregation\n\ndef solve():\n    \"\"\"\n    Verification: Implement a sliding window counter rate limiter in Redis Lua script handling 50,000 concurrent reque\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.6", "subtopics_count": 6, "verification_criteria": "Implement a sliding window counter rate limiter in Redis Lua script handling 50,000 concurrent requests with zero race conditions.", "subtopics": ["8.6.1 API Gateway responsibilities: request routing, protocol translation (gRPC to JSON), authentication, and telemetry", "8.6.2 Backend-For-Frontend (BFF) pattern: tailored API gateways for mobile, web, and public developer clients", "8.6.3 Distributed Rate Limiting algorithms: Token Bucket, Leaky Bucket, Sliding Window Counter with Redis and Lua scripts", "8.6.4 Distributed rate limiting synchronization: centralized Redis vs local memory with gossip protocol synchronization", "8.6.5 Request aggregation and batching: combining multiple microservice calls into single client responses to reduce latency", "8.6.6 Security controls at the gateway: IP whitelisting, geo-blocking, DDoS mitigation, and WAF rule evaluation"]}'::jsonb, '["Explain how this implementation prevents: Centralized Redis rate limiter creating a single point of failure and adding 10ms latency overhead to every API request.", "How does API Gateway Architectures, Rate Limiting & Aggregation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-7', 'phase-08-lesson-07-message-queues-vs-event-streams-decouplin', 'module-9', 7, 'Lesson 9.7: Message Queues vs Event Streams: Decoupling Asynchronous Systems', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 350.0, '# Lesson 8.7: Message Queues vs Event Streams: Decoupling Asynchronous Systems

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `8.7.1` Queue-based messaging (RabbitMQ, SQS): push model, message acknowledgment, individual message consumption, worker pools
  - `8.7.2` Log-based event streaming (Kafka, Kinesis): pull model, partitioned commit logs, ordered replayability, consumer groups
  - `8.7.3` Choosing between Queues and Streams: complex routing/task distribution vs high-throughput real-time event analytics
  - `8.7.4` Message delivery guarantees: At-most-once, At-least-once, Exactly-once processing (idempotent consumers)
  - `8.7.5` Dead Letter Queues (DLQ) and retry backoff strategies: handling poisoned messages without blocking queue pipelines
  - `8.7.6` Event-driven architecture patterns: Event Sourcing, Command Query Responsibility Segregation (CQRS), and Saga choreography
- **Key Failure Modes & Edge Cases**: Using a message queue as a permanent database without understanding broker storage limits and memory backpressure.
- **Verification & Mastery Check**: Design an end-to-end asynchronous order processing architecture comparing RabbitMQ task queues with Kafka event streaming.
- **Project Application**: System Design Portfolio: Asynchronous event messaging blueprints.', '{"solution.py": "# Phase 8 // Lesson 8.7: Message Queues vs Event Streams: Decoupling Asynchronous Systems\n\ndef solve():\n    \"\"\"\n    Verification: Design an end-to-end asynchronous order processing architecture comparing RabbitMQ task queues with \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.7", "subtopics_count": 6, "verification_criteria": "Design an end-to-end asynchronous order processing architecture comparing RabbitMQ task queues with Kafka event streaming.", "subtopics": ["8.7.1 Queue-based messaging (RabbitMQ, SQS): push model, message acknowledgment, individual message consumption, worker pools", "8.7.2 Log-based event streaming (Kafka, Kinesis): pull model, partitioned commit logs, ordered replayability, consumer groups", "8.7.3 Choosing between Queues and Streams: complex routing/task distribution vs high-throughput real-time event analytics", "8.7.4 Message delivery guarantees: At-most-once, At-least-once, Exactly-once processing (idempotent consumers)", "8.7.5 Dead Letter Queues (DLQ) and retry backoff strategies: handling poisoned messages without blocking queue pipelines", "8.7.6 Event-driven architecture patterns: Event Sourcing, Command Query Responsibility Segregation (CQRS), and Saga choreography"]}'::jsonb, '["Explain how this implementation prevents: Using a message queue as a permanent database without understanding broker storage limits and memory backpressure.", "How does Message Queues vs Event Streams: Decoupling Asynchronous Systems scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-8', 'phase-08-lesson-08-database-sharding-partitioning-rebalancin', 'module-9', 8, 'Lesson 9.8: Database Sharding, Partitioning & Rebalancing Strategies', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 400.0, '# Lesson 8.8: Database Sharding, Partitioning & Rebalancing Strategies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `8.8.1` Vertical partitioning (splitting columns) vs Horizontal partitioning / Sharding (splitting rows across machines)
  - `8.8.2` Sharding key selection: cardinality, query access patterns, avoiding hot spots (celebrity problem)
  - `8.8.3` Sharding strategies: Range-based sharding vs Hash-based sharding vs Directory-based (lookup table) sharding
  - `8.8.4` Consistent Hashing in database sharding: minimizing data movement during node additions and removals
  - `8.8.5` Cross-shard queries and joins: scatter-gather queries, two-phase commit over shards, and why cross-shard joins are anti-patterns
  - `8.8.6` Live sharding rebalancing: migrating partitions online without downtime using dual-writes and asynchronous reconciliation
- **Key Failure Modes & Edge Cases**: Selecting a monotonically increasing auto-increment ID as sharding key, concentrating 100% of all write traffic on the latest single shard.
- **Verification & Mastery Check**: Implement a consistent hashing sharding manager in Python mapping keys across 16 database shards with virtual node balancing.
- **Project Application**: System Design Portfolio: Scalable database sharding architecture.', '{"solution.py": "# Phase 8 // Lesson 8.8: Database Sharding, Partitioning & Rebalancing Strategies\n\ndef solve():\n    \"\"\"\n    Verification: Implement a consistent hashing sharding manager in Python mapping keys across 16 database shards wit\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.8", "subtopics_count": 6, "verification_criteria": "Implement a consistent hashing sharding manager in Python mapping keys across 16 database shards with virtual node balancing.", "subtopics": ["8.8.1 Vertical partitioning (splitting columns) vs Horizontal partitioning / Sharding (splitting rows across machines)", "8.8.2 Sharding key selection: cardinality, query access patterns, avoiding hot spots (celebrity problem)", "8.8.3 Sharding strategies: Range-based sharding vs Hash-based sharding vs Directory-based (lookup table) sharding", "8.8.4 Consistent Hashing in database sharding: minimizing data movement during node additions and removals", "8.8.5 Cross-shard queries and joins: scatter-gather queries, two-phase commit over shards, and why cross-shard joins are anti-patterns", "8.8.6 Live sharding rebalancing: migrating partitions online without downtime using dual-writes and asynchronous reconciliation"]}'::jsonb, '["Explain how this implementation prevents: Selecting a monotonically increasing auto-increment ID as sharding key, concentrating 100% of all write traffic on the l", "How does Database Sharding, Partitioning & Rebalancing Strategies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-9', 'phase-08-lesson-09-high-availability-redundancy-active-activ', 'module-9', 9, 'Lesson 9.9: High Availability, Redundancy & Active-Active Failover', 'Prerequisites: Phase 7, Lesson 8.8', 'Prerequisites: Phase 7, Lesson 8.8 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 450.0, '# Lesson 8.9: High Availability, Redundancy & Active-Active Failover

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 8.8
- **Subtopics**:
  - `8.9.1` High Availability (HA) metrics: 99.9% (Three Nines, 8.76h downtime/yr) vs 99.999% (Five Nines, 5.26m downtime/yr)
  - `8.9.2` Redundancy models: Active-Passive (Warm/Cold standby) vs Active-Active multi-region deployment architectures
  - `8.9.3` Automated failover mechanics: health heartbeats, split-brain detection, fencing tokens, and DNS TTL considerations
  - `8.9.4` Active-Active data synchronization: conflict-free replication, asynchronous cross-region replication, and multi-master conflicts
  - `8.9.5` GeoDNS and Latency-based Anycast routing: steering global users dynamically to healthy regions during catastrophic disasters
  - `8.9.6` Designing for disaster recovery: mean time to detect (MTTD), mean time to recover (MTTR), and chaos game days
- **Key Failure Modes & Edge Cases**: Split-brain condition causing two active masters in different datacenters to accept conflicting writes during network partition.
- **Verification & Mastery Check**: Draft an Active-Active multi-region architecture diagram with failover runbooks and split-brain fencing token safety proofs.
- **Project Application**: System Design Portfolio: Global multi-region high-availability blueprint.', '{"solution.py": "# Phase 8 // Lesson 8.9: High Availability, Redundancy & Active-Active Failover\n\ndef solve():\n    \"\"\"\n    Verification: Draft an Active-Active multi-region architecture diagram with failover runbooks and split-brain fenc\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.9", "subtopics_count": 6, "verification_criteria": "Draft an Active-Active multi-region architecture diagram with failover runbooks and split-brain fencing token safety proofs.", "subtopics": ["8.9.1 High Availability (HA) metrics: 99.9% (Three Nines, 8.76h downtime/yr) vs 99.999% (Five Nines, 5.26m downtime/yr)", "8.9.2 Redundancy models: Active-Passive (Warm/Cold standby) vs Active-Active multi-region deployment architectures", "8.9.3 Automated failover mechanics: health heartbeats, split-brain detection, fencing tokens, and DNS TTL considerations", "8.9.4 Active-Active data synchronization: conflict-free replication, asynchronous cross-region replication, and multi-master conflicts", "8.9.5 GeoDNS and Latency-based Anycast routing: steering global users dynamically to healthy regions during catastrophic disasters", "8.9.6 Designing for disaster recovery: mean time to detect (MTTD), mean time to recover (MTTR), and chaos game days"]}'::jsonb, '["Explain how this implementation prevents: Split-brain condition causing two active masters in different datacenters to accept conflicting writes during network pa", "How does High Availability, Redundancy & Active-Active Failover scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-10', 'phase-08-lesson-10-unique-id-generation-at-scale-snowflake-u', 'module-9', 10, 'Lesson 9.10: Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers', 'Prerequisites: Phase 0, Phase 7', 'Prerequisites: Phase 0, Phase 7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 500.0, '# Lesson 8.10: Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 7
- **Subtopics**:
  - `8.10.1` Unique ID requirements: 64-bit size, globally unique, roughly time-ordered, high generation throughput (>1M IDs/sec)
  - `8.10.2` UUIDv4 limitations: 128-bit size, completely random ordering causing catastrophic B-tree fragmentation and index bloat
  - `8.10.3` UUIDv7 modern standard: Unix timestamp prefix + random suffix combining time-ordering with standard 128-bit formats
  - `8.10.4` Flickr Ticket Server: centralized MySQL servers with auto-increment and `REPLACE INTO` statements (single point of failure risks)
  - `8.10.5` Twitter Snowflake architecture: 1-bit unused, 41-bit timestamp (epoch ms), 10-bit machine/worker ID, 12-bit sequence number
  - `8.10.6` Handling clock drift in Snowflake: NTP backwards time adjustments, refusing generation, or waiting for clock synchronization
- **Key Failure Modes & Edge Cases**: Server clock moving backwards during NTP sync generating duplicate IDs in Twitter Snowflake algorithm without drift safeguards.
- **Verification & Mastery Check**: Implement a fully functional Twitter Snowflake 64-bit ID generator in Python handling 4,096 IDs per millisecond with clock rollback checks.
- **Project Application**: System Design Portfolio: Distributed ID generation system design.', '{"solution.py": "# Phase 8 // Lesson 8.10: Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers\n\ndef solve():\n    \"\"\"\n    Verification: Implement a fully functional Twitter Snowflake 64-bit ID generator in Python handling 4,096 IDs per \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.10", "subtopics_count": 6, "verification_criteria": "Implement a fully functional Twitter Snowflake 64-bit ID generator in Python handling 4,096 IDs per millisecond with clock rollback checks.", "subtopics": ["8.10.1 Unique ID requirements: 64-bit size, globally unique, roughly time-ordered, high generation throughput (>1M IDs/sec)", "8.10.2 UUIDv4 limitations: 128-bit size, completely random ordering causing catastrophic B-tree fragmentation and index bloat", "8.10.3 UUIDv7 modern standard: Unix timestamp prefix + random suffix combining time-ordering with standard 128-bit formats", "8.10.4 Flickr Ticket Server: centralized MySQL servers with auto-increment and `REPLACE INTO` statements (single point of failure risks)", "8.10.5 Twitter Snowflake architecture: 1-bit unused, 41-bit timestamp (epoch ms), 10-bit machine/worker ID, 12-bit sequence number", "8.10.6 Handling clock drift in Snowflake: NTP backwards time adjustments, refusing generation, or waiting for clock synchronization"]}'::jsonb, '["Explain how this implementation prevents: Server clock moving backwards during NTP sync generating duplicate IDs in Twitter Snowflake algorithm without drift safe", "How does Unique ID Generation at Scale: Snowflake, UUIDv7 & Ticket Servers scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-11', 'phase-08-lesson-11-system-deep-dive-1-global-url-shortener-t', 'module-9', 11, 'Lesson 9.11: System Deep Dive 1: Global URL Shortener (TinyURL / Bitly)', 'Prerequisites: Lesson 8.1, Lesson 8.10', 'Prerequisites: Lesson 8.1, Lesson 8.10 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 550.0, '# Lesson 8.11: System Deep Dive 1: Global URL Shortener (TinyURL / Bitly)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.1, Lesson 8.10
- **Subtopics**:
  - `8.11.1` Requirements: 100M URLs created/month, 100:1 read-to-write ratio, sub-10ms redirection latency, custom alias support
  - `8.11.2` Capacity estimation: 100M writes/month $\approx 40$ write QPS, 4,000 read QPS; 5-year storage: $\approx 15\text{TB}$
  - `8.11.3` URL encoding algorithms: Base62 encoding (a-z, A-Z, 0-9) vs MD5/SHA256 hashing truncation with collision handling
  - `8.11.4` Pre-generated Key Generation Service (KGS): dedicated service generating unique Base62 tokens ahead of time into Redis/DB
  - `8.11.5` Data modeling: relational vs NoSQL schema, primary keys, indexing short URL tokens, and expiration timestamps
  - `8.11.6` High-performance redirection: HTTP 301 Permanent Redirect (client caching) vs HTTP 302 Temporary Redirect (telemetry tracking)
- **Key Failure Modes & Edge Cases**: Using HTTP 301 preventing server-side click analytics tracking; MD5 hash collisions requiring expensive database retry loops.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for TinyURL featuring KGS token generation, Redis caching, and Cassandra storage.
- **Project Application**: System Design Portfolio: Project 1 - Global URL Shortener.', '{"solution.py": "# Phase 8 // Lesson 8.11: System Deep Dive 1: Global URL Shortener (TinyURL / Bitly)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for TinyURL featuring KGS token generation, Redis caching\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.11", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for TinyURL featuring KGS token generation, Redis caching, and Cassandra storage.", "subtopics": ["8.11.1 Requirements: 100M URLs created/month, 100:1 read-to-write ratio, sub-10ms redirection latency, custom alias support", "8.11.2 Capacity estimation: 100M writes/month $\\approx 40$ write QPS, 4,000 read QPS; 5-year storage: $\\approx 15\\text{TB}$", "8.11.3 URL encoding algorithms: Base62 encoding (a-z, A-Z, 0-9) vs MD5/SHA256 hashing truncation with collision handling", "8.11.4 Pre-generated Key Generation Service (KGS): dedicated service generating unique Base62 tokens ahead of time into Redis/DB", "8.11.5 Data modeling: relational vs NoSQL schema, primary keys, indexing short URL tokens, and expiration timestamps", "8.11.6 High-performance redirection: HTTP 301 Permanent Redirect (client caching) vs HTTP 302 Temporary Redirect (telemetry tracking)"]}'::jsonb, '["Explain how this implementation prevents: Using HTTP 301 preventing server-side click analytics tracking; MD5 hash collisions requiring expensive database retry l", "How does System Deep Dive 1: Global URL Shortener (TinyURL / Bitly) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-12', 'phase-08-lesson-12-system-deep-dive-2-high-throughput-distri', 'module-9', 12, 'Lesson 9.12: System Deep Dive 2: High-Throughput Distributed Rate Limiter', 'Prerequisites: Lesson 8.6, Lesson 8.10', 'Prerequisites: Lesson 8.6, Lesson 8.10 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 600.0, '# Lesson 8.12: System Deep Dive 2: High-Throughput Distributed Rate Limiter

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.6, Lesson 8.10
- **Subtopics**:
  - `8.12.1` Requirements: protect APIs from DDoS and abuse, enforce multi-tier tenant quotas, sub-2ms latency overhead
  - `8.12.2` Capacity estimation: 1,000,000 requests/second global API ingress; tracking millions of unique client IP/API keys
  - `8.12.3` Algorithm trade-offs: Token Bucket vs Sliding Window Counter vs Leaky Bucket across high concurrency
  - `8.12.4` Distributed architecture: Edge API gateways with local caching + central Redis clusters using pipelined Lua scripts
  - `8.12.5` Race condition mitigation: eliminating check-then-set race conditions using atomic Redis Lua scripts
  - `8.12.6` Handling Redis cluster outages: failing open (allowing traffic) vs failing closed (blocking traffic) under security SLAs
- **Key Failure Modes & Edge Cases**: Failing closed during rate limiter redis outage, taking down entire company API for all legitimate paying customers.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for an enterprise rate limiter handling 1M QPS with localized synchronization.
- **Project Application**: System Design Portfolio: Project 2 - Distributed Rate Limiter.', '{"solution.py": "# Phase 8 // Lesson 8.12: System Deep Dive 2: High-Throughput Distributed Rate Limiter\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for an enterprise rate limiter handling 1M QPS with local\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.12", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for an enterprise rate limiter handling 1M QPS with localized synchronization.", "subtopics": ["8.12.1 Requirements: protect APIs from DDoS and abuse, enforce multi-tier tenant quotas, sub-2ms latency overhead", "8.12.2 Capacity estimation: 1,000,000 requests/second global API ingress; tracking millions of unique client IP/API keys", "8.12.3 Algorithm trade-offs: Token Bucket vs Sliding Window Counter vs Leaky Bucket across high concurrency", "8.12.4 Distributed architecture: Edge API gateways with local caching + central Redis clusters using pipelined Lua scripts", "8.12.5 Race condition mitigation: eliminating check-then-set race conditions using atomic Redis Lua scripts", "8.12.6 Handling Redis cluster outages: failing open (allowing traffic) vs failing closed (blocking traffic) under security SLAs"]}'::jsonb, '["Explain how this implementation prevents: Failing closed during rate limiter redis outage, taking down entire company API for all legitimate paying customers.", "How does System Deep Dive 2: High-Throughput Distributed Rate Limiter scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-13', 'phase-08-lesson-13-system-deep-dive-3-distributed-web-crawle', 'module-9', 13, 'Lesson 9.13: System Deep Dive 3: Distributed Web Crawler & Indexer', 'Prerequisites: Lesson 8.3, Lesson 8.7', 'Prerequisites: Lesson 8.3, Lesson 8.7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2060.0, 650.0, '# Lesson 8.13: System Deep Dive 3: Distributed Web Crawler & Indexer

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.3, Lesson 8.7
- **Subtopics**:
  - `8.13.1` Requirements: crawl 1 billion web pages per month, respect robots.txt, avoid infinite crawl traps, extract links and text
  - `8.13.2` Capacity estimation: 1B pages/month $\approx 400$ pages/sec; storing raw HTML (100TB/month), inverted index extraction
  - `8.13.3` Crawl frontier architecture: prioritized queues, politeness queues (per-host rate limiting), and DNS caching layer
  - `8.13.4` Duplicate URL detection: Fingerprinting web page content using SimHash and 64-bit Bloom filters for billions of URLs
  - `8.13.5` Distributed worker architecture: stateless crawler pods, distributed task scheduling via Kafka, and S3 object storage ingestion
  - `8.13.6` Parsing & extraction pipeline: headless browser rendering (for JS-rendered SPAs) vs lightweight HTTP parsing trade-offs
- **Key Failure Modes & Edge Cases**: Getting caught in infinite calendar crawl traps (`/calendar?day=X+1`); overloading small web servers violating politeness rules.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for a distributed web crawler crawling 1B pages with SimHash deduplication.
- **Project Application**: System Design Portfolio: Project 3 - Distributed Web Crawler.', '{"solution.py": "# Phase 8 // Lesson 8.13: System Deep Dive 3: Distributed Web Crawler & Indexer\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for a distributed web crawler crawling 1B pages with SimH\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.13", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for a distributed web crawler crawling 1B pages with SimHash deduplication.", "subtopics": ["8.13.1 Requirements: crawl 1 billion web pages per month, respect robots.txt, avoid infinite crawl traps, extract links and text", "8.13.2 Capacity estimation: 1B pages/month $\\approx 400$ pages/sec; storing raw HTML (100TB/month), inverted index extraction", "8.13.3 Crawl frontier architecture: prioritized queues, politeness queues (per-host rate limiting), and DNS caching layer", "8.13.4 Duplicate URL detection: Fingerprinting web page content using SimHash and 64-bit Bloom filters for billions of URLs", "8.13.5 Distributed worker architecture: stateless crawler pods, distributed task scheduling via Kafka, and S3 object storage ingestion", "8.13.6 Parsing & extraction pipeline: headless browser rendering (for JS-rendered SPAs) vs lightweight HTTP parsing trade-offs"]}'::jsonb, '["Explain how this implementation prevents: Getting caught in infinite calendar crawl traps (`/calendar?day=X+1`); overloading small web servers violating politenes", "How does System Deep Dive 3: Distributed Web Crawler & Indexer scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-14', 'phase-08-lesson-14-system-deep-dive-4-real-time-social-media', 'module-9', 14, 'Lesson 9.14: System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X)', 'Prerequisites: Lesson 8.4, Lesson 8.7', 'Prerequisites: Lesson 8.4, Lesson 8.7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2120.0, 700.0, '# Lesson 8.14: System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.4, Lesson 8.7
- **Subtopics**:
  - `8.14.1` Requirements: 500M DAU, post tweets, follow users, generate timeline news feeds, real-time fanout
  - `8.14.2` Capacity estimation: 500M DAU, 5,000 tweets/sec average, 25,000 peak; timeline reads 500,000 QPS
  - `8.14.3` Fanout-on-Write (Push model): writing tweet IDs directly into followers'' Redis home timeline lists upon post
  - `8.14.4` Fanout-on-Read (Pull model): fetching and merging tweets dynamically when a user requests their timeline
  - `8.14.5` The Celebrity / Hotspot Problem: why Push models fail for users with 100M followers (Taylor Swift, Elon Musk)
  - `8.14.6` Hybrid Fanout Architecture: Push for standard users, Pull for high-follower celebrity accounts, merged at read time
- **Key Failure Modes & Edge Cases**: Attempting Push fanout on a 100M follower user causing 10-minute fanout processing lag and overwhelming Redis cluster queues.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for Twitter''s news feed using hybrid push/pull fanout and Redis caching.
- **Project Application**: System Design Portfolio: Project 4 - Social Media News Feed.', '{"solution.py": "# Phase 8 // Lesson 8.14: System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for Twitter''s news feed using hybrid push/pull fanout and\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.14", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for Twitter''s news feed using hybrid push/pull fanout and Redis caching.", "subtopics": ["8.14.1 Requirements: 500M DAU, post tweets, follow users, generate timeline news feeds, real-time fanout", "8.14.2 Capacity estimation: 500M DAU, 5,000 tweets/sec average, 25,000 peak; timeline reads 500,000 QPS", "8.14.3 Fanout-on-Write (Push model): writing tweet IDs directly into followers'' Redis home timeline lists upon post", "8.14.4 Fanout-on-Read (Pull model): fetching and merging tweets dynamically when a user requests their timeline", "8.14.5 The Celebrity / Hotspot Problem: why Push models fail for users with 100M followers (Taylor Swift, Elon Musk)", "8.14.6 Hybrid Fanout Architecture: Push for standard users, Pull for high-follower celebrity accounts, merged at read time"]}'::jsonb, '["Explain how this implementation prevents: Attempting Push fanout on a 100M follower user causing 10-minute fanout processing lag and overwhelming Redis cluster qu", "How does System Deep Dive 4: Real-Time Social Media News Feed (Twitter / X) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-8-15', 'phase-08-lesson-15-system-deep-dive-5-global-real-time-chat-', 'module-9', 15, 'Lesson 9.15: System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack)', 'Prerequisites: Lesson 8.5, Lesson 8.7', 'Prerequisites: Lesson 8.5, Lesson 8.7 | Subtopics: 6 items', 'Systems project application', 260, 9, 2000.0, 750.0, '# Lesson 8.15: System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 8.5, Lesson 8.7
- **Subtopics**:
  - `8.15.1` Requirements: 1-on-1 chat, group chat (up to 1,000 users), read receipts, offline message storage, end-to-end encryption (E2EE)
  - `8.15.2` Capacity estimation: 2B users, 100B messages/day $\approx 1.15\text{M}$ messages/sec; peak 3M msgs/sec
  - `8.15.3` Connection management: maintaining persistent bidirectional WebSocket / TCP connections across millions of chat gateways
  - `8.15.4` Session Service and User-to-Gateway mapping: tracking which gateway holds the active socket for user $X$ via Redis
  - `8.15.5` Message delivery workflow: online routing through gateways vs offline message persistence in Cassandra / DynamoDB
  - `8.15.6` Group chat fanout: server-side fanout queues vs client-side individual sends, managing group state and message ordering
- **Key Failure Modes & Edge Cases**: Chat servers crashing and disconnecting 500,000 active WebSockets simultaneously, triggering a catastrophic reconnection storm.
- **Verification & Mastery Check**: Produce a complete architectural blueprint for a global chat platform supporting 2B users with WebSocket connection servers.
- **Project Application**: System Design Portfolio: Project 5 - Real-Time Chat Platform.', '{"solution.py": "# Phase 8 // Lesson 8.15: System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack)\n\ndef solve():\n    \"\"\"\n    Verification: Produce a complete architectural blueprint for a global chat platform supporting 2B users with WebSo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "8.15", "subtopics_count": 6, "verification_criteria": "Produce a complete architectural blueprint for a global chat platform supporting 2B users with WebSocket connection servers.", "subtopics": ["8.15.1 Requirements: 1-on-1 chat, group chat (up to 1,000 users), read receipts, offline message storage, end-to-end encryption (E2EE)", "8.15.2 Capacity estimation: 2B users, 100B messages/day $\\approx 1.15\\text{M}$ messages/sec; peak 3M msgs/sec", "8.15.3 Connection management: maintaining persistent bidirectional WebSocket / TCP connections across millions of chat gateways", "8.15.4 Session Service and User-to-Gateway mapping: tracking which gateway holds the active socket for user $X$ via Redis", "8.15.5 Message delivery workflow: online routing through gateways vs offline message persistence in Cassandra / DynamoDB", "8.15.6 Group chat fanout: server-side fanout queues vs client-side individual sends, managing group state and message ordering"]}'::jsonb, '["Explain how this implementation prevents: Chat servers crashing and disconnecting 500,000 active WebSockets simultaneously, triggering a catastrophic reconnection", "How does System Deep Dive 5: Global Real-Time Chat System (WhatsApp / Slack) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
