INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-10-31', 'phase-10-lesson-31-golden-datasets-curation-versioning-regre', 'module-11', 31, 'Lesson 11.31: Golden Datasets: Curation, Versioning & Regression Testing', 'Prerequisites: Lesson 10.29, Lesson 10.30', 'Prerequisites: Lesson 10.29, Lesson 10.30 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 1550.0, '# Lesson 10.31: Golden Datasets: Curation, Versioning & Regression Testing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.29, Lesson 10.30
- **Subtopics**:
  - `10.31.1` What constitutes a true Golden Dataset: curated, human-verified, representative question-answer-context benchmark suites
  - `10.31.2` Stratified sampling: ensuring golden datasets cover diverse document types, difficulty levels, and domain topics proportionally
  - `10.31.3` Versioning golden datasets: tracking dataset git hashes, schema versions, and ground truth updates alongside model code
  - `10.31.4` Regression testing pipelines: detecting breaking changes in retrieval or synthesis when updating embedding models or prompts
  - `10.31.5` Establishing performance baselines: tracking precision@K, recall@K, MRR, NDCG, and RAG Triad scores across model releases
  - `10.31.6` Continuous dataset updating: harvesting hard production queries and user-reported bad answers into the regression suite
- **Key Failure Modes & Edge Cases**: Modifying prompt templates in production without running the golden regression suite, silently degrading edge-case answer quality.
- **Verification & Mastery Check**: Establish a version-controlled 250-sample Golden Dataset and automated regression test suite running in GitHub Actions.
- **Project Application**: EvalKit: Golden dataset repository and CI/CD test harness.', '{"solution.py": "# Phase 10 // Lesson 10.31: Golden Datasets: Curation, Versioning & Regression Testing\n\ndef solve():\n    \"\"\"\n    Verification: Establish a version-controlled 250-sample Golden Dataset and automated regression test suite running\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.31", "subtopics_count": 6, "verification_criteria": "Establish a version-controlled 250-sample Golden Dataset and automated regression test suite running in GitHub Actions.", "subtopics": ["10.31.1 What constitutes a true Golden Dataset: curated, human-verified, representative question-answer-context benchmark suites", "10.31.2 Stratified sampling: ensuring golden datasets cover diverse document types, difficulty levels, and domain topics proportionally", "10.31.3 Versioning golden datasets: tracking dataset git hashes, schema versions, and ground truth updates alongside model code", "10.31.4 Regression testing pipelines: detecting breaking changes in retrieval or synthesis when updating embedding models or prompts", "10.31.5 Establishing performance baselines: tracking precision@K, recall@K, MRR, NDCG, and RAG Triad scores across model releases", "10.31.6 Continuous dataset updating: harvesting hard production queries and user-reported bad answers into the regression suite"]}'::jsonb, '["Explain how this implementation prevents: Modifying prompt templates in production without running the golden regression suite, silently degrading edge-case answe", "How does Golden Datasets: Curation, Versioning & Regression Testing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-32', 'phase-10-lesson-32-statistical-inter-rater-reliability-cohen', 'module-11', 32, 'Lesson 11.32: Statistical Inter-Rater Reliability: Cohen''s Kappa & Krippendorff''s Alpha', 'Prerequisites: Phase 2, Lesson 10.30', 'Prerequisites: Phase 2, Lesson 10.30 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1600.0, '# Lesson 10.32: Statistical Inter-Rater Reliability: Cohen''s Kappa & Krippendorff''s Alpha

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2, Lesson 10.30
- **Subtopics**:
  - `10.32.1` Why measuring agreement is essential: validating whether automated LLM judges agree with human expert evaluators
  - `10.32.2` Observed agreement vs Chance agreement: why raw percent agreement ($P_o$) is mathematically misleading
  - `10.32.3` Cohen''s Kappa ($\kappa$): $\kappa = \frac{P_o - P_e}{1 - P_e}$; correcting for agreement occurring purely by chance
  - `10.32.4` Interpreting Kappa: $<0.20$ (poor), $0.41-0.60$ (moderate), $0.61-0.80$ (substantial), $0.81-1.00$ (almost perfect agreement)
  - `10.32.5` Krippendorff''s Alpha ($\alpha$): generalized reliability metric handling multiple raters, missing data, and ordinal/interval scales
  - `10.32.6` Calibrating LLM judges: iterating on judge prompt rubrics until agreement with domain experts achieves $\kappa > 0.75$
- **Key Failure Modes & Edge Cases**: Deploying an automated LLM judge that has a Cohen''s Kappa of 0.15 with human experts, making automated metrics completely uncorrelated with reality.
- **Verification & Mastery Check**: Implement Cohen''s Kappa and Krippendorff''s Alpha from scratch; measure statistical agreement between an LLM judge and human ratings.
- **Project Application**: EvalKit: Statistical inter-rater reliability calculation suite.', '{"solution.py": "# Phase 10 // Lesson 10.32: Statistical Inter-Rater Reliability: Cohen''s Kappa & Krippendorff''s Alpha\n\ndef solve():\n    \"\"\"\n    Verification: Implement Cohen''s Kappa and Krippendorff''s Alpha from scratch; measure statistical agreement between\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.32", "subtopics_count": 6, "verification_criteria": "Implement Cohen''s Kappa and Krippendorff''s Alpha from scratch; measure statistical agreement between an LLM judge and human ratings.", "subtopics": ["10.32.1 Why measuring agreement is essential: validating whether automated LLM judges agree with human expert evaluators", "10.32.2 Observed agreement vs Chance agreement: why raw percent agreement ($P_o$) is mathematically misleading", "10.32.3 Cohen''s Kappa ($\\kappa$): $\\kappa = \\frac{P_o - P_e}{1 - P_e}$; correcting for agreement occurring purely by chance", "10.32.4 Interpreting Kappa: $<0.20$ (poor), $0.41-0.60$ (moderate), $0.61-0.80$ (substantial), $0.81-1.00$ (almost perfect agreement)", "10.32.5 Krippendorff''s Alpha ($\\alpha$): generalized reliability metric handling multiple raters, missing data, and ordinal/interval scales", "10.32.6 Calibrating LLM judges: iterating on judge prompt rubrics until agreement with domain experts achieves $\\kappa > 0.75$"]}'::jsonb, '["Explain how this implementation prevents: Deploying an automated LLM judge that has a Cohen''s Kappa of 0.15 with human experts, making automated metrics completel", "How does Statistical Inter-Rater Reliability: Cohen''s Kappa & Krippendorff''s Alpha scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-33', 'phase-10-lesson-33-human-in-the-loop-hitl-annotation-discord', 'module-11', 33, 'Lesson 11.33: Human-in-the-Loop (HITL) Annotation & Discordance Analysis', 'Prerequisites: Lesson 10.31, Lesson 10.32', 'Prerequisites: Lesson 10.31, Lesson 10.32 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 1650.0, '# Lesson 10.33: Human-in-the-Loop (HITL) Annotation & Discordance Analysis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.31, Lesson 10.32
- **Subtopics**:
  - `10.33.1` Designing annotation interfaces: building ergonomic web UIs for human domain experts to review and rate RAG outputs
  - `10.33.2` Annotation guidelines: creating unambiguous, deterministic rubric documentation to minimize human annotator variance
  - `10.33.3` Discordance Analysis: systematic analysis of edge cases where human annotators disagree with each other or with LLM judges
  - `10.33.4` Root cause taxonomy for discordance: ambiguous questions, incomplete context, subjective criteria, or annotation fatigue
  - `10.33.5` Feedback loops: routing low-confidence production queries to human expert review queues for ongoing active learning
  - `10.33.6` Privacy and compliance in annotation: masking PII and sensitive enterprise data before presenting to internal or external raters
- **Key Failure Modes & Edge Cases**: Providing vague annotation guidelines (''rate quality 1-5''), causing human annotator agreement to collapse into random noise.
- **Verification & Mastery Check**: Conduct a structured discordance analysis on 50 contested evaluations; refine rubric guidelines to resolve 90% of ambiguities.
- **Project Application**: EvalKit: Human evaluation protocol and discordance report.', '{"solution.py": "# Phase 10 // Lesson 10.33: Human-in-the-Loop (HITL) Annotation & Discordance Analysis\n\ndef solve():\n    \"\"\"\n    Verification: Conduct a structured discordance analysis on 50 contested evaluations; refine rubric guidelines to r\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.33", "subtopics_count": 6, "verification_criteria": "Conduct a structured discordance analysis on 50 contested evaluations; refine rubric guidelines to resolve 90% of ambiguities.", "subtopics": ["10.33.1 Designing annotation interfaces: building ergonomic web UIs for human domain experts to review and rate RAG outputs", "10.33.2 Annotation guidelines: creating unambiguous, deterministic rubric documentation to minimize human annotator variance", "10.33.3 Discordance Analysis: systematic analysis of edge cases where human annotators disagree with each other or with LLM judges", "10.33.4 Root cause taxonomy for discordance: ambiguous questions, incomplete context, subjective criteria, or annotation fatigue", "10.33.5 Feedback loops: routing low-confidence production queries to human expert review queues for ongoing active learning", "10.33.6 Privacy and compliance in annotation: masking PII and sensitive enterprise data before presenting to internal or external raters"]}'::jsonb, '["Explain how this implementation prevents: Providing vague annotation guidelines (''rate quality 1-5''), causing human annotator agreement to collapse into random no", "How does Human-in-the-Loop (HITL) Annotation & Discordance Analysis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-34', 'phase-10-lesson-34-failure-mode-triage-retrieval-failures-vs', 'module-11', 34, 'Lesson 11.34: Failure Mode Triage: Retrieval Failures vs Synthesis Failures', 'Prerequisites: Lesson 10.27, Lesson 10.30', 'Prerequisites: Lesson 10.27, Lesson 10.30 | Subtopics: 7 items', 'Systems project application', 300, 11, 2560.0, 1700.0, '# Lesson 10.34: Failure Mode Triage: Retrieval Failures vs Synthesis Failures

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.27, Lesson 10.30
- **Subtopics**:
  - `10.34.1` Systematic failure categorization: decomposing RAG errors into precise failure modes across the pipeline
  - `10.34.2` Failure Mode 1: Missing Content: the answer does not exist anywhere in the source corpus (knowledge gap)
  - `10.34.3` Failure Mode 2: Missed Retrieval: the answer exists in corpus, but retrieval failed to include it in top-$K$ candidates
  - `10.34.4` Failure Mode 3: Out of Context: the chunk was retrieved, but dropped during re-ranking or context compression
  - `10.34.5` Failure Mode 4: Synthesis Failure: the answer was present in context, but the LLM failed to extract it or hallucinated
  - `10.34.6` Failure Mode 5: Wrong Format: the LLM extracted the right answer but violated schema or format constraints
  - `10.34.7` Building automated diagnostic decision trees to categorize user bug reports instantly into the exact responsible component
- **Key Failure Modes & Edge Cases**: Spending weeks tuning vector search indexes to fix a problem where the requested information was never ingested into the database.
- **Verification & Mastery Check**: Build an automated diagnostic triager that takes a failed RAG query and categorizes it into one of the 5 canonical failure modes.
- **Project Application**: DocuMind: Automated failure diagnostic harness.', '{"solution.py": "# Phase 10 // Lesson 10.34: Failure Mode Triage: Retrieval Failures vs Synthesis Failures\n\ndef solve():\n    \"\"\"\n    Verification: Build an automated diagnostic triager that takes a failed RAG query and categorizes it into one of t\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.34", "subtopics_count": 7, "verification_criteria": "Build an automated diagnostic triager that takes a failed RAG query and categorizes it into one of the 5 canonical failure modes.", "subtopics": ["10.34.1 Systematic failure categorization: decomposing RAG errors into precise failure modes across the pipeline", "10.34.2 Failure Mode 1: Missing Content: the answer does not exist anywhere in the source corpus (knowledge gap)", "10.34.3 Failure Mode 2: Missed Retrieval: the answer exists in corpus, but retrieval failed to include it in top-$K$ candidates", "10.34.4 Failure Mode 3: Out of Context: the chunk was retrieved, but dropped during re-ranking or context compression", "10.34.5 Failure Mode 4: Synthesis Failure: the answer was present in context, but the LLM failed to extract it or hallucinated", "10.34.6 Failure Mode 5: Wrong Format: the LLM extracted the right answer but violated schema or format constraints", "10.34.7 Building automated diagnostic decision trees to categorize user bug reports instantly into the exact responsible component"]}'::jsonb, '["Explain how this implementation prevents: Spending weeks tuning vector search indexes to fix a problem where the requested information was never ingested into the", "How does Failure Mode Triage: Retrieval Failures vs Synthesis Failures scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-35', 'phase-10-lesson-35-production-observability-for-genai-langfu', 'module-11', 35, 'Lesson 11.35: Production Observability for GenAI: Langfuse, Arize Phoenix & OpenInference', 'Prerequisites: Phase 7, Lesson 10.1', 'Prerequisites: Phase 7, Lesson 10.1 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 1750.0, '# Lesson 10.35: Production Observability for GenAI: Langfuse, Arize Phoenix & OpenInference

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 10.1
- **Subtopics**:
  - `10.35.1` The GenAI observability challenge: tracking complex multi-step nested traces across prompts, embeddings, retrievals, and tools
  - `10.35.2` OpenInference semantic conventions: standardized tracing attributes for LLM calls, vector DB queries, and retrieval spans
  - `10.35.3` Langfuse / Arize Phoenix architecture: collecting distributed spans, visualizing execution DAGs, and tracking token costs
  - `10.35.4` Latency profiling: measuring latency bottlenecks across individual stages (prompt prep, vector search, re-ranking, first-token time)
  - `10.35.5` User feedback tracking: capturing user thumbs-up / thumbs-down and explicit corrections linked directly to specific trace IDs
  - `10.35.6` Alerting on GenAI anomalies: triggering alerts on spike in token usage, elevated latency, or sudden drops in retrieval score averages
- **Key Failure Modes & Edge Cases**: Treating the entire RAG pipeline as a black box without span tracing, leaving on-call engineers unable to diagnose production latency spikes.
- **Verification & Mastery Check**: Instrument a production RAG pipeline with OpenInference and Langfuse; visualize full execution traces with latency and token cost breakdowns.
- **Project Application**: DocuMind: Production GenAI observability and tracing pipeline.', '{"solution.py": "# Phase 10 // Lesson 10.35: Production Observability for GenAI: Langfuse, Arize Phoenix & OpenInference\n\ndef solve():\n    \"\"\"\n    Verification: Instrument a production RAG pipeline with OpenInference and Langfuse; visualize full execution trace\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.35", "subtopics_count": 6, "verification_criteria": "Instrument a production RAG pipeline with OpenInference and Langfuse; visualize full execution traces with latency and token cost breakdowns.", "subtopics": ["10.35.1 The GenAI observability challenge: tracking complex multi-step nested traces across prompts, embeddings, retrievals, and tools", "10.35.2 OpenInference semantic conventions: standardized tracing attributes for LLM calls, vector DB queries, and retrieval spans", "10.35.3 Langfuse / Arize Phoenix architecture: collecting distributed spans, visualizing execution DAGs, and tracking token costs", "10.35.4 Latency profiling: measuring latency bottlenecks across individual stages (prompt prep, vector search, re-ranking, first-token time)", "10.35.5 User feedback tracking: capturing user thumbs-up / thumbs-down and explicit corrections linked directly to specific trace IDs", "10.35.6 Alerting on GenAI anomalies: triggering alerts on spike in token usage, elevated latency, or sudden drops in retrieval score averages"]}'::jsonb, '["Explain how this implementation prevents: Treating the entire RAG pipeline as a black box without span tracing, leaving on-call engineers unable to diagnose produ", "How does Production Observability for GenAI: Langfuse, Arize Phoenix & OpenInference scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-1', 'phase-11-lesson-01-performance-engineering-principles-amdahl', 'module-12', 1, 'Lesson 12.1: Performance Engineering Principles: Amdahl''s Law, Latency & Throughput', 'Prerequisites: Phase 0, Phase 8', 'Prerequisites: Phase 0, Phase 8 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 50.0, '# Lesson 11.1: Performance Engineering Principles: Amdahl''s Law, Latency & Throughput

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 8
- **Subtopics**:
  - `11.1.1` Amdahl''s Law: theoretical speedup limits of parallelization ($S_{latency}(s) = \frac{1}{(1-p) + \frac{p}{s}}$)
  - `11.1.2` Universal Scalability Law (Gunther): accounting for concurrency contention and coherence cross-talk overhead
  - `11.1.3` Latency vs Throughput trade-offs: batching increases throughput at the cost of individual request latency
  - `11.1.4` Percentiles and Tail Latency: why average latency is meaningless; p50, p95, p99, and max tail latency impact in microservices
  - `11.1.5` The Tail at Scale (Dean & Barroso): how tail latency compounds in distributed systems with hundreds of fanout calls
  - `11.1.6` The Golden Rule of Optimization: never optimize without profiling and establishing verified baseline measurements
- **Key Failure Modes & Edge Cases**: Optimizing code that accounts for 1% of runtime execution, spending weeks for a 0.05% total performance improvement.
- **Verification & Mastery Check**: Calculate theoretical speedup limits using Amdahl''s Law and Gunther''s USL for a multi-threaded data processing pipeline.
- **Project Application**: ModelPulse: Performance baseline calculation harness.', '{"solution.py": "# Phase 11 // Lesson 11.1: Performance Engineering Principles: Amdahl''s Law, Latency & Throughput\n\ndef solve():\n    \"\"\"\n    Verification: Calculate theoretical speedup limits using Amdahl''s Law and Gunther''s USL for a multi-threaded data \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.1", "subtopics_count": 6, "verification_criteria": "Calculate theoretical speedup limits using Amdahl''s Law and Gunther''s USL for a multi-threaded data processing pipeline.", "subtopics": ["11.1.1 Amdahl''s Law: theoretical speedup limits of parallelization ($S_{latency}(s) = \\frac{1}{(1-p) + \\frac{p}{s}}$)", "11.1.2 Universal Scalability Law (Gunther): accounting for concurrency contention and coherence cross-talk overhead", "11.1.3 Latency vs Throughput trade-offs: batching increases throughput at the cost of individual request latency", "11.1.4 Percentiles and Tail Latency: why average latency is meaningless; p50, p95, p99, and max tail latency impact in microservices", "11.1.5 The Tail at Scale (Dean & Barroso): how tail latency compounds in distributed systems with hundreds of fanout calls", "11.1.6 The Golden Rule of Optimization: never optimize without profiling and establishing verified baseline measurements"]}'::jsonb, '["Explain how this implementation prevents: Optimizing code that accounts for 1% of runtime execution, spending weeks for a 0.05% total performance improvement.", "How does Performance Engineering Principles: Amdahl''s Law, Latency & Throughput scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-2', 'phase-11-lesson-02-cpu-profiling-foundations-sampling-vs-det', 'module-12', 2, 'Lesson 12.2: CPU Profiling Foundations: Sampling vs Deterministic Instrumentation', 'Prerequisites: Phase 0, Phase 1', 'Prerequisites: Phase 0, Phase 1 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 100.0, '# Lesson 11.2: CPU Profiling Foundations: Sampling vs Deterministic Instrumentation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 1
- **Subtopics**:
  - `11.2.1` Deterministic (Tracing) Profilers: recording every function call event (cProfile, sys.settrace); high overhead distorting execution timings
  - `11.2.2` Statistical (Sampling) Profilers: periodically inspecting the call stack at regular intervals (e.g. 100Hz); sub-1% runtime overhead
  - `11.2.3` Kernel vs User Space profiling: capturing system calls, context switches, and page faults vs pure application code
  - `11.2.4` Hardware Performance Counters: CPU cycles, instructions retired, cache misses (L1, L2, L3), and branch mispredictions
  - `11.2.5` Profiling in production: why sampling profilers are the only safe tool for profiling live customer-facing traffic
  - `11.2.6` Overhead mitigation: tuning sampling frequency to balance statistical significance with CPU measurement distortion
- **Key Failure Modes & Edge Cases**: Running heavy deterministic tracing profilers in production, causing request latency to explode by $10\times$ and tripping timeouts.
- **Verification & Mastery Check**: Benchmark cProfile (tracing) vs py-spy (sampling) on a CPU-bound mathematical script; compare execution time distortion.
- **Project Application**: ModelPulse: Sampling profiler integration.', '{"solution.py": "# Phase 11 // Lesson 11.2: CPU Profiling Foundations: Sampling vs Deterministic Instrumentation\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark cProfile (tracing) vs py-spy (sampling) on a CPU-bound mathematical script; compare execut\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.2", "subtopics_count": 6, "verification_criteria": "Benchmark cProfile (tracing) vs py-spy (sampling) on a CPU-bound mathematical script; compare execution time distortion.", "subtopics": ["11.2.1 Deterministic (Tracing) Profilers: recording every function call event (cProfile, sys.settrace); high overhead distorting execution timings", "11.2.2 Statistical (Sampling) Profilers: periodically inspecting the call stack at regular intervals (e.g. 100Hz); sub-1% runtime overhead", "11.2.3 Kernel vs User Space profiling: capturing system calls, context switches, and page faults vs pure application code", "11.2.4 Hardware Performance Counters: CPU cycles, instructions retired, cache misses (L1, L2, L3), and branch mispredictions", "11.2.5 Profiling in production: why sampling profilers are the only safe tool for profiling live customer-facing traffic", "11.2.6 Overhead mitigation: tuning sampling frequency to balance statistical significance with CPU measurement distortion"]}'::jsonb, '["Explain how this implementation prevents: Running heavy deterministic tracing profilers in production, causing request latency to explode by $10\\times$ and trippi", "How does CPU Profiling Foundations: Sampling vs Deterministic Instrumentation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-3', 'phase-11-lesson-03-visualizing-performance-flame-graphs-call', 'module-12', 3, 'Lesson 12.3: Visualizing Performance: Flame Graphs, Call Trees & Hotspots', 'Prerequisites: Lesson 11.2', 'Prerequisites: Lesson 11.2 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 150.0, '# Lesson 11.3: Visualizing Performance: Flame Graphs, Call Trees & Hotspots

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.2
- **Subtopics**:
  - `11.3.1` Brendan Gregg''s Flame Graphs: x-axis representing alphabetized population width (CPU time percentage), y-axis representing call stack depth
  - `11.3.2` Reading Flame Graphs: identifying wide plateaus as hot functions consuming the most CPU time on-CPU
  - `11.3.3` Differential Flame Graphs: subtracting baseline profile from modified profile (red = regression, blue = improvement)
  - `11.3.4` Icicle Graphs (top-down) vs Flame Graphs (bottom-up): analyzing root callers vs leaf resource sinks
  - `11.3.5` Off-CPU Flame Graphs: identifying why threads are blocked (waiting on I/O, locks, sleep, paging) rather than consuming CPU
  - `11.3.6` Generating interactive SVG flame graphs from raw profiling data in automated CI/CD benchmark pipelines
- **Key Failure Modes & Edge Cases**: Misinterpreting flame graph horizontal width as execution time over chronological time instead of aggregated percentage of samples.
- **Verification & Mastery Check**: Generate an interactive Flame Graph from a slow data processing application and identify the 2 primary bottleneck functions.
- **Project Application**: ModelPulse: Automated flame graph generation module.', '{"solution.py": "# Phase 11 // Lesson 11.3: Visualizing Performance: Flame Graphs, Call Trees & Hotspots\n\ndef solve():\n    \"\"\"\n    Verification: Generate an interactive Flame Graph from a slow data processing application and identify the 2 prima\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.3", "subtopics_count": 6, "verification_criteria": "Generate an interactive Flame Graph from a slow data processing application and identify the 2 primary bottleneck functions.", "subtopics": ["11.3.1 Brendan Gregg''s Flame Graphs: x-axis representing alphabetized population width (CPU time percentage), y-axis representing call stack depth", "11.3.2 Reading Flame Graphs: identifying wide plateaus as hot functions consuming the most CPU time on-CPU", "11.3.3 Differential Flame Graphs: subtracting baseline profile from modified profile (red = regression, blue = improvement)", "11.3.4 Icicle Graphs (top-down) vs Flame Graphs (bottom-up): analyzing root callers vs leaf resource sinks", "11.3.5 Off-CPU Flame Graphs: identifying why threads are blocked (waiting on I/O, locks, sleep, paging) rather than consuming CPU", "11.3.6 Generating interactive SVG flame graphs from raw profiling data in automated CI/CD benchmark pipelines"]}'::jsonb, '["Explain how this implementation prevents: Misinterpreting flame graph horizontal width as execution time over chronological time instead of aggregated percentage ", "How does Visualizing Performance: Flame Graphs, Call Trees & Hotspots scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-4', 'phase-11-lesson-04-python-performance-profiling-py-spy-cprof', 'module-12', 4, 'Lesson 12.4: Python Performance Profiling: py-spy & cProfile Mastery', 'Prerequisites: Lesson 11.2, Lesson 11.3', 'Prerequisites: Lesson 11.2, Lesson 11.3 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 200.0, '# Lesson 11.4: Python Performance Profiling: py-spy & cProfile Mastery

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.2, Lesson 11.3
- **Subtopics**:
  - `11.4.1` `py-spy` architecture: out-of-process sampling profiler reading Python process memory directly via `process_vm_readv`
  - `11.4.2` Zero overhead in target: profiling production Python processes without code modification or restarting
  - `11.4.3` Live top mode: running `py-spy top --pid <PID>` to view active real-time function execution rates in terminal
  - `11.4.4` Tracing multi-threaded and GIL-bound processes: identifying which threads are blocked on the Global Interpreter Lock (GIL)
  - `11.4.5` Profiling native C extensions: using `--native` flag to inspect C/Rust stack traces alongside Python frames
  - `11.4.6` `cProfile` and `pstats` deep dive: analyzing `tottime` (exclusive function time) vs `cumtime` (inclusive cumulative time)
- **Key Failure Modes & Edge Cases**: Relying solely on `tottime` in cProfile, missing high-level orchestrator bottlenecks with massive `cumtime`.
- **Verification & Mastery Check**: Profile a live multi-threaded Python API service under load using `py-spy`; extract interactive flame graphs and identify GIL contention.
- **Project Application**: ModelPulse: Live process profiling harness.', '{"solution.py": "# Phase 11 // Lesson 11.4: Python Performance Profiling: py-spy & cProfile Mastery\n\ndef solve():\n    \"\"\"\n    Verification: Profile a live multi-threaded Python API service under load using `py-spy`; extract interactive flam\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.4", "subtopics_count": 6, "verification_criteria": "Profile a live multi-threaded Python API service under load using `py-spy`; extract interactive flame graphs and identify GIL contention.", "subtopics": ["11.4.1 `py-spy` architecture: out-of-process sampling profiler reading Python process memory directly via `process_vm_readv`", "11.4.2 Zero overhead in target: profiling production Python processes without code modification or restarting", "11.4.3 Live top mode: running `py-spy top --pid <PID>` to view active real-time function execution rates in terminal", "11.4.4 Tracing multi-threaded and GIL-bound processes: identifying which threads are blocked on the Global Interpreter Lock (GIL)", "11.4.5 Profiling native C extensions: using `--native` flag to inspect C/Rust stack traces alongside Python frames", "11.4.6 `cProfile` and `pstats` deep dive: analyzing `tottime` (exclusive function time) vs `cumtime` (inclusive cumulative time)"]}'::jsonb, '["Explain how this implementation prevents: Relying solely on `tottime` in cProfile, missing high-level orchestrator bottlenecks with massive `cumtime`.", "How does Python Performance Profiling: py-spy & cProfile Mastery scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-5', 'phase-11-lesson-05-go-rust-performance-profiling-pprof-perf-', 'module-12', 5, 'Lesson 12.5: Go & Rust Performance Profiling: pprof & perf Internals', 'Prerequisites: Phase 0, Lesson 11.2', 'Prerequisites: Phase 0, Lesson 11.2 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 250.0, '# Lesson 11.5: Go & Rust Performance Profiling: pprof & perf Internals

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 11.2
- **Subtopics**:
  - `11.5.1` Go runtime profiling with `pprof`: CPU profiling, memory allocations, goroutine blocking, and mutex contention
  - `11.5.2` Exposing pprof endpoints: `net/http/pprof` handlers and capturing remote production profiles via curl
  - `11.5.3` Linux `perf` subsystem: hardware performance events, sampling kernel execution, and `perf record` / `perf report`
  - `11.5.4` Rust profiling with `cargo-flamegraph`: compiling with debug symbols (`debug = true` in release profile) for clean symbolication
  - `11.5.5` Analyzing Goroutine leaks: using `pprof/goroutine` to detect accumulating un-garbage-collected goroutines
  - `11.5.6` Analyzing Mutex contention: `pprof/mutex` measuring exact time spent waiting for lock acquisition across threads
- **Key Failure Modes & Edge Cases**: Profiling Go/Rust release binaries stripped of symbol tables, resulting in unreadable hexadecimal memory address flame graphs.
- **Verification & Mastery Check**: Capture and analyze a live Go service profile with `go tool pprof`; diagnose and resolve a high-contention mutex bottleneck.
- **Project Application**: ModelPulse: Go and native service profiling harness.', '{"solution.py": "# Phase 11 // Lesson 11.5: Go & Rust Performance Profiling: pprof & perf Internals\n\ndef solve():\n    \"\"\"\n    Verification: Capture and analyze a live Go service profile with `go tool pprof`; diagnose and resolve a high-cont\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.5", "subtopics_count": 6, "verification_criteria": "Capture and analyze a live Go service profile with `go tool pprof`; diagnose and resolve a high-contention mutex bottleneck.", "subtopics": ["11.5.1 Go runtime profiling with `pprof`: CPU profiling, memory allocations, goroutine blocking, and mutex contention", "11.5.2 Exposing pprof endpoints: `net/http/pprof` handlers and capturing remote production profiles via curl", "11.5.3 Linux `perf` subsystem: hardware performance events, sampling kernel execution, and `perf record` / `perf report`", "11.5.4 Rust profiling with `cargo-flamegraph`: compiling with debug symbols (`debug = true` in release profile) for clean symbolication", "11.5.5 Analyzing Goroutine leaks: using `pprof/goroutine` to detect accumulating un-garbage-collected goroutines", "11.5.6 Analyzing Mutex contention: `pprof/mutex` measuring exact time spent waiting for lock acquisition across threads"]}'::jsonb, '["Explain how this implementation prevents: Profiling Go/Rust release binaries stripped of symbol tables, resulting in unreadable hexadecimal memory address flame g", "How does Go & Rust Performance Profiling: pprof & perf Internals scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-6', 'phase-11-lesson-06-low-level-optimization-vectorization-simd', 'module-12', 6, 'Lesson 12.6: Low-Level Optimization: Vectorization, SIMD & Cache Locality', 'Prerequisites: Phase 0, Phase 9', 'Prerequisites: Phase 0, Phase 9 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 300.0, '# Lesson 11.6: Low-Level Optimization: Vectorization, SIMD & Cache Locality

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 9
- **Subtopics**:
  - `11.6.1` CPU memory hierarchy: L1 cache (32KB, 4 cycles), L2 cache (512KB, 14 cycles), L3 cache (16MB, 40 cycles), Main Memory (100ns)
  - `11.6.2` Cache lines: 64-byte chunks, spatial locality (accessing adjacent memory) and temporal locality (reusing recent memory)
  - `11.6.3` Array of Structures (AoS) vs Structure of Arrays (SoA): memory layout implications for vector processing and cache line utilization
  - `11.6.4` Single Instruction Multiple Data (SIMD): AVX-512, AVX2, and ARM NEON registers executing parallel arithmetic
  - `11.6.5` Auto-vectorization in compilers: loop structures that allow vectorization vs pointer aliasing and branch divergence impediments
  - `11.6.6` High-performance numerical libraries: OpenBLAS, MKL, and utilizing SIMD instructions in NumPy and PyTorch
- **Key Failure Modes & Edge Cases**: Iterating through 2D matrices in column-major order in C/Python, causing a cache miss on every single element access.
- **Verification & Mastery Check**: Refactor a data processing loop from AoS to SoA layout; measure $5\times$ speedup and $90\%$ reduction in L1 cache misses using `perf`.
- **Project Application**: ModelPulse: Memory-optimized data transformation kernel.', '{"solution.py": "# Phase 11 // Lesson 11.6: Low-Level Optimization: Vectorization, SIMD & Cache Locality\n\ndef solve():\n    \"\"\"\n    Verification: Refactor a data processing loop from AoS to SoA layout; measure $5\\times$ speedup and $90\\%$ reducti\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.6", "subtopics_count": 6, "verification_criteria": "Refactor a data processing loop from AoS to SoA layout; measure $5\\times$ speedup and $90\\%$ reduction in L1 cache misses using `perf`.", "subtopics": ["11.6.1 CPU memory hierarchy: L1 cache (32KB, 4 cycles), L2 cache (512KB, 14 cycles), L3 cache (16MB, 40 cycles), Main Memory (100ns)", "11.6.2 Cache lines: 64-byte chunks, spatial locality (accessing adjacent memory) and temporal locality (reusing recent memory)", "11.6.3 Array of Structures (AoS) vs Structure of Arrays (SoA): memory layout implications for vector processing and cache line utilization", "11.6.4 Single Instruction Multiple Data (SIMD): AVX-512, AVX2, and ARM NEON registers executing parallel arithmetic", "11.6.5 Auto-vectorization in compilers: loop structures that allow vectorization vs pointer aliasing and branch divergence impediments", "11.6.6 High-performance numerical libraries: OpenBLAS, MKL, and utilizing SIMD instructions in NumPy and PyTorch"]}'::jsonb, '["Explain how this implementation prevents: Iterating through 2D matrices in column-major order in C/Python, causing a cache miss on every single element access.", "How does Low-Level Optimization: Vectorization, SIMD & Cache Locality scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-7', 'phase-11-lesson-07-memory-management-foundations-stack-heap-', 'module-12', 7, 'Lesson 12.7: Memory Management Foundations: Stack, Heap & Virtual Memory', 'Prerequisites: Phase 0, Phase 1', 'Prerequisites: Phase 0, Phase 1 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 350.0, '# Lesson 11.7: Memory Management Foundations: Stack, Heap & Virtual Memory

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 1
- **Subtopics**:
  - `11.7.1` Stack allocation: contiguous memory, stack pointer increment, automatic deallocation upon function return, L1 cache friendly
  - `11.7.2` Heap allocation: dynamic memory, allocator algorithms (ptmalloc, jemalloc, tcmalloc), fragmentation, and metadata overhead
  - `11.7.3` Virtual memory architecture: page tables, Translation Lookaside Buffer (TLB), 4KB standard pages vs 2MB HugePages
  - `11.7.4` Page faults: Minor page faults (allocating physical frame) vs Major page faults (reading from disk/swap)
  - `11.7.5` Resident Set Size (RSS) vs Virtual Memory Size (VMS) vs Shared Memory (SHR): what `top` metrics actually mean
  - `11.7.6` The Linux Out-Of-Memory (OOM) Killer: `oom_score`, `oom_score_adj`, and heuristic algorithm selecting processes to SIGKILL
- **Key Failure Modes & Edge Cases**: Confusing Virtual Memory (VMS) with real physical memory usage (RSS), prematurely panicking over unused virtual allocations.
- **Verification & Mastery Check**: Write a C/Python script demonstrating the difference between allocated virtual memory and committed physical RSS memory pages.
- **Project Application**: ModelPulse: Virtual memory allocation diagnostic utility.', '{"solution.py": "# Phase 11 // Lesson 11.7: Memory Management Foundations: Stack, Heap & Virtual Memory\n\ndef solve():\n    \"\"\"\n    Verification: Write a C/Python script demonstrating the difference between allocated virtual memory and committed \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.7", "subtopics_count": 6, "verification_criteria": "Write a C/Python script demonstrating the difference between allocated virtual memory and committed physical RSS memory pages.", "subtopics": ["11.7.1 Stack allocation: contiguous memory, stack pointer increment, automatic deallocation upon function return, L1 cache friendly", "11.7.2 Heap allocation: dynamic memory, allocator algorithms (ptmalloc, jemalloc, tcmalloc), fragmentation, and metadata overhead", "11.7.3 Virtual memory architecture: page tables, Translation Lookaside Buffer (TLB), 4KB standard pages vs 2MB HugePages", "11.7.4 Page faults: Minor page faults (allocating physical frame) vs Major page faults (reading from disk/swap)", "11.7.5 Resident Set Size (RSS) vs Virtual Memory Size (VMS) vs Shared Memory (SHR): what `top` metrics actually mean", "11.7.6 The Linux Out-Of-Memory (OOM) Killer: `oom_score`, `oom_score_adj`, and heuristic algorithm selecting processes to SIGKILL"]}'::jsonb, '["Explain how this implementation prevents: Confusing Virtual Memory (VMS) with real physical memory usage (RSS), prematurely panicking over unused virtual allocati", "How does Memory Management Foundations: Stack, Heap & Virtual Memory scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-8', 'phase-11-lesson-08-garbage-collection-internals-tracing-refe', 'module-12', 8, 'Lesson 12.8: Garbage Collection Internals: Tracing, Reference Counting & Generational GC', 'Prerequisites: Phase 1, Phase 9', 'Prerequisites: Phase 1, Phase 9 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 400.0, '# Lesson 11.8: Garbage Collection Internals: Tracing, Reference Counting & Generational GC

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Phase 9
- **Subtopics**:
  - `11.8.1` Reference counting (CPython, Swift): immediate deallocation when reference count drops to 0; deterministic cleanup
  - `11.8.2` The cyclic reference flaw: why reference counting cannot reclaim cyclic graphs ($A \to B \to A$) on its own
  - `11.8.3` CPython Generational Garbage Collector: Generation 0, 1, and 2; threshold counters, heuristic collection intervals, and `gc` module
  - `11.8.4` Tracing Garbage Collection (Go, JVM, V8): Mark-and-Sweep, Tri-color marking algorithm (White, Grey, Black), Stop-The-World pauses
  - `11.8.5` Go''s concurrent low-latency GC: write barriers, concurrent mark phase, and sub-millisecond GC pauses at the cost of higher CPU usage
  - `11.8.6` Tuning GC in production: tuning `GOGC` in Go, tuning `gc.set_threshold()` in Python, and disabling GC during latency-critical batch passes
- **Key Failure Modes & Edge Cases**: Creating accidental circular references in Python that disable immediate deallocation, causing memory spikes until generational GC runs.
- **Verification & Mastery Check**: Build an in-memory graph with intentional circular references; trace and measure CPython generational GC reclamation passes.
- **Project Application**: ModelPulse: Garbage collection telemetry and tuner.', '{"solution.py": "# Phase 11 // Lesson 11.8: Garbage Collection Internals: Tracing, Reference Counting & Generational GC\n\ndef solve():\n    \"\"\"\n    Verification: Build an in-memory graph with intentional circular references; trace and measure CPython generationa\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.8", "subtopics_count": 6, "verification_criteria": "Build an in-memory graph with intentional circular references; trace and measure CPython generational GC reclamation passes.", "subtopics": ["11.8.1 Reference counting (CPython, Swift): immediate deallocation when reference count drops to 0; deterministic cleanup", "11.8.2 The cyclic reference flaw: why reference counting cannot reclaim cyclic graphs ($A \\to B \\to A$) on its own", "11.8.3 CPython Generational Garbage Collector: Generation 0, 1, and 2; threshold counters, heuristic collection intervals, and `gc` module", "11.8.4 Tracing Garbage Collection (Go, JVM, V8): Mark-and-Sweep, Tri-color marking algorithm (White, Grey, Black), Stop-The-World pauses", "11.8.5 Go''s concurrent low-latency GC: write barriers, concurrent mark phase, and sub-millisecond GC pauses at the cost of higher CPU usage", "11.8.6 Tuning GC in production: tuning `GOGC` in Go, tuning `gc.set_threshold()` in Python, and disabling GC during latency-critical batch passes"]}'::jsonb, '["Explain how this implementation prevents: Creating accidental circular references in Python that disable immediate deallocation, causing memory spikes until gener", "How does Garbage Collection Internals: Tracing, Reference Counting & Generational GC scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-9', 'phase-11-lesson-09-memory-profiling-leak-detection-memray-he', 'module-12', 9, 'Lesson 12.9: Memory Profiling & Leak Detection: memray & Heap Inspection', 'Prerequisites: Lesson 11.7, Lesson 11.8', 'Prerequisites: Lesson 11.7, Lesson 11.8 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 450.0, '# Lesson 11.9: Memory Profiling & Leak Detection: memray & Heap Inspection

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.7, Lesson 11.8
- **Subtopics**:
  - `11.9.1` Why memory leaks kill long-running services: progressive RSS growth leading to slow degradation and sudden catastrophic OOM-Kills
  - `11.9.2` `memray` deep dive: Bloomberg''s dedicated memory profiler for Python tracking every single C and Python allocation
  - `11.9.3` Capturing memory profiles: `memray run -o output.bin script.py` and generating interactive memory flame graphs
  - `11.9.4` Detecting temporary vs permanent allocations: high-water mark memory usage vs lingering leaked objects at exit
  - `11.9.5` Analyzing live memory leaks: using `tracemalloc` to capture memory snapshots at $T_1$ and $T_2$, computing top line-by-line diffs
  - `11.9.6` C-extension memory leaks: detecting unfreed `malloc()` allocations in Cython, C extensions, or PyTorch custom CUDA kernels
- **Key Failure Modes & Edge Cases**: Searching for memory leaks using simple object counters, missing large underlying C-allocated buffers.
- **Verification & Mastery Check**: Diagnose a hidden memory leak in an API service using `memray`; locate the exact line of code retaining uncollected objects.
- **Project Application**: ModelPulse: Automated memory leak detection suite.', '{"solution.py": "# Phase 11 // Lesson 11.9: Memory Profiling & Leak Detection: memray & Heap Inspection\n\ndef solve():\n    \"\"\"\n    Verification: Diagnose a hidden memory leak in an API service using `memray`; locate the exact line of code retain\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.9", "subtopics_count": 6, "verification_criteria": "Diagnose a hidden memory leak in an API service using `memray`; locate the exact line of code retaining uncollected objects.", "subtopics": ["11.9.1 Why memory leaks kill long-running services: progressive RSS growth leading to slow degradation and sudden catastrophic OOM-Kills", "11.9.2 `memray` deep dive: Bloomberg''s dedicated memory profiler for Python tracking every single C and Python allocation", "11.9.3 Capturing memory profiles: `memray run -o output.bin script.py` and generating interactive memory flame graphs", "11.9.4 Detecting temporary vs permanent allocations: high-water mark memory usage vs lingering leaked objects at exit", "11.9.5 Analyzing live memory leaks: using `tracemalloc` to capture memory snapshots at $T_1$ and $T_2$, computing top line-by-line diffs", "11.9.6 C-extension memory leaks: detecting unfreed `malloc()` allocations in Cython, C extensions, or PyTorch custom CUDA kernels"]}'::jsonb, '["Explain how this implementation prevents: Searching for memory leaks using simple object counters, missing large underlying C-allocated buffers.", "How does Memory Profiling & Leak Detection: memray & Heap Inspection scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-10', 'phase-11-lesson-10-high-performance-allocators-jemalloc-tcma', 'module-12', 10, 'Lesson 12.10: High-Performance Allocators: jemalloc, tcmalloc & Mimalloc', 'Prerequisites: Lesson 11.7, Phase 0', 'Prerequisites: Lesson 11.7, Phase 0 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 500.0, '# Lesson 11.10: High-Performance Allocators: jemalloc, tcmalloc & Mimalloc

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.7, Phase 0
- **Subtopics**:
  - `11.10.1` Standard system allocators (glibc ptmalloc) limitations: lock contention on multi-threaded workloads, severe memory fragmentation
  - `11.10.2` jemalloc architecture: thread-specific caches (tcache), arenas, size classes (small, large, huge), and proactive dirty page purging
  - `11.10.3` tcmalloc (Google Thread-Caching Malloc): thread caches, central cache, page heap, and lock-free thread allocation paths
  - `11.10.4` Memory fragmentation mechanics: internal fragmentation (slack space in size class) vs external fragmentation (unusable scattered holes)
  - `11.10.5` Dropping in alternative allocators: setting `LD_PRELOAD=/usr/lib/libjemalloc.so` without recompiling application binaries
  - `11.10.6` Runtime profiling with jemalloc: enabling heap profiling via `MALLOC_CONF=prof:true` and analyzing memory dumps with `jeprof`
- **Key Failure Modes & Edge Cases**: Severe glibc allocator memory fragmentation causing 10GB RSS usage when the application only holds 2GB of actual live data.
- **Verification & Mastery Check**: Benchmark glibc ptmalloc vs jemalloc on a high-concurrency multi-threaded workload; measure RSS reduction and throughput improvement.
- **Project Application**: ModelPulse: High-performance memory allocator benchmark.', '{"solution.py": "# Phase 11 // Lesson 11.10: High-Performance Allocators: jemalloc, tcmalloc & Mimalloc\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark glibc ptmalloc vs jemalloc on a high-concurrency multi-threaded workload; measure RSS redu\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.10", "subtopics_count": 6, "verification_criteria": "Benchmark glibc ptmalloc vs jemalloc on a high-concurrency multi-threaded workload; measure RSS reduction and throughput improvement.", "subtopics": ["11.10.1 Standard system allocators (glibc ptmalloc) limitations: lock contention on multi-threaded workloads, severe memory fragmentation", "11.10.2 jemalloc architecture: thread-specific caches (tcache), arenas, size classes (small, large, huge), and proactive dirty page purging", "11.10.3 tcmalloc (Google Thread-Caching Malloc): thread caches, central cache, page heap, and lock-free thread allocation paths", "11.10.4 Memory fragmentation mechanics: internal fragmentation (slack space in size class) vs external fragmentation (unusable scattered holes)", "11.10.5 Dropping in alternative allocators: setting `LD_PRELOAD=/usr/lib/libjemalloc.so` without recompiling application binaries", "11.10.6 Runtime profiling with jemalloc: enabling heap profiling via `MALLOC_CONF=prof:true` and analyzing memory dumps with `jeprof`"]}'::jsonb, '["Explain how this implementation prevents: Severe glibc allocator memory fragmentation causing 10GB RSS usage when the application only holds 2GB of actual live da", "How does High-Performance Allocators: jemalloc, tcmalloc & Mimalloc scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-11', 'phase-11-lesson-11-memory-leak-debugging-in-native-code-valg', 'module-12', 11, 'Lesson 12.11: Memory Leak Debugging in Native Code: Valgrind, ASan & LeakSanitizer', 'Prerequisites: Phase 0, Lesson 11.9', 'Prerequisites: Phase 0, Lesson 11.9 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 550.0, '# Lesson 11.11: Memory Leak Debugging in Native Code: Valgrind, ASan & LeakSanitizer

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 11.9
- **Subtopics**:
  - `11.11.1` Valgrind Memcheck architecture: dynamic binary instrumentation tracking every memory read, write, and allocation in virtual CPU
  - `11.11.2` Valgrind detection capabilities: definitely lost, indirectly lost, possibly lost, still reachable memory, and invalid reads/writes
  - `11.11.3` AddressSanitizer (ASan): compile-time instrumentation (`-fsanitize=address`); shadow memory architecture, $2\times$ overhead vs Valgrind''s $20\times$
  - `11.11.4` LeakSanitizer (LSan): stand-alone or ASan-integrated memory leak detector with near-zero runtime overhead
  - `11.11.5` Detecting use-after-free, buffer overflows (stack and heap), and double-free bugs in C/C++ and Rust `unsafe` code
  - `11.11.6` Debugging memory bugs in Python C-extensions: running Python interpreter under ASan with custom suppression files
- **Key Failure Modes & Edge Cases**: Running Valgrind on high-throughput network tests, causing artificial 30x slowdown that trips network timeouts.
- **Verification & Mastery Check**: Compile a C/Rust module with AddressSanitizer; execute a test suite that triggers a use-after-free and interpret the ASan crash trace.
- **Project Application**: ModelPulse: Native memory debugging and sanitizer harness.', '{"solution.py": "# Phase 11 // Lesson 11.11: Memory Leak Debugging in Native Code: Valgrind, ASan & LeakSanitizer\n\ndef solve():\n    \"\"\"\n    Verification: Compile a C/Rust module with AddressSanitizer; execute a test suite that triggers a use-after-free a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.11", "subtopics_count": 6, "verification_criteria": "Compile a C/Rust module with AddressSanitizer; execute a test suite that triggers a use-after-free and interpret the ASan crash trace.", "subtopics": ["11.11.1 Valgrind Memcheck architecture: dynamic binary instrumentation tracking every memory read, write, and allocation in virtual CPU", "11.11.2 Valgrind detection capabilities: definitely lost, indirectly lost, possibly lost, still reachable memory, and invalid reads/writes", "11.11.3 AddressSanitizer (ASan): compile-time instrumentation (`-fsanitize=address`); shadow memory architecture, $2\\times$ overhead vs Valgrind''s $20\\times$", "11.11.4 LeakSanitizer (LSan): stand-alone or ASan-integrated memory leak detector with near-zero runtime overhead", "11.11.5 Detecting use-after-free, buffer overflows (stack and heap), and double-free bugs in C/C++ and Rust `unsafe` code", "11.11.6 Debugging memory bugs in Python C-extensions: running Python interpreter under ASan with custom suppression files"]}'::jsonb, '["Explain how this implementation prevents: Running Valgrind on high-throughput network tests, causing artificial 30x slowdown that trips network timeouts.", "How does Memory Leak Debugging in Native Code: Valgrind, ASan & LeakSanitizer scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-12', 'phase-11-lesson-12-database-profiling-i-pg-stat-statements-w', 'module-12', 12, 'Lesson 12.12: Database Profiling I: pg_stat_statements & Workload Analysis', 'Prerequisites: Phase 4, Phase 7', 'Prerequisites: Phase 4, Phase 7 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 600.0, '# Lesson 11.12: Database Profiling I: pg_stat_statements & Workload Analysis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7
- **Subtopics**:
  - `11.12.1` `pg_stat_statements` extension internals: tracking execution statistics across all SQL statements executed on PostgreSQL
  - `11.12.2` Key performance metrics: `calls`, `total_exec_time`, `mean_exec_time`, `stddev_exec_time`, `rows`, `shared_blks_hit`, `shared_blks_read`
  - `11.12.3` Identifying query bottlenecks: Top-N queries by total time (system impact) vs Top-N queries by mean time (user latency)
  - `11.12.4` Cache hit ratio calculations: evaluating PostgreSQL buffer cache efficiency: $\frac{\text{shared\_blks\_hit}}{\text{shared\_blks\_hit} + \text{shared\_blks\_read}}$
  - `11.12.5` Query normalization: how pg_stat_statements strips constants to group identical query structures together
  - `11.12.6` Automated query regression detection: scheduling periodic snapshots of pg_stat_statements into analytical tables
- **Key Failure Modes & Edge Cases**: Optimizing rare 10-second queries that execute once a month while ignoring 50ms queries that execute 5,000 times per second.
- **Verification & Mastery Check**: Configure `pg_stat_statements` on PostgreSQL; write diagnostic queries that pinpoint the top 5 most resource-consuming production queries.
- **Project Application**: ModelPulse: PostgreSQL query telemetry collector.', '{"solution.py": "# Phase 11 // Lesson 11.12: Database Profiling I: pg_stat_statements & Workload Analysis\n\ndef solve():\n    \"\"\"\n    Verification: Configure `pg_stat_statements` on PostgreSQL; write diagnostic queries that pinpoint the top 5 most \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.12", "subtopics_count": 6, "verification_criteria": "Configure `pg_stat_statements` on PostgreSQL; write diagnostic queries that pinpoint the top 5 most resource-consuming production queries.", "subtopics": ["11.12.1 `pg_stat_statements` extension internals: tracking execution statistics across all SQL statements executed on PostgreSQL", "11.12.2 Key performance metrics: `calls`, `total_exec_time`, `mean_exec_time`, `stddev_exec_time`, `rows`, `shared_blks_hit`, `shared_blks_read`", "11.12.3 Identifying query bottlenecks: Top-N queries by total time (system impact) vs Top-N queries by mean time (user latency)", "11.12.4 Cache hit ratio calculations: evaluating PostgreSQL buffer cache efficiency: $\\frac{\\text{shared\\_blks\\_hit}}{\\text{shared\\_blks\\_hit} + \\text{shared\\_blks\\_read}}$", "11.12.5 Query normalization: how pg_stat_statements strips constants to group identical query structures together", "11.12.6 Automated query regression detection: scheduling periodic snapshots of pg_stat_statements into analytical tables"]}'::jsonb, '["Explain how this implementation prevents: Optimizing rare 10-second queries that execute once a month while ignoring 50ms queries that execute 5,000 times per sec", "How does Database Profiling I: pg_stat_statements & Workload Analysis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-13', 'phase-11-lesson-13-database-profiling-ii-explain-analyze-que', 'module-12', 13, 'Lesson 12.13: Database Profiling II: EXPLAIN ANALYZE & Query Execution Plans', 'Prerequisites: Lesson 11.12', 'Prerequisites: Lesson 11.12 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 650.0, '# Lesson 11.13: Database Profiling II: EXPLAIN ANALYZE & Query Execution Plans

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.12
- **Subtopics**:
  - `11.13.1` How PostgreSQL executes queries: Parser $\to$ Rewriter $\to$ Planner/Optimizer $\to$ Executor
  - `11.13.2` `EXPLAIN` vs `EXPLAIN (ANALYZE, BUFFERS, TIMING)`: estimated plan costs vs actual execution times and buffer hits
  - `11.13.3` Cost estimation units: arbitrary units relative to 1.0 (sequential page fetch `seq_page_cost`); `random_page_cost` default 4.0
  - `11.13.4` Plan node types: Seq Scan, Index Scan, Index Only Scan, Bitmap Index Scan, Bitmap Heap Scan
  - `11.13.5` Join algorithms: Nested Loop (small sets), Hash Join (large unsorted sets), Merge Join (pre-sorted inputs)
  - `11.13.6` Spotting optimizer estimation errors: large discrepancies between estimated `rows=X` and actual `rows=Y` indicating stale statistics
- **Key Failure Modes & Edge Cases**: Running `EXPLAIN ANALYZE` on a destructive `DELETE` or `UPDATE` query in production, accidentally executing the deletion.
- **Verification & Mastery Check**: Analyze an `EXPLAIN (ANALYZE, BUFFERS)` execution plan; eliminate a slow Sequential Scan by adding an optimized composite index.
- **Project Application**: ModelPulse: Execution plan analyzer and index recommender.', '{"solution.py": "# Phase 11 // Lesson 11.13: Database Profiling II: EXPLAIN ANALYZE & Query Execution Plans\n\ndef solve():\n    \"\"\"\n    Verification: Analyze an `EXPLAIN (ANALYZE, BUFFERS)` execution plan; eliminate a slow Sequential Scan by adding a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.13", "subtopics_count": 6, "verification_criteria": "Analyze an `EXPLAIN (ANALYZE, BUFFERS)` execution plan; eliminate a slow Sequential Scan by adding an optimized composite index.", "subtopics": ["11.13.1 How PostgreSQL executes queries: Parser $\\to$ Rewriter $\\to$ Planner/Optimizer $\\to$ Executor", "11.13.2 `EXPLAIN` vs `EXPLAIN (ANALYZE, BUFFERS, TIMING)`: estimated plan costs vs actual execution times and buffer hits", "11.13.3 Cost estimation units: arbitrary units relative to 1.0 (sequential page fetch `seq_page_cost`); `random_page_cost` default 4.0", "11.13.4 Plan node types: Seq Scan, Index Scan, Index Only Scan, Bitmap Index Scan, Bitmap Heap Scan", "11.13.5 Join algorithms: Nested Loop (small sets), Hash Join (large unsorted sets), Merge Join (pre-sorted inputs)", "11.13.6 Spotting optimizer estimation errors: large discrepancies between estimated `rows=X` and actual `rows=Y` indicating stale statistics"]}'::jsonb, '["Explain how this implementation prevents: Running `EXPLAIN ANALYZE` on a destructive `DELETE` or `UPDATE` query in production, accidentally executing the deletion", "How does Database Profiling II: EXPLAIN ANALYZE & Query Execution Plans scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-14', 'phase-11-lesson-14-database-profiling-iii-lock-contention-de', 'module-12', 14, 'Lesson 12.14: Database Profiling III: Lock Contention, Deadlocks & Vacuum', 'Prerequisites: Lesson 11.12, Lesson 11.13', 'Prerequisites: Lesson 11.12, Lesson 11.13 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 700.0, '# Lesson 11.14: Database Profiling III: Lock Contention, Deadlocks & Vacuum

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.12, Lesson 11.13
- **Subtopics**:
  - `11.14.1` PostgreSQL locking hierarchy: Table locks (AccessShare to AccessExclusive) vs Row locks (ForShare, ForUpdate)
  - `11.14.2` Lock contention analysis: inspecting `pg_locks` and `pg_stat_activity` to find blocking PIDs and blocked queries
  - `11.14.3` Deadlock detection: PostgreSQL deadlock_timeout (default 1s), wait-for graph cycle resolution, and transactional retry patterns
  - `11.14.4` Multi-Version Concurrency Control (MVCC) bloat: table and index bloat caused by dead tuples left behind by updates and deletes
  - `11.14.5` Autovacuum internals: vacuum workers, scale factors (`autovacuum_vacuum_scale_factor`), cost limits, and freeze maps
  - `11.14.6` Aggressive vacuum tuning: tuning autovacuum for high-write tables to prevent table bloat and transaction ID wraparound (TXID)
- **Key Failure Modes & Edge Cases**: Running `ALTER TABLE ADD COLUMN ... DEFAULT <non-null>` on legacy Postgres versions, taking an AccessExclusive lock that freezes traffic.
- **Verification & Mastery Check**: Simulate concurrent locking conflicts; write an automated monitoring query that alerts on transactions blocked for $>5$ seconds.
- **Project Application**: ModelPulse: Database lock contention and vacuum monitor.', '{"solution.py": "# Phase 11 // Lesson 11.14: Database Profiling III: Lock Contention, Deadlocks & Vacuum\n\ndef solve():\n    \"\"\"\n    Verification: Simulate concurrent locking conflicts; write an automated monitoring query that alerts on transactio\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.14", "subtopics_count": 6, "verification_criteria": "Simulate concurrent locking conflicts; write an automated monitoring query that alerts on transactions blocked for $>5$ seconds.", "subtopics": ["11.14.1 PostgreSQL locking hierarchy: Table locks (AccessShare to AccessExclusive) vs Row locks (ForShare, ForUpdate)", "11.14.2 Lock contention analysis: inspecting `pg_locks` and `pg_stat_activity` to find blocking PIDs and blocked queries", "11.14.3 Deadlock detection: PostgreSQL deadlock_timeout (default 1s), wait-for graph cycle resolution, and transactional retry patterns", "11.14.4 Multi-Version Concurrency Control (MVCC) bloat: table and index bloat caused by dead tuples left behind by updates and deletes", "11.14.5 Autovacuum internals: vacuum workers, scale factors (`autovacuum_vacuum_scale_factor`), cost limits, and freeze maps", "11.14.6 Aggressive vacuum tuning: tuning autovacuum for high-write tables to prevent table bloat and transaction ID wraparound (TXID)"]}'::jsonb, '["Explain how this implementation prevents: Running `ALTER TABLE ADD COLUMN ... DEFAULT <non-null>` on legacy Postgres versions, taking an AccessExclusive lock that", "How does Database Profiling III: Lock Contention, Deadlocks & Vacuum scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-15', 'phase-11-lesson-15-database-profiling-iv-connection-pooling-', 'module-12', 15, 'Lesson 12.15: Database Profiling IV: Connection Pooling & PgBouncer Internals', 'Prerequisites: Lesson 11.12, Phase 4', 'Prerequisites: Lesson 11.12, Phase 4 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 750.0, '# Lesson 11.15: Database Profiling IV: Connection Pooling & PgBouncer Internals

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.12, Phase 4
- **Subtopics**:
  - `11.15.1` The cost of PostgreSQL connections: process-per-connection architecture, 5-10MB RAM per backend, and fork overhead
  - `11.15.2` Why thousands of open connections degrade database performance: context switching, cache contention, and lock table overhead
  - `11.15.3` PgBouncer architecture: lightweight, single-process, event-driven connection pooler sitting in front of PostgreSQL
  - `11.15.4` Pooling modes: Session pooling (connection held until client disconnects) vs Transaction pooling (held during transaction only)
  - `11.15.5` Statement pooling: extreme multiplexing for autocommit queries; incompatibility with prepared statements
  - `11.15.6` Configuring PgBouncer: `pool_mode = transaction`, `max_client_conn = 5000`, `default_pool_size = 50`, `reserve_pool_size`
- **Key Failure Modes & Edge Cases**: Using Transaction pooling mode with application code relying on session-level `SET` variables or un-named prepared statements.
- **Verification & Mastery Check**: Deploy PgBouncer in front of PostgreSQL; benchmark 2,000 concurrent client connections with and without pooling using `pgbench`.
- **Project Application**: ModelPulse: Enterprise database connection pooling blueprint.', '{"solution.py": "# Phase 11 // Lesson 11.15: Database Profiling IV: Connection Pooling & PgBouncer Internals\n\ndef solve():\n    \"\"\"\n    Verification: Deploy PgBouncer in front of PostgreSQL; benchmark 2,000 concurrent client connections with and with\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.15", "subtopics_count": 6, "verification_criteria": "Deploy PgBouncer in front of PostgreSQL; benchmark 2,000 concurrent client connections with and without pooling using `pgbench`.", "subtopics": ["11.15.1 The cost of PostgreSQL connections: process-per-connection architecture, 5-10MB RAM per backend, and fork overhead", "11.15.2 Why thousands of open connections degrade database performance: context switching, cache contention, and lock table overhead", "11.15.3 PgBouncer architecture: lightweight, single-process, event-driven connection pooler sitting in front of PostgreSQL", "11.15.4 Pooling modes: Session pooling (connection held until client disconnects) vs Transaction pooling (held during transaction only)", "11.15.5 Statement pooling: extreme multiplexing for autocommit queries; incompatibility with prepared statements", "11.15.6 Configuring PgBouncer: `pool_mode = transaction`, `max_client_conn = 5000`, `default_pool_size = 50`, `reserve_pool_size`"]}'::jsonb, '["Explain how this implementation prevents: Using Transaction pooling mode with application code relying on session-level `SET` variables or un-named prepared state", "How does Database Profiling IV: Connection Pooling & PgBouncer Internals scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-16', 'phase-11-lesson-16-load-testing-foundations-closed-vs-open-s', 'module-12', 16, 'Lesson 12.16: Load Testing Foundations: Closed vs Open Systems & Little''s Law', 'Prerequisites: Phase 8, Lesson 11.1', 'Prerequisites: Phase 8, Lesson 11.1 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 800.0, '# Lesson 11.16: Load Testing Foundations: Closed vs Open Systems & Little''s Law

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 8, Lesson 11.1
- **Subtopics**:
  - `11.16.1` Load testing paradigms: Closed System (fixed number of users looping; requests delayed if system slows) vs Open System
  - `11.16.2` Open System model: users arrive independently according to a Poisson process; arrival rate does not slow down when system degrades
  - `11.16.3` Why closed model load testers hide catastrophic production outages: masking queue explosions through coordinated omission
  - `11.16.4` Little''s Law: $L = \lambda W$ (Average items in system = Arrival rate $\times$ Average time in system)
  - `11.16.5` Load testing types: Smoke test (minimal load), Stress test (breaking point), Soak/Endurance test (memory leaks over 24h), Spike test
  - `11.16.6` Defining load testing targets: p95 latency $<150$ms at 5,000 QPS with $<0.01\%$ HTTP error rate
- **Key Failure Modes & Edge Cases**: Conducting load testing using a closed-loop tester that throttles itself when the server degrades, reporting misleadingly low latencies.
- **Verification & Mastery Check**: Calculate expected queue lengths and concurrency requirements for a 10,000 QPS service using Little''s Law.
- **Project Application**: ModelPulse: Load test capacity planning spreadsheet.', '{"solution.py": "# Phase 11 // Lesson 11.16: Load Testing Foundations: Closed vs Open Systems & Little''s Law\n\ndef solve():\n    \"\"\"\n    Verification: Calculate expected queue lengths and concurrency requirements for a 10,000 QPS service using Little''\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.16", "subtopics_count": 6, "verification_criteria": "Calculate expected queue lengths and concurrency requirements for a 10,000 QPS service using Little''s Law.", "subtopics": ["11.16.1 Load testing paradigms: Closed System (fixed number of users looping; requests delayed if system slows) vs Open System", "11.16.2 Open System model: users arrive independently according to a Poisson process; arrival rate does not slow down when system degrades", "11.16.3 Why closed model load testers hide catastrophic production outages: masking queue explosions through coordinated omission", "11.16.4 Little''s Law: $L = \\lambda W$ (Average items in system = Arrival rate $\\times$ Average time in system)", "11.16.5 Load testing types: Smoke test (minimal load), Stress test (breaking point), Soak/Endurance test (memory leaks over 24h), Spike test", "11.16.6 Defining load testing targets: p95 latency $<150$ms at 5,000 QPS with $<0.01\\%$ HTTP error rate"]}'::jsonb, '["Explain how this implementation prevents: Conducting load testing using a closed-loop tester that throttles itself when the server degrades, reporting misleadingl", "How does Load Testing Foundations: Closed vs Open Systems & Little''s Law scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-17', 'phase-11-lesson-17-modern-load-testing-with-k6-javascript-sc', 'module-12', 17, 'Lesson 12.17: Modern Load Testing with k6: JavaScript Scripting & Virtual Users', 'Prerequisites: Lesson 11.16', 'Prerequisites: Lesson 11.16 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 850.0, '# Lesson 11.17: Modern Load Testing with k6: JavaScript Scripting & Virtual Users

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.16
- **Subtopics**:
  - `11.17.1` k6 engine architecture: Go-based multi-threaded execution engine with embedded JavaScript (Goja) runtime for test scripts
  - `11.17.2` Writing k6 scripts: Virtual Users (VUs), `setup()`, default function, `teardown()`, and lifecycle stages
  - `11.17.3` Execution scenarios: configuring ramping VUs, constant VUs, ramping arrival rate (open model), and constant arrival rate
  - `11.17.4` Custom metrics: Counters, Gauges, Rates, and Trends; defining thresholds (`thresholds: { ''http_req_duration'': [''p(95)<200''] }`)
  - `11.17.5` Checks vs Thresholds: verifying functional response correctness without halting tests vs failing CI builds on SLA violations
  - `11.17.6` Data-driven testing: parameterizing tests with real CSV/JSON user credentials, unique search queries, and realistic payloads
- **Key Failure Modes & Edge Cases**: Writing k6 scripts that execute heavy synchronous computational loops inside the VU iteration, choking the load generator''s own CPU.
- **Verification & Mastery Check**: Write a modular k6 load testing suite simulating an e-commerce checkout flow with ramping arrival rate and strict p95 latency thresholds.
- **Project Application**: ModelPulse: Automated k6 load testing suite.', '{"solution.py": "# Phase 11 // Lesson 11.17: Modern Load Testing with k6: JavaScript Scripting & Virtual Users\n\ndef solve():\n    \"\"\"\n    Verification: Write a modular k6 load testing suite simulating an e-commerce checkout flow with ramping arrival ra\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.17", "subtopics_count": 6, "verification_criteria": "Write a modular k6 load testing suite simulating an e-commerce checkout flow with ramping arrival rate and strict p95 latency thresholds.", "subtopics": ["11.17.1 k6 engine architecture: Go-based multi-threaded execution engine with embedded JavaScript (Goja) runtime for test scripts", "11.17.2 Writing k6 scripts: Virtual Users (VUs), `setup()`, default function, `teardown()`, and lifecycle stages", "11.17.3 Execution scenarios: configuring ramping VUs, constant VUs, ramping arrival rate (open model), and constant arrival rate", "11.17.4 Custom metrics: Counters, Gauges, Rates, and Trends; defining thresholds (`thresholds: { ''http_req_duration'': [''p(95)<200''] }`)", "11.17.5 Checks vs Thresholds: verifying functional response correctness without halting tests vs failing CI builds on SLA violations", "11.17.6 Data-driven testing: parameterizing tests with real CSV/JSON user credentials, unique search queries, and realistic payloads"]}'::jsonb, '["Explain how this implementation prevents: Writing k6 scripts that execute heavy synchronous computational loops inside the VU iteration, choking the load generato", "How does Modern Load Testing with k6: JavaScript Scripting & Virtual Users scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-18', 'phase-11-lesson-18-distributed-load-testing-locust-cloud-sca', 'module-12', 18, 'Lesson 12.18: Distributed Load Testing: Locust & Cloud-Scale Traffic Injection', 'Prerequisites: Lesson 11.16, Lesson 11.17', 'Prerequisites: Lesson 11.16, Lesson 11.17 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 900.0, '# Lesson 11.18: Distributed Load Testing: Locust & Cloud-Scale Traffic Injection

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.16, Lesson 11.17
- **Subtopics**:
  - `11.18.1` Single-node load generator limits: network socket exhaustion (ephemeral port limits), client CPU saturation, and bandwidth ceilings
  - `11.18.2` Locust architecture: Python-based load testing framework with gevent coroutines; Master-Worker distributed topology
  - `11.18.3` Master node role: aggregating metrics, coordinating worker start/stop, and serving web UI dashboard
  - `11.18.4` Worker nodes role: executing greenlets injecting traffic against target systems across multiple VMs or Kubernetes pods
  - `11.18.5` Customizing traffic behavior in Locust: `FastHttpUser` (geventhttpclient) for $5\times$ higher throughput than standard `HttpUser`
  - `11.18.6` Running cloud-scale tests: deploying 50 Locust workers in Kubernetes to inject 200,000 QPS against target infrastructure
- **Key Failure Modes & Edge Cases**: Running distributed load tests from inside the same Kubernetes cluster as the target, bypassing realistic cloud ingress and firewalls.
- **Verification & Mastery Check**: Deploy a distributed Locust load testing cluster on Kubernetes with 1 master and 10 workers; generate 50,000 QPS against a test target.
- **Project Application**: ModelPulse: Distributed cloud-scale load testing harness.', '{"solution.py": "# Phase 11 // Lesson 11.18: Distributed Load Testing: Locust & Cloud-Scale Traffic Injection\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a distributed Locust load testing cluster on Kubernetes with 1 master and 10 workers; generat\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.18", "subtopics_count": 6, "verification_criteria": "Deploy a distributed Locust load testing cluster on Kubernetes with 1 master and 10 workers; generate 50,000 QPS against a test target.", "subtopics": ["11.18.1 Single-node load generator limits: network socket exhaustion (ephemeral port limits), client CPU saturation, and bandwidth ceilings", "11.18.2 Locust architecture: Python-based load testing framework with gevent coroutines; Master-Worker distributed topology", "11.18.3 Master node role: aggregating metrics, coordinating worker start/stop, and serving web UI dashboard", "11.18.4 Worker nodes role: executing greenlets injecting traffic against target systems across multiple VMs or Kubernetes pods", "11.18.5 Customizing traffic behavior in Locust: `FastHttpUser` (geventhttpclient) for $5\\times$ higher throughput than standard `HttpUser`", "11.18.6 Running cloud-scale tests: deploying 50 Locust workers in Kubernetes to inject 200,000 QPS against target infrastructure"]}'::jsonb, '["Explain how this implementation prevents: Running distributed load tests from inside the same Kubernetes cluster as the target, bypassing realistic cloud ingress ", "How does Distributed Load Testing: Locust & Cloud-Scale Traffic Injection scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-19', 'phase-11-lesson-19-network-kernel-tuning-for-high-concurrenc', 'module-12', 19, 'Lesson 12.19: Network & Kernel Tuning for High-Concurrency Systems', 'Prerequisites: Phase 0, Lesson 11.16', 'Prerequisites: Phase 0, Lesson 11.16 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 950.0, '# Lesson 11.19: Network & Kernel Tuning for High-Concurrency Systems

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 11.16
- **Subtopics**:
  - `11.19.1` Linux socket buffers: `rmem_max`, `wmem_max`, `tcp_rmem`, and `tcp_wmem` auto-tuning for high bandwidth-delay products
  - `11.19.2` File descriptor limits: configuring `nofile` limits in `/etc/security/limits.conf` and `fs.file-max` for 100,000+ open sockets
  - `11.19.3` TCP connection queues: SYN backlog (`tcp_max_syn_backlog`) and accept queue (`net.core.somaxconn`) preventing dropped handshakes
  - `11.19.4` Ephemeral port exhaustion: tuning `net.ipv4.ip_local_port_range` ($1024-65535$) and `tcp_tw_reuse` for high outbound connection rates
  - `11.19.5` TCP TIME_WAIT state mechanics: 2MSL (Maximum Segment Lifetime) delay; why reusing sockets safely requires timestamp support
  - `11.19.6` TCP Congestion Control algorithms: CUBIC (loss-based) vs Google BBR (Bottleneck Bandwidth and RTT-based) for high throughput
- **Key Failure Modes & Edge Cases**: Dropping client connections during load spikes because the Linux `somaxconn` listen backlog remained at the default 128.
- **Verification & Mastery Check**: Apply kernel `sysctl` network hardening configurations; verify that a server accepts 50,000 concurrent persistent TCP connections.
- **Project Application**: ModelPulse: Linux kernel network tuning automation script.', '{"solution.py": "# Phase 11 // Lesson 11.19: Network & Kernel Tuning for High-Concurrency Systems\n\ndef solve():\n    \"\"\"\n    Verification: Apply kernel `sysctl` network hardening configurations; verify that a server accepts 50,000 concurre\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.19", "subtopics_count": 6, "verification_criteria": "Apply kernel `sysctl` network hardening configurations; verify that a server accepts 50,000 concurrent persistent TCP connections.", "subtopics": ["11.19.1 Linux socket buffers: `rmem_max`, `wmem_max`, `tcp_rmem`, and `tcp_wmem` auto-tuning for high bandwidth-delay products", "11.19.2 File descriptor limits: configuring `nofile` limits in `/etc/security/limits.conf` and `fs.file-max` for 100,000+ open sockets", "11.19.3 TCP connection queues: SYN backlog (`tcp_max_syn_backlog`) and accept queue (`net.core.somaxconn`) preventing dropped handshakes", "11.19.4 Ephemeral port exhaustion: tuning `net.ipv4.ip_local_port_range` ($1024-65535$) and `tcp_tw_reuse` for high outbound connection rates", "11.19.5 TCP TIME_WAIT state mechanics: 2MSL (Maximum Segment Lifetime) delay; why reusing sockets safely requires timestamp support", "11.19.6 TCP Congestion Control algorithms: CUBIC (loss-based) vs Google BBR (Bottleneck Bandwidth and RTT-based) for high throughput"]}'::jsonb, '["Explain how this implementation prevents: Dropping client connections during load spikes because the Linux `somaxconn` listen backlog remained at the default 128.", "How does Network & Kernel Tuning for High-Concurrency Systems scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-20', 'phase-11-lesson-20-chaos-load-testing-blameless-failure-inje', 'module-12', 20, 'Lesson 12.20: Chaos Load Testing: Blameless Failure Injection under High Traffic', 'Prerequisites: Phase 7, Lesson 11.17', 'Prerequisites: Phase 7, Lesson 11.17 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 1000.0, '# Lesson 11.20: Chaos Load Testing: Blameless Failure Injection under High Traffic

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 11.17
- **Subtopics**:
  - `11.20.1` The objective of Chaos Load Testing: verifying that systems maintain SLAs and fail gracefully when components crash under peak load
  - `11.20.2` Combining load generators with chaos injectors: running sustained 20,000 QPS load while injecting simulated infrastructure faults
  - `11.20.3` Chaos injection scenarios: terminating primary database pods, injecting 200ms network latency to external payment gateways, killing random worker nodes
  - `11.20.4` Verifying system resilience properties: testing whether circuit breakers trip, read-replicas take over, and fallback caches engage
  - `11.20.5` Monitoring steady-state health: tracking error rates and user experience continuity throughout the chaos event
  - `11.20.6` Automated verification assertions: asserting that error rate remains $<0.5\%$ and 0 orphaned transactions linger in database
- **Key Failure Modes & Edge Cases**: Injecting chaos faults without a continuous active load test, failing to uncover race conditions that only manifest under concurrent load.
- **Verification & Mastery Check**: Execute a synchronized k6 load test while terminating the primary database replica; prove zero data corruption and self-healing under load.
- **Project Application**: ModelPulse: Automated chaos load testing verification suite.', '{"solution.py": "# Phase 11 // Lesson 11.20: Chaos Load Testing: Blameless Failure Injection under High Traffic\n\ndef solve():\n    \"\"\"\n    Verification: Execute a synchronized k6 load test while terminating the primary database replica; prove zero data \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.20", "subtopics_count": 6, "verification_criteria": "Execute a synchronized k6 load test while terminating the primary database replica; prove zero data corruption and self-healing under load.", "subtopics": ["11.20.1 The objective of Chaos Load Testing: verifying that systems maintain SLAs and fail gracefully when components crash under peak load", "11.20.2 Combining load generators with chaos injectors: running sustained 20,000 QPS load while injecting simulated infrastructure faults", "11.20.3 Chaos injection scenarios: terminating primary database pods, injecting 200ms network latency to external payment gateways, killing random worker nodes", "11.20.4 Verifying system resilience properties: testing whether circuit breakers trip, read-replicas take over, and fallback caches engage", "11.20.5 Monitoring steady-state health: tracking error rates and user experience continuity throughout the chaos event", "11.20.6 Automated verification assertions: asserting that error rate remains $<0.5\\%$ and 0 orphaned transactions linger in database"]}'::jsonb, '["Explain how this implementation prevents: Injecting chaos faults without a continuous active load test, failing to uncover race conditions that only manifest unde", "How does Chaos Load Testing: Blameless Failure Injection under High Traffic scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
