export interface PhaseData {
  id: number;
  slug: string;
  title: string;
  category: "Systems" | "Algorithms" | "Distributed" | "AI/ML" | "Full-Stack";
  lessonsCount: number;
  subtopicsCount: number;
  capstonesCount: number;
  capstoneTitle: string;
  description: string;
  keyTopics: string[];
}

export const CURRICULUM_STATS = {
  totalLessons: 600,
  totalPhases: 15,
  totalCapstones: 22,
  totalSubtopics: 3000,
  estimatedHours: 490,
  averagePassRate: "91.8%",
};

export const CURRICULUM_PHASES: PhaseData[] = [
  {
    id: 0,
    slug: "phase-00-computing-developer-environment",
    title: "Python & AI Developer Foundations",
    category: "Systems",
    lessonsCount: 50,
    subtopicsCount: 250,
    capstonesCount: 1,
    capstoneTitle: "PromptCLI: Developer AI Workbench",
    description: "Beginner-friendly computing fundamentals: writing clean Python, command-line mastery, virtual environments, Git branching, JSON handling, and making your first AI API calls.",
    keyTopics: ["Terminal & Shell Automation", "Python Syntax, Logic & Control Flow", "Working with Strings, JSON & Files", "Git Branching & Collaborative Workflows", "Prompt Templating & First LLM API Calls"],
  },
  {
    id: 1,
    slug: "phase-01-programming-mastery",
    title: "AI Software Architecture & Data Contracts",
    category: "Systems",
    lessonsCount: 50,
    subtopicsCount: 250,
    capstonesCount: 1,
    capstoneTitle: "SchemaAgent: Resilient AI Client SDK",
    description: "Building production software: object-oriented design, CPython memory patterns, Pydantic data validation schemas, automated unit testing with pytest, and resilient AI client SDKs.",
    keyTopics: ["Clean Functions & Modularity", "Object-Oriented Design Patterns", "Pydantic v2 & Guaranteed Data Contracts", "Automated Testing Suites with pytest", "Middleware & Circuit Breakers"],
  },
  {
    id: 2,
    slug: "phase-02-mathematics-numerical-computing",
    title: "Intuitive Math, Vectors & Numerical Computing",
    category: "AI/ML",
    lessonsCount: 60,
    subtopicsCount: 300,
    capstonesCount: 1,
    capstoneTitle: "VectorLite Numerical Search Engine",
    description: "Visual mathematics for AI: 2D/3D coordinates, vectors, dot products, cosine similarity, dimensions, token embeddings, and NumPy array computing from scratch.",
    keyTopics: ["Visual Vector Intuition & Coordinates", "Dot Products & Cosine Similarity", "High-Dimensional Vector Spaces", "NumPy Array Memory & Operations", "Word & Sentence Embedding Mechanics"],
  },
  {
    id: 3,
    slug: "phase-03-data-structures-algorithms",
    title: "Data Structures & Practical Problem Solving",
    category: "Algorithms",
    lessonsCount: 75,
    subtopicsCount: 375,
    capstonesCount: 1,
    capstoneTitle: "DataSifter High-Speed Dataset Cleaning Engine",
    description: "Algorithmic mastery: hash maps, sliding windows, two-pointers, stacks, queues, trees, and text tokenization algorithms required for data pipelines.",
    keyTopics: ["Hash Maps & Frequency Counting", "Two-Pointers & Sliding Window", "Binary Search & Search Spaces", "Trees, Graphs & Recursive Traversals", "Tokenization & Text Chunking Algorithms"],
  },
  {
    id: 4,
    slug: "phase-04-systems-internals-os-docker",
    title: "Web Architecture, HTTP & Asynchronous APIs",
    category: "Systems",
    lessonsCount: 35,
    subtopicsCount: 175,
    capstonesCount: 1,
    capstoneTitle: "GatewayAI Asynchronous Streaming Proxy",
    description: "How modern web systems communicate: HTTP/1.1 and HTTP/2, REST APIs, Python asyncio event loops, Server-Sent Events (SSE) for token streaming, and Docker containerization.",
    keyTopics: ["Client-Server Architecture & HTTP", "Python Asyncio & Non-Blocking Loops", "FastAPI Asynchronous Microservices", "Server-Sent Events (SSE) Token Streaming", "Docker Containers & Isolated Workspaces"],
  },
  {
    id: 5,
    slug: "phase-05-backend-systems-api-engineering",
    title: "Relational Databases, PostgreSQL & Semantic Caching",
    category: "Systems",
    lessonsCount: 45,
    subtopicsCount: 225,
    capstonesCount: 3,
    capstoneTitle: "ChatMemory Vault, CacheKit, and AuthForge",
    description: "Persistent data systems: relational modeling, SQL optimization, PostgreSQL indexing, connection pooling, ACID transactions, and Redis semantic caching for AI responses.",
    keyTopics: ["Relational Modeling & PostgreSQL", "SQL Indexing & Execution Performance", "ACID Transactions & Connection Pools", "Redis In-Memory & Semantic Caching", "User Auth, API Keys & Rate Limiting"],
  },
  {
    id: 6,
    slug: "phase-06-full-stack-frontend-engineering",
    title: "Full-Stack Frontend Engineering & Browser Internals",
    category: "Full-Stack",
    lessonsCount: 40,
    subtopicsCount: 200,
    capstonesCount: 2,
    capstoneTitle: "CompKit Design System & TenantIQ Multi-Tenant Dashboard",
    description: "Browser rendering engine internals, DOM tree, CSS layout models, modern React reconciliation, Next.js App Router, SSR, and Playwright E2E suites.",
    keyTopics: ["Browser Parsing, Layout & Paint Cycles", "Modern CSS & Responsive Systems", "React Virtual DOM Reconciliation", "Next.js App Router & Server Components", "End-to-End Testing with Playwright"],
  },
  {
    id: 7,
    slug: "phase-07-distributed-systems-cloud-devops",
    title: "Distributed Systems & Platform Engineering",
    category: "Distributed",
    lessonsCount: 35,
    subtopicsCount: 175,
    capstonesCount: 1,
    capstoneTitle: "InfraBlueprint Cloud-Native Infrastructure",
    description: "Consensus protocols (Raft), Kubernetes orchestration, Terraform infrastructure-as-code, Apache Kafka streaming, and LitmusChaos fault injection.",
    keyTopics: ["Raft Consensus & Leader Election", "Kubernetes Pod Lifecycle & CRDs", "Terraform Infrastructure as Code", "Kafka Partitioning & Consumer Groups", "Chaos Engineering & Resiliency"],
  },
  {
    id: 8,
    slug: "phase-08-systems-design-interview-mastery",
    title: "Systems Design & High-Availability Architectures",
    category: "Distributed",
    lessonsCount: 25,
    subtopicsCount: 125,
    capstonesCount: 1,
    capstoneTitle: "10 Scaled Enterprise Architecture Portfolios",
    description: "Capacity estimation, back-of-the-envelope math, high availability, database sharding, CAP theorem tradeoffs, and FAANG-grade system design defense.",
    keyTopics: ["Scale & Capacity Estimation Math", "Database Sharding & Consistent Hashing", "Message Fanout & Feed Architecture", "Global CDN & Multi-Region Failover", "System Tradeoff & Bottleneck Defense"],
  },
  {
    id: 9,
    slug: "phase-09-mathematics-deep-learning-autograd",
    title: "Mathematics of Deep Learning, Autograd & Core Neural Architectures",
    category: "AI/ML",
    lessonsCount: 35,
    subtopicsCount: 175,
    capstonesCount: 2,
    capstoneTitle: "GradFlow Autograd Engine & TransformerLab",
    description: "Reverse-mode autodiff, computational graphs, MLP backpropagation from scratch, transformer self-attention, and PyTorch tensors.",
    keyTopics: ["Computational Graph Directed Acyclic Graphs", "Reverse-Mode Automatic Differentiation", "Multi-Layer Perceptrons from Scratch", "Scaled Dot-Product Self-Attention", "Multi-Head Attention & Transformer Encoders"],
  },
  {
    id: 10,
    slug: "phase-10-generative-ai-rag-vector-systems",
    title: "Production RAG, Hybrid Retrieval & pgvector",
    category: "AI/ML",
    lessonsCount: 35,
    subtopicsCount: 175,
    capstonesCount: 2,
    capstoneTitle: "EvalKit Vector Benchmark & DocuMind Hybrid RAG",
    description: "Production RAG architectures: semantic chunking, PostgreSQL pgvector with HNSW indexing, hybrid sparse (BM25) + dense search, cross-encoder re-ranking, and grounded citation pipelines.",
    keyTopics: ["Document Ingestion & Semantic Chunking", "PostgreSQL pgvector & HNSW Indexing", "Hybrid BM25 + Dense Vector Search", "Cross-Encoder Re-ranking Models", "RAG Triad & Hallucination Mitigation"],
  },
  {
    id: 11,
    slug: "phase-11-production-engineering-mlops",
    title: "AI Evals, Observability & OpenTelemetry",
    category: "Systems",
    lessonsCount: 25,
    subtopicsCount: 125,
    capstonesCount: 1,
    capstoneTitle: "ModelPulse Observability & Drift Detection System",
    description: "Testing and observing generative AI: LLM-as-a-judge evaluation frameworks (Ragas/DeepEval), synthetic test sets, OpenTelemetry distributed tracing (Langfuse), latency (TTFT), and cost telemetry.",
    keyTopics: ["LLM-as-a-Judge & Automated Evals", "Synthetic Evaluation Dataset Generation", "OpenTelemetry & Langfuse Tracing", "Time-To-First-Token (TTFT) & Latency", "Prompt Regression & Safety Benchmarks"],
  },
  {
    id: 12,
    slug: "phase-12-autonomous-ai-agents-orchestration",
    title: "Autonomous Agents, State Machines & Model Context Protocol",
    category: "AI/ML",
    lessonsCount: 30,
    subtopicsCount: 150,
    capstonesCount: 1,
    capstoneTitle: "AutoDev-Agent Autonomous Assistant",
    description: "Stateful autonomous agent systems: ReAct reasoning loops, tool calling interfaces, LangGraph cyclic state machines, Model Context Protocol (MCP) tool integration, and secure sandbox execution.",
    keyTopics: ["ReAct Agent Loops & Tool Execution", "Cyclic State Machines with LangGraph", "Model Context Protocol (MCP) Standards", "Ephemeral Docker Execution Sandboxes", "Agent Guardrails, Checkpointing & Recovery"],
  },
  {
    id: 13,
    slug: "phase-13-specialized-production-tracks",
    title: "Specialized Production Tracks",
    category: "Full-Stack",
    lessonsCount: 20,
    subtopicsCount: 100,
    capstonesCount: 1,
    capstoneTitle: "Specialization Track Production Portfolio",
    description: "Deep dive specialization tracks: AI Product Engineering, MLOps & AI Infrastructure, AI Security & Red Teaming, or Applied AI Research.",
    keyTopics: ["Track 1: AI Product Engineering", "Track 2: MLOps & AI Infrastructure", "Track 3: AI Security & Red Teaming", "Track 4: Applied AI Research", "Specialization Benchmark Defense"],
  },
  {
    id: 14,
    slug: "phase-14-comprehensive-enterprise-capstone",
    title: "Comprehensive Capstone Project & Production Defense",
    category: "Full-Stack",
    lessonsCount: 15,
    subtopicsCount: 75,
    capstonesCount: 1,
    capstoneTitle: "Enterprise-Grade Autonomous AI Platform",
    description: "End-to-end multi-tenant autonomous AI software system built from raw architecture to production deployment, security audit, and live defense.",
    keyTopics: ["Architecture Specification & RFC", "Multi-Tenant Cloud-Native Microservices", "Resilient Agent Execution & Guardrails", "CI/CD, Monitoring & SLOs", "Final Architectural Production Defense"],
  },
];
