export interface PhaseData {
  id: number;
  slug: string;
  title: string;
  category: "Systems" | "Algorithms" | "Distributed" | "AI/ML" | "Full-Stack";
  lessonsCount: number;
  subtopicsCount: number;
  capstonesCount: number;
  capstoneTitle: string;
  description: string;
  keyTopics: string[];
}

export const CURRICULUM_STATS = {
  totalLessons: 600,
  totalPhases: 15,
  totalCapstones: 22,
  totalSubtopics: 3000,
  estimatedHours: 490,
  averagePassRate: "91.8%",
};

export const CURRICULUM_PHASES: PhaseData[] = [
  {
    id: 0,
    slug: "phase-00-computing-developer-environment",
    title: "Computing & Developer Environment",
    category: "Systems",
    lessonsCount: 50,
    subtopicsCount: 250,
    capstonesCount: 1,
    capstoneTitle: "SysTrace System Profiler & Environment Blueprint",
    description: "Beginner-friendly computing fundamentals: shell scripting, virtual environments, Git branching, terminal debugging, memory models, syscalls, and developer ergonomics.",
    keyTopics: ["Terminal & Shell Fundamentals", "Virtual Environments & Dependencies", "Git Plumbing & Interactive Workflows", "POSIX Syscalls & File Descriptors", "Process Memory & Virtual Memory"],
  },
  {
    id: 1,
    slug: "phase-01-programming-mastery",
    title: "Programming Mastery",
    category: "Algorithms",
    lessonsCount: 75,
    subtopicsCount: 375,
    capstonesCount: 3,
    capstoneTitle: "LoxLang Interpreter, TypeTrace, and DevAudit",
    description: "Beginner programming ramp from variables and control flow up to OOP, static typing, AST parsers, tree-walk interpreters, and GoF design patterns.",
    keyTopics: ["Syntax, Loops & Conditionals", "Functions, Scope & Recursion", "Object-Oriented Design & Clean Architecture", "Static Typing & Generic Systems", "Tree-Walk Interpreters & ASTs"],
  },
  {
    id: 2,
    slug: "phase-02-mathematics-numerical-computing",
    title: "Mathematics for Engineers & Numerical Computing",
    category: "AI/ML",
    lessonsCount: 60,
    subtopicsCount: 300,
    capstonesCount: 1,
    capstoneTitle: "MathKit Vectorized Numerical Engine",
    description: "Intuitive mathematics: coordinate geometry, vectors, matrices, probability distributions, calculus, gradient descent, and NumPy memory layout from scratch.",
    keyTopics: ["Visual Linear Algebra Intuition", "Matrix Operations & Inversion", "Calculus & Automatic Gradients", "Probability & Distributions", "NumPy Strides & Buffer Protocol"],
  },
  {
    id: 3,
    slug: "phase-03-data-structures-algorithms",
    title: "Data Structures, Algorithms & Problem Solving",
    category: "Algorithms",
    lessonsCount: 75,
    subtopicsCount: 375,
    capstonesCount: 1,
    capstoneTitle: "DataSift High-Throughput Stream Processing Engine",
    description: "Gradual algorithmic mastery: two-pointers, sliding window, binary search, linear structures, trees, graphs, dynamic programming, and streaming sketches.",
    keyTopics: ["Two-Pointers & Sliding Window", "Hash Tables & Frequency Counting", "Binary Search Invariants", "Trees, Heaps & Graph Traversals", "Dynamic Programming & Memoization"],
  },
  {
    id: 4,
    slug: "phase-04-systems-internals-os-docker",
    title: "Systems Internals: OS, Concurrency, Networks, Docker",
    category: "Systems",
    lessonsCount: 35,
    subtopicsCount: 175,
    capstonesCount: 1,
    capstoneTitle: "NanoHTTP Event-Driven Web Server",
    description: "Kernel internals, epoll event loops, threads vs processes, socket programming, network protocol framing, and container isolation (cgroups & namespaces).",
    keyTopics: ["Linux Syscalls & File Descriptors", "epoll Event Multiplexing", "Threads, Locks & Atomics", "BSD Sockets & TCP Protocol", "cgroups v2 & Linux Namespaces"],
  },
  {
    id: 5,
    slug: "phase-05-backend-systems-api-engineering",
    title: "Backend Systems & API Engineering",
    category: "Systems",
    lessonsCount: 45,
    subtopicsCount: 225,
    capstonesCount: 3,
    capstoneTitle: "SchemaVault, CacheKit, and AuthForge",
    description: "Relational database internals, SQL optimization, MVCC, Redis caching tiers, token authentication, rate limiting, gRPC, and asynchronous Celery queues.",
    keyTopics: ["SQL Indexing & Query Execution Plans", "PostgreSQL MVCC & Isolation Levels", "Redis Caching Strategies & Eviction", "OAuth2, JWT & RBAC Auth Gateways", "gRPC Protobuf Services & Celery Tasks"],
  },
  {
    id: 6,
    slug: "phase-06-full-stack-frontend-engineering",
    title: "Full-Stack Frontend Engineering & Browser Internals",
    category: "Full-Stack",
    lessonsCount: 40,
    subtopicsCount: 200,
    capstonesCount: 2,
    capstoneTitle: "CompKit Design System & TenantIQ Multi-Tenant Dashboard",
    description: "Browser rendering engine internals, DOM tree, CSS layout models, modern React reconciliation, Next.js App Router, SSR, and Playwright E2E suites.",
    keyTopics: ["Browser Parsing, Layout & Paint Cycles", "Modern CSS & Responsive Systems", "React Virtual DOM Reconciliation", "Next.js App Router & Server Components", "End-to-End Testing with Playwright"],
  },
  {
    id: 7,
    slug: "phase-07-distributed-systems-cloud-devops",
    title: "Distributed Systems & Platform Engineering",
    category: "Distributed",
    lessonsCount: 35,
    subtopicsCount: 175,
    capstonesCount: 1,
    capstoneTitle: "InfraBlueprint Cloud-Native Infrastructure",
    description: "Consensus protocols (Raft), Kubernetes orchestration, Terraform infrastructure-as-code, Apache Kafka streaming, and LitmusChaos fault injection.",
    keyTopics: ["Raft Consensus & Leader Election", "Kubernetes Pod Lifecycle & CRDs", "Terraform Infrastructure as Code", "Kafka Partitioning & Consumer Groups", "Chaos Engineering & Resiliency"],
  },
  {
    id: 8,
    slug: "phase-08-systems-design-interview-mastery",
    title: "Systems Design & High-Availability Architectures",
    category: "Distributed",
    lessonsCount: 25,
    subtopicsCount: 125,
    capstonesCount: 1,
    capstoneTitle: "10 Scaled Enterprise Architecture Portfolios",
    description: "Capacity estimation, back-of-the-envelope math, high availability, database sharding, CAP theorem tradeoffs, and FAANG-grade system design defense.",
    keyTopics: ["Scale & Capacity Estimation Math", "Database Sharding & Consistent Hashing", "Message Fanout & Feed Architecture", "Global CDN & Multi-Region Failover", "System Tradeoff & Bottleneck Defense"],
  },
  {
    id: 9,
    slug: "phase-09-mathematics-deep-learning-autograd",
    title: "Mathematics of Deep Learning, Autograd & Core Neural Architectures",
    category: "AI/ML",
    lessonsCount: 35,
    subtopicsCount: 175,
    capstonesCount: 2,
    capstoneTitle: "GradFlow Autograd Engine & TransformerLab",
    description: "Reverse-mode autodiff, computational graphs, MLP backpropagation from scratch, transformer self-attention, and PyTorch tensors.",
    keyTopics: ["Computational Graph Directed Acyclic Graphs", "Reverse-Mode Automatic Differentiation", "Multi-Layer Perceptrons from Scratch", "Scaled Dot-Product Self-Attention", "Multi-Head Attention & Transformer Encoders"],
  },
  {
    id: 10,
    slug: "phase-10-generative-ai-rag-vector-systems",
    title: "Generative AI, Retrieval-Augmented Generation (RAG) & Vector Systems",
    category: "AI/ML",
    lessonsCount: 35,
    subtopicsCount: 175,
    capstonesCount: 2,
    capstoneTitle: "EvalKit Vector Benchmark & DocuMind Hybrid RAG",
    description: "Vector embeddings, HNSW graph index traversal, dense and sparse hybrid retrieval, reciprocal rank fusion, cross-encoders, and LLM evaluation.",
    keyTopics: ["Dense Embeddings & Cosine Similarity", "HNSW & IVFFlat Vector Indexing", "Hybrid BM25 + Dense Retrieval", "Cross-Encoder Re-ranking Models", "LLM-as-a-Judge Evaluation Frameworks"],
  },
  {
    id: 11,
    slug: "phase-11-production-engineering-mlops",
    title: "Production Engineering, Performance Profiling & MLOps",
    category: "Systems",
    lessonsCount: 25,
    subtopicsCount: 125,
    capstonesCount: 1,
    capstoneTitle: "ModelPulse Observability & Drift Detection System",
    description: "Sampling CPU profilers (py-spy), memory allocators (memray), load testing (k6), MLflow experiment tracking, and model drift telemetry.",
    keyTopics: ["Sampling CPU Profiling & Flame Graphs", "Heap Memory Allocations & Tracing", "High-Throughput Load Testing with k6", "MLflow Model Lifecycle Tracking", "Data & Prediction Drift Detection"],
  },
  {
    id: 12,
    slug: "phase-12-autonomous-ai-agents-orchestration",
    title: "Autonomous AI Agents & Tool Orchestration",
    category: "AI/ML",
    lessonsCount: 30,
    subtopicsCount: 150,
    capstonesCount: 1,
    capstoneTitle: "CodeAgent Autonomous Development Assistant",
    description: "ReAct reasoning loops, tool calling interfaces, LangGraph cyclic state graphs, secure container sandboxing, and multi-agent coordination.",
    keyTopics: ["ReAct Agent Loops & Tool Execution", "Cyclic State Machines & LangGraph", "Subprocess & Docker Code Sandboxing", "Multi-Agent Protocol & Delegation", "Agent Evaluation & Loop Guards"],
  },
  {
    id: 13,
    slug: "phase-13-specialized-production-tracks",
    title: "Specialized Production Tracks",
    category: "Full-Stack",
    lessonsCount: 20,
    subtopicsCount: 100,
    capstonesCount: 1,
    capstoneTitle: "Specialization Track Production Portfolio",
    description: "Deep dive specialization tracks: AI Product Engineering, MLOps & AI Infrastructure, AI Security & Red Teaming, or Applied AI Research.",
    keyTopics: ["Track 1: AI Product Engineering", "Track 2: MLOps & AI Infrastructure", "Track 3: AI Security & Red Teaming", "Track 4: Applied AI Research", "Specialization Benchmark Defense"],
  },
  {
    id: 14,
    slug: "phase-14-comprehensive-enterprise-capstone",
    title: "Comprehensive Capstone Project & Production Defense",
    category: "Full-Stack",
    lessonsCount: 15,
    subtopicsCount: 75,
    capstonesCount: 1,
    capstoneTitle: "Enterprise-Grade Autonomous AI Platform",
    description: "End-to-end multi-tenant autonomous AI software system built from raw architecture to production deployment, security audit, and live defense.",
    keyTopics: ["Architecture Specification & RFC", "Multi-Tenant Cloud-Native Microservices", "Resilient Agent Execution & Guardrails", "CI/CD, Monitoring & SLOs", "Final Architectural Production Defense"],
  },
];
