INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-3-41', 'phase-03-lesson-41-cpython-dict-architecture-compact-dict-pe', 'module-5', 41, 'Lesson 5.41: CPython `dict` Architecture: Compact Dict & Perturb Probing', 'Prerequisites: Lesson 3.40', 'Prerequisites: Lesson 3.40 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 2050.0, '# Lesson 3.41: CPython `dict` Architecture: Compact Dict & Perturb Probing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.40
- **Subtopics**:
  - `3.41.1` Historical Python dict memory layout: 24-byte entries containing sparse unallocated rows.
  - `3.41.2` Modern Compact Dict (PEP 468): dense `entries` array + sparse byte `indices` array; 30%–95% memory savings.
  - `3.41.3` CPython Perturb Probing formula: `j = ((5*j) + 1 + perturb) % m; perturb >>= 5`.
  - `3.41.4` Preserving insertion order: how compact dicts naturally make Python dictionaries ordered.
- **Key Failure Modes & Edge Cases**: Relying on dictionary insertion order in older runtime environments or cross-language serialization.
- **Verification & Mastery Check**: Implement a compact dictionary prototype matching CPython''s indices/entries array architecture.
- **Project Application**: DataSift: High-cardinality aggregation.', '{"solution.py": "# Phase 3 // Lesson 3.41: CPython `dict` Architecture: Compact Dict & Perturb Probing\n\ndef solve():\n    \"\"\"\n    Verification: Implement a compact dictionary prototype matching CPython''s indices/entries array architecture.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.41", "subtopics_count": 4, "verification_criteria": "Implement a compact dictionary prototype matching CPython''s indices/entries array architecture.", "subtopics": ["3.41.1 Historical Python dict memory layout: 24-byte entries containing sparse unallocated rows.", "3.41.2 Modern Compact Dict (PEP 468): dense `entries` array + sparse byte `indices` array; 30%\u201395% memory savings.", "3.41.3 CPython Perturb Probing formula: `j = ((5*j) + 1 + perturb) % m; perturb >>= 5`.", "3.41.4 Preserving insertion order: how compact dicts naturally make Python dictionaries ordered."]}'::jsonb, '["Explain how this implementation prevents: Relying on dictionary insertion order in older runtime environments or cross-language serialization.", "How does CPython `dict` Architecture: Compact Dict & Perturb Probing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-42', 'phase-03-lesson-42-bloom-filters-probabilistic-set-membershi', 'module-5', 42, 'Lesson 5.42: Bloom Filters & Probabilistic Set Membership', 'Prerequisites: Lesson 3.38', 'Prerequisites: Lesson 3.38 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 2100.0, '# Lesson 3.42: Bloom Filters & Probabilistic Set Membership

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.38
- **Subtopics**:
  - `3.42.1` The memory limit of exact hash sets: tracking billions of keys exceeding available physical RAM.
  - `3.42.2` Bloom Filter architecture: bit array of size $m$, $k$ independent hash functions.
  - `3.42.3` Operations: `add(key)` sets $k$ bits to 1; `contains(key)` checks if all $k$ bits are 1.
  - `3.42.4` Error bounds: zero false negatives guaranteed; mathematical false positive rate: $(1 - e^{-kn/m})^k$.
- **Key Failure Modes & Edge Cases**: Assuming a Bloom filter can confirm presence with 100% certainty (it only confirms *absence* with certainty).
- **Verification & Mastery Check**: Implement a Bloom Filter from scratch, calculate optimal $m$ and $k$ for 1M keys at 1% false positive rate, and empirically verify error rate.
- **Project Application**: Phase 8: Web crawler URL deduplication.', '{"solution.py": "# Phase 3 // Lesson 3.42: Bloom Filters & Probabilistic Set Membership\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Bloom Filter from scratch, calculate optimal $m$ and $k$ for 1M keys at 1% false positiv\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.42", "subtopics_count": 4, "verification_criteria": "Implement a Bloom Filter from scratch, calculate optimal $m$ and $k$ for 1M keys at 1% false positive rate, and empirically verify error rate.", "subtopics": ["3.42.1 The memory limit of exact hash sets: tracking billions of keys exceeding available physical RAM.", "3.42.2 Bloom Filter architecture: bit array of size $m$, $k$ independent hash functions.", "3.42.3 Operations: `add(key)` sets $k$ bits to 1; `contains(key)` checks if all $k$ bits are 1.", "3.42.4 Error bounds: zero false negatives guaranteed; mathematical false positive rate: $(1 - e^{-kn/m})^k$."]}'::jsonb, '["Explain how this implementation prevents: Assuming a Bloom filter can confirm presence with 100% certainty (it only confirms *absence* with certainty).", "How does Bloom Filters & Probabilistic Set Membership scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-43', 'phase-03-lesson-43-binary-trees-tree-traversals-depth-analys', 'module-5', 43, 'Lesson 5.43: Binary Trees: Tree Traversals & Depth Analysis', 'Prerequisites: Phase 2 (Lesson 2.8)', 'Prerequisites: Phase 2 (Lesson 2.8) | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 2150.0, '# Lesson 3.43: Binary Trees: Tree Traversals & Depth Analysis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2 (Lesson 2.8)
- **Subtopics**:
  - `3.43.1` Tree recursive definition: root node, left subtree, right subtree, leaves.
  - `3.43.2` Depth-First Traversals: Pre-order ($N-L-R$), In-order ($L-N-R$), Post-order ($L-R-N$); call stack visualization.
  - `3.43.3` Breadth-First Traversal (Level-order): queue-based level-by-level breadth exploration.
  - `3.43.4` Tree properties: height, depth, diameter, complete vs full vs degenerate trees.
- **Key Failure Modes & Edge Cases**: Unbounded recursion in tree traversals exceeding call stack limits on skewed, degenerate trees.
- **Verification & Mastery Check**: Implement all four tree traversals both recursively and iteratively using an explicit stack/queue.
- **Project Application**: LoxLang: AST traversals.', '{"solution.py": "# Phase 3 // Lesson 3.43: Binary Trees: Tree Traversals & Depth Analysis\n\ndef solve():\n    \"\"\"\n    Verification: Implement all four tree traversals both recursively and iteratively using an explicit stack/queue.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.43", "subtopics_count": 4, "verification_criteria": "Implement all four tree traversals both recursively and iteratively using an explicit stack/queue.", "subtopics": ["3.43.1 Tree recursive definition: root node, left subtree, right subtree, leaves.", "3.43.2 Depth-First Traversals: Pre-order ($N-L-R$), In-order ($L-N-R$), Post-order ($L-R-N$); call stack visualization.", "3.43.3 Breadth-First Traversal (Level-order): queue-based level-by-level breadth exploration.", "3.43.4 Tree properties: height, depth, diameter, complete vs full vs degenerate trees."]}'::jsonb, '["Explain how this implementation prevents: Unbounded recursion in tree traversals exceeding call stack limits on skewed, degenerate trees.", "How does Binary Trees: Tree Traversals & Depth Analysis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-44', 'phase-03-lesson-44-binary-search-trees-bst-invariants-node-d', 'module-5', 44, 'Lesson 5.44: Binary Search Trees (BST): Invariants & Node Deletion', 'Prerequisites: Lesson 3.43', 'Prerequisites: Lesson 3.43 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 2200.0, '# Lesson 3.44: Binary Search Trees (BST): Invariants & Node Deletion

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.43
- **Subtopics**:
  - `3.44.1` The BST Invariant: for every node, all left subtree values are smaller, all right subtree values are larger.
  - `3.44.2` Search and Insertion: $O(h)$ time where $h$ is tree height.
  - `3.44.3` Node Deletion algorithm: 3 cases (Leaf node, Node with one child, Node with two children / in-order successor swap).
  - `3.44.4` The Degeneracy hazard: sorted insertions degrading a BST into an $O(n)$ linked list.
- **Key Failure Modes & Edge Cases**: Deleting a node with two children incorrectly, severing subtree linkages and violating BST invariants.
- **Verification & Mastery Check**: Implement a full BST from scratch supporting search, insertion, and 3-case node deletion.
- **Project Application**: DataSift: Sorted indexing.', '{"solution.py": "# Phase 3 // Lesson 3.44: Binary Search Trees (BST): Invariants & Node Deletion\n\ndef solve():\n    \"\"\"\n    Verification: Implement a full BST from scratch supporting search, insertion, and 3-case node deletion.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.44", "subtopics_count": 4, "verification_criteria": "Implement a full BST from scratch supporting search, insertion, and 3-case node deletion.", "subtopics": ["3.44.1 The BST Invariant: for every node, all left subtree values are smaller, all right subtree values are larger.", "3.44.2 Search and Insertion: $O(h)$ time where $h$ is tree height.", "3.44.3 Node Deletion algorithm: 3 cases (Leaf node, Node with one child, Node with two children / in-order successor swap).", "3.44.4 The Degeneracy hazard: sorted insertions degrading a BST into an $O(n)$ linked list."]}'::jsonb, '["Explain how this implementation prevents: Deleting a node with two children incorrectly, severing subtree linkages and violating BST invariants.", "How does Binary Search Trees (BST): Invariants & Node Deletion scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-45', 'phase-03-lesson-45-balanced-search-trees-avl-tree-rotations', 'module-5', 45, 'Lesson 5.45: Balanced Search Trees: AVL Tree Rotations', 'Prerequisites: Lesson 3.44', 'Prerequisites: Lesson 3.44 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 2250.0, '# Lesson 3.45: Balanced Search Trees: AVL Tree Rotations

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.44
- **Subtopics**:
  - `3.45.1` Why balance matters: guaranteeing $O(\log n)$ height under all insertion sequences.
  - `3.45.2` AVL Balance Factor: $	ext{height}(	ext{left}) - 	ext{height}(	ext{right}) \in \{-1, 0, 1\}$.
  - `3.45.3` Single Rotations: Left Rotation (LL) and Right Rotation (RR).
  - `3.45.4` Double Rotations: Left-Right Rotation (LR) and Right-Left Rotation (RL).
- **Key Failure Modes & Edge Cases**: Failing to update tree heights after rotations, causing subsequent balance factor calculations to fail.
- **Verification & Mastery Check**: Implement an AVL Tree with automatic self-balancing via rotations on insertion.
- **Project Application**: DataSift: Range query indexes.', '{"solution.py": "# Phase 3 // Lesson 3.45: Balanced Search Trees: AVL Tree Rotations\n\ndef solve():\n    \"\"\"\n    Verification: Implement an AVL Tree with automatic self-balancing via rotations on insertion.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.45", "subtopics_count": 4, "verification_criteria": "Implement an AVL Tree with automatic self-balancing via rotations on insertion.", "subtopics": ["3.45.1 Why balance matters: guaranteeing $O(\\log n)$ height under all insertion sequences.", "3.45.2 AVL Balance Factor: $\text{height}(\text{left}) - \text{height}(\text{right}) \\in \\{-1, 0, 1\\}$.", "3.45.3 Single Rotations: Left Rotation (LL) and Right Rotation (RR).", "3.45.4 Double Rotations: Left-Right Rotation (LR) and Right-Left Rotation (RL)."]}'::jsonb, '["Explain how this implementation prevents: Failing to update tree heights after rotations, causing subsequent balance factor calculations to fail.", "How does Balanced Search Trees: AVL Tree Rotations scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-1', 'phase-04-lesson-01-process-address-space-segments-memory-lay', 'module-6', 1, 'Lesson 6.1: Process Address Space: Segments & Memory Layout', 'Prerequisites: Phase 0 (Lesson 0.9)', 'Prerequisites: Phase 0 (Lesson 0.9) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 50.0, '# Lesson 4.1: Process Address Space: Segments & Memory Layout

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.9)
- **Subtopics**:
  - `4.1.1` The 64-bit virtual memory address space: user space (lower addresses) vs kernel space (upper canonical addresses).
  - `4.1.2` Segment breakdown: Text (.text), Initialized Data (.data), Uninitialized Data (.bss), Heap, Memory Mapping, Stack.
  - `4.1.3` Address Space Layout Randomization (ASLR): randomizing base addresses to prevent buffer overflow exploits.
  - `4.1.4` Inspecting process memory maps via `/proc/<pid>/maps` and runtime segment boundaries.
- **Key Failure Modes & Edge Cases**: Assuming fixed memory addresses across program executions, broken by ASLR security mitigations.
- **Verification & Mastery Check**: Write a C/Python script to inspect and print the memory addresses of stack, heap, and text variables in real time.
- **Project Application**: NanoHTTP: Memory-mapped static file buffers.', '{"solution.py": "# Phase 4 // Lesson 4.1: Process Address Space: Segments & Memory Layout\n\ndef solve():\n    \"\"\"\n    Verification: Write a C/Python script to inspect and print the memory addresses of stack, heap, and text variables\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.1", "subtopics_count": 4, "verification_criteria": "Write a C/Python script to inspect and print the memory addresses of stack, heap, and text variables in real time.", "subtopics": ["4.1.1 The 64-bit virtual memory address space: user space (lower addresses) vs kernel space (upper canonical addresses).", "4.1.2 Segment breakdown: Text (.text), Initialized Data (.data), Uninitialized Data (.bss), Heap, Memory Mapping, Stack.", "4.1.3 Address Space Layout Randomization (ASLR): randomizing base addresses to prevent buffer overflow exploits.", "4.1.4 Inspecting process memory maps via `/proc/<pid>/maps` and runtime segment boundaries."]}'::jsonb, '["Explain how this implementation prevents: Assuming fixed memory addresses across program executions, broken by ASLR security mitigations.", "How does Process Address Space: Segments & Memory Layout scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-2', 'phase-04-lesson-02-multi-level-page-tables-page-directory-po', 'module-6', 2, 'Lesson 6.2: Multi-Level Page Tables & Page Directory Pointers', 'Prerequisites: Lesson 4.1', 'Prerequisites: Lesson 4.1 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 100.0, '# Lesson 4.2: Multi-Level Page Tables & Page Directory Pointers

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.1
- **Subtopics**:
  - `4.2.1` 4-level paging in x86-64: Page Map Level 4 (PML4), Page Directory Pointer Table (PDPT), Page Directory (PD), Page Table (PT).
  - `4.2.2` Virtual Address Bit Breakdown: 9 bits per level ($4 	imes 9 = 36$ bits) + 12-bit page offset ($2^{12} = 4096$ bytes).
  - `4.2.3` Page Table Entries (PTE): Present bit, Read/Write bit, User/Supervisor bit, Accessed/Dirty bits, No-Execute (NX) bit.
  - `4.2.4` 5-level paging (PML5): extending virtual address space to 57 bits (128 petabytes) in modern enterprise datacenters.
- **Key Failure Modes & Edge Cases**: Paging memory overhead: allocating millions of tiny sparse mappings causing excessive page table memory consumption.
- **Verification & Mastery Check**: Calculate the physical memory required to store the page table for a process mapping 10GB of fragmented RAM.
- **Project Application**: Systems foundation for OS memory understanding.', '{"solution.py": "# Phase 4 // Lesson 4.2: Multi-Level Page Tables & Page Directory Pointers\n\ndef solve():\n    \"\"\"\n    Verification: Calculate the physical memory required to store the page table for a process mapping 10GB of fragmen\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.2", "subtopics_count": 4, "verification_criteria": "Calculate the physical memory required to store the page table for a process mapping 10GB of fragmented RAM.", "subtopics": ["4.2.1 4-level paging in x86-64: Page Map Level 4 (PML4), Page Directory Pointer Table (PDPT), Page Directory (PD), Page Table (PT).", "4.2.2 Virtual Address Bit Breakdown: 9 bits per level ($4 \times 9 = 36$ bits) + 12-bit page offset ($2^{12} = 4096$ bytes).", "4.2.3 Page Table Entries (PTE): Present bit, Read/Write bit, User/Supervisor bit, Accessed/Dirty bits, No-Execute (NX) bit.", "4.2.4 5-level paging (PML5): extending virtual address space to 57 bits (128 petabytes) in modern enterprise datacenters."]}'::jsonb, '["Explain how this implementation prevents: Paging memory overhead: allocating millions of tiny sparse mappings causing excessive page table memory consumption.", "How does Multi-Level Page Tables & Page Directory Pointers scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-3', 'phase-04-lesson-03-translation-lookaside-buffer-tlb-hardware', 'module-6', 3, 'Lesson 6.3: Translation Lookaside Buffer (TLB) & Hardware Walkers', 'Prerequisites: Lesson 4.2', 'Prerequisites: Lesson 4.2 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 150.0, '# Lesson 4.3: Translation Lookaside Buffer (TLB) & Hardware Walkers

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.2
- **Subtopics**:
  - `4.3.1` TLB hardware cache: associative lookups converting virtual page numbers to physical frame numbers in $<1$ clock cycle.
  - `4.3.2` TLB Miss penalty: hardware page table walker traversing physical RAM across 4 memory references.
  - `4.3.3` TLB Shootdowns: multi-core cache coherency inter-processor interrupts (IPI) invalidating TLB entries across cores.
  - `4.3.4` HugePages (2MB, 1GB): reducing TLB misses by covering $512	imes$ to $262,144	imes$ more memory per TLB entry.
- **Key Failure Modes & Edge Cases**: Severe multi-threaded latency spikes caused by frequent TLB shootdowns during active memory re-mapping.
- **Verification & Mastery Check**: Configure Linux Transparent HugePages (THP) and benchmark memory access latency on a 10GB array.
- **Project Application**: High-performance memory tuning for vector search in Phase 10.', '{"solution.py": "# Phase 4 // Lesson 4.3: Translation Lookaside Buffer (TLB) & Hardware Walkers\n\ndef solve():\n    \"\"\"\n    Verification: Configure Linux Transparent HugePages (THP) and benchmark memory access latency on a 10GB array.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.3", "subtopics_count": 4, "verification_criteria": "Configure Linux Transparent HugePages (THP) and benchmark memory access latency on a 10GB array.", "subtopics": ["4.3.1 TLB hardware cache: associative lookups converting virtual page numbers to physical frame numbers in $<1$ clock cycle.", "4.3.2 TLB Miss penalty: hardware page table walker traversing physical RAM across 4 memory references.", "4.3.3 TLB Shootdowns: multi-core cache coherency inter-processor interrupts (IPI) invalidating TLB entries across cores.", "4.3.4 HugePages (2MB, 1GB): reducing TLB misses by covering $512\times$ to $262,144\times$ more memory per TLB entry."]}'::jsonb, '["Explain how this implementation prevents: Severe multi-threaded latency spikes caused by frequent TLB shootdowns during active memory re-mapping.", "How does Translation Lookaside Buffer (TLB) & Hardware Walkers scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-4', 'phase-04-lesson-04-zero-copy-i-o-memory-mapped-files-with-mm', 'module-6', 4, 'Lesson 6.4: Zero-Copy I/O & Memory-Mapped Files with `mmap`', 'Prerequisites: Lesson 4.1', 'Prerequisites: Lesson 4.1 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 200.0, '# Lesson 4.4: Zero-Copy I/O & Memory-Mapped Files with `mmap`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.1
- **Subtopics**:
  - `4.4.1` Traditional file I/O overhead: disk $	o$ kernel page cache $	o$ user space buffer (`read`) $	o$ socket buffer (`write`).
  - `4.4.2` `mmap()` zero-copy architecture: mapping disk blocks directly into the process virtual address space.
  - `4.4.3` Memory protection flags: `PROT_READ`, `PROT_WRITE`, `PROT_EXEC`; sharing modes: `MAP_SHARED` vs `MAP_PRIVATE` (COW).
  - `4.4.4` Kernel zero-copy syscalls: `sendfile()` transferring bytes directly from page cache to socket descriptor.
- **Key Failure Modes & Edge Cases**: Triggering `SIGBUS` crashes when reading from an `mmap` region after another process truncates the underlying file.
- **Verification & Mastery Check**: Implement a static file server using `sendfile()` and `mmap()` that serves multi-gigabyte files with zero user-space copying.
- **Project Application**: NanoHTTP: Static file serving engine.', '{"solution.py": "# Phase 4 // Lesson 4.4: Zero-Copy I/O & Memory-Mapped Files with `mmap`\n\ndef solve():\n    \"\"\"\n    Verification: Implement a static file server using `sendfile()` and `mmap()` that serves multi-gigabyte files with\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.4", "subtopics_count": 4, "verification_criteria": "Implement a static file server using `sendfile()` and `mmap()` that serves multi-gigabyte files with zero user-space copying.", "subtopics": ["4.4.1 Traditional file I/O overhead: disk $\to$ kernel page cache $\to$ user space buffer (`read`) $\to$ socket buffer (`write`).", "4.4.2 `mmap()` zero-copy architecture: mapping disk blocks directly into the process virtual address space.", "4.4.3 Memory protection flags: `PROT_READ`, `PROT_WRITE`, `PROT_EXEC`; sharing modes: `MAP_SHARED` vs `MAP_PRIVATE` (COW).", "4.4.4 Kernel zero-copy syscalls: `sendfile()` transferring bytes directly from page cache to socket descriptor."]}'::jsonb, '["Explain how this implementation prevents: Triggering `SIGBUS` crashes when reading from an `mmap` region after another process truncates the underlying file.", "How does Zero-Copy I/O & Memory-Mapped Files with `mmap` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-5', 'phase-04-lesson-05-the-linux-out-of-memory-oom-killer-memory', 'module-6', 5, 'Lesson 6.5: The Linux Out-Of-Memory (OOM) Killer & Memory Cgroups', 'Prerequisites: Lesson 4.1', 'Prerequisites: Lesson 4.1 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 250.0, '# Lesson 4.5: The Linux Out-Of-Memory (OOM) Killer & Memory Cgroups

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.1
- **Subtopics**:
  - `4.5.1` Memory overcommit (`vm.overcommit_memory`): why Linux permits allocating more virtual memory than physical RAM exists.
  - `4.5.2` The OOM Killer invocation: kernel heuristics evaluating `oom_score` and `oom_score_adj` (-1000 to +1000).
  - `4.5.3` Control Groups (cgroups v2) Memory limits: `memory.max`, `memory.high`, and container OOM termination (`OOMKilled: 137`).
  - `4.5.4` Swap space dynamics: page swapping mechanics, swappiness tuning (`vm.swappiness`), and swap thrashing.
- **Key Failure Modes & Edge Cases**: Production container terminations with exit code 137 caused by exceeding cgroup `memory.max` limits without metrics visibility.
- **Verification & Mastery Check**: Simulate an OOM condition inside a constrained cgroup and analyze the kernel dmesg OOM kill log.
- **Project Application**: Docker container memory limit configuration in Phase 4 and Phase 7.', '{"solution.py": "# Phase 4 // Lesson 4.5: The Linux Out-Of-Memory (OOM) Killer & Memory Cgroups\n\ndef solve():\n    \"\"\"\n    Verification: Simulate an OOM condition inside a constrained cgroup and analyze the kernel dmesg OOM kill log.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.5", "subtopics_count": 4, "verification_criteria": "Simulate an OOM condition inside a constrained cgroup and analyze the kernel dmesg OOM kill log.", "subtopics": ["4.5.1 Memory overcommit (`vm.overcommit_memory`): why Linux permits allocating more virtual memory than physical RAM exists.", "4.5.2 The OOM Killer invocation: kernel heuristics evaluating `oom_score` and `oom_score_adj` (-1000 to +1000).", "4.5.3 Control Groups (cgroups v2) Memory limits: `memory.max`, `memory.high`, and container OOM termination (`OOMKilled: 137`).", "4.5.4 Swap space dynamics: page swapping mechanics, swappiness tuning (`vm.swappiness`), and swap thrashing."]}'::jsonb, '["Explain how this implementation prevents: Production container terminations with exit code 137 caused by exceeding cgroup `memory.max` limits without metrics visi", "How does The Linux Out-Of-Memory (OOM) Killer & Memory Cgroups scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
