INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-4-6', 'phase-04-lesson-06-process-forking-copy-on-write-cow-execve', 'module-6', 6, 'Lesson 6.6: Process Forking, Copy-On-Write (COW), & `execve`', 'Prerequisites: Phase 0 (Lesson 0.21)', 'Prerequisites: Phase 0 (Lesson 0.21) | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 300.0, '# Lesson 4.6: Process Forking, Copy-On-Write (COW), & `execve`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.21)
- **Subtopics**:
  - `4.6.1` The `fork()` system call: duplicating process address space, file descriptors, and signal masks.
  - `4.6.2` Copy-On-Write (COW) mechanics: sharing identical physical pages marked read-only until a process writes to a page.
  - `4.6.3` The `execve()` system call: clearing virtual address space, loading new ELF binary, initializing new stack and heap.
  - `4.6.4` The `posix_spawn()` optimized interface: avoiding memory table duplication overhead on modern Linux.
- **Key Failure Modes & Edge Cases**: Redis background save (`BGSAVE`) memory spikes: COW dirty page copies exhausting RAM when writes are heavy during saves.
- **Verification & Mastery Check**: Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW in action.
- **Project Application**: NanoHTTP and systems tooling.', '{"solution.py": "# Phase 4 // Lesson 4.6: Process Forking, Copy-On-Write (COW), & `execve`\n\ndef solve():\n    \"\"\"\n    Verification: Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.6", "subtopics_count": 4, "verification_criteria": "Measure physical RAM usage before and after `fork()` with varying write workloads to demonstrate COW in action.", "subtopics": ["4.6.1 The `fork()` system call: duplicating process address space, file descriptors, and signal masks.", "4.6.2 Copy-On-Write (COW) mechanics: sharing identical physical pages marked read-only until a process writes to a page.", "4.6.3 The `execve()` system call: clearing virtual address space, loading new ELF binary, initializing new stack and heap.", "4.6.4 The `posix_spawn()` optimized interface: avoiding memory table duplication overhead on modern Linux."]}'::jsonb, '["Explain how this implementation prevents: Redis background save (`BGSAVE`) memory spikes: COW dirty page copies exhausting RAM when writes are heavy during saves.", "How does Process Forking, Copy-On-Write (COW), & `execve` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-7', 'phase-04-lesson-07-inter-process-communication-pipes-named-f', 'module-6', 7, 'Lesson 6.7: Inter-Process Communication: Pipes & Named FIFOs', 'Prerequisites: Phase 0 (Lesson 0.24)', 'Prerequisites: Phase 0 (Lesson 0.24) | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 350.0, '# Lesson 4.7: Inter-Process Communication: Pipes & Named FIFOs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.24)
- **Subtopics**:
  - `4.7.1` Anonymous pipes (`pipe()`): unidirectional kernel ring buffer (64KB default capacity).
  - `4.7.2` Blocking behavior: `write()` blocks when pipe buffer is full; `read()` blocks when pipe buffer is empty.
  - `4.7.3` Broken pipe signal: `SIGPIPE` generated when writing to a pipe with zero active read file descriptors.
  - `4.7.4` Named pipes (`mkfifo()`): filesystem entries enabling IPC between unrelated processes without parent-child ancestry.
- **Key Failure Modes & Edge Cases**: Crashing on unhandled `SIGPIPE` when downstream readers close connections abruptly while writer continues writing.
- **Verification & Mastery Check**: Implement a bidirectional IPC communication channel between two processes using a pair of named FIFOs.
- **Project Application**: SysTrace and systems IPC.', '{"solution.py": "# Phase 4 // Lesson 4.7: Inter-Process Communication: Pipes & Named FIFOs\n\ndef solve():\n    \"\"\"\n    Verification: Implement a bidirectional IPC communication channel between two processes using a pair of named FIFO\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.7", "subtopics_count": 4, "verification_criteria": "Implement a bidirectional IPC communication channel between two processes using a pair of named FIFOs.", "subtopics": ["4.7.1 Anonymous pipes (`pipe()`): unidirectional kernel ring buffer (64KB default capacity).", "4.7.2 Blocking behavior: `write()` blocks when pipe buffer is full; `read()` blocks when pipe buffer is empty.", "4.7.3 Broken pipe signal: `SIGPIPE` generated when writing to a pipe with zero active read file descriptors.", "4.7.4 Named pipes (`mkfifo()`): filesystem entries enabling IPC between unrelated processes without parent-child ancestry."]}'::jsonb, '["Explain how this implementation prevents: Crashing on unhandled `SIGPIPE` when downstream readers close connections abruptly while writer continues writing.", "How does Inter-Process Communication: Pipes & Named FIFOs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-8', 'phase-04-lesson-08-unix-domain-sockets-passing-file-descript', 'module-6', 8, 'Lesson 6.8: Unix Domain Sockets & Passing File Descriptors', 'Prerequisites: Lesson 4.7', 'Prerequisites: Lesson 4.7 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 400.0, '# Lesson 4.8: Unix Domain Sockets & Passing File Descriptors

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.7
- **Subtopics**:
  - `4.8.1` Unix Domain Sockets (`AF_UNIX`): bidirectional local IPC bypassing network stack, checksums, and TCP headers.
  - `4.8.2` Stream (`SOCK_STREAM`) vs Datagram (`SOCK_DGRAM`) Unix sockets; filesystem socket nodes.
  - `4.8.3` Passing Open File Descriptors: utilizing `sendmsg()` and `recvmsg()` with `SCM_RIGHTS` ancillary control messages.
  - `4.8.4` Why UDS outperforms loopback TCP (`127.0.0.1`): 2x throughput, lower latency, filesystem permission security.
- **Key Failure Modes & Edge Cases**: Dangling socket files on filesystem after unclean process termination preventing service restarts.
- **Verification & Mastery Check**: Build a parent process that opens a TCP socket and passes the active file descriptor to a child worker via UDS.
- **Project Application**: PgBouncer local connections in Phase 5.', '{"solution.py": "# Phase 4 // Lesson 4.8: Unix Domain Sockets & Passing File Descriptors\n\ndef solve():\n    \"\"\"\n    Verification: Build a parent process that opens a TCP socket and passes the active file descriptor to a child work\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.8", "subtopics_count": 4, "verification_criteria": "Build a parent process that opens a TCP socket and passes the active file descriptor to a child worker via UDS.", "subtopics": ["4.8.1 Unix Domain Sockets (`AF_UNIX`): bidirectional local IPC bypassing network stack, checksums, and TCP headers.", "4.8.2 Stream (`SOCK_STREAM`) vs Datagram (`SOCK_DGRAM`) Unix sockets; filesystem socket nodes.", "4.8.3 Passing Open File Descriptors: utilizing `sendmsg()` and `recvmsg()` with `SCM_RIGHTS` ancillary control messages.", "4.8.4 Why UDS outperforms loopback TCP (`127.0.0.1`): 2x throughput, lower latency, filesystem permission security."]}'::jsonb, '["Explain how this implementation prevents: Dangling socket files on filesystem after unclean process termination preventing service restarts.", "How does Unix Domain Sockets & Passing File Descriptors scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-9', 'phase-04-lesson-09-posix-signals-asynchronous-interruption-r', 'module-6', 9, 'Lesson 6.9: POSIX Signals: Asynchronous Interruption & Re-entrancy', 'Prerequisites: Phase 0 (Lesson 0.25)', 'Prerequisites: Phase 0 (Lesson 0.25) | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 450.0, '# Lesson 4.9: POSIX Signals: Asynchronous Interruption & Re-entrancy

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.25)
- **Subtopics**:
  - `4.9.1` Signal delivery mechanics: kernel interrupting user-space instruction stream and executing registered signal handler.
  - `4.9.2` Signal masks: blocking and unblocking signals via `sigprocmask()` during critical sections.
  - `4.9.3` Signal Re-entrancy: why calling non-reentrant functions (`printf`, `malloc`, `free`) inside signal handlers causes deadlocks.
  - `4.9.4` Async-signal-safe functions list: POSIX standard guarantees; setting `sig_atomic_t` or `volatile` flags.
- **Key Failure Modes & Edge Cases**: Deadlocks in production signal handlers caused by attempting to acquire a mutex or allocate memory inside the handler.
- **Verification & Mastery Check**: Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self-pipe trick.
- **Project Application**: NanoHTTP: Graceful shutdown signal engine.', '{"solution.py": "# Phase 4 // Lesson 4.9: POSIX Signals: Asynchronous Interruption & Re-entrancy\n\ndef solve():\n    \"\"\"\n    Verification: Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.9", "subtopics_count": 4, "verification_criteria": "Write a signal handler that safely coordinates graceful shutdown using `sig_atomic_t` flags and self-pipe trick.", "subtopics": ["4.9.1 Signal delivery mechanics: kernel interrupting user-space instruction stream and executing registered signal handler.", "4.9.2 Signal masks: blocking and unblocking signals via `sigprocmask()` during critical sections.", "4.9.3 Signal Re-entrancy: why calling non-reentrant functions (`printf`, `malloc`, `free`) inside signal handlers causes deadlocks.", "4.9.4 Async-signal-safe functions list: POSIX standard guarantees; setting `sig_atomic_t` or `volatile` flags."]}'::jsonb, '["Explain how this implementation prevents: Deadlocks in production signal handlers caused by attempting to acquire a mutex or allocate memory inside the handler.", "How does POSIX Signals: Asynchronous Interruption & Re-entrancy scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-10', 'phase-04-lesson-10-zombie-processes-orphan-reaping-waitpid', 'module-6', 10, 'Lesson 6.10: Zombie Processes, Orphan Reaping, & `waitpid`', 'Prerequisites: Lesson 4.6', 'Prerequisites: Lesson 4.6 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 500.0, '# Lesson 4.10: Zombie Processes, Orphan Reaping, & `waitpid`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.6
- **Subtopics**:
  - `4.10.1` Process termination lifecycle: child process exits, becomes Zombie (`Z` state), retains exit status in PCB.
  - `4.10.2` Reaping zombies: parent calling `wait()` or `waitpid()` to read child exit status and release kernel PCB memory.
  - `4.10.3` Orphan processes: parent terminating before child; child adopted by init process (PID 1 / systemd).
  - `4.10.4` Subreaper processes: using `prctl(PR_SET_CHILD_SUBREAPER)` in process managers to reap orphaned descendant trees.
- **Key Failure Modes & Edge Cases**: Zombie accumulation exhausting kernel PID limits in container environments where PID 1 fails to reap children.
- **Verification & Mastery Check**: Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated workers immediately.
- **Project Application**: Container process management in Phase 4 and Phase 7.', '{"solution.py": "# Phase 4 // Lesson 4.10: Zombie Processes, Orphan Reaping, & `waitpid`\n\ndef solve():\n    \"\"\"\n    Verification: Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated wor\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.10", "subtopics_count": 4, "verification_criteria": "Write a process supervisor that spawns worker processes, handles `SIGCHLD`, and reaps terminated workers immediately.", "subtopics": ["4.10.1 Process termination lifecycle: child process exits, becomes Zombie (`Z` state), retains exit status in PCB.", "4.10.2 Reaping zombies: parent calling `wait()` or `waitpid()` to read child exit status and release kernel PCB memory.", "4.10.3 Orphan processes: parent terminating before child; child adopted by init process (PID 1 / systemd).", "4.10.4 Subreaper processes: using `prctl(PR_SET_CHILD_SUBREAPER)` in process managers to reap orphaned descendant trees."]}'::jsonb, '["Explain how this implementation prevents: Zombie accumulation exhausting kernel PID limits in container environments where PID 1 fails to reap children.", "How does Zombie Processes, Orphan Reaping, & `waitpid` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-11', 'phase-04-lesson-11-kernel-threads-vs-user-space-green-thread', 'module-6', 11, 'Lesson 6.11: Kernel Threads vs User-Space Green Threads', 'Prerequisites: Phase 1 (Lesson 1.31)', 'Prerequisites: Phase 1 (Lesson 1.31) | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 550.0, '# Lesson 4.11: Kernel Threads vs User-Space Green Threads

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.31)
- **Subtopics**:
  - `4.11.1` 1:1 Threading Model: each application thread maps directly to a Linux kernel thread (NPTL - Native POSIX Thread Library).
  - `4.11.2` M:N Threading Model: $M$ user-space green threads multiplexed over $N$ OS threads (Go goroutines, Erlang actors).
  - `4.11.3` Context-switch cost: saving CPU registers, flushing pipeline, kernel transition overhead (~1–2 microseconds).
  - `4.11.4` Thread stack allocation: 8MB default stack vs customizable thread stack sizes (`pthread_attr_setstacksize`).
- **Key Failure Modes & Edge Cases**: Spawning 10,000 OS threads simultaneously, exhausting virtual memory and collapsing system under context switching.
- **Verification & Mastery Check**: Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 coroutines.
- **Project Application**: NanoHTTP: Version 1 (Multi-Threaded Server).', '{"solution.py": "# Phase 4 // Lesson 4.11: Kernel Threads vs User-Space Green Threads\n\ndef solve():\n    \"\"\"\n    Verification: Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 corout\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.11", "subtopics_count": 4, "verification_criteria": "Measure and compare the memory usage and creation latency of 1,000 native OS threads vs 1,000 coroutines.", "subtopics": ["4.11.1 1:1 Threading Model: each application thread maps directly to a Linux kernel thread (NPTL - Native POSIX Thread Library).", "4.11.2 M:N Threading Model: $M$ user-space green threads multiplexed over $N$ OS threads (Go goroutines, Erlang actors).", "4.11.3 Context-switch cost: saving CPU registers, flushing pipeline, kernel transition overhead (~1\u20132 microseconds).", "4.11.4 Thread stack allocation: 8MB default stack vs customizable thread stack sizes (`pthread_attr_setstacksize`)."]}'::jsonb, '["Explain how this implementation prevents: Spawning 10,000 OS threads simultaneously, exhausting virtual memory and collapsing system under context switching.", "How does Kernel Threads vs User-Space Green Threads scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-12', 'phase-04-lesson-12-race-conditions-critical-sections-mutual-', 'module-6', 12, 'Lesson 6.12: Race Conditions, Critical Sections, & Mutual Exclusion', 'Prerequisites: Lesson 4.11', 'Prerequisites: Lesson 4.11 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 600.0, '# Lesson 4.12: Race Conditions, Critical Sections, & Mutual Exclusion

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.11
- **Subtopics**:
  - `4.12.1` Race conditions defined: output non-deterministically dependent on relative execution timing of concurrent threads.
  - `4.12.2` Critical Section: code block accessing shared mutable state that must execute atomically.
  - `4.12.3` Mutual Exclusion (Mutex): binary lock ensuring at most one thread executes inside the critical section.
  - `4.12.4` Mutex performance: futex (Fast Userspace Mutex) in Linux — avoiding syscalls on uncontended lock acquisitions.
- **Key Failure Modes & Edge Cases**: Data corruption in concurrent bank account balances caused by unprotected read-modify-write operations.
- **Verification & Mastery Check**: Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it using a Mutex.
- **Project Application**: NanoHTTP: Shared connection metrics.', '{"solution.py": "# Phase 4 // Lesson 4.12: Race Conditions, Critical Sections, & Mutual Exclusion\n\ndef solve():\n    \"\"\"\n    Verification: Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.12", "subtopics_count": 4, "verification_criteria": "Demonstrate a multi-threaded integer counter race condition in Python/C, verify failure, and fix it using a Mutex.", "subtopics": ["4.12.1 Race conditions defined: output non-deterministically dependent on relative execution timing of concurrent threads.", "4.12.2 Critical Section: code block accessing shared mutable state that must execute atomically.", "4.12.3 Mutual Exclusion (Mutex): binary lock ensuring at most one thread executes inside the critical section.", "4.12.4 Mutex performance: futex (Fast Userspace Mutex) in Linux \u2014 avoiding syscalls on uncontended lock acquisitions."]}'::jsonb, '["Explain how this implementation prevents: Data corruption in concurrent bank account balances caused by unprotected read-modify-write operations.", "How does Race Conditions, Critical Sections, & Mutual Exclusion scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-13', 'phase-04-lesson-13-deadlocks-coffman-conditions-lock-orderin', 'module-6', 13, 'Lesson 6.13: Deadlocks, Coffman Conditions, & Lock Ordering', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1060.0, 650.0, '# Lesson 4.13: Deadlocks, Coffman Conditions, & Lock Ordering

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.13.1` Deadlock definition: two or more threads permanently blocked, each waiting for a lock held by the other.
  - `4.13.2` The Four Coffman Conditions: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait.
  - `4.13.3` Deadlock prevention via strict Lock Ordering: establishing a global lock hierarchy (always acquire Lock A before Lock B).
  - `4.13.4` Deadlock detection: resource allocation graphs and cycle detection; lock acquisition timeouts (`try_lock`).
- **Key Failure Modes & Edge Cases**: Intermittent production deadlocks occurring when two background jobs acquire database table locks in reverse order.
- **Verification & Mastery Check**: Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using strict lock hierarchies.
- **Project Application**: Database transaction concurrency in Phase 5.', '{"solution.py": "# Phase 4 // Lesson 4.13: Deadlocks, Coffman Conditions, & Lock Ordering\n\ndef solve():\n    \"\"\"\n    Verification: Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using st\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.13", "subtopics_count": 4, "verification_criteria": "Write a multi-threaded program that reliably deadlocks, trace it with `gdb`, and resolve it using strict lock hierarchies.", "subtopics": ["4.13.1 Deadlock definition: two or more threads permanently blocked, each waiting for a lock held by the other.", "4.13.2 The Four Coffman Conditions: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait.", "4.13.3 Deadlock prevention via strict Lock Ordering: establishing a global lock hierarchy (always acquire Lock A before Lock B).", "4.13.4 Deadlock detection: resource allocation graphs and cycle detection; lock acquisition timeouts (`try_lock`)."]}'::jsonb, '["Explain how this implementation prevents: Intermittent production deadlocks occurring when two background jobs acquire database table locks in reverse order.", "How does Deadlocks, Coffman Conditions, & Lock Ordering scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-14', 'phase-04-lesson-14-condition-variables-thread-signaling', 'module-6', 14, 'Lesson 6.14: Condition Variables & Thread Signaling', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1120.0, 700.0, '# Lesson 4.14: Condition Variables & Thread Signaling

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.14.1` The need for Condition Variables: waiting for a state condition to become true without busy-waiting (spinning).
  - `4.14.2` Condition Variable primitives: `wait(mutex)` (atomically releases mutex and sleeps), `signal()` / `notify()`, `broadcast()`.
  - `4.14.3` Spurious Wakeups: why condition variables must ALWAYS be checked inside a `while (!condition)` loop.
  - `4.14.4` Lost Wakeups: signaling a condition variable before a waiting thread has entered the wait state.
- **Key Failure Modes & Edge Cases**: Using an `if` statement instead of `while` with condition variables, causing data corruption on spurious wakeups.
- **Verification & Mastery Check**: Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`, `not_empty`).
- **Project Application**: NanoHTTP: Thread pool task queue.', '{"solution.py": "# Phase 4 // Lesson 4.14: Condition Variables & Thread Signaling\n\ndef solve():\n    \"\"\"\n    Verification: Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.14", "subtopics_count": 4, "verification_criteria": "Implement a thread-safe Bounded Blocking Queue using a mutex and two condition variables (`not_full`, `not_empty`).", "subtopics": ["4.14.1 The need for Condition Variables: waiting for a state condition to become true without busy-waiting (spinning).", "4.14.2 Condition Variable primitives: `wait(mutex)` (atomically releases mutex and sleeps), `signal()` / `notify()`, `broadcast()`.", "4.14.3 Spurious Wakeups: why condition variables must ALWAYS be checked inside a `while (!condition)` loop.", "4.14.4 Lost Wakeups: signaling a condition variable before a waiting thread has entered the wait state."]}'::jsonb, '["Explain how this implementation prevents: Using an `if` statement instead of `while` with condition variables, causing data corruption on spurious wakeups.", "How does Condition Variables & Thread Signaling scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-4-15', 'phase-04-lesson-15-read-write-locks-reader-writer-priority-d', 'module-6', 15, 'Lesson 6.15: Read-Write Locks & Reader-Writer Priority Dilemmas', 'Prerequisites: Lesson 4.12', 'Prerequisites: Lesson 4.12 | Subtopics: 4 items', 'Systems project application', 180, 5, 1000.0, 750.0, '# Lesson 4.15: Read-Write Locks & Reader-Writer Priority Dilemmas

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 4.12
- **Subtopics**:
  - `4.15.1` Shared-Exclusive Locking (Read-Write Lock / `rwlock`): multiple concurrent readers OR single exclusive writer.
  - `4.15.2` Reader-Preference locks: allows continuous readers; risks Writer Starvation under heavy read traffic.
  - `4.15.3` Writer-Preference locks: incoming readers wait once a writer requests the lock; prevents writer starvation.
  - `4.15.4` Fair Read-Write locks: FIFO ordering of readers and writers.
- **Key Failure Modes & Edge Cases**: Writer starvation in read-heavy caches where writers are permanently blocked from updating expired cache keys.
- **Verification & Mastery Check**: Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read throughput vs standard mutex.
- **Project Application**: CacheKit: Multi-threaded cache design.', '{"solution.py": "# Phase 4 // Lesson 4.15: Read-Write Locks & Reader-Writer Priority Dilemmas\n\ndef solve():\n    \"\"\"\n    Verification: Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read thro\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "4.15", "subtopics_count": 4, "verification_criteria": "Implement an in-memory thread-safe key-value cache using reader-writer locks and benchmark read throughput vs standard mutex.", "subtopics": ["4.15.1 Shared-Exclusive Locking (Read-Write Lock / `rwlock`): multiple concurrent readers OR single exclusive writer.", "4.15.2 Reader-Preference locks: allows continuous readers; risks Writer Starvation under heavy read traffic.", "4.15.3 Writer-Preference locks: incoming readers wait once a writer requests the lock; prevents writer starvation.", "4.15.4 Fair Read-Write locks: FIFO ordering of readers and writers."]}'::jsonb, '["Explain how this implementation prevents: Writer starvation in read-heavy caches where writers are permanently blocked from updating expired cache keys.", "How does Read-Write Locks & Reader-Writer Priority Dilemmas scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
