INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-3-21', 'phase-03-lesson-21-queue-applications-sliding-window-buffers', 'module-5', 21, 'Lesson 5.21: Queue Applications: Sliding Window Buffers', 'Prerequisites: Lesson 3.7, Lesson 3.16', 'Prerequisites: Lesson 3.7, Lesson 3.16 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1050.0, '# Lesson 3.21: Queue Applications: Sliding Window Buffers

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.7, Lesson 3.16
- **Subtopics**:
  - `3.21.1` The Queue FIFO principle (First In, First Out): adding to the back, removing from the front.
  - `3.21.2` Circular ring buffers: fixed-capacity queues that overwrite the oldest item when full.
  - `3.21.3` Producer-Consumer pattern: decoupling data producers from slower data processors via a queue.
  - `3.21.4` Queue thread safety preview: preventing data corruption when multiple workers access a queue.
- **Key Failure Modes & Edge Cases**: Allowing an unbounded queue to grow indefinitely under high input traffic, exhausting server RAM.
- **Verification & Mastery Check**: Build a CircularBuffer class of fixed capacity 5 that safely records the most recent 5 events in order.
- **Project Application**: StreamBuffer: Fixed-memory stream buffer.', '{"solution.py": "# Phase 3 // Lesson 3.21: Queue Applications: Sliding Window Buffers\n\ndef solve():\n    \"\"\"\n    Verification: Build a CircularBuffer class of fixed capacity 5 that safely records the most recent 5 events in ord\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.21", "subtopics_count": 4, "verification_criteria": "Build a CircularBuffer class of fixed capacity 5 that safely records the most recent 5 events in order.", "subtopics": ["3.21.1 The Queue FIFO principle (First In, First Out): adding to the back, removing from the front.", "3.21.2 Circular ring buffers: fixed-capacity queues that overwrite the oldest item when full.", "3.21.3 Producer-Consumer pattern: decoupling data producers from slower data processors via a queue.", "3.21.4 Queue thread safety preview: preventing data corruption when multiple workers access a queue."]}'::jsonb, '["Explain how this implementation prevents: Allowing an unbounded queue to grow indefinitely under high input traffic, exhausting server RAM.", "How does Queue Applications: Sliding Window Buffers scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-22', 'phase-03-lesson-22-heap-priority-queue-finding-top-k-element', 'module-5', 22, 'Lesson 5.22: Heap / Priority Queue: Finding Top-K Elements', 'Prerequisites: Lesson 3.2', 'Prerequisites: Lesson 3.2 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1100.0, '# Lesson 3.22: Heap / Priority Queue: Finding Top-K Elements

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.2
- **Subtopics**:
  - `3.22.1` Priority Queues: retrieving the highest (or lowest) priority item in O(log N) time.
  - `3.22.2` Binary Heaps: min-heaps (parent <= children) vs max-heaps (parent >= children).
  - `3.22.3` The heapq module in Python: heappush(), heappop(), and nlargest().
  - `3.22.4` The Top-K pattern: finding the K largest elements in a stream of N items using a min-heap of size K in O(N log K).
- **Key Failure Modes & Edge Cases**: Sorting the entire N-element list (O(N log N)) just to find the top 5 elements, wasting CPU time.
- **Verification & Mastery Check**: Find the 10 highest-scoring documents from an endless stream of 1,000,000 search results using a min-heap.
- **Project Application**: StreamBuffer: Real-time top-K scoring buffer.', '{"solution.py": "# Phase 3 // Lesson 3.22: Heap / Priority Queue: Finding Top-K Elements\n\ndef solve():\n    \"\"\"\n    Verification: Find the 10 highest-scoring documents from an endless stream of 1,000,000 search results using a min\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.22", "subtopics_count": 4, "verification_criteria": "Find the 10 highest-scoring documents from an endless stream of 1,000,000 search results using a min-heap.", "subtopics": ["3.22.1 Priority Queues: retrieving the highest (or lowest) priority item in O(log N) time.", "3.22.2 Binary Heaps: min-heaps (parent <= children) vs max-heaps (parent >= children).", "3.22.3 The heapq module in Python: heappush(), heappop(), and nlargest().", "3.22.4 The Top-K pattern: finding the K largest elements in a stream of N items using a min-heap of size K in O(N log K)."]}'::jsonb, '["Explain how this implementation prevents: Sorting the entire N-element list (O(N log N)) just to find the top 5 elements, wasting CPU time.", "How does Heap / Priority Queue: Finding Top-K Elements scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-23', 'phase-03-lesson-23-greedy-algorithms-interval-scheduling', 'module-5', 23, 'Lesson 5.23: Greedy Algorithms: Interval Scheduling', 'Prerequisites: Lesson 3.2', 'Prerequisites: Lesson 3.2 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1150.0, '# Lesson 3.23: Greedy Algorithms: Interval Scheduling

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.2
- **Subtopics**:
  - `3.23.1` The Greedy choice property: making the locally optimal decision at each step to find a global optimum.
  - `3.23.2` When greedy works vs when it fails: why greedy fails for the 0/1 knapsack problem but works for intervals.
  - `3.23.3` Interval scheduling: maximizing the number of non-overlapping meetings in a conference room.
  - `3.23.4` The optimal greedy strategy: sorting intervals by their earliest end times.
- **Key Failure Modes & Edge Cases**: Sorting intervals by start time instead of end time, which fails to maximize scheduled meetings.
- **Verification & Mastery Check**: Given a list of start and end times for tasks, compute the maximum number of non-overlapping tasks you can run.
- **Project Application**: StreamBuffer: Task schedule optimizer.', '{"solution.py": "# Phase 3 // Lesson 3.23: Greedy Algorithms: Interval Scheduling\n\ndef solve():\n    \"\"\"\n    Verification: Given a list of start and end times for tasks, compute the maximum number of non-overlapping tasks y\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.23", "subtopics_count": 4, "verification_criteria": "Given a list of start and end times for tasks, compute the maximum number of non-overlapping tasks you can run.", "subtopics": ["3.23.1 The Greedy choice property: making the locally optimal decision at each step to find a global optimum.", "3.23.2 When greedy works vs when it fails: why greedy fails for the 0/1 knapsack problem but works for intervals.", "3.23.3 Interval scheduling: maximizing the number of non-overlapping meetings in a conference room.", "3.23.4 The optimal greedy strategy: sorting intervals by their earliest end times."]}'::jsonb, '["Explain how this implementation prevents: Sorting intervals by start time instead of end time, which fails to maximize scheduled meetings.", "How does Greedy Algorithms: Interval Scheduling scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-24', 'phase-03-lesson-24-backtracking-generating-subsets-combinati', 'module-5', 24, 'Lesson 5.24: Backtracking: Generating Subsets & Combinations', 'Prerequisites: Lesson 3.14', 'Prerequisites: Lesson 3.14 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1200.0, '# Lesson 3.24: Backtracking: Generating Subsets & Combinations

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.14
- **Subtopics**:
  - `3.24.1` Exploring decision trees: making a choice, exploring consequences, and undoing the choice (backtracking).
  - `3.24.2` The three steps of backtracking: Choose, Explore, Un-choose.
  - `3.24.3` Generating all subsets (the power set): branching on whether to include or exclude each element.
  - `3.24.4` Combinations and permutations: systematically building valid configurations without duplicate work.
- **Key Failure Modes & Edge Cases**: Forgetting to un-choose (pop) the candidate from the current path list before returning from recursion.
- **Verification & Mastery Check**: Generate all unique subsets of a 3-element list using the recursive choose-explore-unchoose pattern.
- **Project Application**: StreamBuffer: Combinatorial prompt permuter.', '{"solution.py": "# Phase 3 // Lesson 3.24: Backtracking: Generating Subsets & Combinations\n\ndef solve():\n    \"\"\"\n    Verification: Generate all unique subsets of a 3-element list using the recursive choose-explore-unchoose pattern.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.24", "subtopics_count": 4, "verification_criteria": "Generate all unique subsets of a 3-element list using the recursive choose-explore-unchoose pattern.", "subtopics": ["3.24.1 Exploring decision trees: making a choice, exploring consequences, and undoing the choice (backtracking).", "3.24.2 The three steps of backtracking: Choose, Explore, Un-choose.", "3.24.3 Generating all subsets (the power set): branching on whether to include or exclude each element.", "3.24.4 Combinations and permutations: systematically building valid configurations without duplicate work."]}'::jsonb, '["Explain how this implementation prevents: Forgetting to un-choose (pop) the candidate from the current path list before returning from recursion.", "How does Backtracking: Generating Subsets & Combinations scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-25', 'phase-03-lesson-25-dynamic-programming-memoization-top-down', 'module-5', 25, 'Lesson 5.25: Dynamic Programming: Memoization (Top-Down)', 'Prerequisites: Lesson 3.14', 'Prerequisites: Lesson 3.14 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1250.0, '# Lesson 3.25: Dynamic Programming: Memoization (Top-Down)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.14
- **Subtopics**:
  - `3.25.1` Why naive recursion repeats work: Fibonacci numbers recalculating the same sub-problems exponentially.
  - `3.25.2` Overlapping sub-problems: noticing that identical calculations occur hundreds of times across branches.
  - `3.25.3` Memoization (Top-Down DP): caching the return value of a recursive function in a dictionary.
  - `3.25.4` Transforming exponential O(2^N) algorithms into linear O(N) algorithms effortlessly.
- **Key Failure Modes & Edge Cases**: Using mutable unhashable objects (like lists) as keys in the memoization cache dictionary.
- **Verification & Mastery Check**: Implement top-down Fibonacci with a dictionary cache and compute fib(100) instantly without recursion errors.
- **Project Application**: StreamBuffer: Memoized sub-problem cache.', '{"solution.py": "# Phase 3 // Lesson 3.25: Dynamic Programming: Memoization (Top-Down)\n\ndef solve():\n    \"\"\"\n    Verification: Implement top-down Fibonacci with a dictionary cache and compute fib(100) instantly without recursio\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.25", "subtopics_count": 4, "verification_criteria": "Implement top-down Fibonacci with a dictionary cache and compute fib(100) instantly without recursion errors.", "subtopics": ["3.25.1 Why naive recursion repeats work: Fibonacci numbers recalculating the same sub-problems exponentially.", "3.25.2 Overlapping sub-problems: noticing that identical calculations occur hundreds of times across branches.", "3.25.3 Memoization (Top-Down DP): caching the return value of a recursive function in a dictionary.", "3.25.4 Transforming exponential O(2^N) algorithms into linear O(N) algorithms effortlessly."]}'::jsonb, '["Explain how this implementation prevents: Using mutable unhashable objects (like lists) as keys in the memoization cache dictionary.", "How does Dynamic Programming: Memoization (Top-Down) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-26', 'phase-03-lesson-26-dynamic-programming-tabulation-bottom-up', 'module-5', 26, 'Lesson 5.26: Dynamic Programming: Tabulation (Bottom-Up)', 'Prerequisites: Lesson 3.25', 'Prerequisites: Lesson 3.25 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1300.0, '# Lesson 3.26: Dynamic Programming: Tabulation (Bottom-Up)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.25
- **Subtopics**:
  - `3.26.1` Bottom-Up DP: building solutions iteratively starting from the smallest base cases up to N.
  - `3.26.2` The DP table: using a 1D array where table[i] represents the answer for sub-problem of size i.
  - `3.26.3` Eliminating recursion overhead: saving stack frame memory and avoiding recursion depth limits entirely.
  - `3.26.4` Transition relations: writing the recurrence formula that computes table[i] from earlier cells.
- **Key Failure Modes & Edge Cases**: Iterating in the wrong direction or accessing uninitialized table cells that haven''t been computed yet.
- **Verification & Mastery Check**: Implement bottom-up tabulation to compute Fibonacci numbers in iterative O(N) time with 0 recursion.
- **Project Application**: StreamBuffer: Tabulation DP engine.', '{"solution.py": "# Phase 3 // Lesson 3.26: Dynamic Programming: Tabulation (Bottom-Up)\n\ndef solve():\n    \"\"\"\n    Verification: Implement bottom-up tabulation to compute Fibonacci numbers in iterative O(N) time with 0 recursion.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.26", "subtopics_count": 4, "verification_criteria": "Implement bottom-up tabulation to compute Fibonacci numbers in iterative O(N) time with 0 recursion.", "subtopics": ["3.26.1 Bottom-Up DP: building solutions iteratively starting from the smallest base cases up to N.", "3.26.2 The DP table: using a 1D array where table[i] represents the answer for sub-problem of size i.", "3.26.3 Eliminating recursion overhead: saving stack frame memory and avoiding recursion depth limits entirely.", "3.26.4 Transition relations: writing the recurrence formula that computes table[i] from earlier cells."]}'::jsonb, '["Explain how this implementation prevents: Iterating in the wrong direction or accessing uninitialized table cells that haven''t been computed yet.", "How does Dynamic Programming: Tabulation (Bottom-Up) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-27', 'phase-03-lesson-27-1d-dynamic-programming-climbing-stairs-ho', 'module-5', 27, 'Lesson 5.27: 1D Dynamic Programming: Climbing Stairs & House Robber', 'Prerequisites: Lesson 3.26', 'Prerequisites: Lesson 3.26 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1350.0, '# Lesson 3.27: 1D Dynamic Programming: Climbing Stairs & House Robber

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.26
- **Subtopics**:
  - `3.27.1` The Climbing Stairs problem: how many ways to reach step N taking 1 or 2 steps at a time?
  - `3.27.2` The House Robber problem: maximizing loot without robbing two adjacent houses.
  - `3.27.3` Formulating the recurrence: dp[i] = max(dp[i-1], dp[i-2] + loot[i]).
  - `3.27.4` Space optimization: reducing memory from O(N) array down to O(1) by storing only the last two values.
- **Key Failure Modes & Edge Cases**: Failing to handle edge cases for small inputs (like arrays with 0, 1, or 2 elements).
- **Verification & Mastery Check**: Solve the House Robber problem with O(1) space optimization and verify maximum loot on test arrays.
- **Project Application**: StreamBuffer: Optimal sequential selection.', '{"solution.py": "# Phase 3 // Lesson 3.27: 1D Dynamic Programming: Climbing Stairs & House Robber\n\ndef solve():\n    \"\"\"\n    Verification: Solve the House Robber problem with O(1) space optimization and verify maximum loot on test arrays.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.27", "subtopics_count": 4, "verification_criteria": "Solve the House Robber problem with O(1) space optimization and verify maximum loot on test arrays.", "subtopics": ["3.27.1 The Climbing Stairs problem: how many ways to reach step N taking 1 or 2 steps at a time?", "3.27.2 The House Robber problem: maximizing loot without robbing two adjacent houses.", "3.27.3 Formulating the recurrence: dp[i] = max(dp[i-1], dp[i-2] + loot[i]).", "3.27.4 Space optimization: reducing memory from O(N) array down to O(1) by storing only the last two values."]}'::jsonb, '["Explain how this implementation prevents: Failing to handle edge cases for small inputs (like arrays with 0, 1, or 2 elements).", "How does 1D Dynamic Programming: Climbing Stairs & House Robber scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-28', 'phase-03-lesson-28-2d-dynamic-programming-grid-unique-paths', 'module-5', 28, 'Lesson 5.28: 2D Dynamic Programming: Grid Unique Paths', 'Prerequisites: Lesson 3.26', 'Prerequisites: Lesson 3.26 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1400.0, '# Lesson 3.28: 2D Dynamic Programming: Grid Unique Paths

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.26
- **Subtopics**:
  - `3.28.1` Extending DP to 2D grids: counting unique paths from top-left (0, 0) to bottom-right (M-1, N-1).
  - `3.28.2` Grid transitions: dp[row][col] = dp[row-1][col] + dp[row][col-1] (moving only right and down).
  - `3.28.3` Base cases: setting borders (top row and left column) to 1.
  - `3.28.4` Adding obstacles: zeroing out paths that hit blocked grid cells.
- **Key Failure Modes & Edge Cases**: Swapping row and column coordinates when indexing 2D arrays, causing out-of-bounds errors.
- **Verification & Mastery Check**: Write a function that counts unique paths across an M x N grid with obstacles in O(M * N) time.
- **Project Application**: StreamBuffer: Grid traversal path optimizer.', '{"solution.py": "# Phase 3 // Lesson 3.28: 2D Dynamic Programming: Grid Unique Paths\n\ndef solve():\n    \"\"\"\n    Verification: Write a function that counts unique paths across an M x N grid with obstacles in O(M * N) time.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.28", "subtopics_count": 4, "verification_criteria": "Write a function that counts unique paths across an M x N grid with obstacles in O(M * N) time.", "subtopics": ["3.28.1 Extending DP to 2D grids: counting unique paths from top-left (0, 0) to bottom-right (M-1, N-1).", "3.28.2 Grid transitions: dp[row][col] = dp[row-1][col] + dp[row][col-1] (moving only right and down).", "3.28.3 Base cases: setting borders (top row and left column) to 1.", "3.28.4 Adding obstacles: zeroing out paths that hit blocked grid cells."]}'::jsonb, '["Explain how this implementation prevents: Swapping row and column coordinates when indexing 2D arrays, causing out-of-bounds errors.", "How does 2D Dynamic Programming: Grid Unique Paths scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-29', 'phase-03-lesson-29-monotonic-stack-next-greater-element', 'module-5', 29, 'Lesson 5.29: Monotonic Stack: Next Greater Element', 'Prerequisites: Lesson 3.20', 'Prerequisites: Lesson 3.20 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1450.0, '# Lesson 3.29: Monotonic Stack: Next Greater Element

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.20
- **Subtopics**:
  - `3.29.1` What is a monotonic stack: a stack where elements are strictly kept in increasing or decreasing order.
  - `3.29.2` The Next Greater Element problem: finding the first element to the right that is strictly larger.
  - `3.29.3` How it works: popping smaller elements off the stack as soon as a larger element arrives.
  - `3.29.4` Why it is O(N): every element is pushed onto the stack once and popped at most once.
- **Key Failure Modes & Edge Cases**: Pushing values instead of indices onto the stack when the problem requires tracking index distances.
- **Verification & Mastery Check**: Find the next greater element for every number in an array using a monotonic stack in single-pass O(N).
- **Project Application**: StreamBuffer: Monotonic trend detection.', '{"solution.py": "# Phase 3 // Lesson 3.29: Monotonic Stack: Next Greater Element\n\ndef solve():\n    \"\"\"\n    Verification: Find the next greater element for every number in an array using a monotonic stack in single-pass O(\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.29", "subtopics_count": 4, "verification_criteria": "Find the next greater element for every number in an array using a monotonic stack in single-pass O(N).", "subtopics": ["3.29.1 What is a monotonic stack: a stack where elements are strictly kept in increasing or decreasing order.", "3.29.2 The Next Greater Element problem: finding the first element to the right that is strictly larger.", "3.29.3 How it works: popping smaller elements off the stack as soon as a larger element arrives.", "3.29.4 Why it is O(N): every element is pushed onto the stack once and popped at most once."]}'::jsonb, '["Explain how this implementation prevents: Pushing values instead of indices onto the stack when the problem requires tracking index distances.", "How does Monotonic Stack: Next Greater Element scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-30', 'phase-03-lesson-30-string-matching-knuth-morris-pratt-kmp-pr', 'module-5', 30, 'Lesson 5.30: String Matching: Knuth-Morris-Pratt (KMP) Prefix Table', 'Prerequisites: Lesson 3.2, Phase 0 (Lesson 0.3)', 'Prerequisites: Lesson 3.2, Phase 0 (Lesson 0.3) | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1500.0, '# Lesson 3.30: String Matching: Knuth-Morris-Pratt (KMP) Prefix Table

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.2, Phase 0 (Lesson 0.3)
- **Subtopics**:
  - `3.30.1` The brute-force string search limitation: checking patterns against text takes O(N * M) time.
  - `3.30.2` The core insight of KMP: never re-examine characters in text that have already matched.
  - `3.30.3` The Longest Prefix Suffix (LPS) table: pre-computing pattern self-overlaps.
  - `3.30.4` Achieving linear time O(N + M) string search across massive documents and log files.
- **Key Failure Modes & Edge Cases**: Incorrectly indexing the LPS table, causing the search pointer to backtrack too far or skip matches.
- **Verification & Mastery Check**: Construct the LPS table for a search pattern on paper, then implement the KMP search algorithm in Python.
- **Project Application**: StreamBuffer: Linear-time pattern search.', '{"solution.py": "# Phase 3 // Lesson 3.30: String Matching: Knuth-Morris-Pratt (KMP) Prefix Table\n\ndef solve():\n    \"\"\"\n    Verification: Construct the LPS table for a search pattern on paper, then implement the KMP search algorithm in Py\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.30", "subtopics_count": 4, "verification_criteria": "Construct the LPS table for a search pattern on paper, then implement the KMP search algorithm in Python.", "subtopics": ["3.30.1 The brute-force string search limitation: checking patterns against text takes O(N * M) time.", "3.30.2 The core insight of KMP: never re-examine characters in text that have already matched.", "3.30.3 The Longest Prefix Suffix (LPS) table: pre-computing pattern self-overlaps.", "3.30.4 Achieving linear time O(N + M) string search across massive documents and log files."]}'::jsonb, '["Explain how this implementation prevents: Incorrectly indexing the LPS table, causing the search pointer to backtrack too far or skip matches.", "How does String Matching: Knuth-Morris-Pratt (KMP) Prefix Table scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
