INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-12-16', 'phase-12-lesson-16-sandboxed-code-execution-iv-webassembly-w', 'module-13', 16, 'Lesson 13.16: Sandboxed Code Execution IV: WebAssembly (Wasm) & WASI Runtimes', 'Prerequisites: Phase 0, Lesson 12.13', 'Prerequisites: Phase 0, Lesson 12.13 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 800.0, '# Lesson 12.16: Sandboxed Code Execution IV: WebAssembly (Wasm) & WASI Runtimes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 12.13
- **Subtopics**:
  - `12.16.1` WebAssembly as a universal secure sandbox: memory-safe, deterministic, capability-based virtual execution environment
  - `12.16.2` WebAssembly System Interface (WASI): standardized capability-based system interface for non-browser Wasm execution
  - `12.16.3` Wasmtime / Wasmer runtimes in Python: executing compiled Wasm modules directly from Python via language bindings
  - `12.16.4` Zero-trust capabilities: granting explicit, fine-grained directory access and network permissions to Wasm modules
  - `12.16.5` Executing Python inside Wasm: compiling CPython to WebAssembly (Pyodide, Wasm-Python) for near-instant sandboxed Python execution
  - `12.16.6` Performance and cold starts: sub-millisecond instantiation times and microsecond execution teardown with Wasm
- **Key Failure Modes & Edge Cases**: Attempting to run compiled C/Rust binaries with unrestricted host filesystem access, bypassing Wasm capability sandboxing.
- **Verification & Mastery Check**: Deploy a Python-in-Wasm (Wasmtime) sandboxed execution engine in Python; benchmark 1ms cold start and strict capability boundaries.
- **Project Application**: CodeAgent: High-speed WebAssembly sandboxed runner.', '{"solution.py": "# Phase 12 // Lesson 12.16: Sandboxed Code Execution IV: WebAssembly (Wasm) & WASI Runtimes\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a Python-in-Wasm (Wasmtime) sandboxed execution engine in Python; benchmark 1ms cold start an\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.16", "subtopics_count": 6, "verification_criteria": "Deploy a Python-in-Wasm (Wasmtime) sandboxed execution engine in Python; benchmark 1ms cold start and strict capability boundaries.", "subtopics": ["12.16.1 WebAssembly as a universal secure sandbox: memory-safe, deterministic, capability-based virtual execution environment", "12.16.2 WebAssembly System Interface (WASI): standardized capability-based system interface for non-browser Wasm execution", "12.16.3 Wasmtime / Wasmer runtimes in Python: executing compiled Wasm modules directly from Python via language bindings", "12.16.4 Zero-trust capabilities: granting explicit, fine-grained directory access and network permissions to Wasm modules", "12.16.5 Executing Python inside Wasm: compiling CPython to WebAssembly (Pyodide, Wasm-Python) for near-instant sandboxed Python execution", "12.16.6 Performance and cold starts: sub-millisecond instantiation times and microsecond execution teardown with Wasm"]}'::jsonb, '["Explain how this implementation prevents: Attempting to run compiled C/Rust binaries with unrestricted host filesystem access, bypassing Wasm capability sandboxin", "How does Sandboxed Code Execution IV: WebAssembly (Wasm) & WASI Runtimes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-17', 'phase-12-lesson-17-building-codeagent-i-the-workspace-virtua', 'module-13', 17, 'Lesson 13.17: Building CodeAgent I: The Workspace & Virtual Filesystem Environment', 'Prerequisites: Phase 0, Phase 4', 'Prerequisites: Phase 0, Phase 4 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 850.0, '# Lesson 12.17: Building CodeAgent I: The Workspace & Virtual Filesystem Environment

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 4
- **Subtopics**:
  - `12.17.1` CodeAgent project requirements: an autonomous software engineer that writes, tests, debugs, and refactors real codebases
  - `12.17.2` Workspace abstraction: managing a dedicated directory per task with file tracking, git initialization, and clean isolation
  - `12.17.3` Virtual Filesystem operations: implementing robust tool primitives: `read_file`, `write_file`, `edit_file`, `list_directory`
  - `12.17.4` Precise file editing: why whole-file rewriting fails on large files; implementing chunk-based string replacement with diffs
  - `12.17.5` Diff validation: verifying that target replacement blocks are unique before modifying source files to prevent accidental corruption
  - `12.17.6` Git integration: automatic git commit after every agent action to provide an immutable operational audit trail
- **Key Failure Modes & Edge Cases**: Whole-file rewrites truncating large 1,000-line files when output token limits are hit mid-generation.
- **Verification & Mastery Check**: Build a robust file manipulation toolset in Python supporting line-targeted replacements, diff previews, and git snapshotting.
- **Project Application**: CodeAgent: Workspace and filesystem management toolset.', '{"solution.py": "# Phase 12 // Lesson 12.17: Building CodeAgent I: The Workspace & Virtual Filesystem Environment\n\ndef solve():\n    \"\"\"\n    Verification: Build a robust file manipulation toolset in Python supporting line-targeted replacements, diff previ\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.17", "subtopics_count": 6, "verification_criteria": "Build a robust file manipulation toolset in Python supporting line-targeted replacements, diff previews, and git snapshotting.", "subtopics": ["12.17.1 CodeAgent project requirements: an autonomous software engineer that writes, tests, debugs, and refactors real codebases", "12.17.2 Workspace abstraction: managing a dedicated directory per task with file tracking, git initialization, and clean isolation", "12.17.3 Virtual Filesystem operations: implementing robust tool primitives: `read_file`, `write_file`, `edit_file`, `list_directory`", "12.17.4 Precise file editing: why whole-file rewriting fails on large files; implementing chunk-based string replacement with diffs", "12.17.5 Diff validation: verifying that target replacement blocks are unique before modifying source files to prevent accidental corruption", "12.17.6 Git integration: automatic git commit after every agent action to provide an immutable operational audit trail"]}'::jsonb, '["Explain how this implementation prevents: Whole-file rewrites truncating large 1,000-line files when output token limits are hit mid-generation.", "How does Building CodeAgent I: The Workspace & Virtual Filesystem Environment scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-18', 'phase-12-lesson-18-building-codeagent-ii-terminal-execution-', 'module-13', 18, 'Lesson 13.18: Building CodeAgent II: Terminal Execution & Bash Tool Orchestration', 'Prerequisites: Phase 0, Phase 4, Lesson 12.14', 'Prerequisites: Phase 0, Phase 4, Lesson 12.14 | Subtopics: 6 items', 'Systems project application', 340, 13, 3000.0, 900.0, '# Lesson 12.18: Building CodeAgent II: Terminal Execution & Bash Tool Orchestration

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 4, Lesson 12.14
- **Subtopics**:
  - `12.18.1` Bash command execution tool: allowing the agent to run compilers, linters, tests, and package managers
  - `12.18.2` Process execution mechanics: `asyncio.create_subprocess_exec` vs `create_subprocess_shell` security trade-offs
  - `12.18.3` Handling long-running and hanging commands: automated timeouts, process group termination (`os.killpg`), and SIGKILL escalation
  - `12.18.4` Paging command mitigation: enforcing `PAGER=cat` to prevent commands like `git diff` or `less` from blocking on interactive stdin
  - `12.18.5` Capturing stdout and stderr: streaming command output, truncation limits (preventing multi-megabyte log flooding), and exit codes
  - `12.18.6` Command whitelisting and blacklisting: preventing interactive commands (`vim`, `nano`, `top`) from hanging the execution loop
- **Key Failure Modes & Edge Cases**: Executing a command that prompts for interactive user confirmation (`y/n`), hanging the background agent process indefinitely.
- **Verification & Mastery Check**: Build an asynchronous, non-interactive Bash command executor in Python with process group termination and output truncation.
- **Project Application**: CodeAgent: Interactive terminal execution engine.', '{"solution.py": "# Phase 12 // Lesson 12.18: Building CodeAgent II: Terminal Execution & Bash Tool Orchestration\n\ndef solve():\n    \"\"\"\n    Verification: Build an asynchronous, non-interactive Bash command executor in Python with process group terminatio\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.18", "subtopics_count": 6, "verification_criteria": "Build an asynchronous, non-interactive Bash command executor in Python with process group termination and output truncation.", "subtopics": ["12.18.1 Bash command execution tool: allowing the agent to run compilers, linters, tests, and package managers", "12.18.2 Process execution mechanics: `asyncio.create_subprocess_exec` vs `create_subprocess_shell` security trade-offs", "12.18.3 Handling long-running and hanging commands: automated timeouts, process group termination (`os.killpg`), and SIGKILL escalation", "12.18.4 Paging command mitigation: enforcing `PAGER=cat` to prevent commands like `git diff` or `less` from blocking on interactive stdin", "12.18.5 Capturing stdout and stderr: streaming command output, truncation limits (preventing multi-megabyte log flooding), and exit codes", "12.18.6 Command whitelisting and blacklisting: preventing interactive commands (`vim`, `nano`, `top`) from hanging the execution loop"]}'::jsonb, '["Explain how this implementation prevents: Executing a command that prompts for interactive user confirmation (`y/n`), hanging the background agent process indefin", "How does Building CodeAgent II: Terminal Execution & Bash Tool Orchestration scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-19', 'phase-12-lesson-19-building-codeagent-iii-code-navigation-as', 'module-13', 19, 'Lesson 13.19: Building CodeAgent III: Code Navigation & AST Semantic Search', 'Prerequisites: Phase 1, Phase 10', 'Prerequisites: Phase 1, Phase 10 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 950.0, '# Lesson 12.19: Building CodeAgent III: Code Navigation & AST Semantic Search

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Phase 10
- **Subtopics**:
  - `12.19.1` Why simple grep is insufficient for large codebases: missing semantic context, hierarchy, and symbol relationships
  - `12.19.2` Abstract Syntax Tree (AST) parsing with Tree-sitter: universal multi-language parsing (Python, TypeScript, Go, Rust)
  - `12.19.3` Symbol extraction: parsing class definitions, function signatures, docstrings, and imports into a structured symbol index
  - `12.19.4` Code navigation tools: `find_symbol_definition`, `find_references`, `get_function_signature`, and `get_class_hierarchy`
  - `12.19.5` Combining lexical search with AST navigation: using ripgrep for fast regex scanning and Tree-sitter for precise syntax node extraction
  - `12.19.6` Token-efficient repository map: generating a compact 500-token structural map of the entire codebase for working context
- **Key Failure Modes & Edge Cases**: Stuffing all source files into the prompt, overwhelming the model context window and degrading reasoning accuracy.
- **Verification & Mastery Check**: Build a Tree-sitter powered code navigation engine extracting symbols and function signatures across a multi-file Python project.
- **Project Application**: CodeAgent: Semantic code navigation and AST symbol engine.', '{"solution.py": "# Phase 12 // Lesson 12.19: Building CodeAgent III: Code Navigation & AST Semantic Search\n\ndef solve():\n    \"\"\"\n    Verification: Build a Tree-sitter powered code navigation engine extracting symbols and function signatures across\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.19", "subtopics_count": 6, "verification_criteria": "Build a Tree-sitter powered code navigation engine extracting symbols and function signatures across a multi-file Python project.", "subtopics": ["12.19.1 Why simple grep is insufficient for large codebases: missing semantic context, hierarchy, and symbol relationships", "12.19.2 Abstract Syntax Tree (AST) parsing with Tree-sitter: universal multi-language parsing (Python, TypeScript, Go, Rust)", "12.19.3 Symbol extraction: parsing class definitions, function signatures, docstrings, and imports into a structured symbol index", "12.19.4 Code navigation tools: `find_symbol_definition`, `find_references`, `get_function_signature`, and `get_class_hierarchy`", "12.19.5 Combining lexical search with AST navigation: using ripgrep for fast regex scanning and Tree-sitter for precise syntax node extraction", "12.19.6 Token-efficient repository map: generating a compact 500-token structural map of the entire codebase for working context"]}'::jsonb, '["Explain how this implementation prevents: Stuffing all source files into the prompt, overwhelming the model context window and degrading reasoning accuracy.", "How does Building CodeAgent III: Code Navigation & AST Semantic Search scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-20', 'phase-12-lesson-20-building-codeagent-iv-test-driven-develop', 'module-13', 20, 'Lesson 13.20: Building CodeAgent IV: Test-Driven Development (TDD) Loop & Repair', 'Prerequisites: Phase 1, Lesson 12.2', 'Prerequisites: Phase 1, Lesson 12.2 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 1000.0, '# Lesson 12.20: Building CodeAgent IV: Test-Driven Development (TDD) Loop & Repair

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Lesson 12.2
- **Subtopics**:
  - `12.20.1` Test-Driven Development (TDD) agent loop: Write Test $\to$ Run Test (Verify Failure) $\to$ Implement Code $\to$ Run Test (Verify Pass)
  - `12.20.2` Parsing test suite outputs: structured regex extraction of test failures, assertion errors, and tracebacks from `pytest` / `vitest`
  - `12.20.3` Automated error triage: feeding stack traces, failing line numbers, and expected vs actual values back into the agent reasoning loop
  - `12.20.4` The Reflexion repair cycle: agent formulates a bug hypothesis, inspects relevant source lines, modifies code, and re-executes tests
  - `12.20.5` Preventing regression: running the full test suite after every modification to verify that bug fixes didn''t break existing functionality
  - `12.20.6` Self-stopping criteria: terminating execution successfully upon 100% test pass or escalating to human after 5 failed repair attempts
- **Key Failure Modes & Edge Cases**: Agent modifying the test assertions to pass rather than fixing the underlying broken application logic.
- **Verification & Mastery Check**: Run CodeAgent on a broken repository; verify that it parses pytest error output, applies correct code edits, and passes all tests.
- **Project Application**: CodeAgent: Automated TDD execution and repair engine.', '{"solution.py": "# Phase 12 // Lesson 12.20: Building CodeAgent IV: Test-Driven Development (TDD) Loop & Repair\n\ndef solve():\n    \"\"\"\n    Verification: Run CodeAgent on a broken repository; verify that it parses pytest error output, applies correct cod\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.20", "subtopics_count": 6, "verification_criteria": "Run CodeAgent on a broken repository; verify that it parses pytest error output, applies correct code edits, and passes all tests.", "subtopics": ["12.20.1 Test-Driven Development (TDD) agent loop: Write Test $\\to$ Run Test (Verify Failure) $\\to$ Implement Code $\\to$ Run Test (Verify Pass)", "12.20.2 Parsing test suite outputs: structured regex extraction of test failures, assertion errors, and tracebacks from `pytest` / `vitest`", "12.20.3 Automated error triage: feeding stack traces, failing line numbers, and expected vs actual values back into the agent reasoning loop", "12.20.4 The Reflexion repair cycle: agent formulates a bug hypothesis, inspects relevant source lines, modifies code, and re-executes tests", "12.20.5 Preventing regression: running the full test suite after every modification to verify that bug fixes didn''t break existing functionality", "12.20.6 Self-stopping criteria: terminating execution successfully upon 100% test pass or escalating to human after 5 failed repair attempts"]}'::jsonb, '["Explain how this implementation prevents: Agent modifying the test assertions to pass rather than fixing the underlying broken application logic.", "How does Building CodeAgent IV: Test-Driven Development (TDD) Loop & Repair scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-21', 'phase-12-lesson-21-multi-agent-architectures-when-to-split-i', 'module-13', 21, 'Lesson 13.21: Multi-Agent Architectures: When to Split into Specialized Agents', 'Prerequisites: Lesson 12.1', 'Prerequisites: Lesson 12.1 | Subtopics: 6 items', 'Systems project application', 340, 13, 3000.0, 1050.0, '# Lesson 12.21: Multi-Agent Architectures: When to Split into Specialized Agents

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 12.1
- **Subtopics**:
  - `12.21.1` The monolithic agent breakdown: why single agents with 30 tools fail due to tool selection confusion and context bloat
  - `12.21.2` Principles of Multi-Agent Systems: division of labor, domain specialization, smaller focused prompt contexts, and modular testing
  - `12.21.3` Agent roles taxonomy: Planner / Architect, Researcher / Explorer, Software Engineer, Code Reviewer / QA, DevOps Engineer
  - `12.21.4` Communication topologies: Centralized Supervisor vs Decentralized Peer-to-Peer vs Hierarchical Teams vs Pipeline Chaining
  - `12.21.5` Cost and latency implications: multi-agent systems multiply token usage; matching architecture to task value
  - `12.21.6` Evaluating multi-agent trade-offs: when single-agent with structured workflows outperforms multi-agent debate
- **Key Failure Modes & Edge Cases**: Deploying a multi-agent system of 6 debating agents for a trivial 1-file typo fix, burning $5 in tokens for a 2-second task.
- **Verification & Mastery Check**: Draft an architectural comparison matrix evaluating Single-Agent vs Supervisor Multi-Agent on a complex software feature task.
- **Project Application**: CodeAgent: Multi-agent architectural design document.', '{"solution.py": "# Phase 12 // Lesson 12.21: Multi-Agent Architectures: When to Split into Specialized Agents\n\ndef solve():\n    \"\"\"\n    Verification: Draft an architectural comparison matrix evaluating Single-Agent vs Supervisor Multi-Agent on a comp\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.21", "subtopics_count": 6, "verification_criteria": "Draft an architectural comparison matrix evaluating Single-Agent vs Supervisor Multi-Agent on a complex software feature task.", "subtopics": ["12.21.1 The monolithic agent breakdown: why single agents with 30 tools fail due to tool selection confusion and context bloat", "12.21.2 Principles of Multi-Agent Systems: division of labor, domain specialization, smaller focused prompt contexts, and modular testing", "12.21.3 Agent roles taxonomy: Planner / Architect, Researcher / Explorer, Software Engineer, Code Reviewer / QA, DevOps Engineer", "12.21.4 Communication topologies: Centralized Supervisor vs Decentralized Peer-to-Peer vs Hierarchical Teams vs Pipeline Chaining", "12.21.5 Cost and latency implications: multi-agent systems multiply token usage; matching architecture to task value", "12.21.6 Evaluating multi-agent trade-offs: when single-agent with structured workflows outperforms multi-agent debate"]}'::jsonb, '["Explain how this implementation prevents: Deploying a multi-agent system of 6 debating agents for a trivial 1-file typo fix, burning $5 in tokens for a 2-second t", "How does Multi-Agent Architectures: When to Split into Specialized Agents scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-22', 'phase-12-lesson-22-multi-agent-patterns-i-the-supervisor-wor', 'module-13', 22, 'Lesson 13.22: Multi-Agent Patterns I: The Supervisor-Worker Orchestration Pattern', 'Prerequisites: Lesson 12.6, Lesson 12.21', 'Prerequisites: Lesson 12.6, Lesson 12.21 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 1100.0, '# Lesson 12.22: Multi-Agent Patterns I: The Supervisor-Worker Orchestration Pattern

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 12.6, Lesson 12.21
- **Subtopics**:
  - `12.22.1` Supervisor-Worker topology: a centralized orchestrator agent delegating specialized sub-tasks to dedicated worker agents
  - `12.22.2` The Supervisor node in LangGraph: analyzing user request, maintaining high-level plan, and routing to specialized worker nodes
  - `12.22.3` Worker agent specialization: Research Worker (read-only tools), Coder Worker (filesystem tools), Test Worker (bash/pytest tools)
  - `12.22.4` Worker execution lifecycle: worker receives sub-task, executes internal cyclic loop to completion, and returns structured outcome to Supervisor
  - `12.22.5` Supervisor state synthesis: aggregating worker outputs, updating task progress, and deciding the next worker to invoke or terminating
  - `12.22.6` Dynamic replanning: supervisor modifying the remaining plan when a worker reports an impossible sub-task
- **Key Failure Modes & Edge Cases**: Workers returning massive unstructured chat transcripts to the supervisor, overflowing the supervisor context window.
- **Verification & Mastery Check**: Implement a LangGraph Supervisor-Worker system with a Research Worker and Coder Worker collaborating to solve a coding challenge.
- **Project Application**: CodeAgent: Supervisor-Worker orchestration network.', '{"solution.py": "# Phase 12 // Lesson 12.22: Multi-Agent Patterns I: The Supervisor-Worker Orchestration Pattern\n\ndef solve():\n    \"\"\"\n    Verification: Implement a LangGraph Supervisor-Worker system with a Research Worker and Coder Worker collaborating\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.22", "subtopics_count": 6, "verification_criteria": "Implement a LangGraph Supervisor-Worker system with a Research Worker and Coder Worker collaborating to solve a coding challenge.", "subtopics": ["12.22.1 Supervisor-Worker topology: a centralized orchestrator agent delegating specialized sub-tasks to dedicated worker agents", "12.22.2 The Supervisor node in LangGraph: analyzing user request, maintaining high-level plan, and routing to specialized worker nodes", "12.22.3 Worker agent specialization: Research Worker (read-only tools), Coder Worker (filesystem tools), Test Worker (bash/pytest tools)", "12.22.4 Worker execution lifecycle: worker receives sub-task, executes internal cyclic loop to completion, and returns structured outcome to Supervisor", "12.22.5 Supervisor state synthesis: aggregating worker outputs, updating task progress, and deciding the next worker to invoke or terminating", "12.22.6 Dynamic replanning: supervisor modifying the remaining plan when a worker reports an impossible sub-task"]}'::jsonb, '["Explain how this implementation prevents: Workers returning massive unstructured chat transcripts to the supervisor, overflowing the supervisor context window.", "How does Multi-Agent Patterns I: The Supervisor-Worker Orchestration Pattern scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-23', 'phase-12-lesson-23-multi-agent-patterns-ii-hierarchical-team', 'module-13', 23, 'Lesson 13.23: Multi-Agent Patterns II: Hierarchical Teams & Subgraph Composition', 'Prerequisites: Lesson 12.6, Lesson 12.22', 'Prerequisites: Lesson 12.6, Lesson 12.22 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 1150.0, '# Lesson 12.23: Multi-Agent Patterns II: Hierarchical Teams & Subgraph Composition

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 12.6, Lesson 12.22
- **Subtopics**:
  - `12.23.1` Scaling beyond flat supervisor topologies: nested hierarchical teams managing complex enterprise software projects
  - `12.23.2` Subgraph composition in LangGraph: compiling independent state graphs and embedding them as callable nodes inside parent graphs
  - `12.23.3` Top-level Engineering Director graph: delegating to Frontend Team subgraph, Backend Team subgraph, and QA Team subgraph
  - `12.23.4` State boundary isolation: subgraphs operating on local state schemas, passing only essential summaries back to parent graphs
  - `12.23.5` Cross-team communication protocols: standardized contract interfaces between frontend and backend agent teams
  - `12.23.6` Parallel team execution: executing independent subgraphs concurrently in the same superstep to minimize total wall-clock time
- **Key Failure Modes & Edge Cases**: State pollution across teams: sharing global mutable variables across subgraphs causing unintended cross-team side effects.
- **Verification & Mastery Check**: Build a nested LangGraph system where a parent Manager graph coordinates a Backend subgraph and a Frontend subgraph in parallel.
- **Project Application**: CodeAgent: Hierarchical multi-team subgraph architecture.', '{"solution.py": "# Phase 12 // Lesson 12.23: Multi-Agent Patterns II: Hierarchical Teams & Subgraph Composition\n\ndef solve():\n    \"\"\"\n    Verification: Build a nested LangGraph system where a parent Manager graph coordinates a Backend subgraph and a Fr\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.23", "subtopics_count": 6, "verification_criteria": "Build a nested LangGraph system where a parent Manager graph coordinates a Backend subgraph and a Frontend subgraph in parallel.", "subtopics": ["12.23.1 Scaling beyond flat supervisor topologies: nested hierarchical teams managing complex enterprise software projects", "12.23.2 Subgraph composition in LangGraph: compiling independent state graphs and embedding them as callable nodes inside parent graphs", "12.23.3 Top-level Engineering Director graph: delegating to Frontend Team subgraph, Backend Team subgraph, and QA Team subgraph", "12.23.4 State boundary isolation: subgraphs operating on local state schemas, passing only essential summaries back to parent graphs", "12.23.5 Cross-team communication protocols: standardized contract interfaces between frontend and backend agent teams", "12.23.6 Parallel team execution: executing independent subgraphs concurrently in the same superstep to minimize total wall-clock time"]}'::jsonb, '["Explain how this implementation prevents: State pollution across teams: sharing global mutable variables across subgraphs causing unintended cross-team side effec", "How does Multi-Agent Patterns II: Hierarchical Teams & Subgraph Composition scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-24', 'phase-12-lesson-24-multi-agent-patterns-iii-collaborative-mu', 'module-13', 24, 'Lesson 13.24: Multi-Agent Patterns III: Collaborative Multi-Agent Debate & Consensus', 'Prerequisites: Lesson 12.21', 'Prerequisites: Lesson 12.21 | Subtopics: 6 items', 'Systems project application', 340, 13, 3000.0, 1200.0, '# Lesson 12.24: Multi-Agent Patterns III: Collaborative Multi-Agent Debate & Consensus

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 12.21
- **Subtopics**:
  - `12.24.1` The Multi-Agent Debate paradigm (Du et al.): multiple agents presenting solutions, critiquing each other, and reaching consensus
  - `12.24.2` Mitigating individual model hallucinations: how peer critique surfaces factual errors, edge-case oversights, and logic bugs
  - `12.24.3` Debate topologies: Round-Robin debate vs Adversarial debate (Proposer vs Red Team Critic) vs Jury Consensus voting
  - `12.24.4` Structuring critique prompts: forcing critics to focus on security vulnerabilities, edge cases, and algorithmic complexity
  - `12.24.5` Consensus termination algorithms: measuring solution convergence; terminating when critique identifies zero remaining issues
  - `12.24.6` Preventing groupthink: injecting contrarian personas or temperature diversity to avoid agents prematurely agreeing on wrong answers
- **Key Failure Modes & Edge Cases**: Agents entering an infinite polite agreement loop (''I agree with your brilliant point'') without performing rigorous critical verification.
- **Verification & Mastery Check**: Implement an Adversarial Code Review debate where a Critic agent attacks a Coder agent''s code until 0 security vulnerabilities remain.
- **Project Application**: CodeAgent: Adversarial debate and code review engine.', '{"solution.py": "# Phase 12 // Lesson 12.24: Multi-Agent Patterns III: Collaborative Multi-Agent Debate & Consensus\n\ndef solve():\n    \"\"\"\n    Verification: Implement an Adversarial Code Review debate where a Critic agent attacks a Coder agent''s code until \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.24", "subtopics_count": 6, "verification_criteria": "Implement an Adversarial Code Review debate where a Critic agent attacks a Coder agent''s code until 0 security vulnerabilities remain.", "subtopics": ["12.24.1 The Multi-Agent Debate paradigm (Du et al.): multiple agents presenting solutions, critiquing each other, and reaching consensus", "12.24.2 Mitigating individual model hallucinations: how peer critique surfaces factual errors, edge-case oversights, and logic bugs", "12.24.3 Debate topologies: Round-Robin debate vs Adversarial debate (Proposer vs Red Team Critic) vs Jury Consensus voting", "12.24.4 Structuring critique prompts: forcing critics to focus on security vulnerabilities, edge cases, and algorithmic complexity", "12.24.5 Consensus termination algorithms: measuring solution convergence; terminating when critique identifies zero remaining issues", "12.24.6 Preventing groupthink: injecting contrarian personas or temperature diversity to avoid agents prematurely agreeing on wrong answers"]}'::jsonb, '["Explain how this implementation prevents: Agents entering an infinite polite agreement loop (''I agree with your brilliant point'') without performing rigorous crit", "How does Multi-Agent Patterns III: Collaborative Multi-Agent Debate & Consensus scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-25', 'phase-12-lesson-25-agent-communication-protocols-structured-', 'module-13', 25, 'Lesson 13.25: Agent Communication Protocols & Structured Message Buses', 'Prerequisites: Phase 4, Phase 7, Lesson 12.22', 'Prerequisites: Phase 4, Phase 7, Lesson 12.22 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 1250.0, '# Lesson 12.25: Agent Communication Protocols & Structured Message Buses

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 7, Lesson 12.22
- **Subtopics**:
  - `12.25.1` Inter-agent communication standards: moving beyond raw natural language strings to structured protocol messages
  - `12.25.2` Agent Communication Language (ACL) principles: performatives (Request, Inform, Propose, Reject, Confirm, Query)
  - `12.25.3` Structured message envelop: `sender`, `recipient`, `performative`, `conversation_id`, `reply_with`, `payload` (Pydantic model)
  - `12.25.4` Asynchronous message routing: backing inter-agent communication with Redis Streams or Kafka for distributed multi-agent systems
  - `12.25.5` Agent service discovery: registry where agents query capabilities of available peer agents dynamically
  - `12.25.6` Dead-letter queues and message tracing: tracking inter-agent message exchanges with distributed OpenTelemetry spans
- **Key Failure Modes & Edge Cases**: Natural language ambiguity causing Worker B to misinterpret Worker A''s output format, resulting in parsing crashes.
- **Verification & Mastery Check**: Implement a typed JSON message bus supporting standard FIPA-ACL performatives for structured inter-agent collaboration.
- **Project Application**: CodeAgent: Distributed agent message bus protocol.', '{"solution.py": "# Phase 12 // Lesson 12.25: Agent Communication Protocols & Structured Message Buses\n\ndef solve():\n    \"\"\"\n    Verification: Implement a typed JSON message bus supporting standard FIPA-ACL performatives for structured inter-a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.25", "subtopics_count": 6, "verification_criteria": "Implement a typed JSON message bus supporting standard FIPA-ACL performatives for structured inter-agent collaboration.", "subtopics": ["12.25.1 Inter-agent communication standards: moving beyond raw natural language strings to structured protocol messages", "12.25.2 Agent Communication Language (ACL) principles: performatives (Request, Inform, Propose, Reject, Confirm, Query)", "12.25.3 Structured message envelop: `sender`, `recipient`, `performative`, `conversation_id`, `reply_with`, `payload` (Pydantic model)", "12.25.4 Asynchronous message routing: backing inter-agent communication with Redis Streams or Kafka for distributed multi-agent systems", "12.25.5 Agent service discovery: registry where agents query capabilities of available peer agents dynamically", "12.25.6 Dead-letter queues and message tracing: tracking inter-agent message exchanges with distributed OpenTelemetry spans"]}'::jsonb, '["Explain how this implementation prevents: Natural language ambiguity causing Worker B to misinterpret Worker A''s output format, resulting in parsing crashes.", "How does Agent Communication Protocols & Structured Message Buses scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
