INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-11-21', 'phase-11-lesson-21-mlops-foundations-the-ml-lifecycle-techni', 'module-12', 21, 'Lesson 12.21: MLOps Foundations: The ML Lifecycle & Technical Debt in AI Systems', 'Prerequisites: Phase 9, Phase 10', 'Prerequisites: Phase 9, Phase 10 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 1050.0, '# Lesson 11.21: MLOps Foundations: The ML Lifecycle & Technical Debt in AI Systems

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 10
- **Subtopics**:
  - `11.21.1` The Hidden Technical Debt in Machine Learning Systems (Sculley et al.): ML code as a small fraction of real-world ML systems
  - `11.21.2` The ML lifecycle: Data Ingestion $\to$ Feature Engineering $\to$ Model Training $\to$ Evaluation $\to$ Registry $\to$ Deployment $\to$ Monitoring
  - `11.21.3` Reproducibility in MLOps: tracking the exact triplet of (Code Version, Data Version, Hyperparameters) for every trained model
  - `11.21.4` Configuration debt, pipeline jungles, dead experimental code branches, and boundary erosion in ML architectures
  - `11.21.5` Data versioning with DVC (Data Version Control): Git-like tracking of multi-gigabyte datasets using S3/GCS content hashes
  - `11.21.6` Automating the training pipeline: orchestrating end-to-end reproducible training jobs via Kubeflow Pipelines or GitHub Actions
- **Key Failure Modes & Edge Cases**: Deploying a high-performing model to production without recording its exact training commit hash or dataset snapshot, making retraining impossible.
- **Verification & Mastery Check**: Set up DVC tracking a 5GB dataset in Google Cloud Storage; link dataset version commit tags directly to a training script run.
- **Project Application**: ModelPulse: Dataset versioning and DVC pipeline.', '{"solution.py": "# Phase 11 // Lesson 11.21: MLOps Foundations: The ML Lifecycle & Technical Debt in AI Systems\n\ndef solve():\n    \"\"\"\n    Verification: Set up DVC tracking a 5GB dataset in Google Cloud Storage; link dataset version commit tags directly\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.21", "subtopics_count": 6, "verification_criteria": "Set up DVC tracking a 5GB dataset in Google Cloud Storage; link dataset version commit tags directly to a training script run.", "subtopics": ["11.21.1 The Hidden Technical Debt in Machine Learning Systems (Sculley et al.): ML code as a small fraction of real-world ML systems", "11.21.2 The ML lifecycle: Data Ingestion $\\to$ Feature Engineering $\\to$ Model Training $\\to$ Evaluation $\\to$ Registry $\\to$ Deployment $\\to$ Monitoring", "11.21.3 Reproducibility in MLOps: tracking the exact triplet of (Code Version, Data Version, Hyperparameters) for every trained model", "11.21.4 Configuration debt, pipeline jungles, dead experimental code branches, and boundary erosion in ML architectures", "11.21.5 Data versioning with DVC (Data Version Control): Git-like tracking of multi-gigabyte datasets using S3/GCS content hashes", "11.21.6 Automating the training pipeline: orchestrating end-to-end reproducible training jobs via Kubeflow Pipelines or GitHub Actions"]}'::jsonb, '["Explain how this implementation prevents: Deploying a high-performing model to production without recording its exact training commit hash or dataset snapshot, ma", "How does MLOps Foundations: The ML Lifecycle & Technical Debt in AI Systems scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-22', 'phase-11-lesson-22-model-registries-artifact-versioning-with', 'module-12', 22, 'Lesson 12.22: Model Registries & Artifact Versioning with MLflow', 'Prerequisites: Lesson 11.21', 'Prerequisites: Lesson 11.21 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 1100.0, '# Lesson 11.22: Model Registries & Artifact Versioning with MLflow

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 11.21
- **Subtopics**:
  - `11.22.1` MLflow architecture: MLflow Tracking (metrics/params), MLflow Models (standard packaging), and MLflow Model Registry
  - `11.22.2` Logging training runs: `mlflow.log_params()`, `mlflow.log_metrics()`, and logging training curves over epochs
  - `11.22.3` Model packaging: MLmodel format, Conda/Pip environment specifications, and universal pyfunc Python flavor
  - `11.22.4` Model Registry lifecycle: transitioning model versions across stages (`None` $\to$ `Staging` $\to$ `Production` $\to$ `Archived`)
  - `11.22.5` Model governance: assigning model descriptions, tagging accuracy metrics, tracking author provenance, and approval workflows
  - `11.22.6` Automated model promotion: promoting a candidate model to `Production` stage only if validation metrics exceed current production champion
- **Key Failure Modes & Edge Cases**: Deploying raw model weights without tracking dependencies, causing runtime import crashes due to mismatched library versions in production.
- **Verification & Mastery Check**: Deploy a central MLflow tracking server backed by PostgreSQL and GCS; log training runs and automate model promotion via Python SDK.
- **Project Application**: ModelPulse: Enterprise MLflow model registry infrastructure.', '{"solution.py": "# Phase 11 // Lesson 11.22: Model Registries & Artifact Versioning with MLflow\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a central MLflow tracking server backed by PostgreSQL and GCS; log training runs and automate\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.22", "subtopics_count": 6, "verification_criteria": "Deploy a central MLflow tracking server backed by PostgreSQL and GCS; log training runs and automate model promotion via Python SDK.", "subtopics": ["11.22.1 MLflow architecture: MLflow Tracking (metrics/params), MLflow Models (standard packaging), and MLflow Model Registry", "11.22.2 Logging training runs: `mlflow.log_params()`, `mlflow.log_metrics()`, and logging training curves over epochs", "11.22.3 Model packaging: MLmodel format, Conda/Pip environment specifications, and universal pyfunc Python flavor", "11.22.4 Model Registry lifecycle: transitioning model versions across stages (`None` $\\to$ `Staging` $\\to$ `Production` $\\to$ `Archived`)", "11.22.5 Model governance: assigning model descriptions, tagging accuracy metrics, tracking author provenance, and approval workflows", "11.22.6 Automated model promotion: promoting a candidate model to `Production` stage only if validation metrics exceed current production champion"]}'::jsonb, '["Explain how this implementation prevents: Deploying raw model weights without tracking dependencies, causing runtime import crashes due to mismatched library vers", "How does Model Registries & Artifact Versioning with MLflow scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-23', 'phase-11-lesson-23-high-performance-model-serving-triton-vll', 'module-12', 23, 'Lesson 12.23: High-Performance Model Serving: Triton, vLLM & TorchServe', 'Prerequisites: Phase 9, Phase 10', 'Prerequisites: Phase 9, Phase 10 | Subtopics: 6 items', 'Systems project application', 320, 12, 2870.0, 1150.0, '# Lesson 11.23: High-Performance Model Serving: Triton, vLLM & TorchServe

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Phase 10
- **Subtopics**:
  - `11.23.1` The model serving challenge: optimizing GPU utilization, memory bandwidth, latency, and throughput during inference
  - `11.23.2` Triton Inference Server (NVIDIA): multi-framework support (PyTorch, ONNX, TensorRT), dynamic batching, concurrent model execution
  - `11.23.3` Dynamic Batching mechanics: aggregating individual incoming requests into a single GPU tensor batch within a small time window (e.g. 5ms)
  - `11.23.4` vLLM engine internals: high-throughput LLM serving via PagedAttention (managing KV-cache memory like virtual memory pages)
  - `11.23.5` Continuous batching (iteration-level scheduling): scheduling new requests at every token generation step rather than waiting for full sequences
  - `11.23.6` Benchmarking model serving: measuring Time To First Token (TTFT), Inter-Token Latency (ITL), and Requests Per Second (RPS)
- **Key Failure Modes & Edge Cases**: Serving PyTorch models using naive Flask/FastAPI processes with concurrency=1, underutilizing expensive $30,000 GPUs by 90%.
- **Verification & Mastery Check**: Deploy an LLM using vLLM with PagedAttention; benchmark throughput against a naive HuggingFace baseline, demonstrating $4\times$ speedup.
- **Project Application**: ModelPulse: High-performance model serving deployment.', '{"solution.py": "# Phase 11 // Lesson 11.23: High-Performance Model Serving: Triton, vLLM & TorchServe\n\ndef solve():\n    \"\"\"\n    Verification: Deploy an LLM using vLLM with PagedAttention; benchmark throughput against a naive HuggingFace basel\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.23", "subtopics_count": 6, "verification_criteria": "Deploy an LLM using vLLM with PagedAttention; benchmark throughput against a naive HuggingFace baseline, demonstrating $4\\times$ speedup.", "subtopics": ["11.23.1 The model serving challenge: optimizing GPU utilization, memory bandwidth, latency, and throughput during inference", "11.23.2 Triton Inference Server (NVIDIA): multi-framework support (PyTorch, ONNX, TensorRT), dynamic batching, concurrent model execution", "11.23.3 Dynamic Batching mechanics: aggregating individual incoming requests into a single GPU tensor batch within a small time window (e.g. 5ms)", "11.23.4 vLLM engine internals: high-throughput LLM serving via PagedAttention (managing KV-cache memory like virtual memory pages)", "11.23.5 Continuous batching (iteration-level scheduling): scheduling new requests at every token generation step rather than waiting for full sequences", "11.23.6 Benchmarking model serving: measuring Time To First Token (TTFT), Inter-Token Latency (ITL), and Requests Per Second (RPS)"]}'::jsonb, '["Explain how this implementation prevents: Serving PyTorch models using naive Flask/FastAPI processes with concurrency=1, underutilizing expensive $30,000 GPUs by ", "How does High-Performance Model Serving: Triton, vLLM & TorchServe scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-24', 'phase-11-lesson-24-model-serialization-optimization-onnx-ten', 'module-12', 24, 'Lesson 12.24: Model Serialization & Optimization: ONNX, TensorRT & Quantization', 'Prerequisites: Phase 9, Lesson 11.23', 'Prerequisites: Phase 9, Lesson 11.23 | Subtopics: 6 items', 'Systems project application', 320, 12, 2750.0, 1200.0, '# Lesson 11.24: Model Serialization & Optimization: ONNX, TensorRT & Quantization

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Lesson 11.23
- **Subtopics**:
  - `11.24.1` Open Neural Network Exchange (ONNX): open format representing computational graphs independently of source framework
  - `11.24.2` Exporting PyTorch models to ONNX: tracing (`torch.onnx.export`) vs script-based export, dynamic axes handling
  - `11.24.3` Graph optimization with TensorRT: layer fusion (fusing Conv+BatchNorm+ReLU into single kernel), kernel auto-tuning for specific GPU
  - `11.24.4` Quantization paradigms: Post-Training Quantization (PTQ) vs Quantization-Aware Training (QAT)
  - `11.24.5` INT8 quantization mechanics: symmetric vs asymmetric quantization, calibration datasets, and computing scaling factors
  - `11.24.6` FP8 and 4-bit quantization (AWQ, GPTQ): compressing large language models for high-throughput edge and data-center inference
- **Key Failure Modes & Edge Cases**: Exporting ONNX models with fixed batch sizes and sequence lengths, causing runtime failures when serving variable-length production requests.
- **Verification & Mastery Check**: Export a PyTorch transformer model to ONNX, optimize with TensorRT/ONNX Runtime, and measure $3\times$ latency reduction at identical accuracy.
- **Project Application**: ModelPulse: ONNX model optimization and quantization pipeline.', '{"solution.py": "# Phase 11 // Lesson 11.24: Model Serialization & Optimization: ONNX, TensorRT & Quantization\n\ndef solve():\n    \"\"\"\n    Verification: Export a PyTorch transformer model to ONNX, optimize with TensorRT/ONNX Runtime, and measure $3\\time\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.24", "subtopics_count": 6, "verification_criteria": "Export a PyTorch transformer model to ONNX, optimize with TensorRT/ONNX Runtime, and measure $3\\times$ latency reduction at identical accuracy.", "subtopics": ["11.24.1 Open Neural Network Exchange (ONNX): open format representing computational graphs independently of source framework", "11.24.2 Exporting PyTorch models to ONNX: tracing (`torch.onnx.export`) vs script-based export, dynamic axes handling", "11.24.3 Graph optimization with TensorRT: layer fusion (fusing Conv+BatchNorm+ReLU into single kernel), kernel auto-tuning for specific GPU", "11.24.4 Quantization paradigms: Post-Training Quantization (PTQ) vs Quantization-Aware Training (QAT)", "11.24.5 INT8 quantization mechanics: symmetric vs asymmetric quantization, calibration datasets, and computing scaling factors", "11.24.6 FP8 and 4-bit quantization (AWQ, GPTQ): compressing large language models for high-throughput edge and data-center inference"]}'::jsonb, '["Explain how this implementation prevents: Exporting ONNX models with fixed batch sizes and sequence lengths, causing runtime failures when serving variable-length", "How does Model Serialization & Optimization: ONNX, TensorRT & Quantization scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-11-25', 'phase-11-lesson-25-deployment-strategies-i-canary-releases-p', 'module-12', 25, 'Lesson 12.25: Deployment Strategies I: Canary Releases & Progressive Delivery with Flagger', 'Prerequisites: Phase 7, Lesson 11.22', 'Prerequisites: Phase 7, Lesson 11.22 | Subtopics: 6 items', 'Systems project application', 320, 12, 2810.0, 1250.0, '# Lesson 11.25: Deployment Strategies I: Canary Releases & Progressive Delivery with Flagger

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 7, Lesson 11.22
- **Subtopics**:
  - `11.25.1` Canary deployment principles: routing a small percentage of real production traffic (e.g. 5%) to the new version before full rollout
  - `11.25.2` Progressive Delivery with Flagger: automating progressive canary promotions on Kubernetes using Envoy, Istio, or NGINX Ingress
  - `11.25.3` Analysis metrics: automated validation of canary health using Prometheus metrics (HTTP 5xx error rate, p99 latency thresholds)
  - `11.25.4` Canary promotion workflow: shifting traffic $5\% \to 10\% \to 25\% \to 50\% \to 100\%$ over 15-minute analysis intervals
  - `11.25.5` Automated rollbacks: immediately routing 100% traffic back to stable primary if canary error rate exceeds 1% during analysis
  - `11.25.6` Alerting integration: sending real-time Slack/PagerDuty notifications during canary promotion stages and automated rollbacks
- **Key Failure Modes & Edge Cases**: Promoting canary deployments based on zero errors during low-traffic midnight hours, missing bugs that only manifest under peak load.
- **Verification & Mastery Check**: Configure a Flagger canary deployment on Kubernetes with automated Prometheus metric analysis and verified self-healing rollback.
- **Project Application**: ModelPulse: Progressive canary deployment infrastructure.', '{"solution.py": "# Phase 11 // Lesson 11.25: Deployment Strategies I: Canary Releases & Progressive Delivery with Flagger\n\ndef solve():\n    \"\"\"\n    Verification: Configure a Flagger canary deployment on Kubernetes with automated Prometheus metric analysis and ve\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "11.25", "subtopics_count": 6, "verification_criteria": "Configure a Flagger canary deployment on Kubernetes with automated Prometheus metric analysis and verified self-healing rollback.", "subtopics": ["11.25.1 Canary deployment principles: routing a small percentage of real production traffic (e.g. 5%) to the new version before full rollout", "11.25.2 Progressive Delivery with Flagger: automating progressive canary promotions on Kubernetes using Envoy, Istio, or NGINX Ingress", "11.25.3 Analysis metrics: automated validation of canary health using Prometheus metrics (HTTP 5xx error rate, p99 latency thresholds)", "11.25.4 Canary promotion workflow: shifting traffic $5\\% \\to 10\\% \\to 25\\% \\to 50\\% \\to 100\\%$ over 15-minute analysis intervals", "11.25.5 Automated rollbacks: immediately routing 100% traffic back to stable primary if canary error rate exceeds 1% during analysis", "11.25.6 Alerting integration: sending real-time Slack/PagerDuty notifications during canary promotion stages and automated rollbacks"]}'::jsonb, '["Explain how this implementation prevents: Promoting canary deployments based on zero errors during low-traffic midnight hours, missing bugs that only manifest und", "How does Deployment Strategies I: Canary Releases & Progressive Delivery with Flagger scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-1', 'phase-12-lesson-01-cognitive-agent-architectures-beyond-simp', 'module-13', 1, 'Lesson 13.1: Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains', 'Prerequisites: Phase 10, Lesson 10.2', 'Prerequisites: Phase 10, Lesson 10.2 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 50.0, '# Lesson 12.1: Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 10, Lesson 10.2
- **Subtopics**:
  - `12.1.1` The spectrum of autonomy: deterministic scripts vs prompt chains vs autonomous agents with dynamic branching
  - `12.1.2` Core components of an agent: Brain (LLM), Memory (short-term working state & long-term episodic memory), Tools, and Planning
  - `12.1.3` The Sense-Plan-Act cycle: perceiving environment feedback, updating internal beliefs, formulating plans, and executing actions
  - `12.1.4` Bounded rationality in LLM agents: token horizon limits, stochastic decision making, and cascading failure propagation
  - `12.1.5` Deterministic guardrails on non-deterministic models: constraining agent state transitions with state machines
  - `12.1.6` Architecture overview: designing agent workflows that guarantee business logic invariants while leveraging model flexibility
- **Key Failure Modes & Edge Cases**: Granting an un-constrained agent open loop execution without state boundaries, burning thousands of dollars in infinite tool loops.
- **Verification & Mastery Check**: Draft an architectural state chart comparing linear prompt chaining vs dynamic cyclic agent state execution.
- **Project Application**: CodeAgent: Agent architectural specification.', '{"solution.py": "# Phase 12 // Lesson 12.1: Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains\n\ndef solve():\n    \"\"\"\n    Verification: Draft an architectural state chart comparing linear prompt chaining vs dynamic cyclic agent state ex\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.1", "subtopics_count": 6, "verification_criteria": "Draft an architectural state chart comparing linear prompt chaining vs dynamic cyclic agent state execution.", "subtopics": ["12.1.1 The spectrum of autonomy: deterministic scripts vs prompt chains vs autonomous agents with dynamic branching", "12.1.2 Core components of an agent: Brain (LLM), Memory (short-term working state & long-term episodic memory), Tools, and Planning", "12.1.3 The Sense-Plan-Act cycle: perceiving environment feedback, updating internal beliefs, formulating plans, and executing actions", "12.1.4 Bounded rationality in LLM agents: token horizon limits, stochastic decision making, and cascading failure propagation", "12.1.5 Deterministic guardrails on non-deterministic models: constraining agent state transitions with state machines", "12.1.6 Architecture overview: designing agent workflows that guarantee business logic invariants while leveraging model flexibility"]}'::jsonb, '["Explain how this implementation prevents: Granting an un-constrained agent open loop execution without state boundaries, burning thousands of dollars in infinite ", "How does Cognitive Agent Architectures: Beyond Simple RAG & Prompt Chains scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-2', 'phase-12-lesson-02-reasoning-action-paradigms-react-plan-and', 'module-13', 2, 'Lesson 13.2: Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion', 'Prerequisites: Lesson 12.1', 'Prerequisites: Lesson 12.1 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 100.0, '# Lesson 12.2: Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 12.1
- **Subtopics**:
  - `12.2.1` ReAct (Yao et al.): interleaving Reasoning (''Thought''), Action (''Tool Call''), and Observation (''Environment Feedback'')
  - `12.2.2` Failure modes of pure ReAct: local greedy planning, losing track of high-level goals, and cycling between similar actions
  - `12.2.3` Plan-and-Solve (Wang et al.): generating an explicit multi-step plan upfront, then executing sub-tasks systematically
  - `12.2.4` Reflexion (Shinn et al.): verbal self-reflection, evaluating task outcomes, writing critique into episodic memory, and retrying
  - `12.2.5` Tree-of-Thoughts (ToT) (Yao et al.): exploring multiple reasoning paths concurrently with backtracking and lookahead evaluation
  - `12.2.6` Selecting the right architecture: matching task complexity to cognitive overhead and latency budgets
- **Key Failure Modes & Edge Cases**: Using pure ReAct on complex 20-step software engineering tasks, causing the agent to get stuck in myopic 3-step loops.
- **Verification & Mastery Check**: Implement a Reflexion agent harness that critiques its own failed Python code executions and succeeds on the second attempt.
- **Project Application**: CodeAgent: Cognitive loop controller.', '{"solution.py": "# Phase 12 // Lesson 12.2: Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Reflexion agent harness that critiques its own failed Python code executions and succeed\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.2", "subtopics_count": 6, "verification_criteria": "Implement a Reflexion agent harness that critiques its own failed Python code executions and succeeds on the second attempt.", "subtopics": ["12.2.1 ReAct (Yao et al.): interleaving Reasoning (''Thought''), Action (''Tool Call''), and Observation (''Environment Feedback'')", "12.2.2 Failure modes of pure ReAct: local greedy planning, losing track of high-level goals, and cycling between similar actions", "12.2.3 Plan-and-Solve (Wang et al.): generating an explicit multi-step plan upfront, then executing sub-tasks systematically", "12.2.4 Reflexion (Shinn et al.): verbal self-reflection, evaluating task outcomes, writing critique into episodic memory, and retrying", "12.2.5 Tree-of-Thoughts (ToT) (Yao et al.): exploring multiple reasoning paths concurrently with backtracking and lookahead evaluation", "12.2.6 Selecting the right architecture: matching task complexity to cognitive overhead and latency budgets"]}'::jsonb, '["Explain how this implementation prevents: Using pure ReAct on complex 20-step software engineering tasks, causing the agent to get stuck in myopic 3-step loops.", "How does Reasoning & Action Paradigms: ReAct, Plan-and-Solve & Reflexion scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-3', 'phase-12-lesson-03-tool-engineering-i-dynamic-schema-generat', 'module-13', 3, 'Lesson 13.3: Tool Engineering I: Dynamic Schema Generation & Pydantic Validation', 'Prerequisites: Phase 1, Phase 10', 'Prerequisites: Phase 1, Phase 10 | Subtopics: 6 items', 'Systems project application', 340, 13, 3000.0, 150.0, '# Lesson 12.3: Tool Engineering I: Dynamic Schema Generation & Pydantic Validation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Phase 10
- **Subtopics**:
  - `12.3.1` Tools as typed RPC interfaces: exposing functions, APIs, and databases to LLMs via JSON Schema definitions
  - `12.3.2` Writing clear, unambiguous tool descriptions: specifying parameter types, required fields, constraints, and return schemas
  - `12.3.3` Pydantic schema generation: using `TypeAdapter` and Pydantic models to automatically generate clean OpenAPI/JSON schemas
  - `12.3.4` Input validation and sanitization: intercepting invalid LLM tool arguments before execution and returning structured errors
  - `12.3.5` Handling missing arguments: implementing conversational clarification loops when required tool parameters are omitted
  - `12.3.6` Security threat modeling for tools: preventing privilege escalation, SQL injection, and command injection via tool parameters
- **Key Failure Modes & Edge Cases**: Providing vague tool descriptions (''executes stuff''), causing the LLM to hallucinate invalid parameter names and argument types.
- **Verification & Mastery Check**: Build a tool registry library in Python that dynamically exports Pydantic-validated callable tools to OpenAI and Anthropic formats.
- **Project Application**: CodeAgent: Core tool registry engine.', '{"solution.py": "# Phase 12 // Lesson 12.3: Tool Engineering I: Dynamic Schema Generation & Pydantic Validation\n\ndef solve():\n    \"\"\"\n    Verification: Build a tool registry library in Python that dynamically exports Pydantic-validated callable tools t\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.3", "subtopics_count": 6, "verification_criteria": "Build a tool registry library in Python that dynamically exports Pydantic-validated callable tools to OpenAI and Anthropic formats.", "subtopics": ["12.3.1 Tools as typed RPC interfaces: exposing functions, APIs, and databases to LLMs via JSON Schema definitions", "12.3.2 Writing clear, unambiguous tool descriptions: specifying parameter types, required fields, constraints, and return schemas", "12.3.3 Pydantic schema generation: using `TypeAdapter` and Pydantic models to automatically generate clean OpenAPI/JSON schemas", "12.3.4 Input validation and sanitization: intercepting invalid LLM tool arguments before execution and returning structured errors", "12.3.5 Handling missing arguments: implementing conversational clarification loops when required tool parameters are omitted", "12.3.6 Security threat modeling for tools: preventing privilege escalation, SQL injection, and command injection via tool parameters"]}'::jsonb, '["Explain how this implementation prevents: Providing vague tool descriptions (''executes stuff''), causing the LLM to hallucinate invalid parameter names and argumen", "How does Tool Engineering I: Dynamic Schema Generation & Pydantic Validation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-4', 'phase-12-lesson-04-tool-engineering-ii-idempotency-timeouts-', 'module-13', 4, 'Lesson 13.4: Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery', 'Prerequisites: Phase 4, Lesson 12.3', 'Prerequisites: Phase 4, Lesson 12.3 | Subtopics: 6 items', 'Systems project application', 340, 13, 3060.0, 200.0, '# Lesson 12.4: Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 12.3
- **Subtopics**:
  - `12.4.1` The unreliability of external environments: handling network timeouts, API rate limits, and non-deterministic tool failures
  - `12.4.2` Idempotent tool design: ensuring that duplicate tool executions do not produce unintended side effects (e.g. double charging)
  - `12.4.3` Structured error returns: why raising Python exceptions crashes agents; formatting errors as informative feedback strings
  - `12.4.4` Designing actionable error messages: providing the LLM with exact guidance on how to fix invalid inputs upon failure
  - `12.4.5` Execution timeouts: wrapping tool executions with strict `asyncio.timeout()` boundaries to prevent hung external processes
  - `12.4.6` Tool output truncation: summarizing massive tool return payloads (e.g. 50MB file reads) to prevent blowing the context window
- **Key Failure Modes & Edge Cases**: Allowing an unhandled tool exception to bubble up and crash the entire agent runtime, losing all conversational session state.
- **Verification & Mastery Check**: Implement a resilient tool execution wrapper supporting timeouts, exponential retries, and informative error formatting for LLMs.
- **Project Application**: CodeAgent: Resilient tool execution pipeline.', '{"solution.py": "# Phase 12 // Lesson 12.4: Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery\n\ndef solve():\n    \"\"\"\n    Verification: Implement a resilient tool execution wrapper supporting timeouts, exponential retries, and informati\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.4", "subtopics_count": 6, "verification_criteria": "Implement a resilient tool execution wrapper supporting timeouts, exponential retries, and informative error formatting for LLMs.", "subtopics": ["12.4.1 The unreliability of external environments: handling network timeouts, API rate limits, and non-deterministic tool failures", "12.4.2 Idempotent tool design: ensuring that duplicate tool executions do not produce unintended side effects (e.g. double charging)", "12.4.3 Structured error returns: why raising Python exceptions crashes agents; formatting errors as informative feedback strings", "12.4.4 Designing actionable error messages: providing the LLM with exact guidance on how to fix invalid inputs upon failure", "12.4.5 Execution timeouts: wrapping tool executions with strict `asyncio.timeout()` boundaries to prevent hung external processes", "12.4.6 Tool output truncation: summarizing massive tool return payloads (e.g. 50MB file reads) to prevent blowing the context window"]}'::jsonb, '["Explain how this implementation prevents: Allowing an unhandled tool exception to bubble up and crash the entire agent runtime, losing all conversational session ", "How does Tool Engineering II: Idempotency, Timeouts & Structured Error Recovery scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-12-5', 'phase-12-lesson-05-agent-memory-systems-working-memory-episo', 'module-13', 5, 'Lesson 13.5: Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory', 'Prerequisites: Phase 10, Lesson 12.1', 'Prerequisites: Phase 10, Lesson 12.1 | Subtopics: 6 items', 'Systems project application', 340, 13, 3120.0, 250.0, '# Lesson 12.5: Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 10, Lesson 12.1
- **Subtopics**:
  - `12.5.1` Taxonomy of agent memory: Working Memory (active context), Episodic Memory (past task experiences), Semantic Memory (knowledge)
  - `12.5.2` Managing Working Memory: rolling window message history, summarization compression, and token budget management
  - `12.5.3` Episodic Memory with Vector Stores: embedding past execution trajectories, indexing task outcomes, and retrieving relevant past solutions
  - `12.5.4` Entity Memory: maintaining a structured JSON knowledge graph of extracted user preferences, project configurations, and facts
  - `12.5.5` Memory consolidation: background tasks that distill daily conversation logs into concise long-term user profiles
  - `12.5.6` Privacy and memory purging: implementing GDPR-compliant memory forgetfulness APIs to delete user history on demand
- **Key Failure Modes & Edge Cases**: Unbounded message history growth causing context window overflow and astronomical API token costs on long-running tasks.
- **Verification & Mastery Check**: Build a hybrid agent memory system combining in-memory message history with vector-indexed episodic retrieval of past task logs.
- **Project Application**: CodeAgent: Multi-tiered agent memory architecture.', '{"solution.py": "# Phase 12 // Lesson 12.5: Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory\n\ndef solve():\n    \"\"\"\n    Verification: Build a hybrid agent memory system combining in-memory message history with vector-indexed episodic \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "12.5", "subtopics_count": 6, "verification_criteria": "Build a hybrid agent memory system combining in-memory message history with vector-indexed episodic retrieval of past task logs.", "subtopics": ["12.5.1 Taxonomy of agent memory: Working Memory (active context), Episodic Memory (past task experiences), Semantic Memory (knowledge)", "12.5.2 Managing Working Memory: rolling window message history, summarization compression, and token budget management", "12.5.3 Episodic Memory with Vector Stores: embedding past execution trajectories, indexing task outcomes, and retrieving relevant past solutions", "12.5.4 Entity Memory: maintaining a structured JSON knowledge graph of extracted user preferences, project configurations, and facts", "12.5.5 Memory consolidation: background tasks that distill daily conversation logs into concise long-term user profiles", "12.5.6 Privacy and memory purging: implementing GDPR-compliant memory forgetfulness APIs to delete user history on demand"]}'::jsonb, '["Explain how this implementation prevents: Unbounded message history growth causing context window overflow and astronomical API token costs on long-running tasks.", "How does Agent Memory Systems: Working Memory, Episodic Memory & Semantic Memory scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
