INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-5-1', 'phase-05-lesson-01-restful-architecture-resource-modeling-ve', 'module-7', 1, 'Lesson 7.1: RESTful Architecture: Resource Modeling & Verbs', 'Prerequisites: Phase 4 (Lesson 4.29)', 'Prerequisites: Phase 4 (Lesson 4.29) | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 50.0, '# Lesson 5.1: RESTful Architecture: Resource Modeling & Verbs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4 (Lesson 4.29)
- **Subtopics**:
  - `5.1.1` Resource-oriented URI design: resources as plural nouns (`/api/v1/projects/{id}/artifacts`).
  - `5.1.2` HTTP verb semantic contracts: `GET` (safe, idempotent), `POST` (non-idempotent), `PUT` (idempotent replace), `PATCH` (partial update), `DELETE`.
  - `5.1.3` Nesting resources vs flat resource paths: trade-offs in sub-resource modeling.
  - `5.1.4` Hypermedia and HATEOAS: dynamic discoverability of API action links.
- **Key Failure Modes & Edge Cases**: Exposing RPC verbs in REST paths (e.g., `POST /api/v1/deleteUser`), violating HTTP caching and semantic specifications.
- **Verification & Mastery Check**: Design a RESTful API specification for a multi-tenant project management platform adhering strictly to RFC specifications.
- **Project Application**: AuthForge and TenantIQ API surfaces.', '{"solution.py": "# Phase 5 // Lesson 5.1: RESTful Architecture: Resource Modeling & Verbs\n\ndef solve():\n    \"\"\"\n    Verification: Design a RESTful API specification for a multi-tenant project management platform adhering strictly \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.1", "subtopics_count": 4, "verification_criteria": "Design a RESTful API specification for a multi-tenant project management platform adhering strictly to RFC specifications.", "subtopics": ["5.1.1 Resource-oriented URI design: resources as plural nouns (`/api/v1/projects/{id}/artifacts`).", "5.1.2 HTTP verb semantic contracts: `GET` (safe, idempotent), `POST` (non-idempotent), `PUT` (idempotent replace), `PATCH` (partial update), `DELETE`.", "5.1.3 Nesting resources vs flat resource paths: trade-offs in sub-resource modeling.", "5.1.4 Hypermedia and HATEOAS: dynamic discoverability of API action links."]}'::jsonb, '["Explain how this implementation prevents: Exposing RPC verbs in REST paths (e.g., `POST /api/v1/deleteUser`), violating HTTP caching and semantic specifications.", "How does RESTful Architecture: Resource Modeling & Verbs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-2', 'phase-05-lesson-02-http-status-codes-precision-rfc-semantics', 'module-7', 2, 'Lesson 7.2: HTTP Status Codes Precision & RFC Semantics', 'Prerequisites: Lesson 5.1', 'Prerequisites: Lesson 5.1 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 100.0, '# Lesson 5.2: HTTP Status Codes Precision & RFC Semantics

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.1
- **Subtopics**:
  - `5.2.1` 2xx Success: 200 OK, 201 Created (with `Location` header), 204 No Content.
  - `5.2.2` 4xx Client Errors: 400 Bad Request, 401 Unauthorized (unauthenticated), 403 Forbidden (authenticated, unauthorized), 404 Not Found, 409 Conflict, 422 Unprocessable Entity, 429 Too Many Requests.
  - `5.2.3` 5xx Server Errors: 500 Internal Error, 502 Bad Gateway, 503 Service Unavailable, 504 Gateway Timeout.
  - `5.2.4` Error response standards: RFC 7807 Problem Details for HTTP APIs (`type`, `title`, `status`, `detail`, `instance`).
- **Key Failure Modes & Edge Cases**: Returning `200 OK` with `{"error": true}` in the JSON payload, breaking client error handling and upstream HTTP proxies.
- **Verification & Mastery Check**: Implement custom error handlers in FastAPI returning standardized RFC 7807 problem detail payloads.
- **Project Application**: AuthForge: API error handling.', '{"solution.py": "# Phase 5 // Lesson 5.2: HTTP Status Codes Precision & RFC Semantics\n\ndef solve():\n    \"\"\"\n    Verification: Implement custom error handlers in FastAPI returning standardized RFC 7807 problem detail payloads.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.2", "subtopics_count": 4, "verification_criteria": "Implement custom error handlers in FastAPI returning standardized RFC 7807 problem detail payloads.", "subtopics": ["5.2.1 2xx Success: 200 OK, 201 Created (with `Location` header), 204 No Content.", "5.2.2 4xx Client Errors: 400 Bad Request, 401 Unauthorized (unauthenticated), 403 Forbidden (authenticated, unauthorized), 404 Not Found, 409 Conflict, 422 Unprocessable Entity, 429 Too Many Requests.", "5.2.3 5xx Server Errors: 500 Internal Error, 502 Bad Gateway, 503 Service Unavailable, 504 Gateway Timeout.", "5.2.4 Error response standards: RFC 7807 Problem Details for HTTP APIs (`type`, `title`, `status`, `detail`, `instance`)."]}'::jsonb, '["Explain how this implementation prevents: Returning `200 OK` with `{\"error\": true}` in the JSON payload, breaking client error handling and upstream HTTP proxies.", "How does HTTP Status Codes Precision & RFC Semantics scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-3', 'phase-05-lesson-03-safe-retries-idempotency-key-architecture', 'module-7', 3, 'Lesson 7.3: Safe Retries & Idempotency Key Architecture', 'Prerequisites: Lesson 5.1', 'Prerequisites: Lesson 5.1 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 150.0, '# Lesson 5.3: Safe Retries & Idempotency Key Architecture

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.1
- **Subtopics**:
  - `5.3.1` The network retry hazard: network timeout on `POST` requests causing duplicate credit card charges or order creation.
  - `5.3.2` Idempotency Key mechanism: client transmits UUID in `Idempotency-Key` header.
  - `5.3.3` Server-side idempotency state machine in Redis: Pending, Processing, Completed; storing response payload with TTL.
  - `5.3.4` Concurrency handling: locking idempotency keys to reject simultaneous duplicate requests with `409 Conflict`.
- **Key Failure Modes & Edge Cases**: Double-charging customers during network blips due to non-idempotent order submission endpoints.
- **Verification & Mastery Check**: Build an Idempotency Middleware in FastAPI using Redis that guarantees zero duplicate executions for repeated identical requests.
- **Project Application**: AuthForge and TenantIQ: Stripe payment and mutation endpoints.', '{"solution.py": "# Phase 5 // Lesson 5.3: Safe Retries & Idempotency Key Architecture\n\ndef solve():\n    \"\"\"\n    Verification: Build an Idempotency Middleware in FastAPI using Redis that guarantees zero duplicate executions for\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.3", "subtopics_count": 4, "verification_criteria": "Build an Idempotency Middleware in FastAPI using Redis that guarantees zero duplicate executions for repeated identical requests.", "subtopics": ["5.3.1 The network retry hazard: network timeout on `POST` requests causing duplicate credit card charges or order creation.", "5.3.2 Idempotency Key mechanism: client transmits UUID in `Idempotency-Key` header.", "5.3.3 Server-side idempotency state machine in Redis: Pending, Processing, Completed; storing response payload with TTL.", "5.3.4 Concurrency handling: locking idempotency keys to reject simultaneous duplicate requests with `409 Conflict`."]}'::jsonb, '["Explain how this implementation prevents: Double-charging customers during network blips due to non-idempotent order submission endpoints.", "How does Safe Retries & Idempotency Key Architecture scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-4', 'phase-05-lesson-04-pagination-architectures-offset-vs-keyset', 'module-7', 4, 'Lesson 7.4: Pagination Architectures: Offset vs Keyset Cursors', 'Prerequisites: Lesson 5.1, Phase 3 (Lesson 3.26)', 'Prerequisites: Lesson 5.1, Phase 3 (Lesson 3.26) | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 200.0, '# Lesson 5.4: Pagination Architectures: Offset vs Keyset Cursors

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.1, Phase 3 (Lesson 3.26)
- **Subtopics**:
  - `5.4.1` Offset-based pagination: `LIMIT 20 OFFSET 1000`; $O(n)$ database scan overhead; offset drift (missing or duplicate rows during insertions).
  - `5.4.2` Keyset / Cursor-based pagination: `WHERE (created_at, id) < (:cursor_time, :cursor_id) ORDER BY created_at DESC, id DESC LIMIT 20`.
  - `5.4.3` Cursor encoding: base64 encoding opaque composite cursor strings.
  - `5.4.4` Performance comparison: $O(1)$ indexed seek vs $O(n)$ full scan across deep pagination pages.
- **Key Failure Modes & Edge Cases**: Database CPU saturation caused by web crawlers scraping deep pages on offset-paginated tables with 10M rows.
- **Verification & Mastery Check**: Implement keyset cursor pagination on a high-throughput table, verify constant-time query latency across deep offsets.
- **Project Application**: TenantIQ: Activity feed pagination.', '{"solution.py": "# Phase 5 // Lesson 5.4: Pagination Architectures: Offset vs Keyset Cursors\n\ndef solve():\n    \"\"\"\n    Verification: Implement keyset cursor pagination on a high-throughput table, verify constant-time query latency ac\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.4", "subtopics_count": 4, "verification_criteria": "Implement keyset cursor pagination on a high-throughput table, verify constant-time query latency across deep offsets.", "subtopics": ["5.4.1 Offset-based pagination: `LIMIT 20 OFFSET 1000`; $O(n)$ database scan overhead; offset drift (missing or duplicate rows during insertions).", "5.4.2 Keyset / Cursor-based pagination: `WHERE (created_at, id) < (:cursor_time, :cursor_id) ORDER BY created_at DESC, id DESC LIMIT 20`.", "5.4.3 Cursor encoding: base64 encoding opaque composite cursor strings.", "5.4.4 Performance comparison: $O(1)$ indexed seek vs $O(n)$ full scan across deep pagination pages."]}'::jsonb, '["Explain how this implementation prevents: Database CPU saturation caused by web crawlers scraping deep pages on offset-paginated tables with 10M rows.", "How does Pagination Architectures: Offset vs Keyset Cursors scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-5', 'phase-05-lesson-05-api-versioning-methodologies-deprecation-', 'module-7', 5, 'Lesson 7.5: API Versioning Methodologies & Deprecation Policies', 'Prerequisites: Lesson 5.1', 'Prerequisites: Lesson 5.1 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 250.0, '# Lesson 5.5: API Versioning Methodologies & Deprecation Policies

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.1
- **Subtopics**:
  - `5.5.1` URI Path versioning (`/v1/users`): clarity, simple caching, routing isolation.
  - `5.5.2` Header versioning: `Accept: application/vnd.app.v1+json`; clean URIs, client complexity.
  - `5.5.3` Query parameter versioning: `/users?version=1`.
  - `5.5.4` Managing backward compatibility: additive schema updates, Sunset headers (`Sunset: Wed, 11 Nov 2026 00:00:00 GMT`), graceful migration windows.
- **Key Failure Modes & Edge Cases**: Breaking mobile client applications by removing or modifying fields on active API versions without backward compatibility.
- **Verification & Mastery Check**: Design and implement a versioned API supporting both v1 and v2 simultaneously with automated deprecation warning headers.
- **Project Application**: AuthForge and TenantIQ API versioning.', '{"solution.py": "# Phase 5 // Lesson 5.5: API Versioning Methodologies & Deprecation Policies\n\ndef solve():\n    \"\"\"\n    Verification: Design and implement a versioned API supporting both v1 and v2 simultaneously with automated depreca\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.5", "subtopics_count": 4, "verification_criteria": "Design and implement a versioned API supporting both v1 and v2 simultaneously with automated deprecation warning headers.", "subtopics": ["5.5.1 URI Path versioning (`/v1/users`): clarity, simple caching, routing isolation.", "5.5.2 Header versioning: `Accept: application/vnd.app.v1+json`; clean URIs, client complexity.", "5.5.3 Query parameter versioning: `/users?version=1`.", "5.5.4 Managing backward compatibility: additive schema updates, Sunset headers (`Sunset: Wed, 11 Nov 2026 00:00:00 GMT`), graceful migration windows."]}'::jsonb, '["Explain how this implementation prevents: Breaking mobile client applications by removing or modifying fields on active API versions without backward compatibilit", "How does API Versioning Methodologies & Deprecation Policies scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-6', 'phase-05-lesson-06-fastapi-architecture-uvicorn-the-asgi-spe', 'module-7', 6, 'Lesson 7.6: FastAPI Architecture, Uvicorn, & The ASGI Specification', 'Prerequisites: Phase 1 (Lesson 1.32), Phase 4 (Lesson 4.23)', 'Prerequisites: Phase 1 (Lesson 1.32), Phase 4 (Lesson 4.23) | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 300.0, '# Lesson 5.6: FastAPI Architecture, Uvicorn, & The ASGI Specification

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.32), Phase 4 (Lesson 4.23)
- **Subtopics**:
  - `5.6.1` Asynchronous Server Gateway Interface (ASGI): scope dictionary, receive callable, send callable.
  - `5.6.2` Uvicorn server: libuv/asyncio-backed ASGI HTTP server.
  - `5.6.3` Starlette core: routing, middleware stack, request/response cycle.
  - `5.6.4` FastAPI enhancements: automatic OpenAPI documentation (`/docs`), Swagger UI, ReDoc, and validation integration.
- **Key Failure Modes & Edge Cases**: Running CPU-intensive tasks inside FastAPI async route handlers, blocking the single event loop thread for all requests.
- **Verification & Mastery Check**: Write a raw ASGI application callable from scratch without frameworks, and run it directly with Uvicorn.
- **Project Application**: AuthForge: Core web service engine.', '{"solution.py": "# Phase 5 // Lesson 5.6: FastAPI Architecture, Uvicorn, & The ASGI Specification\n\ndef solve():\n    \"\"\"\n    Verification: Write a raw ASGI application callable from scratch without frameworks, and run it directly with Uvic\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.6", "subtopics_count": 4, "verification_criteria": "Write a raw ASGI application callable from scratch without frameworks, and run it directly with Uvicorn.", "subtopics": ["5.6.1 Asynchronous Server Gateway Interface (ASGI): scope dictionary, receive callable, send callable.", "5.6.2 Uvicorn server: libuv/asyncio-backed ASGI HTTP server.", "5.6.3 Starlette core: routing, middleware stack, request/response cycle.", "5.6.4 FastAPI enhancements: automatic OpenAPI documentation (`/docs`), Swagger UI, ReDoc, and validation integration."]}'::jsonb, '["Explain how this implementation prevents: Running CPU-intensive tasks inside FastAPI async route handlers, blocking the single event loop thread for all requests.", "How does FastAPI Architecture, Uvicorn, & The ASGI Specification scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-7', 'phase-05-lesson-07-pydantic-v2-internals-high-speed-schema-v', 'module-7', 7, 'Lesson 7.7: Pydantic v2 Internals & High-Speed Schema Validation', 'Prerequisites: Phase 1 (Lesson 1.4)', 'Prerequisites: Phase 1 (Lesson 1.4) | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 350.0, '# Lesson 5.7: Pydantic v2 Internals & High-Speed Schema Validation

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.4)
- **Subtopics**:
  - `5.7.1` Pydantic v2 core: `pydantic-core` C/Rust validation engine delivering 5x–20x speedups over v1.
  - `5.7.2` Data validation with `BaseModel`: field types, constraints (`Field(gt=0, max_length=100)`), custom regex.
  - `5.7.3` Field validators (`@field_validator`) vs Model validators (`@model_validator(mode=''before'')`).
  - `5.7.4` Serialization: `model_dump()`, `model_dump_json()`, excluding unset fields (`exclude_unset=True`).
- **Key Failure Modes & Edge Cases**: Using Pydantic models for high-throughput batch transformations without understanding serialization overhead.
- **Verification & Mastery Check**: Define strict nested Pydantic models validating complex API payloads with cross-field conditional validation.
- **Project Application**: AuthForge: Request/Response validation schemas.', '{"solution.py": "# Phase 5 // Lesson 5.7: Pydantic v2 Internals & High-Speed Schema Validation\n\ndef solve():\n    \"\"\"\n    Verification: Define strict nested Pydantic models validating complex API payloads with cross-field conditional va\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.7", "subtopics_count": 4, "verification_criteria": "Define strict nested Pydantic models validating complex API payloads with cross-field conditional validation.", "subtopics": ["5.7.1 Pydantic v2 core: `pydantic-core` C/Rust validation engine delivering 5x\u201320x speedups over v1.", "5.7.2 Data validation with `BaseModel`: field types, constraints (`Field(gt=0, max_length=100)`), custom regex.", "5.7.3 Field validators (`@field_validator`) vs Model validators (`@model_validator(mode=''before'')`).", "5.7.4 Serialization: `model_dump()`, `model_dump_json()`, excluding unset fields (`exclude_unset=True`)."]}'::jsonb, '["Explain how this implementation prevents: Using Pydantic models for high-throughput batch transformations without understanding serialization overhead.", "How does Pydantic v2 Internals & High-Speed Schema Validation scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-8', 'phase-05-lesson-08-fastapi-dependency-injection-hierarchy-li', 'module-7', 8, 'Lesson 7.8: FastAPI Dependency Injection Hierarchy & Lifespan Hooks', 'Prerequisites: Phase 1 (Lesson 1.50), Lesson 5.6', 'Prerequisites: Phase 1 (Lesson 1.50), Lesson 5.6 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 400.0, '# Lesson 5.8: FastAPI Dependency Injection Hierarchy & Lifespan Hooks

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.50), Lesson 5.6
- **Subtopics**:
  - `5.8.1` FastAPI Dependency Injection: `fastapi.Depends`, sub-dependencies, hierarchical dependency resolution.
  - `5.8.2` Yield dependencies: resource provisioning and cleanup (database sessions, transaction scopes).
  - `5.8.3` Authentication dependencies: extracting Bearer tokens, decoding claims, injecting `CurrentUser` models.
  - `5.8.4` Application Lifespan: `lifespan(app)` context manager for managing global connection pools on startup/shutdown.
- **Key Failure Modes & Edge Cases**: Opening database connections inside individual route dependencies without pooling or cleanup yields, leaking connections.
- **Verification & Mastery Check**: Build a multi-level dependency tree that validates API keys, checks database tenancy, and injects a scoped DB session.
- **Project Application**: AuthForge: Route security dependencies.', '{"solution.py": "# Phase 5 // Lesson 5.8: FastAPI Dependency Injection Hierarchy & Lifespan Hooks\n\ndef solve():\n    \"\"\"\n    Verification: Build a multi-level dependency tree that validates API keys, checks database tenancy, and injects a \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.8", "subtopics_count": 4, "verification_criteria": "Build a multi-level dependency tree that validates API keys, checks database tenancy, and injects a scoped DB session.", "subtopics": ["5.8.1 FastAPI Dependency Injection: `fastapi.Depends`, sub-dependencies, hierarchical dependency resolution.", "5.8.2 Yield dependencies: resource provisioning and cleanup (database sessions, transaction scopes).", "5.8.3 Authentication dependencies: extracting Bearer tokens, decoding claims, injecting `CurrentUser` models.", "5.8.4 Application Lifespan: `lifespan(app)` context manager for managing global connection pools on startup/shutdown."]}'::jsonb, '["Explain how this implementation prevents: Opening database connections inside individual route dependencies without pooling or cleanup yields, leaking connections", "How does FastAPI Dependency Injection Hierarchy & Lifespan Hooks scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-9', 'phase-05-lesson-09-relational-algebra-normalization-1nf-2nf-', 'module-7', 9, 'Lesson 7.9: Relational Algebra & Normalization: 1NF, 2NF, 3NF, BCNF', 'Prerequisites: Phase 2 (Lesson 2.5)', 'Prerequisites: Phase 2 (Lesson 2.5) | Subtopics: 5 items', 'Systems project application', 200, 6, 1250.0, 450.0, '# Lesson 5.9: Relational Algebra & Normalization: 1NF, 2NF, 3NF, BCNF

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2 (Lesson 2.5)
- **Subtopics**:
  - `5.9.1` Relational Algebra primitives: Selection ($\sigma$), Projection ($\pi$), Cartesian Product ($	imes$), Join ($owtie$).
  - `5.9.2` First Normal Form (1NF): atomic values, unique column names, primary key defined.
  - `5.9.3` Second Normal Form (2NF): 1NF + no partial dependencies (non-key attributes dependent on full composite key).
  - `5.9.4` Third Normal Form (3NF): 2NF + no transitive dependencies (non-key attributes dependent only on primary key).
  - `5.9.5` Boyce-Codd Normal Form (BCNF): every determinant is a candidate key; anomalies eliminated.
- **Key Failure Modes & Edge Cases**: Storing comma-separated lists in database columns (violating 1NF), making indexing and joins impossible.
- **Verification & Mastery Check**: Take an un-normalized, redundant spreadsheet schema and normalize it through 1NF, 2NF, and 3NF into relational tables.
- **Project Application**: SchemaVault: Normalized relational models.', '{"solution.py": "# Phase 5 // Lesson 5.9: Relational Algebra & Normalization: 1NF, 2NF, 3NF, BCNF\n\ndef solve():\n    \"\"\"\n    Verification: Take an un-normalized, redundant spreadsheet schema and normalize it through 1NF, 2NF, and 3NF into \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.9", "subtopics_count": 5, "verification_criteria": "Take an un-normalized, redundant spreadsheet schema and normalize it through 1NF, 2NF, and 3NF into relational tables.", "subtopics": ["5.9.1 Relational Algebra primitives: Selection ($\\sigma$), Projection ($\\pi$), Cartesian Product ($\times$), Join ($\bowtie$).", "5.9.2 First Normal Form (1NF): atomic values, unique column names, primary key defined.", "5.9.3 Second Normal Form (2NF): 1NF + no partial dependencies (non-key attributes dependent on full composite key).", "5.9.4 Third Normal Form (3NF): 2NF + no transitive dependencies (non-key attributes dependent only on primary key).", "5.9.5 Boyce-Codd Normal Form (BCNF): every determinant is a candidate key; anomalies eliminated."]}'::jsonb, '["Explain how this implementation prevents: Storing comma-separated lists in database columns (violating 1NF), making indexing and joins impossible.", "How does Relational Algebra & Normalization: 1NF, 2NF, 3NF, BCNF scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-10', 'phase-05-lesson-10-pragmatic-denormalization-write-amplifica', 'module-7', 10, 'Lesson 7.10: Pragmatic Denormalization & Write Amplification', 'Prerequisites: Lesson 5.9', 'Prerequisites: Lesson 5.9 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 500.0, '# Lesson 5.10: Pragmatic Denormalization & Write Amplification

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.9
- **Subtopics**:
  - `5.10.1` When to violate 3NF: read-heavy workloads where joins across 8 tables cause severe latency.
  - `5.10.2` Denormalization strategies: pre-computed counters, caching parent status in child records, summary tables.
  - `5.10.3` Maintaining consistency in denormalized data: database triggers vs application-level transactions.
  - `5.10.4` Write Amplification: calculating the extra disk writes incurred across multiple denormalized copies during updates.
- **Key Failure Modes & Edge Cases**: Denormalizing data without transactional synchronization, causing permanent data divergence between tables.
- **Verification & Mastery Check**: Benchmark query performance between a fully normalized 3NF schema and a pragmatic denormalized schema under read/write load.
- **Project Application**: TenantIQ: Precomputed DORA metric summaries.', '{"solution.py": "# Phase 5 // Lesson 5.10: Pragmatic Denormalization & Write Amplification\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark query performance between a fully normalized 3NF schema and a pragmatic denormalized schem\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.10", "subtopics_count": 4, "verification_criteria": "Benchmark query performance between a fully normalized 3NF schema and a pragmatic denormalized schema under read/write load.", "subtopics": ["5.10.1 When to violate 3NF: read-heavy workloads where joins across 8 tables cause severe latency.", "5.10.2 Denormalization strategies: pre-computed counters, caching parent status in child records, summary tables.", "5.10.3 Maintaining consistency in denormalized data: database triggers vs application-level transactions.", "5.10.4 Write Amplification: calculating the extra disk writes incurred across multiple denormalized copies during updates."]}'::jsonb, '["Explain how this implementation prevents: Denormalizing data without transactional synchronization, causing permanent data divergence between tables.", "How does Pragmatic Denormalization & Write Amplification scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
