INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-3-31', 'phase-03-lesson-31-memory-contiguity-cache-locality-in-data-', 'module-5', 31, 'Lesson 5.31: Memory Contiguity & Cache Locality in Data Structures', 'Prerequisites: Phase 0 (Lesson 0.6), Phase 2 (Lesson 2.11)', 'Prerequisites: Phase 0 (Lesson 0.6), Phase 2 (Lesson 2.11) | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1550.0, '# Lesson 3.31: Memory Contiguity & Cache Locality in Data Structures

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0 (Lesson 0.6), Phase 2 (Lesson 2.11)
- **Subtopics**:
  - `3.31.1` Physical memory layouts: contiguous memory allocations vs node-pointer graph allocations.
  - `3.31.2` Cache line utilization: iterating contiguous arrays vs dereferencing scattered linked-list pointers.
  - `3.31.3` Memory overhead per element: 8 bytes for 64-bit int array vs 32+ bytes for linked-list node.
  - `3.31.4` Spatial prefetching in hardware: CPU prefetching contiguous memory blocks automatically.
- **Key Failure Modes & Edge Cases**: Assuming linked lists are faster than arrays for insertion without accounting for cache miss penalties.
- **Verification & Mastery Check**: Benchmark traversal time of 10,000,000 integers in a flat array vs a pointer-linked list, demonstrating a 20x delta.
- **Project Application**: DataSift: Chunk memory layout.', '{"solution.py": "# Phase 3 // Lesson 3.31: Memory Contiguity & Cache Locality in Data Structures\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark traversal time of 10,000,000 integers in a flat array vs a pointer-linked list, demonstrat\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.31", "subtopics_count": 4, "verification_criteria": "Benchmark traversal time of 10,000,000 integers in a flat array vs a pointer-linked list, demonstrating a 20x delta.", "subtopics": ["3.31.1 Physical memory layouts: contiguous memory allocations vs node-pointer graph allocations.", "3.31.2 Cache line utilization: iterating contiguous arrays vs dereferencing scattered linked-list pointers.", "3.31.3 Memory overhead per element: 8 bytes for 64-bit int array vs 32+ bytes for linked-list node.", "3.31.4 Spatial prefetching in hardware: CPU prefetching contiguous memory blocks automatically."]}'::jsonb, '["Explain how this implementation prevents: Assuming linked lists are faster than arrays for insertion without accounting for cache miss penalties.", "How does Memory Contiguity & Cache Locality in Data Structures scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-32', 'phase-03-lesson-32-dynamic-array-architecture-resizing-amort', 'module-5', 32, 'Lesson 5.32: Dynamic Array Architecture: Resizing & Amortized Analysis', 'Prerequisites: Lesson 3.31', 'Prerequisites: Lesson 3.31 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1600.0, '# Lesson 3.32: Dynamic Array Architecture: Resizing & Amortized Analysis

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.31
- **Subtopics**:
  - `3.32.1` Dynamic array structure: pointer to contiguous heap buffer, capacity, length.
  - `3.32.2` The Resizing Strategy: allocating new buffer of size $k 	imes 	ext{capacity}$ and copying elements.
  - `3.32.3` Resize multiplier trade-offs: $2.0	imes$ vs $1.5	imes$ (reusing previously freed memory chunks).
  - `3.32.4` Amortized $O(1)$ proof: Aggregate method and Potential method proving constant average append time.
- **Key Failure Modes & Edge Cases**: Resizing with a constant additive increase ($	ext{capacity} + 1000$), degrading appends to quadratic $O(n^2)$ time.
- **Verification & Mastery Check**: Implement a dynamic array from scratch with a custom geometric growth factor and prove $O(1)$ amortized append.
- **Project Application**: DataSift: Dynamic accumulator buffers.', '{"solution.py": "# Phase 3 // Lesson 3.32: Dynamic Array Architecture: Resizing & Amortized Analysis\n\ndef solve():\n    \"\"\"\n    Verification: Implement a dynamic array from scratch with a custom geometric growth factor and prove $O(1)$ amorti\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.32", "subtopics_count": 4, "verification_criteria": "Implement a dynamic array from scratch with a custom geometric growth factor and prove $O(1)$ amortized append.", "subtopics": ["3.32.1 Dynamic array structure: pointer to contiguous heap buffer, capacity, length.", "3.32.2 The Resizing Strategy: allocating new buffer of size $k \times \text{capacity}$ and copying elements.", "3.32.3 Resize multiplier trade-offs: $2.0\times$ vs $1.5\times$ (reusing previously freed memory chunks).", "3.32.4 Amortized $O(1)$ proof: Aggregate method and Potential method proving constant average append time."]}'::jsonb, '["Explain how this implementation prevents: Resizing with a constant additive increase ($\text{capacity} + 1000$), degrading appends to quadratic $O(n^2)$ time.", "How does Dynamic Array Architecture: Resizing & Amortized Analysis scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-33', 'phase-03-lesson-33-singly-linked-lists-pointer-manipulation-', 'module-5', 33, 'Lesson 5.33: Singly Linked Lists: Pointer Manipulation & Invariants', 'Prerequisites: Phase 1 (Lesson 1.1)', 'Prerequisites: Phase 1 (Lesson 1.1) | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1650.0, '# Lesson 3.33: Singly Linked Lists: Pointer Manipulation & Invariants

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1 (Lesson 1.1)
- **Subtopics**:
  - `3.33.1` Node structure: payload value and pointer to next node.
  - `3.33.2` Insertion and deletion: head insertion ($O(1)$), tail insertion ($O(n)$ or $O(1)$ with tail pointer), arbitrary deletion ($O(n)$).
  - `3.33.3` Pointer manipulation discipline: maintaining invariants to avoid losing references to remaining list.
  - `3.33.4` The Sentinel / Dummy Node pattern: eliminating edge-case code for empty lists and head deletions.
- **Key Failure Modes & Edge Cases**: Losing the reference to `curr.next` before updating pointers, resulting in dangling memory and broken lists.
- **Verification & Mastery Check**: Implement a Singly Linked List with dummy head and prove zero memory leaks or lost nodes on edge cases.
- **Project Application**: LoxLang: Environment scope chains.', '{"solution.py": "# Phase 3 // Lesson 3.33: Singly Linked Lists: Pointer Manipulation & Invariants\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Singly Linked List with dummy head and prove zero memory leaks or lost nodes on edge cas\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.33", "subtopics_count": 4, "verification_criteria": "Implement a Singly Linked List with dummy head and prove zero memory leaks or lost nodes on edge cases.", "subtopics": ["3.33.1 Node structure: payload value and pointer to next node.", "3.33.2 Insertion and deletion: head insertion ($O(1)$), tail insertion ($O(n)$ or $O(1)$ with tail pointer), arbitrary deletion ($O(n)$).", "3.33.3 Pointer manipulation discipline: maintaining invariants to avoid losing references to remaining list.", "3.33.4 The Sentinel / Dummy Node pattern: eliminating edge-case code for empty lists and head deletions."]}'::jsonb, '["Explain how this implementation prevents: Losing the reference to `curr.next` before updating pointers, resulting in dangling memory and broken lists.", "How does Singly Linked Lists: Pointer Manipulation & Invariants scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-34', 'phase-03-lesson-34-doubly-linked-lists-sentinels', 'module-5', 34, 'Lesson 5.34: Doubly Linked Lists & Sentinels', 'Prerequisites: Lesson 3.33', 'Prerequisites: Lesson 3.33 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1700.0, '# Lesson 3.34: Doubly Linked Lists & Sentinels

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.33
- **Subtopics**:
  - `3.34.1` Node structure: payload, pointer to next node, pointer to previous node.
  - `3.34.2` Bidirectional traversal: traversing forward and backward.
  - `3.34.3` Constant-time node removal: deleting a known node reference in $O(1)$ without searching from head.
  - `3.34.4` Circular doubly linked lists with a single sentinel node: simplifying insertion and deletion logic.
- **Key Failure Modes & Edge Cases**: Failing to update `prev` pointers during node splicing, breaking backward traversals.
- **Verification & Mastery Check**: Implement a Doubly Linked List supporting $O(1)$ insertion and deletion at both ends and of arbitrary known nodes.
- **Project Application**: Phase 5: Foundation for CacheKit LRU cache.', '{"solution.py": "# Phase 3 // Lesson 3.34: Doubly Linked Lists & Sentinels\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Doubly Linked List supporting $O(1)$ insertion and deletion at both ends and of arbitrar\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.34", "subtopics_count": 4, "verification_criteria": "Implement a Doubly Linked List supporting $O(1)$ insertion and deletion at both ends and of arbitrary known nodes.", "subtopics": ["3.34.1 Node structure: payload, pointer to next node, pointer to previous node.", "3.34.2 Bidirectional traversal: traversing forward and backward.", "3.34.3 Constant-time node removal: deleting a known node reference in $O(1)$ without searching from head.", "3.34.4 Circular doubly linked lists with a single sentinel node: simplifying insertion and deletion logic."]}'::jsonb, '["Explain how this implementation prevents: Failing to update `prev` pointers during node splicing, breaking backward traversals.", "How does Doubly Linked Lists & Sentinels scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-35', 'phase-03-lesson-35-floyd-s-cycle-finding-algorithm-tortoise-', 'module-5', 35, 'Lesson 5.35: Floyd''s Cycle-Finding Algorithm (Tortoise and Hare)', 'Prerequisites: Lesson 3.33', 'Prerequisites: Lesson 3.33 | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1750.0, '# Lesson 3.35: Floyd''s Cycle-Finding Algorithm (Tortoise and Hare)

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.33
- **Subtopics**:
  - `3.35.1` The linked list cycle problem: detecting infinite loops in pointer structures.
  - `3.35.2` Two-pointer approach: Slow pointer (1 step) and Fast pointer (2 steps).
  - `3.35.3` Cycle detection proof: why fast and slow pointers must collide within the cycle in $O(n)$ time.
  - `3.35.4` Finding the cycle start node: resetting one pointer to head and advancing both by 1 step.
- **Key Failure Modes & Edge Cases**: Creating infinite loops in traversal routines when circular references exist in linked structures.
- **Verification & Mastery Check**: Implement Floyd''s cycle detection from memory and return the exact node where the cycle begins in $O(1)$ memory.
- **Project Application**: DevAudit: Cycle detection in linked imports.', '{"solution.py": "# Phase 3 // Lesson 3.35: Floyd''s Cycle-Finding Algorithm (Tortoise and Hare)\n\ndef solve():\n    \"\"\"\n    Verification: Implement Floyd''s cycle detection from memory and return the exact node where the cycle begins in $O\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.35", "subtopics_count": 4, "verification_criteria": "Implement Floyd''s cycle detection from memory and return the exact node where the cycle begins in $O(1)$ memory.", "subtopics": ["3.35.1 The linked list cycle problem: detecting infinite loops in pointer structures.", "3.35.2 Two-pointer approach: Slow pointer (1 step) and Fast pointer (2 steps).", "3.35.3 Cycle detection proof: why fast and slow pointers must collide within the cycle in $O(n)$ time.", "3.35.4 Finding the cycle start node: resetting one pointer to head and advancing both by 1 step."]}'::jsonb, '["Explain how this implementation prevents: Creating infinite loops in traversal routines when circular references exist in linked structures.", "How does Floyd''s Cycle-Finding Algorithm (Tortoise and Hare) scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-36', 'phase-03-lesson-36-the-stack-abstract-data-type-array-vs-lin', 'module-5', 36, 'Lesson 5.36: The Stack Abstract Data Type: Array vs Linked Implementations', 'Prerequisites: Lesson 3.32, 3.3', 'Prerequisites: Lesson 3.32, 3.3 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1800.0, '# Lesson 3.36: The Stack Abstract Data Type: Array vs Linked Implementations

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.32, 3.3
- **Subtopics**:
  - `3.36.1` Stack LIFO (Last-In, First-Out) semantics: `push`, `pop`, `peek`, `is_empty`.
  - `3.36.2` Array-backed stack: memory contiguity, cache efficiency, amortized $O(1)$ push.
  - `3.36.3` Linked-list-backed stack: strict $O(1)$ worst-case push/pop, pointer memory overhead.
  - `3.36.4` Stack overflow and capacity limits in fixed-size hardware/virtual stacks.
- **Key Failure Modes & Edge Cases**: Calling `pop()` on an empty stack without bounds checks, causing index out-of-range crashes.
- **Verification & Mastery Check**: Implement a generic Stack supporting `push`, `pop`, and `min()` in constant $O(1)$ time and $O(n)$ space.
- **Project Application**: LoxLang: Expression evaluation stack.', '{"solution.py": "# Phase 3 // Lesson 3.36: The Stack Abstract Data Type: Array vs Linked Implementations\n\ndef solve():\n    \"\"\"\n    Verification: Implement a generic Stack supporting `push`, `pop`, and `min()` in constant $O(1)$ time and $O(n)$ s\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.36", "subtopics_count": 4, "verification_criteria": "Implement a generic Stack supporting `push`, `pop`, and `min()` in constant $O(1)$ time and $O(n)$ space.", "subtopics": ["3.36.1 Stack LIFO (Last-In, First-Out) semantics: `push`, `pop`, `peek`, `is_empty`.", "3.36.2 Array-backed stack: memory contiguity, cache efficiency, amortized $O(1)$ push.", "3.36.3 Linked-list-backed stack: strict $O(1)$ worst-case push/pop, pointer memory overhead.", "3.36.4 Stack overflow and capacity limits in fixed-size hardware/virtual stacks."]}'::jsonb, '["Explain how this implementation prevents: Calling `pop()` on an empty stack without bounds checks, causing index out-of-range crashes.", "How does The Stack Abstract Data Type: Array vs Linked Implementations scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-37', 'phase-03-lesson-37-the-queue-circular-buffer-deque', 'module-5', 37, 'Lesson 5.37: The Queue & Circular Buffer Deque', 'Prerequisites: Lesson 3.32', 'Prerequisites: Lesson 3.32 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 1850.0, '# Lesson 3.37: The Queue & Circular Buffer Deque

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.32
- **Subtopics**:
  - `3.37.1` Queue FIFO (First-In, First-Out) semantics: `enqueue`, `dequeue`, `peek`.
  - `3.37.2` The flaw of naive array queues: `list.pop(0)` requiring $O(n)$ element shifts.
  - `3.37.3` Circular Buffer array queue: head pointer, tail pointer, modulo arithmetic (`(tail + 1) % capacity`).
  - `3.37.4` Double-Ended Queue (Deque): $O(1)$ insertions and removals at both head and tail.
- **Key Failure Modes & Edge Cases**: Using a standard Python list as a FIFO queue in high-throughput services, incurring massive $O(n)$ CPU penalties.
- **Verification & Mastery Check**: Implement a high-performance Circular Buffer Deque with zero element shifts passing all FIFO unit tests.
- **Project Application**: NanoHTTP: Request socket queues in Phase 4.', '{"solution.py": "# Phase 3 // Lesson 3.37: The Queue & Circular Buffer Deque\n\ndef solve():\n    \"\"\"\n    Verification: Implement a high-performance Circular Buffer Deque with zero element shifts passing all FIFO unit te\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.37", "subtopics_count": 4, "verification_criteria": "Implement a high-performance Circular Buffer Deque with zero element shifts passing all FIFO unit tests.", "subtopics": ["3.37.1 Queue FIFO (First-In, First-Out) semantics: `enqueue`, `dequeue`, `peek`.", "3.37.2 The flaw of naive array queues: `list.pop(0)` requiring $O(n)$ element shifts.", "3.37.3 Circular Buffer array queue: head pointer, tail pointer, modulo arithmetic (`(tail + 1) % capacity`).", "3.37.4 Double-Ended Queue (Deque): $O(1)$ insertions and removals at both head and tail."]}'::jsonb, '["Explain how this implementation prevents: Using a standard Python list as a FIFO queue in high-throughput services, incurring massive $O(n)$ CPU penalties.", "How does The Queue & Circular Buffer Deque scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-38', 'phase-03-lesson-38-hash-functions-uniformity-avalanche-rolli', 'module-5', 38, 'Lesson 5.38: Hash Functions: Uniformity, Avalanche, & Rolling Hashes', 'Prerequisites: Phase 2 (Lesson 2.1)', 'Prerequisites: Phase 2 (Lesson 2.1) | Subtopics: 4 items', 'Systems project application', 160, 4, 870.0, 1900.0, '# Lesson 3.38: Hash Functions: Uniformity, Avalanche, & Rolling Hashes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 2 (Lesson 2.1)
- **Subtopics**:
  - `3.38.1` Hash function criteria: deterministic, uniform distribution across buckets, fast evaluation.
  - `3.38.2` The Avalanche Effect: a single bit change in input flips approximately 50% of output bits.
  - `3.38.3` Non-cryptographic hash functions: FNV-1a, MurmurHash3, CityHash, xxHash.
  - `3.38.4` Polynomial Rolling Hash for strings: $H = \sum s[i] \cdot p^i \pmod m$; sliding window string searches.
- **Key Failure Modes & Edge Cases**: Using trivial sum-of-characters hash functions, causing massive collision clusters on anagram strings.
- **Verification & Mastery Check**: Implement a polynomial rolling hash function and prove avalanche properties across single-character mutations.
- **Project Application**: DataSift: Fast string hashing.', '{"solution.py": "# Phase 3 // Lesson 3.38: Hash Functions: Uniformity, Avalanche, & Rolling Hashes\n\ndef solve():\n    \"\"\"\n    Verification: Implement a polynomial rolling hash function and prove avalanche properties across single-character \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.38", "subtopics_count": 4, "verification_criteria": "Implement a polynomial rolling hash function and prove avalanche properties across single-character mutations.", "subtopics": ["3.38.1 Hash function criteria: deterministic, uniform distribution across buckets, fast evaluation.", "3.38.2 The Avalanche Effect: a single bit change in input flips approximately 50% of output bits.", "3.38.3 Non-cryptographic hash functions: FNV-1a, MurmurHash3, CityHash, xxHash.", "3.38.4 Polynomial Rolling Hash for strings: $H = \\sum s[i] \\cdot p^i \\pmod m$; sliding window string searches."]}'::jsonb, '["Explain how this implementation prevents: Using trivial sum-of-characters hash functions, causing massive collision clusters on anagram strings.", "How does Hash Functions: Uniformity, Avalanche, & Rolling Hashes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-39', 'phase-03-lesson-39-hash-collision-resolution-separate-chaini', 'module-5', 39, 'Lesson 5.39: Hash Collision Resolution: Separate Chaining vs Open Addressing', 'Prerequisites: Lesson 3.38', 'Prerequisites: Lesson 3.38 | Subtopics: 4 items', 'Systems project application', 160, 4, 750.0, 1950.0, '# Lesson 3.39: Hash Collision Resolution: Separate Chaining vs Open Addressing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.38
- **Subtopics**:
  - `3.39.1` The Birthday Paradox in hashing: collisions occur much earlier than capacity limit.
  - `3.39.2` Separate Chaining: bucket linked lists; worst-case degradation to $O(n)$ on adversarial keys.
  - `3.39.3` Open Addressing: storing all elements directly in the array; finding open slots via probing sequences.
  - `3.39.4` Load Factor ($lpha = n/k$): collision frequency scaling as load factor increases.
- **Key Failure Modes & Edge Cases**: Failing to resize a separate chaining hash map when load factor exceeds 1.0, degrading queries to linear scans.
- **Verification & Mastery Check**: Implement Separate Chaining with red-black tree bucket thresholding on collision chains.
- **Project Application**: DataSift: Key cardinality counting.', '{"solution.py": "# Phase 3 // Lesson 3.39: Hash Collision Resolution: Separate Chaining vs Open Addressing\n\ndef solve():\n    \"\"\"\n    Verification: Implement Separate Chaining with red-black tree bucket thresholding on collision chains.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.39", "subtopics_count": 4, "verification_criteria": "Implement Separate Chaining with red-black tree bucket thresholding on collision chains.", "subtopics": ["3.39.1 The Birthday Paradox in hashing: collisions occur much earlier than capacity limit.", "3.39.2 Separate Chaining: bucket linked lists; worst-case degradation to $O(n)$ on adversarial keys.", "3.39.3 Open Addressing: storing all elements directly in the array; finding open slots via probing sequences.", "3.39.4 Load Factor ($\u0007lpha = n/k$): collision frequency scaling as load factor increases."]}'::jsonb, '["Explain how this implementation prevents: Failing to resize a separate chaining hash map when load factor exceeds 1.0, degrading queries to linear scans.", "How does Hash Collision Resolution: Separate Chaining vs Open Addressing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-3-40', 'phase-03-lesson-40-open-addressing-linear-probing-quadratic-', 'module-5', 40, 'Lesson 5.40: Open Addressing: Linear Probing, Quadratic, & Double Hashing', 'Prerequisites: Lesson 3.39', 'Prerequisites: Lesson 3.39 | Subtopics: 4 items', 'Systems project application', 160, 4, 810.0, 2000.0, '# Lesson 3.40: Open Addressing: Linear Probing, Quadratic, & Double Hashing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 3.39
- **Subtopics**:
  - `3.40.1` Linear Probing: probing index $(h(k) + i) \pmod m$; primary clustering phenomena.
  - `3.40.2` Quadratic Probing: probing index $(h(k) + c_1 i + c_2 i^2) \pmod m$; secondary clustering.
  - `3.40.3` Double Hashing: probing index $(h_1(k) + i \cdot h_2(k)) \pmod m$; eliminating clustering.
  - `3.40.4` Tombstones for deletion: marking deleted slots as `TOMBSTONE` to preserve search probe chains.
- **Key Failure Modes & Edge Cases**: Failing to handle tombstones during deletion, prematurely terminating lookups for subsequent inserted keys.
- **Verification & Mastery Check**: Build an Open-Addressed hash table from scratch using double hashing and tombstone deletion.
- **Project Application**: DataSift: Core hash map.', '{"solution.py": "# Phase 3 // Lesson 3.40: Open Addressing: Linear Probing, Quadratic, & Double Hashing\n\ndef solve():\n    \"\"\"\n    Verification: Build an Open-Addressed hash table from scratch using double hashing and tombstone deletion.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "3.40", "subtopics_count": 4, "verification_criteria": "Build an Open-Addressed hash table from scratch using double hashing and tombstone deletion.", "subtopics": ["3.40.1 Linear Probing: probing index $(h(k) + i) \\pmod m$; primary clustering phenomena.", "3.40.2 Quadratic Probing: probing index $(h(k) + c_1 i + c_2 i^2) \\pmod m$; secondary clustering.", "3.40.3 Double Hashing: probing index $(h_1(k) + i \\cdot h_2(k)) \\pmod m$; eliminating clustering.", "3.40.4 Tombstones for deletion: marking deleted slots as `TOMBSTONE` to preserve search probe chains."]}'::jsonb, '["Explain how this implementation prevents: Failing to handle tombstones during deletion, prematurely terminating lookups for subsequent inserted keys.", "How does Open Addressing: Linear Probing, Quadratic, & Double Hashing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
