INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-7-31', 'phase-07-lesson-31-terraform-modules-workspaces-production-a', 'module-10', 31, 'Lesson 10.31: Terraform Modules, Workspaces & Production Architecture', 'Prerequisites: Lesson 7.30', 'Prerequisites: Lesson 7.30 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 1550.0, '# Lesson 7.31: Terraform Modules, Workspaces & Production Architecture

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.30
- **Subtopics**:
  - `7.31.1` Terraform module architecture: root modules, child modules, input variables, outputs, and validation blocks
  - `7.31.2` Module design best practices: single responsibility, version pinning, and publishing to private registries
  - `7.31.3` Environment segregation: Terraform Workspaces vs directory-based layout (separate root modules per environment)
  - `7.31.4` Why directory-based segregation (`environments/prod`, `environments/stage`) is superior to workspaces for blast radius control
  - `7.31.5` Terraform expressions: for_each, count, dynamic blocks, splat operators, and conditional expressions
  - `7.31.6` Static analysis and policy-as-code: `tflint`, `tfsec`, and Open Policy Agent (OPA) / Conftest compliance validation in CI
- **Key Failure Modes & Edge Cases**: Using `count` instead of `for_each` causing massive cascading resource destructions when reordering list elements.
- **Verification & Mastery Check**: Build a reusable, versioned Terraform module for multi-zone GKE clusters with strict input variable validations.
- **Project Application**: InfraBlueprint: Production Terraform module library.', '{"solution.py": "# Phase 7 // Lesson 7.31: Terraform Modules, Workspaces & Production Architecture\n\ndef solve():\n    \"\"\"\n    Verification: Build a reusable, versioned Terraform module for multi-zone GKE clusters with strict input variable \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.31", "subtopics_count": 6, "verification_criteria": "Build a reusable, versioned Terraform module for multi-zone GKE clusters with strict input variable validations.", "subtopics": ["7.31.1 Terraform module architecture: root modules, child modules, input variables, outputs, and validation blocks", "7.31.2 Module design best practices: single responsibility, version pinning, and publishing to private registries", "7.31.3 Environment segregation: Terraform Workspaces vs directory-based layout (separate root modules per environment)", "7.31.4 Why directory-based segregation (`environments/prod`, `environments/stage`) is superior to workspaces for blast radius control", "7.31.5 Terraform expressions: for_each, count, dynamic blocks, splat operators, and conditional expressions", "7.31.6 Static analysis and policy-as-code: `tflint`, `tfsec`, and Open Policy Agent (OPA) / Conftest compliance validation in CI"]}'::jsonb, '["Explain how this implementation prevents: Using `count` instead of `for_each` causing massive cascading resource destructions when reordering list elements.", "How does Terraform Modules, Workspaces & Production Architecture scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-32', 'phase-07-lesson-32-terraform-drift-detection-refactoring-ter', 'module-10', 32, 'Lesson 10.32: Terraform Drift Detection, Refactoring & Terragrunt', 'Prerequisites: Lesson 7.31', 'Prerequisites: Lesson 7.31 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1600.0, '# Lesson 7.32: Terraform Drift Detection, Refactoring & Terragrunt

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.31
- **Subtopics**:
  - `7.32.1` Infrastructure drift: out-of-band manual console edits, silent cloud provider API changes, and reconciling state
  - `7.32.2` Automated drift detection: running scheduled `terraform plan -detailed-exitcode` pipelines in CI/CD
  - `7.32.3` Refactoring Terraform configurations: `moved` blocks for seamless resource renaming without destroying live infrastructure
  - `7.32.4` Targeted operations: `-target` flag usage, emergency manual state surgery (`state rm`, `state import`), and risks
  - `7.32.5` DRY Terraform with Terragrunt: centralized backend generation, common provider inheritance, and dependency graphs
  - `7.32.6` Handling breaking provider upgrades: managing provider lock files (`.terraform.lock.hcl`) across teams
- **Key Failure Modes & Edge Cases**: Manual console modifications creating unresolvable drift; dangerous `-target` applications leaving state partially updated.
- **Verification & Mastery Check**: Refactor an existing monolithic Terraform configuration using `moved` blocks to relocate resources into modules with zero recreations.
- **Project Application**: InfraBlueprint: Drift detection automation and Terragrunt orchestrations.', '{"solution.py": "# Phase 7 // Lesson 7.32: Terraform Drift Detection, Refactoring & Terragrunt\n\ndef solve():\n    \"\"\"\n    Verification: Refactor an existing monolithic Terraform configuration using `moved` blocks to relocate resources i\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.32", "subtopics_count": 6, "verification_criteria": "Refactor an existing monolithic Terraform configuration using `moved` blocks to relocate resources into modules with zero recreations.", "subtopics": ["7.32.1 Infrastructure drift: out-of-band manual console edits, silent cloud provider API changes, and reconciling state", "7.32.2 Automated drift detection: running scheduled `terraform plan -detailed-exitcode` pipelines in CI/CD", "7.32.3 Refactoring Terraform configurations: `moved` blocks for seamless resource renaming without destroying live infrastructure", "7.32.4 Targeted operations: `-target` flag usage, emergency manual state surgery (`state rm`, `state import`), and risks", "7.32.5 DRY Terraform with Terragrunt: centralized backend generation, common provider inheritance, and dependency graphs", "7.32.6 Handling breaking provider upgrades: managing provider lock files (`.terraform.lock.hcl`) across teams"]}'::jsonb, '["Explain how this implementation prevents: Manual console modifications creating unresolvable drift; dangerous `-target` applications leaving state partially updat", "How does Terraform Drift Detection, Refactoring & Terragrunt scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-33', 'phase-07-lesson-33-event-streaming-fundamentals-apache-kafka', 'module-10', 33, 'Lesson 10.33: Event Streaming Fundamentals: Apache Kafka Architecture & Storage Internals', 'Prerequisites: Phase 4, Lesson 7.4', 'Prerequisites: Phase 4, Lesson 7.4 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 1650.0, '# Lesson 7.33: Event Streaming Fundamentals: Apache Kafka Architecture & Storage Internals

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 7.4
- **Subtopics**:
  - `7.33.1` Message queues (RabbitMQ) vs Event streaming platforms (Kafka): push vs pull, message consumption vs durable logs
  - `7.33.2` Kafka core concepts: Topics, Partitions, Brokers, Clusters, and Replication Factor
  - `7.33.3` Storage internals on disk: commit log, segments, `.log` data files, `.index` offset indexes, and `.timeindex` files
  - `7.33.4` Sequential I/O and Zero-Copy optimization: page cache utilization and `sendfile()` kernel syscall eliminating context switches
  - `7.33.5` Log retention and compaction: time-based retention, size-based retention, clean/dirty log compaction, and tombstone markers
  - `7.33.6` Kafka metadata architectures: legacy ZooKeeper coordination vs modern KRaft (Kafka Raft metadata mode)
- **Key Failure Modes & Edge Cases**: High partition counts exceeding broker memory and file descriptor limits; broker disk filling up due to uncompacted tombstone keys.
- **Verification & Mastery Check**: Deploy a multi-broker Kafka KRaft cluster; inspect partition segment files on disk with `kafka-run-class.sh kafka.tools.DumpLogSegments`.
- **Project Application**: InfraBlueprint: Distributed Kafka event streaming infrastructure.', '{"solution.py": "# Phase 7 // Lesson 7.33: Event Streaming Fundamentals: Apache Kafka Architecture & Storage Internals\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a multi-broker Kafka KRaft cluster; inspect partition segment files on disk with `kafka-run-c\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.33", "subtopics_count": 6, "verification_criteria": "Deploy a multi-broker Kafka KRaft cluster; inspect partition segment files on disk with `kafka-run-class.sh kafka.tools.DumpLogSegments`.", "subtopics": ["7.33.1 Message queues (RabbitMQ) vs Event streaming platforms (Kafka): push vs pull, message consumption vs durable logs", "7.33.2 Kafka core concepts: Topics, Partitions, Brokers, Clusters, and Replication Factor", "7.33.3 Storage internals on disk: commit log, segments, `.log` data files, `.index` offset indexes, and `.timeindex` files", "7.33.4 Sequential I/O and Zero-Copy optimization: page cache utilization and `sendfile()` kernel syscall eliminating context switches", "7.33.5 Log retention and compaction: time-based retention, size-based retention, clean/dirty log compaction, and tombstone markers", "7.33.6 Kafka metadata architectures: legacy ZooKeeper coordination vs modern KRaft (Kafka Raft metadata mode)"]}'::jsonb, '["Explain how this implementation prevents: High partition counts exceeding broker memory and file descriptor limits; broker disk filling up due to uncompacted tomb", "How does Event Streaming Fundamentals: Apache Kafka Architecture & Storage Internals scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-34', 'phase-07-lesson-34-kafka-producers-consumers-guarantees-prot', 'module-10', 34, 'Lesson 10.34: Kafka Producers & Consumers: Guarantees & Protocols', 'Prerequisites: Lesson 7.33', 'Prerequisites: Lesson 7.33 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 1700.0, '# Lesson 7.34: Kafka Producers & Consumers: Guarantees & Protocols

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.33
- **Subtopics**:
  - `7.34.1` Producer mechanics: message keys, partitioners (Murmur2 hash), batching (`batch.size`, `linger.ms`), and compression (snappy, zstd)
  - `7.34.2` Producer durability guarantees: `acks=0`, `acks=1`, and `acks=all` (`min.insync.replicas` interaction)
  - `7.34.3` Idempotent producers: sequence numbers, producer IDs (PID), and eliminating message duplication on network retry
  - `7.34.4` Consumer groups architecture: partition assignment, group coordinators, and rebalance protocols (Eager vs Incremental Cooperative)
  - `7.34.5` Offset commit semantics: at-most-once, at-least-once, and exactly-once processing (Kafka Transactions and Read-Committed)
  - `7.34.6` Handling poisoned messages: Dead Letter Queues (DLQ), non-blocking retry topics with exponential backoff delay
- **Key Failure Modes & Edge Cases**: Silent message loss caused by `acks=1` during broker crashes; consumer rebalance storms freezing stream consumption.
- **Verification & Mastery Check**: Implement a resilient Kafka consumer with non-blocking retry topics, incremental cooperative rebalancing, and dead-letter queues.
- **Project Application**: TenantIQ: Asynchronous tenant event ingestion and audit pipeline.', '{"solution.py": "# Phase 7 // Lesson 7.34: Kafka Producers & Consumers: Guarantees & Protocols\n\ndef solve():\n    \"\"\"\n    Verification: Implement a resilient Kafka consumer with non-blocking retry topics, incremental cooperative rebalan\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.34", "subtopics_count": 6, "verification_criteria": "Implement a resilient Kafka consumer with non-blocking retry topics, incremental cooperative rebalancing, and dead-letter queues.", "subtopics": ["7.34.1 Producer mechanics: message keys, partitioners (Murmur2 hash), batching (`batch.size`, `linger.ms`), and compression (snappy, zstd)", "7.34.2 Producer durability guarantees: `acks=0`, `acks=1`, and `acks=all` (`min.insync.replicas` interaction)", "7.34.3 Idempotent producers: sequence numbers, producer IDs (PID), and eliminating message duplication on network retry", "7.34.4 Consumer groups architecture: partition assignment, group coordinators, and rebalance protocols (Eager vs Incremental Cooperative)", "7.34.5 Offset commit semantics: at-most-once, at-least-once, and exactly-once processing (Kafka Transactions and Read-Committed)", "7.34.6 Handling poisoned messages: Dead Letter Queues (DLQ), non-blocking retry topics with exponential backoff delay"]}'::jsonb, '["Explain how this implementation prevents: Silent message loss caused by `acks=1` during broker crashes; consumer rebalance storms freezing stream consumption.", "How does Kafka Producers & Consumers: Guarantees & Protocols scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-35', 'phase-07-lesson-35-chaos-engineering-principles-fault-inject', 'module-10', 35, 'Lesson 10.35: Chaos Engineering: Principles, Fault Injection & LitmusChaos', 'Prerequisites: Lesson 7.1, Lesson 7.12', 'Prerequisites: Lesson 7.1, Lesson 7.12 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1750.0, '# Lesson 7.35: Chaos Engineering: Principles, Fault Injection & LitmusChaos

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.1, Lesson 7.12
- **Subtopics**:
  - `7.35.1` Principles of Chaos Engineering: forming steady-state hypotheses, introducing real-world events, and minimizing blast radius
  - `7.35.2` Fault injection techniques: killing pods, terminating VMs, network latency injection, packet loss, and CPU/memory pressure
  - `7.35.3` Linux network chaos with `tc` (Traffic Control) and `netem`: adding jitter, artificial delay, and packet corruption
  - `7.35.4` LitmusChaos on Kubernetes: ChaosEngine, ChaosExperiment CRDs, and automated validation probes
  - `7.35.5` Game Days: designing team chaos exercises to validate monitoring, alerts, runbooks, and self-healing systems
  - `7.35.6` Automated continuous chaos testing in CI/CD staging environments before major production releases
- **Key Failure Modes & Edge Cases**: Running un-scoped chaos experiments in production taking down core shared databases; lacking automated abort switches.
- **Verification & Mastery Check**: Execute a LitmusChaos experiment injecting 500ms network latency and 20% packet drop; verify circuit breakers trip without user errors.
- **Project Application**: InfraBlueprint: Automated chaos engineering verification harness.', '{"solution.py": "# Phase 7 // Lesson 7.35: Chaos Engineering: Principles, Fault Injection & LitmusChaos\n\ndef solve():\n    \"\"\"\n    Verification: Execute a LitmusChaos experiment injecting 500ms network latency and 20% packet drop; verify circuit\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.35", "subtopics_count": 6, "verification_criteria": "Execute a LitmusChaos experiment injecting 500ms network latency and 20% packet drop; verify circuit breakers trip without user errors.", "subtopics": ["7.35.1 Principles of Chaos Engineering: forming steady-state hypotheses, introducing real-world events, and minimizing blast radius", "7.35.2 Fault injection techniques: killing pods, terminating VMs, network latency injection, packet loss, and CPU/memory pressure", "7.35.3 Linux network chaos with `tc` (Traffic Control) and `netem`: adding jitter, artificial delay, and packet corruption", "7.35.4 LitmusChaos on Kubernetes: ChaosEngine, ChaosExperiment CRDs, and automated validation probes", "7.35.5 Game Days: designing team chaos exercises to validate monitoring, alerts, runbooks, and self-healing systems", "7.35.6 Automated continuous chaos testing in CI/CD staging environments before major production releases"]}'::jsonb, '["Explain how this implementation prevents: Running un-scoped chaos experiments in production taking down core shared databases; lacking automated abort switches.", "How does Chaos Engineering: Principles, Fault Injection & LitmusChaos scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-1', 'phase-10-lesson-01-llm-apis-interaction-paradigms-rest-strea', 'module-11', 1, 'Lesson 11.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs', 'Prerequisites: Phase 4, Phase 9', 'Prerequisites: Phase 4, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 50.0, '# Lesson 10.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Phase 9
- **Subtopics**:
  - `10.1.1` Foundation model API architectures: OpenAI, Anthropic, and Google Gemini API surface comparison
  - `10.1.2` HTTP streaming with Server-Sent Events (SSE): chunked transfer encoding, `data: [DONE]` markers, and low-latency token streaming
  - `10.1.3` Client-side consumption of streaming LLM outputs: handling partial JSON buffers and smooth rendering loops
  - `10.1.4` API parameters: Temperature (softmax scaling), Top-p (nucleus sampling), frequency_penalty, and presence_penalty
  - `10.1.5` Statelessness of LLM endpoints: passing multi-turn conversational message history (`system`, `user`, `assistant`)
  - `10.1.6` Rate limits: Tiered TPM (Tokens Per Minute) and RPM (Requests Per Minute); exponential backoff with jitter on HTTP 429
- **Key Failure Modes & Edge Cases**: Buffering the entire LLM response on the server before sending to the client, destroying perceived user response latency.
- **Verification & Mastery Check**: Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token rendering and retry backoff.
- **Project Application**: DocuMind: Streaming LLM gateway.', '{"solution.py": "# Phase 10 // Lesson 10.1: LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs\n\ndef solve():\n    \"\"\"\n    Verification: Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token ren\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.1", "subtopics_count": 6, "verification_criteria": "Build a streaming client consuming raw OpenAI/Anthropic SSE chunks with real-time markdown token rendering and retry backoff.", "subtopics": ["10.1.1 Foundation model API architectures: OpenAI, Anthropic, and Google Gemini API surface comparison", "10.1.2 HTTP streaming with Server-Sent Events (SSE): chunked transfer encoding, `data: [DONE]` markers, and low-latency token streaming", "10.1.3 Client-side consumption of streaming LLM outputs: handling partial JSON buffers and smooth rendering loops", "10.1.4 API parameters: Temperature (softmax scaling), Top-p (nucleus sampling), frequency_penalty, and presence_penalty", "10.1.5 Statelessness of LLM endpoints: passing multi-turn conversational message history (`system`, `user`, `assistant`)", "10.1.6 Rate limits: Tiered TPM (Tokens Per Minute) and RPM (Requests Per Minute); exponential backoff with jitter on HTTP 429"]}'::jsonb, '["Explain how this implementation prevents: Buffering the entire LLM response on the server before sending to the client, destroying perceived user response latency", "How does LLM APIs & Interaction Paradigms: REST, Streaming SSE & SDKs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-2', 'phase-10-lesson-02-prompt-engineering-science-zero-shot-few-', 'module-11', 2, 'Lesson 11.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct', 'Prerequisites: Lesson 10.1', 'Prerequisites: Lesson 10.1 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 100.0, '# Lesson 10.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 10.1
- **Subtopics**:
  - `10.2.1` Prompt engineering as programmatic programming: system instructions, contextual framing, and role specification
  - `10.2.2` Zero-Shot vs Few-Shot learning: in-context demonstrations, format conditioning, and selection of representative exemplars
  - `10.2.3` Chain-of-Thought (CoT) prompting (Wei et al.): eliciting step-by-step intermediate reasoning paths for complex logic
  - `10.2.4` Least-to-Most prompting: decomposing complex multi-step queries into sub-problems solved iteratively
  - `10.2.5` ReAct framework (Yao et al.): interleaving Reasoning (''Thought'') and Action (''Act'' / tool call) to interact with external tools
  - `10.2.6` Prompt fragility: why formatting quirks, whitespace, and capitalization trigger dramatic model accuracy variations
- **Key Failure Modes & Edge Cases**: Over-prompting with contradictory multi-page instructions causing the model to hallucinate or ignore negative constraints.
- **Verification & Mastery Check**: Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy on mathematical word problems.
- **Project Application**: DocuMind: Prompt orchestration and template library.', '{"solution.py": "# Phase 10 // Lesson 10.2: Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct\n\ndef solve():\n    \"\"\"\n    Verification: Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.2", "subtopics_count": 6, "verification_criteria": "Construct a standardized prompt harness comparing Zero-Shot, Few-Shot, and Chain-of-Thought accuracy on mathematical word problems.", "subtopics": ["10.2.1 Prompt engineering as programmatic programming: system instructions, contextual framing, and role specification", "10.2.2 Zero-Shot vs Few-Shot learning: in-context demonstrations, format conditioning, and selection of representative exemplars", "10.2.3 Chain-of-Thought (CoT) prompting (Wei et al.): eliciting step-by-step intermediate reasoning paths for complex logic", "10.2.4 Least-to-Most prompting: decomposing complex multi-step queries into sub-problems solved iteratively", "10.2.5 ReAct framework (Yao et al.): interleaving Reasoning (''Thought'') and Action (''Act'' / tool call) to interact with external tools", "10.2.6 Prompt fragility: why formatting quirks, whitespace, and capitalization trigger dramatic model accuracy variations"]}'::jsonb, '["Explain how this implementation prevents: Over-prompting with contradictory multi-page instructions causing the model to hallucinate or ignore negative constraint", "How does Prompt Engineering Science: Zero-Shot, Few-Shot, CoT & ReAct scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-3', 'phase-10-lesson-03-structured-outputs-function-calling-json-', 'module-11', 3, 'Lesson 11.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding', 'Prerequisites: Phase 1, Lesson 10.1', 'Prerequisites: Phase 1, Lesson 10.1 | Subtopics: 6 items', 'Systems project application', 300, 11, 2500.0, 150.0, '# Lesson 10.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 1, Lesson 10.1
- **Subtopics**:
  - `10.3.1` Why natural language outputs fail in production pipelines: parsing errors, non-deterministic formatting, and markdown fences
  - `10.3.2` OpenAI Function Calling / Tool Calling specification: JSON Schema declarations for functions, parameters, and types
  - `10.3.3` Pydantic integration: automatic generation of JSON Schemas from Python type annotations (`model_json_schema()`)
  - `10.3.4` OpenAI Structured Outputs (`response_format={''type'': ''json_schema''}`): 100% schema adherence guarantees
  - `10.3.5` Constrained Decoding mechanics: how inference engines mask invalid token vocabulary logits during autoregressive sampling based on CFG/grammar
  - `10.3.6` Open-source grammar-constrained decoding: Outlines, Guidance, and llama.cpp GBNF grammar files
- **Key Failure Modes & Edge Cases**: Relying on naive regex parsing to extract JSON from raw model strings, causing crashes when models wrap output in markdown code blocks.
- **Verification & Mastery Check**: Build an automated data extraction pipeline using Pydantic models and strict constrained decoding with 100% schema compliance.
- **Project Application**: DocuMind: Structured schema extraction engine.', '{"solution.py": "# Phase 10 // Lesson 10.3: Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding\n\ndef solve():\n    \"\"\"\n    Verification: Build an automated data extraction pipeline using Pydantic models and strict constrained decoding wi\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.3", "subtopics_count": 6, "verification_criteria": "Build an automated data extraction pipeline using Pydantic models and strict constrained decoding with 100% schema compliance.", "subtopics": ["10.3.1 Why natural language outputs fail in production pipelines: parsing errors, non-deterministic formatting, and markdown fences", "10.3.2 OpenAI Function Calling / Tool Calling specification: JSON Schema declarations for functions, parameters, and types", "10.3.3 Pydantic integration: automatic generation of JSON Schemas from Python type annotations (`model_json_schema()`)", "10.3.4 OpenAI Structured Outputs (`response_format={''type'': ''json_schema''}`): 100% schema adherence guarantees", "10.3.5 Constrained Decoding mechanics: how inference engines mask invalid token vocabulary logits during autoregressive sampling based on CFG/grammar", "10.3.6 Open-source grammar-constrained decoding: Outlines, Guidance, and llama.cpp GBNF grammar files"]}'::jsonb, '["Explain how this implementation prevents: Relying on naive regex parsing to extract JSON from raw model strings, causing crashes when models wrap output in markdo", "How does Structured Outputs & Function Calling: JSON Schemas, Pydantic & Constrained Decoding scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-4', 'phase-10-lesson-04-context-window-dynamics-lost-in-the-middl', 'module-11', 4, 'Lesson 11.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution', 'Prerequisites: Phase 9, Lesson 10.2', 'Prerequisites: Phase 9, Lesson 10.2 | Subtopics: 6 items', 'Systems project application', 300, 11, 2560.0, 200.0, '# Lesson 10.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 9, Lesson 10.2
- **Subtopics**:
  - `10.4.1` Context window evolution: from 4K (GPT-3) to 128K (GPT-4) to 1M-2M tokens (Gemini 1.5)
  - `10.4.2` The ''Lost in the Middle'' phenomenon (Liu et al.): attention bias toward the beginning and end of long contexts
  - `10.4.3` Needle-in-a-Haystack (NIAH) evaluation: inserting synthetic facts at varying depth percentages ($0\%$ to $100\%$) to measure retrieval recall
  - `10.4.4` Attention dilution: performance degradation and reasoning degradation as context length increases with irrelevant noise
  - `10.4.5` Cost and latency implications: linear cost scaling and quadratic/linear latency increases with massive input prompts
  - `10.4.6` Strategic context placement: placing primary instructions at the very end and grounding documents near the top/bottom
- **Key Failure Modes & Edge Cases**: Stuffing 200 pages of raw un-filtered documentation into an LLM prompt, causing the model to miss critical instructions buried in the middle.
- **Verification & Mastery Check**: Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the resulting retrieval accuracy heatmap.
- **Project Application**: EvalKit: Context window diagnostic and needle benchmark suite.', '{"solution.py": "# Phase 10 // Lesson 10.4: Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution\n\ndef solve():\n    \"\"\"\n    Verification: Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the r\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.4", "subtopics_count": 6, "verification_criteria": "Run a Needle-in-a-Haystack benchmark across 8 context depth intervals on a long document; plot the resulting retrieval accuracy heatmap.", "subtopics": ["10.4.1 Context window evolution: from 4K (GPT-3) to 128K (GPT-4) to 1M-2M tokens (Gemini 1.5)", "10.4.2 The ''Lost in the Middle'' phenomenon (Liu et al.): attention bias toward the beginning and end of long contexts", "10.4.3 Needle-in-a-Haystack (NIAH) evaluation: inserting synthetic facts at varying depth percentages ($0\\%$ to $100\\%$) to measure retrieval recall", "10.4.4 Attention dilution: performance degradation and reasoning degradation as context length increases with irrelevant noise", "10.4.5 Cost and latency implications: linear cost scaling and quadratic/linear latency increases with massive input prompts", "10.4.6 Strategic context placement: placing primary instructions at the very end and grounding documents near the top/bottom"]}'::jsonb, '["Explain how this implementation prevents: Stuffing 200 pages of raw un-filtered documentation into an LLM prompt, causing the model to miss critical instructions ", "How does Context Window Dynamics: Lost-in-the-Middle, Needle-in-a-Haystack & Dilution scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-10-5', 'phase-10-lesson-05-tokenization-mechanics-bpe-wordpiece-tikt', 'module-11', 5, 'Lesson 11.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math', 'Prerequisites: Phase 3, Phase 9', 'Prerequisites: Phase 3, Phase 9 | Subtopics: 6 items', 'Systems project application', 300, 11, 2620.0, 250.0, '# Lesson 10.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 3, Phase 9
- **Subtopics**:
  - `10.5.1` Tokenization paradigms: Character-level vs Word-level vs Subword tokenization (Byte-Pair Encoding, WordPiece, Unigram)
  - `10.5.2` Byte-Pair Encoding (BPE) algorithm: starting with single bytes, iteratively merging most frequent byte pairs into vocabulary
  - `10.5.3` Byte-level BPE: handling arbitrary Unicode characters without unknown token (`<unk>`) out-of-vocabulary fallbacks
  - `10.5.4` Tiktoken library internals: fast Rust-backed BPE tokenizer for OpenAI models (`cl100k_base`, `o200k_base`)
  - `10.5.5` Tokenization quirks and vulnerabilities: space prefix sensitivity, arithmetic failure modes (numbers split into uneven chunks)
  - `10.5.6` Financial cost and latency estimation: calculating token consumption formulas ($1\text{ token} \approx 0.75\text{ words}$ in English; higher for code/non-English)
- **Key Failure Modes & Edge Cases**: Assuming 1 character = 1 token, underestimating API costs and context window consumption by 300% on multilingual text.
- **Verification & Mastery Check**: Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and visualize merge operations.
- **Project Application**: DocuMind: Tokenization and cost accounting module.', '{"solution.py": "# Phase 10 // Lesson 10.5: Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "10.5", "subtopics_count": 6, "verification_criteria": "Implement a Byte-Pair Encoding (BPE) tokenizer from scratch in Python; train it on a text corpus and visualize merge operations.", "subtopics": ["10.5.1 Tokenization paradigms: Character-level vs Word-level vs Subword tokenization (Byte-Pair Encoding, WordPiece, Unigram)", "10.5.2 Byte-Pair Encoding (BPE) algorithm: starting with single bytes, iteratively merging most frequent byte pairs into vocabulary", "10.5.3 Byte-level BPE: handling arbitrary Unicode characters without unknown token (`<unk>`) out-of-vocabulary fallbacks", "10.5.4 Tiktoken library internals: fast Rust-backed BPE tokenizer for OpenAI models (`cl100k_base`, `o200k_base`)", "10.5.5 Tokenization quirks and vulnerabilities: space prefix sensitivity, arithmetic failure modes (numbers split into uneven chunks)", "10.5.6 Financial cost and latency estimation: calculating token consumption formulas ($1\\text{ token} \\approx 0.75\\text{ words}$ in English; higher for code/non-English)"]}'::jsonb, '["Explain how this implementation prevents: Assuming 1 character = 1 token, underestimating API costs and context window consumption by 300% on multilingual text.", "How does Tokenization Mechanics: BPE, WordPiece, Tiktoken & Cost Math scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
