INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-7-11', 'phase-07-lesson-11-service-discovery-health-checks-client-si', 'module-10', 11, 'Lesson 10.11: Service Discovery, Health Checks & Client-Side Load Balancing', 'Prerequisites: Phase 4, Lesson 7.10', 'Prerequisites: Phase 4, Lesson 7.10 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 550.0, '# Lesson 7.11: Service Discovery, Health Checks & Client-Side Load Balancing

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 7.10
- **Subtopics**:
  - `7.11.1` Service discovery topologies: client-side discovery vs server-side discovery (API Gateways, Load Balancers)
  - `7.11.2` Registration lifecycles: heartbeat registrations, TTL-based deregulation, and graceful shutdown deregistration
  - `7.11.3` Health checking architectures: active liveness probes vs passive error-rate inspection, deep vs shallow checks
  - `7.11.4` Load balancing algorithms: Round Robin, Weighted Round Robin, Least Connections, and Peak EWMA (Exponentially Weighted Moving Average)
  - `7.11.5` Consistent Hashing: ring topologies, virtual nodes (vnodes), and minimizing key remapping during node scaling
  - `7.11.6` Client-side RPC load balancing: gRPC Subchannel management, name resolvers, and load-balancing policies
- **Key Failure Modes & Edge Cases**: Cascading failures triggered by deep health checks querying overloaded downstream databases, bringing down entire fleets.
- **Verification & Mastery Check**: Implement a Consistent Hashing ring with 256 virtual nodes per server; verify uniform distribution and minimal remapping upon node churn.
- **Project Application**: InfraBlueprint: High-throughput client-side load balancer.', '{"solution.py": "# Phase 7 // Lesson 7.11: Service Discovery, Health Checks & Client-Side Load Balancing\n\ndef solve():\n    \"\"\"\n    Verification: Implement a Consistent Hashing ring with 256 virtual nodes per server; verify uniform distribution a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.11", "subtopics_count": 6, "verification_criteria": "Implement a Consistent Hashing ring with 256 virtual nodes per server; verify uniform distribution and minimal remapping upon node churn.", "subtopics": ["7.11.1 Service discovery topologies: client-side discovery vs server-side discovery (API Gateways, Load Balancers)", "7.11.2 Registration lifecycles: heartbeat registrations, TTL-based deregulation, and graceful shutdown deregistration", "7.11.3 Health checking architectures: active liveness probes vs passive error-rate inspection, deep vs shallow checks", "7.11.4 Load balancing algorithms: Round Robin, Weighted Round Robin, Least Connections, and Peak EWMA (Exponentially Weighted Moving Average)", "7.11.5 Consistent Hashing: ring topologies, virtual nodes (vnodes), and minimizing key remapping during node scaling", "7.11.6 Client-side RPC load balancing: gRPC Subchannel management, name resolvers, and load-balancing policies"]}'::jsonb, '["Explain how this implementation prevents: Cascading failures triggered by deep health checks querying overloaded downstream databases, bringing down entire fleets", "How does Service Discovery, Health Checks & Client-Side Load Balancing scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-12', 'phase-07-lesson-12-resilience-engineering-circuit-breakers-b', 'module-10', 12, 'Lesson 10.12: Resilience Engineering: Circuit Breakers, Bulkheads & Backpressure', 'Prerequisites: Phase 4, Lesson 7.11', 'Prerequisites: Phase 4, Lesson 7.11 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 600.0, '# Lesson 7.12: Resilience Engineering: Circuit Breakers, Bulkheads & Backpressure

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4, Lesson 7.11
- **Subtopics**:
  - `7.12.1` Cascading failure mechanics: thread starvation, resource exhaustion, and queuing delay amplification
  - `7.12.2` Circuit Breaker pattern: Closed, Open, and Half-Open states, failure thresholds, and recovery trial windows
  - `7.12.3` Bulkhead pattern: isolating resource pools (thread pools, connection pools, CPU quotas) by service or tenant
  - `7.12.4` Backpressure mechanisms: TCP window flow control, reactive streams, and dropping requests with HTTP 429 / 503
  - `7.12.5` Rate limiting algorithms in distributed systems: Token Bucket, Leaky Bucket, Sliding Window Log, and Redis Lua scripts
  - `7.12.6` Dead-letter queues (DLQ): capturing failed message deliveries, poison pills, and automated replay workflows
- **Key Failure Modes & Edge Cases**: Thundering herd crashing a recovering service when an open circuit breaker abruptly transitions to closed.
- **Verification & Mastery Check**: Implement an asynchronous Circuit Breaker with exponential backoff and half-open trial concurrency limits.
- **Project Application**: InfraBlueprint: Microservice fault-tolerance middleware.', '{"solution.py": "# Phase 7 // Lesson 7.12: Resilience Engineering: Circuit Breakers, Bulkheads & Backpressure\n\ndef solve():\n    \"\"\"\n    Verification: Implement an asynchronous Circuit Breaker with exponential backoff and half-open trial concurrency l\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.12", "subtopics_count": 6, "verification_criteria": "Implement an asynchronous Circuit Breaker with exponential backoff and half-open trial concurrency limits.", "subtopics": ["7.12.1 Cascading failure mechanics: thread starvation, resource exhaustion, and queuing delay amplification", "7.12.2 Circuit Breaker pattern: Closed, Open, and Half-Open states, failure thresholds, and recovery trial windows", "7.12.3 Bulkhead pattern: isolating resource pools (thread pools, connection pools, CPU quotas) by service or tenant", "7.12.4 Backpressure mechanisms: TCP window flow control, reactive streams, and dropping requests with HTTP 429 / 503", "7.12.5 Rate limiting algorithms in distributed systems: Token Bucket, Leaky Bucket, Sliding Window Log, and Redis Lua scripts", "7.12.6 Dead-letter queues (DLQ): capturing failed message deliveries, poison pills, and automated replay workflows"]}'::jsonb, '["Explain how this implementation prevents: Thundering herd crashing a recovering service when an open circuit breaker abruptly transitions to closed.", "How does Resilience Engineering: Circuit Breakers, Bulkheads & Backpressure scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-13', 'phase-07-lesson-13-linux-containers-internals-namespaces-cgr', 'module-10', 13, 'Lesson 10.13: Linux Containers Internals: Namespaces, Cgroups & Rootfs', 'Prerequisites: Phase 0, Phase 5', 'Prerequisites: Phase 0, Phase 5 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 650.0, '# Lesson 7.13: Linux Containers Internals: Namespaces, Cgroups & Rootfs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Phase 5
- **Subtopics**:
  - `7.13.1` What a container really is: isolated Linux processes running under kernel namespaces and control groups
  - `7.13.2` Linux Namespaces: PID (process IDs), NET (network interfaces/routing), MNT (mount points), IPC, UTS, and USER namespaces
  - `7.13.3` Control Groups (cgroups v2): resource quotas for CPU (cpu.max), Memory (memory.max, OOM killer), and I/O (io.max)
  - `7.13.4` Root filesystem (rootfs) and UnionFS: OverlayFS architecture (lowerdir, upperdir, merged, workdir layers)
  - `7.13.5` Container security: dropping Linux capabilities (`cap_drop`), SecComp syscall filtering, and AppArmor profiles
  - `7.13.6` Building a container runtime from scratch in C/Python: `clone()` syscall with `CLONE_NEWPID`, `pivot_root`, and cgroup assignment
- **Key Failure Modes & Edge Cases**: Escaping container boundaries due to running as root with un-dropped capabilities (e.g. `CAP_SYS_ADMIN`).
- **Verification & Mastery Check**: Write a 150-line Python script that creates an isolated container environment using `unshare`, `pivot_root`, and cgroup v2 limits.
- **Project Application**: InfraBlueprint: Custom secure sandboxed container execution engine.', '{"solution.py": "# Phase 7 // Lesson 7.13: Linux Containers Internals: Namespaces, Cgroups & Rootfs\n\ndef solve():\n    \"\"\"\n    Verification: Write a 150-line Python script that creates an isolated container environment using `unshare`, `pivo\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.13", "subtopics_count": 6, "verification_criteria": "Write a 150-line Python script that creates an isolated container environment using `unshare`, `pivot_root`, and cgroup v2 limits.", "subtopics": ["7.13.1 What a container really is: isolated Linux processes running under kernel namespaces and control groups", "7.13.2 Linux Namespaces: PID (process IDs), NET (network interfaces/routing), MNT (mount points), IPC, UTS, and USER namespaces", "7.13.3 Control Groups (cgroups v2): resource quotas for CPU (cpu.max), Memory (memory.max, OOM killer), and I/O (io.max)", "7.13.4 Root filesystem (rootfs) and UnionFS: OverlayFS architecture (lowerdir, upperdir, merged, workdir layers)", "7.13.5 Container security: dropping Linux capabilities (`cap_drop`), SecComp syscall filtering, and AppArmor profiles", "7.13.6 Building a container runtime from scratch in C/Python: `clone()` syscall with `CLONE_NEWPID`, `pivot_root`, and cgroup assignment"]}'::jsonb, '["Explain how this implementation prevents: Escaping container boundaries due to running as root with un-dropped capabilities (e.g. `CAP_SYS_ADMIN`).", "How does Linux Containers Internals: Namespaces, Cgroups & Rootfs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-14', 'phase-07-lesson-14-container-images-oci-specification-secure', 'module-10', 14, 'Lesson 10.14: Container Images, OCI Specification & Secure Multi-Stage Builds', 'Prerequisites: Phase 5, Lesson 7.13', 'Prerequisites: Phase 5, Lesson 7.13 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 700.0, '# Lesson 7.14: Container Images, OCI Specification & Secure Multi-Stage Builds

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 5, Lesson 7.13
- **Subtopics**:
  - `7.14.1` Open Container Initiative (OCI) specification: image manifest, layer tarballs, config JSON, and runtime spec
  - `7.14.2` Docker build cache mechanics: layer hash invalidation, order of operations optimization, and buildkit improvements
  - `7.14.3` Multi-stage builds: separating build-time toolchains (compilers, SDKs) from lean runtime artifacts (distroless, scratch)
  - `7.14.4` Container supply chain security: vulnerability scanning with Trivy/Grype, CVE remediation, and non-root users
  - `7.14.5` Image signing and verification: Sigstore Cosign, cryptographic key pairs, and admissions controller policy enforcement
  - `7.14.6` Minimizing attack surface: stripping package managers, shells, and debugging binaries from production containers
- **Key Failure Modes & Edge Cases**: Baking AWS/GCP credentials or private SSH keys into intermediate Docker build layers; bloated 1.5GB production images.
- **Verification & Mastery Check**: Author an optimized multi-stage Dockerfile for a Go/Python service reducing final image size from 900MB to 18MB with 0 CVEs.
- **Project Application**: InfraBlueprint: Production container pipeline and image signing.', '{"solution.py": "# Phase 7 // Lesson 7.14: Container Images, OCI Specification & Secure Multi-Stage Builds\n\ndef solve():\n    \"\"\"\n    Verification: Author an optimized multi-stage Dockerfile for a Go/Python service reducing final image size from 90\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.14", "subtopics_count": 6, "verification_criteria": "Author an optimized multi-stage Dockerfile for a Go/Python service reducing final image size from 900MB to 18MB with 0 CVEs.", "subtopics": ["7.14.1 Open Container Initiative (OCI) specification: image manifest, layer tarballs, config JSON, and runtime spec", "7.14.2 Docker build cache mechanics: layer hash invalidation, order of operations optimization, and buildkit improvements", "7.14.3 Multi-stage builds: separating build-time toolchains (compilers, SDKs) from lean runtime artifacts (distroless, scratch)", "7.14.4 Container supply chain security: vulnerability scanning with Trivy/Grype, CVE remediation, and non-root users", "7.14.5 Image signing and verification: Sigstore Cosign, cryptographic key pairs, and admissions controller policy enforcement", "7.14.6 Minimizing attack surface: stripping package managers, shells, and debugging binaries from production containers"]}'::jsonb, '["Explain how this implementation prevents: Baking AWS/GCP credentials or private SSH keys into intermediate Docker build layers; bloated 1.5GB production images.", "How does Container Images, OCI Specification & Secure Multi-Stage Builds scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-15', 'phase-07-lesson-15-kubernetes-architecture-control-plane-int', 'module-10', 15, 'Lesson 10.15: Kubernetes Architecture & Control Plane Internals', 'Prerequisites: Lesson 7.10, Lesson 7.13', 'Prerequisites: Lesson 7.10, Lesson 7.13 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 750.0, '# Lesson 7.15: Kubernetes Architecture & Control Plane Internals

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.10, Lesson 7.13
- **Subtopics**:
  - `7.15.1` Kubernetes architectural philosophy: declarative desired state management vs imperative commands
  - `7.15.2` Control Plane components: kube-apiserver, etcd, kube-scheduler, and kube-controller-manager
  - `7.15.3` kube-apiserver deep dive: authentication, authorization (RBAC), admission control (validating/mutating webhooks), and storage in etcd
  - `7.15.4` kube-scheduler algorithms: filtering (predicates) and scoring (priorities), node affinity, taints, and tolerations
  - `7.15.5` kube-controller-manager: reconciliation control loops (Deployment, Node, ReplicaSet, EndpointSlice controllers)
  - `7.15.6` Worker Node components: kubelet, kube-proxy, and Container Runtime Interface (CRI) implementations (containerd)
- **Key Failure Modes & Edge Cases**: Mutating webhooks introducing deadlocks preventing cluster recovery; overloaded API server due to excessive unindexed watches.
- **Verification & Mastery Check**: Trace an end-to-end `kubectl apply` request through apiserver authentication, admission webhooks, etcd persistence, and scheduler binding.
- **Project Application**: InfraBlueprint: Production GKE cluster architecture.', '{"solution.py": "# Phase 7 // Lesson 7.15: Kubernetes Architecture & Control Plane Internals\n\ndef solve():\n    \"\"\"\n    Verification: Trace an end-to-end `kubectl apply` request through apiserver authentication, admission webhooks, et\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.15", "subtopics_count": 6, "verification_criteria": "Trace an end-to-end `kubectl apply` request through apiserver authentication, admission webhooks, etcd persistence, and scheduler binding.", "subtopics": ["7.15.1 Kubernetes architectural philosophy: declarative desired state management vs imperative commands", "7.15.2 Control Plane components: kube-apiserver, etcd, kube-scheduler, and kube-controller-manager", "7.15.3 kube-apiserver deep dive: authentication, authorization (RBAC), admission control (validating/mutating webhooks), and storage in etcd", "7.15.4 kube-scheduler algorithms: filtering (predicates) and scoring (priorities), node affinity, taints, and tolerations", "7.15.5 kube-controller-manager: reconciliation control loops (Deployment, Node, ReplicaSet, EndpointSlice controllers)", "7.15.6 Worker Node components: kubelet, kube-proxy, and Container Runtime Interface (CRI) implementations (containerd)"]}'::jsonb, '["Explain how this implementation prevents: Mutating webhooks introducing deadlocks preventing cluster recovery; overloaded API server due to excessive unindexed wa", "How does Kubernetes Architecture & Control Plane Internals scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-16', 'phase-07-lesson-16-kubernetes-core-workloads-pods-deployment', 'module-10', 16, 'Lesson 10.16: Kubernetes Core Workloads: Pods, Deployments & ReplicaSets', 'Prerequisites: Lesson 7.15', 'Prerequisites: Lesson 7.15 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 800.0, '# Lesson 7.16: Kubernetes Core Workloads: Pods, Deployments & ReplicaSets

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.15
- **Subtopics**:
  - `7.16.1` Pod lifecycle and phases: Pending, Running, Succeeded, Failed, Unknown, and container statuses
  - `7.16.2` Init containers vs application containers vs ephemeral debug containers: execution ordering and shared volumes
  - `7.16.3` Deployment reconciliation mechanics: ReplicaSet management, maxSurge, and maxUnavailable rolling update arithmetic
  - `7.16.4` Pod termination lifecycle: SIGTERM signal propagation, terminationGracePeriodSeconds, preStop hooks, and endpoint deregistration
  - `7.16.5` Liveness, Readiness, and Startup probes: failure thresholds, probe types (HTTP, Exec, gRPC), and restart loops
  - `7.16.6` Resource management: requests (scheduling baseline) vs limits (cgroup ceiling), CPU throttling, and Memory OOM-Kills (Exit Code 137)
- **Key Failure Modes & Edge Cases**: Readiness probe misconfigured as liveness probe triggering infinite restart cascades when services face temporary overload.
- **Verification & Mastery Check**: Deploy a zero-downtime rolling update deployment with calibrated preStop hooks and readiness probes passing load testing without dropped packets.
- **Project Application**: InfraBlueprint: Zero-downtime microservice workload manifests.', '{"solution.py": "# Phase 7 // Lesson 7.16: Kubernetes Core Workloads: Pods, Deployments & ReplicaSets\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a zero-downtime rolling update deployment with calibrated preStop hooks and readiness probes \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.16", "subtopics_count": 6, "verification_criteria": "Deploy a zero-downtime rolling update deployment with calibrated preStop hooks and readiness probes passing load testing without dropped packets.", "subtopics": ["7.16.1 Pod lifecycle and phases: Pending, Running, Succeeded, Failed, Unknown, and container statuses", "7.16.2 Init containers vs application containers vs ephemeral debug containers: execution ordering and shared volumes", "7.16.3 Deployment reconciliation mechanics: ReplicaSet management, maxSurge, and maxUnavailable rolling update arithmetic", "7.16.4 Pod termination lifecycle: SIGTERM signal propagation, terminationGracePeriodSeconds, preStop hooks, and endpoint deregistration", "7.16.5 Liveness, Readiness, and Startup probes: failure thresholds, probe types (HTTP, Exec, gRPC), and restart loops", "7.16.6 Resource management: requests (scheduling baseline) vs limits (cgroup ceiling), CPU throttling, and Memory OOM-Kills (Exit Code 137)"]}'::jsonb, '["Explain how this implementation prevents: Readiness probe misconfigured as liveness probe triggering infinite restart cascades when services face temporary overlo", "How does Kubernetes Core Workloads: Pods, Deployments & ReplicaSets scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-17', 'phase-07-lesson-17-kubernetes-advanced-workloads-statefulset', 'module-10', 17, 'Lesson 10.17: Kubernetes Advanced Workloads: StatefulSets, DaemonSets & Jobs', 'Prerequisites: Lesson 7.16', 'Prerequisites: Lesson 7.16 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 850.0, '# Lesson 7.17: Kubernetes Advanced Workloads: StatefulSets, DaemonSets & Jobs

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.16
- **Subtopics**:
  - `7.17.1` StatefulSet architecture: stable unique network identities (`pod-0`, `pod-1`), persistent storage binding (volumeClaimTemplates)
  - `7.17.2` StatefulSet ordering guarantees: ordered deployment, sequential rolling updates, and parallel pod management policies
  - `7.17.3` Headless Services (`clusterIP: None`): direct DNS SRV record resolution to individual stateful pod IP addresses
  - `7.17.4` DaemonSet architecture: scheduling exactly one pod per eligible node, hostPort/hostNetwork usage, and node taints bypass
  - `7.17.5` Jobs and CronJobs: batch execution, completions, parallelism, backoffLimit, and dead-lock prevention with activeDeadlineSeconds
  - `7.17.6` Pod disruption budgets (PDB): minAvailable vs maxUnavailable protecting stateful services during node draining and upgrades
- **Key Failure Modes & Edge Cases**: Deleting a StatefulSet pod expecting storage cleanup; running database replicas without Pod Disruption Budgets during node pools upgrades.
- **Verification & Mastery Check**: Deploy a 3-node clustered Raft/etcd service as a StatefulSet with automated headless DNS discovery and persistent volume claims.
- **Project Application**: InfraBlueprint: Clustered stateful database deployment on Kubernetes.', '{"solution.py": "# Phase 7 // Lesson 7.17: Kubernetes Advanced Workloads: StatefulSets, DaemonSets & Jobs\n\ndef solve():\n    \"\"\"\n    Verification: Deploy a 3-node clustered Raft/etcd service as a StatefulSet with automated headless DNS discovery a\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.17", "subtopics_count": 6, "verification_criteria": "Deploy a 3-node clustered Raft/etcd service as a StatefulSet with automated headless DNS discovery and persistent volume claims.", "subtopics": ["7.17.1 StatefulSet architecture: stable unique network identities (`pod-0`, `pod-1`), persistent storage binding (volumeClaimTemplates)", "7.17.2 StatefulSet ordering guarantees: ordered deployment, sequential rolling updates, and parallel pod management policies", "7.17.3 Headless Services (`clusterIP: None`): direct DNS SRV record resolution to individual stateful pod IP addresses", "7.17.4 DaemonSet architecture: scheduling exactly one pod per eligible node, hostPort/hostNetwork usage, and node taints bypass", "7.17.5 Jobs and CronJobs: batch execution, completions, parallelism, backoffLimit, and dead-lock prevention with activeDeadlineSeconds", "7.17.6 Pod disruption budgets (PDB): minAvailable vs maxUnavailable protecting stateful services during node draining and upgrades"]}'::jsonb, '["Explain how this implementation prevents: Deleting a StatefulSet pod expecting storage cleanup; running database replicas without Pod Disruption Budgets during no", "How does Kubernetes Advanced Workloads: StatefulSets, DaemonSets & Jobs scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-18', 'phase-07-lesson-18-kubernetes-networking-i-pod-to-pod-cni-cl', 'module-10', 18, 'Lesson 10.18: Kubernetes Networking I: Pod-to-Pod, CNI & ClusterIP', 'Prerequisites: Phase 0, Lesson 7.15', 'Prerequisites: Phase 0, Lesson 7.15 | Subtopics: 6 items', 'Systems project application', 240, 8, 1750.0, 900.0, '# Lesson 7.18: Kubernetes Networking I: Pod-to-Pod, CNI & ClusterIP

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 0, Lesson 7.15
- **Subtopics**:
  - `7.18.1` The Kubernetes networking model: every pod gets its own unique, routable IP address without NAT across nodes
  - `7.18.2` Container Network Interface (CNI): plugin architecture, Cilium (eBPF-based) vs Calico (BGP/iptables) vs GCP VPC-Native CNI
  - `7.18.3` Pod network namespaces and veth pairs: routing packets from container namespace into host bridge and physical interfaces
  - `7.18.4` Service abstraction mechanics: ClusterIP allocation, virtual IP ranges, and why ClusterIPs don''t respond to ICMP ping
  - `7.18.5` kube-proxy internals: iptables mode (linear chain traversal overhead) vs IPVS mode (hash tables) vs eBPF (direct socket routing)
  - `7.18.6` CoreDNS architecture: in-cluster DNS resolution, search paths (`ndots: 5` latency pitfall), and DNS caching
- **Key Failure Modes & Edge Cases**: Massive DNS latency amplification caused by `ndots: 5` appending search domains to external queries; iptables table exhaustion.
- **Verification & Mastery Check**: Inspect container veth pairs and host routing tables using `ip route` and `iptables-save`; trace a packet between pods across nodes.
- **Project Application**: InfraBlueprint: Cilium eBPF-powered Kubernetes network topology.', '{"solution.py": "# Phase 7 // Lesson 7.18: Kubernetes Networking I: Pod-to-Pod, CNI & ClusterIP\n\ndef solve():\n    \"\"\"\n    Verification: Inspect container veth pairs and host routing tables using `ip route` and `iptables-save`; trace a p\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.18", "subtopics_count": 6, "verification_criteria": "Inspect container veth pairs and host routing tables using `ip route` and `iptables-save`; trace a packet between pods across nodes.", "subtopics": ["7.18.1 The Kubernetes networking model: every pod gets its own unique, routable IP address without NAT across nodes", "7.18.2 Container Network Interface (CNI): plugin architecture, Cilium (eBPF-based) vs Calico (BGP/iptables) vs GCP VPC-Native CNI", "7.18.3 Pod network namespaces and veth pairs: routing packets from container namespace into host bridge and physical interfaces", "7.18.4 Service abstraction mechanics: ClusterIP allocation, virtual IP ranges, and why ClusterIPs don''t respond to ICMP ping", "7.18.5 kube-proxy internals: iptables mode (linear chain traversal overhead) vs IPVS mode (hash tables) vs eBPF (direct socket routing)", "7.18.6 CoreDNS architecture: in-cluster DNS resolution, search paths (`ndots: 5` latency pitfall), and DNS caching"]}'::jsonb, '["Explain how this implementation prevents: Massive DNS latency amplification caused by `ndots: 5` appending search domains to external queries; iptables table exha", "How does Kubernetes Networking I: Pod-to-Pod, CNI & ClusterIP scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-19', 'phase-07-lesson-19-kubernetes-networking-ii-nodeport-loadbal', 'module-10', 19, 'Lesson 10.19: Kubernetes Networking II: NodePort, LoadBalancer, Ingress & Gateway API', 'Prerequisites: Lesson 7.18', 'Prerequisites: Lesson 7.18 | Subtopics: 6 items', 'Systems project application', 240, 8, 1810.0, 950.0, '# Lesson 7.19: Kubernetes Networking II: NodePort, LoadBalancer, Ingress & Gateway API

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.18
- **Subtopics**:
  - `7.19.1` External traffic entrypoints: NodePort mechanics, high-port allocations (30000-32767), and `externalTrafficPolicy: Local` vs `Cluster`
  - `7.19.2` LoadBalancer services: cloud provider integration, cloud load balancer provisioning, and SNAT IP preservation
  - `7.19.3` Ingress controllers: NGINX Ingress vs Envoy-based Ingress, TLS termination, path-based and host-based routing rules
  - `7.19.4` Cert-Manager integration: automated ACME Let''s Encrypt TLS certificate provisioning and renewal via DNS-01/HTTP-01 challenges
  - `7.19.5` The Gateway API evolution: GatewayClass, Gateway, and HTTPRoute decoupling infrastructure provisioning from application routing
  - `7.19.6` Traffic shaping with Gateway API: header matching, traffic splitting (canary releases), and cross-namespace routing permissions
- **Key Failure Modes & Edge Cases**: `externalTrafficPolicy: Cluster` hiding client source IP addresses behind SNAT; Ingress controller regex routing collisions.
- **Verification & Mastery Check**: Configure a Gateway API setup with HTTPRoute performing 90/10 canary traffic splitting and automated Let''s Encrypt TLS termination.
- **Project Application**: InfraBlueprint: Gateway API ingress and canary routing infrastructure.', '{"solution.py": "# Phase 7 // Lesson 7.19: Kubernetes Networking II: NodePort, LoadBalancer, Ingress & Gateway API\n\ndef solve():\n    \"\"\"\n    Verification: Configure a Gateway API setup with HTTPRoute performing 90/10 canary traffic splitting and automated\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.19", "subtopics_count": 6, "verification_criteria": "Configure a Gateway API setup with HTTPRoute performing 90/10 canary traffic splitting and automated Let''s Encrypt TLS termination.", "subtopics": ["7.19.1 External traffic entrypoints: NodePort mechanics, high-port allocations (30000-32767), and `externalTrafficPolicy: Local` vs `Cluster`", "7.19.2 LoadBalancer services: cloud provider integration, cloud load balancer provisioning, and SNAT IP preservation", "7.19.3 Ingress controllers: NGINX Ingress vs Envoy-based Ingress, TLS termination, path-based and host-based routing rules", "7.19.4 Cert-Manager integration: automated ACME Let''s Encrypt TLS certificate provisioning and renewal via DNS-01/HTTP-01 challenges", "7.19.5 The Gateway API evolution: GatewayClass, Gateway, and HTTPRoute decoupling infrastructure provisioning from application routing", "7.19.6 Traffic shaping with Gateway API: header matching, traffic splitting (canary releases), and cross-namespace routing permissions"]}'::jsonb, '["Explain how this implementation prevents: `externalTrafficPolicy: Cluster` hiding client source IP addresses behind SNAT; Ingress controller regex routing collisi", "How does Kubernetes Networking II: NodePort, LoadBalancer, Ingress & Gateway API scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-7-20', 'phase-07-lesson-20-kubernetes-storage-csi-storageclasses-pvc', 'module-10', 20, 'Lesson 10.20: Kubernetes Storage: CSI, StorageClasses, PVCs & Dynamic Provisioning', 'Prerequisites: Lesson 7.17', 'Prerequisites: Lesson 7.17 | Subtopics: 6 items', 'Systems project application', 240, 8, 1870.0, 1000.0, '# Lesson 7.20: Kubernetes Storage: CSI, StorageClasses, PVCs & Dynamic Provisioning

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 7.17
- **Subtopics**:
  - `7.20.1` Container Storage Interface (CSI): plugin architecture, node-driver-registrar, csi-provisioner, and csi-attacher
  - `7.20.2` PersistentVolume (PV) vs PersistentVolumeClaim (PVC): declarative storage provisioning abstraction layer
  - `7.20.3` StorageClass mechanics: provisioners (e.g. `pd.csi.storage.gke.io`), volumeBindingMode (`WaitForFirstConsumer`), and reclaim policies
  - `7.20.4` Access modes: ReadWriteOnce (RWO), ReadOnlyMany (ROX), ReadWriteMany (RWX), and ReadWriteOncePod (RWOP)
  - `7.20.5` Volume volume lifecycle: provisioning, binding, attaching (to node), and mounting (into container mount namespace)
  - `7.20.6` Volume snapshots and resizing: CSISnapshot, online filesystem expansion, and backup automation
- **Key Failure Modes & Edge Cases**: Storage provisioned in an Availability Zone different from scheduled pod due to `volumeBindingMode: Immediate`.
- **Verification & Mastery Check**: Provision dynamic GCP Persistent Disk storage via CSI with `WaitForFirstConsumer` and perform an online volume expansion without pod restart.
- **Project Application**: InfraBlueprint: CSI dynamic storage infrastructure with automated snapshots.', '{"solution.py": "# Phase 7 // Lesson 7.20: Kubernetes Storage: CSI, StorageClasses, PVCs & Dynamic Provisioning\n\ndef solve():\n    \"\"\"\n    Verification: Provision dynamic GCP Persistent Disk storage via CSI with `WaitForFirstConsumer` and perform an onl\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "7.20", "subtopics_count": 6, "verification_criteria": "Provision dynamic GCP Persistent Disk storage via CSI with `WaitForFirstConsumer` and perform an online volume expansion without pod restart.", "subtopics": ["7.20.1 Container Storage Interface (CSI): plugin architecture, node-driver-registrar, csi-provisioner, and csi-attacher", "7.20.2 PersistentVolume (PV) vs PersistentVolumeClaim (PVC): declarative storage provisioning abstraction layer", "7.20.3 StorageClass mechanics: provisioners (e.g. `pd.csi.storage.gke.io`), volumeBindingMode (`WaitForFirstConsumer`), and reclaim policies", "7.20.4 Access modes: ReadWriteOnce (RWO), ReadOnlyMany (ROX), ReadWriteMany (RWX), and ReadWriteOncePod (RWOP)", "7.20.5 Volume volume lifecycle: provisioning, binding, attaching (to node), and mounting (into container mount namespace)", "7.20.6 Volume snapshots and resizing: CSISnapshot, online filesystem expansion, and backup automation"]}'::jsonb, '["Explain how this implementation prevents: Storage provisioned in an Availability Zone different from scheduled pod due to `volumeBindingMode: Immediate`.", "How does Kubernetes Storage: CSI, StorageClasses, PVCs & Dynamic Provisioning scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
