INSERT INTO curriculum_nodes (id, slug, phase_id, order_index, title, subtitle, cs_foundation, ai_convergence, xp_reward, level_required, position_x, position_y, handbook_markdown, starter_code, test_suite, defense_prompts) VALUES
('node-5-31', 'phase-05-lesson-31-serialization-anomaly-write-skew-in-pract', 'module-7', 31, 'Lesson 7.31: Serialization Anomaly & Write Skew in Practice', 'Prerequisites: Lesson 5.30', 'Prerequisites: Lesson 5.30 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 1550.0, '# Lesson 5.31: Serialization Anomaly & Write Skew in Practice

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.30
- **Subtopics**:
  - `5.31.1` Serialization Anomaly: concurrent transactions execute without serial equivalent ordering, violating business invariants.
  - `5.31.2` Write Skew anomaly: transactions read overlapping data sets, make disjoint writes, and violate a global constraint (e.g., on-call doctor shift minimum).
  - `5.31.3` Why `REPEATABLE READ` fails to prevent Write Skew: snapshot isolation only checks for conflicts on the *same* row.
  - `5.31.4` Resolving Write Skew: explicit locking (`SELECT FOR UPDATE`) or upgrading to `SERIALIZABLE` isolation.
- **Key Failure Modes & Edge Cases**: Double-booking hospital shifts or hotel rooms due to write skew under `REPEATABLE READ` isolation.
- **Verification & Mastery Check**: Write a Python script with two concurrent threads that triggers a Write Skew anomaly on a shared balance constraint.
- **Project Application**: AuthForge: Concurrency test suite.', '{"solution.py": "# Phase 5 // Lesson 5.31: Serialization Anomaly & Write Skew in Practice\n\ndef solve():\n    \"\"\"\n    Verification: Write a Python script with two concurrent threads that triggers a Write Skew anomaly on a shared bal\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.31", "subtopics_count": 4, "verification_criteria": "Write a Python script with two concurrent threads that triggers a Write Skew anomaly on a shared balance constraint.", "subtopics": ["5.31.1 Serialization Anomaly: concurrent transactions execute without serial equivalent ordering, violating business invariants.", "5.31.2 Write Skew anomaly: transactions read overlapping data sets, make disjoint writes, and violate a global constraint (e.g., on-call doctor shift minimum).", "5.31.3 Why `REPEATABLE READ` fails to prevent Write Skew: snapshot isolation only checks for conflicts on the *same* row.", "5.31.4 Resolving Write Skew: explicit locking (`SELECT FOR UPDATE`) or upgrading to `SERIALIZABLE` isolation."]}'::jsonb, '["Explain how this implementation prevents: Double-booking hospital shifts or hotel rooms due to write skew under `REPEATABLE READ` isolation.", "How does Serialization Anomaly & Write Skew in Practice scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-32', 'phase-05-lesson-32-the-four-ansi-sql-isolation-levels-in-pos', 'module-7', 32, 'Lesson 7.32: The Four ANSI SQL Isolation Levels in PostgreSQL', 'Prerequisites: Lesson 5.30, 5.31', 'Prerequisites: Lesson 5.30, 5.31 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 1600.0, '# Lesson 5.32: The Four ANSI SQL Isolation Levels in PostgreSQL

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.30, 5.31
- **Subtopics**:
  - `5.32.1` `READ UNCOMMITTED`: treated as `READ COMMITTED` in PostgreSQL (dirty reads are physically impossible under MVCC).
  - `5.32.2` `READ COMMITTED` (PostgreSQL default): each statement sees a new snapshot of committed data; non-repeatable reads possible.
  - `5.32.3` `REPEATABLE READ`: transaction sees a consistent snapshot taken at the beginning of the *transaction*; non-repeatable reads eliminated.
  - `5.32.4` `SERIALIZABLE`: Serializable Snapshot Isolation (SSI); tracks read-write dependencies (SIREAD locks); aborts conflicting transactions with `40001 serialization_failure`.
- **Key Failure Modes & Edge Cases**: Failing to implement retry loops in application code when running under `SERIALIZABLE` isolation, causing unhandled 40001 errors.
- **Verification & Mastery Check**: Implement a database transaction wrapper in Python that catches serialization failures and retries with exponential backoff.
- **Project Application**: AuthForge: Financial transaction logic.', '{"solution.py": "# Phase 5 // Lesson 5.32: The Four ANSI SQL Isolation Levels in PostgreSQL\n\ndef solve():\n    \"\"\"\n    Verification: Implement a database transaction wrapper in Python that catches serialization failures and retries w\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.32", "subtopics_count": 4, "verification_criteria": "Implement a database transaction wrapper in Python that catches serialization failures and retries with exponential backoff.", "subtopics": ["5.32.1 `READ UNCOMMITTED`: treated as `READ COMMITTED` in PostgreSQL (dirty reads are physically impossible under MVCC).", "5.32.2 `READ COMMITTED` (PostgreSQL default): each statement sees a new snapshot of committed data; non-repeatable reads possible.", "5.32.3 `REPEATABLE READ`: transaction sees a consistent snapshot taken at the beginning of the *transaction*; non-repeatable reads eliminated.", "5.32.4 `SERIALIZABLE`: Serializable Snapshot Isolation (SSI); tracks read-write dependencies (SIREAD locks); aborts conflicting transactions with `40001 serialization_failure`."]}'::jsonb, '["Explain how this implementation prevents: Failing to implement retry loops in application code when running under `SERIALIZABLE` isolation, causing unhandled 4000", "How does The Four ANSI SQL Isolation Levels in PostgreSQL scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-33', 'phase-05-lesson-33-explicit-locking-row-locks-table-locks-sk', 'module-7', 33, 'Lesson 7.33: Explicit Locking: Row Locks, Table Locks, & `SKIP LOCKED`', 'Prerequisites: Phase 4 (Lesson 4.12), Lesson 5.32', 'Prerequisites: Phase 4 (Lesson 4.12), Lesson 5.32 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 1650.0, '# Lesson 5.33: Explicit Locking: Row Locks, Table Locks, & `SKIP LOCKED`

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4 (Lesson 4.12), Lesson 5.32
- **Subtopics**:
  - `5.33.1` Row-level locking: `SELECT ... FOR UPDATE` (exclusive lock) and `SELECT ... FOR SHARE` (shared lock).
  - `5.33.2` Non-blocking locking: `NOWAIT` (fails immediately if row is locked) vs `SKIP LOCKED` (skips locked rows).
  - `5.33.3` Building High-Performance Queues in PostgreSQL: `SELECT id FROM tasks WHERE status = ''pending'' ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1`.
  - `5.33.4` Table locks: `ACCESS SHARE`, `ROW SHARE`, `EXCLUSIVE`, `ACCESS EXCLUSIVE`; lock conflict matrices.
- **Key Failure Modes & Edge Cases**: Deadlocks caused by workers locking task rows without `SKIP LOCKED`, stalling queue throughput.
- **Verification & Mastery Check**: Build a multi-worker job queue on PostgreSQL using `FOR UPDATE SKIP LOCKED` and verify zero duplicate task processing.
- **Project Application**: SchemaVault and Celery queues.', '{"solution.py": "# Phase 5 // Lesson 5.33: Explicit Locking: Row Locks, Table Locks, & `SKIP LOCKED`\n\ndef solve():\n    \"\"\"\n    Verification: Build a multi-worker job queue on PostgreSQL using `FOR UPDATE SKIP LOCKED` and verify zero duplicat\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.33", "subtopics_count": 4, "verification_criteria": "Build a multi-worker job queue on PostgreSQL using `FOR UPDATE SKIP LOCKED` and verify zero duplicate task processing.", "subtopics": ["5.33.1 Row-level locking: `SELECT ... FOR UPDATE` (exclusive lock) and `SELECT ... FOR SHARE` (shared lock).", "5.33.2 Non-blocking locking: `NOWAIT` (fails immediately if row is locked) vs `SKIP LOCKED` (skips locked rows).", "5.33.3 Building High-Performance Queues in PostgreSQL: `SELECT id FROM tasks WHERE status = ''pending'' ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1`.", "5.33.4 Table locks: `ACCESS SHARE`, `ROW SHARE`, `EXCLUSIVE`, `ACCESS EXCLUSIVE`; lock conflict matrices."]}'::jsonb, '["Explain how this implementation prevents: Deadlocks caused by workers locking task rows without `SKIP LOCKED`, stalling queue throughput.", "How does Explicit Locking: Row Locks, Table Locks, & `SKIP LOCKED` scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-34', 'phase-05-lesson-34-multi-version-concurrency-control-mvcc-ar', 'module-7', 34, 'Lesson 7.34: Multi-Version Concurrency Control (MVCC) Architecture', 'Prerequisites: Lesson 5.23, 5.32', 'Prerequisites: Lesson 5.23, 5.32 | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 1700.0, '# Lesson 5.34: Multi-Version Concurrency Control (MVCC) Architecture

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.23, 5.32
- **Subtopics**:
  - `5.34.1` The core MVCC guarantee: readers never block writers, and writers never block readers.
  - `5.34.2` Tuple versioning: updates create a new tuple version; deletes mark tuple as expired.
  - `5.34.3` Transaction snapshots: tracking `xmin` (inserting TXID), `xmax` (deleting/updating TXID), and active transaction arrays.
  - `5.34.4` Snapshot visibility rules: determining whether a tuple version is visible to a running query.
- **Key Failure Modes & Edge Cases**: Long-running analytic queries holding snapshots open, preventing vacuuming and causing massive table bloat.
- **Verification & Mastery Check**: Inspect hidden `xmin` and `xmax` fields on active tables across concurrent transactions.
- **Project Application**: PostgreSQL engine mastery.', '{"solution.py": "# Phase 5 // Lesson 5.34: Multi-Version Concurrency Control (MVCC) Architecture\n\ndef solve():\n    \"\"\"\n    Verification: Inspect hidden `xmin` and `xmax` fields on active tables across concurrent transactions.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.34", "subtopics_count": 4, "verification_criteria": "Inspect hidden `xmin` and `xmax` fields on active tables across concurrent transactions.", "subtopics": ["5.34.1 The core MVCC guarantee: readers never block writers, and writers never block readers.", "5.34.2 Tuple versioning: updates create a new tuple version; deletes mark tuple as expired.", "5.34.3 Transaction snapshots: tracking `xmin` (inserting TXID), `xmax` (deleting/updating TXID), and active transaction arrays.", "5.34.4 Snapshot visibility rules: determining whether a tuple version is visible to a running query."]}'::jsonb, '["Explain how this implementation prevents: Long-running analytic queries holding snapshots open, preventing vacuuming and causing massive table bloat.", "How does Multi-Version Concurrency Control (MVCC) Architecture scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-35', 'phase-05-lesson-35-dead-tuples-table-bloat-the-vacuum-engine', 'module-7', 35, 'Lesson 7.35: Dead Tuples, Table Bloat, & The VACUUM Engine', 'Prerequisites: Lesson 5.34', 'Prerequisites: Lesson 5.34 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 1750.0, '# Lesson 5.35: Dead Tuples, Table Bloat, & The VACUUM Engine

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.34
- **Subtopics**:
  - `5.35.1` Dead Tuples: expired tuple versions that are no longer visible to any active transaction.
  - `5.35.2` Measuring bloat: `pg_stat_user_tables.n_dead_tup` and dead-to-live tuple ratios.
  - `5.35.3` Standard `VACUUM`: marks dead tuple space as reusable in the Free Space Map (FSM); does NOT shrink table file on disk.
  - `5.35.4` `VACUUM FULL`: acquires exclusive table lock, rewrites table into a compact file; emergency bloat remediation.
- **Key Failure Modes & Edge Cases**: Table files consuming 500GB disk space for 10GB of real data due to dead tuple bloat from un-vacuumed updates.
- **Verification & Mastery Check**: Generate 100,000 updates, monitor dead tuple accumulation, execute `VACUUM`, and inspect the Free Space Map.
- **Project Application**: SchemaVault: Database maintenance procedures.', '{"solution.py": "# Phase 5 // Lesson 5.35: Dead Tuples, Table Bloat, & The VACUUM Engine\n\ndef solve():\n    \"\"\"\n    Verification: Generate 100,000 updates, monitor dead tuple accumulation, execute `VACUUM`, and inspect the Free Sp\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.35", "subtopics_count": 4, "verification_criteria": "Generate 100,000 updates, monitor dead tuple accumulation, execute `VACUUM`, and inspect the Free Space Map.", "subtopics": ["5.35.1 Dead Tuples: expired tuple versions that are no longer visible to any active transaction.", "5.35.2 Measuring bloat: `pg_stat_user_tables.n_dead_tup` and dead-to-live tuple ratios.", "5.35.3 Standard `VACUUM`: marks dead tuple space as reusable in the Free Space Map (FSM); does NOT shrink table file on disk.", "5.35.4 `VACUUM FULL`: acquires exclusive table lock, rewrites table into a compact file; emergency bloat remediation."]}'::jsonb, '["Explain how this implementation prevents: Table files consuming 500GB disk space for 10GB of real data due to dead tuple bloat from un-vacuumed updates.", "How does Dead Tuples, Table Bloat, & The VACUUM Engine scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-36', 'phase-05-lesson-36-autovacuum-architecture-freezing-wraparou', 'module-7', 36, 'Lesson 7.36: Autovacuum Architecture, Freezing, & Wraparound Catastrophe', 'Prerequisites: Lesson 5.35', 'Prerequisites: Lesson 5.35 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 1800.0, '# Lesson 5.36: Autovacuum Architecture, Freezing, & Wraparound Catastrophe

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.35
- **Subtopics**:
  - `5.36.1` Autovacuum daemon: background workers continuously monitoring table modification thresholds.
  - `5.36.2` Tuning autovacuum: `autovacuum_vacuum_scale_factor`, `autovacuum_vacuum_cost_limit`.
  - `5.36.3` The 32-bit Transaction ID (TXID) Wraparound: why TXIDs wrap around after ~2 billion transactions.
  - `5.36.4` Tuple Freezing: setting the `frozen` bit on tuples to mark them as older than all past and future TXIDs; preventing data invisibility.
- **Key Failure Modes & Edge Cases**: PostgreSQL entering emergency read-only shutdown mode because autovacuum was disabled and TXID wraparound threshold was reached.
- **Verification & Mastery Check**: Inspect table ages with `pg_class.relfrozenxid` and calculate distance to wraparound threshold.
- **Project Application**: InfraBlueprint: Production Cloud SQL operations.', '{"solution.py": "# Phase 5 // Lesson 5.36: Autovacuum Architecture, Freezing, & Wraparound Catastrophe\n\ndef solve():\n    \"\"\"\n    Verification: Inspect table ages with `pg_class.relfrozenxid` and calculate distance to wraparound threshold.\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.36", "subtopics_count": 4, "verification_criteria": "Inspect table ages with `pg_class.relfrozenxid` and calculate distance to wraparound threshold.", "subtopics": ["5.36.1 Autovacuum daemon: background workers continuously monitoring table modification thresholds.", "5.36.2 Tuning autovacuum: `autovacuum_vacuum_scale_factor`, `autovacuum_vacuum_cost_limit`.", "5.36.3 The 32-bit Transaction ID (TXID) Wraparound: why TXIDs wrap around after ~2 billion transactions.", "5.36.4 Tuple Freezing: setting the `frozen` bit on tuples to mark them as older than all past and future TXIDs; preventing data invisibility."]}'::jsonb, '["Explain how this implementation prevents: PostgreSQL entering emergency read-only shutdown mode because autovacuum was disabled and TXID wraparound threshold was ", "How does Autovacuum Architecture, Freezing, & Wraparound Catastrophe scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-37', 'phase-05-lesson-37-postgresql-row-level-security-rls-for-mul', 'module-7', 37, 'Lesson 7.37: PostgreSQL Row-Level Security (RLS) for Multi-Tenancy', 'Prerequisites: Lesson 5.15', 'Prerequisites: Lesson 5.15 | Subtopics: 5 items', 'Systems project application', 200, 6, 1310.0, 1850.0, '# Lesson 5.37: PostgreSQL Row-Level Security (RLS) for Multi-Tenancy

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.15
- **Subtopics**:
  - `5.37.1` Multi-tenancy models: Database-per-tenant vs Schema-per-tenant vs Shared-database with Tenant ID.
  - `5.37.2` Row-Level Security (RLS): database-level policy enforcement preventing cross-tenant data access.
  - `5.37.3` Enabling RLS: `ALTER TABLE documents ENABLE ROW LEVEL SECURITY;`.
  - `5.37.4` Policy creation: `CREATE POLICY tenant_isolation ON documents USING (tenant_id = current_setting(''app.current_tenant'')::uuid);`.
  - `5.37.5` Session configuration: `SET LOCAL app.current_tenant = :tenant_id;` inside transactions.
- **Key Failure Modes & Edge Cases**: Relying on application-level `WHERE tenant_id = :id` filters, where a single forgotten filter exposes all customer data.
- **Verification & Mastery Check**: Implement a complete multi-tenant database schema in PostgreSQL enforced by RLS, proving cross-tenant data leakage is impossible.
- **Project Application**: TenantIQ: Core multi-tenant isolation architecture.', '{"solution.py": "# Phase 5 // Lesson 5.37: PostgreSQL Row-Level Security (RLS) for Multi-Tenancy\n\ndef solve():\n    \"\"\"\n    Verification: Implement a complete multi-tenant database schema in PostgreSQL enforced by RLS, proving cross-tenan\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.37", "subtopics_count": 5, "verification_criteria": "Implement a complete multi-tenant database schema in PostgreSQL enforced by RLS, proving cross-tenant data leakage is impossible.", "subtopics": ["5.37.1 Multi-tenancy models: Database-per-tenant vs Schema-per-tenant vs Shared-database with Tenant ID.", "5.37.2 Row-Level Security (RLS): database-level policy enforcement preventing cross-tenant data access.", "5.37.3 Enabling RLS: `ALTER TABLE documents ENABLE ROW LEVEL SECURITY;`.", "5.37.4 Policy creation: `CREATE POLICY tenant_isolation ON documents USING (tenant_id = current_setting(''app.current_tenant'')::uuid);`.", "5.37.5 Session configuration: `SET LOCAL app.current_tenant = :tenant_id;` inside transactions."]}'::jsonb, '["Explain how this implementation prevents: Relying on application-level `WHERE tenant_id = :id` filters, where a single forgotten filter exposes all customer data.", "How does PostgreSQL Row-Level Security (RLS) for Multi-Tenancy scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-38', 'phase-05-lesson-38-postgresql-process-per-connection-overhea', 'module-7', 38, 'Lesson 7.38: PostgreSQL Process-per-Connection Overhead & Resource Limits', 'Prerequisites: Phase 4 (Lesson 4.1), Lesson 5.34', 'Prerequisites: Phase 4 (Lesson 4.1), Lesson 5.34 | Subtopics: 4 items', 'Systems project application', 200, 6, 1370.0, 1900.0, '# Lesson 5.38: PostgreSQL Process-per-Connection Overhead & Resource Limits

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4 (Lesson 4.1), Lesson 5.34
- **Subtopics**:
  - `5.38.1` Process-based connection model: each client connection forks a dedicated backend process consuming ~5–10MB RAM.
  - `5.38.2` Connection creation latency: TCP + TLS + process fork + authentication taking 30ms–50ms.
  - `5.38.3` Connection saturation: why 500 concurrent direct connections degrade CPU performance through context switching thrashing.
  - `5.38.4` The `max_connections` setting: sizing formula: `connections = ((core_count * 2) + effective_spindle_count)`.
- **Key Failure Modes & Edge Cases**: Spawning 1,000 container instances each configured with a connection pool of 20, crushing PostgreSQL with 20,000 connections.
- **Verification & Mastery Check**: Benchmark query throughput against direct PostgreSQL connections as connection count scales from 10 to 1,000.
- **Project Application**: InfraBlueprint: Database capacity sizing.', '{"solution.py": "# Phase 5 // Lesson 5.38: PostgreSQL Process-per-Connection Overhead & Resource Limits\n\ndef solve():\n    \"\"\"\n    Verification: Benchmark query throughput against direct PostgreSQL connections as connection count scales from 10 \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.38", "subtopics_count": 4, "verification_criteria": "Benchmark query throughput against direct PostgreSQL connections as connection count scales from 10 to 1,000.", "subtopics": ["5.38.1 Process-based connection model: each client connection forks a dedicated backend process consuming ~5\u201310MB RAM.", "5.38.2 Connection creation latency: TCP + TLS + process fork + authentication taking 30ms\u201350ms.", "5.38.3 Connection saturation: why 500 concurrent direct connections degrade CPU performance through context switching thrashing.", "5.38.4 The `max_connections` setting: sizing formula: `connections = ((core_count * 2) + effective_spindle_count)`."]}'::jsonb, '["Explain how this implementation prevents: Spawning 1,000 container instances each configured with a connection pool of 20, crushing PostgreSQL with 20,000 connect", "How does PostgreSQL Process-per-Connection Overhead & Resource Limits scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-39', 'phase-05-lesson-39-pgbouncer-architecture-pooling-modes', 'module-7', 39, 'Lesson 7.39: PgBouncer Architecture & Pooling Modes', 'Prerequisites: Lesson 5.38', 'Prerequisites: Lesson 5.38 | Subtopics: 4 items', 'Systems project application', 200, 6, 1250.0, 1950.0, '# Lesson 5.39: PgBouncer Architecture & Pooling Modes

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Lesson 5.38
- **Subtopics**:
  - `5.39.1` PgBouncer proxy: lightweight connection pooler managing thousands of client connections with minimal overhead.
  - `5.39.2` Session Pooling: server connection assigned to client until disconnect (minimal pooling advantage).
  - `5.39.3` Transaction Pooling (Production Standard): server connection returned to pool immediately upon transaction commit/rollback.
  - `5.39.4` Statement Pooling: connection returned after every statement (breaks multi-statement transactions; rarely used).
- **Key Failure Modes & Edge Cases**: Attempting to use session-level features (`SET timezone`, prepared statements, temporary tables) under Transaction Pooling.
- **Verification & Mastery Check**: Deploy PgBouncer in Docker, configure Transaction Pooling, and demonstrate 5,000 client connections served by 20 PostgreSQL backends.
- **Project Application**: InfraBlueprint: Database proxy deployment.', '{"solution.py": "# Phase 5 // Lesson 5.39: PgBouncer Architecture & Pooling Modes\n\ndef solve():\n    \"\"\"\n    Verification: Deploy PgBouncer in Docker, configure Transaction Pooling, and demonstrate 5,000 client connections \n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.39", "subtopics_count": 4, "verification_criteria": "Deploy PgBouncer in Docker, configure Transaction Pooling, and demonstrate 5,000 client connections served by 20 PostgreSQL backends.", "subtopics": ["5.39.1 PgBouncer proxy: lightweight connection pooler managing thousands of client connections with minimal overhead.", "5.39.2 Session Pooling: server connection assigned to client until disconnect (minimal pooling advantage).", "5.39.3 Transaction Pooling (Production Standard): server connection returned to pool immediately upon transaction commit/rollback.", "5.39.4 Statement Pooling: connection returned after every statement (breaks multi-statement transactions; rarely used)."]}'::jsonb, '["Explain how this implementation prevents: Attempting to use session-level features (`SET timezone`, prepared statements, temporary tables) under Transaction Pooli", "How does PgBouncer Architecture & Pooling Modes scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb),
('node-5-40', 'phase-05-lesson-40-grpc-health-checking-protocol-kubernetes-', 'module-7', 40, 'Lesson 7.40: gRPC Health Checking Protocol & Kubernetes Integration', 'Prerequisites: Phase 4 (Lesson 4.29)', 'Prerequisites: Phase 4 (Lesson 4.29) | Subtopics: 4 items', 'Systems project application', 200, 6, 1310.0, 2000.0, '# Lesson 5.40: gRPC Health Checking Protocol & Kubernetes Integration

- **Status**: `[State: Active | Complete Specification | Core]`
- **Prerequisites**: Phase 4 (Lesson 4.29)
- **Subtopics**:
  - `5.40.1` The gRPC Health Checking Protocol standard: `grpc.health.v1.Health` service definition.
  - `5.40.2` RPC methods: `Check(HealthCheckRequest)` (unary check) and `Watch(HealthCheckRequest)` (streaming status updates).
  - `5.40.3` Health status states: `UNKNOWN`, `SERVING`, `NOT_SERVING`, `SERVICE_UNKNOWN`.
  - `5.40.4` Container lifecycle probing: using the `grpc_health_probe` binary inside Kubernetes liveness and readiness probes.
- **Key Failure Modes & Edge Cases**: Kubernetes killing healthy gRPC containers because naive HTTP health probes fail on gRPC HTTP/2 ports.
- **Verification & Mastery Check**: Implement `grpc.health.v1.Health` in Python/gRPC, and verify health probing using `grpc_health_probe` CLI binary.
- **Project Application**: AuthForge and InfraBlueprint: Kubernetes health checks.', '{"solution.py": "# Phase 5 // Lesson 5.40: gRPC Health Checking Protocol & Kubernetes Integration\n\ndef solve():\n    \"\"\"\n    Verification: Implement `grpc.health.v1.Health` in Python/gRPC, and verify health probing using `grpc_health_probe\n    \"\"\"\n    pass\n"}'::jsonb, '{"lesson": "5.40", "subtopics_count": 4, "verification_criteria": "Implement `grpc.health.v1.Health` in Python/gRPC, and verify health probing using `grpc_health_probe` CLI binary.", "subtopics": ["5.40.1 The gRPC Health Checking Protocol standard: `grpc.health.v1.Health` service definition.", "5.40.2 RPC methods: `Check(HealthCheckRequest)` (unary check) and `Watch(HealthCheckRequest)` (streaming status updates).", "5.40.3 Health status states: `UNKNOWN`, `SERVING`, `NOT_SERVING`, `SERVICE_UNKNOWN`.", "5.40.4 Container lifecycle probing: using the `grpc_health_probe` binary inside Kubernetes liveness and readiness probes."]}'::jsonb, '["Explain how this implementation prevents: Kubernetes killing healthy gRPC containers because naive HTTP health probes fail on gRPC HTTP/2 ports.", "How does gRPC Health Checking Protocol & Kubernetes Integration scale under memory and concurrency constraints?", "Defend the architectural tradeoffs of this design in production."]'::jsonb)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, phase_id = EXCLUDED.phase_id, order_index = EXCLUDED.order_index, title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, cs_foundation = EXCLUDED.cs_foundation, ai_convergence = EXCLUDED.ai_convergence, xp_reward = EXCLUDED.xp_reward, level_required = EXCLUDED.level_required, position_x = EXCLUDED.position_x, position_y = EXCLUDED.position_y, handbook_markdown = EXCLUDED.handbook_markdown, starter_code = EXCLUDED.starter_code, test_suite = EXCLUDED.test_suite, defense_prompts = EXCLUDED.defense_prompts;
